### ISSUE TITLE
Removal of Type-specific timing names

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#100]
Currently there are multiple names for some of the AI timing hints, is there a reason that the AI needs to know about an 'Artifact' timing and not 'Creature'? - If type is relevant, checking the cards type would make more sense.

Most type-timings are main, except for tapland which is fmain. Being able to streamline these would aid in scripting, thinking more on when it should be cast instead of what it is.

**Comment by melvinzhang** [comment]
The timing is the same but the priority is different. Artifact is priority 4 while Aura/Equipment is priority 7

**Comment by ShawnieBoy** [comment]
Thanks, I didn't realise there was a separate priority rating.  I can see it now. Is a higher rating the higher priority?

**Comment by ShawnieBoy** [comment]
>Is a higher rating the higher priority?
I'm guessing that it is, if so it would seem as though playing land has a priority of 1 - Would be good if there was some way of having this priority dynamically generated against the number of lands on the battlefield and the max casting cost in hand/deck.

**Comment by melvinzhang** [comment]
priority means within the same phase, cards with smaller priority are played first.

**Comment by ShawnieBoy** [comment]
I see, that makes more sense now. It's essentially functioning as a way of filtering out cards from the hand to consider.

**Comment by melvinzhang** [comment]
Right, so during it's priority, the AI doesn't have to consider all possible order of cards/abilities. Though this also rules out certain combos that require activating abilities in a particular order sequence. So it is not certain if the priority system is a net benefit. Something to be tested out in AI rating matches.

**Comment by ShawnieBoy** [comment]
Would be interesting to see if there is much change in behaviour without priority involved, much of the restrictions are already placed on phases of a turn.

**Comment by melvinzhang** [comment]
I see the two as orthogonal: timing limits when to play, priority limits in what order to play

**Comment by ShawnieBoy** [comment]
Order of play in my eyes, would depend more on what the battlefield/stack contains instead of what a card's priority is (generally based on card type).

I would guess that the AI would function similarly without the priority - but would be interesting to see.

**Comment by melvinzhang** [comment]
Its one of those consider more options but reduce look ahead vs limit the options and increase the look ahead type trade-offs. Uncertain how it will be, likely to depend on the type of deck being played and the game states involved. I intend to allow AI to turn off the priority system.

**Comment by melvinzhang** [comment]
Type specific hints include priority.
