### ISSUE TITLE
AI opponent's hand can be seen by the human player

### ISSUE THREAD

**Issue by Agetian** [magarena/magarena#1000]
In Magarena 1.79, it's always possible to see what is in the AI opponent's hand by clicking the hand icon next to the AI opponent's icon. Not sure if this is intentional, but it feels quite odd, and I haven't found an option to disable/enable this behavior.

**Comment by ShawnieBoy** [comment]
I think it was included as the 'S' shortcut wasn't widely known. It is mainly for examining 'why did the AI do that' in case of possible bad plays.
It is a bit of a test of self-control though! I think @lodici included those instances of 'cheating' in the profile stats. There could be a way of disabling it though, or only having it active in dev-mode, as our game-reports include the contents of the AI's hand.

**Comment by Agetian** [comment]
Ah, this makes sense! Thanks for the clarification.

**Comment by lodici** [comment]
This is already on the todo list and has been for quite a while! First raised as #217.
