### ISSUE TITLE
Simplify/Enable addition of custom cards

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#1005]
Raised on [forums](http://www.slightlymagic.net/forum/viewtopic.php?f=82&t=3700&start=210#p206372)

Currently to add new cards to the game, the AllCardNames.txt file needs to be updated to include the card names. This is the only file that would need adjusting to enable adding custom cards. Would this be possible to be included in the install and referred as a separate file?

**Comment by melvinzhang** [comment]
AllCardNames.txt is only used in getMissingCardNames() to determine the list of missing cards without going though the cards in scripts_missing folder. It does not have to be modified to add custom cards, as usual just drop the custom card in scripts and add them to you deck and it will work.

**Comment by ShawnieBoy** [comment]
Oh, I thought that the Card Explorer used it

**Comment by melvinzhang** [comment]
It does as it uses getMissingCardNames() to generate the entries of missing cards (greyed out) in the card pool. If "show unimplemented cards data" is enabled, it ignores the missing card names and just load all the scripts in scripts_missing, otherwise it generates a blank card definition using just the name.

**Comment by ShawnieBoy** [comment]
Ahh, yes - was remembering it the wrong way round. When the names of cards for a set were included before scripts were done.  That's good news then 😃 Thanks for clarifying

**Comment by melvinzhang** [comment]
Hmm, actually a better file would be just MissingCardNames.txt that contains just the names of the missing cards, rather than use AllCardNames.txt and then remove the cards in scripts to get the missing one.

**Comment by ShawnieBoy** [comment]
Wouldn't that need more maintenance though, than just including all cards?

**Comment by melvinzhang** [comment]
True, it would need to change in each release rather than each set release.  showMissingCardData defaults to true so most of the time, AllCardNames.txt is loaded and never used. Perhaps just fix that option as true? The number of missing cards is less than half of the implemented cards.

**Comment by ShawnieBoy** [comment]
That makes sense, saves loading something that isn't used.

> The number of missing cards is less than half of the implemented cards.

I like hearing that.

**Comment by melvinzhang** [comment]
Which is better though? 

1. Leave the option there "show missing cards" in preferences and not show missing cards when it is off 

2. Remove the option, behave as though that option is true (which is the default value in new install).

**Comment by ShawnieBoy** [comment]
Difficult to say without user feedback - Although it would only appear in card explorer, and they can be filtered out with the show implemented filter.

I'd probably go for option 2 myself as I always have them shown

**Comment by melvinzhang** [comment]
I think it is good to show missing cards, perhaps seeing them will inspire some users to craft card scripts. Will take 2 then, it is less of a change as enabled is the default.

**Comment by ShawnieBoy** [comment]
Had a shock and realised I'd been using AllCardNames.txt for the purpose of reparsing the scripts - managed to pull the last used copy - maybe a dev-mode 'create all cards in magarena' button similar to 'create cards missing in magarena'
