### ISSUE TITLE
Status=not supported: becomes-copy

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#1013]
I may be missing something here, but I would have thought that permanents that become a copy of another permanent would be possible in groovy code. (Not easy, but still do-able).

In a way it would be easier than `enters the battlefield as a copy` as there's no need to worry about any triggered abilities which rely on the permanent's properties.

**Comment by melvinzhang** [comment]
There is no way to do this in groovy code. For example, the name of a permanent cannot be changed once it is created.
