### ISSUE TITLE
Test class starting phase confusion.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#1025]
When I run ``TestBloodArtistWrath`` it always runs to DA and stops. It is set to start at [MagicMainPhase.getFirstInstance()](https://github.com/magarena/magarena/blob/master/src/magic/test/TestBloodArtistWrath.java#L12) but even if I set it to ``MagicDrawPhase.getInstance()`` it stills runs to DA. Only if I set the phase to ``MagicUntapPhase.getInstance()`` will it actually stop at M1. Should it not start _and wait_ at the starting phase?

**Comment by ShawnieBoy** [comment]
It would only stop during a phase if the player can act in that phase. As you have no mana, there's nothing you can do during your main phase.

**Comment by lodici** [comment]
Thanks, you are quite right. I thought the lands were untapped but they are not, which is why it works if I start from ``MagicUntapPhase.getInstance()``. _Must pay more attention to what I am looking at!_

**Comment by ShawnieBoy** [comment]
All the Rupture Spires enter the battlefield tapped - regarless of the tap setting given to them. When you start at the Untap phase, they get untapped so you can cast things. One of the quirks with the test classes.

**Comment by ShawnieBoy** [comment]
I try not to use lands that enter the battlefield tapped in test classes - might be worth editing them all out.

**Comment by ShawnieBoy** [comment]
The defaults for createPermanent are untapped with a quantity of 1. addTo< location > all default to 1 as well, so they don't need to be defined unless they're different states/amounts.

**Comment by lodici** [comment]
> I try not to use lands that enter the battlefield tapped in test classes - might be worth editing them all out.

I don't want to mess around with the tests since it is not really my area, I just assume there must be a reason why the lands are initially all tapped. I guess it depends on why the test was originally created. It was my bad really.

**Comment by lodici** [comment]
Perhaps it would be useful to add a a header comment block to each test class explaining what feature is being put through it paces. There is only so much you can convey in a filename after all.
