### ISSUE TITLE
OSX ... crashed first time I tried to play

### ISSUE THREAD

**Issue by tleeuwenburg** [magarena/magarena#1026]
#### Crash report
I ran the game for the first time, tried to start a new duel with a random deck. As soon as the duel started, the game crashed. 
[crash.log.txt](https://github.com/magarena/magarena/files/698628/crash.log.txt)

---

**Comment by tleeuwenburg** [comment]
I was able to restart the duel, and it seems to be working fine thereafter

**Comment by lodici** [comment]
Thanks for the crash report. I will close this as it has already been raised in #685. I think a recent fix for #696 might have actually fixed this problem as well and will be included in the next release (1.81).
