### ISSUE TITLE
Choice bullets and numbering

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#103]
Currently with a modal choice, you are given the option of 1 or 2 (or 3) - Replacing the bullets in the text with the corresponding number would aid readability and more clearly understand what is occurring in the log.

Choose one — (1) [text]. (2) [text]. etc

The oracle text can remain the same.

**Comment by melvinzhang** [comment]
Good idea! Please go ahead.

**Comment by ShawnieBoy** [comment]
Will have a look at the scriptbuilder for this process
