### ISSUE TITLE
Unable to restore back to May choice

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#1031]
As undo points are not created for May choice.

**Comment by melvinzhang** [comment]
@ShawnieBoy should work now, it will be possible to rollback to just before a May choice, rather than requiring the player to cast/activate the ability again. Please verify and close if ok. Thanks!

**Comment by ShawnieBoy** [comment]
I'm getting a crash:

```
Exception from controller.runGame: null
java.lang.AssertionError
        at magic.ui.widget.duel.animation.MagicAnimations.getDrawCardAnimation(MagicAnimations.java:95)
        at magic.ui.widget.duel.animation.MagicAnimations.getGameplayAnimation(MagicAnimations.java:27)
        at magic.ui.screen.duel.game.SwingGameController.doPlayAnimationAndWait(SwingGameController.java:663)
        at magic.ui.screen.duel.game.SwingGameController.updateGameView(SwingGameController.java:687)
        at magic.ui.screen.duel.game.SwingGameController.runGame(SwingGameController.java:810)
        at magic.ui.screen.duel.game.DuelGameScreen$1.run(DuelGameScreen.java:51)
```

**Comment by melvinzhang** [comment]
Hmm, the problem is it is tripping on the assert cards.size() == 1 because of all the Grizzly Bears put into the library by Terminus. Normally undo could not bring your back to draw phase where it tries to run the animation.

@lodici There is now legitimate situations where you could be brought back into draw phase but with more than 1 additional card in your library. i.e. oldGame is after Terminus puts cards into your library, newGame after undo before Terminus puts cards into your library.

I would suggest replacing the isEmpty check and cards.size assert with the following, to indicate that animation should play only if there is exactly one cards.

```
if (cards.size() != 1) {
  return null
}
```

@lodici what do you think?

**Comment by melvinzhang** [comment]
I think undo in general would break some of the heuristics for animation to check oldGame and newGame as in the undo case, newGame is before the oldGame. Another suggestion is to disable animation during undo by checking number of undo points between oldGameInfo and newGameInfo

**Comment by melvinzhang** [comment]
I've implemented the second method which is to skip animation if newGameInfo is the result of undo. @ShawnieBoy this fixes the crash due to assert. Normally I play without animations hence I did not notice the crash earlier, good thing you caught it.
