### ISSUE TITLE
SN in "return SN to the battlefield" log message not clickable link.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#1033]
![screenshot from 2017-01-14 13 22 03](https://cloud.githubusercontent.com/assets/2443519/21955137/b12ecba8-da5c-11e6-8ffd-46f9f4204923.png)

**Comment by melvinzhang** [comment]
Good find, due to LeavesReturnExiledTrigger inserting the card name into description string directly. Fixed by using getTokenizedCardNames.
