### ISSUE TITLE
Energy gain log message

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#1035]
Currently displays `PN get {E}` should be `PN gets {E}`

**Comment by melvinzhang** [comment]
@ShawnieBoy which card does this occur? I tested Highspire Infusion and it shows correctly. See
![screenshot_2017-08-11_14-31-55](https://user-images.githubusercontent.com/1620634/29203212-d75c892a-7ea1-11e7-9d4c-080ac500ba58.png)

**Comment by ShawnieBoy** [comment]
Most likely fixed since Jan
