### ISSUE TITLE
mtgimage.com shut down affect on Magarena.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#104]
Need to find a new download source for images. Should also look at a way of being able to add images that have been sourced externally by user.

**Comment by ShawnieBoy** [comment]
I guess that as long as the images in the folder fit the naming conventions, they should be fine if they've been downloaded separately.

Changing the download source for all the card files shouldn't be too bad with modifications to the scriptbuilder.

**Comment by lodici** [comment]
> I guess that as long as the images in the folder fit the naming conventions, they should be fine if they've been downloaded separately.

Hell of a job to do manually though! I was thinking it might be useful if Magarena had the ability to parse a directory of images and copy/move them to the Magarena image folder with the correct names. Sounds like one for a regex expert.

> Changing the download source for all the card files shouldn't be too bad with modifications to the scriptbuilder.

Should probably do mass script update asap.

**Comment by ShawnieBoy** [comment]
I don't even want to think about mtgjson going! I think it's safer though, images have more copyright and ownership involved.

I've used GathererExtractor before which allows you to choose the save format, having a rename option in magarena would certainly be useful. Can see it being a bit of a headache depending on what naming format is used to begin with.

Melvin may have some ideas on which source to use for images, I remember a time when gathererID was going to be used as reference. Maybe a new announcement that we're on the case.

Reparsing the scripts folder does have a few problems, mainly those with groovy references, and auras (Always auras), and some 'effects that are abilities' on spells, and multiple effects on spells (sometimes isn't catched)- Would need to be able to edit/overwrite specific lines to make it less intrusive, which should be do-able.

**Comment by melvinzhang** [comment]
I propose magiccards.info. Their naming convention is based on set name and collector id, eg http://magiccards.info/scans/en/frf/157.jpg

**Comment by ShawnieBoy** [comment]
The mtgjsonReader will have to be adjusted so it can pull the set code. This might be tricky as the card informatio that is pulled, doesn't contain set codes. The set is what the cards are contained in, plus we want to get the most recent printing of these cards as well.

**Comment by lodici** [comment]
Adding the set code should not be too difficult it should just be a case of adding ``setCode`` as a new argument to ``extractCardDataFromJson()`` in [``loadJsonData()``](https://github.com/magarena/magarena-scripts-builder/blob/master/src/mtgjson/reader/MtgJsonReader.java#L106)
```
extractCardDataFromJson(setObject.getAsJsonArray("cards"), setCode);
```
Not so sure about a recent printing though.

**Comment by ShawnieBoy** [comment]
Not really no, I'd suggest going through the sets in descending release date (which is there).

Was the nice thing about mtgimage :cry:

**Comment by ShawnieBoy** [comment]
However we wouldn't want to pick up any foil sets or special sets with no text (Some of the promo cards) Would have to extend the ignored sets, or have a list of allowed sets for images. (Not forgetting to include the mtgo sets which have more up to date card text and card types for earlier cards)

**Comment by ShawnieBoy** [comment]
Oh and also, magiccards.info doesn't use the standard set codes, so we'd have to convert some of those as well.

**Comment by lodici** [comment]
I have [forked](https://github.com/lodici/magarena-scripts-builder) the scripter repository to have a quick play with the ``http://magiccards.info/`` as the image link. It is very rudimentary and uses the first set it finds for a matching card but initial thoughts are -
* it will generally work using ``http://magiccards.info/scans/en/{CODE}/{NUMBER}.jpg``
* except not all json card entries have a {NUMBER}. Maybe it is a set thing?
* as mentioned not all set codes match, eg. JSON = tor, MAGICCARDS = tr. Will need to create a map.

**Comment by ShawnieBoy** [comment]
Yes, the {NUMBER} may be missing from older sets, or special box sets. It's the card's number in that set, not a multiverseID (which is also there). I can't remember when it was introduced, was fairly early on.

**Comment by ShawnieBoy** [comment]
I have a feeling they use the same set codes as MWS http://www.slightlymagic.net/forum/viewtopic.php?f=2&t=581#p6454

**Comment by lodici** [comment]
Actually there is a ``gathererCode`` so a mapping might not be required...
```
    {
                "name" : "Nemesis",            // The name of the set
                "code" : "NMS",                // The code name of the set
        "gathererCode" : "NE",                 // The code that Gatherer uses for the set. Only present if different than 'code'
             "oldCode" : "NEM",                // An old style code used by some Magic software. Only present if different than 'gathererCode' and 'code'
         "releaseDate" : "2000-02-14"          // When the set was released (YYYY-MM-DD). For promo sets, the date the first card was released.
              "border" : "black",              // The type of border on the cards, either "white", "black" or "silver"
                "type" : "expansion",          // Type of set. One of: "core", "expansion", "reprint", "box", "un",
                                               //                      "from the vault", "premium deck", "duel deck",
                                               //                      "starter", "commander", "planechase", "archenemy",
                                               //                      "promo", "vanguard", "masters"
               "block" : "Masques",            // The block this set is in,
          "onlineOnly" : false,                // Present and set to true if the set was only released online
             "booster" : [ "rare", ... ],      // Booster contents for this set, see below for details
               "cards" : [ {}, {}, {}, ... ]  // The cards in the set
    }
```
Just to confirm then, given a card appears in more than one set choose the one in the set with the most recent release date? That way should always get a {NUMBER}?

**Comment by ShawnieBoy** [comment]
Yes, that's right. - Must have missed those other code options for the sets. Hopefully there won't be any that magiccards.info made up itself, hehe

**Comment by ShawnieBoy** [comment]
http://magiccards.info/sitemap.html

Looks like it is using the modern codes after lorwyn. Although I remember that conflux is cfx instead of con (Same for us actually as windows doesn't allow filenames called con)

**Comment by lodici** [comment]
The following is the list of sets sorted by release date including where the ``mtgjson`` set code is replaced with ``gathererCode``.
```
2015-02-27 : DDO
2015-01-23 : FRF
2014-12-05 : DD3_JVC
2014-11-07 : C14
2014-09-26 : KTK
2014-09-05 : DDN
2014-08-22 : V14
2014-07-18 : M15
2014-06-16 : VMA
2014-06-06 : CNS
2014-05-30 : MD1
2014-05-02 : JOU
2014-03-14 : DDM
2014-02-07 : BNG
2013-11-01 : C13
2013-09-27 : THS
2013-09-06 : DDL
2013-08-23 : V13
2013-07-19 : M14
2013-06-07 : MMA
2013-05-03 : DGM
2013-04-06 : pWCQ
2013-03-15 : DDK
2013-02-01 : GTC
2012-11-02 : CM1
2012-10-05 : RTR
2012-09-07 : DDJ
2012-08-31 : V12
2012-07-13 : M13
2012-06-01 : PC2
2012-05-04 : AVR
2012-03-30 : DDI
2012-02-03 : DKA
2011-11-18 : PD3
2011-09-30 : ISD
2011-09-02 : DDH
2011-08-26 : V11
2011-07-15 : M12
2011-06-17 : CMD
2011-05-13 : NPH
2011-04-01 : DDG
2011-02-04 : MBS
2011-01-10 : ME4
2010-11-19 : PD2
2010-10-01 : SOM
2010-09-03 : DDF
2010-08-27 : V10
2010-07-16 : M11
2010-06-18 : ARC
2010-06-04 : DPA
2010-04-23 : ROE
2010-03-19 : DDE
2010-02-05 : WWK
2009-11-20 : H09
2009-10-30 : DDD
2009-10-02 : ZEN
2009-09-07 : ME3
2009-09-04 : HOP
2009-08-28 : V09
2009-07-17 : M10
2009-04-30 : ARB
2009-04-10 : DDC
2009-02-06 : CON
2008-11-07 : DD2
2008-10-03 : ALA
2008-09-22 : ME2
2008-08-29 : DRB
2008-07-25 : EVE
2008-05-02 : SHM
2008-04-01 : p15A
2008-02-01 : MOR
2007-11-16 : EVG
2007-10-12 : LRW
2007-09-10 : MED
2007-07-21 : pSUM
2007-07-14 : pMGD
2007-07-13 : 10E
2007-05-04 : FUT
2007-02-24 : pGPX
2007-02-09 : pPRO
2007-02-02 : PLC
2006-12-31 : pHHO
2006-10-06 : TSB
2006-07-21 : CST
2006-05-05 : DIS
2006-03-18 : pCMP
2006-02-03 : GPT
2006-01-01 : pWPN
2005-12-09 : p2HG
2005-10-07 : RAV
2005-07-29 : 9ED
2005-06-03 : SOK
2005-02-04 : BOK
2004-10-01 : CHK
2004-06-04 : 5DN
2004-02-06 : DST
2003-10-02 : MRD
2003-07-28 : 8ED
2003-07-26 : pREL
2003-05-26 : SCG
2003-02-03 : LGN
2002-10-07 : ONS
2002-05-27 : JUD
2002-02-04 : TOR
2001-12-01 : DKM
2001-10-01 : ODY -> OD
2001-06-04 : APC -> AP
2001-05-01 : pMPR
2001-04-11 : 7ED -> 7E
2001-02-05 : PLS -> PS
2000-10-02 : INV -> IN
2000-10-01 : BTD -> BD
2000-06-05 : PCY -> PR
2000-04-01 : S00 -> P4
2000-02-14 : NMS -> NE
2000-02-05 : pELP
2000-02-01 : pFNM
1999-12-01 : pSUS
1999-11-12 : BRB -> BR
1999-10-04 : MMQ -> MM
1999-09-04 : pWOS
1999-08-04 : pWOR
1999-07-12 : pGRU
1999-07-01 : S99 -> P3
1999-06-07 : UDS -> CG
1999-05-01 : PTK -> PK
1999-04-21 : 6ED -> 6E
1999-02-15 : ULG -> GU
1998-11-01 : ATH
1998-10-12 : USG -> UZ
1998-09-01 : pALP
1998-08-11 : UGL -> UG
1998-06-15 : EXO -> EX
1998-06-01 : pJGP
1998-03-02 : STH -> ST
1997-10-14 : TMP -> TE
1997-10-04 : pPRE
1997-06-09 : WTH -> WL
1997-03-24 : 5ED -> 5E
1997-02-03 : VIS -> VI
1996-12-31 : ITP
1996-11-01 : MGB
1996-10-08 : MIR -> MI
1996-08-14 : pCEL
1996-08-02 : pARL
1996-07-01 : RQS
1996-06-10 : ALL -> AL
1995-10-01 : HML -> HM
1995-07-01 : CHR -> CH
1995-06-01 : ICE -> IA
1995-04-01 : 4ED -> 4E
1995-01-01 : pLGM
1994-11-01 : FEM -> FE
1994-08-01 : DRK -> DK
1994-06-01 : LEG -> LE
1994-04-01 : 3ED -> 3E
1994-03-01 : ATQ -> AQ
1994-01-01 : pDRC
1993-12-01 : 2ED -> 2U
1993-10-01 : LEB -> 2E
1993-08-05 : LEA -> 1E
```
 This still does not work, for example TOR is not converted to TR so we will need a suitable mapping to the codes used by ``mtginfo``. I would be grateful if someone else could do this while I update the scripter code - a properties file of the format would probably be the easiest.
```
<mgtjson code>=<mtginfo code>
```

**Comment by melvinzhang** [comment]
tab separated list of set codes from magiccards.info
```
frf	Fate Reforged
ktk	Khans of Tarkir
m15	Magic 2015
cns	Conspiracy
frf	Fate Reforged
ktk	Khans of Tarkir
jou	Journey into Nyx
bng	Born of the Gods
ths	Theros
dgm	Dragon's Maze
gtc	Gatecrash
rtr	Return to Ravnica
avr	Avacyn Restored
dka	Dark Ascension
isd	Innistrad
nph	New Phyrexia
mbs	Mirrodin Besieged
som	Scars of Mirrodin
roe	Rise of the Eldrazi
wwk	Worldwake
zen	Zendikar
arb	Alara Reborn
cfx	Conflux
ala	Shards of Alara
eve	Eventide
shm	Shadowmoor
mt	Morningtide
lw	Lorwyn
fut	Future Sight
pc	Planar Chaos
ts	Time Spiral
tsts	Time Spiral "Timeshifted"
cs	Coldsnap
ai	Alliances
ia	Ice Age
di	Dissension
gp	Guildpact
rav	Ravnica: City of Guilds
sok	Saviors of Kamigawa
bok	Betrayers of Kamigawa
chk	Champions of Kamigawa
5dn	Fifth Dawn
ds	Darksteel
mi	Mirrodin
sc	Scourge
le	Legions
on	Onslaught
ju	Judgment
tr	Torment
od	Odyssey
ap	Apocalypse
ps	Planeshift
in	Invasion
pr	Prophecy
ne	Nemesis
mm	Mercadian Masques
ud	Urza's Destiny
ul	Urza's Legacy
us	Urza's Saga
ex	Exodus
sh	Stronghold
tp	Tempest
wl	Weatherlight
vi	Visions
mr	Mirage
hl	Homelands
fe	Fallen Empires
dk	The Dark
lg	Legends
aq	Antiquities
an	Arabian Nights
m15	Magic 2015
m14	Magic 2014 Core Set
m13	Magic 2013
m12	Magic 2012
m11	Magic 2011
m10	Magic 2010
10e	Tenth Edition
9e	Ninth Edition
8e	Eighth Edition
7e	Seventh Edition
6e	Classic Sixth Edition
5e	Fifth Edition
4e	Fourth Edition
rv	Revised Edition
un	Unlimited Edition
be	Limited Edition Beta
al	Limited Edition Alpha
vma	Vintage Masters
me4	MTGO Masters Edition IV
me3	MTGO Masters Edition III
me2	MTGO Masters Edition II
med	MTGO Masters Edition
cns	Conspiracy
pd3	Premium Deck Series: Graveborn
pd2	Premium Deck Series: Fire and Lightning
pds	Premium Deck Series: Slivers
md1	Modern Event Deck
mma	Modern Masters
dpa	Duels of the Planeswalkers
ch	Chronicles
c14	Commander 2014 Edition
c13	Commander 2013 Edition
cma	Commander's Arsenal
pc2	Planechase 2012 Edition
cmd	Commander
arc	Archenemy
pch	Planechase
v14	From the Vault: Annihilation
v13	From the Vault: Twenty
v12	From the Vault: Realms
fvl	From the Vault: Legends
fvr	From the Vault: Relics
fve	From the Vault: Exiled
fvd	From the Vault: Dragons
ddo	Duel Decks: Kiora vs. Elspeth
ddn	Duel Decks: Speed vs. Cunning
ddm	Duel Decks: Jace vs. Vraska
ddl	Duel Decks: Heroes vs. Monsters
ddk	Duel Decks: Sorin vs. Tibalt
ddj	Duel Decks: Izzet vs. Golgari
ddi	Duel Decks: Venser vs. Koth
ddh	Duel Decks: Ajani vs. Nicol Bolas
ddg	Duel Decks: Knights vs. Dragons
ddf	Duel Decks: Elspeth vs. Tezzeret
pvc	Duel Decks: Phyrexia vs. The Coalition
gvl	Duel Decks: Garruk vs. Liliana
dvd	Duel Decks: Divine vs. Demonic
jvc	Duel Decks: Jace vs. Chandra
evg	Duel Decks: Elves vs. Goblins
cstd	Coldsnap Theme Decks
9eb	Ninth Edition Box Set
8eb	Eighth Edition Box Set
dm	Deckmasters
bd	Beatdown Box Set
br	Battle Royale Box Set
at	Anthologies
mgbc	Multiverse Gift Box Cards
uh	Unhinged
ug	Unglued
uhaa	Unhinged Alternate Foils
st2k	Starter 2000
st	Starter 1999
p3k	Portal Three Kingdoms
po2	Portal Second Age
po	Portal
itp	Introductory Two-Player Set
ced	Collector's Edition
cedi	International Collectors' Edition
15ann	15th Anniversary
gpx	Grand Prix
pro	Pro Tour
mgdc	Magic Game Day Cards
wrl	Worlds
wmcq	World Magic Cup Qualifiers
drc	Dragon Con
ptc	Prerelease Events
rep	Release Events
mlp	Magic: The Gathering Launch Parties
sum	Summer of Magic
grc	WPN/Gateway
cp	Champs
thgt	Two-Headed Giant Tournament
arena	Arena League
fnmp	Friday Night Magic
mprp	Magic Player Rewards
sus	Super Series
hho	Happy Holidays
jr	Judge Gift Program
pot	Portal Demogame
euro	European Land Program
guru	Guru
apac	Asia Pacific Land Program
wotc	WotC Online Store
uqc	Celebration Cards
mbp	Media Inserts
dcilm	Legend Membership
```

**Comment by ShawnieBoy** [comment]
Thanks for those lists, I'll get to it. I can also extend the ignored sets so we don't catch any textless or foil cards.

**Comment by lodici** [comment]
Unfortunately, there appear to be an awful lot (5257) of cards with no ``number`` in the json feed.
https://gist.github.com/lodici/e15e5900b850eb5a0bb4#file-errors-txt
This was generated whereby if a card for a given set has no number it would then try to see if it has a number in another set. Each card in the out is prefixed with the json set code.

**Comment by lodici** [comment]
Sorry, slight miscalculation - the number is more like 2641 (still alot).
https://gist.github.com/lodici/e15e5900b850eb5a0bb4#file-errors-txt

**Comment by ShawnieBoy** [comment]
It looks like Exodus is the first expansion to have card numbers (incidentally also the first to have colored rarity symbols). - Last expansion of Rath Cycle/Tempst block, 1998-ish

So anything printed before then that hasn't been reprinted won't have one. I wasn't expecting there to be so many!

Even trying to assign our own numbers would be awkward, cards by color, alphabetically.

This is becoming a bit of a nightmare :sad:

**Comment by lodici** [comment]
Possible alternative - ``api.mtgdb.info``? Can use ``multiverseid``.

**Comment by ShawnieBoy** [comment]
Looks good - shame it doesn't have all the mtgo images. Some of the hi-res images aren't so hi-res either.

Compare these - 

Vintage Masters, Mox Jet.
http://api.mtgdb.info/content/hi_res_card_images/383020.jpg
http://magiccards.info/scans/en/vma/6.jpg

Although it does have the Masters Edition sets it seems.

Masters Edition II, Aysen Crusader
http://api.mtgdb.info/content/hi_res_card_images/184587.jpg
http://magiccards.info/me2/en/7.html

(The crusader is my go-to card to emphasise the need for the online 'printings' - her original card text is so very different: http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=184587&type=card She used to be a 'Crusader' not a 'Human Knight' and her toughness was effected by 'Heroes' not 'Soldiers and Warriors')

Looks like a good place to start as well - if Wizards don't find out about it, hehe

**Comment by lodici** [comment]
I have updated the code so that it uses ``mtginfo`` if the json feed has ``number`` but if not then it uses ``mtgdb.info`` and the ``multiverseid``. This leaves a much more manageable 125 cards with neither.
https://gist.github.com/lodici/3348794199612cd41a2e#file-errors2-txt

**Comment by lodici** [comment]
Miscalculated again! Only 10 cards left with neither a ``number`` or ``multiverseid``
https://gist.github.com/lodici/3348794199612cd41a2e#file-errors2-txt

**Comment by lodici** [comment]
So if we could come up with a third image url that uses the card name that would probably cover all cases.

**Comment by ShawnieBoy** [comment]
But they must have a multiverseID - 

http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=83440
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3667

King Cheetah 83440 - 9th Ed
King Cheetah 3667 - Visions

**Comment by ShawnieBoy** [comment]
They all seem to be from the visions set actually

**Comment by lodici** [comment]
Ok, I think there is something still screwy. ``Bull Elephant`` should not be in the errors log since it is not in ``CardsMissingInMagarena.txt`` and I just checked the ``Necrosavant`` script and it does contain an image link - http://magiccards.info/scans/en/6e/145.jpg so not sure why it ended up in the error log.

**Comment by lodici** [comment]
The list of set codes sorted by release date above is incorrect since it assumes only one set is released per date. The correct list can be found [here](https://gist.github.com/lodici/29f77145b4a8ed6a2a26#file-jsonsetcodes-txt).

This plus a load of other updates (see https://github.com/lodici/magarena-scripts-builder) seem to have fixed all issues. This is what I am getting now -
![screenshot00054](https://cloud.githubusercontent.com/assets/2443519/6670909/9851a92a-cbf9-11e4-81ef-f75658707359.png)

Once the mapping file is included all ``mtginfo`` links should then work correctly and we are done.

**Comment by lodici** [comment]
I have added functionality to read ``src/main/resources/mtginfoSetsMap.txt`` which can be used to specify the mapping from a ``mtgjson`` set code to the equivalent ``mtginfo`` code. To test I added ``TOR=tr`` and it  seems to be updating the image links as expected. So (because I have never done it) I have created a Pull request for merging the completed updates into the main scripter repository.

**Comment by lodici** [comment]
I have created a [file](https://gist.github.com/lodici/51a01e8066b6f29ff377#file-imagelinks-txt) which lists the the image link for each script file. I thought this might be useful for say running an ``awk`` script to update the image url for all existing scripts. Here are the first few lines...
```
A_Display_of_My_Dark_Power.txt = http://magiccards.info/scans/en/arc/8.jpg
Abandon_Hope.txt = http://api.mtgdb.info/content/hi_res_card_images/4635.jpg
Abandoned_Outpost.txt = http://magiccards.info/scans/en/ody/312.jpg
Abattoir_Ghoul.txt = http://magiccards.info/scans/en/isd/85.jpg
Abbey_Gargoyles.txt = http://magiccards.info/scans/en/me2/1.jpg
Abbey_Griffin.txt = http://magiccards.info/scans/en/isd/1.jpg
...
```

**Comment by ShawnieBoy** [comment]
I've pushed all the changes - the small group of rarity 'S' only cards were done manually.

Every card is guaranteed to have a corresponding image - I've attempted to re-reference images in the scriptbuilder CardImages.txt to get the most recent versions on magiccards.info with the following priorities:

* Most accurate printed text to match oracle
* Non-foil (Some of the foil scans do not read very well/unclear image)
* Modern Frame (10E+ and latest frame version)

Some of the changes in CardImages.txt are purely Aesthetic (The Timespiral Timeshifted and  Coldsnap Theme Deck cards for example. Lots of these were 'reprinted' in the online MTG sets, and in the case of the Coldsnap cards, they include a modern frame, unlike the online versions, though the text is still modern oracle.)

**Comment by lodici** [comment]
Good stuff. I've re-synched my scripts and it updated all 95 missing images without a hitch.

**Comment by melvinzhang** [comment]
For the cards without a number, are we able to determine the correct set from magiccards.info to use? If the scripts builder can write a file with the card name <tab> URL for magiccards.info up to the set name, without the number, I can write a script to query magiccards.info via the http://magiccards.info/query?q=!<card name> to retrieve the full URL. We can then append the full URL to the override file.

**Comment by ShawnieBoy** [comment]
Yes, we'd know the set and the cardname, would just be missing the collector number - Sounds like a good solution to the 1000 or so cards from mtgdb.

**Comment by lodici** [comment]
Not sure what the exact format you need is but you could add the ``sout`` indicated to the following method and copy the results
```
    private void setImageUrl(final JsonObject card) throws UnsupportedEncodingException {

        if (card.has("number")) {
            this.imageUrl = String.format(
                    "http://magiccards.info/scans/en/%s/%s.jpg",
                    setCode.toLowerCase(),
                    card.get("number").getAsString()
            );
            clearCardImageError(this);

        } else if (card.has("multiverseid")) {
            this.imageUrl = String.format(
                    "http://api.mtgdb.info/content/hi_res_card_images/%s.jpg",
                    card.get("multiverseid").getAsString()
            );
            clearCardImageError(this);
			
			--->
			System.out.printf("%s=http://magiccards.info/scans/en/%s\n", getCardName(), setCode);
			---->

        } else {
            addCardImageError(this, String.format("%s has no number or multiverseid - cannot set {image} property.", cardName));
        }
        
    }
```

**Comment by melvinzhang** [comment]
Yes, that's the format. I've try running the script builder with your suggested modification.

**Comment by lodici** [comment]
Ok, if you have any problems I can run it later (I won't be at my PC for the next few hours).

**Comment by melvinzhang** [comment]
All done, most were updated automatically, some done by hand when the default image from query doesn't match the set we want to use. Some cards which selected st2k could not be found on magiccards.info:
Goblin_Hero.txt
Python.txt
Armored_Pegasus.txt
Hero_s_Resolve.txt

There are only 20 st2k cards on magiccards.info, likely most were not scanned. Suggest we ignore st2k when selecting the set to use.

**Comment by lodici** [comment]
I did a complete image download, running the playable and unimplemented downloaders together. All downloaded without a single error...but although the unimplemented finished quickly it took over an hour to complete the 9000+ playable images. It seemed to slow down to about one image per second from about halfway. 

It might be worthwhile looking into @huggybaby's forum suggestion - run the download in the background but add an on-demand function that prioritizes images to download based on the decks that have been selected to play in a duel.

**Comment by lodici** [comment]
Also 312 x 445 appears to be  the new standard size, whereas with ``mtgimages.com`` it was 480 x 680 so might need to adjust some of the display code (Large Card Images option, in-game image scaling, etc).

**Comment by lodici** [comment]
And even at native size some images are out-of-focus...
![screenshot00070](https://cloud.githubusercontent.com/assets/2443519/6769311/2525aa5c-d08e-11e4-88b5-509d314290db.png)

**Comment by ShawnieBoy** [comment]
Ahh, I forgot about the basic land - we can always override them back to the full-art lands. As sets age they normally get better quality images.

**Comment by ShawnieBoy** [comment]
```
There are only 20 st2k cards on magiccards.info, likely most were not scanned. Suggest we ignore st2k when selecting the set to use.
```

Good find, not even half of them on there - I'll add them to the ignore list.

**Comment by melvinzhang** [comment]
+1 for override lands to use full card art.

**Comment by ShawnieBoy** [comment]
I'll do that now then :grinning:

**Comment by lodici** [comment]
I think this has run its course.
