### ISSUE TITLE
`Captain of the Watch` copy made by `Seance` doesn't create `Soldier` tokens

### ISSUE THREAD

**Issue by itandetnik** [magarena/magarena#1040]
Computer has `Seance` in play, and the freshly destroyed `Captain of the Watch` in the graveyard. At my next upkeep, it decides, quite sensibly, to use `Seance` effect on that `Captain of the Watch` and put a copy of it on the battlefield.

I believe this should trigger *"when `Captain of the Watch` enters the battlefield..."* effect - but it didn't; no `Soldier` tokens got created. That's kind of the whole point of `Seance`, it's pretty useless otherwise.

Gameplay  report: [gameplay-report.zip](https://github.com/magarena/magarena/files/721971/gameplay-report.zip)

**Comment by melvinzhang** [comment]
Confirmed by code inspection, bug is in setting up token that is a copy of a card. It did not get the ability of the card.

**Comment by lodici** [comment]
Possibly related (raised in #1044), the "captain of the watch" log link is incorrect, highlighting a land card on the battlefield and displaying the land card if clicked -
![screenshot00567](https://cloud.githubusercontent.com/assets/2443519/22368873/b917f9f6-e480-11e6-8e98-49dda65bb724.jpg)

**Comment by lodici** [comment]
This has not fixed the log link. I will raise another issue.
