### ISSUE TITLE
Is CardBuilder already being loaded in-game to display modified cards?

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#1042]
From the screen-shot in the gameplay report in #1040 it appears so. If this is the case then CB should be loaded by default during the game setup process (ie. when the 'Next Game' is disabled) since the long time initialization will be less noticeable. And focus should be on using CB consistently whenever a card is modified (eg. new P/T, abilities, etc) as raised in #965.

**Comment by melvinzhang** [comment]
It is loaded when needed, not always loaded. See NewGameWorker.loadCardBuilderIfRequired and also MScreen.useLoadingScreen

**Comment by lodici** [comment]
IIRC loadCardBuilderIfRequired only checks the decks to see whether all card images are available before the game starts. The game report in #1040 appears to be a case where where all printed images are available so CB was not loaded until a token 'Captain of the Watch' was created using CardBuilder, so CB would have been loaded during the game which I don't think is desirable. If CB is going to be used to display such cards (which I think it should) then you cannot predict if it will or will not be required during a game so it should be loaded by default at game start up.

**Comment by melvinzhang** [comment]
I tried to trace from MagicImages.getCardImage but from what I can tell it should load the image for "Captain of the Watch" and not create a new image. @ShawnieBoy any idea what is causing the token image to be generated but the rest of the cards to be showing the printed image?

**Comment by ShawnieBoy** [comment]
Tokens which do not have any scripts (ie. token copies of existing permanents) will use cardbuilder to create the image as there's no token image to display - it's a proxy, as if there's no image available.
As there's no cropped image either it then creates a proxy card image to fill the space. #66 #208 #719 

As tokens aren't loaded along with decklists - cardbuilder will kick in if there's no token image.

**Comment by ShawnieBoy** [comment]
With the #1040 - Cropping full size images to display crops hasn't been implemented for Token images, as it cannot distinguish between a token that is an existing full size normal card made into a token, or a token that is just a token. Otherwise the token tokens would always be cropped.

If an existing cropped image of 'Captain of the Watch' was available, it would appear on the token.

**Comment by lodici** [comment]
I think the answer to the original question is then, yes it is loaded in-game. Given that in future CB should only become more integrated into displaying in-game card modifications I think it would be better to always load it at the start of game when Magarena is already doing some heavy lifting on a background thread. This would probably add about 20 to 30 seconds to game setup time on my low spec machine but as I am already waiting it is a more natural expectation and I can always browse the player decks while I wait.

**Comment by melvinzhang** [comment]
Agree, it is not possible to tell what tokens are used, when token images are missing, a proxy is generated.

**Comment by ShawnieBoy** [comment]
Although I've just noticed that the token isn't displaying a text box, which it should as 'Captain of the Watch' has abilities. I'll look into that.
