### ISSUE TITLE
Loading cardbuilding is slow, especially during a duel

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#1046]
as per discussion in #1042.

**Comment by melvinzhang** [comment]
Would it be better to do it at startup instead?

**Comment by lodici** [comment]
I think it is better at game startup so it does not impact accessing card explorer and deck editor which can already take a while if loading cards / missing card properties.

**Comment by lodici** [comment]
I have included some diagnostics which are sent to the System.out console. Here are mine when running on a cold-start VM and warmed up VM -
```
loading CardBuilder (Used: 50.2 • Free: 17.3 • Total: 67.5 • Max: 494.9)
done in 13.79s (Used: 199.4 • Free: 154.2 • Total: 353.6 • Max: 494.9)

loading CardBuilder (Used: 49.2 • Free: 32.1 • Total: 81.3 • Max: 494.9)
done in 5.26s (Used: 187.5 • Free: 74.3 • Total: 261.8 • Max: 494.9)
```

**Comment by melvinzhang** [comment]
Does this mean on first start it would take at least 13.80s before the first game can begin?

**Comment by melvinzhang** [comment]
> I think it is better at game startup so it does not impact accessing card explorer and deck editor 
Why would loading cardbuilder impact card explorer and deck editor? If the user is displaying rendered cards, card explorer will itself trigger a load of cardbuilder. If not, there will be no effect by loading cardbuilder on a background thread, similar to loading of card data.

**Comment by lodici** [comment]
On my very low spec Acer Aspire One -
```
loading CardBuilder (Used: 98.3 • Free: 149.3 • Total: 247.6 • Max: 494.9)
done in 57.30s (Used: 201.1 • Free: 46.5 • Total: 247.6 • Max: 494.9)

loading CardBuilder (Used: 74.9 • Free: 172.7 • Total: 247.6 • Max: 494.9)
done in 41.82s (Used: 202.8 • Free: 44.7 • Total: 247.6 • Max: 494.9)
```

**Comment by lodici** [comment]
> Why would loading cardbuilder impact card explorer and deck editor? If the user is displaying rendered cards, card explorer will itself trigger a load of cardbuilder. If not, there will be no effect on card explorer or deck editor by loading cardbuilder on a background thread at startup.

Won't make much difference if the user immediately selects Resume Duel on starting Magarena but if you think it would make a difference then go for it. I would be interested to see even if running on a background thread whether it has an affect on the responsiveness of the UI given that card data is also being loaded at the same time (assuming you mean parallel background tasks). Would the start up memory parameters need to be increased (eg. ``-Xms256M``) given it will be at around 200M before image caching, AI simulations, running a game, etc. are taken into account.

**Comment by melvinzhang** [comment]
I would like to give it a try, probably for next dev cycle. I'm a bit uncomfortable with including this load time for players who are not using rendered cards. Would it be alright to temporarily revert this for Jan release? I'll patch it back in once Jan release is out.

**Comment by lodici** [comment]
Sure, no probs.

**Comment by melvinzhang** [comment]
Thanks. I'll reopen this as reminder than works needs to be done on this for Feb.

**Comment by melvinzhang** [comment]
> Would the start up memory parameters need to be increased (eg. -Xms256M) given it will be at around 200M before image caching, AI simulations, running a game, etc. are taken into account.

@lodici  Yes, I think so. Any thoughts on what should be the new memory parameters?

**Comment by melvinzhang** [comment]
This discussion on memory got me thinking, card builder takes a long time to load because it loads all the images at the start. This is slow and takes up quite a bit of memory. Perhaps if we improve this we do not need to separately load card builder. Created https://github.com/magarena/magarena/issues/1073 to speed up card builder loading using an image cache.

**Comment by lodici** [comment]
> @lodici Yes, I think so. Any thoughts on what should be the new memory parameters?

TBH I am not sure how the XMS value impacts on performance. Certainly XMX has a distinct affect, I have played Magarena with low XMX settings and gameplay gets very stuttery which goes away on increasing XMX. According to http://stackoverflow.com/questions/4667483/how-is-the-default-java-heap-size-determined XMS represents the initial heap size so I guess if we were loading up a ton of stuff at startup then a low XMS might have an effect. By using a cache this should alleviate that huge CB resource load so I would leave as-is until we can see how the cache affects things.

**Comment by lodici** [comment]
http://stackoverflow.com/questions/2532326/java-xms-initial-size-effects explains how XMS affects things pretty well. Basically if Magarena startup is close to or needs more memory than specified by XMS the JVM will have to thrash about increasing the heap and general memory management instead of devoting cpu cycles to Magarena which is a bad thing.

**Comment by melvinzhang** [comment]
With dynamic asset loading, creating the "Captain of the Watch" token on the fly is a lot faster as it only loads the relevant token frames rather than all possible frames.

@lodici please help to test the improvement of image cache with TestTokenCopy on your low spec laptop. Images should be set to "as printed", then create a copy of "Captain of the Watch" from the trigger and that will generate a token proxy. Thanks!

**Comment by lodici** [comment]
Takes two to three seconds instead of 20 to 30 seconds in 1.81. A huge improvement. :+1: Memory wise it also makes a big difference, shown is the mem usage after the CB token copy is displayed on the battlefield for 1.81, then with the cache.
![screenshot00581](https://cloud.githubusercontent.com/assets/2443519/22847847/c861d34c-efe7-11e6-929e-8ae6a4a20b44.jpg)
![screenshot00582](https://cloud.githubusercontent.com/assets/2443519/22847852/d2e2a3d2-efe7-11e6-81d1-0bc955464751.jpg)

**Comment by melvinzhang** [comment]
Thanks for the confirmation! The before and after memory profile is a good comparison. I think we can let cardbuilder do its thing as needed without requiring a special loading, as there is now nothing to load beforehand.
