### ISSUE TITLE
Allow snapshot.game to be accessed inside the gameplay-report.zip

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#1053]
Be able to load the snapshots without having to unzip reports.

**Comment by lodici** [comment]
:+1:  Yes this would be very useful. Either drag and drop the zip or snapshot.game file to automatically load the game state. Normally, when I click on the zip link I open it instead of downloading it so would like to be able to drag the game.snapshot from the archive directly into Magarena.

**Comment by lodici** [comment]
Can now load a game snapshot by dragging and dropping the ``snapshot.game`` file into Magarena directly. Confirmed to work dragging file out of gameplay report zip file.
