### ISSUE TITLE
Unable to undo *past* a "may" choice

### ISSUE THREAD

**Issue by itandetnik** [magarena/magarena#1054]
With Magarena 1.81, it's now possible to Undo to a "may" choice - but it appears impossible to undo past it, farther back in time. Clicking Undo button just gets back to the same choice.

Gameplay report: [gameplay-report.zip](https://github.com/magarena/magarena/files/741144/gameplay-report.zip)

**Comment by melvinzhang** [comment]
Thanks for catching this. Able to reproduce it,

**Comment by melvinzhang** [comment]
@itandetnik we've updated 1.81 release zip to fix this, you can redownload the zip file to get the fix. The silly mistake was taking the undo snapshot before the choice is made. Then when you undo, it takes another snapshot, so undoing goes back to itself.
