### ISSUE TITLE
Draft - Ignoring and implementing, or not implementing?

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#1067]
Some cards using the draft mechanic are listed as `status=not supported: draft`, some are implemented without their draft abilities, and others are simply not implemented.

Which process should we use for mechanics which we won't be implementing (Like Partner, and other Commander-related abilities). Having non-functional card text could be confusing/misleading.

Another way to question it, would be for other mechanics we don't implement (like Scry >1) - We don't remove the scry ability from the card and implement them.

**Comment by melvinzhang** [comment]
Not all draft mechanics are the same, some affect drafting only (eg. draft SN face up), other have gameplay implications (eg. note how many cards ... SN have PT equal to the number you noted). The former can be implemented while the latter are not supported.

**Comment by melvinzhang** [comment]
In other words, if the cards plays the same without the ability, it can be implemented. For example, a card with "Draft SN face up" plays the same once the game starts as a cards without that ability.

**Comment by ShawnieBoy** [comment]
I was confused as [Aether Searcher](http://magiccards.info/cns/en/53.html) is noted as not supported.

**Comment by melvinzhang** [comment]
Because it has "search your hand and/or library for a card with a name noted", there is no way to note anything as there is no drafting.

**Comment by ShawnieBoy** [comment]
But [Cogwork Tracker](http://magiccards.info/cns/en/60.html) also notes information during the draft, but is implemented. 😖

**Comment by melvinzhang** [comment]
In a two player game, Cogwork Tracker would always attack the opponent, so the information from draft is not necessary.

**Comment by ShawnieBoy** [comment]
Cool, yes, I think I'm getting it now. - Taking commander rules as an equivalent example:
The planeswalkers which can be commanders function the same with or without that ability, so are fine. Same would apply to Partner abilities as none of them refer to the partnered Commander.
Command Tower isn't implemented as it's ability depends on a Commander.

Wouldn't the Lieutenant ability technically be affecting how the card plays? [Angelic Field Marshal](http://magiccards.info/c14/en/2.html)

Sorry - just trying to get this set in my head, hehe

**Comment by ShawnieBoy** [comment]
I guess it's just a conditional ability - Even in a commander game, it's not going to always be relevant.

**Comment by melvinzhang** [comment]
Lieutenant can be dropped because commanders do not exist in out matches.

**Comment by ShawnieBoy** [comment]
👍  Thanks for helping to clear that up
