### ISSUE TITLE
manifest does not work for spells

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#107]
jerichopumpkin @ forum wrote:
manifest does not work properly, if you manifest a non-creature spell, it is cast for free instead of being put into play face down as a 2/2 creature

**Comment by ShawnieBoy** [comment]
I would assume this is due to the facedown properties being a permanent state. Although looking at manifest it only considers permanent cards as the card is 'played' first.
Is there a way of including cards themselves with states?

**Comment by ShawnieBoy** [comment]
Essentially, need to cast a non-permanent card as a permanent to fix this. Was thinking of a card template that can be added to make it a permanent, but not include a creature type so it cannot be turned face up.

Either change the MagicManifestAction so it doesn't play the card, or add 'permanent' attributes before it does so.

Would having a psuedo MagicType of 'Permanent' help here? Adding that type to a card that doesn't have a permanent type, but viewed as a permanent just for the purpose of casting?

What is annoying is that I can remember times when having bugs in groovy that  ended up with spells on the battlefield, but I can't remember what caused it, lol.

**Comment by melvinzhang** [comment]
Spells provide a custom MagicSpellCardEvent, most permanent uses the default MagicPlayCardEvent.create() as their MagicSpellCardEvent. Fixed by specifying the MagicSpellCardEvent to be MagicPlayCardEvent.create() when playing the card.

**Comment by melvinzhang** [comment]
A spell without groovy code or an effect property will use the default MagicPlayCardEvent.create() and enter the battlefield as a permanent.
