### ISSUE TITLE
Add option that lets you click an empty area of the battlefield to pass.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#1070]
instead of having to move mouse cursor to pass button each time. If too sensitive on normal click then hold mb down for a couple of seconds to trigger.

**Comment by ShawnieBoy** [comment]
Maybe a right-click? Sometimes trying to click on an Aura or Equipment to activate an ability could cause a pass.

**Comment by lodici** [comment]
It would only apply if you tap an _empty_ area of the battlefield. However I don't think right-click is currently assigned during gameplay so it could also work.

**Comment by ShawnieBoy** [comment]
> Left click would only apply if you tap an _empty_ area of the battlefield.

I sometimes miss 😁

**Comment by lodici** [comment]
Just [discovered](https://github.com/magarena/magarena/wiki/Keyboard-shortcuts) you can right click on the hand area to pass. So just need to extend to the whole battlefield.

**Comment by lodici** [comment]
Finally went with double-click since it seems most flexible - it should also work with a single button mouse, touchpad and possibly even touch screen. Left double-click is the same as left clicking the ``->`` button and right double-click is the same as shift-clicking the ``->`` button.

Note this works on any empty area of the battlefield (both player permanents and combat zones) but not the bottom cards zone which already has various mouse events which I did not have time to look at.
