### ISSUE TITLE
Ghastly Conscription status as "needs groovy"

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#1071]
was changed in https://github.com/magarena/magarena/commit/235bc7e5b0bad5bfc47df8d6100885c2c860b0c6 to "not supported: exile-face-down"

I feel the face-down portion is only relevant when using physical cards, so that you don't know what is the actual card being manifested.

In our case, the game performs the actions for you, so you can't tell what are the cards being manifested unless we indicate that in the log. That's why I indicated this as "needs groovy".

@ShawnieBoy your thoughts on this?

**Comment by ShawnieBoy** [comment]
I was just thinking that manifest normally occurs from the top of the library, but this is occurring from exile. Even though we can get the engine to do everything automatically, the cards are still being moved about.

Just thinking of future-proofing.

If there was an effect which said, "Permanents can't enter the battlefield this turn." - the cards would remain in exile face-down. (Or a more Eldrazi-like "Permanents can't enter the battlefield from exile this turn")
Or if there was "You may look at face down cards in exile", you'd be able to identify the Manifested cards.

**Comment by melvinzhang** [comment]
Good point. I think of the effect as one big action and did not consider the possibility that you may not be able to carry out all the steps.
