### ISSUE TITLE
several "not supported: x-cost-as-target cards" are mislabelled

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#1072]
release/Magarena/scripts_missing/Arcum_s_Whistle.txt: x is the converted mana cost of the target, not a restriction of what can be targeted.

release/Magarena/scripts_missing/Green_Sun_s_Zenith.txt: This does not target and can be implemented with groovy code.

release/Magarena/scripts_missing/Wargate.txt: This does not target and can be implemented with groovy code.

**Comment by ShawnieBoy** [comment]
Good point on all of those - will fix
