### ISSUE TITLE
use image cache for card builder assets

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#1073]
Card builder takes up quite a bit of memory for the image assets as they are loaded statically. Before enabling card builder for all users, I hope to improve the memory usage. One simple idea is to use an image cache for the frames and other assets, so that only needed assets are kept in memory. 

This allows us to limit the amount of memory used, even as we add more types of assets (different frames etc). And would also speed up the loading time by not loading all the assets on start-up, but rather only load those that are needed to render the proxies, then store them in cache, for fast access subsequently.

This optimization will (hopefully) allow us to use card builder as needed without requiring a separate "card builder loading" step.

**Comment by melvinzhang** [comment]
This will require a lookup for each image rather than the direct access. Implementation wise, instead of each resource as a static member of ResourceManager, they will be defined as an enum. The image cache will be the static member. And newFrame will take an enum indicating the frame. 

For the other symbols they will need to be retrieved with a get methods taking in an enum. Instead of `ResourceManager.bgLandImage` it will be `ResourceManager.get(FrameResource.bgLandImage)`

**Comment by melvinzhang** [comment]
Requires quite a bit of refactoring but the good thing is that it only involves ResourceManager and its uses. @ShawnieBoy Good thinking of using a separate class for the images.

**Comment by lodici** [comment]
:+1:  Sounds like a good plan.

**Comment by melvinzhang** [comment]
Done! Easier than I imagined, search and replace was good enough to do the work.
