### ISSUE TITLE
implement embalm mechanic

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#1091]
> Embalm is an activated ability you can activate if the creature card with embalm is in your graveyard. Notably you're not casting the card from the graveyard, so things that counter spells won't work against the embalm ability. The original creature spell can be countered, of course, but that just puts the card in the graveyard. I think you see where this is headed.
>
> To activate an embalm ability, simply pay the embalm cost and exile the card. You do this any time you could cast a sorcery, meaning during your main phase when nothing else is happening. When the ability resolves, you create a token copy of the card, but as you'd expect, going through the process of mummification causes some changes. It's got that whole undead thing going on, so it's a Zombie in addition to whatever creature types it used to have. You'll find lots of ways to take advantage of its new Zombiehood, I'm sure. And now that it's all service, all the time and doesn't care about whatever it was it cared about while alive, it's white instead of whatever color it used to be. One more minor change is that it doesn't have the mana cost the card has.
-- http://magic.wizards.com/en/articles/archive/news/so-much-amonkhet-news-2017-03-27

**Comment by ShawnieBoy** [comment]
The official rules for embalm are as follows:

> 702.127.
>
> Embalm
>
>702.127a Embalm is an activated ability that functions while the card with embalm is in a graveyard. "Embalm [cost]" means "[Cost], Exile this card from your graveyard: Create a token that's a copy of this card, except it's white, it has no mana cost, and it's a Zombie in addition to its other types. Activate this ability only any time you could cast a sorcery."
>
>702.127b A token is "embalmed" if it's created by a resolving embalm ability.

**Comment by ShawnieBoy** [comment]
21926c0ef2137c155dc7173430e663489b316c4b is a first pass of the Embalm mechanic, however I've not been able to remove the mana cost from the token copies. It looks like this would be a card-level change which hasn't been done before in Magarena as far as I can see. Everything else seems to be working fine.

**Comment by melvinzhang** [comment]
The solution is to create a new card def with MagicCardDefinition.token constructor, this also makes the values of the token copyable. Unlike the play mod which uses a static ability which is not copyable. Fix incoming.

**Comment by melvinzhang** [comment]
I tested with TestEmbalm (thanks for provding it!) and it seems to work fine. @ShawnieBoy Please help to check whether the last commits implements all the needed parts and close if it is good.

**Comment by ShawnieBoy** [comment]
Nice elegant solution 👍  Looks good to me.
