### ISSUE TITLE
implement exert mechanic

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#1092]
> Exert allows creatures to give a little more effort to produce unusually good results.
>
> You make the decision whether to exert a creature as you declare it as an attacker. If you choose to have it exert, an ability will trigger and grant you some bonus. As a trade-off, the creature won't untap during your next turn. It's tired. Needs a nap. Attack more later.
>
> You don't have to exert the creature as it attacks. If you don't, no ability will trigger, and it will untap normal during your next turn. Note that as you declare attackers is the only time you can have it exert. You can't wait until later in the turn and then exert it. When your next untap step rolls around, if the creature you exerted is untapped, nothing happens and the exertion cost you nothing. Maybe you found a different way to untap it, or maybe you gave it vigilance. You are clever!
-- http://magic.wizards.com/en/articles/archive/news/so-much-amonkhet-news-2017-03-27

**Comment by ShawnieBoy** [comment]
The official rules for exert are as follows:

>701.37. Exert
>
>701.37a To exert a permanent, you choose to have it not untap during your next untap step.
>
>701.37b A permanent can be exerted even if it's not tapped or has already been exerted in a turn. If you exert a permanent more than once before your next untap step, each effect causing it not to untap expires during the same untap step.
>
>701.37c An object that isn't on the battlefield can't be exerted.

Exerting is linked to the player that exerts it, not the controller of the permanent. If you gain control of another player's creature and exert it, then lose control of it, it will untap during that player's untap step. If you regain control before your next untap, it won't untap.

**Comment by melvinzhang** [comment]
It is not an exert specific issue, more to do with the phrase "doesn't untap during your next untap step", which we do not link to the player (referenced by your), we implement it as "doesn't untap the next time this permanent would untap" 

For example, the same issue occurs for Arbalest Elite which as `{2}{W}, {T}: SN deals 3 damage to target attacking or blocking creature.~SN doesn't untap during your next untap step.`

We should go ahead with exert as it is using `MagicPermanentState.DoesNotUntapDuringNext` for now. I think we can fix all of these cases by having two variants of the state similar to `MagicAbility.CannotBeTheTarget0` and `MagicAbility.CannotBeTheTarget1`

**Comment by melvinzhang** [comment]
created https://github.com/magarena/magarena/issues/1106 to track the bug with "does not untap during your next untap step"

**Comment by ShawnieBoy** [comment]
Will also require a state trigger (whenever you exert a creature)

I keep looking at exert, but having trouble with an optional trigger and passing the effect.

**Comment by ShawnieBoy** [comment]
Exert is used as a cost in Hour of Devastation -  eg `{T}, Exert SN:`

**Comment by ShawnieBoy** [comment]
added Not supported for the time being a9746ec5392ace71117832d0109bf712d625bc0e

**Comment by melvinzhang** [comment]
see 572c019749827d89ea1287
