### ISSUE TITLE
Vessel of Nasceny does not move cards to graveyard if option is not taken

### ISSUE THREAD

**Issue by Muppet1** [magarena/magarena#1094]
[gameplay-report.zip](https://github.com/magarena/magarena/files/885975/gameplay-report.zip)

cards don't go to graveyard when AI uses this.  Not a new bug in 1.83.   No idea what happens when a player uses it will tell you if I find out.

Ok I am pretty sure it is when the AI declines the may part of the card.  Some times it works which is presumably when the AI does pick a card as far as I can tell.

**Comment by melvinzhang** [comment]
@Muppet1 Thanks for the details of when it fails. It helps to narrow down the problem, it is as you mentioned. No cards are moved to graveyard if player declines.
