### ISSUE TITLE
Badly worded log message - {player} may {player} puts an artifact...

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#1095]
From the gameplay report submitted in #1094.

![screenshot00599](https://cloud.githubusercontent.com/assets/2443519/24575555/7b2100ae-16a1-11e7-9ca3-4577c4d51011.jpg)

**Comment by ShawnieBoy** [comment]
Looks like this is Vessel of Nascency - most likely a new phrase since I last did a haul of the tenses in #503

**Comment by ShawnieBoy** [comment]
PN is placed before "put" and changed to "puts" for phrases like "... put a +1/+1 counter on each creature you control", it doesn't seem to be taking into account optional puts.
