### ISSUE TITLE
Refactor groovy calls to MagicWeakenTargetPicker()

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#1096]
See https://github.com/magarena/magarena/commit/e414d31364731c5eefcb302cc0c5a148dc7dd6a5#commitcomment-21682470.

**Comment by melvinzhang** [comment]
The usage is correct. The issue is that this picker is not using all
relevant information to make its decision. For example, a -5/-0 effect, the
important part is the -5.

**Comment by lodici** [comment]
So it's a bug? The constructor ``MagicWeakenTargetPicker(final int amountPower,final int aAmountToughness)`` should be using ``amountPower``?
```
    public MagicWeakenTargetPicker(final int amountPower,final int aAmountToughness) {
         amountToughness = aAmountToughness;
         count = MagicAmountFactory.One;
     }
```

**Comment by melvinzhang** [comment]
Not really a bug, as there is nothing wrong with it currently, just not as smart as it could be.

**Comment by lodici** [comment]
Am I missing something? amountPower is not used so it is a pointless parameter.

**Comment by melvinzhang** [comment]
Perhaps put it another way, there is a bug in MagicWeakenTargetPicker, it that it doesn't differentiate between -1/-0 and -10/-0. Fix on the way.

**Comment by melvinzhang** [comment]
See c9ac82c1b61b876

**Comment by lodici** [comment]
Thanks.
