### ISSUE TITLE
AI bug related to reanimator deck

### ISSUE THREAD

**Issue by firemind** [magarena/magarena#110]
While analyzing the issues with the AI Rating Match System on firemind.ch I stumbled upon something curious.
The duels fail with different java exceptions like these:
- java.lang.OutOfMemoryError: GC overhead limit exceeded
- java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

But they all have this deck in common: https://www.firemind.ch/deck_lists/7445

For comparison this is the whole list of duels that were run. https://www.firemind.ch/ai_rating_matches/109

The first 4 duels in the state "new" are the ones that failed. All of them have the reanimator decklist in common.
https://www.firemind.ch/duels/490261
https://www.firemind.ch/duels/490331
https://www.firemind.ch/duels/490359
https://www.firemind.ch/duels/490521

I thought this information might help track down a deeper issue with the AI or a card in this deck. I will just remove the deck from the gauntlet for now.

**Comment by melvinzhang** [comment]
Thanks for the report. More details of the crash stack trace is needed. How
can we retrieve the crash.log file with the full exception stack trace?

**Comment by firemind** [comment]
Unfortunately the only one still retrievable is the one related to the last duel (since magarena overwrites it every duel). Maybe something I should fix in the next worker. 

I uploaded it as a gist https://gist.github.com/firemind/60311ae42a3523604e42

**Comment by melvinzhang** [comment]
OOM is due to Griselbrand card draw. Fixed since 1.88

IndexOutOfBoundsException is due to Brainstorm. Fixed in 1.89
