### ISSUE TITLE
Review log messages for errors

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#1100]
Inspired by the bug found in #1095, I wondered if there was a systemic way to check log messages.

To this end, I have generated a text file containing a list of log messages generated by abilities/effects in the card script. See [messages.txt](https://github.com/magarena/magarena/files/908100/messages.txt)

Please help scan through messages and add a comment on any mistakes you noticed. Thanks! @lodici @ShawnieBoy

**Comment by melvinzhang** [comment]
This method has proven to be very effective, I have found and four log message issues, eg may reveals -> may reveal (grammar), PN draw  a card -> PN draw a card (double space), PN do -> PN does, PN control -> PN controls.

**Comment by lodici** [comment]
What does the $ symbol mean, as in "Untap target artifact or creature$."?

**Comment by melvinzhang** [comment]
It indicates the position where the selected target will be shown in the text. For example when the player selects his Grizzly Bears, then the log text will show "Untap target artifact or creature (Grizzly Bears)"

**Comment by lodici** [comment]
Ok, thanks.

**Comment by lodici** [comment]
L3857 Target player$'s life total becomes 10 -> Target **player's$** life total becomes 10
L3858 _the same_

**Comment by lodici** [comment]
L3833 Target player$ loses life equal to its power. 
-> Target player$ loses life equal to **his or her** power.
-> Target player$ loses life equal to **their** power.

**Comment by lodici** [comment]
L3784 Target player$ discards a card. Cipher
-> Target player$ discards a card. Cipher.

**Comment by melvinzhang** [comment]
Thanks for pointing out the issues, they have all been fixed.
