### ISSUE TITLE
Alternative display of player in stack/log message

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#1101]
Currently we try to rephrase the message to replace "you"/"your" with the player name. In many cases, this requires adjusting the form of the other words in the message with regex which mostly works but 

1) can lead to very verbose message if "you"/"your" appears many times and the player's name is long 

2) fails for cases missed by the regex and it is hard to catch all possible cases

I think it is better for us to keep to the text on the card and only add text in parenthesis to indicate the player. Similar to what we do for targets. Below is an example of what I mean.

![stack](https://cloud.githubusercontent.com/assets/1620634/24843111/16289774-1dd2-11e7-9f3e-931c8614c023.png)

![log](https://cloud.githubusercontent.com/assets/1620634/24843117/194fc724-1dd2-11e7-9a3c-c9d2a2ab9459.png)

The player name is added once after the first "you"/"your" occurrence.

**Comment by melvinzhang** [comment]
Tag @lodici @ShawnieBoy for your comments and thoughts on this proposal. Feel free to suggest other options as well.

**Comment by ShawnieBoy** [comment]
This would be confusing when the AI is casting these spells. The text would be addressing the reader, but the effects occurring to another player.

**Comment by lodici** [comment]
I quite like the idea. @ShawnieBoy can you give an example of what you mean, thanks.

**Comment by ShawnieBoy** [comment]
>I quite like the idea. @ShawnieBoy can you give an example of what you mean, thanks.

Giving the example above:
Look at the top four cards of your (AI) Library. You may reveal a creature or land card from among them and put it into your hand. Put the rest of the bottom of your library in any order.

This reads as though you the human player are looking at the AI's deck and choosing. Just a simple example there are some cards where both players are referred and it could be misleading who is doing what - especially with triggered effects.

**Comment by ShawnieBoy** [comment]
How about this:
At the beginning of your (AI) upkeep, Bulwark deals X damage to target opponent (player), where X is the number of cards in your hand minus the number of cards in that player's hand.

The second reference to `your hand` could be read as the target player (as `you` are the target), and expect a different sum when the card difference is calculated.

**Comment by lodici** [comment]
I agree, it is confusing. Also on reflection the use of "you" and "your" (ie. second person) when referring to the opponent feels contrived. Third person is more verbose but I think clearer and easier to follow.

**Comment by melvinzhang** [comment]
True, reading "your" for opponent does sounds weird. The word "you" is too easily mistaken for the user, even with the added player name in parenthesis.

For correctness, the above example would have the following message:

"Bulwark deals X damage to target opponent (player), where X is the number of cards in your (AI) hand minus the number of cards in that player's hand."

The condition of a trigger never appears in the message.

**Comment by lodici** [comment]
Another approach could be to treat log messages from the human player's first person point of view. For example:

"Bulwark deals X damage to you, where X is the number of cards in AI's hand minus the number of cards in that player's hand."
