### ISSUE TITLE
"does not untap during your next untap step" refers to the player who controls SN when ability resolves

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#1106]
This is implemented as "does not untap when SN would next untap" regardless of the player.

Fix is to create two variants of MagicPermanentState.DoesNotUntapDuringNext to indicate which player, eg MagicPermanentState.DoesNotUntapDuringNext0 and MagicPermanentState.DoesNotUntapDuringNext1

**Comment by melvinzhang** [comment]
relevant rulings:
>”Your next untap…” refers to the player who controls Spectral Force when the triggered ability resolves. That means if it’s temporarily stolen (such as with Word of Seizing) and attacked with, it will untap in its previous controller’s untap step.
-- http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=118871 (Spectral Force)

>if another player controls Arbalest Elite during your next untap step, the part of the effect that keeps it from untapping does nothing. It won’t try to apply during a future untap step.
-- http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220078 (Arbalest Elite)

**Comment by melvinzhang** [comment]
`doesn't untap during its controller's next untap step` works correctly as it is based on the creature. Though currently the state sticks on the creature and makes it not untap later which is also incorrect.

Relevant rulings:
> Frost Lynx’s ability tracks the creature, not the creature’s controller. That is, if the creature changes controllers before its first controller’s next untap step, then it won’t untap during its new controller’s next untap step.

> If the creature isn’t tapped during its controller’s next untap step (perhaps because it was untapped by a spell), Frost Lynx’s ability has no effect at that time. It won’t try to keep the creature tapped on subsequent turns.

**Comment by melvinzhang** [comment]
Alternative solution is to tag the permanent with MagicAbility.DoesNotUntap with a static that is removed by a trigger. The static will only apply the ability during the correct player's turn and be removed once the untap step is over.

**Comment by ShawnieBoy** [comment]
I'd go with that option, it would be clearer than having multiple versions of the same effect. Although it would only be removed during the correct player's untap step.
