### ISSUE TITLE
Show Spirit Link as source of life gain in log message.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#1112]
![screenshot](https://cloud.githubusercontent.com/assets/2443519/25577531/a272c0fa-2e5e-11e7-9149-8a1f2211b24e.jpg)

[Lavaborn Muse](http://magiccards.info/query?q=lavaborn+muse&v=card&s=cname) deals 3 damage to AI but [Spirit Link](http://magiccards.info/10e/en/45.html) is attached to Lavaborn Muse so AI gains that much life instead. In the log at ``017:UP`` it shows "...Lavaborn Muse deals 3 damage to Monty Cheater", then in the next message it shows "Monty Cheater gains 3 life.".

It is correct but I think confusing. Would it be possible to add the reason for the gain by adding the card name as a suffix link, eg. "Monty Cheater gains 3 life [Spirit Link]".

**Comment by ShawnieBoy** [comment]
This looks similar to #531 
With the life gain, this isn't restricted to Spirit Link - [Vampiric Link](http://magiccards.info/pc/en/92.html), [Armadillo Cloak](http://magiccards.info/ema/en/195.html), [Soul Link](http://magiccards.info/ap/en/120.html), [Spirit Loop](http://magiccards.info/ts/en/42.html)

The source name can be added, as thankfully these all use the same groovy. But, I still think there could be another look at getting more info onto the log.

**Comment by ShawnieBoy** [comment]
#628 Shows that sources were included along with the, um, event icon?

**Comment by melvinzhang** [comment]
This is a special case of #531, it would be better to address it there rather than create special cases on a card by card basis.

**Comment by lodici** [comment]
The problem with these old issues is out of sight out of mind but I agree #531 seems to be similar so I will close this.
