### ISSUE TITLE
Champion of Lambholt Does Not Prevent Blocking As Expected

### ISSUE THREAD

**Issue by dabgdk** [magarena/magarena#1121]
Thank you for creating Magarena.

When using "Champion of Lambholt", I've noticed that my opponent is able to block with creatures of lesser power. In the game attached to this post, I have 4 +1/+1 counters on it, and a "Stone Throwing Devils" controlled by my opponent (which is a 1/1) was able to block.

I don't think this was a special circumstance (such as Lambholt's ability being disabled in some way). Is this happening because Stone Throwing Devils is black?

[gameplay-report.zip](https://github.com/magarena/magarena/files/1009080/gameplay-report.zip)

**Comment by dabgdk** [comment]
PS: I am using version 1.83, so this issue might have been fixed in 1.84. No idea.

**Comment by ShawnieBoy** [comment]
I've been able to replicate this - unfortunately the gameplay report doesn't include the +1/+1 counters, so had to play a bit further.

![2017-05-17_224135](https://cloud.githubusercontent.com/assets/2363180/26177573/023a79d8-3b52-11e7-9a7f-85c3b70698d9.png)

Here a 3/3 Champion has allowed a 2/3 and a 1/1 to block

**Comment by ShawnieBoy** [comment]
I have a feeling that the ability is only being applied to the Champion itself, and not to the other creatures.

**Comment by melvinzhang** [comment]
Found a couple of problems. 

First, this was applied at the wrong layer, ability layer instead of game layer, so the PT changes due to counters were not considered (counters are applied at a layer after ability).

Second, the "creatures you control" refer to the wrong "you" because it is interpreted as:
"Creatures with power less than Champion of Lambholt's power gain the ability 'This creature can't block creatures it's controller controls.'"

**Comment by melvinzhang** [comment]
For the second issue, we will handle "can't block" specially from the other "can't something" because can't block could specify a list of creatures.

**Comment by dabgdk** [comment]
I'm glad the first issue was easy to fix.

I realize that the second issue is tougher to fix. Perhaps, as a temporary step in the right direction, this change could be made:

"Creatures with power less than Champion of Lambholt's power gain the ability 'This creature cannot block Champion of Lambholt.'"

That's not entirely correct, but would be slightly better than what exists now.

**Comment by dabgdk** [comment]
Or, perhaps even better:

"Opponent creatures with power less than Champion of Lambholt's power gain the ability 'This creature cannot block.'"

Obviously that really screws up multiplayer games, but it would work correctly in most cases for one on one games.

**Comment by melvinzhang** [comment]
@dabgdk that's a great suggestion for using "cannot block". It would work just fine.
