### ISSUE TITLE
Undo back to "declare attackers" shows "Choose a card" instead of player's hand

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#1123]
For example, using TestScry.
1. Pass twice to get to M2
2. Undo to return to DA
3. Expect to see hand zone, but instead sees empty "Choose a card" zone

A related issue is any click of undo will briefly show the empty "Choose a card" zone before showing the correct zone.

Again, using TestScry.
1. Pass once to get to DA
2. Undo to return to M1
3. Expect no change in hand shown, but instead UI flickers to show an empty "Choose a card" zone then flickers back to showing the hand.

@lodici seems to have been caused by 9fd38035a73b4af addition of `clearCardsToChoose()` to performUndo

**Comment by lodici** [comment]
Thanks, will look into it.

**Comment by melvinzhang** [comment]
@lodici I quite liked the improvements implemented in 9fd3803 and 5ec046e. Couldn't we just remove the single call to "clearCardsToChoose()" in performUndo to solve this?

**Comment by lodici** [comment]
I think it might be more complicated than I thought and I don't have the time or interest really to look into it right now. I believe I added ``clearCardsToChoose`` to undo to remove the list of choice cards from hanging around which was causing the choice zone to be shown (still with the old choice cards) when moving the mouse over a subsequent prompt. Something like that anyway.

**Comment by melvinzhang** [comment]
Hmm, clearing on undo should not be needed. The responsibility of clearing the showed cards is with the *Choice object's getPlayerChoiceResults method. It is possible that one of these methods missed a call to clear the cards.

**Comment by lodici** [comment]
To replicate the reason for this line, check out the commits and run the following amended TestSearch. Play Misty Forest from your hand, then activate it, pass and the choice zone should appear with three land cards. Undo everything back to start of test. Move mouse over prompt and the choice zone re-appears with the three cards.

```
package magic.test;

import magic.model.MagicDuel;
import magic.model.MagicGame;
import magic.model.MagicPlayer;
import magic.model.phase.MagicDrawPhase;

class TestSearch extends TestGameBuilder {
    public MagicGame getGame() {
        final MagicDuel duel=createDuel();
        final MagicGame game=duel.nextGame();
        game.setPhase(MagicDrawPhase.getInstance());
        final MagicPlayer player=game.getPlayer(0);
        final MagicPlayer opponent=game.getPlayer(1);

        MagicPlayer P = player;

        P.setLife(6);

        addToLibrary(P, "Bayou", 1);
        addToLibrary(P, "Badlands", 1);
        addToLibrary(P, "Goblin King", 4);
        addToLibrary(P, "Forest", 20);
        addToLibrary(P, "Island", 20);
//        createPermanent(P,"Rupture Spire",false,6);
        createPermanent(P, "Grizzly Bears", false, 2);
        createPermanent(P, "Bow of Nylea", false, 1);
//        createPermanent(P, "Buried Ruin", false, 4);
//        createPermanent(P, "Petrified Field", false, 1);
        createPermanent(P,"Forest",false,2);
        createPermanent(P,"Plains",false,2);

        addToHand(P, "Misty Rainforest", 1);
        addToHand(P, "Buried Ruin", 1);
        addToHand(P, "Petrified Field", 1);
        addToHand(P, "Argivian Find", 1);

//        addToGraveyard(P, "Terramorphic Expanse", 8);
//        addToGraveyard(P, "Rampant Growth", 8);
//        addToGraveyard(P, "Farseek", 8);
//        addToGraveyard(P, "Verdant Catacombs", 1);
//        addToGraveyard(P, "Sylvan Scrying", 2);
        addToGraveyard(P, "Perilous Forays", 1);
//        addToGraveyard(P, "Primeval Titan", 1);
//        addToGraveyard(P,"Altar of Bone",1);
//        addToGraveyard(P, "Goblin Matron", 1);
//        addToGraveyard(P, "Grizzly Bears", 2);

        P = opponent;

        P.setLife(6);

        addToHand(P, "Misty Rainforest", 1);
        addToHand(P, "Buried Ruin", 1);

        addToLibrary(P, "Mountain", 20);
        createPermanent(P,"Rupture Spire",false,9);
        createPermanent(P, "Grizzly Bears", false, 1);
        addToGraveyard(P, "Ink-Eyes, Servant of Oni", 1);

        return game;
    }
}
```

**Comment by melvinzhang** [comment]
Thanks for the test case, I am able to replicate the bug.

**Comment by melvinzhang** [comment]
This bug also occurs in the current master without the two commits.

**Comment by melvinzhang** [comment]
restored the two commits in 73a661
