### ISSUE TITLE
Time for a new menu font...

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#1124]
Instead of plain old SansSerif, I rather like JaceBelerenBold at 24, the Main Menu heading/version text looks a bit cramped, but the main options looks very distinctive.
![screenshot00610](https://cloud.githubusercontent.com/assets/2443519/26270657/b150ec1a-3cf4-11e7-8f9c-806aa6fb99d3.jpg)

**Comment by lodici** [comment]
Although not so good in Russian!
![screenshot00611](https://cloud.githubusercontent.com/assets/2443519/26270737/4de183b4-3cf5-11e7-9176-bb7de6a0a151.jpg)

**Comment by lodici** [comment]
But ok in Italian. Possibly something to do with unicode?
![screenshot00612](https://cloud.githubusercontent.com/assets/2443519/26270767/a6c53b6a-3cf5-11e7-88c7-eeb5ec887944.jpg)

**Comment by ShawnieBoy** [comment]
It's to do with the font - it doesn't have all characters, only basic latin

**Comment by lodici** [comment]
Ah, thought it might be something like that. Thanks. In that case would probably need look at updating themes to specify the menu fonts although I do think it might be worth looking at defining an optional built-in alternative font scheme that replaces the standard Java fonts with those included with cardbuilder, might as well make use of them if they are there and it would be nice to give Magarena a more distinctive default look.

**Comment by ShawnieBoy** [comment]
Actually, I'm surprised at how much is in the fonts - Eth and Thorn are both present in capital and small forms. Not much use for Russian however.

**Comment by LoubiTek** [comment]
Can your edit the font?
Because I just reversed the letter R for the example.
After, if possible. I can see to create with Inkscape or this software for missing letters.
Since the time I want to learn and learn more about it.
![alt tag](http://i.imgur.com/xPAlgRM.png)

**Comment by ShawnieBoy** [comment]
It is possible, although I'm not an expert in kerning and ligatures, as the style for the cyrillic characters wouldn't be a straight mirror - feel free to give it a go though - had issues with the main font for english in the cardbuilder - see #621 for some images

**Comment by lodici** [comment]
> Can your edit the font?

Sorry no idea, @ShawnieBoy knows more about this black art.

**Comment by lodici** [comment]
![screenshot](https://user-images.githubusercontent.com/2443519/26993769-8fa1dade-4d5c-11e7-8403-3defab6c6e47.jpg)

Since the menu style has changed it seemed a good time to implement the font update as well. All languages except Russian now use JaceBelerenBold for the menu options. A translation can enable/disable the custom font via a setting in the header line (see 5fe0747efebae7b64bbcceddfd3efccd96aca6b4). As a safeguard there is also a new global setting ``custom.fonts`` (5b270f7b9f2f3d25121a3b10c418326b0d6680c4) which can be used to switch custom fonts on/off  regardless of the translation file setting - this is currently a non-UI setting and requires manually updating ``general.cfg``.

**Comment by lodici** [comment]
Updated the wiki with information about the [header line.](https://github.com/magarena/magarena/wiki/Translating-Magarena#header-line)
