### ISSUE TITLE
Godhead of Awe only affects opponent creatures. Should be all?

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#1133]
AI played [Godhead of Awe ](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=142019) and reset the p/t for all my creatures to 1/1 but other creatures it controls were not affected. Should it not be all creatures including its own?

[gameplay-report.zip](https://github.com/magarena/magarena/files/1027129/gameplay-report.zip)

**Comment by ShawnieBoy** [comment]
The game report doesn't display the AI creatures with power toughness other than 1/1

**Comment by ShawnieBoy** [comment]
If Stormbound Geist had a +1/+1 counter on it (not saved in gamestate) It would appear as a 2/2, same as if other p/t effects were still affecting them while their base pt became 1/1. Only thing I can think of.

**Comment by ShawnieBoy** [comment]
Forgot to look at the screenshot - the aura is in the graveyard in the report:

Stormbound Geist has a +1/+1 counter on it, so is now a 2/2 - the Tormented Soul has an enchantment on it, making the 1/1 into a 3/2

**Comment by ShawnieBoy** [comment]
Kinda shows how counters and auras are kinda needed in gameplay reports as well, but that's another issue 😁

**Comment by lodici** [comment]
Thanks for the explanation. :+1:

**Comment by ShawnieBoy** [comment]
The updated oracle text for the card kinda explains better than the printed version, referring to 'base power and toughness 1/1'
![2017-05-24_213109](https://cloud.githubusercontent.com/assets/2363180/26424207/56bbc41e-40c8-11e7-9c72-4f1f755dabca.png)

**Comment by lodici** [comment]
Yes that might have helped to clarify things. Also maybe some way to show how the displayed P/T was calculated using for example a popup. Probably quite tricky to do. Also what is going on with the log?

**Comment by ShawnieBoy** [comment]
The log seems to go like that when loading a game-state - although I might just have a dodgy build, had to recently re-install Windows.

Having some way to see what the base p/t is, or even the printed p/t and it's adjustments would be useful in play - Sometimes a creature has been copied, p/t set, then adjusted again with global effects that you're not really sure what it is anymore!

**Comment by lodici** [comment]
> The log seems to go like that when loading a game-state - although I might just have a dodgy build, had to recently re-install Windows.

I have seen this happen literally once or twice since I have been working on Magarena (ie. years), it looks like a resizing issue but I have never been able to replicate since it has happens so infrequently.

> Sometimes a creature has been copied, p/t set, then adjusted again with global effects that you're not really sure what it is anymore!

I had something like this in this game too with Evil Twin where it is difficult to know which is the copy with the new ability conveyed by Evil Twin, especially once it scrolls out of view in the log.

**Comment by ShawnieBoy** [comment]
>I have seen this happen literally once or twice since I have been working on Magarena (ie. years), it looks like a resizing issue but I have never been able to replicate since it has happens so infrequently.

I'm getting it pretty often at the moment - at first I thought it was the drag-drop method of starting a saved game. Just tried it now, and worked in a normal duel, then loaded the test and log went again.

**Comment by lodici** [comment]
What version of java are you running?

**Comment by ShawnieBoy** [comment]
vers 8 upd 131

**Comment by ShawnieBoy** [comment]
>How to do players keep track of stuff like this in real games? Do they keep notes?

Would depend on the setting, don't know about tournaments, but could range from 'taking' the killed creature once the ability was activated and putting it behind - maybe a token on the creature or a note. Normally it's memory - only if there's a few knocking about would it get confusing.

Having the ability to add ability text to cards would solve this confusion - as the copy would have an extra ability the original doesn't.

**Comment by lodici** [comment]
Replicated. It looks like the drag-drop is the cause. I will raise a new issue.
