### ISSUE TITLE
Basandra, Battle Seraph - opponent creature did not attack.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#1135]
[gameplay-report.zip](https://github.com/magarena/magarena/files/1033987/gameplay-report.zip)

During opponent's UP, I activate Basandra, Battle Seraph "target creature attacks this turn if able" on opponent's Noble Hierarch but Noble Hierarch did not attack and I am pretty sure it was able to.

However, if I wait until M1 it does seem to work.

**Comment by melvinzhang** [comment]
The included game.log was helpful. What happen was the AI decided that Noble Hierarch should not attack and be used for mana instead, this is something decided during Draw phase. The bug is that this decision overwrote the must attack part, which should not happen.

**Comment by melvinzhang** [comment]
It always seemed rather odd to me that at Draw phase, the AI needed to decide for each permanent that can both attack and produce mana whether to exclude it from combat or exclude it from mana production. It seems too early to make this choice. Also this is the only extra decision the AI makes that is not something the player makes.

**Comment by lodici** [comment]
I must admit I did not consider that the AI could tap Noble Hierarch in order to prevent it attacking, that would have been a pretty clever play.
