### ISSUE TITLE
UI text errors, typos, improvements, etc.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#1139]
Raised by @LoubiTek in https://github.com/magarena/magarena/pull/1138#issuecomment-305290110 -

```
*Add 'it'*
Ref: Line n°52 | 0820565042 = Click on a creature to declare as attacker or remove it from combat.|Press {f} to continue.
Line n°54 | 2533594575 = Click on a creature to declare as blocker or remove it from combat.|Press {f} to continue.

*For more comprehension*
Line n°95 | 0615792264 = Confirmez pour quitter et retourner sur vôtre bureau
In English: Confirm to quit and return to your desktop

*Remove 'to desktop'*
Line n°105 | 3083392996 = Quit

*Add letter 'm'*
Line n°325 | 0391863698 = Decrease the quantity by one. Minium is one.
Line n°325 | 0391863698 = Decrease the quantity by one. Minimum is one.
```

**Comment by LoubiTek** [comment]
*Add Window Mode*
Line n°509 | 2823720574 = Toggle Full-Screen Mode
Line n°??? | ?????????? = Toggle Window Mode

**Comment by lodici** [comment]
> *For more comprehension*
Line n°95 | 0615792264 = Confirmez pour quitter et retourner sur vôtre bureau
In English: Confirm to quit and return to your desktop
>
> *Remove 'to desktop'*
Line n°105 | 3083392996 = Quit
>
> Add Window Mode
Line n°509 | 2823720574 = Toggle Full-Screen Mode
Line n°??? | ?????????? = Toggle Window Mode

It is all a bit subjective but I think the current English text is fine. However, please amend as required if it makes it clearer in the translation. There is no requirement to translate the English text verbatim, whatever works in the translated language would be best.

> *Add letter 'm'*
Line n°325 | 0391863698 = Decrease the quantity by one. Minium is one.
Line n°325 | 0391863698 = Decrease the quantity by one. Minimum is one.

Thanks, I have actually simplified the text in 8050e48.

> *Add 'it'*
Ref: Line n°52 | 0820565042 = Click on a creature to declare as attacker or remove it from combat.|Press {f} to continue.
Line n°54 | 2533594575 = Click on a creature to declare as blocker or remove it from combat.|Press {f} to continue.

@melvinzhang, @ShawnieBoy the current text is declare attacker with "it" and declare blocker without, ie  -
```
0820565042 = ▫Click on a creature to declare as attacker or remove it from combat.|Press {f} to continue.
2533594575 = ▫Click on a creature to declare as blocker or remove from combat.|Press {f} to continue.
```
I think it is better without the "it". What do you think?

**Comment by melvinzhang** [comment]
I'd go with without the 'it' as you've suggested.

**Comment by lodici** [comment]
@LoubiTek thanks for highlighting the inconsistency with the use of "it" in the declare attacker/blocker prompts. As it turns out, in English it reads better without the "it".

**Comment by LoubiTek** [comment]
For information, adding the display mode was more obvious.
Because when you click to switch to Full-Screen Mode, it remains with the same text even when it is in Window Mode.
That is why I think to add this line is better for understand..

**Comment by lodici** [comment]
Are you referring to
![screenshot00620](https://user-images.githubusercontent.com/2443519/26892429-252b9274-4bb0-11e7-8e4e-9f9657d61fd1.jpg)
and in French-
![screenshot00621](https://user-images.githubusercontent.com/2443519/26892452-3eaee35e-4bb0-11e7-9d1d-d4366d4e2c0f.jpg)
?

**Comment by lodici** [comment]
On the other hand if you are referring to 
![screenshot00622](https://user-images.githubusercontent.com/2443519/26893612-b9746188-4bb3-11e7-8d90-ea3441dbebc8.jpg)

then I would say that the wording is sufficient and that most people would understand that if you are in full screen mode then it means to switch back to windowed mode and vice-versa. I could be wrong, but that is my assumption.

**Comment by LoubiTek** [comment]
I'm running Windows 10.
And yes when I launch full screen mode, I only see the text below. Otherwise I have the same thing you have shown in window mode.

But I'm talking about this: http://imgur.com/a/zOBja

In most other games.
The UI and make this way, because it and more logical.

Yeah good idea ! 👍

**Comment by lodici** [comment]
Thanks for the clarification - looks like we might need to increase the width of the menu panels a touch as well.
