### ISSUE TITLE
Game board side-bar updates.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#114]
![screenshot00059](https://cloud.githubusercontent.com/assets/2443519/6766580/99c3495e-d003-11e4-83ca-d23d8d782e5a.png)
- [x] merge user-action panel with player panel.
- [x] improve signal-to-noise ratio in user-action panel by restricting to user-decision prompts only.
- [x] suppress user-action panel if playing an AI vs AI game.
- [x] position of the four side-bar components should be configurable.
- [x] remove priority player from turn status panel. Inconsistent.
- [x] display overall duel score in turn status panel.
- [x] display duel target as tooltip (eg. "First player to win 4 games wins the duel.").
- [x] display number of items in stack.

**Comment by lodici** [comment]
You can now re-arrange the components in the duel side-bar. No UI as yet but you can do it manually by adding or updating the following property in ``\Magarena\general.cfg`` -
```
duelSidebarLayout=LOGSTACK,PLAYER2,TURNINFO,PLAYER1
```
Simply move the order around to have it reflected in the display (game restart required).

I have also made the above order the default order -
![screenshot00071](https://cloud.githubusercontent.com/assets/2443519/6770632/0315b396-d0be-11e4-9775-2ba7e8eeea21.png)

**Comment by lodici** [comment]
Added dialog to arrange side-bar components
![duelsidebarlayoutdialog](https://cloud.githubusercontent.com/assets/2443519/6847029/383a9f46-d3bb-11e4-95be-0c4c381b87c8.gif)

**Comment by ShawnieBoy** [comment]
Nice

**Comment by lodici** [comment]
I have added a new setting to the gameplay preferences tab. Off by default, if enabled it will suppress the prompts in the user action panel unless a decision is required by you. I find this a big improvement on the signal-to-noise ratio not least of which is the removal of the prompt that tells you what the AI is going to play about 5 seconds before it plays it.. 

I could not come up with a particularly elegant solution (see [``isUserActionPromptHidden``](https://github.com/magarena/magarena/commit/234ee1c942ca73214f5b886fedc7a01c4ff04ef5#diff-6f688fc46237c4c1fe999947638a3af8R539) in ``SwingGameController``) so if you know of a better way please let me know. 

I have played quite extensively with this setting enabled and so far it seems to be working as expected but there is no substitute for more people testing so please give it a go and let me know what you think. My intention is to release it on by default in 1.61 and if there are no major objections remove it as a setting in 1.62.

**Comment by melvinzhang** [comment]
The reason AI message are shown is due to the showMessage call in getArtificialNextEventChoiceResults. I've added a check with getHideAiActionPrompt before calling showMessage.

**Comment by melvinzhang** [comment]
Btw, why does clearUserAction prompt have the condition (game.getPhase().getType() != MagicPhaseType.DeclareAttackers) ?

**Comment by melvinzhang** [comment]
I think I see it, you have to avoid DeclareAttackers because otherwise after choosing the first attacker the message is removed. I think the MagicChoices were not designed with the message being cleared after the first response. We can get the same effect without the awkward check by clearing the user action prompt when it is the AI's decision. Implemented in https://github.com/magarena/magarena/commit/e23debb574019af16a309ca94961092f9a7f8ba9#

**Comment by melvinzhang** [comment]
The final implementation is simpler: if hide AI choices is true, during AI's choice show an empty message to clear the user action prompt, otherwise show the actual message.
