### ISSUE TITLE
New style menu

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#1143]
More consistent look with the header/footer but also this layout is more translation friendly in that there is effectively no width restriction on the menu text. Thoughts?

![screenshot](https://user-images.githubusercontent.com/2443519/26907153-466059fa-4be9-11e7-8b33-9d1eb87b49ab.jpg)

![screenshot](https://user-images.githubusercontent.com/2443519/26907225-e53afdc8-4be9-11e7-9080-bb56017fcb8d.jpg)

**Comment by melvinzhang** [comment]
Looks cleaner and simpler, I like it.

**Comment by LoubiTek** [comment]
I would also like to modify or create the menu interface.
How to do? I can not find the files. There are too many!
I just noticed that everything was make with the code.

Is it possible to create real buttons with textures?
I would apply a half-transparent layer over the background with textured buttons.

I'll see what I can do!
Although I do not know the exact sizes...
I think the resizing of the game will be done, whatever happens.

**Comment by LoubiTek** [comment]
Here is the beginning of the project under Krita, if necessary I can provide it.
![alt tag](http://i.imgur.com/OztNiIy.png)
Do you have a discord / IRC or anything else?
To you join and so not to publish without stop.
Also if someone ever logs in, we can talk better.

**Comment by lodici** [comment]
There is currently no skinning mechanism implemented. Every now and again I make a half-hearted attempt to look at the legacy [themes ](https://github.com/magarena/magarena/wiki/Customizing-Magarena#themes) code but this is really just mainly for colors and a few background textures. My main focus has been on implementing a consistent minimal-style UI using mono-color icons and text which is more or less done I think except for better fonts, although languages such as Russian can be problematic (see #1124).

> Do you have a discord / IRC or anything else?

Afraid not.

**Comment by LoubiTek** [comment]
Okay, I understand and it's very clever to have thought like this.
So if I ever want to make my own theme I would gladly do it.
I must first finish the translation!

Too bad not to have a more direct contact. 😞
