### ISSUE TITLE
implement afflict <n> mechanic

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#1150]
"Whenever this creature becomes blocked, defending player loses n life."

**Comment by ShawnieBoy** [comment]
The official rules for afflict are as follows:
```
702.129. Afflict

702.129a Afflict is a triggered ability. "Afflict N" means "Whenever this creature becomes blocked, defending player loses N life."

702.129b If a creature has multiple instances of afflict, each triggers separately.
```
- If multiple creatures block a creature with afflict, afflict triggers only once.
- Afflict causes the defending player to lose life; it's not damage or combat damage.
- If a creature is attacking a planeswalker, that planeswalker's controller is the defending player.
- Afflict resolves before combat damage is dealt. If this loss of life brings a player to 0 life or less, that player loses the game immediately. A blocking creature with lifelink won't deal combat damage in time to save that player.
