### ISSUE TITLE
Crash - "Brimaz King of Oreskos" and "Archbound Ravager" interaction

### ISSUE THREAD

**Issue by MarcusAseth** [magarena/magarena#1156]
Magarena just crashed.

I've attacked with my creatures and the AI used "Brimaz King of Oreskos" to block one of my creatures, at which point I've activated "Archbound Ravager" ability to sacrifice said blocked creature, and I suspect the game crashed because "Brimaz King of Oreskos"'s blocked creature disappeared and he didn't get to resolve his ability to create his cat soldier token even though he had blocked since technically he wasn't blocking anymore, so he freaked out and crashed the game :(

Crash log data below

[logs.zip](https://github.com/magarena/magarena/files/1119209/logs.zip)

**Comment by ShawnieBoy** [comment]
There is a problem with the groovy for Brimaz - it always assumes that the attacker remains on the battlefield. This also makes me think that the token should still enter the battlefield, it's not actually a targeted effect. I'll see if I can find some rulings on this - token blocking nothing vs no token.

**Comment by lodici** [comment]
You might also want to check this refactor - https://github.com/magarena/magarena/commit/9d5015632d7e1ddcd31b9d9b1e320a75558b192a#diff-38d04d9bfc95d9418efeca43d2af2e9b.

I can't see anything obvious but it is possible it is less robust with null objects after refactoring the two ``for..loops`` using ``Stream.concat(...)``.
