### ISSUE TITLE
Activated abilities which self-sacrifice: AI will use them if the 'self' is the only possible target.

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#116]
After playing with the newly implemented 'protection from chosen', the AI sacrificed Benevolent Bodyguard (Sacrifice SN: Target creature gets protection from the color of your choice until end of turn.) while it had no other creatures on the battlefield. I'm assuming it was intending to give the protection to itself.

**Comment by PalladiaMors** [comment]
Another example of this problem, with the AI sacrificing Goblin Sledder as soon as it entered the battlefield, with no possible targets in play. I've actually seen it having to pump an opponent's creature after doing that. I think this looks really bad if a new player comes across it, would be important to figure out a way to solve it. This example involved MCTS at level 8.

LOG (C): Play Mountain. Put Mountain onto the battlefield.
LOG (C): Pay {R}. Tap Mountain. Play Goblin Sledder.
LOG (C): Put Goblin Sledder onto the battlefield.
LOG (C): Play activated ability of Goblin Sledder.
LOG (C): Target creature gets +1/+1 until end of turn. (no legal targets)

**Comment by ShawnieBoy** [comment]
Added AI activation restrictions for self-sacrifice self-target abilities 9cda8873159dc0abc405f4ced7d14fc7d7b2de78
