### ISSUE TITLE
Frostwielder (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1160]
name=Frostwielder
image=http://magiccards.info/scans/en/chk/167.jpg
value=2.867
rarity=C
type=Creature
subtype=Human,Shaman
cost={2}{R}{R}
pt=1/2
ability={T}: SN deals 1 damage to target creature or player. If a creature dealt damage this way would die this turn, exile it instead.
timing=main
oracle={T}: Frostwielder deals 1 damage to target creature or player.\nIf a creature dealt damage by Frostwielder this turn would die, exile it instead.

**Comment by ShawnieBoy** [comment]
The ability which tracks damage and whether to exile, is separate from the activated ability. If Frostwielder deals combat damage to a creature which dies, it is also exiled

**Comment by kelsioboy** [comment]
I did not pay attention to that detail :)

**Comment by kelsioboy** [comment]
I'll close this.
