### ISSUE TITLE
Gideon, Martial Paragon (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1161]
name=Gideon, Martial Paragon
image=http://magiccards.info/scans/en/akh/270.jpg
value=2.500
rarity=M
type=Planeswalker
subtype=Gideon
cost={4}{W}
loyalty=5
ability=+2: Untap all creatures you control.~Creatures you control get +1/+1 until end of turn.  ;\
        0: Until end of turn, SN becomes a 5/5 Human Soldier creature with indestructible that's still a planeswalker.~Prevent all damage that would be dealt to SN this turn.;\
        −10: Creatures you control get +2/+2 until end of turn.~Tap all creatures your opponents control.
timing=main
oracle=+2: Untap all creatures you control. Those creatures get +1/+1 until end of turn.  \n0: Until end of turn, Gideon, Martial Paragon becomes a 5/5 Human Soldier creature with indestructible that's still a planeswalker. Prevent all damage that would be dealt to him this turn.\n−10: Creatures you control get +2/+2 until end of turn. Tap all creatures your opponents control.

**Comment by melvinzhang** [comment]
Nice usage of the card script features to create this card.
