### ISSUE TITLE
Kumano, Master Yamabushi (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1162]
name=Kumano, Master Yamabushi
image=http://magiccards.info/scans/en/chk/176.jpg
value=4.234
rarity=R
type=Legendary,Creature
subtype=Human,Shaman
cost={3}{R}{R}
pt=4/4
ability={1}{R}: SN deals 1 damage to target creature or player. If a creature dealt damage this way would die this turn, exile it instead.
timing=main
oracle={1}{R}: Kumano, Master Yamabushi deals 1 damage to target creature or player.\nIf a creature dealt damage by Kumano this turn would die, exile it instead.

**Comment by ShawnieBoy** [comment]
see #1160
