### ISSUE TITLE
Liliana, Death Wielder (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1164]
name=Liliana, Death Wielder
image=http://magiccards.info/scans/en/akh/275.jpg
value=2.500
rarity=M
type=Planeswalker
subtype=Liliana
cost={5}{B}{B}
loyalty=5
ability=+2: Put a -1/-1 counter on target creature.;\
        −3: Destroy target creature with a -1/-1 counter on it.
timing=main
requires_groovy_code
oracle=+2: Put a -1/-1 counter on up to one target creature.\n−3: Destroy target creature with a -1/-1 counter on it.\n−10: Return all creature cards from your graveyard to the battlefield.

[
    new MagicPlaneswalkerActivation(-10) {
        @Override
        public MagicEvent getPermanentEvent(final MagicPermanent source,final MagicPayedCost payedCost) {
            return new MagicEvent(
                source,
                this,
                "Return all creature cards from PN graveyard to the battlefield."
            );
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            CREATURE_CARD_FROM_GRAVEYARD.filter(event) each {
                game.doAction(new ReanimateAction(
                    it,
                    event.getPlayer()
                ));
            }
        }
    }
]

**Comment by melvinzhang** [comment]
@kelsioboy note that `Put a -1/-1 counter on up to one target creature.` should be translated to `You may put a -1/-1 counter on target creature.` so that the player can avoid choosing a target.
