### ISSUE TITLE
Structural Collapse (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1168]
name=Structural Collapse
image=http://magiccards.info/scans/en/gtc/107.jpg
value=1.375
rarity=C
type=Sorcery
cost={5}{R}
effect=Target player sacrifices an artifact~and *that player* sacrifices a land.~SN deals 2 damage to *that player*.
timing=main
oracle=Target player sacrifices an artifact and a land. Structural Collapse deals 2 damage to that player.

**Comment by ShawnieBoy** [comment]
This is interesting - linked effects are generally dependant on the first parts resolving. As there's no targeting involved all effects resolve. Although it does have the issue of the last effects resolving first.
@melvinzhang Could something like this be incorporated into the engine for sacrifice... and a... ?

**Comment by melvinzhang** [comment]
Yes, "sacrifice <permanent> and <permanent>" can be parsed automatically.
