### ISSUE TITLE
Implement on-demand image download.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#117]
You have just downloaded Magarena and want to get straight to playing a duel so you can try out your all-conquering XYZ deck except you can't because the deck's cards (all beginning with "X", "Y", and "Z") have no images and so you have to wait for all 9000+ playable images to download first. And this might take a while, maybe over an hour!

Consider adding an on-demand download on starting a new duel that downloads just the cards needed to play the duel. Perhaps a flash "please wait" screen displaying the cards as they are downloaded.

**Comment by melvinzhang** [comment]
Download image on demand has been released.
