### ISSUE TITLE
target costs should not be skipped with "no legal target"

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#1177]
Currently costs which requires a target and the target is not available will simply continue with "no legal target". This is to account for triggers which sometimes require a target.

However when paying costs to activate an ability, such costs should not be skipped and if unpayable the player should undo and try to pay again.

For the AI, a unpayable cost is an instant game loss for the player suppose to make the payment. This will steer the AI away from such moves.

**Comment by melvinzhang** [comment]
Example is Dune Diviner with one Desert and one Plains. When activating the ability and paying "{1}, Tap an untapped Deset you control". The correct sequence is pay {1} with Plains, then tap Desert. 

The incorrect sequence is pay {1} with Desert, then skip the second cost, it shows as "no legal target"  in the log. If the incorrect sequence is used, the player should get stuck at the second cost and be prompted that the cost is unpayable and the only action is to undo.

**Comment by melvinzhang** [comment]
MagicTargetChoice needs to distinguish between two uses, when used as part of a cost or when as an effect.

**Comment by melvinzhang** [comment]
Change prompt to indicate to the player that he/she must undo.

**Comment by melvinzhang** [comment]
TestNoChoice 1:
Activate "Dune Diviner", tap Desert to pay {1}.
![no-target](https://user-images.githubusercontent.com/1620634/28148273-43ade854-67b8-11e7-8cec-c27aa853019e.png)

TestNoChoice 2:
Activate "Foul Familiar".
![no-mana](https://user-images.githubusercontent.com/1620634/28148290-59449f82-67b8-11e7-9b81-6c0c5a81f056.png)

@ShawnieBoy @lodici appreciate any suggestion on the wording and how it is shown to the player.

**Comment by melvinzhang** [comment]
Just noticed that the text for mana has a different structure from the first one. To make them match it should be reworded as `There are not enough mana to pay {B}, please undo.`

**Comment by lodici** [comment]
``There are not enough mana to pay...`` feels awkward. ``There are not enough mana sources to pay...`` is fine but once you remove the 'sources' it would be better to use ``There is not enough mana to pay...``.

**Comment by lodici** [comment]
This seems like a good solution BTW. If we can avoid modal prompts I think that would be a good thing.

**Comment by melvinzhang** [comment]
Sorry, it should be `mana sources` earlier. Now that you mention it, using `is not enough mana to pay` sounds just as good and it is shorter and clearer. Let's go with that.

To recap, the current phrasing is 

1. `There are no valid options, please undo.`

2. `There is not enough mana to pay <cost>, please undo.`

**Comment by melvinzhang** [comment]
The first one still looks odd as it as two parts, the original choice message and the undo message. I think with some text manipulation I can rewrite the first one without the `Choose an untapped desert you control.` to

`There is no untapped desert you control, please undo.`

This brings in closer in line with the mana wording and removed the two separate sentence. Does this sound better?

**Comment by lodici** [comment]
Just playing ``TestNoChoices`` - must admit I think this is going to cause confusion.

I click the highlighted ``Dune Diviner``. It prompts ``Choose a mana source to pay {1}``. I click the highlighted ``Hostile Desert``. It displays ``Choose an untapped desert you control...there are no valid options``.

But, I just chose the highlighted untapped desert! 😕

**Comment by melvinzhang** [comment]
The situation is like this: you've tapped the Hostile Desert to pay {1}. The second cost is to tap an untapped desert you control, the only desert you had was tapped earlier for {1} so it cannot be used to pay the second cost.

> must admit I think this is going to cause confusion.

Agree, that's why I want to seek more opinions, I worked on it directly so it doesn't seem as confusing to me anymore. How can we reduce the confusion? Does merging the two sentence (`Choose...` and `There is no valid..`) into one sentence (`There is no untapped desert you control...`) help?

**Comment by melvinzhang** [comment]
Just realized we are using an obsolete wording `mana source`. The correct terminology should be `mana ability`

**Comment by lodici** [comment]
Ok, it is down to my lack of understanding of the mechanic. On clicking ``Dune Diviner`` I need to do two things - (1) pay {1}, which I do by tapping the highlighted ``Hostile Desert`` and then (2) tap and untapped desert you control... to gain 1 life, except of course I can't as there is no untapped ``Hostile Desert`` available. Makes more sense now.

**Comment by lodici** [comment]
> Agree, that's why I want to seek more opinions, I worked on it directly so it doesn't seem as confusing to me anymore. How can we reduce the confusion? Does merging the two sentence (Choose... and There is no valid..) into one sentence (There is no untapped desert you control...) help?

I think it would read better as one sentence. But also maybe distinguish the ``There are no valid...`` 'error message' in a different style or color, eg. plain font or red color.

**Comment by lodici** [comment]
Also maybe just by using a hyphen would make it clearer that the ``There are no valid...`` error message is a direct response to the first sentence, ie ``Choose an untapped desert you control - there are no valid options please undo.``

**Comment by melvinzhang** [comment]
There is only one part now, it looks like this: `There is no untapped desert you control. Please undo.`

**Comment by lodici** [comment]
Not sure if this is possible but thinking back on my initial confusion it might help if it also showed some sort of indication that a card requires multiple actions. For example, on click of the highlighted Dune Diviner it shows something like 
```
Dune Diviner
[1/2] Choose a mana ability to pay {1}.
```
then when I click on Hostile Desert it displays
```
Dune Diviner
[2/2] There is no untapped desert you control. Please undo.
```

**Comment by melvinzhang** [comment]
Possible to include it the number, perhaps something like "Cost 1/2: [text]"? 

The font/color change is a good suggestion, but will need to mess around with TextComponentBuilder and friends, perhaps can be added later in a subsequent improvement.

For now, I'm more concerned about getting the wording right.

The current wording states a fact (`There is ...`) but maybe it would be better to state clearly there is a problem to pay the cost? For example:

1. `Unable to pay {B}. Please undo.`

2. `Unable to tap an untapped desert you control. Please undo`

Especially for the second one where the action `tap` is mentioned seems to make things clearer.

**Comment by lodici** [comment]
> Possible to include it the number, perhaps something like "Cost 1/2: [text]"?

Yes, that is better wording and I do think it would help a lot. Could always add it after the card name as well so as not to encroach on the main text area, eg.
```
Dune Diviner (cost 1/2)
Choose a mana ability to pay {1}.

Dune Diviner (cost 2/2)
Unable to tap an untapped desert you control. Please undo.
```

> The font/color change is a good suggestion, but will need to mess around with TextComponentBuilder and friends, perhaps can be added later in a subsequent improvement.

Or you could use html tags.

> For now, I'm more concerned about getting the wording right.

The "Unable..." wording is good, but is even better with the cost indicator.

**Comment by melvinzhang** [comment]
Adding after the source name is a nice idea! It already comes with brackets so may need some other mean to separate the cost wording. Would also have to change the interface method showMessage though as there is no provision for showing additional text after the source name, this can be an additional enhancement after the basic pieces are in.

**Comment by melvinzhang** [comment]
The wording is satisfactory now, the presentation can be improved in a few ways. 1) Indicate this is a one cost out of a series of costs, 2) use a different font or color to alert the user that cost cannot be paid.

I tried using html but it doesn't seem to work in the user action panel, the `<` and `>` get removed and the tags are shown, seems to be becuse `<` and `>` are treated indicating card id by TComponentBuilder

**Comment by lodici** [comment]
I don't think there is a need for the new line.
![screenshot00638](https://user-images.githubusercontent.com/2443519/28200857-390b0266-6866-11e7-9acd-4cc2e172432e.jpg)

**Comment by melvinzhang** [comment]
On Linux, the undo message gets split over two lines, I found that it was easy to miss it and not as clear.

![without-nl](https://user-images.githubusercontent.com/1620634/28201083-f49583ea-68a1-11e7-939c-e74bedd87c8a.png)

The newline helps to make the action to be taken more obvious rather than merged together with the text above which can be quite long.

![with-nl](https://user-images.githubusercontent.com/1620634/28201115-1de1fb66-68a2-11e7-9452-6917e2db456c.png)

**Comment by lodici** [comment]
I actually think you could remove the "Please undo".

**Comment by melvinzhang** [comment]
Wouldn't the player be confused about how to proceed from this situation? In the action panel, we usually explain how to move on, eg "Press {f} to continue", "Click {f} to pass" etc.

**Comment by lodici** [comment]
The I think the great big undo button is fairly obvious. 😉 But it is a minor aesthetic annoyance due to the different font sizes which we cannot legislate for so best to leave as-is.

**Comment by melvinzhang** [comment]
Normally the undo function is optional, players could play through without using it. This is the first time where player must use it to continue. I think it is important to mention it, probably should use the icon so that it is clear which button it is. Just realized that just telling players to undo, doesn't mean they know how it. The "Press" wording should be used.

**Comment by lodici** [comment]
> Normally the undo function is optional

Because normally there are two buttons! The way I view the user prompt is that if one or more buttons are displayed then I have to do something. One thing I have been considering is to add a pulsing glow affect to the buttons after a small period of time just in case the player is wondering what to do next.

**Comment by melvinzhang** [comment]
For cost payment, the player expects to click on something on the battlefield/hand to continue (eg. click on Land to pay mana cost, click on hand to discard, etc), not the user action panel buttons. This case is a bit different from the usual flow, hence the message.
