### ISSUE TITLE
Molten Primordial (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1183]
name=Molten Primordial
image=http://magiccards.info/scans/en/gtc/101.jpg
value=3.222
rarity=R
type=Creature
subtype=Avatar
cost={5}{R}{R}
pt=6/4
ability=Haste;\
        When SN enters the battlefield, gain control of target creature an opponent controls until end of turn.~Untap *that creature*.~*It* gains haste until end of turn.
timing=fmain
oracle=Haste\nWhen Molten Primordial enters the battlefield, for each opponent, gain control of up to one target creature that player controls until end of turn. Untap those creatures. They gain haste until end of turn.

**Comment by kelsioboy** [comment]
[Molten_Primordial.txt](https://github.com/magarena/magarena/files/1139730/Molten_Primordial.txt)
I am sending the original file. Because the above text is wrong and I can not edit.

**Comment by ShawnieBoy** [comment]
This one it a bit tricky - as it is 'gain control of up to one target creature'. You may choose not to target (e.g. [Bronze Bombshell](http://magiccards.info/di/en/160.html)) - Although the may choice shouldn't be 'may gain control', if you do target something you will gain control of it.

**Comment by melvinzhang** [comment]
@ShawnieBoy "may gain control" seems to be fine here, as the choice is chosen when the trigger goes on the stack. Eg `When SN enters the battlefield, you may gain control of target creature an opponent controls until end of turn.~Untap *that creature*.~*It* gains haste until end of turn.`

What's the issue with it?

**Comment by ShawnieBoy** [comment]
I was thinking of things I've encountered with 'may' and targeting. It might not be the case now, but sometimes you're asked to choose a target first, then asked if you want to perform the action. With the Primordial and 'up to one' the choice is whether to target or not. If you choose not to gain control of any creature, there should be no instance of asking for a target. e.g. Not able to use it to trigger 'when becomes target' unless you actually gain control of it.

**Comment by ShawnieBoy** [comment]
Similar to the may tap or untap #371

**Comment by melvinzhang** [comment]
Yes, that is how it works now. When the trigger goes on the stack, you are presented with the may choice. If you answer yes, you are asked to choose a target. If you choose no, nothing else happens.

**Comment by ShawnieBoy** [comment]
Ahh, good - I'm sure I've encountered the opposite before. If the order here is correct then there's no issue.
