### ISSUE TITLE
Sepulchral Primordial (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1185]
name=Sepulchral Primordial
image=http://magiccards.info/scans/en/gtc/75.jpg
value=3.493
rarity=R
type=Creature
subtype=Avatar
cost={5}{B}{B}
pt=5/4
ability=Intimidate;\
        When SN enters the battlefield, you may put target creature card from an opponent's graveyard onto the battlefield under your control.
timing=main
oracle=Intimidate\nWhen Sepulchral Primordial enters the battlefield, for each opponent, you may put up to one target creature card from that player's graveyard onto the battlefield under your control.

**Comment by kelsioboy** [comment]
As in Magarena only has an opponent I found it unnecessary to use groovy for that card. It is also the case of "Molten Primordial" and "Sandwurm Convergence".

**Comment by melvinzhang** [comment]
Great find and making use of the fact that there is only one opponent so that it can be scripted without groovy.
