### ISSUE TITLE
Welcome Deck legality and AKH

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#1196]
30 cards from Welcome Deck 2017 are standard legal as long as AKH is legal. I would have thought that they were not AKH block legal, but they also appear in AKH products (AKH Booster Battle Pack). I've included them in the AKH card list for now, so that they rotate correctly, but may adjust the set's card count.

This is the same method to the 2016 deck and SOI which includes an extra 16 cards.

**Comment by melvinzhang** [comment]
Thanks for including the welcome deck cards. @ShawnieBoy what's left to do to resolve this?

**Comment by ShawnieBoy** [comment]
Nothing more to resolve
