### ISSUE TITLE
Dizzying Gaze (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1199]
name=Dizzying Gaze
image=http://magiccards.info/scans/en/ex/81.jpg
value=2.672
rarity=C
type=Enchantment
subtype=Aura
cost={R}
ability=Enchant creature you control;\
        Enchanted creature has "{R}: This creature deals 1 damage to target creature with flying."
timing=aura
enchant=default,creature you control
oracle=Enchant creature you control\n{R}: Enchanted creature deals 1 damage to target creature with flying.

**Comment by melvinzhang** [comment]
This doesn't interact correct with effect that cause permanents to lose ability. With this interpretation, the creature can later lose the damage dealing ability.
