### ISSUE TITLE
Always present Horizontal scrollbar issue in user action panel

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#120]
indentified during discussion in issue #119
![](https://cloud.githubusercontent.com/assets/2363180/6803399/24fe78ea-d22f-11e4-9861-ce1361c2217b.png)

**Comment by lodici** [comment]
@ShawnieBoy please can you confirm which theme you are using. Thanks.

**Comment by ShawnieBoy** [comment]
It's Granite - Also occurs with Wood and Opal (The three themes that come with Magarena)

**Comment by lodici** [comment]
It's a theme thing. Although not a solution, a temporary workaround is to use Felt or another non-default theme.
![theme-sizes-small](https://cloud.githubusercontent.com/assets/2443519/6815436/a4f7ad8a-d281-11e4-97b3-4267b92940c3.gif)

**Comment by lodici** [comment]
playing Breeding Pool in ``1.60, youMayTest.game, opal theme``
![screenshot00105](https://cloud.githubusercontent.com/assets/2443519/7021651/dd5b2dba-dd1b-11e4-90a7-102e35d3ca5d.png)

**Comment by lodici** [comment]
fixed in b5b2991285190d2c5ba99baef707ba8139164dcc
