### ISSUE TITLE
Greenwheel Liberator (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1200]
name=Greenwheel Liberator
image=http://magiccards.info/scans/en/aer/108.jpg
value=2.500
rarity=R
type=Creature
subtype=Elf,Warrior
cost={1}{G}
pt=2/1
ability=When SN enters the battlefield, if a permanent you controlled left the battlefield this turn, put two +1/+1 counter on SN.
timing=main
oracle=Revolt — Greenwheel Liberator enters the battlefield with two +1/+1 counters on it if a permanent you controlled left the battlefield this turn.

**Comment by melvinzhang** [comment]
This method will create a trigger on the stack, whereas the actual ability does not have a trigger. I will extend the existing script for "enters the battlefield with" to allow specifying the condition.
