### ISSUE TITLE
Gryff's Boon (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1201]
name=Gryff's Boon
image=http://magiccards.info/scans/en/soi/20.jpg
value=2.500
rarity=U
type=Enchantment
subtype=Aura
cost={W}
ability=Enchant creature;\
        Enchanted creature gets +1/+0 and has flying.;\
        {3}{W}: Return SN from your graveyard to the battlefield. Activate this ability only any time you could cast a sorcery.
timing=aura
enchant=default,pos creature
oracle=Enchant creature\nEnchanted creature gets +1/+0 and has flying.\n{3}{W}: Return Gryff's Boon from your graveyard to the battlefield attached to target creature. Activate this ability only any time you could cast a sorcery.

**Comment by melvinzhang** [comment]
When an Aura enters the battlefield due to an effect, the creature to be selected is not targeted, so hexproof/shroud creatures can be selected. In this case, the creature to be attached with aura needs to be chosen after activating the ability.
