### ISSUE TITLE
Gamble (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1203]
[Gamble.txt](https://github.com/magarena/magarena/files/1160106/Gamble.txt)

**Comment by kelsioboy** [comment]
The effect of shuffling the library on the card is a special case where the shuffling order does not directly affect the final effect that is to randomly discard a card.

**Comment by ShawnieBoy** [comment]
If I remember right - I think there was a problem with the discarding at random not including the card that had been searched, or occuring before the search itself. @melvinzhang has the sequencing of secondary effects been resolved? There was a similar one with "Draw a card, then discard a card" and "Discard a card, then draw a card"

**Comment by melvinzhang** [comment]
No issue with this, discard at random is an event. It is easy to check just by playing the card, when you are searching your library, your hand is the same size as before.

**Comment by melvinzhang** [comment]
@kelsioboy Nice find! It is nice to know that is can be done in pure card script without groovy with a simple rearrangement.
