### ISSUE TITLE
Wild Research (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1207]
name=Wild Research
image=http://magiccards.info/scans/en/ap/72.jpg
value=3.839
rarity=R
type=Enchantment
cost={2}{R}
ability={1}{W}: Search your library for an enchantment card, reveal it, and put it into your hand, then shuffle your library~and discard a card at random.;\
        {1}{U}: Search your library for an instant card, reveal it, and put it into your hand, then shuffle your library~and discard a card at random.
timing=enchantment
oracle={1}{W}: Search your library for an enchantment card and reveal that card. Put it into your hand, then discard a card at random. Then shuffle your library.\n{1}{U}: Search your library for an instant card and reveal that card. Put it into your hand, then discard a card at random. Then shuffle your library.

**Comment by melvinzhang** [comment]
@kelsioboy this is similar to Gamble and should work. Why did you close it?

**Comment by kelsioboy** [comment]
[Wild_Research.txt](https://github.com/magarena/magarena/files/1166274/Wild_Research.txt)

**Comment by kelsioboy** [comment]
I closed because it is appearing wrong (Scratched) and I thought that you could not see the original scrip and I was not planning to send the file to you that is above. Please tell me if you can see the text without the "Risk" so that if it happens again I leave it open.

**Comment by melvinzhang** [comment]
Yes, I can see the text without issues. The appearance of the text does not cause any issues.
