### ISSUE TITLE
Aether Thief causing crash when AI plays it as Flash

### ISSUE THREAD

**Issue by pt-dev** [magarena/magarena#1210]
Reproducible crash with Aether Thief being played as a flash response in declaring blockers.

---
![crash](https://user-images.githubusercontent.com/3056147/28440754-aad3bb9a-6d75-11e7-992e-f733dde022dc.png)

[crash.txt](https://github.com/magarena/magarena/files/1163809/crash.txt)

**Comment by melvinzhang** [comment]
@pt-dev please include the deck being played, would like to check the rest of the cards. You'll need to rename it as a txt file first before you can attach it to your comment.

**Comment by melvinzhang** [comment]
Looks like the memory problem due to discarding from a large hand. Should be fixed in 1.88. Please reopen if it happens again.
