### ISSUE TITLE
Veilstone Amulet (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1212]
[Veilstone_Amulet.zip](https://github.com/magarena/magarena/files/1166302/Veilstone_Amulet.zip)

**Comment by kelsioboy** [comment]
It is zipped because it contains a groovy.

**Comment by melvinzhang** [comment]
Thanks, it is almost working. The problem with this effect is that it changes the rule of the game, so it would also affect creatures that enter the battlefield after it resolves. It needs to add a static effect at the game layer to cover creatures that enter later. I've fixed it in https://github.com/magarena/magarena/commit/e9d67ac0a4e6809b4e80da53bb3692cca798093a
