### ISSUE TITLE
`Bonfire of the Damned` deals 0 damage when cast as a *Miracle*

### ISSUE THREAD

**Issue by itandetnik** [magarena/magarena#1218]
I draw `Bonfire of the Damned`. I'm prompted to cast it for its *Miracle* cost. I agree, and pay 6 mana, expecting 5 damage.

As a fast effect, the opponent activates `Trip Noose` and taps my one and only creature, `Tuktuk the Returned`. Not sure if it's relevant.

Finally, "Cast `Bonfire of the Damned` for its *Miracle* cost" spell resolves, but what's placed on the stack is "`Bonfire of the Damned` deals **0** damage ...". Somewhere in the process, it seems the information about the cost paid has been lost.

Gameplay report attached:
[gameplay-report.zip](https://github.com/magarena/magarena/files/1168276/gameplay-report.zip)

**Comment by itandetnik** [comment]
`Bonfire of the Damned` works when cast as a *Micracle* and there is no intervening action by the opponent. It's that interruption in between that seems to trigger the issue.

**Comment by melvinzhang** [comment]
Good catch, the cost is paid too early and there is a chance it could get missed when something else happens in between.
