### ISSUE TITLE
Benefactor's Draught (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1219]
[Benefactor_s_Draught.txt](https://github.com/magarena/magarena/files/1170690/Benefactor_s_Draught.txt)

**Comment by kelsioboy** [comment]
I know you're very different from Oracle, but it works. I tried to do it in other ways, but only this way it worked out without groovy.

**Comment by melvinzhang** [comment]
This doesn't interact correctly with effects that cause permanents to lose abilities. If an opponent's creature loses all abilities, this trigger should still take effect.
