### ISSUE TITLE
Wheel and Deal (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1220]
[Wheel_and_Deal.txt](https://github.com/magarena/magarena/files/1170707/Wheel_and_Deal.txt)

**Comment by melvinzhang** [comment]
It should be possible to have zero opponents discard their hand and draw seven cards.

**Comment by melvinzhang** [comment]
@kelsioboy you can try adding a "You may have", this will let you choose 'no' so that zero opponents discard their hand. Feel free to reopen this issue when you mange to allow zero opponents.

**Comment by melvinzhang** [comment]
@kelsioboy nevermind, just realized that would not work, if you choose 'no' you also don't get to draw a card

**Comment by kelsioboy** [comment]
@melvinzhang Thanks, but I think that card just in groovy same. I also thought the same as you about "You can have". In groovy must give to do, the player draw a card first and then choose whether the opponent discards the hand or not.
