### ISSUE TITLE
Nahiri, the Lithomancer (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1222]
[Nahiri, the Lithomancer.zip](https://github.com/magarena/magarena/files/1170712/Nahiri.the.Lithomancer.zip)

**Comment by kelsioboy** [comment]
I'm sending a set to make this card work, it may seem a bit strange, but I think everything is working perfectly. The token is a modification of the original and does not really exist, but the attach effect is in it.

**Comment by ShawnieBoy** [comment]
1/1 white Kor Soldier creature tokens already exist for other cards, the groovy will apply to all of them - e.g [Nomad's Assembly](http://magiccards.info/c14/en/82.html), [Conqueror's Pledge](http://magiccards.info/zen/en/8.html)

**Comment by kelsioboy** [comment]
No, this card if you notice, it has a small space in its name, which makes it different from the original token. So when using the "Nahiri" effect of creating the token, it will create what is modified rather than the normal one that already exists in magarena.

Ex. Normal token is named after this:
1_1_white_Kor_Soldier_creature_token
       Modified token is named after this:
1_1_white_Kor_Soldier_creature__token

One more underline before the word token.

**Comment by kelsioboy** [comment]
Then it will be exclusive to "Nahiri, the Lithomancer".

**Comment by kelsioboy** [comment]
I noticed that there are other name conflict cards, such as "Goblin Spymaster", this method could be used to resolve these conflicts as well. Making a token or card for the conflicting cards. In the case of the "Goblin Spymaster" I made a test here using a modified token, I just did not accept the token effect at the beginning of each opponent's end step, but as it was just to test, then I modified it to At the beginning of each opponent's Upkeep and worked out. He placed the token with the effect "Creatures you control attack each combat if able." And would not interfere with the original token, since the two are named differently.

**Comment by melvinzhang** [comment]
@kelsioboy in this case the attaching is part of Nahiri's first ability and not a triggered ability of the token. As a triggered ability, your opponent can response to it and destroy the token before the equipment is on it. It should not be possible to do that. I will look into fixing it.

**Comment by melvinzhang** [comment]
The image for the Stoneforged Blade token is incorrect. It is listed as http://magiccards.info/scans/en/bok/106.jpg in the zip file.

**Comment by melvinzhang** [comment]
The choice of equipment is not targeted (equipment with hexproof can be chosen) so it should be 
`new MagicTargetChoice("an Equipment you control")`
