### ISSUE TITLE
stackoverflow when copying multiple counter spells with storm

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#1223]
Cast 2 spells, then cast Hindering Touch. The storm ability creates two copies of Hindering Touch on the stack, call them A and B. For A, select B as its target. For B, select A as its target. This leads to a infinite loop on calling getStateId of A (or B).

**Comment by melvinzhang** [comment]
It seems odd that A could counter B, assuming A is the first copy and goes on the stack first and B is the second copy. 

One solution is to only only allow a spell/ability to select as target another spell/ability that is earlier than it. Therefore B can counter A, but A cannot counter B, as B is later than A.

@ShawnieBoy is it possible for copy A to select copy B as target according to the rules?

The closest I could find is [Hive Mind's ruling](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=190556) which says "First the player whose turn it is (or, if that’s the player who cast the original spell, the player to that player’s left) puts his or her copy on the stack, choosing new targets for it if he or she likes. Then each other player in turn order does the same." which seems to support the fact that A could not have chosen B as target.

**Comment by ShawnieBoy** [comment]
I think they can target each other, as both are added to the stack then targets chosen. There's no infinite loop, just an illegal target (no target).

**Comment by melvinzhang** [comment]
I think I found the rule for this, it is [706.10c](https://mtg.gamepedia.com/Copying_objects) "Once the player has decided what the copy’s targets will be, the copy is put onto the stack with those targets."

Therefore it would have the new targets when it goes onto the stack, so the target cannot be a later copy as that has yet to go on the stack.
