### ISSUE TITLE
Jushi Apprentice + Tomoya the Revealer (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1228]
[Jushi_Apprentice.txt](https://github.com/magarena/magarena/files/1194863/Jushi_Apprentice.txt)
[Tomoya_the_Revealer.txt](https://github.com/magarena/magarena/files/1194864/Tomoya_the_Revealer.txt)

**Comment by melvinzhang** [comment]
Good find! Made me realize that the "draw X" syntax should be supported in the card script so I added it.

**Comment by kelsioboy** [comment]
The "draw X" syntax in version 1.87 does not work here.

**Comment by melvinzhang** [comment]
Correct, the "Draw X" support will be in 1.88. Looking at this from a fresh perspective, we found a way to add support for the ".. X.. , where X is ..." syntax throughout not just for draw but other syntax that already support the "for each" syntax.
