### ISSUE TITLE
Become creature flags incorrect?

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#123]
I've been playing with getting animation into scripting, and after putting together Opal Acrolith, I think I've come across a bit of an error.

Firstly, Opal Acrolith ("Whenever an opponent casts a creature spell, if Opal Acrolith is an enchantment, Opal Acrolith becomes a 2/4 Soldier creature. {0}: Opal Acrolith becomes an enchantment.") is a good example of type changing.

When Opal Acrolith becomes a creature, it is not an Enchantment Creature, just a creature, as it states. Also when it becomes an enchantment, it is only an enchantment, not an Enchantment Creature.

Currently with animation it will state what a permanent's type/s would be e.g:
* {1}: Blinkmoth Nexus becomes a 1/1 Blinkmoth artifact creature with flying until end of turn. It's still a land.
* Whenever a creature enters the battlefield under your control, you may have Angel's Tomb become a 3/3 white Angel artifact creature with flying until end of turn.

If an artifact becomes a creature, it's not just adding types, it's replacing them. Angel's Tomb above is an artifact and becomes an Artifact Creature. Likewise Blinkmoth becomes a Land Artifact Creature. It's completely possible for an artifact to become simply a creature and lose the artifact type.

Currently type changes still refer to previous type flags:
```
@Override
    public int getTypeFlags(final MagicPermanent permanent, final int flags) {
        return flags | MagicType.Creature.getMask();
    }
```

If that were a Blinkmoth I would expect:
```
@Override
    public int getTypeFlags(final MagicPermanent permanent, final int flags) {
        return MagicType.Creature.getMask() | 
                MagicType.Artifact.getMask() | MagicType.Land.getMask();
    }
```
instead of
```
    @Override
    public int getTypeFlags(final MagicPermanent permanent,final int flags) {
        return flags |
               MagicType.Artifact.getMask() |
               MagicType.Creature.getMask();
    }
```
Only when an ability definitely states "in addition to it's other types" would I expect a flags reference.

Am I missing something?

**Comment by melvinzhang** [comment]
I agree with your assessment.

On a side note, when I read "animation" I think of cards moving around on the screen. Took a couple of reading to get the correct meaning.

**Comment by ShawnieBoy** [comment]
>On a side note, when I read "animation" I think of cards moving around on the screen. Took a couple of readings to get the correct meaning.

Oh the wonders of the English language... :smile: 

I'm glad the rest made sense, can become quite a confusing topic in mtg. And even thinking more about the blinkmoth example I gave, if it wasn't a land to begin with (through other type replacements), it wouldn't become a land.

Ok, to prevent confusing myself further, and some more research, there it one caveat to my above:

>205.1b Some effects change an object’s card type, supertype, or subtype but specify that the object
retains a prior card type, supertype, or subtype. In such cases, all the object’s prior card types,
supertypes, and subtypes are retained. This rule applies to effects that use the phrase “in
addition to its types” or that state that something is “still a [type, supertype, or subtype].” **Some
effects state that an object becomes an “artifact creature”; these effects also allow the object to retain all of its prior card types and subtypes.**

Emphasis mine

If something becomes an 'artifact creature' it also retains previous types.

So if a copy of Angel's Tomb from Copy Artifact was triggered, it would become an artifact creature but retain it's enchantment type.
But if Opal Acrolith was an artifact and triggers, although altogether it would appear to become an artifact creature, it becomes a creature - so doesn't retain previous types.

Another reason copying things is bad for the brain, hehe.

I'll see if I can get this together for 1.61
