### ISSUE TITLE
Merciless Javelineer (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1230]
name=Merciless Javelineer
image=http://magiccards.info/scans/en/akh/202.jpg
value=2.500
rarity=U
type=Creature
subtype=Minotaur,Warrior
cost={2}{B}{R}
pt=4/2
ability={2}, Discard a card: Put a -1/-1 counter on target creature.~*It* can't block this turn.
timing=main
oracle={2}, Discard a card: Put a -1/-1 counter on target creature. That creature can't block this turn.

**Comment by melvinzhang** [comment]
Nice addition. Note that we try to keep to the oracle text as far as possible, so it should be `*That creature*` instead of `*It*` so we use the original wording. I have fixed this in the commit.
