### ISSUE TITLE
Add possible scripting for card type/subtype changes.

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#124]
As per discussion issue #123

**Comment by ShawnieBoy** [comment]
Is it worth creating a branch for this? @melvinzhang (As a git newb, it looks like a good idea)

**Comment by melvinzhang** [comment]
depends... can you run though an outline of the changes needed?

**Comment by melvinzhang** [comment]
The method that requires the least git use fork + pull request. You can work of the master on the fork.

**Comment by lodici** [comment]
> The method that requires the least git use is "fork + pull request". You can work of the master on the fork.

Unless I am missing something this seems like a load of work for established team members.
1. Fork repository
2. Clone local fork copy .
3. replicate all the changes you currently have on your local non-fork repository branch into the new local fork master.
4. publish 
5. pull request.

instead of
1. publish feature branch to ``live`` repository
2. pull request on feature branch.

**Comment by melvinzhang** [comment]
More steps but less git if (3) is not required, i.e. no commits has been made. The difference being that a branch needs to be manually managed with git, a fork is managed via the github interface.

**Comment by lodici** [comment]
Can you give an example where (3) is not required.

**Comment by melvinzhang** [comment]
Just starting on a new feature and no code has has been written yet.

**Comment by lodici** [comment]
So what you are saying is that whenever you start a new feature you should fork the repository, clone it locally and work on ``master`` in that?

**Comment by melvinzhang** [comment]
Yes, if you think you might in inadvertently mess up the original repo with wrong git usage. @ShawnieBoy without knowing more details, the way I imagine it would work is that it would be a new rule in MagicRuleEeventAction, as such it shouldn't inter with existing stuff. So I don't think even a branch is necessary.

**Comment by lodici** [comment]
> Yes, if you think you might in inadvertently mess up the original repo with wrong git usage.

Is that possible?

**Comment by melvinzhang** [comment]
Yes. Delete branch, then after a grace period, a auto git gc will remove the commits.

**Comment by lodici** [comment]
Then I can understand the caution but does not reflect that well on git. Personally, I always work on branches and am always testing ideas and trying new things out. That is the beauty of git to me. I have loads of feature branches at various states of completion but all in a single local repository linked to the live remote on github. Having to fork each time would be a nightmare.

**Comment by ShawnieBoy** [comment]
Thanks for the info - It shouldn't be interfering with current code, but as it would be a work in progress, thought that it would make sense being somewhere else as it would be incomplete. I assumed that a separate branch would have been easy enough to implement and then merge back in once it was complete.

Will push what I've been fiddling with so far, but I imagine it eventually replacing the current BecomeCreatureAction to a more generic ChangeTypeAction

**Comment by lodici** [comment]
@ShawnieBoy very sorry for hijacking your thread with a git discussion.

**Comment by ShawnieBoy** [comment]
@lodici No, it's good - I was kinda a git question too.

I understand that I can branch and not push it, keeping it local, but was considering the idea of branching and pushing so others could see/raise questions etc. without it being in the main thread.

**Comment by melvinzhang** [comment]
MagicBecomesCreatureAction is more generic than it sounds, it is a series of MagicAddStaticAction. When you mentioned scripting, I thought you mean we will be able to write "{3}: SN becomes a ..." in card script. I was thinking about doing something like that recently.

A separate line of commits becomes hard to merge back unless you regularly integrate changes on master back to your branch and resolve any conflicts. Unless it is a very experimental and disruptive change, small incremental commits on master is easier to manage and does not require any special git expertise.

**Comment by melvinzhang** [comment]
@ShawnieBoy Can you give an example of what the implementation will allow? Eg. with this feature, card scripts will be able to write ...

**Comment by ShawnieBoy** [comment]
> MagicBecomesCreatureAction is more generic than it sounds, it is a series of MagicAddStaticAction. When you mentioned scripting, I thought you mean we will be able to write "{3}: SN becomes a ..." in card script. I was thinking about doing something like that recently.

Yes, I agree, although I'd also be adding logic for what types/subtypes to keep as well as replace and additional constructors. Will probably create something separate just for non-interference reasons.

> Can you give an example of what the implementation will allow? Eg. with this feature, card scripts will be able to write ...

I'd be hoping to be able to implement all 'becomes' actions in script as they appear in text.

It would be looking through the types and subtypes it becomes, along with any power toughness then building statics based on those. If it's becoming an artifact creature, or contains 'is still a', it will retain previous types and subtypes.
It will also check that any subtypes it has are still relevant for the type, if not then it would then have to supress them until it regains that type (The tricky part)

**Comment by ShawnieBoy** [comment]
I'll push what I have so far which enables Opal Acrolith.

**Comment by melvinzhang** [comment]
The long groovy codes necessary for "becomes a" has long been a thorn in my side. Look forward to greatly simplifying and then getting rid of them.

**Comment by ShawnieBoy** [comment]
It's only the start and ugly, and will all get integrated together, but gives an idea what I'll be heading towards.

**Comment by ShawnieBoy** [comment]
Instead of creating the statics in the MagicRuleEvent the new 'BecomesAction' will be doing that.

**Comment by lodici** [comment]
> A separate line of commits becomes hard to merge back unless you regularly integrate changes on master back to your branch and resolve any conflicts. Unless it is a very experimental and disruptive change, small incremental commits on master is easier to manage and does not require any special git expertise.

Final comment, promise. I was envisaging using a branch in the same way a fork would be used - not for any sort of long running development branch. Just a simpler way of submitting code for review via a pull request.

**Comment by ShawnieBoy** [comment]
First push of new MagicBecomesAction - Checking subtypes and types remain/are changed would be appreciated :grinning: 

f4b00f74b033a464fbd6abc5f4b07e28b7e351ca and 388a22936bb786fe7632e9fd9abab01a8a5855fd

**Comment by ShawnieBoy** [comment]
Currently an issue with permanents losing their colour if the permanent they become doesn't define a colour (e.g.. Opal Caryatid)

**Comment by melvinzhang** [comment]
I find the matching in the "all" group too loose. If there is a typo in the subtype/type/color they are not discovered and will be silently dropped.

**Comment by melvinzhang** [comment]
> Currently an issue with permanents losing their colour/type if the permanent they become doesn't define a colour/type (e.g.. Opal Caryatid, Figure of Destiny)
The way it is invoked, color, subtype, type are never null, they are empty lists (lists of zero elements). For collections, it generally preferred to use empty lists instead of nulls.

**Comment by melvinzhang** [comment]
Since the way the template is written is always in a particular order, color followed by subtype followed by type. I think a better way to parse it is to have the getColors methods consume the tokens as they are matched. I'll look into it.

**Comment by ShawnieBoy** [comment]
>I find the matching in the "all" group too loose. If there is a typo in the subtype/type/color they are not discovered and will be silently dropped.

It was the only way I could think of being able to account for all different combinations in the regex. Combinations of single or multiple colors, single or multiple subtypes, and single or multiple types.

>The way it is invoked, color, subtype, type are never null, they are empty lists (lists of zero elements). For collections, it generally preferred to use empty lists instead of nulls.

Ahh yes, of course - I was working with nulls until the color/subtype/type multiples were complicating matters.

>Since the way the template is written is always in a particular order, color followed by subtype followed by type. I think a better way to parse it is to have the getColors methods consume the tokens as they are matched. I'll look into it.

Thanks - It's certainly getting there. :grinning:

**Comment by melvinzhang** [comment]
Make parsing strict, change null check to isEmpty check.

**Comment by ShawnieBoy** [comment]
Excellent

**Comment by melvinzhang** [comment]
The most impressive groovy to card script conversion, Raging Ravine's ability.

{2}{R}{G}: Until end of turn, SN becomes a 3/3 red and green Elemental creature with "Whenever this creature attacks, put a +1/+1 counter on it." It's still a land.

I feel this issue is done with what we've got so far. Shall we close the issue?

**Comment by ShawnieBoy** [comment]
That is quite impressive - lots of groovy removal as well.

I'd say this is done.
