### ISSUE TITLE
Crested Sunmare (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1242]
[Crested Sunmare.zip](https://github.com/magarena/magarena/files/1209078/Crested.Sunmare.zip)

**Comment by kelsioboy** [comment]
The token image link is wrong, please fix it.

**Comment by melvinzhang** [comment]
Good find on the syntax change. I noticed this recently when adding the status. Since we already support similar syntax for "opponent gained life this turn", I generalized the script to allow for the original syntax. Will be in the next release.
