### ISSUE TITLE
Creeperhulk (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1245]
name=Creeperhulk
image=http://magiccards.info/scans/en/c14/42.jpg
value=2.500
rarity=R
type=Creature
subtype=Plant,Elemental
cost={3}{G}{G}
pt=5/5
ability=Trample;\
        {1}{G}: Until end of turn, target creature you control becomes a 5/5 creature with trample.
timing=main
oracle=Trample\n{1}{G}: Until end of turn, target creature you control has base power and toughness 5/5 and gains trample.

**Comment by melvinzhang** [comment]
added in 10fba0cbae87282adfcf2
