### ISSUE TITLE
Graven Dominator (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1246]
name=Graven Dominator
image=http://magiccards.info/scans/en/gp/7.jpg
value=3.462
rarity=R
type=Creature
subtype=Gargoyle
cost={4}{W}{W}
pt=4/4
ability=Flying;\
        Haunt;\
        When SN enters the battlefield or the creature it haunts dies, each other creature becomes a 1/1 creature until end of turn.
timing=main
oracle=Flying\nHaunt\nWhen Graven Dominator enters the battlefield or the creature it haunts dies, each other creature has base power and toughness 1/1 until end of turn.

**Comment by melvinzhang** [comment]
added in def02697fc5588
