### ISSUE TITLE
Bonds of Faith (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1248]
name=Bonds of Faith
image=http://magiccards.info/scans/en/isd/5.jpg
image_updated=2016-09-12
value=3.357
rarity=C
type=Enchantment
subtype=Aura
cost={1}{W}
ability=Enchant creature;\
        As long as enchanted creature is Human, enchanted creature gets +2/+2.;\
        As long as enchanted creature is non-Human creature, enchanted creature can't attack or block.
timing=aura
enchant=default,creature
oracle=Enchant creature\nEnchanted creature gets +2/+2 as long as it's a Human. Otherwise, it can't attack or block.

**Comment by melvinzhang** [comment]
Neat, this is a nice way to get the same effect in card script.

**Comment by melvinzhang** [comment]
I find that putting cards text directly in the issue is easier to review compared to attaching a file. It saves a step of downloading the file and opening it in a different application.
