### ISSUE TITLE
Unable to access Sliver Overlord's second ability

### ISSUE THREAD

**Issue by Apyrase** [magarena/magarena#1249]
I am unable to use Sliver Overlord's second activated ability to control an opponent's sliver. When I try to activate sliver overlord's ability by clicking on it, the game simply selects the first ability without prompting me and let's me search my deck for another sliver. I am currently using build 1.77 so apologies if this has been already fixed.

If there is a way to do this with a clever keystroke, then I would suggest adding that keystroke to the user interface section of the wiki.

[gameplay-report.zip](https://github.com/magarena/magarena/files/1220204/gameplay-report.zip)

**Comment by melvinzhang** [comment]
@Apyrase Thanks for reporting the issue with the gameplay report. It help us to recreate the scenario.

The situation is due to Crystalline Sliver in play giving all Slivers shroud. Therefore Sliver Overlord's second ability has no valid targets.

**Comment by melvinzhang** [comment]
The shroud icon is the shiny shield. Shroud means a permanent cannot be the target of a spell/ability.

**Comment by Apyrase** [comment]
Dough! That was subtle. Nice catch!
