### ISSUE TITLE
MagicType and MagicColor - Can both be collections like MagicSubType?

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#125]
In regards to the 'BecomesAction' I've hit what could be a problem, at least as far as it goes to returning type and color values. Being able to return multiple 'or' values without knowing how many you have to start with is quite awkward.

MagicSubType flags are referenced as a collection, so it is easy to add/remove/clear them and return all of the rest as a result. The same isn't true for MagicColor or MagicType.

Is there a reason these two can't be stored and referenced as collections?

**Comment by ShawnieBoy** [comment]
I mean Set, but you know...

**Comment by lodici** [comment]
Not sure I understand. They are all enums. You can use the ``values`` static method to get all the enum values as an array (which you can easily convert into a list if required). Perhaps an example would help to clarify your requirement.

**Comment by ShawnieBoy** [comment]
Specifically to do with MagicPermanent - as in the getTypeFlags()

The cached flags are int for type and color, but are Set<> for Subtypes and Abilities

**Comment by ShawnieBoy** [comment]
Here's an example of typical animation statics with type, subtype and color from groovy, all changes are in addition to the types and colors:

```
ST = new MagicStatic(MagicLayer.Type, MagicStatic.UntilEOT) {
    @Override
    public void modSubTypeFlags(final MagicPermanent permanent,final Set<MagicSubType> flags) {
        flags.add(MagicSubType.Construct);
    }
    @Override
    public int getTypeFlags(final MagicPermanent permanent,final int flags) {
        return flags|MagicType.Creature.getMask();
    }
};

C = new MagicStatic(MagicLayer.Color) {
    @Override
    public int getColorFlags(final MagicPermanent permanent,final int flags) {
        return flags|MagicColor.Green.getMask();
    }
};
```

You can see that the subtype flags are added to the Set, where the types and colors need to return either their own colors/types or the new ones.

I'm in a situation where if you have a variable amount of colors or types, you'd have to return each separately:

Being given an array of colors from a constructor ->
```
if (color.length==5) {
    return flags|color[0].getMask()|color[1].getMask()|color[2].getMask()|color[3].getMask()|color[4].getMask();
} else if (color.length==4) {
    return flags|color[0].getMask()|color[1].getMask()|color[2].getMask()|color[3].getMask();
} else if (color.length==3) {
    return flags|color[0].getMask()|color[1].getMask()|color[2].getMask();
} else if (color.length==2) {
    return flags|color[0].getMask()|color[1].getMask();
} else if (color.length==1) {
    return flags|color[0].getMask();
} else
    return flags;
```

**Comment by lodici** [comment]
```
for (int i = 0; i < color.length; i++) {
	flags = flags|color[i].getMask();
}
return flags;
``

**Comment by ShawnieBoy** [comment]
Wouldn't that only return the last one?

**Comment by lodici** [comment]
Not sure, you a quick test should provide the answer. Otherwise, 
```
int mask = 0;
for (int i = 0; i < color.length; i++) {
    mask = mask + color[i].getMask();
}
return flags|mask;
```
Thinking on the fly here!

**Comment by ShawnieBoy** [comment]
Hehe

The thing is it can only return one int value at a time, but must be able to return correctly for hasColor()

If you're adding the int together you'll be getting a different color and eventually going off the scale.

**Comment by ShawnieBoy** [comment]
Essentially if they were a Set, and treated like abilities or subtypes, would be a lot simpler :grinning:

**Comment by lodici** [comment]
Have you tested them - I am pretty sure second one will work. These use bitwise operations. They are not working with color ints but masks. For example for MagicColor...
```
White -> ordinal = 0 -> mask = 1B = 1
Blue -> ordinal = 1 -> mask = 10B = 2
Black -> ordinal = 2 -> mask = 100B = 4
Green -> ordinal = 3 -> mask = 1000B = 8
Red -> ordinal = 4 -> mask = 10000B = 16
```
Adding any combination of these masks together will always produce a different result. So you can then bitwise or ``flags`` to determine which colors it has.

**Comment by ShawnieBoy** [comment]
Ahh of course, will give it a try - should work for both color and type.

**Comment by melvinzhang** [comment]
Yes, they can be rewritten to use EnumSet. BecomesAction supports color and types using the OR method mentioned here.
