### ISSUE TITLE
Exemplar of Strength (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1253]
name=Exemplar of Strength
image=http://magiccards.info/scans/en/akh/165.jpg
value=2.500
rarity=U
type=Creature
subtype=Human,Warrior
cost={1}{G}
pt=4/4
ability=When SN enters the battlefield, put three -1/-1 counters on target creature you control.;\
        Whenever SN attacks, if SN has a -1/-1 counter on it, remove a -1/-1 counter from it~and you gain 1 life.
timing=main
oracle=When Exemplar of Strength enters the battlefield, put three -1/-1 counters on target creature you control.\nWhenever Exemplar of Strength attacks, remove a -1/-1 counter from it. If you do, you gain 1 life.

**Comment by melvinzhang** [comment]
My understanding is that in this rewrite the gain life and -1/-1 counter are independent. It should be the case that if there are no -1/-1 counters, no life is gained.

**Comment by kelsioboy** [comment]
If "Exemplary of Strength" attacks and does not have -1 / -1 counter on it (Exemplar of Strength) to remove, then the player does not gain 1 life.

**Comment by kelsioboy** [comment]
@melvinzhang I noticed that this card is wrong, the player is coming to life every time that "Exemplar of Strength" is attacking, even without it having the -1 / -1 counter in it, which should not happen. I think it can only be done even in groovy.

**Comment by melvinzhang** [comment]
Yes, currently it can be done only in groovy, but it is very close to scriptable. I'll look into whether the scripting can be improved to handle this.

**Comment by kelsioboy** [comment]
Ok.

**Comment by kelsioboy** [comment]
I figured out a way to make that card work properly without groovy. I edited the script I sent you.

**Comment by melvinzhang** [comment]
Good attempt. Unfortunately it doesn't work in one case, when Exemplar of Strength gains a -1/-1 counters after it attacks. In the edited script, the trigger will not on the stack when Exemplar of Strength attacks without a -1/-1 counter. The correct behavior is for the trigger to go on the stack, it doesn't check for the counter until the trigger resolves.

**Comment by melvinzhang** [comment]
Manage to get it into the script!
