### ISSUE TITLE
Olivia, Mobilized for War (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1265]
name=Olivia, Mobilized for War
image=http://magiccards.info/scans/en/soi/248.jpg
value=2.500
rarity=M
type=Legendary,Creature
subtype=Vampire,Knight
cost={1}{B}{R}
pt=3/3
ability=Flying;\
        Whenever another creature enters the battlefield under your control, you may discard a card. If you do, put a +1/+1 counter on that creature.~That creature gains haste until end of turn,~and that creature becomes a Vampire in addition to its other types.
timing=main
oracle=Flying\nWhenever another creature enters the battlefield under your control, you may discard a card. If you do, put a +1/+1 counter on that creature, it gains haste until end of turn, and it becomes a Vampire in addition to its other types.

**Comment by melvinzhang** [comment]
Good find!
