### ISSUE TITLE
Display counters on cards in exile

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#1267]
With suspend being included, cards in exile now can have counters placed on them, but cannot currently be rendered.
It's closely linked to the ability icons and, quite interestingly, ability icons appear in hand and on the battlefield, but not in exile.
I've had a quick look, but unable to puzzle this out.

**Comment by melvinzhang** [comment]
@ShawnieBoy thanks for creating this, was on my mind but forgot about it. I've made the change and commit is incoming. Wanted to find out more about where you got stuck, it does point to a readability problem in the code if it is confusing/hard to figure our where changes should be made.
