### ISSUE TITLE
Halcyon Glaze + Daxos's Torment (Not returning to enchantment when the turn ends, after they become creatures)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1288]
Until Version 1.87 of these cards were running normal. In version 1.88 they stopped working. I modified this way the scrip and returned to normal:

name=Halcyon Glaze
image=http://magiccards.info/scans/en/rav/54.jpg
value=3.488
rarity=U
type=Enchantment
cost={1}{U}{U}
ability=Whenever you cast a creature spell, SN becomes a 4/4 Illusion creature with flying until end of turn. It's still an enchantment.
timing=enchantment
oracle=Whenever you cast a creature spell, Halcyon Glaze becomes a 4/4 Illusion creature with flying in addition to its other types until end of turn.

name=Daxos's Torment
image=http://magiccards.info/scans/en/c15/18.jpg
image_updated=2016-02-29
value=2.500
rarity=R
type=Enchantment
cost={3}{B}
ability=Whenever SN or another enchantment enters the battlefield under your control, SN becomes a 5/5 Demon creature with flying and haste until end of turn. It's still an enchantment.
timing=fmain
oracle=Constellation — Whenever Daxos's Torment or another enchantment enters the battlefield under your control, Daxos's Torment becomes a 5/5 Demon creature with flying and haste in addition to its other types until end of turn.

I'm not sure, but I think it has to do with "in addition to its other types", because when I removed it the cards worked properly. I have not tested on others besides these, but I believe everyone who has "in addition to its other types" is in the same way.

**Comment by melvinzhang** [comment]
Nice catch it is because I assume there is always a period between "in addition to its other types" and  "until end of turn". Turns out this is not the case, working on a fix.
