### ISSUE TITLE
AI takes a lot of time to play even on default setting

### ISSUE THREAD

**Issue by fullmooninu** [magarena/magarena#13]
AI's take a lot of time to play even on default setting. Not sure how they're limited (if on memory, time to run, or just number of cycles ), but would be nice to be able to decrease that time to run factor.

Can one increase the memory available to magarena? How? 

Also, it would be nice to have a "average time taken by the AI's turn" thing of sorts while playing and being able to make changes based on that. In real life it's no problem waiting for the opponent for 4 minutes, but in a computer there's stuff you can do to it so it takes less time ^^;

On another note, on the readme it says:

> Selecting the AI to play against:
>  The desired AI can be selected in the "New duel" dialog (Arena -> New duel).
>  The difficulty level is the maximum number of seconds the AI has to make a move.

The readme should have a clear description of each AI 

Also, there should be a short description in the UI for them.

Should I do this ^ ?

**Comment by lodici** [comment]
Closing as it is quite old and there has been no further feedback from OP in response to melvin's request for more details.

**Comment by fullmooninu** [comment]
Sorry sorry. Not playing much, but the error didn't pop up (i.e. AI taking obviously more seconds to play than it should) Thanks guys.
