### ISSUE TITLE
Broken Ambitions (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1304]
name=Broken Ambitions
image=http://magiccards.info/scans/en/lw/54.jpg
value=3.538
rarity=C
type=Instant
cost={X}{U}
timing=counter
requires_groovy_code
oracle=Counter target spell unless its controller pays {X}. Clash with an opponent. If you win, that spell's controller puts the top four cards of his or her library into his or her graveyard.

def effect = MagicRuleEventAction.create("clash with an opponent. If you win, an opponent puts the top four cards of his or her library into his or her graveyard.")

[
    new MagicSpellCardEvent() {
        @Override
        public MagicEvent getEvent(final MagicCardOnStack cardOnStack,final MagicPayedCost payedCost) {
            return new MagicEvent(
                cardOnStack,
                NEG_TARGET_SPELL,
                payedCost.getX(),
                this,
                "Counter target spell\$ unless its controller pays {X}. (X=RN)"
            );
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
                game.addEvent(effect.getEvent(event));
            event.processTargetCardOnStack(game, {
                final int amount = event.getRefInt();
                game.addEvent(new MagicCounterUnlessEvent(
                    event.getSource(),
                    it,
                    MagicManaCost.create("{"+amount+"}")
                ));
            });
        }
    }
]

**Comment by melvinzhang** [comment]
Doesn't work correctly when you counter your own spell. You still clash with an opponent but you will be the one to mull 4 cards if you win the clash.
