### ISSUE TITLE
Crown of Doom (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1306]
name=Crown of Doom
image=http://magiccards.info/scans/en/c14/55.jpg
value=2.500
rarity=R
type=Artifact
cost={3}
ability=Whenever a creature attacks you or a planeswalker you control, RN gets +2/+0 until end of turn.
timing=artifact
requires_groovy_code
oracle=Whenever a creature attacks you or a planeswalker you control, it gets +2/+0 until end of turn.\n{2}: Target player other than Crown of Doom's owner gains control of it. Activate this ability only during your turn.

[
    new MagicPermanentActivation(
        [MagicCondition.YOUR_TURN_CONDITION],
        new MagicActivationHints(MagicTiming.Main),
        "Control"
    ) {
        @Override
        public Iterable<? extends MagicEvent> getCostEvent(final MagicPermanent source) {
            return [
                new MagicPayManaCostEvent(source, "{2}")
            ];
        }

        @Override
        public MagicEvent getPermanentEvent(final MagicPermanent source, final MagicPayedCost payedCost) {
            return new MagicEvent(
                source,
                TARGET_OPPONENT,
                this,
                "Target player\$ gains control of SN."
            );
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            event.processTargetPlayer(game, {
                game.doAction(new GainControlAction(it, event.getPermanent()));
            })
        }
    }
]

**Comment by melvinzhang** [comment]
"Target player other than Crown of Doom's owner" is not the same as target opponent. For example, when the owner pass it to opponent. The opponent cannot pass it back to the owner.

**Comment by melvinzhang** [comment]
Fixed in version added by creating a custom filter to select player other than owner.
