### ISSUE TITLE
Erebos, God of the Dead becomes a creature with damage already present

### ISSUE THREAD

**Issue by tlorance** [magarena/magarena#131]
Still experimenting with the monoblack devotion deck from Firemind Top Decks, I had Erebos in play, the AI took him out by exiling another of my creatures which caused me to lose devotion threshold. Later, I reestablished threshold, but when Erebos became a creature again, he came into "creaturehood" with one damage already on.  I have saved the game log if helpful.

**Comment by ShawnieBoy** [comment]
If the time you re-established devotion was during the same round, the damage would still be there (changing type won't remove damage). If this was after a cleanup step then this is a bug.

You can't assign damage to a non-creature permanent, but a creature that becomes a non-creature permanent will still have all active effects and damage 'waiting' if it becomes a creature again before a cleanup step.

**Comment by melvinzhang** [comment]
There was a bug where only permanents who are creatures at end of turn got their damage marker cleaned up. Fixed it sow that all permanents got the damage marker cleared at end of turn. https://github.com/magarena/magarena/commit/16001fc994ed41b5df6f66ac994c175c5df5fa94
