### ISSUE TITLE
UI generates exception when using Display as: Printed setting

### ISSUE THREAD

**Issue by Achaean** [magarena/magarena#1318]
I'm using it at Win10x64 v.10.0.15063.

I'm experiencing very frequent crashes (at random places), which I didn't have on previous version.

[Logs.zip](https://github.com/magarena/magarena/files/1303864/Logs.zip)

**Comment by melvinzhang** [comment]
Thanks for reporting the bug. I looks like it has got to do with viewing of card images. Tagging @lodici for comments/thoughts on this,

Contents of crash.log
```
CRASH REPORT FOR MAGARENA THREAD Thread[AWT-EventQueue-0,6,main]
CREATED ON 2017/09/14 19:59:56
MAGARENA VERSION 1.88, JRE 1.8.0_144, OS Windows 10_10.0 amd64
================================
Used Memory: 131M
Free Memory: 182M
Total Memory: 313M
Max Memory: 455M
================================
-Xms256m
-Xmx512m
-Xverify:none


Turn : 1  Phase : Mulligan  Step : Begin  Player : Γιώργος  AI : monte carlo tree search  Score : 0
0] Player : Γιώργος  Life : 20  Delayed : Total=0
   - Hand : Beastmaster Ascension
   - Hand : Nettle Sentinel
   - Hand : Beastmaster Ascension
   - Hand : Nettle Sentinel
   - Hand : Forest
   - Hand : Forest
   - Hand : Forest
   - Library : Forest
   - Library : Elvish Champion
   - Library : Twinblade Slasher
   - Library : Elvish Champion
   - Library : Twinblade Slasher
   - Library : Elvish Champion
   - Library : Wirewood Lodge
1] Player : Monty Carlo  Life : 20  Delayed : Total=0
   - Hand : Fortified Rampart
   - Hand : Aetherstream Leopard
   - Hand : Aether Hub
   - Hand : Oakenform
   - Hand : Forest
   - Hand : Aetherstream Leopard
   - Hand : Peema Outrider
   - Library : Self-Assembler
   - Library : Plains
   - Library : Botanical Sanctum
   - Library : Woodland Stream
   - Library : Nebelgast Herald
   - Library : Plains
   - Library : Blossoming Defense
Stack : 0
Score = 0

Exception from controller.runGame: java.util.concurrent.ExecutionException: java.lang.NullPointerException
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at magic.ui.widget.duel.viewer.CardImageWorker.getImage(CardImageWorker.java:72)
	at magic.ui.widget.duel.viewer.CardImageWorker.done(CardImageWorker.java:48)
	at javax.swing.SwingWorker$5.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at sun.swing.AccumulativeRunnable.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at javax.swing.SwingWorker.get(Unknown Source)
	at magic.ui.widget.duel.viewer.CardImageWorker.getImage(CardImageWorker.java:64)
	... 21 more
Caused by: java.lang.NullPointerException
	at magic.ui.widget.duel.viewer.CardViewer.getCardImage(CardViewer.java:224)
	at magic.ui.widget.duel.viewer.CardImageWorker.doInBackground(CardImageWorker.java:39)
	at magic.ui.widget.duel.viewer.CardImageWorker.doInBackground(CardImageWorker.java:16)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

CRASH REPORT FOR MAGARENA THREAD Thread[AWT-EventQueue-0,6,main]
CREATED ON 2017/09/14 20:09:27
MAGARENA VERSION 1.88, JRE 1.8.0_144, OS Windows 10_10.0 amd64
================================
Used Memory: 103M
Free Memory: 233M
Total Memory: 337M
Max Memory: 455M
================================
-Xms256m
-Xmx512m
-Xverify:none


Turn : 1  Phase : Mulligan  Step : Begin  Player : Γιώργος  AI : monte carlo tree search  Score : 0
0] Player : Γιώργος  Life : 20  Delayed : Total=0
   - Hand : Edric, Spymaster of Trest
   - Hand : Island
   - Hand : Silhana Ledgewalker
   - Hand : Breeding Pool
   - Hand : Explore
   - Hand : Hinterland Harbor
   - Hand : Forest
   - Library : Curiosity
   - Library : Snake Umbra
   - Library : Elvish Champion
   - Library : Joraga Warcaller
   - Library : Explore
   - Library : Imperious Perfect
   - Library : Forest
1] Player : Monty Carlo  Life : 20  Delayed : Total=0
   - Hand : Hissing Quagmire
   - Hand : Ghoulcaller's Accomplice
   - Hand : Paradox Engine
   - Hand : Choking Restraints
   - Hand : Plains
   - Hand : Longtusk Cub
   - Hand : Unruly Mob
   - Library : Bitterblade Warrior
   - Library : Tranquil Expanse
   - Library : Forsaken Sanctuary
   - Library : Heroic Intervention
   - Library : Plains
   - Library : Ornery Kudu
   - Library : Concealed Courtyard
Stack : 0
Score = 0

Exception from controller.runGame: java.util.concurrent.ExecutionException: java.lang.NullPointerException
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at magic.ui.widget.duel.viewer.CardImageWorker.getImage(CardImageWorker.java:72)
	at magic.ui.widget.duel.viewer.CardImageWorker.done(CardImageWorker.java:48)
	at javax.swing.SwingWorker$5.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at sun.swing.AccumulativeRunnable.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at javax.swing.SwingWorker.get(Unknown Source)
	at magic.ui.widget.duel.viewer.CardImageWorker.getImage(CardImageWorker.java:64)
	... 21 more
Caused by: java.lang.NullPointerException
	at magic.ui.widget.duel.viewer.CardViewer.getCardImage(CardViewer.java:224)
	at magic.ui.widget.duel.viewer.CardImageWorker.doInBackground(CardImageWorker.java:39)
	at magic.ui.widget.duel.viewer.CardImageWorker.doInBackground(CardImageWorker.java:16)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

CRASH REPORT FOR MAGARENA THREAD Thread[pool-5-thread-1,5,main]
CREATED ON 2017/09/14 20:10:49
MAGARENA VERSION 1.88, JRE 1.8.0_144, OS Windows 10_10.0 amd64
================================
Used Memory: 191M
Free Memory: 134M
Total Memory: 326M
Max Memory: 455M
================================
-Xms256m
-Xmx512m
-Xverify:none


Turn : 1  Phase : Mulligan  Step : NextPhase  Player : Monty Carlo  AI : monte carlo tree search  Score : 0
0] Player : Γιώργος  Life : 20  Delayed : Total=0
   - Hand : Elvish Champion
   - Hand : Explore
   - Hand : Hinterland Harbor
   - Hand : Hinterland Harbor
   - Hand : Hinterland Harbor
   - Hand : Joraga Warcaller
   - Hand : Skyshroud Ranger
   - Library : Mana Leak
   - Library : Forest
   - Library : Snake Umbra
   - Library : Forest
   - Library : Island
   - Library : Copperhorn Scout
   - Library : Elvish Visionary
1] Player : Monty Carlo  Life : 20  Delayed : Total=0
   - Hand : True-Faith Censer
   - Hand : Lumbering Falls
   - Hand : Emrakul's Influence
   - Hand : Mountain
   - Hand : Sphinx of Magosi
   - Hand : Fleeting Memories
   - Hand : Stitchwing Skaab
   - Library : Cryptic Serpent
   - Library : Woodland Stream
   - Library : Island
   - Library : Island
   - Library : Angler Drake
   - Library : Aether Hub
   - Library : Thresher Lizard
Stack : 0
1. AddEventAction (EVENT: NONE Γιώργος may$ take a mulligan. ) = 0
2. AddEventAction (EVENT: NONE Monty Carlo may$ take a mulligan. ) = 0
Score = 0

Exception from controller.runGame: null
java.lang.NullPointerException
	at magic.ui.widget.cards.canvas.CardCanvas.hashCode(CardCanvas.java:40)
	at magic.ui.widget.cards.canvas.CardsCanvas.createListOfCardCanvasObjects(CardsCanvas.java:210)
	at magic.ui.widget.cards.canvas.CardsCanvas.access$1100(CardsCanvas.java:32)
	at magic.ui.widget.cards.canvas.CardsCanvas$3.clearCards(CardsCanvas.java:171)
	at magic.ui.widget.cards.canvas.CardsCanvas$3.run(CardsCanvas.java:145)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by melvinzhang** [comment]
@Achaean In your settings for "Setup Card Images" I assume you are using "Display card images as: Printed"? If so, can you try switching to "Display card images as: Proxy", and see if it improves the situation.

**Comment by Achaean** [comment]
Indeed!
Proxy setting, solves the problem. :-)

**Comment by melvinzhang** [comment]
It is a workaround for the crash, not a proper fix. We will work on the fix in this issue, it shouldn't crash when you have it set as "Printed".

**Comment by Achaean** [comment]
Ooops!
Mea culpa. :-)

**Comment by avamk** [comment]
Hello,

I am encountering the same bug. I'm not a programmer but hope to help, here is my crash.log:

> CRASH REPORT FOR MAGARENA THREAD Thread[AWT-EventQueue-0,6,main]
> CREATED ON 2017/09/15 14:28:58
> MAGARENA VERSION 1.88, JRE 1.8.0_144, OS Linux_4.9.48-1-MANJARO amd64
> ================================
> Used Memory: 169M
> Free Memory: 152M
> Total Memory: 322M
> Max Memory: 455M
> ================================
> -Xms256M
> -Xmx512M
> -Xverify:none
> -Dmagarena.dir=
> 
> 
> Exception from controller.runGame: sun.awt.image.BufImgSurfaceData cannot be cast to sun.java2d.xr.XRSurfaceData
> java.lang.ClassCastException: sun.awt.image.BufImgSurfaceData cannot be cast to sun.java2d.xr.XRSurfaceData
> 	at sun.java2d.xr.XRPMBlitLoops.cacheToTmpSurface(XRPMBlitLoops.java:148)
> 	at sun.java2d.xr.XrSwToPMBlit.Blit(XRPMBlitLoops.java:356)
> 	at sun.java2d.pipe.DrawImage.blitSurfaceData(DrawImage.java:959)
> 	at sun.java2d.pipe.DrawImage.renderImageCopy(DrawImage.java:577)
> 	at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:67)
> 	at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:1014)
> 	at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3318)
> 	at sun.awt.image.ImageRepresentation.drawToBufImage(ImageRepresentation.java:813)
> 	at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:1021)
> 	at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3318)
> 	at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3296)
> 	at javax.swing.ImageIcon.paintIcon(ImageIcon.java:425)
> 	at sun.swing.plaf.synth.SynthIcon.paintIcon(SynthIcon.java:67)
> 	at javax.swing.plaf.synth.SynthGraphicsUtils.paintText(SynthGraphicsUtils.java:396)
> 	at javax.swing.plaf.synth.SynthLabelUI.paint(SynthLabelUI.java:212)
> 	at javax.swing.plaf.synth.SynthLabelUI.update(SynthLabelUI.java:176)
> 	at javax.swing.JComponent.paintComponent(JComponent.java:780)
> 	at javax.swing.JComponent.paint(JComponent.java:1056)
> 	at javax.swing.JComponent.paintChildren(JComponent.java:889)
> 	at javax.swing.JComponent.paint(JComponent.java:1065)
> 	at javax.swing.JComponent.paintChildren(JComponent.java:889)
> 	at javax.swing.JComponent.paint(JComponent.java:1065)
> 	at javax.swing.JComponent.paintChildren(JComponent.java:889)
> 	at javax.swing.JComponent.paint(JComponent.java:1065)
> 	at javax.swing.JComponent.paintChildren(JComponent.java:889)
> 	at javax.swing.JComponent.paint(JComponent.java:1065)
> 	at javax.swing.JComponent.paintChildren(JComponent.java:889)
> 	at javax.swing.JComponent.paint(JComponent.java:1065)
> 	at javax.swing.JComponent.paintChildren(JComponent.java:889)
> 	at javax.swing.JComponent.paint(JComponent.java:1065)
> 	at javax.swing.JComponent.paintChildren(JComponent.java:889)
> 	at javax.swing.JComponent.paint(JComponent.java:1065)
> 	at javax.swing.JComponent.paintChildren(JComponent.java:889)
> 	at javax.swing.JComponent.paint(JComponent.java:1065)
> 	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
> 	at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:290)
> 	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
> 	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
> 	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
> 	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
> 	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
> 	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
> 	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
> 	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
> 	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> 
> CRASH REPORT FOR MAGARENA THREAD Thread[AWT-EventQueue-0,6,main]
> CREATED ON 2017/09/15 16:21:36
> MAGARENA VERSION 1.88, JRE 1.8.0_144, OS Linux_4.9.48-1-MANJARO amd64
> ================================
> Used Memory: 88M
> Free Memory: 157M
> Total Memory: 246M
> Max Memory: 455M
> ================================
> -Xms256M
> -Xmx512M
> -Xverify:none
> -Dmagarena.dir=
> 
> 
> Exception from controller.runGame: java.util.concurrent.ExecutionException: java.lang.NullPointerException
> java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
> 	at magic.ui.widget.duel.viewer.CardImageWorker.getImage(CardImageWorker.java:72)
> 	at magic.ui.widget.duel.viewer.CardImageWorker.done(CardImageWorker.java:48)
> 	at javax.swing.SwingWorker$5.run(SwingWorker.java:737)
> 	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
> 	at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
> 	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
> 	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
> 	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
> 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
> 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
> 	at javax.swing.SwingWorker.get(SwingWorker.java:602)
> 	at magic.ui.widget.duel.viewer.CardImageWorker.getImage(CardImageWorker.java:64)
> 	... 21 more
> Caused by: java.lang.NullPointerException
> 	at magic.ui.widget.duel.viewer.CardViewer.getCardImage(CardViewer.java:224)
> 	at magic.ui.widget.duel.viewer.CardImageWorker.doInBackground(CardImageWorker.java:39)
> 	at magic.ui.widget.duel.viewer.CardImageWorker.doInBackground(CardImageWorker.java:16)
> 	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at javax.swing.SwingWorker.run(SwingWorker.java:334)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> 
> CRASH REPORT FOR MAGARENA THREAD Thread[AWT-EventQueue-0,6,main]
> CREATED ON 2017/09/15 16:22:15
> MAGARENA VERSION 1.88, JRE 1.8.0_144, OS Linux_4.9.48-1-MANJARO amd64
> ================================
> Used Memory: 77M
> Free Memory: 256M
> Total Memory: 334M
> Max Memory: 455M
> ================================
> -Xms256M
> -Xmx512M
> -Xverify:none
> -Dmagarena.dir=
> 
> 
> Turn : 1  Phase : Mulligan  Step : Begin  Player : player  AI : monte carlo tree search  Score : 0
> 0] Player : player  Life : 20  Delayed : Total=0
>    - Library : Skulking Knight
>    - Library : Scarwood Goblins
>    - Library : Dross Harvester
>    - Library : Cryptolith Rite
>    - Library : Vines of the Recluse
>    - Library : Grotag Siege-Runner
>    - Library : Control of the Court
> 1] Player : Monty Carlo  Life : 20  Delayed : Total=0
> Stack : 0
> Score = 0
> 
> Exception from controller.runGame: java.util.concurrent.ExecutionException: java.lang.NullPointerException
> java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
> 	at magic.ui.widget.duel.viewer.CardImageWorker.getImage(CardImageWorker.java:72)
> 	at magic.ui.widget.duel.viewer.CardImageWorker.done(CardImageWorker.java:48)
> 	at javax.swing.SwingWorker$5.run(SwingWorker.java:737)
> 	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
> 	at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
> 	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
> 	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
> 	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
> 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
> 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
> 	at javax.swing.SwingWorker.get(SwingWorker.java:602)
> 	at magic.ui.widget.duel.viewer.CardImageWorker.getImage(CardImageWorker.java:64)
> 	... 21 more
> Caused by: java.lang.NullPointerException
> 	at magic.ui.widget.duel.viewer.CardViewer.getCardImage(CardViewer.java:224)
> 	at magic.ui.widget.duel.viewer.CardImageWorker.doInBackground(CardImageWorker.java:39)
> 	at magic.ui.widget.duel.viewer.CardImageWorker.doInBackground(CardImageWorker.java:16)
> 	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at javax.swing.SwingWorker.run(SwingWorker.java:334)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)

**Comment by melvinzhang** [comment]
release zips posted on https://github.com/magarena/magarena/releases/tag/1.88 have been patched with the fix. Please redownload a new copy of the release.
