### ISSUE TITLE
Kaervek's Hex (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1319]
name=Kaervek's Hex
image=http://magiccards.info/scans/en/mr/28.jpg
value=2.233
rarity=U
type=Sorcery
cost={3}{B}
effect=SN deals 1 damage to each nonblack creature~and SN deals 1 damage to each green creature.
timing=main
oracle=Kaervek's Hex deals 1 damage to each nonblack creature and an additional 1 damage to each green creature.

**Comment by melvinzhang** [comment]
This needs to be in groovy, the current script will deal damage 1 damage twice to green creatures. Causing enrage to trigger twice, it should deal 2 damage to green creatures once.
