### ISSUE TITLE
Crash when ESC pressed.

### ISSUE THREAD

**Issue by Achaean** [magarena/magarena#1340]
Magarena v.1.88 on Win 10 Pro x64 v.10.0.15063 with Java v.8.144 x64.

Going Settings -> Setup card images, if you press ESC while ...loading card data... the game crashes.
[Logs.zip](https://github.com/magarena/magarena/files/1329643/Logs.zip)

**Comment by melvinzhang** [comment]
Thanks, I can confirm the bug. The attached log file is very helpful.
