### ISSUE TITLE
Crystalline Nautilus (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1351]
[Crystalline_Nautilus.txt](https://github.com/magarena/magarena/files/1333945/Crystalline_Nautilus.txt)

**Comment by kelsioboy** [comment]
Hi, I sent this card to you and as it should have been noticed I did not change it. What is wrong with this card as it seems to be working right?

**Comment by melvinzhang** [comment]
We are aware of this card, the problem is currently AI will only bestow on it own creature, but for this card you may want to enchant an opponent's creature.

**Comment by melvinzhang** [comment]
The other card with this issue is "Hypnotic Siren"
