### ISSUE TITLE
Request for Homing Sliver

### ISSUE THREAD

**Issue by allentiak** [magarena/magarena#1354]
Card Name:
Homing Sliver
Mana Cost:
2 Red
Converted Mana Cost:
3
Types:
Creature — Sliver
Card Text:
Each Sliver card in each player's hand has slivercycling 3.
Slivercycling 3 (3, Discard this card: Search your library for a Sliver card, reveal it, and put it into your hand. Then shuffle your library.)
P/T:
2 / 2
Expansion:
Premium Deck Series: Slivers (Common) Premium Deck Series: Slivers
Rarity:
Common
All Sets:
Future Sight (Common)
Premium Deck Series: Slivers (Common)
Card Number:
19
Artist:
Trevor Hairsine

http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=207908
https://www.firemind.ch/cards/126162

**Comment by melvinzhang** [comment]
Please use https://www.firemind.ch/cards/search

**Comment by allentiak** [comment]
Thanks for the information, Melvin.
Done.

**Comment by allentiak** [comment]
I also uploaded a script for the card. Could you please check it?

**Comment by allentiak** [comment]
The script I sent does not compile. However, the error message from Firemind does not include the text, so I cannot get to fix it...

**Comment by firemind** [comment]
where did you look? There is a link to the failed duel that includes the java stack trace https://www.firemind.ch/duels/609300

**Comment by allentiak** [comment]
Although the Java stack trace **is** included, the source for the script that made the duel fail **is not**.
Which is what makes it difficult to debug the script itself...

**Comment by melvinzhang** [comment]
@allentiak for now you can find it from the status page, https://www.firemind.ch/status -> select the "card script submissions" tab -> Homing Silver.

**Comment by allentiak** [comment]
Thanks! I'll check it.

**Comment by melvinzhang** [comment]
The key line on the stack trace is
```
Caused by: java.lang.RuntimeException: unknown card property value "url" = "https://magiccards.info/pds/en/19.html"
```
The url property was removed in 2014. Card scripts should not have this property. 

There are other problems as well for example:
```
ability=Slivercycling {3}{U};\
Each Sliver card in each player's hand has slivercycling {3}.
```
Does not parse as "Slivercycling" is not implemented in the ability system and also adding abilities to cards is not possible.

If you see the current script file in the repo, https://github.com/magarena/magarena/blob/f47b0268990a424d02f2bbdad1199403b8267648/release/Magarena/scripts_missing/Homing_Sliver.txt it has the property `status=not supported: card-modification` to indicate that card modification is not implemented in the rules engine.

**Comment by melvinzhang** [comment]
@allentiak Do note that all cards are either found in `<installed dir>/Magarena/scripts` or `<installed dir>/Magarena/scripts_missing` If a card is in `scripts_missing` means it doesn't work as it, some additional parts needs to be provided. In the best case, it needs some groovy code to implement one of its abilities or if it has the "not supported" status the core rules engine written in Java needs to be extended.

**Comment by allentiak** [comment]
Thanks again, Melvin. I'll give it a look and go back to you.
Maybe should I open a new bug?

**Comment by melvinzhang** [comment]
> Maybe should I open a new bug?

Regarding "Homing Sliver" we can continue here. If it is a separate problem, please create a new issue.

**Comment by firemind** [comment]
Looks like I might have been causing some confusion here. When I first added the script submission feature in 2013 I just copied a script to link to as an example from the form: https://www.firemind.ch/script_example.txt

Four years later this example is probably outdated (e.g. it includes the url property). Do you have a script I should link to instead as a perfect example (through a raw-link to github this time)? Or should I remove the link entirely?

I will be adding a feature to load the .txt and .groovy files from release/Magarena/scripts_missing/ based on the selected card. This will be based on the git clone I update hourly to get new not-implementable-reasons.

Also if people go through **Workspace** -> **Find card to work on** (http://firemind.local/cards/missing) it will filter out cards with not-implementable reasons automatically which should help with confusion.

**Comment by melvinzhang** [comment]
@firemind thanks, I was wondering where the old script format came from. I think using the scripts_missing file will be the best, once we have that then we can retire the static file link.

**Comment by firemind** [comment]
Alright I'll remove the link.

While I'm at it, there is also this text I just added on a whim that shows up on top of the form:

> Thank you for considering submitting a script. This helps speed up the process of adding new card a lot.
> If you need instructions on how to submit a script please visit the forums or have a look at the examples

Would you like me to adjust that or maybe link somewhere (wiki, forum thread, this issue tracker)?

**Comment by melvinzhang** [comment]
@firemind perhaps point to the scripting guide on the wiki, this page https://github.com/magarena/magarena/wiki/Basic-Structure

**Comment by firemind** [comment]
done, I just deployed the new version
