### ISSUE TITLE
Sliver Hive (New Card)

### ISSUE THREAD

**Issue by allentiak** [magarena/magarena#1357]
Land

{T}: Add {C} to your mana pool.
{T}: Add one mana of any color to your mana pool. Spend this mana only to cast a Sliver spell.
{5}, {T}: Create a 1/1 colorless Sliver creature token. Activate this ability only if you control a Sliver.

https://magiccards.info/m15/en/247.html

**Comment by melvinzhang** [comment]
Please use https://www.firemind.ch/cards/search

**Comment by allentiak** [comment]
Thanks for the information, Melvin.
Done.
