### ISSUE TITLE
Cavern of Souls (New Card)

### ISSUE THREAD

**Issue by allentiak** [magarena/magarena#1358]
Land

As Cavern of Souls enters the battlefield, choose a creature type.
{T}: Add {C} to your mana pool.
{T}: Add one mana of any color to your mana pool. Spend this mana only to cast a creature spell of the chosen type, and that spell can't be countered.

https://magiccards.info/mm3/en/232.html

**Comment by melvinzhang** [comment]
@allentiak we use a separate website to keep track of card requests so we can tabulate the total number of requests for each card. Please use https://www.firemind.ch/cards/search to search for the card and select request it. Do create an account on Firemind first so we can track the number of unique requests.

**Comment by allentiak** [comment]
Thanks for the information, Melvin.
Done.
