### ISSUE TITLE
Treasure Map (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1359]
[Treasure_Map.zip](https://github.com/magarena/magarena/files/1366298/Treasure_Map.zip)

**Comment by kelsioboy** [comment]
I changed the landmark counter by gold counter, as there is no landmark counter.

**Comment by bilbo2** [comment]
this one seems to be implemented in 0ad52d26dc29460f7952e83699b1df5e03ff20d8 about a month ago

**Comment by melvinzhang** [comment]
Thanks for the update on the status. Good to close.
