### ISSUE TITLE
Deck Legality check button

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#136]
Just an idea while putting together some of my RL decks.

In the deck editor, when building a deck, if there was a button that could be pressed to show the legality of the deck in progress in different formats. Maybe even going as far to explain why for each format (eg. Skullclamp is banned in Modern)

I know that filters can be set when building, but when importing or creating from memory, I think it could be a cool function to have.

**Comment by lodici** [comment]
I would imagine you could do that on the go using a new viewer/panel in the deck editor side-bar which refreshes each time the deck is updated (like the deck stats panel). Bearing in mind I have a rudimentary understanding of deck legality, if you could create a simple mockup of what you would like to see it would help me to better understand what you need.

**Comment by lodici** [comment]
Was not quite ready for this to go into 1.62. A new "legality" tab has been added to the deck editor.

![capture-17](https://cloud.githubusercontent.com/assets/2443519/7913809/aa77a660-086a-11e5-92da-2b5b37578abe.gif)

The screenshot should be self-explanatory. The card icon colors are
- greyed out if illegal.
- green if legal for the selected format.
- red if card is banned.
- orange if card is restricted or the number of copies exceeds the format max _[1]_.

_[1]_ There is still a question mark over whether it identifies basic lands properly or not.

**Comment by ShawnieBoy** [comment]
I'm loving this!

May get me away from the old split view :wink:

**Comment by ShawnieBoy** [comment]
Will need to check amount of copies for cards which allow more than 4 in a deck - eg. Relentless Rats

**Comment by lodici** [comment]
> Will need to check amount of copies for cards which allow more than 4 in a deck - eg. Relentless Rats

Ok, I did not realize that a deck could override the format rulings.

This is all driven by the data in the ``fmt`` files with an update to ``MagicFormat`` that lets you specify the minimum deck size and max copies of a card for each format, which is currently 60 and 4 respectively.

**Comment by ShawnieBoy** [comment]
It's only for two cards, [Relentless Rats](http://magiccards.info/m11/en/113.html) and [Shadowborn Apostle](http://magiccards.info/m14/en/114.html).
I can remember seeing an override for those two cards specifically, related to saving legal decks.

If those cards are legal in a format, you can have any number of them in a deck.

**Comment by melvinzhang** [comment]
Looks good! I'd like to try a different approach to writing the release notes for 1.63, to update it as we go along rather than do it all at once (going through 500+ commits at the end takes quite a while). Do add a short note for users about this new feature in 1.63.

**Comment by lodici** [comment]
> It's only for two cards, Relentless Rats and Shadowborn Apostle.

Thanks, I have exempted these two cards from the max copies legality check.

> Do add a short note for users about this new feature in 1.63.

Good idea, will do.

**Comment by lodici** [comment]
Implemented.
