### ISSUE TITLE
Druidic Satchel (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1371]
name=Druidic Satchel
image=https://magiccards.info/scans/en/m12/207.jpg
value=3.667
rarity=R
type=Artifact
cost={3}
timing=artifact
requires_groovy_code
oracle={2}, {T}: Reveal the top card of your library. If it's a creature card, create a 1/1 green Saproling creature token. If it's a land card, put that card onto the battlefield under your control. If it's a noncreature, nonland card, you gain 2 life.
#Land Creatures should trigger two effects

[
    new MagicPermanentActivation(
        new MagicActivationHints(MagicTiming.Draw),
        "Reveal"
    ) {
        @Override
        public Iterable<? extends MagicEvent> getCostEvent(final MagicPermanent source) {
            return [
                new MagicPayManaCostEvent(source,"{2}"),
                new MagicTapEvent(source)
            ];
        }

        @Override
        public MagicEvent getPermanentEvent(final MagicPermanent source, final MagicPayedCost payedCost) {
            return new MagicEvent(
                source,
                this,
                "Reveal the top card of PN's library. If it's a creature card, create a 1/1 green Saproling creature token. " +
                "If it's a land card, put that card onto the battlefield under PN control. " +
                "If it's a noncreature, nonland card, PN gain 2 life."
            );
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            for (final MagicCard card : event.getPlayer().getLibrary().getCardsFromTop(1)) {
                game.doAction(new RevealAction(card));
                if (card.hasType(MagicType.Creature)) {
                    game.doAction(new PlayTokensAction(event.getPlayer(), CardDefinitions.getToken("1/1 green Saproling creature token"),1));                        
                }
                if (card.hasType(MagicType.Land)) {
                    game.doAction(new ReturnCardAction(MagicLocationType.OwnersLibrary,card,event.getPlayer()));
                }
                if (!card.hasType(MagicType.Creature) && !card.hasType(MagicType.Land)) { 
                    game.doAction(new ChangeLifeAction(event.getPlayer(),2));
                }
            }
        }
    }
]

**Comment by kelsioboy** [comment]
Tested with "Dryad Arbor" and is doing both effects.
You are creating the "Saproling creature token" and put "Dryad Arbor" on the battlefield.

**Comment by melvinzhang** [comment]
Merged.
