### ISSUE TITLE
Temple of Aclazotz (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1388]
[Temple_of_Aclazotz.zip](https://github.com/magarena/magarena/files/1415427/Temple_of_Aclazotz.zip)

**Comment by bilbo2** [comment]
Implemented in 0ad52d26dc29460f7952e83699b1df5e03ff20d8

**Comment by melvinzhang** [comment]
Thanks for the update. Closing as this has been added.
