### ISSUE TITLE
Garruk, Apex Predator (Fix for the emblem)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1390]
name=Garruk, Apex Predator
image=https://magiccards.info/scans/en/m15/210.jpg
value=4.125
rarity=M
type=Legendary,Planeswalker
subtype=Garruk
cost={5}{B}{G}
loyalty=5
ability=+1: Destroy another target planeswalker.;\
        +1: Create a 3/3 black Beast creature token with deathtouch.;\
        −8: Target opponent gets an emblem with "Whenever a creature attacks you, that creature gets +5/+5 and gains trample until end of turn."
timing=main
oracle=+1: Destroy another target planeswalker.\n+1: Create a 3/3 black Beast creature token with deathtouch.\n−3: Destroy target creature. You gain life equal to its toughness.\n−8: Target opponent gets an emblem with "Whenever a creature attacks you, it gets +5/+5 and gains trample until end of turn."
requires_groovy_code

**Comment by kelsioboy** [comment]
Just replace "it" with "that creature".

**Comment by melvinzhang** [comment]
Thanks for the fix!
