### ISSUE TITLE
Verdant Sun's Avatar (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1395]
[Verdant_Sun_s_Avatar.zip](https://github.com/magarena/magarena/files/1428422/Verdant_Sun_s_Avatar.zip)

**Comment by bilbo2** [comment]
Implemented in 0ad52d26dc29460f7952e83699b1df5e03ff20d8

**Comment by melvinzhang** [comment]
Thanks for the update. Closing as this has been added.
