### ISSUE TITLE
Summoning sickness should not prevent declaring a creature as blocker

### ISSUE THREAD

**Issue by allentiak** [magarena/magarena#1401]
In this case, I should be able to block this attack with my only untapped creature.

![Attack screenshot](https://user-images.githubusercontent.com/1922297/32453058-097dbad6-c2fa-11e7-9abf-57a8777d9261.png)

[gameplay-report.zip](https://github.com/magarena/magarena/files/1447062/gameplay-report.zip)

**Comment by ShawnieBoy** [comment]
Aether figment is Unblockable, and the other has protection from white.

**Comment by allentiak** [comment]
Sorry! Thanks for noticing it.
