### ISSUE TITLE
minimax AI makes decisions that are self-evidently bad

### ISSUE THREAD

**Issue by cereal314** [magarena/magarena#141]
When i have the minimax AI (level 8, which i presume is the strongest) play the legacy.Infect deck (from the "Firemind Top Decks" selection) this is especially apparent. For instance, it needlessly wastes Mutagenic Growth (and i think also other pump spells) on creatures (without haste) it just put on the battlefield. It will also bizarrely pump creatures of mine for no reason (with vines of vastwood mostly).

It also tends to keep lands in its hand for seemingly no reason (other than potential bluff value i suppose).

Here's a game.log illustrating the needless pumping (i played the 2012elves deck). I'll try to reproduce the other issues as well. The crucial line is marked with an arrow (<----).

LOG (C): Minimax may (no) take a mulligan.
LOG (P): Cereal may (no) take a mulligan.
LOG (C): Minimax may (no) take a mulligan.
LOG (P): Play Forest. Put Forest onto the battlefield.
MMAB cheat=false index=1 life=20 turn=2 phase=FirstMain slice=8000 time=5401
  [330/4866/99900000 at 10] (pass)
* [330/7649/99900000 at 9] (Forest)
LOG (C): Play Forest. Put Forest onto the battlefield.
MMAB cheat=false index=1 life=20 turn=2 phase=FirstMain slice=8000 time=3953
* [330/4435/99900000 at 8] (pass)
  [330/4986/99900000 at 8] (Glistener Elf)
MMAB cheat=false index=1 life=20 turn=2 phase=SecondMain slice=8000 time=5883
  [330/4053/99900000 at 11] (pass)
* [330/7550/99900000 at 7] (Glistener Elf)
LOG (C): Pay {G}. Tap Forest. Play Glistener Elf.
LOG (C): Put Glistener Elf onto the battlefield.
LOG (P): Play Forest. Put Forest onto the battlefield.
LOG (P): Tap Forest. Tap Forest. Pay {1}{G}. Play Elvish Visionary.
MMAB cheat=false index=1 life=20 turn=3 phase=FirstMain slice=8000 time=7192
* [330/8599/3759 at 10] (pass)
  [330/4730/3192 at 9] (Mutagenic Growth)
LOG (P): Put Elvish Visionary onto the battlefield.
MMAB cheat=false index=1 life=20 turn=3 phase=FirstMain slice=8000 time=7118
  [330/8420/99900000 at 10] (pass)
* [330/4805/99900000 at 9] (Mutagenic Growth)
LOG (C): Pay 2 life. Play Mutagenic Growth. 
LOG (C): Target creature gets +2/+2 until end of turn. (Glistener Elf) <---- (This does nothing, as i couldn't possibly attack yet)
LOG (P): Cereal draws a card.
MMAB cheat=false index=1 life=18 turn=4 phase=FirstMain slice=2666 time=4106
  [330/2870/3834 at 8] (pass)
* [330/1548/99900000 at 9] (Vines of Vastwood)
  [330/669/4377 at 6] (Cathedral of War)
  [330/1022/99900000 at 9] (Glistener Elf)
  [330/1580/99900000 at 9] (Forest)
  [330/723/2933 at 11] (Giant Growth)
MMAB cheat=false index=1 life=18 turn=4 phase=FirstMain slice=8000 time=5430
* [330/2261/99900000 at 9] (Elvish Visionary)
  [330/2603/99900000 at 9] (Glistener Elf)
LOG (C): Pay {G}. Tap Forest. Minimax may (no) pay the kicker cost. Play Vines of Vastwood.
LOG (C): Target creature (Elvish Visionary) can't be the target of spells or abilities your opponent controls this turn. If Vines of Vastwood was kicked, that creature gets +4/+4 until end of turn.
MMAB cheat=false index=1 life=18 turn=4 phase=DeclareAttackers slice=8000 time=5832
* [330/1066/99900000 at 8] ([Glistener Elf])
  [330/3407/99900000 at 10] ([])
LOG (C): Minimax attacks with Glistener Elf.

**Comment by melvinzhang** [comment]
Thanks for the report. The AI scores looks a bit weird. Can you email the full game.log file to magarena@googlegroups.com ?

**Comment by cereal314** [comment]
Sorry, I don't have the log anymore. If i recall correctly, the above was actually the full log apart from the beginning bit with the time and date and operating system (windows 7 64 bit). If i encounter the issue again, i'll email the log.

**Comment by melvinzhang** [comment]
The above log only shows up to turn 4. Do you recall the ending of the game? Who won?

Btw, the strongest AI is monte-carlo level 8 not minimax level 8.

**Comment by cereal314** [comment]
Yeah, i left the game at that point. I have since recreated the issue in a game which the AI subsequently won easily. In another game the AI straight up didn't take a sure win. I have the log for both if you're interested.

The AI comparison is interesting. Does a higher level mean higher search depth for the minimax AI? If so, i'm guessing the scoring for unknown cards is problematic (i only had a cursory glance at the source code, so this is to be taken with a grain of salt).

**Comment by melvinzhang** [comment]
Yeah, I'm interested in the log for both, please email to magarena@googlegroups.com

Higher level mean more thinking time, level n -> n seconds of thinking time per move. Can you elaborate on why you feel the scoring for unknown cards is problematic?

**Comment by cereal314** [comment]
Sent both of the log files. As for the scoring: Am i correct in thinking that unknown cards get a flat score regardless of what's actually in the deck?

I could elaborate, but my inkling about it being problematic is based on a whole lot of assumptions which may or may not be true.

**Comment by melvinzhang** [comment]
Yes, hidden cards are considered all the same by the honest AIs. The
cheating AIs is able to use the actual cards, which may have different card
scores.

**Comment by melvinzhang** [comment]
We have since implemented gameplay reports that include snapshots we can directly open up in game. Do consider including gameplay report when such moves occur. A gameplay report is created in-game via Esc -> Gameplay report.
