### ISSUE TITLE
include Fulmene as contributor in README

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#1418]
@Fulmene Thanks for the many card contributions! They will be out end of this month as part of Jan's release.

In the release notes for each release, we will list down the contributors. We will also include the full list of contributors at the top of the README.txt file. How should we properly provide attribution for you? Would using your github username (Fulmene) be ok or should we use something else? Do let us know. Thanks.

**Comment by Fulmene** [comment]
Thanks! This is my first serious contribution into an open source project and it is a very good experience.

Referring to me as Fulmene is OK.

**Comment by melvinzhang** [comment]
Glad to hear that it was a good experience for you. Look out for Jan's release coming out this weekend.
