### ISSUE TITLE
Crash when playing Heart-Piercer Manticore

### ISSUE THREAD

**Issue by Fulmene** [magarena/magarena#1419]
I just found out that Heart-Piercer Manticore, added by #1415, causes the game to crash, but I can't figure out how to properly implement its ability or find any similar card for reference.
[crash.log](https://github.com/magarena/magarena/files/1661976/crash.log)

**Comment by melvinzhang** [comment]
Checking the result of a choice in an event must be done in the action for that event. Here, we are checking sacrificeEvent.isYes before the event has been processed, hence there is a crash as it cannot find the selected option (addEvent puts the event onto a queue for processing). The action is like a callback, it is called when the event choice is made by the player.

In short, the yes check to deal damage should be moved into the sacrificeAction.

**Comment by Fulmene** [comment]
How do I handle the "When you do, SN deals damage to target creature or player" though? I think the targeting event would be the one returned by executeTrigger.

**Comment by melvinzhang** [comment]
After the sacrifice action, use an EnqueueTriggerAction to put the new event for dealing damage on the stack. i.e. `game.doAction(new EnqueueTriggerAction(damageEvent))`

**Comment by melvinzhang** [comment]
The "When you do... damage" is a new trigger with its own target. The way you have created the event now is correct, just need to create the event and put it on the stack inside the sacrificeAction.

**Comment by Fulmene** [comment]
Ah I see. So it's not a single ability like Fling, but rather two separate abilities that's tied to each other.

**Comment by melvinzhang** [comment]
That's right, there are two triggers here. One ETB trigger and one that triggers when the player scarifies due to the ETB trigger's effect.
