### ISSUE TITLE
Awaken the Sky Tyrant (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1428]
name=Awaken the Sky Tyrant
image=https://magiccards.info/scans/en/c15/24.jpg
image_updated=2016-02-29
value=2.500
rarity=R
type=Enchantment
cost={3}{R}
timing=enchantment
oracle=When a source an opponent controls deals damage to you, sacrifice Awaken the Sky Tyrant. If you do, create a 5/5 red Dragon creature token with flying.
requires_groovy_code

[
    new DamageIsDealtTrigger() {
        @Override
        public MagicEvent executeTrigger(final MagicGame game,final MagicPermanent permanent,final MagicDamage damage) {
            return permanent.isEnemy(damage.getSource()) && permanent.isController(damage.getTarget()) ?
                new MagicEvent(
                    permanent,
                    this,
                    "PN Sacrifices SN. If PN does, then creates a 5/5 red Dragon creature token with flying."
                ):
                MagicEvent.NONE;
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            final MagicEvent sac = new MagicSacrificeEvent(event.getPermanent());
            if (sac.isSatisfied()) {
            game.addEvent(sac);
            game.doAction(new PlayTokensAction(event.getPlayer(), CardDefinitions.getToken("5/5 red Dragon creature token with flying"),1));
            }
        }
    }
]

**Comment by kelsioboy** [comment]
I'm sending another groovy because the one I sent first is wrong and I can not edit it directly.

**Comment by kelsioboy** [comment]
[
    new DamageIsDealtTrigger() {
        @Override
        public MagicEvent executeTrigger(final MagicGame game,final MagicPermanent permanent,final MagicDamage damage) {
            return permanent.isEnemy(damage.getSource()) && permanent.isController(damage.getTarget()) ?
                new MagicEvent(
                    permanent,
                    this,
                    "PN Sacrifices SN. If PN does, then creates a 5/5 red Dragon creature token with flying."
                ):
                MagicEvent.NONE;
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            final MagicEvent sac = new MagicSacrificeEvent(event.getPermanent());
            if (sac.isSatisfied()) {
            game.addEvent(sac);
            game.doAction(new PlayTokensAction(event.getPlayer(), CardDefinitions.getToken("5/5 red Dragon creature token with flying"),1));
            }
        }
    }
]

**Comment by melvinzhang** [comment]
Merged.
