### ISSUE TITLE
Deathgorge Scavenger (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1433]
name=Deathgorge Scavenger
image=https://magiccards.info/scans/en/xln/184.jpg
value=2.500
rarity=R
type=Creature
subtype=Dinosaur
cost={2}{G}
pt=3/2
timing=main
requires_groovy_code
oracle=Whenever Deathgorge Scavenger enters the battlefield or attacks, you may exile target card from a graveyard. If a creature card is exiled this way, you gain 2 life. If a noncreature card is exiled this way, Deathgorge Scavenger gets +1/+1 until end of turn.

def choice = MagicTargetChoice.Positive("target card from a graveyard")

[
    new EntersBattlefieldTrigger() {
        @Override
        public MagicEvent executeTrigger(final MagicGame game,final MagicPermanent permanent, final MagicPayedCost payedCost) {
            return new MagicEvent(
                permanent,
                new MagicMayChoice(choice),
                MagicGraveyardTargetPicker.PutOntoBattlefield,
                this,
                "PN may\$ exile target card from a graveyard\$. If a creature card is exiled this way, PN gain 2 life. "+
                "If a noncreature card is exiled this way, SN gets +1/+1 until end of turn."
            );
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            if (event.isYes()) {
            event.processTargetCard(game, {
                final MagicPlayer player = event.getPlayer();
                game.doAction(new ShiftCardAction(it, MagicLocationType.Graveyard, MagicLocationType.Exile));
                if (it.hasType(MagicType.Creature) && it.isInExile()) {
                game.doAction(new ChangeLifeAction(player, 2));
                    } else {
                game.doAction(new ChangeTurnPTAction(event.getPermanent(), 1, 1));
                    }
                });
            }
        }
    },
    new ThisAttacksTrigger() {
        @Override
        public MagicEvent executeTrigger(final MagicGame game,final MagicPermanent permanent, final MagicPermanent attacker) {
            return new MagicEvent(
                permanent,
                new MagicMayChoice(choice),
                MagicGraveyardTargetPicker.PutOntoBattlefield,
                this,
                "PN may\$ exile target card from a graveyard\$. If a creature card is exiled this way, PN gain 2 life. "+
                "If a noncreature card is exiled this way, SN gets +1/+1 until end of turn."
            );
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            if (event.isYes()) {
            event.processTargetCard(game, {
                final MagicPlayer player = event.getPlayer();
                game.doAction(new ShiftCardAction(it, MagicLocationType.Graveyard, MagicLocationType.Exile));
                if (it.hasType(MagicType.Creature) && it.isInExile()) {
                game.doAction(new ChangeLifeAction(player, 2));
                    } else {
                game.doAction(new ChangeTurnPTAction(event.getPermanent(), 1, 1));
                    }
                });
            }
        }
    }
]

**Comment by bilbo2** [comment]
Already implemented in e1c73ed8ba13a7dd0aae0318638879fd11f2eff0

**Comment by melvinzhang** [comment]
Thanks for the update. Closing this.
