### ISSUE TITLE
Debt to the Deathless (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1434]
name=Debt to the Deathless
image=https://magiccards.info/scans/en/dgm/64.jpg
value=3.784
rarity=U
type=Sorcery
cost={X}{W}{W}{B}{B}
timing=main
oracle=Each opponent loses two times X life. You gain life equal to the life lost this way.
requires_groovy_code

[
    new MagicSpellCardEvent() {
        @Override
        public MagicEvent getEvent(final MagicCardOnStack cardOnStack,final MagicPayedCost payedCost) {
            return new MagicEvent(
                cardOnStack,
                cardOnStack.getOpponent(),
                payedCost.getX(),
                this,
                "PN loses twice X life. (X="+payedCost.getX()+")" 
            );
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
                final ChangeLifeAction act = new ChangeLifeAction(event.getPlayer(), -event.getRefInt() * 2);
                game.doAction(act);
                final int amount = -act.getLifeChange();
                final MagicPlayer you = event.cardOnStack.getController();
                game.logAppendMessage(you, "${you.getName()} gains (${amount}) life.");
                game.doAction(new ChangeLifeAction(you,amount));
        }
    }
]

**Comment by melvinzhang** [comment]
Merged.
