### ISSUE TITLE
Divine Congregation (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1436]
name=Divine Congregation
image=https://magiccards.info/scans/en/ts/13.jpg
value=2.643
rarity=C
type=Sorcery
cost={3}{W}
ability=Suspend 5—{1}{W}
timing=main
requires_groovy_code
oracle=You gain 2 life for each creature target player controls.\nSuspend 5—{1}{W}

[
    new MagicSpellCardEvent() {
        @Override
        public MagicEvent getEvent(final MagicCardOnStack cardOnStack,final MagicPayedCost payedCost) {
            return new MagicEvent(
                cardOnStack,
                TARGET_PLAYER,
                this,
                "PN gain 2 life for each creature target player\$ controls."
            );
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            event.processTargetPlayer(game, {
                final MagicPlayer it ->
                final int amount = it.getNrOfPermanents(MagicType.Creature);
                final MagicPlayer player = event.getPlayer();
                game.logAppendValue(player, amount);
                game.doAction(new ChangeLifeAction(player, amount*2));
            });
        }
    }
]

**Comment by melvinzhang** [comment]
Merged.
