### ISSUE TITLE
Master the Way (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1445]
name=Master the Way
image=https://magiccards.info/scans/en/ktk/188.jpg
value=3.500
rarity=U
type=Sorcery
cost={3}{U}{R}
timing=main
oracle=Draw a card. Master the Way deals damage to target creature or player equal to the number of cards in your hand.
requires_groovy_code

def effect = MagicRuleEventAction.create("SN deals damage to target creature or player equal to the number of cards in your hand.")

[
    new MagicSpellCardEvent() {
        @Override
        public MagicEvent getEvent(final MagicCardOnStack cardOnStack,final MagicPayedCost payedCost) {
            return new MagicEvent(
                cardOnStack,
                this,
                "PN draw a card."
            );
        }

        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            game.doAction(new DrawAction(event.getPlayer()));
            game.addEvent(effect.getEvent(event));
        }
    }
]

**Comment by melvinzhang** [comment]
Merged.
