### ISSUE TITLE
Nezumi Shortfang (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1448]
[Nezumi_Shortfang.zip](https://github.com/magarena/magarena/files/2090907/Nezumi_Shortfang.zip)

**Comment by bilbo2** [comment]
This wording may be incorrect if there would be more than 2 players supported in the future (like 2-hg or alike ...)

Not sure what are plans with regard of supporting 3+ players matches ...

**Comment by melvinzhang** [comment]
Should be fine, don't expect more than 2 players to happen anytime soon. Perhaps good to add a comment in there (starting with #) to remind us to fix this card if the 2 player assumption changes later.

**Comment by bilbo2** [comment]
When testing, I found a problem with the ability:

ability={1}{B}, {T}: Target opponent discards a card.~Then if an opponent has no cards in hand, flip SN.

The "no cards in the hand" seems to be evaluated when the ability is activated, not "then". So if opponent discards from 1 to 0, Nezumi does not flip. If opponent have 0 cards ant nothiong to discard, Nezumi is flipped.

Maybe parsing of the "Then" word is broken? Or is it limit of the engine?

**Comment by bilbo2** [comment]
Also a small bug in the flipped card I had to fix .... opponent is not supposed to gain life if he has 4 or more cards :)

```
         public void executeEvent(final MagicGame game, final MagicEvent event) {
             final MagicPlayer player = event.getRefPlayer();
             final int amount = 3 - player.getHandSize();
-            game.doAction(new ChangeLifeAction(player,-amount));
+            if (amount > 0) {
+                game.doAction(new ChangeLifeAction(player,-amount));
+            }
         }
     }
 ]
```

**Comment by kelsioboy** [comment]
I corrected and resent "Nezumi Shortfang" now in groovy.

**Comment by melvinzhang** [comment]
Merged
