### ISSUE TITLE
Value rating and Gatherer Scores

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#145]
As I've just realised [on the forums] (http://www.slightlymagic.net/forum/viewtopic.php?f=82&t=14985&start=75#p176514). The gatherer ratings are set specific. Does the method to pull the card Values try to pull the highest rating of all printed editions?

**Comment by melvinzhang** [comment]
No, it takes the data from the page returned by http://gatherer.wizards.com/pages/card/details.aspx?name=[card name]. This has the issue that cards recently reprinted has 0 votes and their value is not updated from the default of 2.5.

**Comment by ShawnieBoy** [comment]
Looking at the site there doesn't seem to be an easy way to pull the highest rating per card. Most of the ratings even out in the end, may just take a while.
