### ISSUE TITLE
Nicol Bolas, the Deceiver (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1450]
name=Nicol Bolas, the Deceiver
image=https://magiccards.info/scans/en/hou/205.jpg
value=2.500
rarity=M
type=Legendary,Planeswalker
subtype=Bolas
cost={5}{U}{B}{R}
loyalty=5
ability=−3: Destroy target creature.~Draw a card.;\
        −11: SN deals 7 damage to each opponent.~You draw seven cards.
timing=main
oracle=+3: Each opponent loses 3 life unless that player sacrifices a nonland permanent or discards a card.\n−3: Destroy target creature. Draw a card.\n−11: Nicol Bolas, the Deceiver deals 7 damage to each opponent. You draw seven cards.
requires_groovy_code

def choice = new MagicTargetChoice("a nonland permanent to sacrifice");

[
    new MagicPlaneswalkerActivation(3) {        
        @Override
        public MagicEvent getPermanentEvent(final MagicPermanent source, final MagicPayedCost payedCost) {             
            return new MagicEvent(
                source,
                source.getOpponent(),
                new MagicOrChoice(
                    MagicChoice.NONE,
                    MagicChoice.NONE,
                    MagicChoice.NONE
                ),
                source.getController(),
                this,
                "Choose one\$ — (1) PN lose 3 life; " +
                "or (2) PN sacrifices a nonland permanent; " +
                "or (3) PN discards a card."
            );
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            if (event.isMode(1)) {
                game.doAction(new ChangeLifeAction(event.getPlayer(), -3));
            } else if (event.isMode(2)) {
            final MagicEvent sac = new MagicSacrificePermanentEvent(
                event.getPlayer(),
                choice
            );
            if (sac.isSatisfied()) {
                game.addEvent(sac);
            } else {
                game.doAction(new ChangeLifeAction(event.getPlayer(), -3));
            }

            } else if (event.isMode(3)) {
            final MagicEvent discard = new MagicDiscardEvent(event.getPlayer())
            if (discard.isSatisfied()) {
                game.addEvent(discard);
            } else {
                game.doAction(new ChangeLifeAction(event.getPlayer(), -3));
                }  
            }
        }
    }
]

**Comment by bilbo2** [comment]
Already implemented in e5ebff99b12cbecd30c762222529f126d8e402a3

**Comment by melvinzhang** [comment]
Thanks for the update. Closing this.
