### ISSUE TITLE
Prying Questions (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1452]
name=Prying Questions
image=https://magiccards.info/scans/en/emn/101.jpg
image_updated=2016-09-05
value=2.500
rarity=U
type=Sorcery
cost={2}{B}
timing=main
oracle=Target opponent loses 3 life and puts a card from his or her hand on top of his or her library.
requires_groovy_code

[
    new MagicSpellCardEvent() {
        @Override
        public MagicEvent getEvent(final MagicCardOnStack cardOnStack,final MagicPayedCost payedCost) {
            return new MagicEvent(
                cardOnStack,
                TARGET_OPPONENT,
                this,
                "Target opponent\$ loses 3 life and puts a card from his or her hand on top of his or her library."
            );
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            event.processTargetPlayer(game, {
                game.doAction(new ChangeLifeAction(it, -3));
                game.addEvent(new MagicReturnCardEvent(event.getSource(), it));
            });
        }
    }
]

**Comment by melvinzhang** [comment]
Merged.
