### ISSUE TITLE
Sekki, Seasons' Guide (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1455]
name=Sekki, Seasons' Guide
image=https://magiccards.info/scans/en/sok/148.jpg
value=3.896
rarity=R
type=Legendary,Creature
subtype=Spirit
cost={5}{G}{G}{G}
pt=0/0
ability=SN enters the battlefield with eight +1/+1 counters on it.;\
        Sacrifice eight Spirits: Return SN from your graveyard to the battlefield.
timing=main
oracle=Sekki, Seasons' Guide enters the battlefield with eight +1/+1 counters on it.\nIf damage would be dealt to Sekki, prevent that damage, remove that many +1/+1 counters from Sekki, and create that many 1/1 colorless Spirit creature tokens.\nSacrifice eight Spirits: Return Sekki from your graveyard to the battlefield.
requires_groovy_code

[
    new IfDamageWouldBeDealtTrigger(MagicTrigger.REPLACE_DAMAGE) {
        @Override
        public MagicEvent executeTrigger(final MagicGame game,final MagicPermanent permanent,final MagicDamage damage) {
            final int amount = (damage.getTarget() == permanent) ? damage.prevent() : 0;
            return amount > 0 ?
                new MagicEvent(
                    permanent,
                    amount,
                    this,
                    "PN creates RN 1/1 colorless Spirit creature tokens."
                ):
                MagicEvent.NONE;
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            final int amount = event.getRefInt();
                game.doAction(new ChangeCountersAction(event.getPermanent(),MagicCounterType.PlusOne,-amount));
                game.doAction(new PlayTokensAction(event.getPlayer(), CardDefinitions.getToken("1/1 colorless Spirit creature token"),amount));
        }
    }
]

**Comment by melvinzhang** [comment]
Merged
