### ISSUE TITLE
Servant of the Scale (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1456]
name=Servant of the Scale
image=https://magiccards.info/scans/en/dtk/203.jpg
value=2.500
rarity=C
type=Creature
subtype=Human,Soldier
cost={G}
pt=0/0
ability=SN enters the battlefield with a +1/+1 counter on it.
timing=main
oracle=Servant of the Scale enters the battlefield with a +1/+1 counter on it.\nWhen Servant of the Scale dies, put X +1/+1 counters on target creature you control, where X is the number of +1/+1 counters on Servant of the Scale.
requires_groovy_code

def choice = new MagicTargetChoice("target creature you control");

[
    new ThisDiesTrigger() {
        @Override
        public MagicEvent executeTrigger(final MagicGame game, final MagicPermanent permanent, final MagicPermanent died) {
            return new MagicEvent(
                permanent,
                choice,
                this,
                "PN puts X +1/+1 counters on target creature he or she controls\$, "+
                "where X is the number of +1/+1 counters on SN."
            );
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            event.processTargetPermanent(game, {
                final int X = event.getPermanent().getCounters(MagicCounterType.PlusOne);
                game.logAppendX(event.getPlayer(),X);
                game.doAction(new ChangeCountersAction(it,MagicCounterType.PlusOne,X));
            });
        }
    }
]

**Comment by melvinzhang** [comment]
Merged
