### ISSUE TITLE
Soulstinger (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1457]
name=Soulstinger
image=https://magiccards.info/scans/en/akh/108.jpg
value=2.500
rarity=C
type=Creature
subtype=Scorpion,Demon
cost={3}{B}
pt=4/5
ability=When SN enters the battlefield, put two -1/-1 counters on target creature you control.
timing=main
oracle=When Soulstinger enters the battlefield, put two -1/-1 counters on target creature you control.\nWhen Soulstinger dies, you may put a -1/-1 counter on target creature for each -1/-1 counter on Soulstinger.
requires_groovy_code

def choice = Negative("target creature");

[
    new ThisDiesTrigger() {
        @Override
        public MagicEvent executeTrigger(final MagicGame game, final MagicPermanent permanent, final MagicPermanent died) {
            return new MagicEvent(
                permanent,
                new MagicMayChoice(choice),                
                this,
                "PN may\$ puts X -1/-1 counters on target creature\$, "+
                "where X is the number of -1/-1 counters on SN."
            );
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            if (event.isYes()) {
            event.processTargetPermanent(game, {
                final int X = event.getPermanent().getCounters(MagicCounterType.MinusOne);
                game.logAppendX(event.getPlayer(),X);
                game.doAction(new ChangeCountersAction(it,MagicCounterType.MinusOne,X));
            });
            }
        }
    }
]

**Comment by Fulmene** [comment]
Added in #1415

**Comment by kelsioboy** [comment]
This card has already been released in version 1.91 and so I'm closing.
