### ISSUE TITLE
Tyrannize (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1458]
name=Tyrannize
image=https://magiccards.info/scans/en/shm/201.jpg
value=3.074
rarity=R
type=Sorcery
cost={3}{B/R}{B/R}
timing=main
oracle=Target player discards his or her hand unless he or she pays 7 life.
requires_groovy_code

def action = {
    final MagicGame game, final MagicEvent event ->
    if (event.isYes()) {
        game.doAction(new ChangeLifeAction(event.getPlayer(),-7));
    } else {
        game.addEvent(new MagicDiscardEvent(event.getSource(),event.getPlayer(),event.getPlayer().getHandSize()));
    }
}

[
    new MagicSpellCardEvent() {
        @Override
        public MagicEvent getEvent(final MagicCardOnStack cardOnStack,final MagicPayedCost payedCost) {
            return new MagicEvent(
                cardOnStack,
                NEG_TARGET_PLAYER,
                this,
                "Target player\$ discards his or her hand unless he or she pays 7 life."
            );
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            event.processTargetPlayer(game, {
                game.addEvent(new MagicEvent(
                    event.getSource(),
                    it,
                    new MagicMayChoice("pays 7 life?"),
                    action,
                    "\$ pay 7 life."
                ));
            })
        }
    }
]

**Comment by melvinzhang** [comment]
Merged
