### ISSUE TITLE
Vindictive Lich (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1460]
name=Vindictive Lich
image=https://magiccards.info/scans/en/c17/21.jpg
image_updated=2017-10-03
value=2.500
rarity=R
type=Creature
subtype=Zombie,Wizard
cost={3}{B}
pt=4/1
ability=When SN dies, choose one — (1) Target opponent sacrifices a creature. (2) Target opponent discards two cards. (3) Target opponent loses 5 life.
timing=main
oracle=When Vindictive Lich dies, choose one or more. Each mode must target a different player.\n• Target opponent sacrifices a creature.\n• Target opponent discards two cards.\n• Target opponent loses 5 life.

**Comment by kelsioboy** [comment]
When "Vindictive Lich" dies, choose one or more. In this case a choice for each different opponent. But as Magarena only has one opponent, then I believe that the mode of choice may be the simple one.

**Comment by melvinzhang** [comment]
Merged
