### ISSUE TITLE
Woebringer Demon (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1461]
name=Woebringer Demon
image=https://magiccards.info/scans/en/rav/113.jpg
value=3.344
rarity=R
type=Creature
subtype=Demon
cost={3}{B}{B}
pt=4/4
ability=Flying
timing=main
requires_groovy_code
oracle=Flying\nAt the beginning of each player's upkeep, that player sacrifices a creature. If the player can't, sacrifice Woebringer Demon.

[
    new AtUpkeepTrigger() {
        @Override
        public MagicEvent executeTrigger(final MagicGame game,final MagicPermanent permanent,final MagicPlayer upkeepPlayer) {
            return new MagicEvent(
                permanent,
                permanent.getController(),
                upkeepPlayer,
                this,
                "RN sacrifices a creature. " + 
                "If RN can't, sacrifice SN."
            );
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            final MagicEvent cost = new MagicSacrificePermanentEvent(
                event.getSource(),
                event.getRefPlayer(),
                MagicTargetChoice.A_CREATURE_YOU_CONTROL
            );
            if (cost.isSatisfied()) {
                game.addEvent(cost);
            } else {
                game.doAction(new SacrificeAction(event.getPermanent()));
            }
        }
    }
]

**Comment by melvinzhang** [comment]
Merged
