### ISSUE TITLE
Death's Shadow shouldn't get +X/+X if player's life total is negative

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#1462]
Anon submitted via gitreports.

Death's Shadow shouldn't get +X/+X if player's life total is negative. See ruling at http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=425889 . Example: use Platinum Angel to prevent from losing the game, or have opponent control Abyssal Persecutor.

**Comment by Fulmene** [comment]
The underlying rule change is this one: https://magic.wizards.com/en/articles/archive/play-design/hour-devastation-comprehensive-rules-changes-2017-07-14 (107.1b)

Basically, +X and -X for power/toughness treats X as zero if it is negative. I think it's better to just make the change in `MagicPowerToughness` class to comply with this ruling. Your thoughts?

For reference, [comprehensive rules](http://media.wizards.com/2018/downloads/MagicCompRules%2020180119.txt)

> 107.1b
> [...]
> If a calculation that would determine the result of an effect yields a negative number, zero is used instead, unless that effect sets a player’s life total to a specific value, doubles a player’s life total, or sets a creature’s power or toughness to a specific value.

(previously it also had "modifies power or toughness" in the exceptions)

**Comment by melvinzhang** [comment]
Thanks for looking into this. What would we need to change in `MagicPowerToughness`?

For reference, Death's Shadow ability is handled by the rule `LordPumpX` in `MagicAbility` which constructs a `MagicStatic` via `genPTStatic`.

**Comment by Fulmene** [comment]
I was thinking that `MagicPowerToughness.add` should check for negative number. However, upon further thought, we would need a separate `subtract` method, and it would complicate `LordPumpX` and other power/toughness changes like `ChangeTurnPTAction`.

Although, as far as I can tell, numbers that can be negative is Magic are only life total, power, and toughness. These are already covered in regular script, so maybe we can get away with `MagicAmountParser.getX` returning positive value by default, or just add `MagicAmountParser.getPositiveX` just like `MagicPowerToughness.getPositive{Power,Toughness}`.

I am thinking in terms of groovy script as well. If a +X/+X effect is a part of an effect that needs groovy, doing manual checks at each one will be fragile, as it will break upon further rule changes.

**Comment by melvinzhang** [comment]
Hmm, `MagicAmountParser.getX` currently returns 1 for 'X' and -1 for '-X' so that it can be multiplied with the value of X returned from `MagicAmount.getAmount`.

Seems like it should be the value of X that we need to be concerned with the one returned by `MagicAmout.getAmount`. `getX` should probably be renamed to `getXSign` to indicate it returns only the sign (positive/negative) and not the value of X.

**Comment by Fulmene** [comment]
I see. I'm thinking whether to add `getPositiveAmount` or make `getAmount` return positive number by default (by editing `MagicAmountFactory`) then add `getNegativeableAmount` (?).

So, todo list:
- Rename `MagicAmountParser.getX` to `getXSign`
- Create a way to get positive amount

**Comment by melvinzhang** [comment]
Not a good idea to change the meaning of an existing method and also not intuitive that getAmount is only for positive amounts as there are cases where the negative value can be used. Better to add a new method, this pattern would match how `MagicPowerToughness` does it as well.

**Comment by melvinzhang** [comment]
Fixed in #1475
