### ISSUE TITLE
Liberating Combustion (BUG)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1466]
"Liberating Combustion" not returning Chandra, Pyrogenius from the cemetery to the hand.

**Comment by Fulmene** [comment]
@melvinzhang This bug is because `MagicSearchToLocationEvent` is only applicable to search from library. Is it safe if I change it to be search from anywhere instead?

**Comment by melvinzhang** [comment]
@Fulmene Should be ok. How would the "If player search his or her library this way, shuffle it" be implemented?
