### ISSUE TITLE
Hostility (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1467]
name=Hostility
image=https://magiccards.info/scans/en/lw/176.jpg
image_updated=2016-02-29
value=2.500
rarity=R
type=Creature
subtype=Elemental,Incarnation
cost={3}{R}{R}{R}
pt=6/6
ability=Haste;\
        When SN is put into a graveyard from anywhere, shuffle it into its owner's library.
timing=fmain
oracle=Haste\nIf a spell you control would deal damage to an opponent, prevent that damage. Create a 3/1 red Elemental Shaman creature token with haste for each 1 damage prevented this way.\nWhen Hostility is put into a graveyard from anywhere, shuffle it into its owner's library.
requires_groovy_code

[
    new IfDamageWouldBeDealtTrigger(MagicTrigger.REPLACE_DAMAGE) {
        @Override
        public MagicEvent executeTrigger(final MagicGame game, final MagicPermanent permanent, final MagicDamage damage) {
            int amount = (damage.getSource().isSpell() &&
                    permanent.isFriend(damage.getSource()) &&
                    permanent.isOpponent(damage.getTarget())) ? damage.prevent() : 0;
            return amount > 0 ?
                new MagicEvent(
                    permanent,
                    amount,
                    this,
                    "Prevent RN damage and PN creates RN 3/1 red Elemental Shaman creature token with haste."
                ):
                MagicEvent.NONE;
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            game.doAction(new PlayTokensAction(event.getPlayer(), CardDefinitions.getToken("3/1 red Elemental Shaman creature token with haste"), event.getRefInt()));
        }
    }
]

**Comment by kelsioboy** [comment]
Invented Token for this card:
Used a copy of the image of 3/1 red Elemental Shaman creature token (Normal).
Name used for the token:
3_1_red_Elemental_Shaman_creature_token_with_haste.txt

name=3/1 red Elemental Shaman creature token with haste
image=https://magiccards.info/extras/token/duel-decks-jace-vs-chandra/elemental-shaman-haste.jpg
value=3
token=Elemental Shaman
type=Creature
subtype=Elemental,Shaman
color=R
pt=3/1
ability=haste
oracle=Haste

**Comment by kelsioboy** [comment]
Invented Token for this card:
Used a copy of the image of 3/1 red Elemental Shaman creature token (Normal).
Name used for the token:
3_1_red_Elemental_Shaman_creature_token_with_haste.txt

**Comment by melvinzhang** [comment]
Merged
