### ISSUE TITLE
Huatli, Radiant Champion (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1468]
name=Huatli, Radiant Champion
image=https://magiccards.info/scans/en/rix/159.jpg
value=2.500
rarity=M
type=Legendary,Planeswalker
subtype=Huatli
cost={2}{G}{W}
loyalty=3
ability=−1: Target creature gets +X/+X until end of turn, where X is the number of creatures you control.;\
        −8: You get an emblem with "Whenever a creature enters the battlefield under your control, you may draw a card."
timing=main
oracle=+1: Put a loyalty counter on Huatli, Radiant Champion for each creature you control.\n−1: Target creature gets +X/+X until end of turn, where X is the number of creatures you control.\n−8: You get an emblem with "Whenever a creature enters the battlefield under your control, you may draw a card."
requires_groovy_code

[
    new MagicPlaneswalkerActivation(1) {
        @Override
        public MagicEvent getPermanentEvent(final MagicPermanent source,final MagicPayedCost payedCost) {
            return new MagicEvent(
                source,
                this,
                "Put a loyalty counter on SN for each creature PN controls."
            );
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            final int size = event.getPlayer().getController().getNrOfPermanents(MagicType.Creature);
            game.doAction(new ChangeCountersAction(event.getPermanent(),MagicCounterType.Loyalty,size));
        }
    }
]

**Comment by melvinzhang** [comment]
Merged
