### ISSUE TITLE
Puresteel Paladin is messing with me

### ISSUE THREAD

**Issue by dtgunslinger** [magarena/magarena#147]
AI has Puresteel Paladin, two equipments and an artifact land in addition to two other creatures in play.  The Paladin just keeps moving the equipment around and around.  :)

**Comment by ShawnieBoy** [comment]
Hehe, yes, I've encountered something similar with 0-cost equipment too - becomes a fussy dresser.

@melvinzhang will need to have a look

**Comment by ShawnieBoy** [comment]
Which AI are you using and which setting?

**Comment by dtgunslinger** [comment]
Las Vegas lvl 8. "fussy dresser"  lol, classic!

**Comment by melvinzhang** [comment]
Thanks for the report! There was code to limit equip activation by the AI to at most twice per turn, turns out there is a bug in it which did not increment the count when an equip activation resolves. Fixed in https://github.com/magarena/magarena/commit/2d044fc314d510fed31a04ae7a82b698cfaa7926
