### ISSUE TITLE
Elemental Mastery (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1482]
name=Elemental Mastery
image=https://magiccards.info/scans/en/shm/90.jpg
value=3.724
rarity=R
type=Enchantment
subtype=Aura
cost={3}{R}
ability=Enchant creature;\
        Enchanted creature has "{T}: Create X 1/1 red Elemental creature tokens with haste, exile them at the beginning of the next end step, where X is this creature's power."
timing=aura
enchant=power,pos creature
oracle=Enchant creature\nEnchanted creature has "{T}: Create X 1/1 red Elemental creature tokens with haste, where X is this creature's power. Exile them at the beginning of the next end step."

**Comment by melvinzhang** [comment]
Merged.
