### ISSUE TITLE
Nazahn, Revered Bladesmith (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1487]
name=Nazahn, Revered Bladesmith
image=https://magiccards.info/scans/en/c17/44.jpg
image_updated=2017-10-03
value=2.500
rarity=M
type=Legendary,Creature
subtype=Cat,Artificer
cost={4}{G}{W}
pt=5/4
ability=Whenever an equipped creature you control attacks, you may tap target creature defending player controls.
timing=main
oracle=When Nazahn, Revered Bladesmith enters the battlefield, search your library for an Equipment card and reveal it. If you reveal a card named Hammer of Nazahn this way, put it onto the battlefield. Otherwise, put that card into your hand. Then shuffle your library.\nWhenever an equipped creature you control attacks, you may tap target creature defending player controls.
requires_groovy_code

def choice = new MagicTargetChoice("an Equipment card from your library");

[
    new EntersBattlefieldTrigger() {
        @Override
        public MagicEvent executeTrigger(final MagicGame game,final MagicPermanent permanent, final MagicPayedCost payedCost) {
            return new MagicEvent(
                permanent,
                choice,
                this,
                "PN searches his or her library for an Equipment card and reveal it. "+
                "If PN reveal a card named Hammer of Nazahn this way, put it onto the battlefield. "+
                "Otherwise, put that card into PN's hand. Then shuffle his or her library."
            );
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            event.processTargetCard(game, {
                    game.doAction(new RevealAction(it));
                if (it.getName().equals("Hammer of Nazahn")) {
                    game.doAction(new ReturnCardAction(MagicLocationType.OwnersLibrary,it,event.getPlayer()));
                    } else {
                    game.doAction(new ShiftCardAction(it, MagicLocationType.OwnersLibrary, MagicLocationType.OwnersHand));
                } 
            });
        }    
    }
]

**Comment by melvinzhang** [comment]
Merged.
