### ISSUE TITLE
Hammer of Nazahn (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1488]
name=Hammer of Nazahn
image=https://magiccards.info/scans/en/c17/51.jpg
image_updated=2017-10-03
value=2.500
rarity=R
type=Legendary,Artifact
subtype=Equipment
cost={4}
ability=Equipped creature gets +2/+0 and has indestructible.;\
        Equip {4}
timing=equipment
oracle=Whenever Hammer of Nazahn or another Equipment enters the battlefield under your control, you may attach that Equipment to target creature you control.\nEquipped creature gets +2/+0 and has indestructible.\nEquip {4}
requires_groovy_code

[
    new OtherEntersBattlefieldTrigger() {
        @Override
        public MagicEvent executeTrigger(final MagicGame game,final MagicPermanent permanent,final MagicPermanent otherPermanent) {
            return otherPermanent.isEquipment() && otherPermanent.isFriend(permanent) ?
                new MagicEvent(
                    permanent,
                new MagicMayChoice(TARGET_CREATURE_YOU_CONTROL),
                    otherPermanent,
                    this,
                    "PN may\$ attach RN to target creature\$ PN controls"
                ):
                MagicEvent.NONE;
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            if (event.isYes()) {
                event.processTargetPermanent(game, {
                    game.doAction(new AttachAction(event.getRefPermanent(), it));
                });
            }
        }
    }
]

**Comment by melvinzhang** [comment]
Merged.
