### ISSUE TITLE
Goblin Festival (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1496]
name=Goblin Festival
image=https://magiccards.info/scans/en/ud/83.jpg
value=3.217
rarity=R
type=Enchantment
cost={1}{R}
timing=enchantment
oracle={2}: Goblin Festival deals 1 damage to target creature or player. Flip a coin. If you lose the flip, choose one of your opponents. That player gains control of Goblin Festival.
requires_groovy_code

def loseAct = {
    final MagicGame game, final MagicEvent event ->
    game.doAction(new GainControlAction(event.getPlayer().getOpponent(), event.getPermanent()));
}

[
    new MagicPermanentActivation(
        new MagicActivationHints(MagicTiming.Removal),
        "Damage"
    ) {

        @Override
        public Iterable<? extends MagicEvent> getCostEvent(final MagicPermanent source) {
            return [
                new MagicPayManaCostEvent(source, "{2}")
            ];
        }

        @Override
        public MagicEvent getPermanentEvent(final MagicPermanent source, final MagicPayedCost payedCost) {
            return new MagicEvent(
                source,
                NEG_TARGET_CREATURE_OR_PLAYER,
                new MagicDamageTargetPicker(1),
                this,
                "SN deals 1 damage to target creature or player\$. "+
                "Flip a coin. If PN loses the flip, an opponent gains control of SN."
            );
        }

        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            event.processTarget(game, {
                game.doAction(new DealDamageAction(event.getPermanent(), it, 1));
                game.addEvent(new MagicCoinFlipEvent(
                    event,
                    MagicEventAction.NONE,
                    loseAct
                ));
            });
        }
    }
]

**Comment by melvinzhang** [comment]
Merged.
