### ISSUE TITLE
Goblin Archaeologist (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1497]
[Goblin_Archaeologist.zip](https://github.com/magarena/magarena/files/1929259/Goblin_Archaeologist.zip)

**Comment by bilbo2** [comment]
As pasting groovy code in the issue breaks formatting and sometimes breaks even the code by mangling some characters - can you attach a zipfile for this card, like you do in newer new card requests?

Or, alternatively, attach a zipfile with all your cards you have written at once, I'll sort it out, playtest them and then create another merge request :)

**Comment by bilbo2** [comment]
It seems the original text of the issue can be retrieved via API, so perhaps zipping might not be necessary in the end:
https://api.github.com/repos/magarena/magarena/issues?labels=new+card

**Comment by melvinzhang** [comment]
Merged.
