### ISSUE TITLE
use of Collections.shuffle leads to IndexOutOfBoundsException in growTree

### ISSUE THREAD

**Issue by Fulmene** [magarena/magarena#1502]
https://circleci.com/gh/Fulmene/magarena/305

**Comment by melvinzhang** [comment]
This occurs when multiple simulations down the game tree results in different choices. The MCTS AI uses a cache to record the game tree from a previous round, if the current game and previous one differs this error occurs.  I noticed the card "Tezzeret, Master of Metal" uses Collections.shuffle and this can cause such problems. The Ajani card also uses Collections.shuffle.

The correct method is to use the shufle method in MagicCardList.

**Comment by melvinzhang** [comment]
Fixed by PR #1503
