### ISSUE TITLE
Casting from library could fail during MCTS simulation when hidden cards are rearranged

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#1506]
Alerted to this bug by the following crash report, where Sunbird's Invocation casts a card from library.

```
Turn : 18  Phase : FirstMain  Step : ActivePlayer  Player : MMABC  AI : monte carlo tree search  Score : 0
0] Player : MMABC  Life : 9  Delayed : Total=0
   - Hand : Pride Sovereign
   - Hand : Makeshift Munitions
   - Graveyard : Unbridled Growth
   - Graveyard : Implement of Combustion
   - Graveyard : Embraal Gear-Smasher
   - Graveyard : Fireforger's Puzzleknot
   - Graveyard : Pia Nalaar
   - Library : Kumena's Speaker
   - Library : Mountain
   - Library : Ravenous Intruder
   - Library : Rootbound Crag
   - Library : Forest
   - Library : Forest
   - Library : Fathom Fleet Firebrand
   - Permanent : Filigree Crawler  Power : 2  Toughness : 2  Damage : 0
   - Permanent : Mountain  Tapped
   - Permanent : Mountain  Tapped
   - Permanent : Mountain
   - Permanent : Mountain
   - Permanent : Mountain  Summoned
   - Permanent : Multiform Wonder  Power : 3  Toughness : 3  Damage : 0
   - Permanent : Rootbound Crag  Tapped
   - Permanent : Sunbird's Invocation
   - Permanent : Timber Gorge  Tapped
1] Player : MCTS  Life : 6  Delayed : Total=0
   - Hand : Chandra's Defeat
   - Hand : Snapping Sailback
   - Graveyard : Wily Bandar
   - Graveyard : Fling
   - Graveyard : Pursue Glory
   - Graveyard : Blossom Dryad
   - Graveyard : Fiery Cannonade
   - Library : Khenra Charioteer
   - Library : Mountain
   - Library : Foundry Inspector
   - Library : Greenwheel Liberator
   - Library : Mountain
   - Library : Mountain
   - Library : Resilient Khenra
   - Permanent : Consulate Turret  Tapped
   - Permanent : Forest
   - Permanent : Forest
   - Permanent : Forest
   - Permanent : Mountain
   - Permanent : Timber Gorge
   - Permanent : Timber Gorge
   - Permanent : Trueheart Twins  Power : 4  Toughness : 4  Damage : 0
Stack : 1
   - Name : Heart-Piercer Manticore  Player : MMABC
1. ExecuteFirstEventAction = 0
2. TapAction (Consulate Turret) = -5
3. AddEventAction (EVENT: Consulate Turret Play activated ability of <Consulate Turret~1000054>. ) = 0
4. ExecuteFirstEventAction = 0
5. PutItemOnStackAction (MagicAbilityOnStack,Consulate Turret) = -1
6. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
7. ExecuteFirstEventAction = 0
8. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
9. ExecuteFirstEventAction = 0
10. StackResolveAction = 0
11. ChangeCountersAction = 0
12. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
13. ExecuteFirstEventAction = 0
14. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
15. ExecuteFirstEventAction = 0
16. StackResolveAction = 0
17. AddEventAction (EVENT: Sunbird's Invocation MMABC may cast a card revealed this way with converted mana cost 4 or less$ without paying its mana cost. Put the rest on the bottom of MMABC's library in a random order. Choose up to 1 card.) = 0
18. ExecuteFirstEventAction = 0
19. CastCardAction (MMABC,Pride Sovereign) = 0
20. AddEventAction (EVENT: Pride Sovereign Pay {0}$. Choose how to pay the mana cost.) = 0
21. AddEventAction (EVENT: Pride Sovereign  ) = 0
22. ShiftCardAction = 0
23. RemoveCardAction (Forest) = 0
24. MoveCardAction (Forest,OwnersLibrary,BottomOfOwnersLibrary) = 0
25. ShiftCardAction = 0
26. RemoveCardAction (Forest) = 0
27. MoveCardAction (Forest,OwnersLibrary,BottomOfOwnersLibrary) = 0
28. ShiftCardAction = 0
29. RemoveCardAction (Gremlin Infestation) = 0
30. MoveCardAction (Gremlin Infestation,OwnersLibrary,BottomOfOwnersLibrary) = 0
31. ExecuteFirstEventAction = 0
32. PayDelayedCostAction = 0
33. ExecuteFirstEventAction = 0
34. RemoveCardAction (Pride Sovereign) = 0
Score = -6

Exception from controller.runGame: magic.exception.GameException: java.lang.RuntimeException: Card Pride Sovereign not found.
magic.exception.GameException: magic.exception.GameException: java.lang.RuntimeException: Card Pride Sovereign not found.
	at magic.model.MagicGame.doAction(MagicGame.java:565)
	at magic.model.MagicGame.executeNextEvent(MagicGame.java:869)
	at magic.model.MagicGame.advanceToNextEventWithChoice(MagicGame.java:819)
	at magic.ai.MCTSAI.runSimulation(MCTSAI.java:470)
	at magic.ai.MCTSAI.randomPlay(MCTSAI.java:443)
	at magic.ai.MCTSAI.access$000(MCTSAI.java:63)
	at magic.ai.MCTSAI$2.run(MCTSAI.java:185)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: magic.exception.GameException: java.lang.RuntimeException: Card Pride Sovereign not found.
	at magic.model.MagicGame.doAction(MagicGame.java:565)
	at magic.model.event.MagicPutCardOnStackEvent.lambda$static$0(MagicPutCardOnStackEvent.java:40)
	at magic.model.event.MagicEvent.executeEvent(MagicEvent.java:726)
	at magic.model.MagicGame.executeEvent(MagicGame.java:796)
	at magic.model.action.ExecuteFirstEventAction.doAction(ExecuteFirstEventAction.java:18)
	at magic.model.MagicGame.doAction(MagicGame.java:563)
	... 9 more
Caused by: java.lang.RuntimeException: Card Pride Sovereign not found.
	at magic.model.MagicCardList.removeCard(MagicCardList.java:107)
	at magic.model.action.RemoveCardAction.doAction(RemoveCardAction.java:34)
	at magic.model.MagicGame.doAction(MagicGame.java:563)
	... 14 more

```

**Comment by melvinzhang** [comment]
The crash occurs during the `CastCardAction.WithoutManaCost` part of the script when it tries to remove the card that the player chose to cast from the library.

**Comment by melvinzhang** [comment]
The strange thing about the stack trace is that if you see the game state, it shows the card "Pride Sovereign" is in MMABC's hand but not in its library (only top 7 cards are shown). That explains why the remove from library fails, but why would it be in the hand...

**Comment by melvinzhang** [comment]
Ok, I think I know why. During simulation, the MCTS AI has a step where it rearranges opponent's hidden cards (the ones in hand and library). This is because it should not be able to know exactly where those cards are.

In this case, during one of the simulation it happens to puts "Pride Sovereign" in the hand rather than in the library, causing the removal during casting to fail.

**Comment by Fulmene** [comment]
I think I can follow. So does this mean using `RevealAction` prevents the AI from rearranging the revealed card to the hand?

**Comment by Fulmene** [comment]
On another note, why does putting the card to hand (like Browse) not cause this bug?

**Comment by melvinzhang** [comment]
> Does this mean using RevealAction prevents the AI from rearranging the revealed card to the hand?
Using RevealAction is needed, so that the AI knows these cards are not hidden cards and it needs to keep these cards where they are.

However, currently there is also a bug in the card rearrangement in that it doesn't consider revealed cards in library, it will only consider revealed cards in hand. I will fix that in this issue.

>why does putting the card to hand (like Browse) not cause this bug?
As far as I can tell, it suffers the same problem, but it doesn't crash because ShiftCardAction does nothing if the card is not in the `from` location.

**Comment by melvinzhang** [comment]
> But the resulting simulation will be inaccurrate, right?

That's right, the resulting simulation would be incorrect.

> As far as I can tell, cards that put a card from your library to your hand without revealing are few, but they do exist (like Diabolic Tutor). How does the game handle them currently?

It doesn't do it correctly, you can see MagicSearchToLocationEvent.java It moves it from getLocation which always works, even if the card got assigned to hand during the hidden card rearrangement.

**Comment by melvinzhang** [comment]
Hmm, thinking about this again, actually it does work correctly. Cause the hidden cards rearrangement happens before the choice is made. So the choice will be made based on the rearranged library/hand. So it can resolve correctly.

The issue with the earlier cards is that they have two separate events which are related, the first which looks at the top N cards, the second event uses cards from the top N cards. So after the first event, there could be a hidden card rearrangement, and that rearrangement need to preserve the top N cards.

**Comment by melvinzhang** [comment]
In summary, if it all happens within one event, it will work ok. The hidden card rearrangement happens, then the choice is made and resolved.

When it happens in two events, some information about the library/hand needs to be preserved across the two. That's where it could fail. i.e. the top N cards in the first event may no longer be in the library in the second event.
