### ISSUE TITLE
Sanguine Bond + Exquisite Blood no longer causes an infinite loop

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#1514]
Submitted by anon via gitreports:

Sanguine Bond + Exquisite Blood no longer causes an infinite loop. Specifically, it looks like Exquisite Blood no longer triggers Sanguine Bond. Instead, some log messages about "no legal targets" flash briefly but don't stick around in the log. To test, have both Sanquine Bond and Exquisite Blood in play, then cast Chaplain's Blessing. Expected result: infinite loop where the opponent's life reaches 0 and results in a draw (by official rulings, an infinite loop can't produce a win because there's no way to stop it).

**Comment by bilbo2** [comment]
No, you are incorrect about the draw here ...
It is true that infinite combos that are out of players control (i.e.no "may" on any of the loop components) causes a draw.

But here at the moment when opponent reaches 0 (or less) life through repetition of this combo, he loses and leaves the game.

Then, there is no valid target for "target opponent loses that much life" ... which ends the loop, resulting in a win (as the opponent is dead at that moment) - the combo is not infinite.

Although if the opponent would have Platinum Angel for example, then there would be a truly infinite loop (with the opponent's life total going to minus infinity ... ) resulting in a draw.

**Comment by melvinzhang** [comment]
I checked the scenario described by OP and it works as expected, the opponent loses due to reaching 0 life. There is no draw as @bilbo2 mentioned because one player reached zero and the game is over due to state based actions.

**Comment by melvinzhang** [comment]
As a side note, in this game, there are NO draws (unlike in the paper game). It just cannot happen because we decided that every game leads to either a win or lose.
