### ISSUE TITLE
Ezuri, Claw of Progress (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1521]
[Ezuri__Claw_of_Progress.zip](https://github.com/magarena/magarena/files/1972228/Ezuri__Claw_of_Progress.zip)

**Comment by bilbo2** [comment]
```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/home/bilbo/magarena/release/Magarena/scripts/Ezuri__Claw_of_Progress.groovy: 21: [Static type checking] - Cannot find matching method magic.model.action.ChangeCountersAction#<init>(magic.model.MagicPermanent, magic.model.MagicCounterType, int). Please check if the declared type is right and if the method exists.
 @ line 21, column 31.
                   game.doAction(new ChangeCountersAction(it,MagicCounterType.PlusOne,X));
                                 ^

1 error

```
Does not work with current master

**Comment by bilbo2** [comment]
ChangeCountersAction now has extra first parameter - player, the signature changed from:

`public ChangeCountersAction(final MagicObject obj, final MagicCounterType counterType, final int amount)`

to:

`public ChangeCountersAction(final MagicPlayer player, final MagicObject obj, final MagicCounterType counterType, final int amount)`

**Comment by kelsioboy** [comment]
Updated for the new "ChangeCountersAction".

**Comment by melvinzhang** [comment]
Merged
