### ISSUE TITLE
Crash when casting card with Treasure Keeper and it also casts the wrong card

### ISSUE THREAD

**Issue by Fulmene** [magarena/magarena#1527]
[Crashed when casting Syndicate Trafficker](https://circleci.com/gh/Fulmene/magarena/510)

[Cast a Colossal Dreadmaw](https://circleci.com/gh/Fulmene/magarena/511) (a 6 CMC card)

["Cast" a Sunpetal Grove](https://circleci.com/gh/Fulmene/magarena/509) (a land card)

**Comment by melvinzhang** [comment]
Thanks for reporting these. I can see the crash from the log output. What do you mean by casts the wrong card? How can we replicate it?

**Comment by melvinzhang** [comment]
Ah, I see you mean it can cast "Sunpetal Grove" which it should not be able to. Please be mention that directly, we may not be familiar with the wording of cards mentioned, it is good to explain why a particular action is wrong.

**Comment by melvinzhang** [comment]
I see the bug, you need to reveal a card before you can check its type. The card is hidden when the AI performs its simulations as it is not suppose to know the library. See how release/Magarena/scripts/Mirko_Vosk__Mind_Drinker.groovy is done.

**Comment by Fulmene** [comment]
Ah Okay. Are other cards that reveal until certain condition like [Tezzeret, Master of Metal](https://github.com/magarena/magarena/blob/master/release/Magarena/scripts/Tezzeret__Master_of_Metal.groovy) and [Ajani, Valiant Protector](https://github.com/magarena/magarena/blob/master/release/Magarena/scripts/Ajani__Valiant_Protector.groovy) also affected?

**Comment by melvinzhang** [comment]
Yes, to be able to know the characteristics of a card in the library (that is supposed to be hidden). RevealAction is needed.

**Comment by Fulmene** [comment]
I see. So they just don't crash because they use `ShiftCardAction` instead of `CastCardAction`.

This is kinda off-topic but is there a reason `ShiftCardAction` just does nothing instead of crashing if the card to be shifted isn't in the "from location"? Is there a case where the card can be moved that isn't checked beforehand (by e.g. `event.processChosenCards`) ?

**Comment by melvinzhang** [comment]
This is a good question. I think it is related to effect that deals with its own card, for example, `When SN dies, return SN from the graveyard to its owner's hand.`. If SN is not in the gravyard when the effect resolves, it should just do nothing.

**Comment by Fulmene** [comment]
Another question. Mirko Vosk mills the cards revealed so the library size can be checked to stop before enough lands are revealed. What would I check for effects that send the cards to the bottom of library? Also what to do with "in random order" clause?

**Comment by melvinzhang** [comment]
> What would I check for effects that send the cards to the bottom of library?

I don't understand what you mean by "check for". Please give a specific example?

> Also what to do with "in random order" clause?

Then we cannot use ShiftCardAction. Internally ShiftCardAction is two actions, RemoveCardAction and MoveCardAction. To do in random, we have to use RemoveCardAction to remove the card and store it in a temporary MagicCardList. Then shuffle the list using the MagicCardList.shuffle method and put it into the final destination.

**Comment by Fulmene** [comment]
> I don't understand what you mean by "check for". Please give a specific example.

From Mirko Vosk:

```
while (landCards < amount && library.size() > 0) {
```

What I meant by "check for" is `library.size() > 0`, in the case where the library has less than four land cards, this check will be applied so that the event stops revealing any more cards indefinitely.

> use RemoveCardAction to remove the card and store it in a temporary MagicCardList.

Then I can check `library.size() > 0` like in Mirko Vosk. Thanks for the clarification.
