### ISSUE TITLE
Phantom Centaur loses counter when blocking a black creature

### ISSUE THREAD

**Issue by itandetnik** [magarena/magarena#153]
Computer attacks with a black creature. I block with Phantom Centaur.

Expected: all damage is prevented due to protection from black; +1/+1 counters remain intact.
Actual: Phantom Centaur loses one counter.

There's even a [ruling](http://gatherer.wizards.com/Pages/Card/Details.aspx?name=phantom+centaur) specifically addressing this case:

> If this card is going to take damage from a black source, you can choose to apply Protection from Black's damage prevention ability prior to applying this card's built-in ability. This means you don't have to remove a counter.

Nothing useful in the log:

```
LOG (C): Computer attacks with Drana, Kalastria Bloodchief.
LOG (P): Igor blocks with Phantom Centaur.
LOG (C): Drana, Kalastria Bloodchief is destroyed.
```

**Comment by ShawnieBoy** [comment]
I've been scratching my head over this one - both are prevent damage effects which are occurring together; however I can't separate, or at least slow down, the removal of counters to allow protection to occur first.

The only option I can see is for the 'prevent damage, remove a +1/+1 counter' effects is to set them as a damage replacement effect. Which doesn't quite feel right. Will look into it more.
