### ISSUE TITLE
Promoting Magarena on Facebook

### ISSUE THREAD

**Issue by anaufalm** [magarena/magarena#1532]
Wow, I've seen trailer of this game, and this is a really cool fantasy card game, very interesting I really like it. May I share this game? So that people (gamers) know more about this cool game. I will promote it on facebook possible. ;)

**Comment by melvinzhang** [comment]
Hi @anaufalm thanks for your interest in our project :) Feel free to post about it. Btw, where did you see this trailer?

**Comment by anaufalm** [comment]
You know I will run facebook ads to promote your game, am I allowed to do this?  I just ask permission from owner of this project. Cz I think this game is need to be promoted for more demands. :)

Ohh sorry, I mean gameplay not trailer. I've seen on youtube.

**Comment by melvinzhang** [comment]
Should be fine, please let us review a copy of the ad before it goes up on facebook.

**Comment by anaufalm** [comment]
Hi, this a link post that I want to promote, if there is something does'nt match or you have a good idea for that, feel free to comment. :)

https://facebook.com/goodnews.os/photos/376500082850923/

Btw I take the photo from your web, may I?
https://raw.githubusercontent.com/wiki/magarena/magarena/screenshots/theme_moon.jpg

**Comment by melvinzhang** [comment]
@anaufalm looks good though that particular screenshot is a bit old as we have updated the UI since then. Could you use https://raw.githubusercontent.com/wiki/magarena/magarena/screenshots/maincombat.jpg instead?

**Comment by anaufalm** [comment]
Yeah, sure. The ads are running now. :)

**Comment by melvinzhang** [comment]
Thanks for promoting this project on your page!

**Comment by anaufalm** [comment]
Ur welcome, glad to hear that :)
