### ISSUE TITLE
implement "saga" mechanic

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#1538]
As this saga and after your draw phase, put a lore counter on it. (tied to the Saga subtype)

Saga has triggered abilities that trigger based on the number of lore counters on it. When a lore counter is added, the triggered abilities trigger.

As a state based action, sacrifice the sage if a) it has 3+ lore counters on it AND b) there are no Chapter triggers that it is the source for on the stack (or waiting to be put on the stack)

**Comment by Fulmene** [comment]
I'm trying to implement chapter abilities in card scripts, but not sure where to put the parser for chapter indicator (the I, II, III in front of the effect). As sometimes different chapters have the same effect, we should also allow writing something like `I, II - <effect>`. Should I just add a new pattern to ARG?

**Comment by melvinzhang** [comment]
@Fulmene Sure, a regex for one or more chapters separated by comma and a method that returns the parsed chapters makes sense in ARG.
