### ISSUE TITLE
Graft and multiple creatures entering the battlefield

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#157]
If multiple creatures enter the battlefield at the same time, you can choose 'yes' for each trigger from one permanent with Graft to gain multiple +1/+1 counters.

Clarify - The permanent with Graft has one +1/+1 counter. Two creatures enter the battlefield at the same time, both can gain a +1/+1 counter.

**Comment by ShawnieBoy** [comment]
Fixed, however try the following:

Two Llanowar Reborn in play. 
Cast Ethereal Ambush.

Now try and get one +1/+1 counter on each creature :imp:

**Comment by lodici** [comment]
![screenshot00087](https://cloud.githubusercontent.com/assets/2443519/6994336/f2948876-db0d-11e4-8c1c-6d7710363684.png)

Not sure about amusing, but pretty confusing. Just from a UI POV - there is the log message ending ``...onto .``. The fact that if the stack can't show all items and you click "Yes" it starts on the bottom item which is "off screen" so there is no feedback that anything has happened. As for the mechanics...my head hurts! :confounded:

**Comment by ShawnieBoy** [comment]
It's a two-card storm of madness!

1. The log message ends with `onto .` as the face down cards are creatures with no name.
2. There's no way of telling which creature entering the battlefield has caused each of the triggers.
3. There's no way of telling which of the lands the triggers have originated from.
4. The prompt doesn't really show where the counter is coming from, or going to.

(I have a larger default screen size so I get all the triggers, but it took lots of undoing to get one counter on each, the triggers weren't in the order I was expecting.

Brain-ache :confounded:

**Comment by ShawnieBoy** [comment]
It's actually a good example of why choosing targets or options as triggers go on the stack instead of on resolution can be very confusing.

**Comment by lodici** [comment]
Well, good luck! If there is anything the UI can do to improve understanding of what is going on let me know.

**Comment by ShawnieBoy** [comment]
The original issue is fixed, other issues remain elsewhere
