### ISSUE TITLE
Why does the defending player choose damage assinging order?

### ISSUE THREAD

**Issue by WormFrizzer** [magarena/magarena#160]
509.2. Second, for each attacking creature that's become blocked, the active player announces that creature's damage assignment order, which consists of the creatures blocking it in an order of that player's choice. (During the combat damage step, an attacking creature can't assign combat damage to a creature that's blocking it unless each creature ahead of that blocking creature in its order is assigned lethal damage.) This turn-based action doesn't use the stack.

    Example: Vastwood Gorger is blocked by Llanowar Elves, Runeclaw Bear, and Serra Angel. Vastwood Gorger's controller announces the Vastwood Gorger's damage assignment order as Serra Angel, then Llanowar Elves, then Runeclaw Bear.

In Magarena the process is backwards.

**Comment by ShawnieBoy** [comment]
Many of the current [Game Rules](https://github.com/magarena/magarena/wiki/GameRules) for Magarena have been in place to aid the AI.

Combat is already a think-heavy situation for the AI, but I think this could do with a review. I'd like to see this changed, as currently there's a constant [Defensive Formation](http://magiccards.info/us/en/9.html) in play, or a kind of defender-banding.

@melvinzhang is the AI man.

**Comment by melvinzhang** [comment]
@ShawnieBoy Correct, it is to simplify combat from three decisions to two. The defender doesn't have to consider the all ways a particular defense can be altered up by the attacker.

@WormFrizzer Given that under the current simplified house rules, there are still a number of known weaknesses with AI combat decisions, it is unlikely we will attempt to move to the more complex combat rules.
