### ISSUE TITLE
Standardising groovy methods

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#165]
When developing new cards, previous similar cards are always useful references.

As many developmental changes have occurred through Magarena, some earlier groovy scripts are now using out-dated methods.

Although functionally fine, they can lead to different 'flavours' of coding via groovy.

I'll be going through the groovy files and updating older tropes and head towards a more standardised 'feel' to aid in legibility for new coders.

 - [X] MagicWhenSelfAttacksTrigger
 - ~~MagicWhenSelfBlocksTrigger~~
 - [X] MagicOtherPermanentTargetFilter -> .except()
 - ~~MagicWhenBlocksOrBecomesBlockedTrigger~~

**Comment by melvinzhang** [comment]
Good stuff. Suggestion: use "improve" or "refactor" instead of "fix" in the commit message. Typically "fix" is used when correcting bugs. It alerts me to bug fixes to include in the release notes.

**Comment by ShawnieBoy** [comment]
Gotcha - didn't think about that

**Comment by melvinzhang** [comment]
Was looking though all the MagicOther... changes, it looks rather verbose. Would something like
```
MagicTargetFilterFactory.HUMAN_CREATURE_YOU_CONTROL.except(event.getPermanent())
```
be preferable?

**Comment by ShawnieBoy** [comment]
That would be a whole lot neater

**Comment by melvinzhang** [comment]
Added except method in https://github.com/magarena/magarena/commit/77481f3f0bd743eea2e43d11145dded85736f8aa

Example using except method in
https://github.com/magarena/magarena/commit/157e293ed59816064d825d0c7bdde686c8cfeda9

**Comment by ShawnieBoy** [comment]
:+1:

**Comment by melvinzhang** [comment]
Reduce scope and considered done.
