### ISSUE TITLE
'Magic' prefix

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#166]
Just something that's starting to do my eyes in as I trawl through Actions, Triggers and Events...

Is the 'Magic' prefix on each file really necessary? It must be a hold-over from an early version and will probably be a fair bit of work to remove, but would aid readability.

Not a vast amount of benefits, but we kinda know what we're working on. :smile:

**Comment by lodici** [comment]
The ``Magic`` does seem redundant is some cases. For example, with ``magic.model.trigger`` classes you could lop off the ``Magic`` prefix and replace with the ``Trigger`` suffix, so ``MagicAtBeginOfCombatTrigger.java`` would become ``TriggerAtBeginOfCombat.java`` which if correct certainly reads better. Not so sure it works with the Event and Action classes though.

**Comment by melvinzhang** [comment]
I think either a common prefix or suffix is sufficient, no need for both. So MagicSacrificeAction can be SacrificeAction. The base class/interface should retain the Magic prefix, eg MagicAction, MagicEvent, so it is not just the suffix alone. The subclasses can drop the Magic prefix as they have a more specific description.

**Comment by ShawnieBoy** [comment]
:+1: 

Maybe some tentative re-factoring of some of the subclasses can be in order?

**Comment by melvinzhang** [comment]
Sure, if there is any concrete proposals we can decide on it in this issue.

**Comment by melvinzhang** [comment]
Let me formalize my earlier suggestion then, we can start with actions. Remove the Magic prefix from subclasses of MagicAction, namely:
src/magic/model/action/MagicRegenerateAction.java
src/magic/model/action/MagicSacrificeAction.java
src/magic/model/action/MagicManifestCardAction.java
src/magic/model/action/MagicPlayCardAction.java
src/magic/model/action/MagicLookAction.java
src/magic/model/action/MagicRemoveTriggerAction.java
src/magic/model/action/MagicPayDelayedCostsAction.java
src/magic/model/action/MagicPutItemOnStackAction.java
src/magic/model/action/MagicLoseAbilityAction.java
src/magic/model/action/MagicPlayTokenAction.java
src/magic/model/action/MagicBecomesCreatureAction.java
src/magic/model/action/MagicChangeCountersAction.java
src/magic/model/action/MagicDestroyAction.java
src/magic/model/action/MagicExileUntilEndOfTurnAction.java
src/magic/model/action/MagicAddTurnTriggerAction.java
src/magic/model/action/MagicReturnExiledAction.java
src/magic/model/action/MagicRemoveItemFromStackAction.java
src/magic/model/action/MagicGainAbilityAction.java
src/magic/model/action/MagicUntapAction.java
src/magic/model/action/MagicCounterItemOnStackAction.java
src/magic/model/action/MagicRemoveStaticAction.java
src/magic/model/action/MagicCopyCardOnStackAction.java
src/magic/model/action/MagicChangePlayerStateAction.java
src/magic/model/action/MagicTurnFaceDownAction.java
src/magic/model/action/MagicDiscardCardAction.java
src/magic/model/action/MagicSoulbondAction.java
src/magic/model/action/MagicChangeTargetAction.java
src/magic/model/action/MagicManifestAction.java
src/magic/model/action/MagicCleanupPermanentAction.java
src/magic/model/action/MagicCombatDamageAction.java
src/magic/model/action/MagicReanimateAction.java
src/magic/model/action/MagicTapAction.java
src/magic/model/action/MagicDeclareBlockersAction.java
src/magic/model/action/MagicExecuteFirstEventAction.java
src/magic/model/action/MagicBecomesAction.java
src/magic/model/action/MagicGainControlAction.java
src/magic/model/action/MagicCleanupTurnStaticsAction.java
src/magic/model/action/MagicPlayCardFromStackAction.java
src/magic/model/action/MagicAddTriggerAction.java
src/magic/model/action/MagicDealDamageAction.java
src/magic/model/action/MagicPlayTokensAction.java
src/magic/model/action/MagicRemoveCardAction.java
src/magic/model/action/MagicCastFreeCopyAction.java
src/magic/model/action/MagicMillLibraryAction.java
src/magic/model/action/MagicAttachAction.java
src/magic/model/action/MagicChangeLifeAction.java
src/magic/model/action/MagicLogMarkerAction.java
src/magic/model/action/MagicCipherAction.java
src/magic/model/action/MagicDeclareBlockerAction.java
src/magic/model/action/MagicRemoveAllDamageAction.java
src/magic/model/action/MagicAIRevealAction.java
src/magic/model/action/MagicLoseGameAction.java
src/magic/model/action/MagicShuffleIntoLibraryAction.java
src/magic/model/action/MagicChangeExtraTurnsAction.java
src/magic/model/action/MagicPlayAbilityAction.java
src/magic/model/action/MagicRemoveFromPlayAction.java
src/magic/model/action/MagicEnterAsCopyAction.java
src/magic/model/action/MagicCleanupTurnTriggersAction.java
src/magic/model/action/MagicTurnFaceUpAction.java
src/magic/model/action/MagicRemoveFromCombatAction.java
src/magic/model/action/MagicChangePoisonAction.java
src/magic/model/action/MagicScryComplAction.java
src/magic/model/action/MagicFlipAction.java
src/magic/model/action/MagicAddEventAction.java
src/magic/model/action/MagicReturnLinkedExileAction.java
src/magic/model/action/MagicShuffleLibraryAction.java
src/magic/model/action/MagicSetKickerAction.java
src/magic/model/action/MagicSetBlockerAction.java
src/magic/model/action/MagicPayDelayedCostAction.java
src/magic/model/action/MagicExileLinkAction.java
src/magic/model/action/MagicMarkerAction.java
src/magic/model/action/MagicChangeTurnPTAction.java
src/magic/model/action/MagicChangeControlAction.java
src/magic/model/action/MagicTransformAction.java
src/magic/model/action/MagicReclaimExiledCardAction.java
src/magic/model/action/MagicChangeStateAction.java
src/magic/model/action/MagicMoveCardAction.java
src/magic/model/action/MagicDeclareAttackersAction.java
src/magic/model/action/MagicAddFirstEventAction.java
src/magic/model/action/MagicDrawAction.java
src/magic/model/action/MagicRevealAction.java
src/magic/model/action/MagicStackResolveAction.java
src/magic/model/action/MagicPutStateTriggerOnStackAction.java
src/magic/model/action/MagicDetainAction.java
src/magic/model/action/MagicChangeCardDestinationAction.java
src/magic/model/action/MagicAddStaticAction.java
src/magic/model/action/MagicCleanupPlayerAction.java
src/magic/model/action/MagicDeclareAttackerAction.java
src/magic/model/action/MagicRemoveTriggersStaticsAction.java
src/magic/model/action/MagicScryAction.java
src/magic/model/action/MagicPreventDamageAction.java

The above will have the Magic prefix removed. So MagicScryAction.java becomes ScryAction.java and so on.

The classes in src/magic/model/action that are excluded are the base classes and interfaces, namely. These remain their original name
src/magic/model/action/MagicTargetAction.java
src/magic/model/action/MagicCardAction.java
src/magic/model/action/MagicAction.java
src/magic/model/action/MagicActionList.java
src/magic/model/action/MagicPermanentAction.java
src/magic/model/action/MagicCardOnStackAction.java
src/magic/model/action/MagicItemOnStackAction.java
src/magic/model/action/MagicPlayMod.java
src/magic/model/action/MagicPlayerAction.java

**Comment by ShawnieBoy** [comment]
Just a query - why would the last group have to keep the prefix - is there a naming clash elsewhere?

**Comment by melvinzhang** [comment]
This is following my original suggestion of only renaming concrete classes. It also lets us identify the abstract/interface classes

**Comment by ShawnieBoy** [comment]
I see - I'd be inclined to remove all Magic Prefixes - currently identifying abstract/interface classes is by looking at the java file. I'm not sure how often needing to know those references would occur.

**Comment by melvinzhang** [comment]
For one thing, we're not renaming the other models yet, so we still have MagicCardOnStack and MagicPermanent and so on. So the respective interfaces being MagicCardOnStackAction and MagicPermanentAction would be more consistent with the rest of the classes.

**Comment by ShawnieBoy** [comment]
For the time being, yes - but when all have been changed then there'd be no 'Magic' prefix anywhere

**Comment by melvinzhang** [comment]
Assuming all will be changed, that would be the case. We're only talking about Actions at the moment, unless you want to propose something else for discussion.

**Comment by ShawnieBoy** [comment]
I was referring to all files in my original question - 'Magic' is on nearly every file and doesn't really need to be there

**Comment by melvinzhang** [comment]
Sure, but my proposal is only for Actions. Are you saying it should be all or nothing? My thinking is do it in in stages.

**Comment by ShawnieBoy** [comment]
Certainly do it in stages - I see now that the second batch will have likely references elsewhere and so would be best to leave them till later

**Comment by melvinzhang** [comment]
I think we agree in principle we can remove the Magic prefix it in certain cases. I'm proposing specific actions we can take to more forward on this. If you disagree with my proposal, please proposal a different change and we can discuss it.

**Comment by ShawnieBoy** [comment]
No, I just misunderstood - I thought you meant that they wouldn't be changed, as in ever. This is certainly a good move, and a good place to start.

**Comment by melvinzhang** [comment]
Right, I mean start with *Action classes. We can certainly propose more renaming later on. 

@lodici Proposal: start by removing Magic prefix from concrete subclasses of MagicAction. Yay or Nay?

**Comment by lodici** [comment]
> Proposal: start by removing Magic prefix from concrete subclasses of MagicAction, eg. MagicScryAction.java -> ScryAction.java. Yay or Nay?

Yay!

**Comment by melvinzhang** [comment]
Great. Then we're all in on the proposed renaming, I'll open up an issue for it and close this issue. The actual renaming work is https://github.com/magarena/magarena/issues/168
