### ISSUE TITLE
Exception on Generate Deck in Duel Decks screen. 

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#167]
![crash](https://cloud.githubusercontent.com/assets/2443519/7006873/7da83b00-dc7c-11e4-8627-1b917e8db891.png)
Replicated in 1.60. Start a new duel. Select a pre-built deck (not random). Click on the Generate Deck button...:boom:

**Comment by melvinzhang** [comment]
Perhaps we should remove the "generate deck" button for pre-built decks.

**Comment by lodici** [comment]
What I was planning to do is show
![screenshot00109](https://cloud.githubusercontent.com/assets/2443519/7034303/890c5e5c-dd78-11e4-940a-137fbbb61cc9.png)
now that it can restore deck selection state (#172). This will not only make it much clearer what "Generate Deck" is actually doing but will let you change the underlying generator for greater flexibility.

**Comment by melvinzhang** [comment]
To be clear, do you mean on prebuilt decks, the "Generate Deck" will show the "deck selection dialog" but on randomly generate decks it will generate a new deck directly? A different label may be clearer, say "Select Deck" instead of "Generate Deck". And we leave "Generate Deck" to mean generate a new deck from the current generator.

**Comment by lodici** [comment]
Generate Deck will open the dialog. In this incarnation, "Save" will be renamed to "Apply" (or "Generate") and "Cancel" to "Close". The heading, "Choose New Deck" or something. On clicking "Apply", the currently displayed deck will be updated based on whatever is selected in the dialog but the dialog will remain open so you will not have to keep opening and closing it to generate a new deck. Even if you do close it, it will open again on whatever the last selected deck type and name was.

**Comment by melvinzhang** [comment]
How would it work if I'm on a randomly generated deck and I want to change to a different deck generator? Would clicking the "Generate Deck" button generate the deck according to the current generator or open up the "Select Deck" dialog?

**Comment by lodici** [comment]
The Generate Deck button would open the dialog but with it set to the random generator you originally selected. Then you can click "Apply"/"Generate" as many times as you like to refresh the deck displayed in the screen behind the dialog. Alternatively, you can change the random generator or select a prebuilt deck - basically the same the thing you can do now on the NewDuelSettings screen but on the DuelDecksScreen instead and with immediate feedback.

**Comment by melvinzhang** [comment]
Ah, now I see the reason that it should stay open while you want to modify your decks. Now you can also change the deck generator dynamically. Nice.
