### ISSUE TITLE
remove Magic prefix from concrete subclasses of MagicAction

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#168]
Remove the Magic prefix from files in src/magic/model/action that are concrete subclass of MagicAction. i.e. all files except for the following which are not subclass of MagicAction

src/magic/model/action/MagicTargetAction.java
src/magic/model/action/MagicCardAction.java
src/magic/model/action/MagicAction.java
src/magic/model/action/MagicActionList.java
src/magic/model/action/MagicPermanentAction.java
src/magic/model/action/MagicCardOnStackAction.java
src/magic/model/action/MagicItemOnStackAction.java
src/magic/model/action/MagicPlayMod.java
src/magic/model/action/MagicPlayerAction.java

**Comment by ShawnieBoy** [comment]
Done - quite an insightful process if I'm honest. Raised quite a few issues/question/opportunities

**Comment by ShawnieBoy** [comment]
Where next?

**Comment by melvinzhang** [comment]
The same as before, make a proposal and have a discussion on it, then proceed when there is consensus.

**Comment by lodici** [comment]
My tuppence - I think you can remove the ``Magic`` prefix from all the classes in the above list except for ``MagicAction`` and possibly ``MagicActionList``. In naming a class the main thing is to make sure it has a self-explanatory, well defined name and cannot be confused or clash with another class that might exist in the java core libraries or a third-party library. Obviously packages help to qualify a class but I still think it is useful to go for distinct class names.

**Comment by ShawnieBoy** [comment]
I agree with @lodici for finishing off the above list - I think they were skipped due to the amount of references involved (?).
