### ISSUE TITLE
Alesha, Who Smiles at Death, Does not remove card put into play from gy

### ISSUE THREAD

**Issue by Muppet1** [magarena/magarena#171]

**Comment by PalladiaMors** [comment]
This was my fault, I rushed this card trying to get some Fate Reforged cards implemented before the release. I've submitted an attempted fix through github. Don't worry, I don't plan on creating more problems for a while.

**Comment by melvinzhang** [comment]
@PalladiaMors You can put the target choice after the mana cost, MagicMayChoice(mana cost choice, target choice).

**Comment by ShawnieBoy** [comment]
Don't beat yourself up over this - A minor setback is all :grinning: 

A matter of having both choices together (May pay mana, and target choice) and using the Reanimate action like you identified.

I appreciate the work you've put into this - You're already tackling (and successfully tackled) some quite technical cards, quite a long way from "I don't know the first thing about coding"

**Comment by ShawnieBoy** [comment]
Damn @melvinzhang Give me a chance to inhale :stuck_out_tongue:

**Comment by melvinzhang** [comment]
@PalladiaMors This is bug and a relatively minor one at that. As Rosewater wrote and I firmly believe in, "mistakes are a crucial part of the creative process", it means you are pushing the boundaries of what you're capable of. 

When you submitted the planeswalker card, it truly made my day to see someone who has grown in their understanding of card scripting. I've learnt a lot too in the process, how to make card scripting simpler and more intuitive, thanks to your feedback.

MagicPutOntoBattlefieldEvent is from hand to battlefield, the name is rather vague. Will think of a better one, say MagicPutOntoBattlefieldFromHandEvent. Perhaps we can make it more general so it would work from other locations as well.

**Comment by PalladiaMors** [comment]
Thanks guys. I guess I have some work to do on my nerves as well! This has two aspects for me. One is trying to help with adding cards to a great game like Magarena, and hopefully bringing some new players in the process. The other thing is that I kinda see card coding as a "puzzle" of sorts. When I can't solve one, I start getting anxious and maybe getting a little crazy as well, lol. Anyway, thanks for the help here, this one raised my blood pressure a bit (without much reason, I guess).

**Comment by ShawnieBoy** [comment]
@melvinzhang I'd be inclined for movement events to be in a From`<location>`To`<Location>`Event format.

So instead of `MagicPutOntoBattlefieldEvent`, it would be simply `FromHandToBattlefieldEvent`

Or even a more general 'MoveCardEvent' with a constructor containing the from and to. A partner to 'PlayCardEvent'

**Comment by melvinzhang** [comment]
@ShawnieBoy thanks for the suggestion, from-to format is much clearer. I think the current one can support both hand and graveyard, but there is duplication of information in that the choice has to match the location. Technically it is possible to determine the from location from the card choice itself.

**Comment by melvinzhang** [comment]
Since the card is checked to be in the legal location by processTargetCard, I think we can remove it from its current location instead of hardcoding the location as OwnersHand, i.e. replace OwnersHand with card.getLocation().

**Comment by ShawnieBoy** [comment]
Excellent, was one of the really annoying things about card movement - unexpected card duplication + having to state where a card is when it's already stated.
