### ISSUE TITLE
Ajani, Caller of the Pride ability optional

### ISSUE THREAD

**Issue by tlorance** [magarena/magarena#173]
The planeswalker card "Ajani, Caller of the Pride" has a +1 loyalty ability "Put a +1/+1 counter on up to one target creature". This is being interpreted by Magarena as an optional ("may") ability. Should it be, or should there be a minimum target count of 1?

**Comment by ShawnieBoy** [comment]
The key phrase is "up to" - The ability can be activated even if there are no creatures on the battlefield, or even get the loyalty counter without having to add a counter to a creature. The simple way of allowing this target/no target activation option is with the 'may' choice.

It's a nicely worded ability, so you can always add counters to Ajani regardless of the situtation (As most +1 abilities usually are) :grinning:
