### ISSUE TITLE
Eidolons

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#175]
Been looking at newly parsable cards - Aurora Eidolon parses and individually everything looks sound:

`Whenever you cast a multicolored spell, you may return SN from your graveyard to your hand.`

It's failing to trigger. Also a strange log reference with it's first ability as well:

`Prevent the next 3 damage that would be dealt to target creature or player this turn.`

Enters the log as:

`Prevent the next 3 damage -1 be dealt to target creature or player Aurora Eidolon.`

**Comment by melvinzhang** [comment]
Trigger from graveyard are not supported, only activated abilities for now. Good catch on the log problem though, over eager regex in MagicMessage replaceName.

**Comment by melvinzhang** [comment]
Tracking the log issue as #176
