### ISSUE TITLE
Place player decks in Player folder

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#193]
Just for a quality of life improvement for me :smile:

Can then gitIgnore that folder as unable to ignore the Decks folder for obvious reasons.

**Comment by ShawnieBoy** [comment]
Similarly, I've noticed my decks seem to be being placed in the /prebuilt folder

**Comment by lodici** [comment]
> Can then gitIgnore that folder as unable to ignore the Decks folder for obvious reasons.

You can update the global ``%HOMEPATH%\.gitignore`` to do this. In mine, I have ``release/Magarena/decks/*.dec`` to ignore my own decks.

**Comment by lodici** [comment]
> Similarly, I've noticed my decks seem to be being placed in the /prebuilt folder

It should prevent you from saving to the ``prebuilt`` folder...
![screenshot00112](https://cloud.githubusercontent.com/assets/2443519/7135824/75f434fa-e2a2-11e4-8af1-6a91d2b2a18a.png)

**Comment by ShawnieBoy** [comment]
I've just moved a bunch out of there - maybe I put them in there myself? Don't think so.

**Comment by ShawnieBoy** [comment]
Thanks for the custom gitignore filter - will be using that. Would make sense on the general gitignore
