### ISSUE TITLE
How to download version 1.44 and below?

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#194]
The [releases](https://github.com/magarena/magarena/releases) page lets you download older versions of Magarena up to 1.45 only. The [forum links](http://www.slightlymagic.net/forum/viewtopic.php?f=82&t=12749) are now out-of-date and missing.

**Comment by melvinzhang** [comment]
It is no longer possible to download them as I did not save a copy during the migration thinking no one would be interested. Shall we update the forum post and remove the broken links?

**Comment by lodici** [comment]
No biggy - I can always rollback the repository.

**Comment by lodici** [comment]
Was able to find 1.40 on [Wayback](http://web.archive.org/web/20140701104042/https://code.google.com/p/magarena/downloads/detail?name=Magarena-1.40.zip&can=2&q=).

**Comment by ShawnieBoy** [comment]
Wow, that's impressive. I wouldn't have thought the files themselves would still exist - maybe just the link.
