### ISSUE TITLE
March of the Machines effects Animated Artifacts

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#202]
continuing from #16 

Current fix will override already animated artifacts with new power/toughness based on their casting cost.

To replicate in [TestMarch](https://github.com/magarena/magarena/blob/master/src/magic/test/TestMarch.java):
Animate [Chimeric Staff](http://magiccards.info/10e/en/313.html) as a 1/1 artifact creature.
Cast [March of the Machines](http://magiccards.info/arc/en/6.html)

Chimeric Staff should remain as a 1/1 until it's animate ability wears off.
March of the Machines looks at it's card definition as a non-creature artifact and applies it's effect.

**Comment by melvinzhang** [comment]
implemented rule http://wiki.magicjudges.org/en/w/CR:613.5
