### ISSUE TITLE
Triggers should go on stack after player has priority, currently triggers go on on stack immediately

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#209]
I'm not sure if it's something I've done with the ScryTriggers, but perform the following with TestScry.

(For each instance of scry, just put the card back/bottom - that's not the important part)

Play Temple of Silence -> Pay for Knowledge and Power targeting the AI's Flamespeaker Adept.
Let them both resolve to an empty stack.

Cast Spark Jolt targeting the Flamespeaker Adept. Let it resolve.

At this point, Knowledge and Power triggers due to the Scry action, and Flamespeaker Adept has lethal damage.

Only when Knowledge and Power resolves does the Adept die.

![2015-04-18_133645](https://cloud.githubusercontent.com/assets/2363180/7215443/fc6659de-e5cf-11e4-866a-aa57726ad96f.png)

I'm fairly sure the Flamespeaker should die before the scry action of Spark Jolt.

**Comment by melvinzhang** [comment]
That is because we don't implement rule 116.5 as written
```
Each time a player would get priority, the game first performs                                                                                                                         
all applicable state-based actions as a single event (see rule 704,                                                                                                                           
<93>State-Based Actions<94>), then repeats this process until no state-based                                                                                                                  
actions are performed. Then triggered abilities are put on the stack                                                                                                                          
(see rule 603, <93>Handling Triggered Abilities<94>). These steps repeat in                                                                                                                   
order until no further state-based actions are performed and no abilities                                                                                                                     
trigger. Then the player who would have received priority does so.
```

Triggers go on the stack first, then you get priority and state-based actions are checked.

**Comment by melvinzhang** [comment]
I think we should follow rule 116.5 and only put triggers on stack when you have priority. I'll look into it.

**Comment by ShawnieBoy** [comment]
I see - thought I made a mistake somewhere.

Cool, thanks
