### ISSUE TITLE
Multicolored colorless cards

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#213]
Something I've discovered while working on the CardBuilder - If a MagicCard has no casting cost and no defined color, it 'defaults' to having all colors and returning MagicColor.isMulti() true.

Had me scratching my head for a while.

**Comment by melvinzhang** [comment]
The default value of colorFlags is -1 to indicate not set. It is checked in the validate method of MagicCardDefinition. The colorFlag is set either by cost, by color property, or set to colorless if type is Land. If non of the above occur, the validate method will throw a runtime exception.

**Comment by melvinzhang** [comment]
Such a card (nonland, without cost and without color property) will not pass the validate check. How did you get it to load?

**Comment by ShawnieBoy** [comment]
Ahh, that would probably explain it then, I'm using an un-validated MagicCardDefinition.

**Comment by melvinzhang** [comment]
Hmm, should always validate, but it is easy to miss. I'll move the validate method into prop2carddef.

**Comment by ShawnieBoy** [comment]
No-no, I'm referencing externally from the cardBuilder - no need to change things.

**Comment by melvinzhang** [comment]
which method are you calling to load the card?

**Comment by melvinzhang** [comment]
The current way we are doing it in CardDefinitions is fairly error prone. It is good to tighten it up so it is harder to obtain an unvalidated card.

**Comment by ShawnieBoy** [comment]
The card isn't being loaded in Magarena, just referencing the MagicColor.isMulti() with a raw MagicCardDefinition -> MagicCard in the cardBuilder.

**Comment by ShawnieBoy** [comment]
Was just wondering if becoming colorless in a game-state would give multicolor when called.

**Comment by melvinzhang** [comment]
As in creating it with new MagicCardDefinition()?

No, colorless is colorFlags = 0, unset is -1 which is multicolor. Then again it is never meant to be -1 cause that will not pass the validation check.

**Comment by ShawnieBoy** [comment]
Yes, with a new MagicCardDefinition() - Assumed that not setting a Color or ManaCost for a non-land permanent would return colorless, not multicolor, but I can see why now.

**Comment by ShawnieBoy** [comment]
Thanks for explaining that - it's a part of Magarena that would normally never come up :grinning:

**Comment by melvinzhang** [comment]
I see. There is no default color per se, we try to infer from costs/type if possible. If non of those are applicable, and there is no color property, then color is left as unset (-1) and should be caught by the validate method.

The purpose is to catch the case that the card script is missing the color. Otherwise it will be a silent error and the color is the wrongly assumed to be colorless.

There is some groovy scripts that create MagicCardDefinition on the spot (eg X/X Ooze). Those were missing a validate check. Closed up that gap in https://github.com/magarena/magarena/commit/327b94b1900b8c1d1db05fe7d784d5e90a226a94

**Comment by ShawnieBoy** [comment]
I thought that was the case - and glad to have helped close that Ooze loophole.
