### ISSUE TITLE
Face-down creatures are visible and are nameless in the log

### ISSUE THREAD

**Issue by bilbo2** [magarena/magarena#214]
The visibility of face-down creatures is not correct in Magarena.

When playing against AI, if AI plays a face-down creature with Morph and I hover mouse cursor over the face-down card, I can see what the card actually is, as it will just pop up. The face-down card should be invisible to me (when it is controlled by an opponent), as per rules only the controller can peek at the card.

Also, the relevant lines in the log regarding that creature shown with no name (empty string) for it. In a game I've encountered this bug, I get:

LOG (C): Monty Carlo attacks with .
LOG (P): bilbo blocks with Kozilek, Butcher of Truth.
LOG (C):  is destroyed.

As the face-down creature should be revealed (per rules) to everybody once it leaves play (like when it is destroyed and put into a graveyard), I would expect the log lines to be something like this in that example:

LOG (C): Monty Carlo attacks with a face-down card.
LOG (P): bilbo blocks with Kozilek, Butcher of Truth.
LOG (C): a face-down card (Raven Guild Initiate) is destroyed.

Some rules for face-down creatures are summarized on http://archive.wizards.com/Magic/magazine/article.aspx?x=mtgcom/feature/87

Considering a part of the FAQ from that page:

--- citation ---
What happens if there’s more than one face-down creature in play?
You have to make sure that your opponent knows what order they came into play. The best way to do this is to mark them with dice. You can’t shuffle them around, or do anything else to try to confuse your opponent. No "Three-Card Monte before blockers are declared."
--- end of citation ---

... it would be nice to number those face down creatures in the log, for example like this:

...
LOG (C): Put a face-down creature 1 onto the battlefield.
...
LOG (C): Put a face-down creature 2 onto the battlefield.
...
LOG (C): Monty Carlo attacks with a face-down creature 2.
LOG (P): bilbo blocks with Kozilek, Butcher of Truth.
LOG (C): a face-down creature 2 (Raven Guild Initiate) is destroyed.

**Comment by ShawnieBoy** [comment]
Thanks for the feedback.

@lodici One for you there with the sneaky-peek card pop-ups

The absence of log info for nameless creatures popped up in #157 and has yet to be sorted out. It's a bit of a quantum state for the cards, they have no name yet require a name for log purposes, along with cumulative count per player.

**Comment by lodici** [comment]
Thanks. Issue #215 created although I just would like to point out that you can still view your opponent's hand whenever you feel like. Inconsistent?

**Comment by ShawnieBoy** [comment]
I think it's possibly easier to accidentally cursor over an opponents card, than it is to accidentally look at their hand

**Comment by bilbo2** [comment]
I didn't notice the ability to view the opponent's hand .... maybe that one should be sorted out too :)

**Comment by ShawnieBoy** [comment]
It's mainly there from a developer's point of view - but can be handy for users to aid with bug-finding/identifying AI issues.

Now you know it's there, try and resist :wink:

**Comment by melvinzhang** [comment]
Closing this as we have split it into #215 (just fixed)  and #216
