### ISSUE TITLE
Nameless permanents and the log

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#216]
Raised in #214 

- [x] Nameless permanent reference on log.
Could possibly have a text replacement for the log for name strings < 1 = "a creature"/"a permanent"

- [x] Permanent numbering for face-down permanents 

- [x] Reveal on removal from battlefield.

**Comment by ShawnieBoy** [comment]
Ok, now this issue sounds like an indie band...

**Comment by lodici** [comment]
:laughing: I would go see them!

**Comment by melvinzhang** [comment]
was looking over the matching of names in filters. The current way is that morph creatures have a name which is the empty string. For the purpose of name filter and name comparison, it would be easier if they have unique names "face down creature [number]" as suggested by @bilbo2

We can achieve this by modifying MagicPermanent.getName to return the unique name.

**Comment by ShawnieBoy** [comment]
Name filters etc shouldn't see them at all, as they have no in-game name. The engine should see them as blank, but the log should be given a unique name. Where I couldn't think how to proceed.

**Comment by melvinzhang** [comment]
Name filter uses getName, right now getName returns the empty string, which means the name is the empty string, which is not the same as not having a name. In particular, empty string equals empty string unless we add a length check, which makes the logic rather messy.

For the purpose of keeping the logic simple, I think we can return unique names for each permanent without producing a result that would  not be different if than they had no names. As a bonus it also produces more readable logs.

Is there some cases where using unique names would produce a different result from MTG rules? The only case I could think of is if a rule mentions cards whose name contains [some text]. As far as I could tell, names are used whole and never considered in parts.

**Comment by ShawnieBoy** [comment]
Card Names are only ever compared in full - however with face down cards and 'unique' numbering: The opponent may have a face down permanent of the same number, and they will return a match.

**Comment by melvinzhang** [comment]
That's not possible because the names are unique as it is based on the internal id used to identify each object.

**Comment by ShawnieBoy** [comment]
I was meaning card name as it's physical name as for cards such as [Echoing Decay](http://magiccards.info/ds/en/41.html)

If face down permanent are going to be named 'face down permanent (1)' etc

**Comment by melvinzhang** [comment]
What would be the issue with Echoing Decay? Assuming unique names, Echoing Decay targeting a morph creature would destroy the targeted creature since its name matches itself, but no other creature would be destroyed as per the rules.

**Comment by ShawnieBoy** [comment]
How are you thinking of numbering them? I was assuming an increasing number per-player.

**Comment by ShawnieBoy** [comment]
Player one controls: face down card 1, face down card 2
Player two controls: face down card 1

That was how I was seeing it and that would be how Echoing Decay could confuse things

**Comment by melvinzhang** [comment]
There is already an increasing number per game to assign unique ids to each object. I'm thinking of using that. It will be more like "face down creature 73", "face down creature 84". The number wouldn't be continuous and would be a big large, at most three digits.

**Comment by ShawnieBoy** [comment]
I see - From a user point of view I could see that as being confusing, but makes sense from an engine point of view.

**Comment by melvinzhang** [comment]
Would that be more confusing that having blank names though?

**Comment by ShawnieBoy** [comment]
Hehe, of course not - Just the high numbers would make me think "Where are the other ones" :grinning:

**Comment by melvinzhang** [comment]
The number is because each MagicCard also has an id, so the smallest number is at least (all cards in the game) + 1. Perhaps interpret the number using a different base? Eg base 26 with A-Z instead of base 10 0-9, "face down creature AF" "face down creature HGF"

**Comment by ShawnieBoy** [comment]
I think I'm just used to MTGO using consecutive numbering. Maybe just having a '#' prefix would make it look more like a code instead of a count.

**Comment by melvinzhang** [comment]
Sure, will use the # prefix then.

**Comment by melvinzhang** [comment]
commit 4f767cf84d57 implements the unique names for face down creature as "face down creature #[id]"

**Comment by melvinzhang** [comment]
commit 0d88ae80ab5 reveals the card when it leaves the battlefield
