### ISSUE TITLE
Is there a way to tell which permanent of the same name the AI has targeted?

### ISSUE THREAD

**Issue by tlorance** [magarena/magarena#218]
I had two Sakura Tribe Elders in play and the AI played a black instant-death card on one of them. Of course, I wanted to sacrifice the Elder out from under the instant, but for the life of me I couldn't figure out which one it had targeted. In the end, I sacrificed them both, which was not an optimal play for me. Is there a nook or cranny in some log that can distinguish which object in play is the target of a spell or ability? Obviously the Magarena engine knows...

(And P.S. How do you get those neat labels on posts, like Question, which would be handy right now?)

**Comment by melvinzhang** [comment]
There is no way to tell the difference at the moment, but we're working on it. If you have suggestions/comments, do add them to #71

**Comment by ShawnieBoy** [comment]
The labels are only able to be defined by contributors I'm afraid - and yes, they are neat :grin:
