### ISSUE TITLE
able to activate unpayable activated ability

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#226]
Player with 1 life and Foul Familiar and Vesper Ghoul on the field, player is able to activate Foul Familiar's ability but unable to complete payment of the costs.

See src/magic/test/TestNoChoice.java for a repeatable test case. d83358a4a62

**Comment by melvinzhang** [comment]
Another case found by @ShawnieBoy 

Currently I'm able to cast Altar's Reap with only one Swamp and a Blood Pet on the battlefield.
The spell resolves even though the additional cost isn't paid.

**Comment by melvinzhang** [comment]
Also for "{1}, Tap an untapped creature you control" and you control a single untapped creature that can tap to generate {1}.

**Comment by melvinzhang** [comment]
Similarly for "{1}{G}, Sacrifice another creature" from Kheru Dreadmaw

**Comment by melvinzhang** [comment]
Similarly for "{3}, {T}, Tap an untapped creature you control" (Unerring Sling), where you already tap the only untapped creature to pay for {3}.

**Comment by melvinzhang** [comment]
Affects not only Altar's Reap but all cards with sacrifice a creature as additional cost, eg Call for Blood, as creature may be used to pay mana cost and not be around to be sacrificed when it is time to pay additional cost.

**Comment by melvinzhang** [comment]
Able to cast Fireblast with only two mountains when Thorn of Amethyst is on the field. Thorn of Amethyst increase casting cost of noncreature spells by {1}.

Using Fireblast's alternate cost, the full cost is "sacrifice two mountains, pay {1}". When checked individually they can be paid but when paid sequentially it cannot be completed as {1} cannot be paid after sacrificing the mountains. Found by CI build https://circleci.com/gh/magarena/magarena/1292

**Comment by ShawnieBoy** [comment]
>Using Fireblast's alternate cost, the full cost is "sacrifice two mountains, pay {1}". When checked individually they can be paid but when paid sequentially it cannot be completed as {1} cannot be paid after sacrificing the mountains. Found by CI build https://circleci.com/gh/magarena/magarena/1292

Would it be possible for .modCost to add mana costs before other costs if there are no mana costs to modify?

**Comment by melvinzhang** [comment]
Yes, but it would only solve this very specific case, would still run into problems if it was "Pay {1}, Tap two untapped mountains" if you already tapped the mountain to get {1}.

**Comment by melvinzhang** [comment]
Also occurs for Emerge, where the creature need to pay for the mana cost is sacrificed.

**Comment by melvinzhang** [comment]
Also occur for alternative casting cost + cost increase, eg "You may return an Island you control to its owner's hand rather than pay Daze's mana cost." and "noncreature spells cost {1} more to cast.". The card that is returned is needed to pay for {1}

**Comment by melvinzhang** [comment]
The last commit ruled out some cases but also made it not possible to activate some abilities when you actually could. The issue is that sometimes, some sequences of payment are legal while others are not. 

The method implement in ab74bf4 checks whether that a particular sequence that always uses the first choice is legal before deciding if an ability is playable. This fails when that sequence is not legal, but there exist another legal sequence.

Even if we could check if there exist a legal sequence, it is hard to force the AI/player to only choose that sequence. There could also be more than one legal sequence of cost payment.

A possible solution is to allow illegal sequences but make them have a bad outcome. For example, the player would be stuck at an unpayable cost, the only option is to undo. Following the rule for "Handling Illegal Actions" where "If a player takes an illegal action or starts to take an action                                                                                                                        
 but can't legally complete it, the entire action is reversed and any                                                                                                                       
 payments already made are canceled."

For the AI it isn't clear what outcome should be used to make it avoid such actions. Perhaps such actions always return a loss for the player making the action as it is always possible to avoid this by passing instead of making the action.

**Comment by melvinzhang** [comment]
It would be confusing to disallow activation when payment is possible, the previous method which allows all payable activation + some unpayable ones is probably better than the current one as it disallows some payable activation (specifically the ones where making the first choice results in a failure to pay all the costs, but there is some other sequence of choices which allows all costs to be paid).

If the player tried to pay an unpayable cost and get stuck, he/she should undo, or the engine will prompt for them to undo.

@ShawnieBoy what do you think?

**Comment by ShawnieBoy** [comment]
I think this is a good compromise - Although would the AI end up getting stuck trying to attempt unplayable routes?

**Comment by melvinzhang** [comment]
Reaching an unpayable cost would be considered a game loss in the AI internal simulation so that it will be avoided.

**Comment by ShawnieBoy** [comment]
For a player it would soon be obvious that the ability can't be activated - having a UI prompt when that occurs, explaining the situation, would help. It's a difficult problem to crack elegantly.

**Comment by melvinzhang** [comment]
Implemented a first cut of the suggested solution in #1177, doesn't have the player prompt at the moment. Will look into that next.

This issue of unpayable activated ability cannot be fully solved automatically so the solution we will take is to allow the player to try and pay and figure out that it is impossible, then undo.
