### ISSUE TITLE
No log message on sacrifice

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#227]
Raised on [Forums](http://www.slightlymagic.net/forum/viewtopic.php?f=82&t=16995&start=15#p178035)

Doesn't seem to be a simple place to put a .logAppendMessage() for SacrificeAction as a cost.

**Comment by melvinzhang** [comment]
Seems to be fixed. The log says "Sacrifice a beat you control (card name link)" If you click on the card name it shows the card.
