### ISSUE TITLE
Deck editor card pool empty because of invalid script...?!?

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#236]
Very strange behaviour raised by @PalladiaMors in the [forum](http://www.slightlymagic.net/forum/viewtopic.php?f=82&t=17132#p178196) when suspect script is added to the scripts folder.

[Edge_of_Autumn.txt](http://www.slightlymagic.net/forum/download/file.php?id=22124)
[Edge_of_Autumn.groovy.doc](http://www.slightlymagic.net/forum/download/file.php?id=22125)

**Comment by lodici** [comment]
Ok, it is definitely the script but I have still not worked out why it does not raise an exception. I thought it might be the encoding of the files which is why I asked for the actual files themselves - the groovy file is identified as Macintosh by Notepad++ (the txt is DOS/Windows) but I am not sure that is relevant. When running a build (both 1.61 and 1.62) the Deck Editor is empty. Running from the IDE it does raise an exception.

**Comment by lodici** [comment]
It is the encoding of the ``txt`` file, not the ``groovy``.

**Comment by ShawnieBoy** [comment]
Shouldn't it be Unix-UTF-8

**Comment by lodici** [comment]
Yes that works too.

**Comment by lodici** [comment]
It is definitely the ``UTF-8`` encoding that causes it. Still would like to know why it affects the card pool the way it does though.

**Comment by ShawnieBoy** [comment]
That's bizarre as they're all UTF

**Comment by ShawnieBoy** [comment]
Setting both files to UNIX line endings with UTF-8 w/o BOM and loads fine, can't load otherwise

**Comment by lodici** [comment]
I did a quick random loading of txt and groovy files from build 1.62.1060 and although it identified all as UNIX the encodings were a mixture of ANSI and UTF-8 w/o BOM. Not sure what the difference between the UTF-8's are to be honest. Will need to do some reading. I certainly would prefer an exception to be raised though otherwise who knows what other strange behaviour it might cause.

**Comment by ShawnieBoy** [comment]
Wasn't expecting ANSI to be in there

**Comment by lodici** [comment]
I don't think it matters too much unless the script contains non-standard characters that extend into the UTF character set.

**Comment by ShawnieBoy** [comment]
True - but most submissions through Firemind are encoded. Probably me before I got all my settings sorted again, hehe

**Comment by PalladiaMors** [comment]
Don't know if this info will be useful to you guys:

I'm now using Windows 8. I never start cards from scratch, I always pick a pre-existing groovy to serve as the "skeleton" for the new card. In this case, I picked Time_Walk.groovy (trololol). My preferred editor has been Notepad for a while, but when I open groovy files from Magarena in Notepad the text is totally scrambled at first, so what I've learned to do is open them in WordPad first, click save without modifying anything else in the script, and then open the file with NotePad, and the text is no longer scrambled.

I've had problems with non-standard characters through Firemind submissions before, related to the long - symbol (don't even know the shortcut to that). This is featured in Edge of Autumn's .txt file. However, it had never made the card pool disappear from Magarena before.

**Comment by lodici** [comment]
What a palaver! :grimacing: Go get NotePad+ + or NotePad2 or anything else other than NotePad/Wordpad. I have no idea why Microsoft keep Notepad (sentimental reasons maybe). This is what I get when opening a groovy file -
![screenshot00138](https://cloud.githubusercontent.com/assets/2443519/7447440/05be9aa2-f1f4-11e4-9c2c-a95492bdcf75.png)
I mean, come on!

**Comment by PalladiaMors** [comment]
Yep, that's exactly what it looks like if I try to open the file with NotePad without saving with another program first. If you try to maximize the window, it gets even worse.

**Comment by ShawnieBoy** [comment]
I use NotePad++ serves me well as the new default for windows
