### ISSUE TITLE
Card Removal warnings for Recover Self

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#240]
The AI generates lots of card removal failures when playing with cards that Recover Self - This can be seen in the dev log, not during play or log file.

I doubt this is having any detrimental effect, but quite spammy

**Comment by ShawnieBoy** [comment]
```
WARNING. Card <cardname> not found.
REMOVE: Failed to remove <cardname> from Graveyard, card in OwnersHand.

**Comment by lodici** [comment]
Agreed. @melvinzhang please can you make these AI debugs optional and off by default. Thanks.

**Comment by melvinzhang** [comment]
The warnings are there to help detect bugs, they are a symptom of possible problems. I'm not certain the best course of action when warnings show up is to suppress them without figuring out the underlying cause. @ShawnieBoy base on the card available, is there a possible sequence of actions for a remove card action to fail?

**Comment by lodici** [comment]
> The warnings are there to help detect bugs, they are a symptom of possible problems. I'm not certain the best course of action when warnings show up is to suppress them without figuring out the underlying cause.

Should you not be raising an exception then? They are a pain when trying to debug other stuff.

**Comment by melvinzhang** [comment]
There are legitimate cases these could happen in a game when a specific combination of effects are used. For instance if an effect exiles the card before it could recover itself from the graveyard. These tend to be fairly rare but could occur in a specific combo deck. Most of the time the warnings have led to discovery of bugs.

**Comment by lodici** [comment]
Well they seem to be cropping up more regulaly recently...
```
REMOVE: Fail to remove Rancor from Graveyard, card in Exile
WARNING. Card Rancor not found.
REMOVE: Fail to remove Rancor from Graveyard, card in Exile
WARNING. Card Rancor not found.
REMOVE: Fail to remove Rancor from Graveyard, card in Exile
```

**Comment by melvinzhang** [comment]
Agree, I've noticed that they are occuring much more often then usual even when using randomly generated two color decks. I've been meaning to do a more thorough investigation of the cause.

**Comment by lodici** [comment]
> Most of the time the warnings have led to discovery of bugs.

Right, by you, which is great. But they mean nothing to me and I have to comment out if they get in the way of my debug statements. My view is that each dev should be responsible for their own debug info and should make sure to remove before publishing - the stdout/stderr should be clean on checkout (I also don't care what the random seed is either). At the very least a VM option should be available that lets you turn off the statements if you insist that they on by default.

**Comment by melvinzhang** [comment]
Warnings are one level down from exceptions, in that they could happen in a rare case but most of the time when they happen something has gone wrong. Think compiler warnings, most of the time they suggest a problem with the code. Thanks for the feedback about making the meaning of the warnings clearer, definitely something to be improved.

Good point about the cluttering up of stdout/stderr, it is a serious problem as it is a shared resource. I will move warnings into a separate log file.

**Comment by ShawnieBoy** [comment]
>@ShawnieBoy base on the cards available, is there a possible sequence of actions for a remove card action to fail? For example, you mention RecoverSelf as the cause, is there some other way for the card with RecoverSelf to move back to the owner's hand before the RecoverSelf trigger resolves?

If the AI is has enough mana/resources to pay the cost twice.

**Comment by melvinzhang** [comment]
I see, this is the activated version. I was wrongly thinking of the
triggered version.

**Comment by melvinzhang** [comment]
The addition of "return sn from graveyard to owner's hand" card script activated abilities makes it much more likely to create legitamate situations where removal will fail. The number of false positives are too high to consider this warning effective, will be removing the warning entirely.
