### ISSUE TITLE
Observations on increasing max AI level and affects on a game.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#241]
A couple of posts recently have suggested it would be useful if you could remove the maximum limit on the AI level. From a UI POV that is very simple to do and would probably be quite a useful option when running AI vs AI (#138) . So I set it to 60 (seconds) for MCTSC and ran a duel to see what it was like.

One of the things I noticed first is that if you pause the game while the AI is thinking the CPU continues to get hammered since it does not pause the AI running its simulations. Personally, if I pause then I would expect the CPU usage to drop but I can also understand the argument that the AI should continue to think in the background as well.

However, I also noticed that if I quit to the main menu while the AI is thinking at M1 the CPU continues at max% well beyond the 60 seconds. Eventually it does stop but it does seem that the  AI simulation threads continue to run.

So my question - is it possible to pause the AI simulation threads and more importantly abort those threads immediately if a game is cancelled?

**Comment by melvinzhang** [comment]
Yes, by including continuously checking of Thread.isInterrupted as the AI is running. In any loop/recursion where the AI could spend a significant amount of time, the condition needs to be checked in every iteration. 

Related to this question is where such a change is worth it, and I feel that the increase in complexity to deal with threads (not a central AI concern) is not worth the benefit of being able to increase the thinking time increase to a large number like 60s.

Pausing would be an order of magnitude more complex and it requires saving the work that the AI has done and being able to resume at the point of stopping. The more problematic issue is that these are incidental problems, the core AI problem should be how to play a better game.

**Comment by lodici** [comment]
The pause does seem like a step too far but it really should be aware of the game cancellation state...

Started a game MCTS, level 8. As soon as it was its turn I quit to main menu. I could see the CPU was still being hammered. So then immediately clicked _Resume Duel_ to see what would happen. :smiling_imp: 

```
Exception from controller.runGame: java.lang.ClassCastException: java.lang.String cannot be cast to magic.model.choice.MagicPlayChoiceResult
magic.exception.GameException: java.lang.ClassCastException: java.lang.String cannot be cast to magic.model.choice.MagicPlayChoiceResult
	at magic.model.MagicGame.doAction(MagicGame.java:570)
	at magic.model.MagicGame.executeNextEvent(MagicGame.java:822)
	at magic.ai.MCTSAI.getNextChoices(MCTSAI.java:514)
	at magic.ai.MCTSAI.growTree(MCTSAI.java:347)
	at magic.ai.MCTSAI.TreeUpdate(MCTSAI.java:246)
	at magic.ai.MCTSAI$1.run(MCTSAI.java:153)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to magic.model.choice.MagicPlayChoiceResult
	at magic.model.event.MagicEvent.getPlayChoice(MagicEvent.java:486)
	at magic.model.event.MagicPriorityEvent$1.executeEvent(MagicPriorityEvent.java:17)
	at magic.model.event.MagicEvent.executeEvent(MagicEvent.java:650)
	at magic.model.MagicGame.executeEvent(MagicGame.java:765)
	at magic.model.action.ExecuteFirstEventAction.doAction(ExecuteFirstEventAction.java:18)
	at magic.model.MagicGame.doAction(MagicGame.java:568)
	... 10 more
```
This occurred after the mulligan screen. The third time I did it Magarena just exited, with no exception at all.

**Comment by melvinzhang** [comment]
My current thinking of how such a feature can be implemented requires extensive changes to the AI code itself, i.e. to each major loop or recursion function. Perhaps there is a different way to do it like a wrapper so that the concerns of threading can be separated from the AI algorithms.

**Comment by lodici** [comment]
Forgetting about threads for a moment, surely it must be possible to cancel the AI thinking process? It is almost like you are saying that once you set the AI off on its 60 second think there is no way to cancel, you just have to wait until it completes?

**Comment by lodici** [comment]
How to prevent the above error? Can we add a flag to ``MagicGame`` to indicate whether it can be cancelled which the UI can poll? Or allow an immediate cancel as it does now but prevent a new game from starting until the previous game/AI has finished?

**Comment by melvinzhang** [comment]
The above is due to the fact that the AI is not thread safe, two copies
shouldn't be run at the same time.

Yes you got it right, it not possible to cancel an AI in progress. Is the
controller notified on a game cancel? If so I think it can forward the
cancel notification to the AI or wait for it to terminate.

**Comment by lodici** [comment]
> Yes you got it right, it not possible to cancel an AI in progress.

Presumably it is a performance thing otherwise I cannot see a reason why you would write code this way. This would also explain why the maxium level is set at 8 instead of being more flexible. I have always thought this value was a bit arbitrary (why 8?) until you realize that it is 8 seconds of "blackout". Obviously having no control for anything much larger than this, let alone something like 60 seconds would be unacceptable.

> Is the controller notified on a game cancel? If so I think it can forward the cancel notification to the AI or wait for it to terminate.

I was thinking of a simple method that SwingGameController can call, something like ``isAiBusy()`` which I assume would be in ``MagicGame`` but you would know best. It it were a static method, ie ``MagicGame.isAiBusy()`` then it can be used to wait on start of a new game as well as cancelling an existing game.

**Comment by melvinzhang** [comment]
Stopping in the middle was never a design consideration hence it is not
present as there was no need for it and the code is simpler without it as
it can assume always running for a fix amount of time.

A notification would be simpler, say via a shutdown method in the
controller.

**Comment by lodici** [comment]
> A notification would be simpler, say via a shutdown method in the controller.

Ok.

**Comment by melvinzhang** [comment]
14dcb5ac957055e4 fixes the game cancellation crash
