### ISSUE TITLE
Question about mana abilities

### ISSUE THREAD

**Issue by tlorance** [magarena/magarena#242]
I understand that Magarena rules are slightly different from that other game's rules, generally to make the scripting easier and less error-prone.  Does the current implementation prevent the use of abilities that are not, strictly speaking, mana abilities (such as untap-a-land abilities) during cost payment, so that the "Can the player play this card?" parser would not see a card as playable because it does not recognize a path to generating the necessary mana?  If so, is there any future intention to address this, or is it considered a permanent simplification of Magarena?

**Comment by melvinzhang** [comment]
Only mana abilities can be used when paying a mana cost. Other abilities
are not allowed, you may use those abilities later when you have priority.
There are no plans to change this, but patches are welcome. The main
complication is in generating all possible computing possible ways to pay a
mana cost.

**Comment by ShawnieBoy** [comment]
This would only be resolved by the implementation of a mana pool.
I remember there was talk of creating 'mana tokens' to represent a mana pool.
