### ISSUE TITLE
Relentless Rats

### ISSUE THREAD

**Issue by JavinAzrael** [magarena/magarena#243]
Relentless rats (Relentless rats gains +1/+1 for each creature you control named Relentless Rats) no longer boosts on copies? They worked in the previous versions, but no longer do. Can we fix?

**Comment by ShawnieBoy** [comment]
Confirmed with Cackling Counterpart (Was kinda hoping it would be due to a particular copy card).
I'm wondering if this is an after-effect of changing morph cards to unique names. (stab in the dark), as I can't find anything that would be missing from a target-card's CardDefinition.

**Comment by melvinzhang** [comment]
Problem is that Rats is converted to singular Rat in the target filter. Fix is to protect the name with a special character.
