### ISSUE TITLE
Reveal action

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#249]
The reveal action related to face-down permanents doesn't seem to be putting their names in parenthesis. Would be nice for it to match other named card references.

I'm not sure if it's using the normal reveal action, in which case that might need to be updated too.

**Comment by melvinzhang** [comment]
It is using the normal reveal action. Seems to be an issue with the way the names are formed in RevealAction.cardNames

**Comment by melvinzhang** [comment]
@ShawnieBoy do you recall how to replicate the bug?

**Comment by ShawnieBoy** [comment]
I would guess that this is when face-down cards are revealed when going to the graveyard face-down. "PN reveals <face-down-card>"

**Comment by melvinzhang** [comment]
How should it look like? You mentioned "other named card references", where can I find those?

**Comment by ShawnieBoy** [comment]
"other named card references" would be the text displayed for "target permanent (permanent name)..." etc. The reveal would need a card-link format similar to other names in the log

**Comment by ShawnieBoy** [comment]
Indeed
