### ISSUE TITLE
AI cast Swords to Ploughshares on my Archangel of Thune, My creatures gained +1 +1 counters

### ISSUE THREAD

**Issue by Muppet1** [magarena/magarena#250]
It should leave the game before the life gain I think.

**Comment by ShawnieBoy** [comment]
Yes, I think you're right. Could be a similar issue with order of effects as #205

**Comment by melvinzhang** [comment]
Not related to #205, this is due to only clearing the static and triggered abilities of a removed permanent via delayed action. The reason for this is to allow destroying multiple permanents at the same time to work correctly. Eg "If an effect would simultaneously destroy Knight Exemplar and another Knight creature you control, only Knight Exemplar is destroyed."

**Comment by melvinzhang** [comment]
There isn't any simultaneous destroy action, every action occurs in a certain order. To allow the Knight Exemplar case, the work around we came up with is to delay the removal of Knight Exemplar's ability of granting "indestructible" till a game.update() using addDelayedAction. Perhaps there is a better way of solving both issues.

**Comment by melvinzhang** [comment]
The Swords to Ploughshares issue can be solved by forcing a game.update after the  RemoveFromPlayAction action. I think the crux is whether it is a single remove from play or multiple. I think a better fix is to allow RemoveFromPlayAction to handle the case of "simultaneously" removal.

**Comment by melvinzhang** [comment]
However RemoveFromPlay is rather complex as it is and making it work for a list of permanents would increase its complexity.

**Comment by ShawnieBoy** [comment]
>There isn't any simultaneous destroy action, every action occurs in a certain order. 

Is that also the case with the DestroyAction(Collection<MagicPermanent>)?

**Comment by melvinzhang** [comment]
Sort of, DestroyAction eventually boils down to RemoveFromPlay after performing a bunch of checks, but it is calling it in a loop for each permanent to be destroyed.

**Comment by melvinzhang** [comment]
In case it wasn't clear, there is never any kind of simultaneous action. The current work around is to delay the result of earlier actions so it seems as though all the actions are occurring at once..

**Comment by ShawnieBoy** [comment]
Yeah, I see now. Same with the dealing of damage, esp. Trample

**Comment by melvinzhang** [comment]
Fixed by having RemoveFromPlayAction perform an update, add variant that skips update called from RemoveAllFromPlayAction for case of "simultaneous" removal.
