### ISSUE TITLE
Permanents that can sacrifice for mana

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#251]
Currently I'm able to cast [Altar's Reap](http://magiccards.info/cns/en/112.html) with only one Swamp and a [Blood Pet](http://magiccards.info/tp/en/3.html) on the battlefield.

The spell resolves even though the additional cost isn't paid.

Similar in a way to #231

**Comment by melvinzhang** [comment]
Good find. This is more similar to #226, failure to detect unsatisfiable costs. Merging with #226.
