### ISSUE TITLE
difference between MagicCardDefinition isMissing, isValid, isScriptFileMissing

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#254]
There are a number of boolean members with similar meaning. Is it possible to consolidate some of them?

For example, isMissing and isValid is typically true, false (all missing cards are not valid, since we always add valid cards to scripts)

isScriptFileMissing (means the .txt file is not there?) seems to be an an issue that should be checked and fixed before a release rather than something we track at run time in MCD.

**Comment by lodici** [comment]
Had a quick look and I reckon you can probably use (!)isValid in place of isMissing. I could not see any reason to distinguish them. isScriptFileMissing is only really to catch where the Scripts Builder fails to generate a script for a card defined in AllCardNames.txt - as you say if you can catch it using awk then it becomes obsolete too.

**Comment by ShawnieBoy** [comment]
I guess `.isScriptFileMissing` can be useful for the dev Card Explorer - I've used it on occasion with implementing new sets.

**Comment by melvinzhang** [comment]
@lodici Thanks for the explanation. Will replace isMissing with isInvalid().

@ShawnieBoy can you elaborate a bit more on how you are using isScriptFileMissing? As lodici suggested, I think this can be integrated as one of the release checks (names in AllCardNames.txt = names from cards in scripts+scripts missing).

**Comment by ShawnieBoy** [comment]
Actually I think it was probably before Scriptbuilder was producing a list of 'Orphaned' cards.

Just for instances where AllCardNames.txt contained a card which didn't have a related script file.

**Comment by ShawnieBoy** [comment]
There's still a filter for them in the dev Card Explorer, but can normally be caught by a card having no values other than name.

**Comment by melvinzhang** [comment]
@ShawnieBoy I take it that it isn't needed then. Will be replacing isScriptFileMissing with check rule in the Makefile. I'll alert when a discrepancy is found.
