### ISSUE TITLE
Belltower Sphinx and triggered effect

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#255]
Should [Belltower Sphinx](http://magiccards.info/m12/en/46.html) be creating an effect instead of immediately resolving?
(Can't find a simple way of linking the groovy)

I ask as I'm working on [Jagged Poppet](http://magiccards.info/di/en/115.html) and the self-damaged discard trigger is similar.

**Comment by ShawnieBoy** [comment]
The answer is yes, it should be using the stack - submitting a fix

**Comment by ShawnieBoy** [comment]
Ok, seems as though a fix won't be as easy as I first thought:
This groovy is producing a crash to desktop with no error log when damaged, due to trying to reference 2 different parts of the executeTrigger Event (`getRefPlayer()` and `getRefInt()`)

**Comment by ShawnieBoy** [comment]
for reference:
```groovy
[
    new MagicWhenDamageIsDealtTrigger() {
        @Override
        public MagicEvent executeTrigger(final MagicGame game, final MagicPermanent permanent, final MagicDamage damage) {
            final int amount = damage.getDealtAmount();
            return damage.getTarget() == permanent ?
                new MagicEvent(
                    permanent,
                    damage.getSource().getController(),
                    amount,
                    this,
                    "RN puts ${amount} cards from the top of his or her library into his or her graveyard."
                ):
                MagicEvent.NONE;
        }
        
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            game.doAction(new MillLibraryAction(event.getRefPlayer(), event.getRefInt()));
        }
    }
]

**Comment by melvinzhang** [comment]
Should be "PN puts RN cards.." and getPlayer(). There is no ref player here, only ref int.

**Comment by ShawnieBoy** [comment]
doh!
I was obviously thinking from the perspective of the controller of the permanent, but should be from the damage dealer's perspective.
Thanks for that :grinning:

**Comment by ShawnieBoy** [comment]
Actually, by not referencing the controller of the source of damage, event.getPlayer() is returning the owner of the permanent. It should be the controller of the source of damage and the amount dealt.

**Comment by ShawnieBoy** [comment]
I guess it would need an event that took the damage as a whole and would return a `getRefDamage()`?
That would allow getting hold of `damage.getDealtAmount()` and `damage.getSource().getController()`

**Comment by melvinzhang** [comment]
You should reference the controller of the damage, the new MagicEvent is correct. Did you change it?
```
new MagicEvent(
    permanent,
    damage.getSource().getController(),
    amount,
    this,
    "RN puts ${amount} cards from the top of his or her library into his or her graveyard."
)
```

**Comment by ShawnieBoy** [comment]
Sorry, confusing myself with RN and PN, think I've got it sorted now.
