### ISSUE TITLE
No log message when detaching cards due to gaining protection

### ISSUE THREAD

**Issue by bilbo2** [magarena/magarena#258]
In a game I had situation where River Boa had Behemoth Sledge (green and white artifact equipment) equipped. I equipped the River Boa with Sword of Feast and Famine (which gives as part of its effect protection from black and green to the creature).

As a result, Behemoth Sledge "suddenly" detached from River Boa (which is correct, as it is green and River Boa gained protection from green), although when I decided to equip Sword of Feast and Famine I overlooked this consequence and in the log was no explanation of this (so it took me a while to figure out why the equipment was actually detached).

I think that when a card (Aura, Equipment, ...) is detached this way due to permanent gaining protection from it, this event should be logged in the log (like "Behemoth Sledge was detached from River Boa, because river Boa gained protection from green"), so it will be more apparent  to the player what and why is happening.

**Comment by melvinzhang** [comment]
Thanks for the suggestion! Implemented in the referenced commit, though it isn't able to show a detailed reason like "protection from green" it will show something like "Behemoth Sledge becomes unattached as River Boa has protection."
