### ISSUE TITLE
MagicPayedCost

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#259]
I've been working on a few cards that deal with the value of something (Casting Cost, Counters etc.) and found that `MagicPayedCost` doesn't return a `.getTarget()` for cards discarded as a cost.

It looks as though it should, as the card is chosen (ignoring random discard for now), and so I expected `.setTarget((MagicTarget)choiceResult)` to allow `.getTarget()` return something for a discarded card.

**Comment by melvinzhang** [comment]
Discard doesn't use MagicTargetChoice, it uses either MagicrRandomCardChoice or MagicCardChoice which supports more than 1 card, hence it fails the "event.getTargetChoiceResultIndex() >= 0" condition.

**Comment by melvinzhang** [comment]
One possible work around is to create a customize version for 1 card (non random) that uses MagicTargetChoice. @ShawnieBoy can you indicate what are the card affected?

**Comment by melvinzhang** [comment]
Turns out we already have one of those, which is needed for discarding a specific type of card. Use MagicDiscardChosenEvent instead for the cost.

**Comment by ShawnieBoy** [comment]
Ahh, excellent - Thanks
