### ISSUE TITLE
Use getName() instead of getDistinctName() in card explorer (affects tokens)?

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#260]
I am pretty sure we had a discussion prior to the recent updates (eg. 22a0e6a48dd6e334c2a70afdffb3dfaf0631a065) to the way tokens are handled but I'll be damned if I kind find it. Am I finally going senile or did we discuss it somewhere?

**Comment by melvinzhang** [comment]
We discussed it in https://github.com/lodici/magarena-cardbuilder/commit/f3349db5f8679c324f4aa2c09bb4e858e9f5cfca

You mentioned in https://github.com/lodici/magarena-cardbuilder/commit/f3349db5f8679c324f4aa2c09bb4e858e9f5cfca#commitcomment-11117556
> The token is also added to the TokenCardDefinitions class which I am not sure about.

Then I replied in https://github.com/lodici/magarena-cardbuilder/commit/f3349db5f8679c324f4aa2c09bb4e858e9f5cfca#commitcomment-11117590
> TokenCardDefinitions is a hang over from the old days. I'll replace it with getToken in CardDefinitions.

**Comment by lodici** [comment]
Thanks @melvinzhang.

The reason I wanted to check was because on reflection I think that in the Explorer it looks better if the ``getName`` value is displayed (ie. 5 Wurms) instead of the ``getDistinctName``. Originally, it was only showing a single Wurm but the recent updates have fixed it so that all 5 Wurms are now displayed correctly. I find the distinct name a bit verbose (the info is already there in the other columns) and don't like the way it lumps all the tokens together at the beginning of the list (that's what the Token filter is for) or the sort order. However, that is just my preference and I would be interested in other opinions.

![screenshot00152](https://cloud.githubusercontent.com/assets/2443519/7666302/d6109c12-fbd8-11e4-9cf4-0d164abdb99a.png)

or

![screenshot00153](https://cloud.githubusercontent.com/assets/2443519/7666341/fd06c6ec-fbd9-11e4-8836-117e745d68ea.png)
?

**Comment by melvinzhang** [comment]
I think using getName is less cluttered and avoids duplication. It would also follow the rules in the sense that the name of the token as recognized by the game rules is just "Wurm" or "Human".

**Comment by ShawnieBoy** [comment]
I agree with you there @lodici 
(I was assuming that would be where we were heading anyway, and that it wasn't implemented yet!)

The Name column should be displaying it's....

What @melvinzhang said ^
