### ISSUE TITLE
Replace Merlin with M icon

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#30]
![magarenaicon](https://cloud.githubusercontent.com/assets/2443519/5061260/0e5e6b40-6d85-11e4-9ee4-e8914e7ca26a.png)

The "M" is quite distinctive I think and should scale much better than the wizard and would look good as the application icon. Will need an outline so that it is displayed clearly on backgrounds with similar color to the foreground color of the logo.

**Comment by melvinzhang** [comment]
I noticed logo.png committed some time ago, it would make a great replacement for the current wizard icon. How should we proceed with this?

**Comment by melvinzhang** [comment]
Off the top of my head, the wizard is currently used in the following places:
1. wizards.png in About page
2. headerIcon.png on the main menu
3. magarena.ico for building magarena.exe
4. arena.icns for building Mac package

**Comment by lodici** [comment]
See above commit. That covers the app. Not so sure about the packaging though. See also #37 which is re-branding related.

**Comment by lodici** [comment]
@ShawnieBoy do you an "M" without the drop shadow? Would like to see how that looks.

**Comment by melvinzhang** [comment]
@lodici thanks for taking care of the program usage of logo. I've created ico and icns file based on logo.png with https://iconverticons.com will use these new files to replace the existing ones.

**Comment by melvinzhang** [comment]
Unfortunately the source image (logo.png) is sufficient to generate icons of max resolution 128x128. Our current mac icon arena.icns has a 512x512 version which was added to fix pixelated icons on Mac (see https://github.com/magarena/magarena-old-issues/blob/c7ce3b596b3ee06676cca3669ee91331a3f7cd4d/closed/issue-132.json). @ShawnieBoy could we have a 512x512 version of logo.png for icon generation?

**Comment by melvinzhang** [comment]
A useful reference article on platforms and icon sizes, http://www.visualpharm.com/articles/icon_sizes.html

**Comment by ShawnieBoy** [comment]
>@ShawnieBoy do you have an "M" without the drop shadow? Would like to see how that looks.

> @ShawnieBoy could we have a 512x512 version of logo.png for icon generation?

I don't I'm afraid - I think they got 'tidied away' - but I can easily make new ones.

**Comment by ShawnieBoy** [comment]
Pushed a larger size - does have a very different appearance due to the texture involved so haven't replaced the original.

Also pushed the psd so it can't go walkabout again

**Comment by melvinzhang** [comment]
Thanks for the new files, I'll look into updating the icons based on the 512x512 png. Btw what's the texture inside the letter? The original one looks more visually interesting, the new one is a bit more bland. Would it be possible to use the previous texture?

**Comment by lodici** [comment]
@melvinzhang do you use the image in resources for the packaging? Ideally we only want one logo image in resources at the max size it would be required for all uses. If you don't need to specifically use that one then we can store a smaller logo.png for use in the app.

**Comment by melvinzhang** [comment]
I think the ico is shown on the shortcut or when the program is the menu, haven't use windows for a while so I can't be sure. For the Mac icns, it should be a similar purpose. When the program is running, then it would be the one set by the program.

**Comment by melvinzhang** [comment]
The source image itself it not needed, it will be used to create the ico and icns file. The icon files (ico and icns) have multiple resolution images inside, it is up to the OS to select the one to use depending on the context. For example, our current Mac icns file contains the following:
```
----------------------------------------------------
Reading icns family from Magarena.app/Contents/Resources/arena.icns...
 Extracting icons from /arena.icns...
 Icon family size is 121016 bytes (including 8 byte header)
 Listing icon elements...
  'ic09' 512x512 32-bit icon (1048576 bytes compressed to 65634)
  'ic08' 256x256 32-bit icon (262144 bytes compressed to 16450)
  'it32' 128x128 32-bit icon (65536 bytes compressed to 18992)
  't8mk' 128x128 8-bit mask (16384 bytes)
  'il32' 32x32 32-bit icon (4096 bytes compressed to 1667)
  'l8mk' 32x32 8-bit mask (1024 bytes)
  'is32' 16x16 32-bit icon (1024 bytes compressed to 537)
  's8mk' 16x16 8-bit mask (256 bytes)
8 elements total found in /arena.icns.
```

**Comment by melvinzhang** [comment]
The current windows ico file is a single 128x128 32-bit icon. Since we are doing the update, I would also like to improve the ico file to follow the Mac icns file so that it will have a few different resolutions, though windows only use up to a max of 256x256.

**Comment by lodici** [comment]
Just committed update with the new icon, using 512 x 512 but scaling LOGO to the same size as before. Looks ok.

**Comment by melvinzhang** [comment]
The https://iconverticons.com website is pretty smart, when fed the 512x512 MagarenaIcon.png it generated a icns file with
```
----------------------------------------------------
Reading icns family from /home/melvin/Downloads/MagarenaIcon.icns...
 Extracting icons from /MagarenaIcon.icns...
 Icon family size is 307914 bytes (including 8 byte header)
 Listing icon elements...
  'is32' 16x16 32-bit icon (1024 bytes compressed to 750)
  's8mk' 16x16 8-bit mask (256 bytes)
  'il32' 32x32 32-bit icon (4096 bytes compressed to 2660)
  'l8mk' 32x32 8-bit mask (1024 bytes)
  'ih32' 48x48 32-bit icon (9216 bytes compressed to 5182)
  'h8mk' 48x48 8-bit mask (2304 bytes)
  'it32' 128x128 32-bit icon (65536 bytes compressed to 26401)
  't8mk' 128x128 8-bit mask (16384 bytes)
  'ic08' 256x256 32-bit icon (262144 bytes compressed to 61180)
  'ic09' 512x512 32-bit icon (1048576 bytes compressed to 191685)
10 elements total found in /MagarenaIcon.icns.
```
and an ico file up to 256x256 (as Windows doesn't use the higher resolutions)
```
MagarenaIcon.ico[0] ICO 256x256 256x256+0+0 32-bit sRGB 370KB 0.000u 0:00.000
MagarenaIcon.ico[1] ICO 128x128 128x128+0+0 32-bit sRGB 370KB 0.000u 0:00.000
MagarenaIcon.ico[2] ICO 64x64 64x64+0+0 32-bit sRGB 370KB 0.000u 0:00.000
MagarenaIcon.ico[3] ICO 48x48 48x48+0+0 32-bit sRGB 370KB 0.000u 0:00.000
MagarenaIcon.ico[4] ICO 32x32 32x32+0+0 32-bit sRGB 370KB 0.000u 0:00.000
MagarenaIcon.ico[5] ICO 16x16 16x16+0+0 32-bit sRGB 370KB 0.000u 0:00.000
```

**Comment by lodici** [comment]
But Is it the MAC wrapper that determines these icons or do they need to be all registered with the program proper?

**Comment by melvinzhang** [comment]
The ico and icns file is meant to contain multiple sizes, it is the OS that will decide which one to use. I think it would depend on things like the DPI of the monitor, the resolution setting etc.

**Comment by lodici** [comment]
I see, thanks.

**Comment by melvinzhang** [comment]
Just pushed a commit with updated ico and icns file. With these changes, we have replaced all known instances of the old logo with the new one.

**Comment by melvinzhang** [comment]
Correct, if the program doesn't use it at runtime, we don't have to distribute the 512x512 png file.

**Comment by melvinzhang** [comment]
The ico and icns files are standalone, once created they do not depend on the original image that created them.

**Comment by lodici** [comment]
Great, I will reduce the size to the max needed and put the 512 version in _excluded for the future if required.

**Comment by lodici** [comment]
Can confirm the new icon sizes very nicely in Windows now, merlin always stayed at the same small size.
![screenshot00425](https://cloud.githubusercontent.com/assets/2443519/11997110/f57f3400-aa6a-11e5-9ed8-a8f6a83c6d1d.png)

**Comment by ShawnieBoy** [comment]
>. Btw what's the texture inside the letter? The original one looks more visually interesting, the new one is more bland. Would it be possible to use the previous texture?

The original texture is from the 8th ed card background used on MTGO for their older card generation. 

This texture is the texture that's cut-out of the artifact frame for the image - used for the default images - even using the older texture (managed to hunt it out) it looks different is due to the size, as 512x512 is far larger than the original, it's showing more of the texture.

If I kept the original part of the texture and scaled it up it would only be a few massive pixels.

Here's an alternate version:
![magarenalogo](https://cloud.githubusercontent.com/assets/2363180/11998184/a22a40ea-aa8a-11e5-8630-535473d45f12.png)

**Comment by melvinzhang** [comment]
Thanks @ShawnieBoy, I like this very much better. The texture feels more rugged and interesting to look at. I would like to propose changing the logo/icons to this new one with the updated texture. @lodici What do you think?

**Comment by lodici** [comment]
App logo updated.

**Comment by melvinzhang** [comment]
@lodici thanks for the update! I've updated the ico and icns file. @ShawnieBoy please update the psd file in the excluded folder with the source for the latest version with the updated textture. Thanks!

**Comment by lodici** [comment]
Downloaded the [latest build](https://circleci.com/gh/magarena/magarena/637). It does not appear that the Windows icons (as shown in file explorer, etc) have been updated, they are still the same as before. Not sure if it is a cache thing. The program icons are ok.

**Comment by melvinzhang** [comment]
I checked the ico and icns files manually and they are accurate. I think on Windows there is an icon cache, you need to clear it first, see https://superuser.com/questions/499078/refresh-icon-cache-without-rebooting

On Linux, we did not package a icon. The one that appears in the taskbar/alt-tab menu would be the one set by the program.

**Comment by lodici** [comment]
Thanks - I rebooted and the new icon appears at all sizes in file explorer.
