### ISSUE TITLE
MagicGraveyardActivation rename?

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#309]
Completely confused myself with this activation name. Been working on [Soul of Ravnica](http://magiccards.info/m15/en/78.html) and trying to use MagicGraveyardActivation for it's second ability (Made sense to me).

After fighting with it, then tracing the abilities of the other scripted 'Soul of' cards, MagicGraveyardActivation isn't used by them, they use MagicCardAbilityActivation.

MagicGraveyardActivation is actually a CastFromGraveyardActivation, used similar to Flashback and Unearth.

Should this be renamed to clarify what it's actually doing?

**Comment by melvinzhang** [comment]
what would be a possible new name?

**Comment by melvinzhang** [comment]
perhaps MagicCardActivation should be renamed as well, the difference between them is one is cast from hand, the other is cast from graveyard.

**Comment by ShawnieBoy** [comment]
I suggested a CastFromGraveyardActivation - Would make sense for MagicCardActivation to be changed as well.

Maybe this could be a valid next place for a Refactoring to remove the Magic prefix?

**Comment by melvinzhang** [comment]
We current have MagicMorphCastActivation, how about MagicHandCastActivation and MagicGraveyardCastActivation?

**Comment by ShawnieBoy** [comment]
That makes sense. Makes it far more clear what each is performing.

Would be good to get the prefix-removing moving again as well.

**Comment by melvinzhang** [comment]
> Would be good to get the prefix-removing moving again as well.
Please create an issue with a proposal on what is to be changed so that we can have an open discussion about it. As an example, see https://github.com/magarena/magarena/issues/168
