### ISSUE TITLE
Cubes need an overhaul

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#311]
Here's some of my thoughts after dealing with issue #305 .

1. When you start a new duel you can specify the cube for the duel as a whole. At least that is the implication from the UI. However, it actually only applies when generating a random color or theme deck. It does not apply if you use prebuilt decks. As a user, because of where you set the cube in the UI I would intuitively expect it to apply to all deck generation (for both players) so that it would restrict prebuilt decks to only those containing cards that are valid for the selected cube. Alternatively, the cube option should be moved to the deck selection dialog (for each player) and only displayed when a random deck generator is selected. Currently, unless both players are using random color or theme decks then displaying the cube as a duel-wide setting is false and confusing information.

2. The _legacy_, _modern_ and _standard_ cubes duplicate the related ``.fmt`` files in ``magic.data.formats`` and so we are having to maintain the same data in two places. It is confusing in explorer/deck editor that these entries in the Cube filter clash with the same entries in the Format filter and the totals don't actually match anyway. I think the Cube filter should contain just custom cubes and leave the definitions of _legacy_, _modern_ and _standard_ to the Format filter.

4. The format filter (maybe sets as well?) should be be added to the new duel setup screen as additional ways of restricting the pool of cards that can be used in a duel (in addition to custom cubes).

3. It seems to me that a cube is essentially defining a pool of cards and is a way of letting users create a custom pool of cards (eg. the _ubeefx_ cube). It would be simple enough to add an option to explorer that lets you save a cube file based on the current filtered list of cards which a user could then open in a text editor to fine tune as required.

4. For some reason the complete collection of cubes is loaded at startup which is just shy of 17,000 string references. Unless I am missing something I think a cube only needs to be loaded on demand - when generating a deck.

5. The cube files should be stored in a ''Magarena\cubes'' directory instead of mingling with the other stuff in ``mods``.

**Comment by ShawnieBoy** [comment]
I agree with all the above, especially about the cubes duplicating the formats - Having the random deck editor using the format filters (e.g. explorer filters) would make much more sense.

**Comment by lodici** [comment]
The whole set of filters or just Format (and possibly Sets)? I think it should be kept simple - I don't think people will want to be faffing around will a load of filters when all they want to do is play a duel. Anything more advanced then you have the explorer from which you could create custom cubes for use in duels.

**Comment by ShawnieBoy** [comment]
Oh just the formats, but using the mechanics of the filters (The block formats should cover most of the set blocks, although having them as an option wouldn't hurt)

**Comment by melvinzhang** [comment]
Agree with all of the above. I think the way forward is for "Format" to replace "Cubes". If I'm not wrong we are only missing the ability to specify a custom format as a list of cards. Once we have the above, cubes should be removed in favor of formats.

**Comment by lodici** [comment]
Wouldn't you still want to distinguish between officially recognised formats and custom sets of cards (cubes?). Lumping everything into the Format filter (in the case of explorer) seems messy. Of course, it does beg the question - is there actually a need for custom cubes/sets/formats?

**Comment by ShawnieBoy** [comment]
Well Cubes (in their MTG term, not how we're using them - custom pools of cards) are still popular. While I don't use them, I'm sure there must be players who do, or would want to. Removing them completely may be too far.

Cubes could also be an entry route for player-designed card sets as well. Instead of creating an Explorer filter and custom set filter etc. they could reside in a Cube instead.

If when assigning a card pool for random deck generation, there could be the option to use the .fmt files for official formats, and maybe .cube/.cbe files which contain a list of custom cards.

**Comment by lodici** [comment]
> If when assigning a card pool for random deck generation, there could be the option to use the .fmt files for official formats, and maybe .cube/.cbe files which contain a list of custom cards.

I was thinking something like...
![screenshot00161](https://cloud.githubusercontent.com/assets/2443519/7835475/2edd4926-0471-11e5-9989-27239f6db4bd.png)

Perhaps move away from using "cubes" to some other term (I have used "custom" and "card pool" in the mock-up)?

**Comment by ShawnieBoy** [comment]
I think Cube is still a valid term, but yes, that mock-up looks good :)

All, Format and Cube - with cube using non-format related cube lists. Cubes could even be created in a Deck-builder interface - with one card max and no 'deck-size' limit.

[Introduction to Cubes](http://archive.wizards.com/Magic/magazine/article.aspx?x=mtg/daily/eventcoverage/tpc12/intro_to_cube) Primarily they're a draft format, but with automatic drafting in Magarena, they only function as a limited, player defined, card pool.

**Comment by melvinzhang** [comment]
> Wouldn't you still want to distinguish between officially recognised formats and custom sets of cards (cubes?). Lumping everything into the Format filter (in the case of explorer) seems messy.

I mean it more in the way of an internal concept, i.e. we should remove MagicCubeDefinition and have only have one internal concept of MagicFormat which includes the functionality of MagicCubeDefinition. 

I see MagicFormat as being more general than cube as it can also define custom deck checking rules. So we may have a format say 100 card Singleton, http://archive.wizards.com/Magic/tcg/resources.aspx?x=magic/rules/100csingleton

Having a single internal concept doesn't mean we have to display all of them all the time. That concept can have a notion of whether it was internally defined or user defined, say isCustom(), and we can choose to display different sets of "formats" in different parts of the UI, formats for duel vs formats for explorer.

**Comment by melvinzhang** [comment]
Alternatively MagicCubeDefinition can be made a subclass of MagicFormat so conceptually they are unified and one handles fmt file and the other handles txt file.

**Comment by melvinzhang** [comment]
In summary, I'm proposing we adopt format as the central abstraction. We can have custom formats (previously known as cubes) and predefined formats (standard, modern, etc). When starting a duel, you choose a format (custom or predefined), in explorer you can filter by predefined formats. 

@lodici Would such a suggestion met the criteria you've listed in the first post?

**Comment by ShawnieBoy** [comment]
:+1:

**Comment by lodici** [comment]
> @lodici Does this proposal met the criteria you've listed in the first post?

Not really. The issue is more about where you define the pool of cards for duel and how this restricts the decks that can be generated in a consistent way for both players. Using custom formats in place of distinct cubes is still a good idea though - they are essentially the same thing.

**Comment by ShawnieBoy** [comment]
The only difference with a 'proper' cube would be that it would be singleton for card-building/drafting between both players

**Comment by melvinzhang** [comment]
We've started to implement my proposal and so far we have eliminated the duplication mentioned in point 2. I think generally we agree that we want to address the concerns raised here, but it will be better to put it as separate issues so we can keep track of progress better. @lodici can you create separate items for each point?

**Comment by lodici** [comment]
Is point 5 still valid now that CubeDefinitions has gone.

**Comment by melvinzhang** [comment]
The *_cube.txt file are loaded eagerly, though there is less of them, official there is one left. Someone with a lot of *_cube.txt might experience problems, but so far no such reports have been received.
