### ISSUE TITLE
Skip till end of turn - Wait at opponent's end of turn step.

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#318]
Using 'Skip till end of turn' during an opponent's turn, will skip until the beginning of your upkeep, instead waiting at the End Step of the opponent's turn.

**Comment by melvinzhang** [comment]
Case of bad naming, the behavior is more of "skip this turn". Would actually stopping at end of turn be more useful than skipping the whole turn?

**Comment by ShawnieBoy** [comment]
Activating abilities and casting spells etc. at the end of an opponent's turn would probably occur more often than doing nothing during an opponent's turn.

It's the last possible moment to use any mana available, and would be very useful.

**Comment by melvinzhang** [comment]
Does this also apply for skipping your own turn? i.e. should we stop at end of your turn and let you case instants at the last moment in your turn as well.

**Comment by ShawnieBoy** [comment]
I guess it would make sense for it to be symmetrical.
