### ISSUE TITLE
Java 1.8

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#319]
Though I'd raise this again after looking at ways to try and speed up CardBuilder.

It would appear that 1.8 is now fully established. When would we begin considering an upgrade to the latest version?

**Comment by melvinzhang** [comment]
For reference, the last public update of Java 6 was 2013-04-16 (according to https://en.wikipedia.org/wiki/Java_version_history). We switched to min req Java 7 for release 1.42 (September 29, 2013). About 5 months after last public update.

From the same wikipedia page, the last public update of Java 7 was 2015-04-14. Going for a similar schedule, would put us also in the September release.

**Comment by melvinzhang** [comment]
Another data point, jdk8 is slow in becoming available on Linux. On Debian (which I'm using), jdk8 became available in the testing repository on May 16, https://tracker.debian.org/news/685007

**Comment by melvinzhang** [comment]
I think it will be easiest to follow the previously established timeline, I'm proposing the September release as the earliest one that will requirement minimum of Java 8.

**Comment by ShawnieBoy** [comment]
Cool - Sounds good to me.

**Comment by lodici** [comment]
> Though I'd raise this again after looking at ways to try and speed up CardBuilder.

I would be interested in which aspects of java 8 speed up CardBuilder?

Also expect subtle (and maybe not so subtle effects with the UI). In the image below the left JList is running in java 7 (7.0.650.19) while the exact same list on the right is running in java 8 (8.0.31.13). For some reason, java 8 has decided to change the highlight color.

![java7java8](https://cloud.githubusercontent.com/assets/2443519/7937600/d7ff8e58-0938-11e5-9c44-765b739f23f7.png)

**Comment by ShawnieBoy** [comment]
Strange - maybe it's something that needs to be defined now?

As for cardbuilder, I was intrigued by the stream api of collections relating to switches and for-each. More of a wondering, than solid proof. It's enabled by lambda.

**Comment by lodici** [comment]
> Strange - maybe it's something that needs to be defined now?

Yes, this will need to be looked at because there is going to be plenty of people running Magarena __now__ using JRE 8 even though it is built using java 7. The color issue might even be related - build in 8 and it might be different.

**Comment by ShawnieBoy** [comment]
Oops, English error - I was meaning that highlight colour may now need to be defined in 1.8

I would imagine that running in 1.8 or building in 1.8 would  produce different results (I've been running in 1.8 for a while now)
