### ISSUE TITLE
Multiple redirected damage from player to creature over it's toughness

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#322]
If multiple sources of damage are redirected to a creature (e.g.. via Pariah during combat) any damage dealt over that creature's toughness are not redirected.

I would assume that this is due to each source of damage being applied separately, and the creature dying in-between these applications and before other damage can be redirected.

**Comment by melvinzhang** [comment]
Unable a replicate, all damage get marked on the creature with Pariah. None goes to the player even though the damage is much greater than the creature's toughness.
