### ISSUE TITLE
Add 'Masters' reprint sets.

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#323]
Chronicles is a reprint set, akin to Modern Masters or Vintage Masters. As we are only including sets that contain new cards that are Vintage legal and not accessible in other sets (e.g. Commander), or are a part of blocks or basic sets. Should we think about removing this set?

This is a ridiculously minor thing, just something I realised while looking through the sets filter.

**Comment by melvinzhang** [comment]
I think we should include reprint sets such as Modern Masters and Vintage Masters as they have a selection of cards that are designed to play well against one another.

**Comment by ShawnieBoy** [comment]
Should we limit reprint sets to those released as boosters then? Saves absorbing all the reprint boxed sets as well. (Battle Royale, Beatdown etc.)

**Comment by melvinzhang** [comment]
I think that makes sense, we can leave out sets that consists of theme decks.
