### ISSUE TITLE
Skip till end of turn, skips fast-effects for attack+block step

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#324]
If you skip till end of turn during an opponent's turn, it will pause when they put something on the stack for you to respond to.
If the opponent attacks, you're unable to respond to the declare attackers, and are only prompted to declare any blockers.

If attackers are declared, the skip till end of turn should stop at the declare attackers phase, allowing fast-effects during the declare attackers, and declare blockers steps.

**Comment by melvinzhang** [comment]
Thanks for checking out the skip functionality. There are many corner cases to take into account that the current implementation lacks. https://github.com/magarena/magarena/commit/2c30b2005e43375761d1276edbfda2ab0d0788b0 addes a check for whether opponent is attacking, if so cancel the skip immediately (same as when there is something on the stack).

**Comment by ShawnieBoy** [comment]
Thanks - I have a feeling that combat would be the only area that needed looking. But who knows.
I forgot about the right click skip myself, and using now when play-testing cards
