### ISSUE TITLE
Miracle being logged if AI doesn't reveal

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#325]
Game logs if the AI drew a Miracle and declined to reveal it. Shouldn't log anything if it's not revealed.

**Comment by ShawnieBoy** [comment]
![oops](https://cloud.githubusercontent.com/assets/2363180/21950556/1d0d31c0-d9f4-11e6-9c35-4a13137977ed.png)

Is the log-header, not the log text which gives it away when the AI draws it.

**Comment by ShawnieBoy** [comment]
The draw trigger shouldn't log anything - it should only log if the choice is 'Yes' and the spell is being cast.

**Comment by lodici** [comment]
I think the stack item is updated in two steps. First the stack item is displayed without the response while Magarena waits for the player (human or AI) to respond. After the player has made their decision it is updated with the response in red (as shown). Therefore, when adding the first time to the stack we need to know that the card cannot yet be revealed so that we can display ??????? (or whatever) instead of the card name. After the player has made their decision then the card name should be shown if the response was yes.

**Comment by ShawnieBoy** [comment]
However, knowing that your opponent has drawn a Miracle card and refused to reveal it, is just a good as revealing it if there's only one type in the deck. In a RL game, you wouldn't know that a reveal has been declined.

**Comment by lodici** [comment]
Hmmm, a tricky one.

**Comment by ShawnieBoy** [comment]
I tried putting the log message into the effect, but the log still displays an empty message with header to the log. If it couldn't display an empty message, it would be possible to only display a message once a choice had been made.

**Comment by melvinzhang** [comment]
Probably should fix miracle into two separate events. First event is a choice of whether to reveal (this does not go on the stack by returning false for usesStack), second is a normal trigger on the stack for casting the card.

**Comment by melvinzhang** [comment]
The reason that the stack message appears even when the description is empty is because the current trigger is defined as using the stack, so it must create a stack entry.

**Comment by melvinzhang** [comment]
I gave this a quick test, one issue is that even when the trigger does not put anything on the stack. The choice menu of whether to reveal will be visible to the player. Probably needs some kind of conditional logic, show normal choice menu if player is human else if player is AI show something that does not reveal information, eg use source as MagicSource.NONE and may choice text as "...".

**Comment by melvinzhang** [comment]
@ShawnieBoy please help to verify if the commit works as required. TestMiracle shows how it looks on both sides when the player draws a Miracle card and when AI draws a Miracle card.

**Comment by ShawnieBoy** [comment]
Looks good 😃 - I'd remove the ellipses though, the thinking symbol is already there to show AI thinking.

**Comment by melvinzhang** [comment]
Ellipses there is for consistency with MagicExcludeEvent which is an AI only choice.

**Comment by melvinzhang** [comment]
The benefit is that the player can't tell if it is the exclude choice or the miracle choice. The way miracle for Ai is done is to make it look like the exclude choice.

**Comment by ShawnieBoy** [comment]
I see.

I've also noticed you can't undo casting a card with Miracle. Although it could be Terminus.

**Comment by melvinzhang** [comment]
Wait, that's not right. You mean once it is cast, undo doesn't work?

**Comment by melvinzhang** [comment]
@ShawnieBoy  Can you give the steps in TestMiracle to show the case of "can't undo"?

**Comment by ShawnieBoy** [comment]
Choose to cast your Terminus with Miracle, advance to the AI's turn (usually chooses to cast as well). Try to undo back and choose not to cast your Terminus.

**Comment by melvinzhang** [comment]
I see, yes that would occur if Miracle is the first card drawn in the game. The game only creates undo points when it is your priority.

**Comment by melvinzhang** [comment]
Currently all May choice have inherit this issue, as it doesn't create undo points at "may choices".

**Comment by melvinzhang** [comment]
Tackling this in https://github.com/magarena/magarena/issues/1031

**Comment by lodici** [comment]
> Looks good :smiley: - I'd remove the ellipses though, the thinking symbol is already there to show AI thinking.

Preferences -> Gameplay -> [Experimental] Suppress AI action prompts. :smiley:
