### ISSUE TITLE
Is there a way to script fights between decks? Command line

### ISSUE THREAD

**Issue by fullmooninu** [magarena/magarena#326]
Does something like this exists?

duel deck1.dec deck2.dec --ai AI_type --resultFile filename

also a question: what AI is used on both decks when you use the deck strength test?

**Comment by melvinzhang** [comment]
Yes!
cd Magarena;
java -cp <Magarena.jar/exe> magic.DeckStrCal --deck1 <.dec file> --deck2 <.dec file> [options]
Options:
--ai1      [MMAB|MMABC|MCTS|RND] (AI for player 1, default MMAB)
--ai2      [MMAB|MMABC|MCTS|RND] (AI for player 2, default MMAB)
--str1 <1-8>                 (level of AI 1, default 6)
--str2 <1-8>                 (level of AI 2, default 6)
--games    <1-*>          (number of games to play, default 10)

Deck strength test using MMABFast which is not time based, but rather limits itself to "level" main phases of look ahead. For all other AIs, level = number of seconds of thinking time.

**Comment by melvinzhang** [comment]
This is the class that is invokved: https://github.com/magarena/magarena/blob/ded3f8b6b6c6cc70551f0fbff24e534aa057ff67/src/magic/DeckStrCal.java

**Comment by fullmooninu** [comment]
thanks!
