### ISSUE TITLE
Griffin Rider doesn't seem to get a boost from Favorable Winds

### ISSUE THREAD

**Issue by itandetnik** [magarena/magarena#331]
Computer has Griffin Rider, Sunrise Griffin and Favorable Winds in play. Griffin Rider is 4/4 ("native" 1/1 and +3/+3 bonus from Sunrise Griffin) - same as it was before Favorable Winds was played. On the other hand, Sunrise Griffin appropriately gets its +1/+1 boost to 3/4.

It seems that, as long as Griffin Rider has flying, it should get a boost from Favorable Winds.

Screenshot:

![image](https://cloud.githubusercontent.com/assets/9506419/7951850/b8b7abb0-097a-11e5-9103-e09415a60ce7.png)

**Comment by melvinzhang** [comment]
Good catch. Griffin Rider was applied at the wrong layer, fixed inGood catch. Griffin Rider was applied at the wrong layer, fixed in https://github.com/magarena/magarena/commit/cb015edec9c3f87bbb77908935fb2cf7b0c83b7c
