### ISSUE TITLE
No error report for script missing 'enchant='

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#338]
Was banging my head trying to work out what I had done wrong while working on [Mind Whip](http://magiccards.info/ia/en/37.html). I kept getting a crash to desktop with no crash log. Even in a Test scenario (which is normally better at catching crash reasons). The ability parser in Dev mode threw no errors, so I thought it must be something in the groovy

After scrutinizing the groovy from every angle, and trying all kinds of alternative methods, I then noticed I'd missed off the 'enchant=' property on the script file! :tired_face: 

I know I normally miss the obvious (It's true!), but was wondering if the dev parser could check for the 'enchant=' property for Auras. I'm sure other script/groovy submitters might get caught by this as well.

**Comment by ShawnieBoy** [comment]
Ok... The crash to desktop wasn't being caused by the omissions (I was using getRefPlayer() instead of getPlayer() - The obvious again) - But I guess the statement about the parser still stands.

**Comment by melvinzhang** [comment]
Another case of getRefPlayer instead of getPlayer, https://buildhive.cloudbees.com/job/magarena/job/magarena/1319/console Fix on the way.

**Comment by melvinzhang** [comment]
Add check for missing enchant in https://github.com/magarena/magarena/commit/a550b42a7ab4151526625f61991bebc0ca4a9386

**Comment by ShawnieBoy** [comment]
@melvinzhang Thanks! I'll get the hang of it someday!
