### ISSUE TITLE
Player Max Hand size adjustment

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#340]
I've been experimenting with cards that adjust the max hand of players. Currently we have a player.noMaxHand() but nothing in-between. So adding the follwing to the list appear as they should work.

```java
public void noMaxHandSize() {
    maxHandSize = Integer.MAX_VALUE; }

public void setMaxHandSize(final int amount) {
    maxHandSize = amount;
}

public void reduceMaxHandSize(final int amount) {
    maxHandSize -= amount;
}

public void increaseMaxHandSize(final int amount) {
    maxHandSize += amount;
}
```

However with testing, the values adjusted appear wrong - too high, to be possibly double (can be tricky to tell - I've only tested the reduceMaxHandSize so far). I'm wondering if this is because the modifying ones are being applied at the player level, which is also the level which maxHandSize is set. Or something else...

There's around 11 cards which reduce, increase or set a hand size, so it's not major.

**Comment by melvinzhang** [comment]
Hard to tell without looking at how the methods are called from groovy. Should be able to make it work. Can you commit your changes and the cards with a test case?

**Comment by ShawnieBoy** [comment]
Sure thing - I'm applying them the same as Spellbook

**Comment by melvinzhang** [comment]
The way it works is maxHandSize is set to 7. Then each of the modPlayer runs in order they were created, oldest first. If you only have reduceMaxHandSize, that shouldn't be a problem. If you have a mixture of reduce and set, then the order they were cast makes a difference. i.e.
7, -1, -1, -1, 5, -1 = 4
7, 5, -1, -1, -1, -1 = 1

**Comment by ShawnieBoy** [comment]
Even only with one reduction, it appears to be applying twice - pushed the test cards and scenario

**Comment by ShawnieBoy** [comment]
Will have to have a read on if the mix of set and reduce are applied by time-stamp. If it is then the application order would be ok.

**Comment by melvinzhang** [comment]
Hmm, the problem is modPlayer should only modify the player passed it, it should not be using source.getController. modPlayer is called twice, once for each player.

**Comment by ShawnieBoy** [comment]
I see. I guess that it wouldn't be noticeable on Spellbook.

Found this
>613.10. Some continuous effects affect game rules rather than objects. For example, effects may modify a player’s maximum hand size, or say that a creature must attack this turn if able. These effects are applied after all other continuous effects have been applied. Continuous effects that affect the costs of spells or abilities are applied according to the order specified in rule 601.2e. All other such effects are applied in timestamp order. See also the rules for timestamp order and dependency (rules 613.6 and 613.7).

**Comment by melvinzhang** [comment]
Fix for spellbook incoming.

**Comment by ShawnieBoy** [comment]
Bingo - from the rules notes for Null Profusion:
>If multiple effects modify your hand size, apply them in timestamp order. For example, if you put Spellbook (an artifact that says you have no maximum hand size) onto the battlefield and then put Null Profusion onto the battlefield, your maximum hand size will be two. However, if those permanents entered the battlefield in the opposite order, you would have no maximum hand size.

**Comment by ShawnieBoy** [comment]
Cool, I'll set about fixing them now - thanks for the help
