### ISSUE TITLE
Add card value to missing scripts?

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#342]
Since I believe it is automated (I can't imagine @melvinzhang updates them manually) is there any reason why the value property for missing scripts could not also be updated at the same time?

**Comment by melvinzhang** [comment]
It will double the time needed, which is already rather long.

**Comment by melvinzhang** [comment]
Hmm, if we update all the missing cards before they get added, then we can remove the card value update from the release process... Sounds promising. I'll get it started.

**Comment by lodici** [comment]
> Hmm, if we update all the missing cards before they get added, then we can remove the card value update from the release process.

Don't you still update the value every month though?

**Comment by melvinzhang** [comment]
Sure, I'll update it at the start of a new release, where it isn't so time critical.

**Comment by melvinzhang** [comment]
Thanks for suggesting this. It will help to reduce some amount of anxiety during release by reducing the work required.

**Comment by lodici** [comment]
No probs. It wasn't a biggy - I just thought it might be useful to have the values in explorer if they were easy enough to update. I wasn't really thinking about how it would decrease your end of month workload, so glad to be of help! :wink:
