### ISSUE TITLE
Is the AI cheating?

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#346]
I was testing [Lifespinner](http://magiccards.info/bok/en/133.html) in a mirror match against the AI.
The only Legendary Spirit in the deck was [Kodama of the South Tree](http://magiccards.info/chk/en/223.html).

Very early on, there was a lot of `WARNING. Card Kodama of the South Tree not found.` spamming the dev log. Now I expect that is from an activation of Lifespinner. (I played again without Lifespinner and the warnings didn't appear).

The interesting point is that the AI didn't have a Lifespinner in hand or in play. I didn't have one in play, but had one in my hand. Neither of us had a Kodama of the South Tree in hand or in play.

Were those error triggers occuring in an AI simulated game where I had played a Lifespinner? If so that would show knowledge of the contents of my hand - which is cheating.

Or could it be that it is in an AI simulated game where it draws a Lifespinner? If so that would show knowledge of the AI's deck - which is cheating.

What's happening here?

**Comment by melvinzhang** [comment]
Which AI were you playing against? Contents of your deck is considered to
be known, as you can inspect it before the match.

The honest MCTC AI can deduce the content of your library and create
simulated library with the same cards but in random order.

If you could create a test case, I can look into it more carefully. There
are also other instances where cards from library are revealed, such as
during a search. There could be bugs there as well.

**Comment by ShawnieBoy** [comment]
MCTS lvl 8 - my default

I see, I didn't realise the AI did that - I was always assuming that simulated games were using the UNKNOWN card for anything it knew nothing about.

I'll have a look if I kept my test scenario, if not I'll do another.

**Comment by melvinzhang** [comment]
This is the technique that enabled honest MCTS to work, which is why we only had cheating MCTS for two years.
