### ISSUE TITLE
Crash to desktop with no log

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#347]
I'm having this with a couple of new groovy files, even in test scenarios. I know it's to do with the looping of lists, and made some adjustments, but I'm not sure exactly what's causing the problem as there's no error report or crash log and they parse ok.

[Mark of Eviction](http://magiccards.info/rav/en/58.html)
```groovy
[
    new MagicAtYourUpkeepTrigger() {
        @Override
        public MagicEvent executeTrigger(final MagicGame game,final MagicPermanent permanent,final MagicPlayer upkeepPlayer) {
            final MagicPermanent enchanted = permanent.getEnchantedPermanent()
            return enchanted.isValid() ? 
                new MagicEvent(
                    permanent,
                    enchanted,
                    this,
                    "Return RN and all Auras attached to that creature to their owners' hands."
                ) :
            MagicEvent.NONE;
        }

        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            final MagicPermanent enchanted = event.getRefPermanent();
            final Set<MagicPermanent> auras = enchanted.getAuraPermanents();
            for (final MagicPermanent aura : auras) {
                game.doAction(new RemoveFromPlayAction(aura, MagicLocationType.OwnersHand));
            }
            game.doAction(new RemoveFromPlayAction(enchanted, MagicLocationType.OwnersHand));
        }
    }
]
```
[Bloodbond March](http://magiccards.info/rav/en/58.html)
```groovy
[
    new MagicWhenOtherSpellIsCastTrigger() {
        @Override
        public MagicEvent executeTrigger(final MagicGame game,final MagicPermanent permanent,final MagicCardOnStack cardOnStack) {  
            return cardOnStack.hasType(MagicType.Creature) ?
                new MagicEvent(
                    permanent,
                    cardOnStack,
                    this,
                    "Each player returns all cards with the same name as (${cardOnStack.getName()}) from his or her graveyard to the battlefield."
                ):
                MagicEvent.NONE;
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            final String name = event.getRefCard().getName();
            for (final MagicPlayer player : game.getAPNAP()) {
                final List<MagicCard> graveyard = cardName(name).from(MagicTargetType.Graveyard).filter(player);
                for (final MagicCard card : graveyard) {
                    game.doAction(new ReanimateAction(card, player));
                }
            }
        }
    }
]
```

**Comment by melvinzhang** [comment]
Please add the two cards and a test scenario which crashes.

**Comment by ShawnieBoy** [comment]
Will do

**Comment by melvinzhang** [comment]
The part about "no log" is something to be concerned about, crash.log should be updated. There could be a bug in the log generation as well.

**Comment by ShawnieBoy** [comment]
I've been finding quite a few of them recently :disappointed:

**Comment by melvinzhang** [comment]
When I run the test scenario from the command line, I always see the exception trace. For now, perhaps try starting the test from the command line?
```
java -ea -DtestGame=<TestClass> -Dmagarena.dir=<path to release dir> -jar <path to jar>
```

**Comment by ShawnieBoy** [comment]
I'm not entirely sure how to attach auras in a test scenario for Mark of Eviction - however I've managed to get it to crash in a game, and also work in a game.

**Comment by ShawnieBoy** [comment]
Ok, managed to push a scenario where the AI makes the crash for Eviction (Hopefully it should)

**Comment by melvinzhang** [comment]
Found the problem why crash.log isn't updated, it is case I'm using a different handler in the AI than the default one. Fixed in https://github.com/magarena/magarena/commit/179f64369d6ea4f542f1cf510fba99a889f1af86

@ShawnieBoy  please confirm if you are able to get the exception trace with the fix in place. If so, we will close this issue. 

If you are unable to figure out the problem from exception trace for the buggy cards, please create new issues for them. Thanks.

**Comment by ShawnieBoy** [comment]
Yes, got it - I can see the reason for Bloodborn, no idea with Eviction - will use new issue.

Thanks for that :+1:
