### ISSUE TITLE
Skip till end of turn and Undo

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#350]
Been using the skip till end of turn a lot, and found another small issue.

If you accidentally right-click instead of left-click, and so skip until your end step (if you have to potential creatures to attack). When you undo, the skip till end of turn still applies, so you end up back at your end of turn.

Even worse, if you undo twice (In this case, to the start of the game) the skip is still in effect and so I skipped my first turn as well :cry: 

Having undo remove the skip effect would solve this issue.

**Comment by melvinzhang** [comment]
Solving this a different way, having the skip clear itself when it reached EOT. So that undo doesn't have to know about skip, which is technically not part of the game state (it is a gameplay helper) and shouldn't be something undo should be tracking.
