### ISSUE TITLE
Introducing Suspend

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#351]
The more I look at suspend, the more I think this can be done, in doing some research on the specific mechanics involved, I can break down what needs to be added/adapted.

Any feedback or insights on this are welcome.

Suspend is essentially 3 abilities, which will be covered below
###### 'Activating' Mechanics.

**“If you could begin to cast this card by putting it onto the stack from your hand, you may pay [cost] and exile it with N time counters on it. This action doesn’t use the stack,”**
- Is a static card ability, only when in hand.
- Uses the casting restriction of the card it is on (Creature, Instant, Sorcery etc.), which isn't effected by targeting restrictions.
- Doesn't use the stack. Can't be responded to, and isn't 'playing' a card.
###### While 'Suspended'

**“At the beginning of your upkeep, if this card is suspended, remove a time counter from it,”**
- Is a triggered ability while 'Suspended' (_702.61b A card is "suspended" if it's in the exile zone, has suspend, and has a time counter on it._).
###### 'Casting' Mechanics

**“When the last time counter is removed from this card, if it’s exiled, play it without paying its mana cost if able. If you can’t, it remains exiled. If you cast a creature spell this way, it gains haste until you lose control of the spell or the permanent it becomes.”**
- Is a triggered ability which activates when the last counter is removed. Not the same as if it has no counters on it (It's then just an exiled card).
- Is 'playing a card'
- If it is a creature it gains Haste 'permanently'. If control of it is lost, it then loses Haste. If on the stack, the creature spell has haste.
- Timing restrictions are ignored, but not other casting/targeting restrictions.
- Casting isn't optional. (If additional costs are required, they must be paid. If the additional costs are mana costs, then those costs are optional. If they are chosen to not be paid, it remains in exile).
##### What needs to be added/modified.
- Adding/Removing counters from MagicCard
- Adding/Removing counters from exiled sources
- Triggered abilities on MagicCard
- Triggered abilities from exiled sources
- Timing restriction enforcement and override
- Displaying counters on cards
###### Relevant Comprehensive rule entries

115.2e A player who has a card with suspend in his or her hand may exile that card. This is a special action. A player can take this action any time he or she has priority, but only if he or she could begin to cast that card by putting it onto the stack. See rule 702.61, “Suspend.”

117.3c Activating mana abilities is not mandatory, even if paying a cost is.
Example: A player controls Lodestone Golem, which says “Nonartifact spells cost {1} more to cast.” Another player removes the last time counter from a suspended sorcery card. That player must cast that spell if able, but doing so costs {1}. The player is forced to spend {1} if enough mana is in his or her mana pool, but the player isn’t forced to activate a mana ability to produce that {1}. If he or she doesn’t, the card simply remains exiled.

702.61. Suspend
702.61a Suspend is a keyword that represents three abilities. The first is a static ability that functions while the card with suspend is in a player’s hand. The second and third are triggered abilities that function in the exile zone. “Suspend N—[cost]” means “If you could begin to cast this card by putting it onto the stack from your hand, you may pay [cost] and exile it with N time counters on it. This action doesn’t use the stack,” and “At the beginning of your upkeep, if
this card is suspended, remove a time counter from it,” and “When the last time counter is removed from this card, if it’s exiled, play it without paying its mana cost if able. If you can’t, it remains exiled. If you cast a creature spell this way, it gains haste until you lose control of the spell or the permanent it becomes.”
702.61b A card is “suspended” if it’s in the exile zone, has suspend, and has a time counter on it.
702.61c Casting a spell as an effect of its suspend ability follows the rules for paying alternative costs in rules 601.2b and 601.2e–g.

**Comment by melvinzhang** [comment]
it possibly "can" be done, but "should" we do it? The increase in code complexity is significant for a mechanic that is unlikely to be used again for new cards.

Some of the components is potentially useful outside of suspend. For example, "triggers from cards" is interesting, there are several cases of it occurring from the graveyard. Perhaps start with one of these first?

**Comment by melvinzhang** [comment]
Are there other cards that put counters on cards? 

Also note rule 121.2
```
121.2. Counters on an object are not retained if that object moves from                                                                                                                       
 one zone to another. The counters are not <93>removed<94>; they simply cease                                                                                                                  
 to exist. See rule 400.7.
```

**Comment by ShawnieBoy** [comment]
There are a few other cards that put counters on to cards in exile, which mimic Suspend.([Ertai's Meddling](http://magiccards.info/tp/en/61.html), [Spelljack](http://magiccards.info/ju/en/51.html), [All Hallow's Eve](http://magiccards.info/lg/en/2.html)). [Skullbriar](http://magiccards.info/cmd/en/227.html) is also a one-off special.

There are also a few cards which interact with suspend spells and time counters which themselves aren't in exile. [Clockspinning](http://magiccards.info/ts/en/53.html), [Dust of Moments](http://magiccards.info/fut/en/5.html), [Fury Charm](http://magiccards.info/mma/en/114.html)

Counters on exiled cards is probably the smallest and simplest of the Suspend part. Triggers from cards and targeting exile will enable more.

Suspend involves around 50-60 cards - but who knows what the future will bring? Transform was only 60-70 or so cards as well, and that's making a comeback.

**Comment by ShawnieBoy** [comment]
Oh, there's [Lightning Storm](http://magiccards.info/cs/en/89.html) as well, which is just a strange card really. That's putting counters on an item on the stack, lol

**Comment by melvinzhang** [comment]
suspend is 9 on the storm scale, see https://mtgcolorpie.files.wordpress.com/2012/11/storm-scale-11-25-12.png

**Comment by ShawnieBoy** [comment]
There's really no way of telling if a mechanic in the future will or will not use counters on a card in exile (or any other zone for that matter, given the list of cards from the top of my head so far).

**Comment by melvinzhang** [comment]
Coming back to the original point, I feel that we need to be mindful of the cost of these changes, and sometimes the benefit doesn't justify the cost. "Counters on cards" is one of the places where I feel the costs outweight the benefit, for example ChangeCountersAction became rather clunky having to deal with NONE cases. I'm currently working on an improvement to it.

**Comment by ShawnieBoy** [comment]
I'm sorry about that - I should have held onto it for longer before pushing that. I was working my way up to MagicObject, but wanted to try a hack-job for testing. Then realised that I'd have to look at icon rendering on cards before properly seeing effects without lots of log messages.

As far as 'costs' go: I think we've kind of got to the point now where anything new we introduce, from the list of currently unsupported cards, is going to have a large impact on the rest of the code in some way.

I feel that chipping at them occasionally would be better than it becoming a list of cards we'll never implement.

**Comment by melvinzhang** [comment]
> As far as 'costs' go: I think we've kind of got to the point now where anything new we introduce, from the list of currently unsupported cards, is going to have a large impact on the rest of the code in  some way.

I think that is a bit of an over simplification. Some things are harder and involve more work than others, mana pool will involve more work than implementing static ability for mana cost reduction for instance. It is important to pick the right one to focus on and develop a clear plan or approach before starting so as to minimize code impact.

I was under the impression this issue is for discussing the feasibility and developing the approach, which is why I was surprised to see the changes for counters on card while this discussion is on going.

**Comment by ShawnieBoy** [comment]
...I just got a bit excited.

**Comment by melvinzhang** [comment]
Suspends looks close to complete, just missing the trigger which removes the counter and the casting. I will try to finish up the last two parts.

**Comment by melvinzhang** [comment]
Didn't want to delve in to triggers on card issue, so I made a global "at upkeep" trigger that removes the time counter and when it is the last counter cast the spell.
