### ISSUE TITLE
"Preferred Selection" should not have to pay mana cost if sacrifice cannot be made

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#355]
In addition, placeholder text (SN, PN, RN) should not appear in may choice description. They can only appear in event description text.

**Comment by ShawnieBoy** [comment]
One thing I've noticed with this however, is that the player (and AI) can choose 'Yes' even if the costs cannot be paid. They won't get the effects, just looks really strange on the log

**Comment by ShawnieBoy** [comment]
I guess that could be fixed by not having a string for the MagicEvent to put onto the log, and instead use game.logAppendMessage with a message depending on the actual choice made.

**Comment by ShawnieBoy** [comment]
Looks as though the PayManaCostEvent.isSatisfied() may not be working correctly. More an observation of Mundungu than Preferred Selection. Attempting to counter an opponent's spell, the AI could just pay 1 life to prevent the counter as it had no free mana.

**Comment by melvinzhang** [comment]
Tracking as https://github.com/magarena/magarena/issues/357

**Comment by melvinzhang** [comment]
should specify the player who is doing the paying, otherwise it defaults to source.getController which is the controller of the Mundungu. fixed in https://github.com/magarena/magarena/commit/7e3737f6b7fd7bef05ab7a5ebc7b8d0436ac69f8
