### ISSUE TITLE
Snow Mana

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#367]
I've re-tried implementing this without involving color (which was where I got stuck last time I tried this) And I think I'm onto something.

I've been able to get Snow mana functioning as long as the mana ability is scripted. I've tried to implement a MagicPermanentStatic similar to the current one for basic lands, but it doesn't seem to be working. I'm wondering if they aren't compatible (I did wonder if it wasn't noticing the basic lands' mana abilities, when re-ordering them the basic land effect stopped working completely)

I'll push what I've done so far - hopefully another pair of eyes can see something I'm missing. (So far, I've not found anything effected by these changes, otherwise feel free to revert).

**Comment by ShawnieBoy** [comment]
Incorporating the PermanentStatic for snow permanents into basic land types seems to have solved this issue. Hesitant to say that this might be done. Testing please!

**Comment by ShawnieBoy** [comment]
Coldsteel Heart doesn't seem to be gaining the Snow mana static, nor do other Snow permanents that gain mana production (e.g. though Paradise Mantle).

**Comment by ShawnieBoy** [comment]
This is due to the MagicPermanent.producesMana() is looking only at the card definition.

**Comment by ShawnieBoy** [comment]
Coldsteel Heart issue fixed 20a2951e659aadba49d51bbfdb52270753fb98a4

**Comment by melvinzhang** [comment]
SnowManaEffect grants "tap: add {S}" to anything with snow type and can produce mana. But the way to produce mana may be by other means than tap, say by sacrificing itself. This is an issue if:
1. There Snow permanents that use a non tap method of generating mana.
2. There is a way to gain the type Snow on an existing non-Snow permanent.
Could either of the above happen?

**Comment by ShawnieBoy** [comment]
The second is definitely possible, which then makes the first possible. Something I hadn't considered.

**Comment by ShawnieBoy** [comment]
Would have to instead add Snow mana to the mana it can produce instead of gifting a mana producing tap ability

**Comment by melvinzhang** [comment]
The first could also happen if a Snow permanents gains a non-tap mana ability due to an effect.

**Comment by melvinzhang** [comment]
> Would have to instead add Snow mana to the mana it can produce instead of gifting a mana producing tap ability

implemented in https://github.com/magarena/magarena/commit/670ff87eadab5b180b013a6e8945e97ed6f7fdcf

**Comment by ShawnieBoy** [comment]
Nice :+1: Job done
