### ISSUE TITLE
Update look of About dialog.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#37]
@ShawnieBoy please could you post

![magarena - neutral](https://cloud.githubusercontent.com/assets/2363180/5049851/d814e6be-6c20-11e4-85f6-6bd61699cec0.png)

without the central logo. If you could actually separate the logo and the background into two images that would be great.

**Comment by melvinzhang** [comment]
The same layout issue also occurs on Linux. Either of the two versions here is much better than what we currently have. I personally prefer the first mock up with the version in the center, the second version seems a bit cluttered.

**Comment by lodici** [comment]
One of the common uses of an about box is to display author/contributors to the project. Since we now have the ability to generate proxy cards it might be fun to create a random proxy with a contributor's image (of their choice) for the art, their name in the card title bar and randomly assigned attributes elsewhere. We can then display each contributor as their very own MTG card using the flip animation to switch cards for example. Obviously not essential, but thought I would mention it. Probably best to restyle the current dialog first. :wink:

**Comment by lodici** [comment]
Finally went for a simple look consistent with the UI which has space and potential for improvements. The memory stats now update every second. Not sure where to put the license text as yet.
![screenshot00500](https://cloud.githubusercontent.com/assets/2443519/13957144/512d7b86-f043-11e5-9166-647b54818c56.jpg)

**Comment by ShawnieBoy** [comment]
:+1:

**Comment by melvinzhang** [comment]
Wow! Looks great :smile:

**Comment by lodici** [comment]
Great, with the additional license button added I think we can consider this very old issue closed.
