### ISSUE TITLE
Use log info to automatically generate a test duel.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#375]
If an exception is raised during a game the crash.log contains info similiar to the following -

```
Turn : 5  Phase : FirstMain  Step : ActivePlayer  Player : cody  Score : 796
0] Player : cody  Life : 20  Delayed : Total=0
   - Hand : Coralhelm Commander
   - Hand : Coralhelm Commander
   - Hand : Master of Waves
   - Hand : Thassa, God of the Sea
   - Hand : Island
   - Permanent : Island
   - Permanent : Island
   - Permanent : Island  Summoned
   - Permanent : Legacy's Allure
1] Player : Monty Carlo  Life : 20  Delayed : Total=0
   - Hand : Arid Mesa
   - Hand : Lightning Helix
   - Hand : Arid Mesa
   - Hand : Boros Reckoner
   - Hand : Rageblood Shaman
   - Hand : Lightning Helix
   - Graveyard : Minotaur Explorer
   - Permanent : Mountain  Tapped  Summoned
   - Permanent : Plateau  Tapped
```

Presumably this is so a test case can be created in order to try an replicate the issue. But instead of having to manually create the test class why not copy and paste the above info and let Magarena automatically create and run the test duel for you.

Alternatively, it could automatically generate the test class. Create a template text file and then fill in the blanks with info from the log as shown.

**Comment by melvinzhang** [comment]
we now have a game snapshot format, this issue is superceeded by https://github.com/magarena/magarena/issues/627
