### ISSUE TITLE
Examine loading cube/custom format definitions on demand.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#382]
Although not such a big deal now that the Vintage, Standard, et al ```_cube.txt``` files have been removed I still see no reason why even custom formats need to be loaded at startup and retained in memory, in the same way that the complete collection of prebuilt deck files are not loaded. Should only need to load the active card pool while running a duel. Based on point 5 in #311.

**Comment by melvinzhang** [comment]
Load each format as needed, using the same technique as MagicPredefinedFormat, when getCardLegality is called. Implemented in https://github.com/magarena/magarena/commit/5324f287f27d488d799e7a34d2fd3772e11530ae
