### ISSUE TITLE
Crash when unable to find icon for {n} where n >= 17

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#383]
Extracted from https://github.com/magarena/magarena/issues/374#issuecomment-114263830
```
AddEventAction (EVENT: Thassa's Rebuff You may$ pay {17}$. If you don't, counter Rancor. Pay {17}?) = 0
MoveCardAction (Thassa's Rebuff,Stack,Graveyard) = 0 Score = 11260
Exception from controller.runGame: No corresponding icon for {17}
java.lang.RuntimeException: No corresponding icon for {17}
at magic.data.TextImages.getIcon(TextImages.java:81)
at magic.ui.widget.TextLabel.buildComponent(TextLabel.java:80)
at magic.ui.widget.TextLabel.buildComponents(TextLabel.java:109)
at magic.ui.widget.TextLabel.(TextLabel.java:57)
at magic.ui.duel.viewer.UserActionPanel.showMessage(UserActionPanel.java:140)
at magic.ui.SwingGameController$10.run(SwingGameController.java:541)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
```

**Comment by ShawnieBoy** [comment]
This is more of an incremental issue, no matter what the maximum number we add for colorless mana icons, there's always going to be a number one higher. Would need to create these dynamically to prevent all possible crashes.

**Comment by melvinzhang** [comment]
another option is to show images if we have, else show text

**Comment by ShawnieBoy** [comment]
True enough, the Mana sheet we have goes up to 20 consecutively, then also has 100, 1,000,000 and infinity. I can add those (Maybe not infinity, something must be going very strange for that :wink: )

**Comment by lodici** [comment]
The colorless mana symbol is simple - a filled grey circle with a text overlay. It should be fairly straightforward to create the image dynamically. A similar thing was done with the poison and shield counters on the player avatar,
