### ISSUE TITLE
when cycling Ichor Slick with sufficient to pay for madness, madness cost is paid before cycling cost

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#385]
The player should finish paying for the cycling cost before dealing with the madness trigger.

Stack trace of the bug:
```
1007. DrawAction = 410
1008. AddEventAction (EVENT: NONE  ...) = 0
1009. ExecuteFirstEventAction = 0
1010. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
1011. ExecuteFirstEventAction = 0
1012. DiscardCardAction = -271
1013. MoveCardAction (Ichor Slick,OwnersHand,Exile) = 0
1014. AddEventAction (EVENT: Ichor Slick MMABC may$ cast Ichor Slick for its madness cost instead of putting it into his or her graveyard. Cast for its madness cost?) = 0
1015. AddEventAction (EVENT: Ichor Slick Pay {2}$. Choose how to pay the mana cost.) = 0
1016. AddEventAction (EVENT: Ichor Slick Cycle Ichor Slick. ) = 0
1017. ExecuteFirstEventAction = 0
1018. TapAction (Swamp) = -5
1019. TapAction (Swamp) = -5
1020. TapAction (Swamp) = -5
1021. TapAction (Swamp) = -5
1022. RemoveCardAction (Ichor Slick) = 0
1023. PutItemOnStackAction (MagicCardOnStack,Ichor Slick) = -1
1024. AddEventAction (EVENT: Ichor Slick  Choose Target creature.) = 0
1025. AddEventAction (EVENT: Ichor Slick  ) = 0
Score = 1917

Exception from controller.runGame: no artificial choice result for EVENT: Ichor Slick Pay {2}$. Choose how to pay the mana cost.
java.lang.RuntimeException: no artificial choice result for EVENT: Ichor Slick Pay {2}$. Choose how to pay the mana cost.
        at magic.model.choice.MagicChoice.getArtificialChoiceResults(MagicChoice.java:88)
        at magic.model.event.MagicEvent.getArtificialChoiceResults(MagicEvent.java:402)
        at magic.ai.MMAB.findNextEventChoiceResults(MMAB.java:47)
        at magic.headless.HeadlessGameController.getAIChoiceResults(HeadlessGameController.java:50)
        at magic.headless.HeadlessGameController.runGame(HeadlessGameController.java:33)
        at magic.DeckStrCal.runDuel(DeckStrCal.java:202)
        at magic.DeckStrCal.main(DeckStrCal.java:175)
```

**Comment by lodici** [comment]
see also [failed Jenkins build #1503](https://buildhive.cloudbees.com/job/magarena/job/magarena/1503/console).

**Comment by lodici** [comment]
also [failed Jenkins build #1508](https://buildhive.cloudbees.com/job/magarena/job/magarena/1508/consoleText). Perhaps move Ichor Slick to ``incomplete``?

**Comment by ShawnieBoy** [comment]
The problem would be for decks which already have the card in a deck - however with the deckbuilder no longer crashing with invalid decks, maybe this would then be a possibility.

Not sure what impact it would have on firemind - Though thinking about it, it would be preventing crashes.

I'd say to move Ichor Slick to incomplete - There was another card causing problems too, but I can't remember the name.

What do you think @melvinzhang ?

**Comment by lodici** [comment]
> There was another card causing problems too, but I can't remember the name.

I added the link to the #1503 build above because the error was the same but was actually caused by ``Foul Familiar``.

**Comment by melvinzhang** [comment]
There is nothing wrong with these cards, they  expose bugs in the game
engine. We should fix the game engine, not remove the cards.

**Comment by lodici** [comment]
> An analogy is say if attacking with first strike causes the program to crash, do we remove all cards with the first strike ability or fix the implementation of first strike?

Yes, I think we should remove all cards if it occurs frequently enough and is proving difficult to fix.

**Comment by melvinzhang** [comment]
> I always thought the onus was on quality not quantity in terms of AI compatability
Yes, but that is when considering which cards to add. Once added we try not to remove cards as it annoys users. Eg. when a working deck becomes unplayable without a key card.

**Comment by melvinzhang** [comment]
The fix for this bug is to finish paying for the cycling cost before dealing with the madness trigger.

**Comment by melvinzhang** [comment]
This bug is not particular to madness and cycling. It occurs when there is an optional trigger with a mana cost that triggers on discard and an activated ability with discard as one of the cost. There are other such combinations besides Ichor Slick but they are much harder to occur in randomize decks. Ichor Slick happens to be one card with both abilities.

**Comment by lodici** [comment]
> Once added we try not to remove cards as it annoys users.

And a game crashing because of a dodgy card won't?

> It seems that there is a perception that this bug is difficult to fix.

I came to that conclusion since it has been open for almost a month now. I have focused on this simply because it was preventing builds from completing although more recently it is has not occurred with timeouts and java heap space errors the norm.

**Comment by melvinzhang** [comment]
> And a game crashing because of a dodgy card won't?
Sure it does, that why I created this issue.

Instead of comparing a proposed solution (remove the card) with the bug. I find it more useful to compare the two proposed solutions.

1) remove the card
pro: the card no longer causes a crash
con: does not fix the underlying problem between discard trigger and discard cost, future cards and other combination of cards can still trigger this bug, removal of cards is annoying to users who play it

2) fix the bad interaction between discard trigger and discard cost
pro: fixes this card and other combination of cards (present and future) that has discard trigger or discard cost
con: require changing the Java code

**Comment by lodici** [comment]
I don't think it as black and white as this, all or nothing. In this particular case, with this particular card which caused a number of builds to fail I don't see why it could not be temporarily taken offline during the development cycle. Re-instate before a release by all means, but it is very frustrating when a build keeps falling over for the same reason and there does not seem to be any rush to address the issue. If a change I made caused the build to fall over I would drop everything to fix it or rollback the commit.

**Comment by melvinzhang** [comment]
I see, you meant remove the card temporarily. I'm ok with that. My impression was that the suggestion is to remove the card and consider this closed without fixing the underlying issue.

In any case, it would be too late to consider a temporarily removal now as the release is planned to be this weekend.

**Comment by lodici** [comment]
Sorry, I should have been clearer - I guess my beef was more with how the AI testing code regularly causes the build to fail but which is usually completely unrelated to the commits that triggered the build in the first place. This particular issue just happened to focus my ire.
