### ISSUE TITLE
Launch4j Update

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#389]
Launch4j wraps the jar such that it is not accessible using reflection which means the translation mechanism is unable to discover classes with translatable strings. It also prevents the restart option.

Is there any reason why we cannot update ``magarena.xml`` so that  
```
<dontWrapJar>false</dontWrapJar>
``` 
is changed to 
```
<dontWrapJar>true</dontWrapJar>
```
and the exe becomes a simple launcher to ``Magarena.jar``. It would also mean updating the ``sh`` and ``command`` launchers to point to the jar instead of the exe.

**Comment by lodici** [comment]
Thanks @melvinzhang.  With this [simple instruction](https://github.com/magarena/magarena/issues/388#issuecomment-117891058) I was able to replicate locally the build artifacts as generated by the CI server but without the extra 80 minute wait. This in turn meant I was able to properly test the above fix for the automatic creation of a translation file.

**Comment by melvinzhang** [comment]
by "not accessible using reflection" is there a specific example of where a reflection call would fail with the exe

**Comment by lodici** [comment]
see https://github.com/magarena/magarena/issues/387#issuecomment-117841895 onwards.

**Comment by melvinzhang** [comment]
When using the exe, I could open the translation file without errors but it is empty. Making it be a wrapper is probably the best solution. There was some confusion in the past about the exe being a jar. Now the exe is like the .sh and .command file, which is more consistent and the jar is just .jar Thanks for the fix.
