### ISSUE TITLE
restart Magarena works ok on Windows and Linux (with one exception)

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#390]
extracted from https://github.com/magarena/magarena/issues/387#issue-92438379
 
@lodici What's the exception?

**Comment by lodici** [comment]
![screenshot00184](https://cloud.githubusercontent.com/assets/2443519/8470483/cb342c4e-2083-11e5-8c87-cfe843356d7d.png)
If I click Run it restarts fine but Run in Terminal does not restart. If I run directly from a terminal using ``java -jar...`` it restarts ok as well.

**Comment by melvinzhang** [comment]
"does not restart" as in nothing happens? Btw, how do you trigger a restart?

**Comment by lodici** [comment]
> "does not restart" as in nothing happens?

Well once I saw the splash screen briefly flicker into existence before disappearing.


> Btw, how do you trigger a restart?

See [restart() in MagicSystem](https://github.com/magarena/magarena/blob/master/src/magic/utility/MagicSystem.java#L207)

**Comment by lodici** [comment]
Eventually, I was able to avoid using a restart, although I have left the code in as it may be useful in future. So as this is not an _active_ issue anymore I recommend closing although @melvinzhang might still want to investigate further.
