### ISSUE TITLE
The order of events for Oracle's Insight is wrong.

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#396]
Submitter: sponeta
The order of events for Oracle's Insight is wrong. The card text says "Scry 1, then draw a card", but in game it happens the other way around.

**Comment by Dozar** [comment]
I'm new to the repo, would anyone mind pointing me in the direction of the file from which these events take place?

**Comment by melvinzhang** [comment]
These are built-in effects, as the card has no groovy code. So they are implemented in src/magic/model/event/MagicRuleEventAction.java Scry is from line 1723 "Scry1" and Drawing is from line 675 "Draw".

The key issue is the scry is implement as an event because it requires a decision which means it goes into the event queue and occurs after the card resolves. While draw is implemented as an action so it takes place immediately. One way to fix this would be to change the DrawAction to a MagicDrawEvent.

**Comment by melvinzhang** [comment]
duplicate of #205
