### ISSUE TITLE
AI will use Echoes of the Kin Tree to bolster even if it doesn't have any creatures in play.

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#399]
Submitter: sponeta
AI will use Echoes of the Kin Tree to bolster even if it doesn't have any creatures in play.

**Comment by ShawnieBoy** [comment]
An  'Activate this ability with AI only if you control a creature' will fix this card.
It could be put onto the Bolster ability itself to catch other non-creature activated sources. Or even as a restriction for the player as well, as the effect will be redundant if you control no creatures.
