### ISSUE TITLE
The Seeker of Skybreak card working with an error

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#405]
Submitter: Dan
Email: dan_noune@yahoo.com
The Seeker of Skybreak card working with an error. Special skill (Untap target creature) works on this card cyclically. Even if there is another card to untap. This happens when you play with minimax. Sometimes after 4-5 cycles of tap-untap AI doing something else. But mostly, the cycle is repeated continuously.

**Comment by ShawnieBoy** [comment]
Is this covered by the maximum activation limit for the AI?

**Comment by melvinzhang** [comment]
yes, there is a AI constraint "Activate this ability with AI no more than three times each turn.", there could be a bug in enforcing the limit.

Alternative, perhaps it would be better to rephrase the ability as "Untap another target creature."?

**Comment by ShawnieBoy** [comment]
Being able to untap itself is a valid use to get multiple triggers from "when becomes tapped" effects. Wouldn't want to remove that function.

**Comment by ShawnieBoy** [comment]
Still testing, but it seems that it's mainly used to untap creatures that are already untapped...

**Comment by melvinzhang** [comment]
not reproducible
