### ISSUE TITLE
Warstorm Surge doesn't seem to work

### ISSUE THREAD

**Issue by itandetnik** [magarena/magarena#415]
Computer has Warstorm Surge in play, and casts Zhur-Taa Swine, directing damage to one of my creatures. There's nothing fancy in play that would prevent damage (for completeness, I have Growing Ranks enchantment; apart from that, it's just run-of-the-mill creatures and lands).

Expected: the target creature is dealt 5 damage. Actual: the creature is dealt 0 damage.

From the log:

> (C): Pay {1}{G}. Tap Forest. Tap Mountain. Play Nature's Spiral.
(C): Return target permanent card from Computer's graveyard to Computer's hand. (Zhur-Taa Swine)
(C): Pay {3}{R}{G}. Tap Forest. Tap Copperline Gorge. Tap Stomping Ground. Tap Stomping Ground. Tap Stomping Ground. Play Zhur-Taa Swine.
(C): Put Zhur-Taa Swine onto the battlefield.
(C): Zhur-Taa Swine deals damage equal to its power to target creature or player. (Gravetiller Wurm) (0)

**Comment by ShawnieBoy** [comment]
Looks like there's some problems since it's had it's Groovy removed: e30dd21ffbd2b2e98d2962b9a165f10f149a37f4

I'm assuming that the java code is dealing damage equal to "it's" power (ie. Warstorm Surge's power) to the target.

**Comment by ShawnieBoy** [comment]
MagicAmountParser requires an RN reference for other permanent's power/values.
Reverted Warstorm Surge to use groovy.

**Comment by itandetnik** [comment]
Looking at the change you referenced, `Stalking Vengeance` seems like it might have the same problem (using `Stalking Vengeance`'s power, not the dying creature).

**Comment by ShawnieBoy** [comment]
Was my next task :+1: 
It's functioning the same, it will deal damage equal to Stalking Vengeance's power, not the dying creature. Will revert that one as well for now - Hopefully @melvinzhang will be able to work some magic with the references here. :grin: 

Thanks for picking this up!
