### ISSUE TITLE
Point to language specific version of Keywords.txt if available.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#417]
There is now a [russian translation available in the forums](http://www.slightlymagic.net/forum/viewtopic.php?f=82&t=17489&p=183670#p183668).

**Comment by PalladiaMors** [comment]
I've downloaded the latest build and tried to find the keywords file in order to translate it, but couldn't locate it in the Magarena folder. The file in the forums is in Russian which unfortunately isn't one of my greatest skills (well I confess I've tried to sing the Katyusha on occasion and found out that's a pretty good way to evacuate a room, for some reason). Where can I find the file in English?

**Comment by lodici** [comment]
Good point. The [``keywords.txt``](https://github.com/magarena/magarena/blob/master/resources/magic/data/keywords.txt) file is currently built into the ``jar`` file which means you need access to the source code. 

To make translation easier and with an eye on future work I think it might be useful to update the [``translations`` folder](https://github.com/magarena/magarena/tree/master/release/Magarena/translations) to contain sub-folders for each translation - ``translations\Português``, ``translations\Русский``, etc. The folder name is used in the 'language' selector and the folder itself contains the UI strings file and optionally a ``keywords.txt`` file that overrides the default.

**Comment by lodici** [comment]
I decided to go for the easy option and just slightly tweak the existing code. The keyword files are still stored in the jar but have now been given their own [folder](https://github.com/magarena/magarena/tree/master/resources/magic/data/keywords). Simply add the translated file with exactly the same name as the file used in the [``translations``](https://github.com/magarena/magarena/tree/master/release/Magarena/translations) folder to override the default English version.

**Comment by PalladiaMors** [comment]
Not sure if this is the proper place to mention this, but the build queue has been stuck for over three days...

**Comment by lodici** [comment]
I sent them a message and they have raised [an issue.](https://cloudbees.zendesk.com/hc/en-us/requests/28496) - they don't seem to be aware that there is a problem.

**Comment by lodici** [comment]
Implemented (and Jenkins have also sorted themselves out as well!).
