### ISSUE TITLE
Use language-specific version of card image.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#418]
See [forum post from @ShawnieBoy](http://www.slightlymagic.net/forum/viewtopic.php?f=82&t=17489&p=183670#p183667).

> There could be a simpler solution:
> 
> Having a look at magiccards.info they are thankfully well structured for other languages. Having an option on the downloads for different languages, and then a string replacement from the script file for "/en/" to the chosen language:
> 
> Grabbing an image file at random - Scion of Ugin
> 
> http://magiccards.info/scans/en/dtk/1.jpg
> http://magiccards.info/scans/de/dtk/1.jpg
> http://magiccards.info/scans/ru/dtk/1.jpg
> 
> For some of the earlier sets this may not match as well due to some translations not existing (at a guess).
> 
> If a non-English language is chosen I would assume that also having an English version may not be required so could replace the English versions as the filenames will be the same.
> 
> (Also scaring me with the side-project of in-game created cards!)

**Comment by lodici** [comment]
Ok, is the following pseudo code what you are getting at? Assume I am using the Russian UI...

- if the download url pulled from the card script is ``magiccards.info`` then
  - replace the ``/en/`` part of the url with ``/ru/``.
  - attempt to download, if fail then down original ``en`` edition instead.

This is doable but I think the results could be very patchy. The first three cards I randomly selected ( [Æther Membrane](http://magiccards.info/scans/en/ddi/48.jpg), [Pelakka Wurm](http://magiccards.info/scans/en/cns/172.jpg) and [Fault Riders](http://magiccards.info/scans/en/pr/88.jpg)) would all have failed to download the appropriate translation - they do exist but with different numbers and/or edition codes.

**Comment by lodici** [comment]
I did some [tests on 100 cards](https://gist.github.com/lodici/b31fe154445a0bd06a66) for ``ru (russian)``, ``pt (portuguese)`` and ``de (german)``. The results were poor to say the least with ``pt`` having a 70% fail rate, ``ru`` 68% and ``de`` 43%.

**Comment by lodici** [comment]
Tried with [1000 cards for ``ru``](https://gist.github.com/lodici/d59642d897cc55b7f5f2) - 63% fail rate.

**Comment by lodici** [comment]
Of course it is better than nothing I guess.

**Comment by ShawnieBoy** [comment]
Sorry PC inoperative at the moment.

The fail rate is most likely due to using the most recent versions of card printings. Some editions/special sets may not have translations. I'm thinking the Duel Deck series and probably Commander, Planechase and Archenemy - There's probably going to be gaps with older cards that haven't been printed in particular languages as well.

**Comment by lodici** [comment]
Can download non-english card images so I think this can be closed.

**Comment by ShawnieBoy** [comment]
Would be interesting to see how the stats improve once I've completed re-parsing all the scripts files (I sure hope they improve! Not a small job)
