### ISSUE TITLE
Mulligan event not shown in log when starting second duel

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#420]
split out from #419 

Lodici wrote
Start a duel and at earliest opportunity return back to main menu. Start next duel. Mulligan down to three cards. It does not display your mulligan steps in the log. It is related to layout - for some reason the scrollpane is not sized correctly in this case.

Melvin wrote
I'm unable to replicate the edge case.

My steps were:
1. New duel
2. Next ->
3. Game 1 ->
4. Play this hand ->
5. Hit esc, select quit to main menu
6. New duel
7. Next ->
8. Game 1 ->
9. Mulligan down to 3 cards
10. Play this hand ->

Log shows two entries with Player and AI mulligan choices.

Lodici wrote
That is correct - I am still able to replicate at will. Strange.

**Comment by lodici** [comment]
dcacd6e3924f69d90da33e02044dbd9a60b3595b seems to have fixed it. Good job.
