### ISSUE TITLE
Call of the Herd doesn't exile after playing flashback

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#422]
raised by kannikkiy in [forum](http://www.slightlymagic.net/forum/viewtopic.php?f=82&t=17490&p=184354&sid=09fbb0f886879abbab010e7f936824e6#p184222).

**Comment by ShawnieBoy** [comment]
Created TestFlashback for testing, possible user update problem

**Comment by ShawnieBoy** [comment]
confirmed version mix
