### ISSUE TITLE
drop support for Java 7, compile with Java 8

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#429]

**Comment by lodici** [comment]
Since this a major change perhaps update to version 2 also which I think would be clearer to end users.

**Comment by melvinzhang** [comment]
I'd rather save 2.0 for a major upgrade to the application's behavior/functionality, such as rendered card images. I see this more of as a technical upgrade to keep up with the times rather than a major breaking change. Java 8 has been released since March 2014, and promoted as the official version on java.com since October 2014.

**Comment by melvinzhang** [comment]
Perhaps a two stage process for this will be better in inform the users ahead of time. So in 1.66, we include a notification button (similar to the download images button) to warn users on Java 7 that next version will no longer support Java 7 and they are encouraged to upgrade. The in 1.67 we actually drop Java 7 support.

**Comment by lodici** [comment]
That would be better - only show the alert if ``System.getProperty("java.version")`` is less than 1.8. On clicking the alert button display a simple message box with suitable explanation. 

Also we should include a similar reminder on the the main webpage and forum.

**Comment by lodici** [comment]
I have added an alert button that will be displayed at startup if the version of java running Magarena is less than 1.8.

**Comment by melvinzhang** [comment]
Awesome, thanks!

**Comment by lodici** [comment]
When do you think we will be able to start using 1.8 features? I am guessing you will need to update the Jenkins build first.

**Comment by melvinzhang** [comment]
@lodici there is no configuration to select java version in buildhive. From report on https://odoepner.wordpress.com/2015/02/15/build-java-maven-github-project-on-travis-ci/ it looks like buildhive does not support Java 8

**Comment by lodici** [comment]
That is a bit of a fly in the ointment! I had a quick look at travis when we were having problems with Jenkins - the main drawback I could see was that it does not handle the management of artifacts. Looks like #448 may be the way to go - presumably no more CI or dev builds though.

**Comment by melvinzhang** [comment]
Running the self test takes quite a bit of time, would be good to off load this to a hosted service. Investigating the CI issue in https://github.com/magarena/magarena/issues/449

**Comment by melvinzhang** [comment]
1.67 requires Java 8
