### ISSUE TITLE
Magarena branded back-face design

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#430]
I think it would be better to have a design for the card back-face that is unique to Magarena. Currently this would be displayed when a card is morphed. Here are a couple of ideas -
![magarena-card-back](https://cloud.githubusercontent.com/assets/2443519/9703322/f3c1d594-5477-11e5-9afd-673c3b95d1f9.png)
![magarena-card-back-red](https://cloud.githubusercontent.com/assets/2443519/9703325/00c700fc-5478-11e5-8a97-59e31eddbc4c.png)

**Comment by ShawnieBoy** [comment]
Nice, I like them!
However there's already images we can use for morph and manifest cards:  
![morph](http://magiccards.info/extras/token/dragons-of-tarkir/morph.jpg)
![manifest](http://magiccards.info/extras/token/fate-reforged/manifest.jpg)

I can see the Magarena backs fitting well with ui themes too

**Comment by lodici** [comment]
Currently the only situation where the back-face is shown is morph. If the "morph" image is shown instead then there would actually be no need for a back-face image at all. A card flip animation is the only case I can think of where you would need the back-face but that is not implemented yet.

**Comment by ShawnieBoy** [comment]
I was also thinking of the deck back shown as a pile of face-down cards, as seen in other card games.

One interesting note from the Morph and Manifest card backs is that it also serves as a good reminder for the opponent from where the cards originated. Face-down cards should always remain identifiable as in the order they entered the battlefield, this also adds the source (from the deck for manifest, from play/the hand for morph)

**Comment by melvinzhang** [comment]
commit 63c0b082afddf1dffee2447fbb018230c5cf1f7b adds Morph and Manifest overlay for face-down cards

**Comment by ShawnieBoy** [comment]
>commit 63c0b08 adds Morph and Manifest overlay for face-down cards

Cool, thanks.

Another area where face down cards can occur, which isn't currently implemented as far as I know, is face-down in exile. These could use the custom card-backs. (Also possibly face-down 'piles' in exile e.g.. Parallel Thoughts)

**Comment by lodici** [comment]
I think the new morph/manifest overlays may be potentially confusing since the size they are displayed on the battlefield means they are essentially unreadable yet look similar to other playable cards.
![screenshot00289](https://cloud.githubusercontent.com/assets/2443519/9809526/eabb6aa4-5860-11e5-97d1-52d3004c77c2.png)
I still think it would be clearer to have a distinct back-face with for example some sort of symbol that clearly identifies the card as morph/manifest and which scales to the smaller images better.

**Comment by ShawnieBoy** [comment]
The Morph/Manifest would be more for your opponent's cards. If you had cast a manifest card, or had a morph creature you would know. Zooming in on an opponent's morph card for example would show the overlay, and also be able to distinguish between manifest and morph which work differently.

There's a change a Manifest creature could be turned into a creature (it may just be a face-down land), but it's definite with morph.

**Comment by lodici** [comment]
Shot down in flames :boom:

**Comment by ShawnieBoy** [comment]
😢 Still has potential once 'exile face down' and 'face down piles' are implemented
