### ISSUE TITLE
Altar of Bone - sacrifice a creature, not logged.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#436]
When I played [Alter of Bone](http://gatherer.wizards.com/Pages/Card/Details.aspx?printed=true&name=altar%20of%20bone) and sacrificed Grizzly Bears it does not log what was sacrificed
![screenshot00299](https://cloud.githubusercontent.com/assets/2443519/9975593/f7254036-5eb8-11e5-896d-6e8151d524c0.png)
Would that not be useful to know (eg. ``Play Altar of Bone, sacrifice Grizzly Bears.``)?

**Comment by ShawnieBoy** [comment]
Yes it should be logged really as the sacrifice is an additional cost. It should appear after the mana has been paid, and before 'Play Altar of Bone' eg.

>Tap **Forest**. Tap **Plains**. Pay {G}{W}. Sacrifice **Grizzly Bears**. Play **Altar of Bone**

**Comment by ShawnieBoy** [comment]
Or displayed as:
>Sacrifice a creature **(Grizzly Bears)**

**Comment by lodici** [comment]
Thanks, I prefer your first suggestion since as you say the sacrifice is a cost. Not really my area of expertise but I just thought I would flag it.

**Comment by ShawnieBoy** [comment]
I thought it would be clearer to explain what was being sacrificed more clearly, in cases where the additional cost is '...sacrifice an Artifact or Creature' for example, but probably not overly necessary.

I'm not entirely sure where the messages are generated for displaying costs after having a quick look at the most likely places. And MagicCostEvent looks more like messages to the caster, not the log. Hopefully @melvinzhang may be able to append this.

**Comment by melvinzhang** [comment]
Bug is in MagicRepeatedPermanentsEvent, the first sacrifice event has an empty description.
