### ISSUE TITLE
Playing Mox Emerald creates two log entries.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#437]
![screenshot00304](https://cloud.githubusercontent.com/assets/2443519/9982057/fd71f7a4-5fc6-11e5-9c0e-0f25f2d26b07.png)
Note, how __Mountain__ and __Rupture Spire__ use a single entry.

**Comment by ShawnieBoy** [comment]
I think this is due to the fact that you can respond to Mox Emerald as it is a spell being cast, so it waits on the stack before entering the battlefield. However with lands, they cannot be responded to, so enter the battlefield straight away.

**Comment by lodici** [comment]
Right I see, thanks.
