### ISSUE TITLE
Slightly strange log message with Buyback.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#438]
![screenshot00305](https://cloud.githubusercontent.com/assets/2443519/9986590/465ac47c-6036-11e5-906f-d75235c7336a.png)

**Comment by ShawnieBoy** [comment]
Looks like this is a result of 4fd9562473f92d57cae7271865f49a43f5f6e9fd 
I think it was due to the ordering of the effects, the buyback was occurring before the spell effect itself. In that case the extra Buyback effect shouldn't be logging if it's not boughtback(?).

**Comment by melvinzhang** [comment]
Buyback is implemented as a second effect in MagicRuleEventAction, hence it is part of the text of the card effect. Perhaps change it to the full text instead of just the keyword? eg "Last Vegas draws a card. If the buyback cost was paid, put this card into your hand as it resolves"

**Comment by ShawnieBoy** [comment]
That is one option, I'd kinda prefer it not to be referenced if the buyback hasn't been paid. So if Whispers of the Muse -is- boughtback it would say.

> PN draws a card. SN is put into PN's hand.

otherwise

> PN draws a card.

**Comment by melvinzhang** [comment]
I'd prefer that too, could not figure out to get it that way.

**Comment by ShawnieBoy** [comment]
Maybe a separate log message?

> PN draws a card. If the buyback cost was paid, put this card into his or her hand as it resolves.
> SN is put into PN's hand.

**Comment by melvinzhang** [comment]
The main problem is how to cause the buyback logic to run. It is now in MagicRuleEventAction, hence the need to have some text in the "effect" property to trigger this code to run.

**Comment by lodici** [comment]
> Last Vegas draws a card. If the buyback cost was paid, put this card...

I find that very confusing (not difficult!). I read this as "this card" referring to the card that Les Vegas has drawn. Instead of "this card" could you insert SN so that it becomes "Last Vegas draws a card. If the buyback cost was paid, put Whispers of the Muse into your hand as it resolves."

**Comment by melvinzhang** [comment]
> Instead of "this card" could you insert SN
Good suggestion! Just ran an quick test, it works as expected and it is indeed clearer.

**Comment by melvinzhang** [comment]
@ShawnieBoy any ideas how the buyback logic (check if paid and move card) can be triggered besides putting it as part of the "effect"? If not, we'll go with the rephrase for now.

**Comment by melvinzhang** [comment]
Just realized the Entwine trick may be applicable here, giving it a shot now.

**Comment by lodici** [comment]
Looks good
![screenshot00309](https://cloud.githubusercontent.com/assets/2443519/9994672/4bac930c-6076-11e5-95a1-f508a3586a36.png)

... except to me it would make more sense as -  _Tap Island. Pay {U}. Play Whispers of the Muse. Player may (yes) pay the buyback cost. Tap Island. Tap Island. Tap Island. Tap Island. Tap Island. Pay {5}._ 

or 

_Tap Island. Pay {U}. Play Whispers of the Muse. Player may (no) pay the buyback cost._

**Comment by ShawnieBoy** [comment]
Sorry I didn't reply earlier - Looks like the solution works well :)

@lodici The choice on whether or not to pay the buyback cost is made before the card is played, so the 'Play Whispers of the Muse' would always come last - once all decisions on how to play the card are made and paid for.
In a real-life game this wouldn't really be considered, as long as everyone knew what was going on!

**Comment by lodici** [comment]
Thanks I understand, payment is all or nothing.
