### ISSUE TITLE
libpng warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#439]
After upgrading to Java 1.8.0_60 everything works fine except when I exit Magarena the console displays the following warning - 
```
libpng warning: iCCP: known incorrect sRGB profile
```

**Comment by lodici** [comment]
It turns out the culprit is the splash screen (splash.png). I ran this through [pngcrush](http://pmt.sourceforge.net/pngcrush/) to fix using the following command -
```
pngcrush -rem allb -brute -reduce splash.png splash-crushed.png
```
see also https://perishablepress.com/png-image-optimization/.

**Comment by ShawnieBoy** [comment]
Thank you! I've been trying to work out where this was coming from - I first noticed it while working on the card rendering but the profiles for those were all ok (As far as I can tell).

**Comment by lodici** [comment]
A bit of a weird one since it was not being generated in 1.8.0_25. At some point it will probably be worth running all the pngs through pngcrush so they are all running at optimal size and efficiency.

**Comment by ShawnieBoy** [comment]
A handy batch program for windows [PNGGauntlet](pnggauntlet.com) which I've just tested with the card frames and the icons. Some good size reductions on some files.
