### ISSUE TITLE
Vertical scrollbar thumb missing when running under Java 1.8.0_60

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#440]
Vertical scrollbar thumb has gone missing although scrolling still works. This happens when running 1.65 using 1.8 JRE or running latest dev build compiled using 1.8. This is on Windows 7.
![screenshot00308](https://cloud.githubusercontent.com/assets/2443519/9992292/fad9c380-6068-11e5-82ac-b2f4d3699933.png)

**Comment by lodici** [comment]
Also from issue #319, highlight in legality table is now gray.

![Legality table highlight](https://cloud.githubusercontent.com/assets/2443519/7937600/d7ff8e58-0938-11e5-9c44-765b739f23f7.png)

**Comment by lodici** [comment]
> Vertical scrollbar thumb has gone missing

Actually it is not missing, its invisible. If you manage to click and drag where it is located then scrolling works as if it was visible.

**Comment by lodici** [comment]
https://bugs.openjdk.java.net/browse/JDK-8134828

**Comment by lodici** [comment]
From the above links the current solution seems to be to revert to an earlier version so I have installed 1.8.0_51 and the scrollbar is back to normal.

**Comment by lodici** [comment]
For the change in the JList selection color
- https://bugs.openjdk.java.net/browse/JDK-8057791
- https://stackoverflow.com/questions/25685269/wrong-colors-in-jlist-when-using-nimbus-and-java-8u20

**Comment by lodici** [comment]
Looks like this has been fixed in [update 8u72](http://www.oracle.com/technetwork/java/javase/8u72-bugfixes-2775805.html). Need to test on Windows but it is back in Linux.

**Comment by ShawnieBoy** [comment]
Ok, time to update :+1:

**Comment by lodici** [comment]
I reverted back to 8u51 when this happened - I will wait to see how you get on then before updating. :smiling_imp:

**Comment by ShawnieBoy** [comment]
*sigh* Would help updating to 8u72 instead of 71...

**Comment by ShawnieBoy** [comment]
Must have forgot or blanked my memory of how annoying updating is...

**Comment by ShawnieBoy** [comment]
Ok, all done - and the little vertical friend is back

**Comment by lodici** [comment]
Same here.
