### ISSUE TITLE
pressing "space" to advance the game stops working after clicking on "log style" icon 

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#444]
Steps to replicate:
1. Start TestCounterFlash
2. Click on "log style icon" to change the log style
3. Press "Space" to skip priority

Expected:
pressing the keyboard shortcut "Space" passes priority

What happened:
pressing "Space" cycles through the log styles

System:
Linux, Java 1.7, Magarena @ 7047bc72

**Comment by melvinzhang** [comment]
@lodici the new "log style" is capturing the keyboard input, prevents keyboard shortcut from working

**Comment by lodici** [comment]
Thanks, good testing.
