### ISSUE TITLE
Replace splash.png with splash.jpg

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#445]
We can replace splash.png (216KB) with splash.jpg (39KB) since transparency is not an issue. There is no discernible loss in quality that I can see and anyway it is only displayed for a brief period. @melvinzhang please can you confirm what config files need to be updated - I have updated "build.xml". Is there anything else?

**Comment by melvinzhang** [comment]
```
% grep "splash.png" -r .  
./src/magic/MagicMain.java:     * Can override with custom splash by placing "splash.png" in mods folder.
./src/magic/MagicMain.java:                final File splashFile = MagicFileSystem.getDataPath(DataPath.MODS).resolve("splash.png").toFile();
```

**Comment by lodici** [comment]
Thanks, this lets you replace the splash image if you wish. I think it was added when we were playing around with new splash images.
