### ISSUE TITLE
commit source of splash.jpg to repo

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#450]
The current splash screen we have is fairly low res (540x280) and merged into a single layer of pixels. I presume this image is generated from a program in a higher resolution format and in several layers. If so, could we also have the source of the image in the repo so that modifications to the splash image can be made in the future.

**Comment by melvinzhang** [comment]
@lodici do you know more about the origin of the splash image?

**Comment by ShawnieBoy** [comment]
I made it - I'll have a quick rummage to see if I still have the original psd file

**Comment by ShawnieBoy** [comment]
I still have it - The original is still 540x280, I think due to match the size of the original splash - @lodici has recently compressed it into a jpg from the png.

**Comment by melvinzhang** [comment]
@ShawnieBoy thanks, good to have the original file. The size is fine, I'm more concerned about the ability to make modifications. Without the source, will have to redo it from scratch or do some messy pixel editing.

**Comment by ShawnieBoy** [comment]
There's all the colors of magic in there - we were considering a random one each load.
