### ISSUE TITLE
Light of Day effecting creatures with protection from black

### ISSUE THREAD

**Issue by Blankamen** [magarena/magarena#451]
Creatures whit protection from black is affected from Light of Day card. (Ex: Auriok Champion)

**Comment by ShawnieBoy** [comment]
Just tested this and not been able to reproduce.

Was there something else on the battlefield either changing the color of the creatures or preventing them from attacking?

**Comment by Blankamen** [comment]
Oh man, now you talk about color change i remember. I have played Rise from
the Grave to return that Auriok Champion to play, but the card don´t change
the colors so i make confusion.Thank´s for the help!

2015-09-29 18:20 GMT-03:00 ShawnieBoy <notifications@github.com>:

**Comment by ShawnieBoy** [comment]
No problem!

The color-change issue is something being worked on in the background here with dynamic card frames.
