### ISSUE TITLE
Name of card displayed in user prompt when AI plays megamorph ability.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#454]
Reported in [forum](http://www.slightlymagic.net/forum/viewtopic.php?f=82&t=17748&p=186616#p186616) -
![](http://www.slightlymagic.net/forum/download/file.php?id=23266&mode=view)

**Comment by lodici** [comment]
This would not be an issue if
![screenshot00348](https://cloud.githubusercontent.com/assets/2443519/10816165/b5ea73ae-7e28-11e5-976c-afe00dabfb5a.png)
is on by default. Any objections to making it so?

**Comment by melvinzhang** [comment]
I find it easier to follow the AI's action if I know what it is trying to do. AI deciding on how pay {3}, <thinking>, some lands tapped, rather than suddenly see three lands being tapped.
