### ISSUE TITLE
Card played face down by AI is revealed when popup shown via stack

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#455]
...and possibly using the new card link in the log as well. Reported on [forum](http://www.slightlymagic.net/forum/viewtopic.php?f=82&t=17748&p=186616#p186616) -
![](http://www.slightlymagic.net/forum/download/file.php?id=23267&mode=view)

**Comment by lodici** [comment]
@melvinzhang, what is the best way to determine if ``MagicCardOnStack`` is face down?

**Comment by melvinzhang** [comment]
@lodici there wasn't a good way to do it, so I made some modifications. For face down spells, cardOnStack.getCardDefinition() will return the Morph card definition instead of the actual card. To get the actual card definition, call cardOnStack.getSource().getCardDefinition()

**Comment by lodici** [comment]
That is certainly better than it is now, it now shows the morph image although for both players. It seems to me that if ``MagicCardOnStack `` can be face down then it would more logical and consistent if it has an ``isFaceDown()`` property similar to ``MagicPermanent`` (ie. it has a state that can be checked).

Will this update work for all other cases where the popup image should not show the main image? For example, manifest, double-sided, etc. I would find it very helpful we could compile a definitive list of scenarios where this can happen.

**Comment by melvinzhang** [comment]
Added isFaceDown to MagicCardOnStack

**Comment by melvinzhang** [comment]
Changed to show the true card for human player. Not sure where you mean by other cases, as far I can can tell, spells can only be face down and that occurs when casting via the Morph ability. Manifest does not cast the spell it takes it from the library and put it on the battlefield face-down, double-faced cards are always cast from the normal face.

**Comment by lodici** [comment]
Thanks for the updates - it now behaves as expected. I was not sure whether there might be other circumstances other than morph where this issue might occur again. If it only affects morph then all bases appear to have been covered, thanks again for the clarification.
