### ISSUE TITLE
Make message in user prompt panel more consistent with Log/Stack?

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#457]
![screenshot00331](https://cloud.githubusercontent.com/assets/2443519/10207114/5c86ff20-67c2-11e5-9c14-c28849794e31.png)

Currently, when the mouse moves over the user prompt it will automatically display the image at full size to the right of the prompt panel. It would be more consistent if it behaved like the log and stack messages whereby card names in the message are interactive and respond to mouse move and click events in the same way. Likewise with the name in brackets.

 Alternatively, the prompt should be totally non-interactive with no coloring with same popup behaviour as occurs now.

Generally, I think the full size image popup should be activated via a mouse click to avoid it appearing unexpectedly as the mouse is moved around the game screen.

**Comment by ShawnieBoy** [comment]
If the source and target are separate, I could see the pop-up being useful to identify what the source is - If a spell a pop-up of the spell, otherwise highlight the permanent.

**Comment by lodici** [comment]
@ShawnieBoy do you have example choice messages for the two cases you mentioned?.

**Comment by ShawnieBoy** [comment]
Off the top of my head:

Book Burning - A spell that gives the opponent a choice, but no information about the result of the choice unless you look at the spell. ("Have SN deal 6 damage to you?")

I'll have to have a think about the permanent one when I have a database to look at, hehe

**Comment by lodici** [comment]
Thanks I will give Book Burning a try.

**Comment by ShawnieBoy** [comment]
Alaborn Cavalier may fit the other example, an optional "May tap target creature" when it attacks. Hopefully this helps.

I've got so much Magic in my head...

**Comment by lodici** [comment]
Neither of these generate a prompt with a card name in them - it all goes to the stack. Also, I can't get my head around Book Burning at all - is it implemented correctly? It automatically selects opponent but the card text ("Unless a player...") seems to imply that it can apply to either player, then you have to select the _target player_ before you know the damage decision!
![screenshot00333](https://cloud.githubusercontent.com/assets/2443519/10219376/529fa18c-6836-11e5-9e87-4a4a5056a6e9.png)

**Comment by ShawnieBoy** [comment]
It will produce a prompt if the opponent casts it on you. The target is chosen (the player to put cards into the graveyard), then any player may take damage - I think in magarena it won't prompt the caster, but will the opponent. (It's one that came to mind due to strange target and choice options)

**Comment by lodici** [comment]
Thanks for the explanation, unfortunately I can't seem to get the AI to play it even when it is the only card in its hand! It would be really useful if we could add some test-only options that forces the AI opponent down a particular path (eg. play selected card next).

**Comment by ShawnieBoy** [comment]
Yes, it's each player's choice whether to take damage or not. I never considered the possibility that several players could take the damage, but that could happen. In multiplayer, choices would be made in turn order, so unless there was something to gain from taking damage as well, only one player would need to take damage to prevent the spell effect.
