### ISSUE TITLE
Strange "may" wording in stack.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#459]
![screenshot00332](https://cloud.githubusercontent.com/assets/2443519/10207798/9c1d14ea-67c6-11e5-9460-828a8cd0dcb9.png)

How about...

pre-response: 
_mechs may put a quest counter on Quest for the Gravelord._
post-response:
1. _mechs may put a quest counter on Quest for the Gravelord. (yes/no)_
2. _mechs may (yes/no) put a quest counter on Quest for the Gravelord._

**Comment by ShawnieBoy** [comment]
I noticed that from the screenshot too - it's linked with the grammar changes for optional effects #358

**Comment by lodici** [comment]
Duplicates #358.
