### ISSUE TITLE
tokenize "SN is put into..."

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#463]
![screenshot00335](https://cloud.githubusercontent.com/assets/2443519/10412779/89565b04-6f88-11e5-8b97-48f94f13b46a.png)

**Comment by ShawnieBoy** [comment]
MagicPermanent line 782 is the start of the state-based actions if you need to know where to look.

**Comment by lodici** [comment]
Thanks, there were quite a few messages that needed updating.
