### ISSUE TITLE
Make a separate images location mandatory.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#466]
I would like to make it mandatory that the location for storing images is outside the Magarena installation folder. At the moment it is too optional and most users may not even be aware that they can change the folder using the settings dialog. It has a significant affect on the import (upgrade) process since if the images are stored inside the install folder they will have to be copied to the new install folder for consistency. If the location is separate from the installation of Magarena then the import only has to copy the location.

I envisage this requirement being implemented thus during the post-install startup -

- if not importing from an existing version then ask user for a location in which to store the images. Prevent them from selecting the Magarena install folder.
- if importing an existing version which is using the default images location, ask user to select a new location in which to store the images. The import will then __move__ the existing images to this folder.
- if for some reason the user elects to choose no folder then use the proxy images (#453).

This is related to what I am current looking at which is removing the need to manually download images (goodbye _new images_ alert) - the idea is that once the images folder is specified then missing images will be downloaded on a low priority background thread whilst prioritizing images on-demand based on whatever the user is currently doing. It should be completely transparent to the user, card images should just appear as needed.

**Comment by melvinzhang** [comment]
I'm one of those users who prefer to store images inside the Magarena install folder. It lets me put the whole application + images on a USB stick and demo it easily on a different computer.

**Comment by melvinzhang** [comment]
I'm not sure I see how this is related to downloading images on a background thread (which would be a very nice feature to have). Regardless of the location of the images (inside the install folder or outside), the background thread should be able to write images to it.

**Comment by lodici** [comment]
> I'm one of those users who prefer to store images inside the Magarena install folder. It lets me put the whole application + images on a USB stick and run it on any computer.

Good point. In that case, instead of it being the silent default as it is now I would prefer it if we can prompt the user at startup for the location. This way we can encourage them to use an external location but they still have the choice of using the Magarena folder as well.

**Comment by lodici** [comment]
Actually if moving the image folder is as fast in java as on the OS then this would be my preferred solution. Leave everything as it is now with a silent default and a setting in preferences which lets you point to an external location if you wish.

**Comment by melvinzhang** [comment]
> Actually if moving the image folder is as fast in java as on the OS then this would be my preferred solution.

As far as I know, moving a folder is as fast as the underlying OS. see https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#move-java.nio.file.Path-java.nio.file.Path-java.nio.file.CopyOption...-

Note that as stated on the docs, move will fail if moving of the files is required, such as when moving between two different filesystems.

**Comment by lodici** [comment]
> Note that as stated on the docs, move will fail if moving of the files is required, such as when moving between two different filesystems.

That would be a bit of a pain but I am taking advantage of the [_commons-io-2.4.FileUtils_](https://commons.apache.org/proper/commons-io/javadocs/api-2.4/org/apache/commons/io/FileUtils.html) library. It has ``moveDirectory`` and ``moveDirectoryToDirectory`` which does a "copy and delete" when the destination directory is on another file system. I should be able to test between a usb fat32 and ntfs drive.
