### ISSUE TITLE
Condition "two or fewer other lands" not parsing/applying correctly

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#467]
After amalgamating the enter the battlefield tapped methods to use conditions, it looks as though the 'other' component isn't recognising correctly. The cycle of lands that use "Enters the battlefield tapped unless you control two or fewer lands" still counts the land being played.

For the trigger, it is essentially on the battlefield already, but the 'other' part should be searching for other lands and not itself, especially as the check is referring to the permanent.

**Comment by melvinzhang** [comment]
MagicCondition.YouControlAtMost delegates to MagicPlayer.getNrOfPermanents(MagicTargetFilter<MagicPermanent>) which passed in MagicSource.NONE to the accept method which makes the other part useless.

**Comment by ShawnieBoy** [comment]
Ahh yes, thanks for fixing that :+1:
