### ISSUE TITLE
Problem with Ashcloud Phoenix and Morph.txt

### ISSUE THREAD

**Issue by firemind** [magarena/magarena#470]
When I was trying to get some results on the new Standard format on firemind.ch I noticed that the duels involving Ashcloud Phoenix fail with error message:

magic.exception.GameException: java.lang.RuntimeException: card script file not found: /var/local/aiworker/magarena2/release/Magarena/scripts/Morph.txt
	at magic.model.MagicGame.doAction(MagicGame.java:554)
	at magic.model.MagicGame.executeNextEvent(MagicGame.java:824)
	at magic.model.MagicGame.advanceToNextEventWithChoice(MagicGame.java:784)

Duel details here: https://www.firemind.ch/duels/525693
or here: https://www.firemind.ch/duels/525691

I have not tried if other morphs are affected by this

**Comment by melvinzhang** [comment]
Thanks, I can confirm this bug. All morph and manifest cards are affected. This is due to trying to load the definition using getCard("Morph") but the actual file on disk is _Morph.txt

**Comment by melvinzhang** [comment]
@firemind the fix is to rename _Morph.tx to Morph.txt and _Manifest.txt to Manifest.txt, you can apply this fix directly to 1.66 or wait for 1.67 which will include commit 5464e89 that includes the fix.
