### ISSUE TITLE
discussion of rules for selecting card image

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#471]
I'd like to propose the following criteria for comparing card images to be used on a card.
1. rules text clarity
2. image quality
3. recent printing

In order of preference, i.e. for any two candidate image, first compare the rules text (the one with the rules text that better match the oracle text wins). If rules text are the same, compare the image quality (the clearer, less blur image wins). If the first two criteria is a tie, consider the more recent printing.

@ShawnieBoy @lodici please comment on this proposal or offer a counter proposal. The goal of this issue is to determine and document the rules for card image.

**Comment by lodici** [comment]
In an ideal world you would be able to choose the print you want, something which has been raised in the past although possibly not here on GitHub yet. In lieu of having such an option then I think the rules you have described are clear and will lead to consistency which is the main thing. TBH, I more or less assumed that was how they are selected now anyway.

I would add that the card value/rating has more than just cosmetic value (I am sure there is/was a post in the forum that uses this to group cards each month) so perhaps insert this in at #3.

**Comment by ShawnieBoy** [comment]
@melvinzhang The card value/rating has not currently been functional on Gatherer since Khans of Tarkir, so you could argue that all new cards printed and released this year are not working correctly for AI evaluations: 

Magic Origins,
Tempest Remastered,
Modern Masters 2015,
Fate Reforged,
Dragons of Tarkir,
Battle for Zendikar.

Being able to choose your own images would be ideal, but I see it that when a new set arrives, you'd expect all cards to be of the new set, especially so with regards to cards that have not been reprinted for a long time and either involve new card text or the most recent card frame.

**Comment by melvinzhang** [comment]
@lodici we are only talking about the rules for the card image here, I don't see how card value comes into the picture. The card value does not need to be from the same printing as the image.

@ShawnieBoy Yes, new cards don't have the proper card values as it generally it takes a while for cards to gather votes on gatherer to settle on the proper value. The fact that new cards have unknown cards value, doesn't mean we can't have better values for reprints. My issue is that we are removing the more accurate value for older cards and replacing them with essentially the unknown value (2.5), I think we should leave the card value as they are.

All things being equal (same rules text, same image quality), the newer cards with newer art work/frames are better. However, in the rules I have proposed, image quality is more important than recent printing. In your case, it is right to say that you would prefer to use the new art even when it is of a poorer quality than the previous card image?

To be clear, when the high quality scans of the reprints are available, we will update the reprints to use them, but not before that point.

**Comment by lodici** [comment]
> @lodici we are only talking about the rules for the card image here, I don't see how card value comes into the picture. The card value does not need to be from the same printing as the image.

I meant that the card value should not be reset to 2.5 based on the card print, it is better to have a meaningful value even if it is based on an older print - basically what you explained to shawnieboy.

**Comment by lodici** [comment]
> This is how the scriptsbuilder is working, taking the most recent card printing version

Unless it is overwritten via ``CardImages.txt``.

**Comment by ShawnieBoy** [comment]
>Yes, new cards don't have the proper card values as it generally it takes a while for cards to gather votes on gatherer and settle on the proper value

The thing is, is that this isn't working, and hasn't been working so far this year. Wouldn't that mean that new cards (that haven't been reprinted) which would be rated highly be overlooked by the AI in some way? I'm not overly sure how much the card value effects the AI's play-preference. There are already around a thousand cards which would have 'incorrect' values because of this, with no information as to when this will be fixed.

>In your case, is it accurate to say that you would prefer to use the new art even when it is of a poorer quality than the previous card image?

Yes, personally I would (and am, hehe) - While they may not be as crisp as other versions, they are stil completely legible.

**Comment by ShawnieBoy** [comment]
>Unless it is overwritten via  CardImages.txt .

It is possible to manually override all card images, currently they're only there for when magiccards.info doesn't have the images for that set (which can sometimes take longer than expected) or for sets with errors in the cardnumbers etc.

Manually curating 15,000+ cards would seem a bit daunting to be honest, checking when and if images have changed on magiccards info. The dimensions and resolutions of the images will remain the same, it's just the 'quality', possibly comparing file-sizes and choosing the larger would determine better quality?

**Comment by melvinzhang** [comment]
As two our of the three maintainers agree on the proposal, I declare that the proposal is now the adopted rule for selecting card images. The card image changes and value changes have been reverted in 396f4f6b3b45b5b117ebce6ec3a1d81c96ade8f4, the other improvements have been manually added back in a88699257cda6ae4582219dfc0e16d1bde21f7de

**Comment by melvinzhang** [comment]
https://github.com/magarena/magarena/wiki/Basic-Structure section on card image has been updated to include the adopted rules for card image selection.

**Comment by ShawnieBoy** [comment]
It would have been nice to have some feedback on the issues I raised before closing this instead of apparently ignoring it for a few weeks :stuck_out_tongue:

**Comment by melvinzhang** [comment]
Sorry about that, I wanted to include this in the October release. My purpose for this issue is to decide on the image selection criteria and for that we have a majority agreement hence I considered it settled.

For the issue of updating the images programmatically, lodici has raised issue #481. What are the other issues? The discussion here got a bit side tracked and it is hard to keep tabs on what are the separate items, it is best to give each issue its own page.

**Comment by ShawnieBoy** [comment]
I understand.

The other issue raised was for the card values - we have a years worth of cards with base-scores. Will this be negatively impacting the AI - WotC has given no information as to when this functionality of Gatherer will be fixed.

This was linked with the card images issue as reprints for sets will be rated higher than other cards in the set.

**Comment by melvinzhang** [comment]
Thanks, let's discuss this in https://github.com/magarena/magarena/issues/482
