### ISSUE TITLE
How to test RevealAction?

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#478]
I am trying to test the log message generated by [``RevealAction``](https://github.com/magarena/magarena/blob/94968b788c49944ad0035168162ba5664ce363a4/src/magic/model/action/RevealAction.java#L34) but I cannot find a card to trigger it. I have tried ``Mind Grind`` but to no avail. Can anyone suggest how I might go about triggering this action. Thanks.
![screenshot00343](https://cloud.githubusercontent.com/assets/2443519/10786180/c09a5fa8-7d60-11e5-8704-607f3a523406.png)

**Comment by ShawnieBoy** [comment]
Cards that search from library into hand generally trigger the reveal - Civic Wayfinder etc

**Comment by lodici** [comment]
Nope that produces the "found (...)" message which looks like [``MagicSearchToLocationEvent``](https://github.com/magarena/magarena/commit/9d334d195b249f4f764c1794e5664fa3ec86bf13).

I have compiled a shortlist of possible candidates -
- Garruk, Caller of Beasts
- Altar of Bone
- Buried Alive
- Defense of the Heart
- Enlightened Tutor
- Foresight
- Howling Wolf
- Lay of the Land
- Plea for Guidance

**Comment by lodici** [comment]
![screenshot00344](https://cloud.githubusercontent.com/assets/2443519/10799560/5cb68210-7da5-11e5-84ea-45925ed6ab28.png)

**Comment by lodici** [comment]
Garruk, Caller of Beasts does the business. :smile:

**Comment by ShawnieBoy** [comment]
Oh yes, that's interesting.
Looks as though there's two 'reveal' methods going on there then - the 'found' should be a reveal really. While there's always an option to 'find nothing' when searching, I don't think that's supported (could be wrong).
