### ISSUE TITLE
Thought Scour double logs and does not show card names.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#480]
It generates two different log messages essentially saying the same thing. It should also show the names of the cards that have been put into the graveyard.
![screenshot00349](https://cloud.githubusercontent.com/assets/2443519/10854849/4e9a4e7c-7f36-11e5-9878-8b92d61a97c4.png)

**Comment by lodici** [comment]
The above commit generates
![screenshot00350](https://cloud.githubusercontent.com/assets/2443519/10857088/e32ec6c8-7f43-11e5-92b0-4d035a0be33f.png)
Not sure what to do about the second log message which is generated by ``MagicMillEvent``. Also, is there any chance the "top N" could be impractically large? In that case, would probably be best to limit the list of cards displayed.

**Comment by ShawnieBoy** [comment]
Some cards can mill a vast amount of cards from the top of the library (Potentially as large as a whole deck) Possibly an ellipses when over a particular number (Say five) to show that there's more. In those situations you'd rather be looking at their graveyard than a list.

**Comment by lodici** [comment]
Thanks - I have added the restriction that will only show the list of cards if five or less, otherwise displays ``...``.

**Comment by lodici** [comment]
The similar "..puts the top..." log messages are in fact associated with different players (note, different health values). Implementing #486 should help to resolve any confusion.
