### ISSUE TITLE
Gatherer voting isn't working -> card values not updated

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#482]
> The thing is, is that Gatherer voting isn't working, and hasn't been working so far this year. Wouldn't that mean that new cards (that haven't been reprinted) which would be rated highly be overlooked by the AI in some way? I'm not overly sure how much the card value effects the AI's play-preference. There are already around a thousand cards which would have 'incorrect' values because of this, with no information as to when this will be fixed.

I do not think it will be much, card value is a small nudge to fudge the card evaluation, other AI hints like removal value and static property seems to have been left out of recent card scripts and there hasn't been any reported problems.

**Comment by melvinzhang** [comment]
> This was linked with the card images issue as reprints for sets will be rated higher than other cards in the set.

My understanding is that the card value affects how often the card is left in the hand. So a higher rated card would be left in hand more often. That is to say assume a Lightning Bolt type card, one has card value 5 and the other has card value 1. The AI will tend to play the one with value 1, leaving it in a stronger situation of a value 5 card in hand.

**Comment by melvinzhang** [comment]
Assuming there is a negative impact, it is not clear for me that reverting all the reprints back to value 2.5 as well would be a net improvement. In that case, I'd prefer to have some ratings rather than no ratings.

**Comment by ShawnieBoy** [comment]
That's interesting to know

Maybe Firemind would be able to help out with some comparisons - duels with and without the value rating involved.

**Comment by melvinzhang** [comment]
Yes, that would be a good way to determine the actual impact. For that to be possible, we need to be able to disable the effect of card value on a per AI basis, which is not doable at the moment.

**Comment by ShawnieBoy** [comment]
I guess the only way to do it would be from the card scripts then. Duels with correct values, then change one deck to only have default values (or no value)

**Comment by melvinzhang** [comment]
That seems to be harder, as it would require change the card scripts between duels. It seems to be easier to make card value an AI option and have the scoring system check that option to determine whether to return the actual value or the default value. This would open up additional ways to improve the scoring system as we can create new options to test different forumulas etc.

**Comment by ShawnieBoy** [comment]
I was thinking a straight duel between two decks which we could probably do ourselves. Do 100 duels or so to establish a win-ratio, then manually change the values in one deck (Making sure the two decks don't share cards) Then another 100 duels with these edited values to compare any win-ratio change.

**Comment by melvinzhang** [comment]
100 duels may be too little to establish statistical significance, the statistics is the same as https://en.wikipedia.org/wiki/Checking_whether_a_coin_is_fair

Closing this as the theoretical effect of card value has been explained (higher value, more likely to be kept in hand).
