### ISSUE TITLE
redesign new duel screen, remove extraneous buttons

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#483]
reduce the number of clicks to start a new game

**Comment by lodici** [comment]
Can you elaborate. Extraneous buttons?

**Comment by melvinzhang** [comment]
Sorry for the brevity, there are some quick notes I jot down from a play testing session with a user who has never seen the game before. I think what the user meant was that the current experience of starting a new game is quite complex, many buttons and icons before you can start playing. 

One idea is perhaps a "Start duel" or "Quickstart" menu item that uses a beginner friendly default setting (for first start) and reuse previous duel for subsequent games. I think it is quite common to reuse the same duel settings. Then perhaps a "Customize duel" option for someone who wants to tweak the settings.

**Comment by lodici** [comment]
How about a Quick Game option that generates random decks for both players, selects a random AI opponent (type and level) and starts a single-game duel. Each player would be assigned a random avatar and the players would be named "Player 1" (you) and "Player 2" (AI). Once the game is finished return to Main menu. No player stats would be recorded, obviously.

**Comment by melvinzhang** [comment]
I'm was thinking of just using the previous duel settings, so there is no need to click next to use my customized settings to play.

The initial settings will be important, it may be the first ever game a new player will play. I think it is better to craft that experience with prebuilt decks and specially selected AI rather than a random selection.

**Comment by lodici** [comment]
> I'm was thinking of just using the previous duel settings, so there is no need to click next to use my customized settings to play.

Isn't that what "Resume Duel" does?

> The initial settings will be important, it may be the first game a new player will play. I think it is better to craft that experience with prebuilt decks and specially selected AI rather than a random selection.

Couldn't this be done using the New Duel screen? TBH, I am not sure what you mean by "customized settings".

**Comment by lodici** [comment]
Actually, do mean having the ability to save multiple duel configurations which you could then select from, eg. something like
![screenshot00011](https://cloud.githubusercontent.com/assets/2443519/6903198/93a717ee-d710-11e4-9993-f0c51ceac16c.png)

**Comment by melvinzhang** [comment]
My understanding is that "Resume duel" is to complete an unfinished duel, say I have played game 1 out of 3. Resume duel will continue on game 2. What I mean is if I finished a duel and I want to start a new duel with the same settings as the last duel.

The current "new duel" requires the user to do some setup which can be confusing for a first time user. I'm suggest a "start duel" option which uses crafted a set of beginner friendly options, and a "customize duel" which allows more experience players to customize the options then start the duel. After the duel is customized, future "start duel" will use the user customized options.

**Comment by lodici** [comment]
> What I mean is if I finished a duel and I want to start a new duel with the same settings as the last duel.

Resume Duel already does this but only for the last duel played. #139 is one way of resuming multiple duels you may have started but have not yet finished. #144 is similar but would let you play completed duels again.

> The current "new duel" requires the user to do some setup which can be confusing for a first time user.

Not necessarily, when you select "New Duel" for the first time it uses default settings which I kind of assumed would be acceptable. I am all for adjusting the defaults for a first time user - what do you suggest?

Currently the New Duel screen only lets you store one duel profile. It might be useful to update it so you can select from a list of saved or pre-defined duel configurations as well.

**Comment by melvinzhang** [comment]
Thanks, I didn't realize "Resume Duel" is able to immediately start a duel using the last completed duel's settings.
