### ISSUE TITLE
AI issue with Swans of Bryn Argol

### ISSUE THREAD

**Issue by firemind** [magarena/magarena#484]
I noticed a lot of duels on firemind.ch failing with gc overhead or out of memory errors. All of them involve a deck with Swans of Bryn Argol in it.

https://www.firemind.ch/duels/525860
https://www.firemind.ch/duels/525859
https://www.firemind.ch/duels/525858
https://www.firemind.ch/duels/525857
https://www.firemind.ch/duels/525853

In the duel logs I also find a lot of messages like this one:
WARNING. RCR:  Choose 25 cards from your hand.Player1 discards 25 cards$. time: 11482

The time values go up as high as 265387: 
WARNING. RCR:  Choose 21 cards from your hand.Player1 discards 21 cards$. time: 265387

**Comment by melvinzhang** [comment]
Looks like due to the ability of Swans of Bryn Argol, the player could get a lot of cards in hand, which lead to a giant decision on what to keep at the end of the turn. The number of possible discards for (25+7) cards in hand is (25+7) choose 25 = 3365856. Trying to generate all these discard options is causing the system to run out of memory.

**Comment by firemind** [comment]
Sounds like it's not actually a problem with Swans. Cards like Stroke of Genius and Enter the Infinite will cause the same type of problem, correct?

**Comment by melvinzhang** [comment]
Correct.

**Comment by firemind** [comment]
Maybe you could give the AI some restrictions to help it evaluate only relevant options. When I think about how I would approach this in a game of magic, my thoughts would be something like this:

* Do I have spells in hand that I can't cast yet? Which lands (in hand) do I need to be able to cast everything. Discard all other lands.
* Do I have multiple legends? Only keep one.
* After that I'd keep a diverse mix of spells and creatures, With a preference for the best cards of course.

The truth is, after drawing that many cards the AI is probably already winning. It just has to play out the game.

This doesn't help combo decks of course but those aren't supported by the AI anyway, right?

**Comment by melvinzhang** [comment]
merge into #721
