### ISSUE TITLE
Duplicate or very similar log entries being created.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#485]
![screenshot00353](https://cloud.githubusercontent.com/assets/2443519/10924640/f890aa9c-827f-11e5-8d0e-7fbcc31b3c79.png)

**Comment by lodici** [comment]
Actually this was an AI vs AI game where the players have the same name so it is possible that the similar entries refer to each player - hard to tell except for the different healths.

**Comment by ShawnieBoy** [comment]
Looking at this it's the log of the spell effect, and then the result (Although sometimes reversed, but there's a bit of an issue with stack ordering with some cards).

Player A casts a spell that states "Player B discards a card"
Player B then does it "Player B discards a card (the card discarded)"

**Comment by lodici** [comment]
Thanks for the clarification - I have raised #487.
