### ISSUE TITLE
Log entries in wrong order.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#487]
Here is the log displayed in #480 
![screenshot00354](https://cloud.githubusercontent.com/assets/2443519/10932097/b0d9e556-82c5-11e5-99d4-b5380b9643ec.png)

Ignoring the fact that both players have the same avatar and the non-AI player is named "Player", the similar "...puts the top..." log entries are confusing because -
- they are in the wrong order.
- the name of the targeted player, MMABFast, is displayed at the end of the message but is confusing because it looks like it is related to the "Player draws a card" sentence. It would be clearer I think if the name of the targeted player was added as "Target player (MMABFast) puts the top two cards...".

**Comment by lodici** [comment]
Also, "Player draws a card" seems to be missing a full stop.

**Comment by ShawnieBoy** [comment]
Lots of non-groovy cards will probably have 'identifiers' (can't think of another word for them) at the end of the string, instead of mid-string. This will probably look a bit strange for cards which have linked effects using the `~` character.
Groovy script allows for a bit more flexibility with crafting log messages, but it seems strange that the 'draws a card' is missing the full stop as it appears in the MagicDrawEvent, it may be removed to place the identifier at the end?

**Comment by lodici** [comment]
I think you are right regarding the full stop - I think it is meant to appear after the '(MMABFast)' but the log message renderer will happily drop it if it does not fit on the line. Alternatively, the code that adds '(MMABFast)' onto the end might also be the culprit.

**Comment by melvinzhang** [comment]
Yes, it is meant to appear after the choice indicator (the part in brackets). @lodici what do you mean the "the log message rendered will happily drop it if it does not fit on the line"? would it not create a newline?

**Comment by melvinzhang** [comment]
On my screen the text "Target player..." appears on four lines and the period is there after the closing parenthesis.

**Comment by lodici** [comment]
> On my screen the text "Target player..." appears on four lines and the period is there after the closing parenthesis.

Yes, I was not correct. In the screen shot the period is after the ``(MMABFast)`` but does not quite fit in the display area - the renderer will not allow a period to force a new line since it would look very strange. So I guess this is what you might call an edge-case since most times the period will be visible. I don't think it worth fretting over and since you have fixed the ordering (thanks) I will consider this issue closed.
