### ISSUE TITLE
Mana Property - Land only?

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#493]
After noticing that the mana property had been left off of the Battle for Zendikar lands, I began to do some checking on other sets, and then began to think more about the mana property in general.

Obviously it will predominantly appear on Lands for determining a mana-base for random decks, however they are not the only sources for mana.

Is this property supposed to only appear on lands, as a trustworthy source of mana, or should it appear on creatures and artifacts that produce mana, but require mana to cast?

Currently there are two creatures with a mana property: Blightsoil Druid and Vesper Ghoul, and one artifact with the mana property: Phyrexian Lens.

With the property being on creatures, I could see a problem with them being added into decks which cannot actually cast them (I'm not sure how the random deck generator weighs the mana property, or even if it looks at any attached casting cost when considering them)

**Comment by lodici** [comment]
Not quite sure what you mean (beyond my MTG knowledge!) but take a look at [``DeckGenerators.setRandomDeck()``](https://github.com/magarena/magarena/blob/master/src/magic/data/DeckGenerators.java#L116) which is called when you select a random deck in the new duel screen.

**Comment by ShawnieBoy** [comment]
[``DeckGenerator.addBasicLandsToDeck()``](https://github.com/magarena/magarena/blob/master/src/magic/data/DeckGenerator.java#L71) is where it considers a land's mana property, but I'm unable to find anything regarding other cards. It would be safe to assume other mana producing permanents are not considered.

**Comment by lodici** [comment]
> It would be safe to assume other mana producing permanents are not considered.

Yes, that is how I understand the the code. As far as I am aware since joining the project the random deck generators have not been updated to any significant degree. Perhaps its time...:wink:

> basicLands is a bit misleading here

Feel free to refactor to something more meaningful.

**Comment by melvinzhang** [comment]
yes, mana property is only important for lands.
