### ISSUE TITLE
DestroyAction(p.getEquippedCreature()) crashes if p is not equipped

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#494]
```
Caused by: magic.exception.GameException: java.lang.ArrayIndexOutOfBoundsException: -1
	at magic.model.MagicGame.doAction(MagicGame.java:554)
	at Dead_Iron_Sledge$1.executeEvent(Dead_Iron_Sledge.groovy:22)
	at magic.model.event.MagicEvent.executeEvent(MagicEvent.java:659)
	at magic.model.MagicGame.executeEvent(MagicGame.java:763)
	at magic.model.stack.MagicItemOnStack.resolve(MagicItemOnStack.java:127)
	at magic.model.action.StackResolveAction.doAction(StackResolveAction.java:13)
	at magic.model.MagicGame.doAction(MagicGame.java:552)
	... 6 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at magic.model.MagicLogMessageBuilder.appendMessage(MagicLogMessageBuilder.java:19)
	at magic.model.MagicGame.logAppendMessage(MagicGame.java:688)
	at magic.model.action.DestroyAction.doAction(DestroyAction.java:78)
	at magic.model.MagicGame.doAction(MagicGame.java:552)
	... 12 more
```

getEquppedCreature may return MagicPernanent.NONE, calling DestroyAction on NONE crashes.

**Comment by ShawnieBoy** [comment]
Hmm, I can only guess that there was another removal action put onto the stack while the trigger was there. Another check would be needed before the destruction attempt of the previously equipped creature.

Or a check on DestroyAction to make sure it's not NONE?

**Comment by melvinzhang** [comment]
In the case of Dead Iron Sledge (where this exception occurred), I think the problem is referring to equipped creature in executeEvent as event.getPermanent().getEquippedCreature(), it should not be the equipped creature when the effect resolves, rather it should be the equipped creature at the point when the trigger occurs. 

Cause it is possible to have the trigger occur and then re-equipped Dead Iron Sledge on a different permanent and when the trigger resolves it should not destroy the currently equipped creature but the previous one.

The correct fix in this case is to construct a MagicPermanentList with the target and equipped creature as elements as pass that as the ref in the MagicEvent and invoke destory as new DestroyAction(event.getRefPermanentList())

**Comment by melvinzhang** [comment]
In the case of Dead Iron Sledge, the gatherer page[1] has a ruling that reads "Moving Dead-Iron Sledge after the ability triggers will not affect which creatures are destroyed."

Which makes me wonder if the same is true for other references to equipped creatures, i.e. it is fixed on activation/trigger and it not checked again on resolution. Anyone knows what is the correct way?

[1] http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=48139

**Comment by melvinzhang** [comment]
112.7a states that "Once activated or triggered, an ability exists on the stack independently of its source." and "any activated or triggered ability that references information about the source because the effect needs to be divided checks that information when the ability is put onto the stack"

Can the above be interpreted as "equipped creature" is determined when the ability is put onto the stack and not updated on resolution, and it a more general version of the Dead Iron Sledge ruling.

**Comment by ShawnieBoy** [comment]
Yes, that would be the reference they would have used for the ruling. Essentially going on the stack as a time-capsule. After some digging:

608.2i If an ability’s effect refers to a specific untargeted object that has been previously referred to by that ability’s cost or trigger condition, it still affects that object even if the object has changed characteristics.

Here that would be the 'equipped creature' when going on the stack, no longer being an 'equipped creature'

**Comment by melvinzhang** [comment]
However, Umezawa's Jitte ruling [1], says "If the Jitte is moved after the "+2/+2" mode is announced but before it resolves, the bonus is given to the creature that is equipped when the ability resolves." So the equipped creature is determined on resolution in this case.

And another ruling has to do with the Jitte leaving the battlefield, which we don't implement at the moment, "if the Jitte leaves the battlefield after the "+2/+2" mode is announced but before it resolves, the bonus is given to the creature that was most recently equipped once the ability resolves."

I think the case for Dead-Iron Sledge could be due to it using the wording "Destroy both creatures" instead of the original wording of "Destroy that creature and equipped creature". Does that make sense?

[1] http://gatherer.wizards.com/Pages/Card/Details.aspx?name=umezawa%27s+jitte

**Comment by ShawnieBoy** [comment]
But the Jitte doesn't involve a trigger or an equipped creature in the cost, it's an activated ability.

If the trigger on the Jitte involved putting counters on the equipped creature instead of the equipment, then moving it would still put counters on the original equipped creature.

**Comment by melvinzhang** [comment]
How about case for "Ring of Thune" and friends? They have the triggered ability "At the beginning of your upkeep, put a +1/+1 counter on equipped creature if it's white." My interpretation is that they put the counter on the equipped creature as it resolves, so if the Ring was moved somehow, it will put the counter on the new equipped creature and not the previous one.

My reasoning is that normally the phrase "equipped creature" refers to the equipped creature as the effect resolves. The "Dead-Iron Sledge" case is different because it is referring to the equipped creature that triggered the effect, hence it does not matter if it is moved.

In a sense, the Dead-Iron Sledge case is special because it is referring to an object in the earlier part of the rule.

**Comment by ShawnieBoy** [comment]
With those rings, the trigger isn't related to the equipped creature, the trigger is a phase. If a trigger or cost refers to the equipped creature, all that information goes to the stack and won't change. As the Sledge does refer to the equipped creature, when it is moved the trigger info is that of the old equipped creature.

The rings will put counters on the new creature, the sledge will destroy the old creature.

**Comment by melvinzhang** [comment]
Agree, the reference to the earlier use of "equipped creature" is the key here.

As a thought experiment, what about the following 

"At the beginning of equipped creature's controller's upkeep, put a +1/+1 counter on equipped creature."

vs

"At the beginning of equipped creature's controller's upkeep, put a +1/+1 counter on that creature."

I think in the first case, the two use of "equipped creature" is not related. So the second equipped creature refers to the equipped creature when the effect resolves.

In the second case, because of the use of "that creature", the equipped creature that cause the trigger would be the one to get the counter.

**Comment by ShawnieBoy** [comment]
That's more of a tricky one, the trigger is the controllers upkeep, not the creature per se. I agree with the outcomes though, as the use of 'that creature' more strongly infers any creature mentioned.

"Whenever equipped creature attacks, put a +1/+1 counter on it."

vs

"Whenever equipped creature attacks, put a +1/+1 counter on equipped creature."

This probably more closely shows the problem - These will both have the same result, the counter being placed on the creature that attacks for the trigger, ie. the 'old' creature if the equipment gets moved.

With the Sledge, the trigger being "equipped creature blocks or becomes blocked by a creature", puts the attacking and blocking creature in the trigger info. The reference then to 'both creatures' is for those that created the 'blocked' state, even if one or both of those creatures are neither blocking, blocked or even on the battlefield by the time it resolves.

**Comment by melvinzhang** [comment]
I'd disagree on the second case, I think if it was templated using the phrase "equipped creature" in the effect it always means the current one. Since these kind of text doesn't occur in practice, it is a moot point really. Thanks for sharing your thoughts.
