### ISSUE TITLE
"sacrifice SN unless you pay <mana cost>" does not parse

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#497]
commit a0eed44064e broke 
release/Magarena/scripts/Breeding_Pit.txt
release/Magarena/scripts/Hungry_Mist.txt
release/Magarena/scripts/Sunken_City.txt

detected by circleci https://circleci.com/gh/magarena/magarena/124

@ShawnieBoy please check if all cards are still able to parse after an scripts update

**Comment by ShawnieBoy** [comment]
Sorry - my bad
