### ISSUE TITLE
Rancor stays attached to Treetop Village even when no longer a creature

### ISSUE THREAD

**Issue by itandetnik** [magarena/magarena#50]
Computer activated Treetop Village, then played Rancor on the resulting Ape creature. At the end of the turn, Treetop Village turned back into a land - at that point, the enchantment should have dropped of it into the graveyard (and then, specifically in case of Rancor), be returned to owner's hand.

Instead, it remains attached to the land. See screenshot (top row, second from right).

![screenshot](https://cloud.githubusercontent.com/assets/9506419/5565904/1fec95d4-8edd-11e4-8bc0-abbae3ed1102.png)

Log for this turn (there doesn't seem to be anything useful there, to my untrained eye):

MCTS cached=0
MCTS cheat=true index=1 life=14 turn=13 phase=Draw sims=1894 time=8067
  [89/138/?] (Mutavault=M, Mutavault=M, Treetop Village=M)
* [93/318/?] (Mutavault=C, Mutavault=M, Treetop Village=M)
  [92/243/?] (Mutavault=M, Mutavault=C, Treetop Village=M)
  [92/240/?] (Mutavault=C, Mutavault=C, Treetop Village=M)
  [88/106/?] (Mutavault=M, Mutavault=M, Treetop Village=C)
  [92/271/?] (Mutavault=C, Mutavault=M, Treetop Village=C)
  [93/281/?] (Mutavault=M, Mutavault=C, Treetop Village=C)
  [93/297/?] (Mutavault=C, Mutavault=C, Treetop Village=C)
MCTS cached=0
MCTS cheat=true index=1 life=14 turn=13 phase=FirstMain sims=2072 time=8039
  [91/169/?] (pass)
  [91/156/?] (Treetop Village)
  [94/341/?] (Rancor)
  [93/245/?] (River Boa)
* [94/357/?] (Treetop Village)
  [90/147/?] (Albino Troll)
  [93/245/?] (Joraga Warcaller)
  [93/253/?] (Mutavault)
  [91/159/?] (Mutavault)
MCTS cached=0
MCTS cheat=true index=1 life=14 turn=13 phase=FirstMain sims=2007 time=8046
  [90/599/?] ()
* [92/1408/?] ()
LOG (C): Pay {1}{G}. Tap Forest. Tap Mutavault. Play activated ability of Treetop Village.
LOG (C): Until end of turn, Treetop Village becomes a 3/3 green Ape creature with trample. It's still a land.
MCTS cached=0
MCTS cheat=true index=1 life=14 turn=13 phase=FirstMain sims=2068 time=8036
  [91/731/?] (pass)
* [92/1138/?] (Rancor)
  [87/199/?] (River Boa)
MCTS cached=0
MCTS cheat=true index=1 life=14 turn=13 phase=FirstMain sims=2154 time=8025
  [88/214/?] (Albino Troll)
  [92/917/?] (River Boa)
* [93/1023/?] (Treetop Village)
LOG (C): Pay {G}. Tap Forest. Play Rancor.
LOG (C): Enchant target creature (Treetop Village) with Rancor.
MCTS cached=0
MCTS cheat=true index=1 life=14 turn=13 phase=DeclareAttackers sims=2074 time=8037
* [94/767/?] ([River Boa, Albino Troll, Treetop Village])
  [84/74/?] ([River Boa, Albino Troll])
  [93/541/?] ([River Boa, Treetop Village])
  [87/116/?] ([River Boa])
  [92/322/?] ([Albino Troll, Treetop Village])
  [76/31/?] ([Albino Troll])
  [89/195/?] ([Treetop Village])
  [76/28/?] ([])
LOG (C): Computer attacks with Albino Troll, River Boa and Treetop Village.
LOG (P): Igor blocks with Arcbound Ravager and Eldrazi Spawn.
LOG (P): {c}Igor loses 5 life.
LOG (C): Albino Troll is destroyed. Rancor is put into its owner's graveyard.
LOG (P): Eldrazi Spawn is destroyed.
LOG (C): Return Rancor from the graveyard to its owner's hand.
MCTS cached=0
MCTS cheat=true index=1 life=14 turn=13 phase=SecondMain sims=1448 time=8083
  [78/620/?] (pass)
* [79/828/?] (Treetop Village)
LOG (C): Play Treetop Village.

**Comment by ShawnieBoy** [comment]
Replicated, I'm guessing this is to do with when auras are checking target legality, and the ending of static abilities.

**Comment by ShawnieBoy** [comment]
Seems to be occurring at end of the next Upkeep or beginning of the next draw Draw.

**Comment by melvinzhang** [comment]
I think the trigger got added during cleanup phase but couldn't go on the stack. Triggers was changed to go on the stack only when player has priority. In the cleanup phase, players do not get priority unless there is something on the stack.

**Comment by melvinzhang** [comment]
The bug is the code is checking for game.getStack().isEmpty() as it assumes that triggers go on the stack directly. It should check if there is any pending triggers. Implementing the fix now.

**Comment by melvinzhang** [comment]
Please ignore the above two comments. cleanup calls game.checkStatePutTriggers() which would put the triggers on the stack, but it is not being put as you pointed out.

**Comment by melvinzhang** [comment]
One reason I could think of is we are missing a call to game.setStateCheckRequired.

**Comment by ShawnieBoy** [comment]
When are auras checked against their enchanted permanents to see if they are still legal? It could just be an ordering thing with them checking before the 'becomes' wears off, so sees a legal target.

**Comment by melvinzhang** [comment]
I think you are on to something, aura's are checked in permanent.generateStateBasedActions(), but this occurs before the call to update(). Before update(), the effect of the removal of the static effect is not observed, hence no state based actions where generated.
