### ISSUE TITLE
Player Name Overload

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#502]
![playername overload](https://cloud.githubusercontent.com/assets/2363180/11217400/03178526-8d48-11e5-8b40-b74283688fb2.png)

Optional search - Search itself could probably do with less self referencing, though would need 'his or her' and 'he or she' and tense determiners.

**Comment by lodici** [comment]
:laughing: I think I read somewhere that if the gender is not clear then you can use "their", so it could be displayed as "...Monty Carlo searches their library for an Equipment card, reveals it, puts it into their hand, then Monty Carlo shuffles their library.". But still seems contrived to me. Tricky one, no easy solution.

**Comment by ShawnieBoy** [comment]
String manipulation fun in MagicRuleEventAction!

I personally don't like the 'he or she' etc. on the Magic cards themselves, but best to match that text. Would need a count to see how many times PN is being replaced and then switch to 'his or her' etc. But certainly no easy solution.
The one place where Groovy code is so much better for log messages.

**Comment by ShawnieBoy** [comment]
Forgot there were specific overrides for searching and shuffling - 22ee771186c41b88ba9db0039de5f2a678968a5d should help here

**Comment by lodici** [comment]
How about when the decision is no, make it short and sweet, for example  -  "Monty Carlo declines to activate SN's ability.". I think that is what makes the message so funny because it proceeds to describe in minute detail the activity that the player didn't actually perform anyway!

**Comment by ShawnieBoy** [comment]
Hehe, very true - and if there was a question about what the ability was, the linked name would point to that permanent to read.
