### ISSUE TITLE
AI & card advantage/disadvantage

### ISSUE THREAD

**Issue by PalladiaMors** [magarena/magarena#504]
Creating this issue to ask/debate whether it would be possible to include card advantage and disadvantage as factors that the AI takes into account in its line evaluations. Perhaps Melvin could explain if I'm correct in assuming that currently it doesn't take this into account? I have a feeling that this explains some misplays involving cards with self-sacrificing abilities and mass removal.

The major problem I see is that although the clear-cut general rule is that taking card advantage is good and card disadvantage is bad, there are exceptional situations where this isn't true. These nuances would probably be challenging to code.

But if possible, I'd like to see some discussion about this, my view is that it's an essential aspect of MtG's strategy and I don't see the AI becoming really strong without somehow being capable of taking card advantage into consideration when it evaluates play lines.

**Comment by melvinzhang** [comment]
Depends on what you mean by card advantage.. the AI doesn't count cards/permanent literally, it associates a score modification for every action.

The way MMAB works is that each action is associated with a score modification, for example the effect of playing a card to summon a creature involves two actions, removing the card from hand (negative score), and creating a creature on the field (positive score). 

The sum of these individual actions gives us the score modification of an effect. Summing up the score modifications of the all effects, give us the game score. Then MMAB seeks to find a line where it has the highest score, aka the most advantage.

MCTS works quite differently, it is not concerned with scores but it only considers wins and loses. Roughly speaking, it determines, via random simulations, the probability of win for each possible action. Then it picks the action with the highest probability of win.

**Comment by melvinzhang** [comment]
> I have a feeling that this explains some misplays involving cards with self-sacrificing abilities and mass removal.

I think we may be jumping the gun here a little, going to a solution without understanding the problem.
 
I think the best example of how we made progress on reducing misplays is #500 There we found that the AI did not find the winning line of play and there were various guesses as to why that occurs. 

The truth turns out to be stranger than anyone of us could imagine: the timing hint on the Jump card was too limiting, it prevented the AI from casting Jump during declare blockers phase.

We were able to discover the root cause because we had a small test game that can generate the misplay in a reliable way and from there we could observe the AI in action and discover why it made the play it did. Furthermore, when we make a fix, we were able to verify that with the fix in place (relaxing the pump timing restriction), the AI is now able to solve the test game and find the winning line.

**Comment by PalladiaMors** [comment]
Thanks Melvin, I think I understand things a bit more clearly now. So MCTS, the most promising AI, doesn't work by attributing scores to various lines, it's a different process. I hadn't managed to understand that so far.

In Minimax's case: when it evaluates an action, would it be possible to count how many cards and permanents it's going to spend in that line and how many of the opponent's cards and permanents from the opponent it's going to disable? Then, if the net result if negative for the AI, attribute negative score to this fact - that it's going to lose more cards than it's going to disable - thus attribute negative score to taking card disadvantage, and therefore making it more prone to reject such lines. The opposite would be done for gaining card advantage, which would be attributed positive score, making Minimax more prone to seeking such lines.

Unfortunately my lack of knowledge about programming prevents me from really being able to contribute to this discussion, but what I do know is that humans play this way - when they see that an action is going to cost them more cards than the opponent they tend to avoid it, and vice-versa. Of course I can't prove that this would improve the AI's play without statistical data, and it could be a pretty impactful change. I don't know, maybe Mike could test something of the sort in Firemind?

But yeah, sorry that I'm going out of my way to throw ideas about something I don't really understand, I just thought that this would be worth talking about. I don't want to be repetitive about this, but when I started playing MtG, it was often said that "the deck that gains the most card advantage should emerge the winner". Things are not quite as clear-cut today, since aggressive decks that take card disadvantage to try to finish the game quickly are fully viable nowadays, but I'm back to playing more or less regularly and still think that this thing is still massively important  in the game's strategy. Googling for "Magic the Gathering card advantage" hits plenty of interesting articles that discuss this subject. My intuitive idea is that, since this is central to how humans make decisions during games, it would have to be a part of the AI's thinking process as well?

**Comment by melvinzhang** [comment]
Sure, it is possible to count cards and permanents. But don't you think a system that takes into account the value of a permanent but better? 

For example, using two cards to kill a very powerful creature that would win the game if left unchecked, when the AI determines the negative score of casting the two cards + positive score of eliminating the permanent is a overall net win for it.

**Comment by PalladiaMors** [comment]
That does make sense, and I have no doubt that in some situations spending two cards to destroy one is the correct line of play, if there's something that's too much of a threat and just has to be eliminated, or you must do it in order to avoid losing. But it's a play I do with regret, because I know that I had to spend one extra card than he did, and in the future, because of this, everything else being equal, he'll have a threat that I'm not capable of dealing with.

I think that attributing a score to each card is fine, but I don't think we should skip that card advantage is a thing, and as much as possible you should seek to stay ahead in total number of cards and avoid getting behind. The way I see it, that's a separate thing going on, besides the value of each card. In the example you suggested, spending two cards to kill a very powerful creature. Besides calculating the value of both cards and comparing to the creature's, because this situation results in a net loss in number of cards, I'd place a further bias against the action, so that the AI only takes it it's forced to. To be honest, >99% of my experience in MtG is in Constructed, and I have no idea to what extent Limited, which Magarena is designed for, treats this differently.

I admit that there are plenty of situations that are exceptions to the general rule that losing more cards is bad and gaining more cards good, and totally agree that it's hard to theorize on how this change would impact the AI's play without a statistical sample. But this one is something I have a really huge feeling that could be "+EV", to put it in Poker terms - the AI would play better on most situations, even if it plays worse in a few situations, and I'd expect the net result to be a gain in strength.

Another idea I think is worth mentioning. Nowadays to an extent the decks that are trying to gain card advantage are called control decks. Once they stabilize the board and have gained card advantage, they intend to be able to answer any threat the opponent plays, while later playing their own threats, which the opponent won't be able to answer. Aggro decks don't care about card advantage nearly as much, they're trying to deal as much damage as they can as quickly as they can before the opponent manages to stabilize, finishing the game quickly. Now I realize that this is very generic and actual play of actual decks in actual situations isn't so simple, but I think in theory you could have an AI that's designed for control decks that strives strongly to gain card advantage, and an AI for aggro decks that doesn't care about that and is simply trying to deal as much damage as it can as quickly as possible.

Wish I could back these ideas with actual code but... yeah, I'm very limited in that regard. Of course I understand that suggesting a bunch of work to test something that we can't know for sure if it's going to work is a bit complicated.

**Comment by ShawnieBoy** [comment]
>Another idea I think is worth mentioning. Nowadays to an extent the decks that are trying to gain card advantage are called control decks. Once they stabilize the board and have gained card advantage, they intend to be able to answer any threat the opponent plays, while later playing their own threats, which the opponent won't be able to answer. Aggro decks don't care about card advantage nearly as much, they're trying to deal as much damage as they can as quickly as they can before the opponent manages to stabilize, finishing the game quickly.

This is a very valid point, as it can be seen on Firemind that control decks perform very badly, as the vast majority of decks in top ratings are Aggro, something the AI can play very well.

Having card advantage being taken into account for MCTS when multiple routes return a victory in a similar amount of time? Something that could be appraised on a separate level?

**Comment by melvinzhang** [comment]
> totally agree that it's hard to theorize on how this change would impact the AI's play without a statistical sample. 

At this stage, I think just a few simple game scenarios (like the one in #500) would be a good way to demonstrate the usefulness of including card advantage.

For example, they would show the current system disregarding card advantage and making a bad play. Which would be prevented by considering card advantage.

**Comment by PalladiaMors** [comment]
Question got answered and my curiosity is satisfied, so I'm closing the issue. Thanks guys, I think we had an interesting discussion!
