### ISSUE TITLE
Tooth and Nail Entwine function broken

### ISSUE THREAD

**Issue by tlorance** [magarena/magarena#513]
I have been away for a while and upgraded from 1.62 to 1.67.  I was playing the Tooth and Nail deck that puts Xenagos and Emrakul into play; however, when I played Tooth and Nail and payed the entwine cost, it only put them into my hand and not onto the board.  I can't seem to attache the log file from the relevant game, so the relevant section is reproduced below:

LOG (P): Tap <Bayou~1000039>. Tap <Bayou~1000041>. Tap <Bayou~1000042>. Tap <Savannah~1000044>. Tap <Savannah~1000046>. Tap <Savannah~1000043>. Tap <Taiga~1000049>. Pay {5}{G}{G}. tlorance may (yes) pay the entwine cost. Tap <Taiga~1000050>. Tap <Taiga~1000051>. Pay {2}. Play <Tooth and Nail~1000035>.
LOG (P): Search your library for up to two creature cards, reveal them, put them into your hand, then shuffle your library. Put up to two creature cards from your hand onto the battlefield. tlorance searches tlorance's library for up to two creature cards, reveals them, tlorance puts them into tlorance's hand, then tlorance shuffles tlorance's library. Found (<Emrakul, the Aeons Torn~1000005>). Found (<Xenagos, God of Revels~1000017>).
VEGAS cheat=false index=1 life=18 phase=Draw slice=6000 time=6006
* [-360/1271] (Sylvan Caryatid=M)
  [-396/1260] (Sylvan Caryatid=C)
VEGAS cheat=false index=1 life=18 phase=FirstMain slice=6000 time=6008
  [-503/1333] (pass)

**Comment by tlorance** [comment]
In a subsequent game, when I played the entwine cost it forced me to place two creatures from my current hand before allowing me to search for two creatures.  Relevant log section follows:

LOG (P): Play <Bayou~1000040>. Put <Bayou~1000040> onto the battlefield.
LOG (P): Tap <Bayou~1000039>. Tap <Bayou~1000042>. Tap <Bayou~1000040>. Tap <Savannah~1000043>. Tap <Savannah~1000046>. Tap <Savannah~1000044>. Tap <Taiga~1000050>. Pay {5}{G}{G}. tlorance may (yes) pay the entwine cost. Tap <Taiga~1000052>. Tap <Taiga~1000051>. Pay {2}. Play <Tooth and Nail~1000034>.
LOG (P): Tap <Bayou~1000039>. Tap <Bayou~1000042>. Tap <Bayou~1000040>. Tap <Savannah~1000043>. Tap <Savannah~1000046>. Tap <Savannah~1000044>. Tap <Taiga~1000050>. Pay {5}{G}{G}. tlorance may (yes) pay the entwine cost. Tap <Taiga~1000052>. Tap <Taiga~1000051>. Pay {2}. Play <Tooth and Nail~1000034>.
LOG (P): Search your library for up to two creature cards, reveal them, put them into your hand, then shuffle your library. Put up to two creature cards from your hand onto the battlefield. tlorance searches tlorance's library for up to two creature cards, reveals them, tlorance puts them into tlorance's hand, then tlorance shuffles tlorance's library. Chosen (<Sylvan Caryatid~1000015>). Chosen (<Llanowar Elves~1000006>). Found (<Xenagos, God of Revels~1000017>). Found (<Emrakul, the Aeons Torn~1000005>). Put <Sylvan Caryatid~1000015> onto the battlefield. Put <Llanowar Elves~1000006> onto the battlefield.
VEGAS cheat=false index=1 life=20 phase=FirstMain slice=6000 time=6011
  [-544/1177] (pass)

**Comment by ShawnieBoy** [comment]
This is fixed for the 1.68 release #460
