### ISSUE TITLE
Log entry switches from third to second person.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#520]
![screenshot00365](https://cloud.githubusercontent.com/assets/2443519/11431838/39ce8aea-9498-11e5-8011-ffc06d528384.png)

**Comment by lodici** [comment]
Suggestion - "...Mini Max may (no) pay 2 life. If not, Sacred Foundry enters the...".

**Comment by ShawnieBoy** [comment]
Going to be another 'he or she doesn't' I'm afraid :cry: 
Matches the string conversion done elsewhere that way. Should have noticed this while renaming the triggers.

**Comment by ShawnieBoy** [comment]
It's a shame the final part after a choice can't be changed depending on the choice.

**Comment by ShawnieBoy** [comment]
fixed in c3c0390817567d0c35da21e2ce66792a852ae640
