### ISSUE TITLE
Creature token naming

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#522]
Currently with tokens, they are named as they appear in the referring card:

e.g. 
"1/1 green Snake creature token"
"2/2 blue Djinn Monk creature token with flying"

If a token has a more detailed ability, normally one in quotations in the referred card, this is normally omitted.

e.g.
1/1 black Assassin creature token with "Whenever this creature deals combat damage to a player, that player loses the game." is called "1/1 black Assassin creature token"

The slight issue with this, is that if in the future there is another card with the same name, but without those abilities, it may grab one with an attached groovy code.

One option would be having tokens only represent the basic structure - Type, color, power/toughness etc. but having everything after the 'with' added to the token as a gained ability.

Another option would be for tokens with groovy to be named "with groovy", and if duplications then "with groovy2" etc.

At the moment there's no big conflicts with this, but I can see that in the future, some token types may end up clashing.

**Comment by ShawnieBoy** [comment]
It has finally happened: Goblin Spymaster creates a 1/1 red Goblin creature with "Creatures you control attack each combat if able."

It obviously cannot refer to a normal 1/1 red Goblin creature token

**Comment by melvinzhang** [comment]
If the short name clashes, just make the name longer, so in the case the name should include the ability, i.e. `name=1/1 red Goblin creature with "Creatures you control attack each combat if able."`
