### ISSUE TITLE
playSound unable to create new native thread

### ISSUE THREAD

**Issue by tlorance** [magarena/magarena#526]
CRASH REPORT FOR MAGARENA THREAD Thread[Thread-2476,1,main]
CREATED ON 2015/11/29 13:53:37
MAGARENA VERSION 1.67, JRE 1.8.0_65, OS Mac OS X_10.10.5 x86_64
================================
Used Memory: 1543M
Free Memory: 307M
Total Memory: 1851M
Max Memory: 3641M
================================

Turn : 10  Phase : EndOfTurn  Step : NextPhase  Player : tlorance  Score : -15109
0] Player : tlorance  Life : 6  Delayed : Total=0
   - Hand : Galvanic Blast
   - Hand : Master of Etherium
   - Graveyard : Memnite
   - Graveyard : Memnite
   - Graveyard : Arcbound Ravager
   - Graveyard : Inkmoth Nexus
   - Graveyard : Signal Pest
   - Graveyard : Vault Skirge
   - Permanent : Blinkmoth Nexus
   - Permanent : Blinkmoth Nexus  Tapped
   - Permanent : Darksteel Citadel  Tapped
   - Permanent : Steel Overseer  Power : 1  Toughness : 1  Damage : 0  Summoned
1] Player : Les Vegas  Life : 12  Delayed : Total=0
   - Graveyard : Merfolk Sovereign
   - Permanent : Cursecatcher  Power : 3  Toughness : 3  Damage : 0  Summoned
   - Permanent : Island  Tapped
   - Permanent : Island
   - Permanent : Island
   - Permanent : Master of the Pearl Trident  Power : 1  Toughness : 1  Damage : 0  Tapped
   - Permanent : Master of the Pearl Trident  Power : 3  Toughness : 3  Damage : 0  Tapped
   - Permanent : Triton Shorestalker  Power : 3  Toughness : 3  Damage : 0  Tapped

Stack : 0

[list of actions removed to save space]

Score = -15091

Exception from controller.runGame: unable to create new native thread
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:714)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1105)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1175)
	at magic.data.SoundEffects.playSound(SoundEffects.java:45)
	at magic.data.SoundEffects.playGameSound(SoundEffects.java:26)
	at magic.model.phase.MagicEndOfTurnPhase.executeEndOfPhase(MagicEndOfTurnPhase.java:32)
	at magic.model.phase.MagicPhase.executePhase(MagicPhase.java:49)
	at magic.model.MagicGame.executePhase(MagicGame.java:468)
	at magic.ui.SwingGameController.executeNextEventOrPhase(SwingGameController.java:780)
	at magic.ui.SwingGameController.runGame(SwingGameController.java:722)
	at magic.ui.duel.DuelPanel$2$1.run(DuelPanel.java:129)

 
![crash](https://cloud.githubusercontent.com/assets/11671821/11460456/76ca1b84-96a1-11e5-92f2-7ad71d509ace.png)

**Comment by tlorance** [comment]
Clearly, I have forgotten the trick to uploading .log files; why doesn't GitHub support that file type?

**Comment by lodici** [comment]
> Clearly, I have forgotten the trick to uploading .log files; why doesn't GitHub support that file type?

Try adding ".txt" as the extension.

Looks like a sound issue. Please open the preferences dialog, then the Audio tab and make sure all settings are switched off.

**Comment by lodici** [comment]
What I could not work out was that the error occurred on a line within a try..catch clause so I would have expected it to have been handled more gracefully.

**Comment by melvinzhang** [comment]
Error is not a subclass of Exception.

**Comment by melvinzhang** [comment]
Error is usually unrecoverable, so it is good to know about it. See https://stackoverflow.com/questions/912334/differences-betweeen-exception-and-error

**Comment by melvinzhang** [comment]
The Java native sound API is rather clunky. Previously you added TinySound and it supports volume control as well. Shall we update game sounds to also be played with TinySound?

**Comment by lodici** [comment]
Thanks for the clarification and links. TinySound sounds like the way to go then.

**Comment by melvinzhang** [comment]
Always close sound clip after it is completed to close potential resource leak.
