### ISSUE TITLE
Size of card popup during gameplay is too large.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#527]
The default size of the card popup at 480 x 680 is way too large especially with the smaller ``magiccards.info`` images.

![screenshot00372](https://cloud.githubusercontent.com/assets/2443519/11469253/fad88842-974c-11e5-9ba0-bc3fe87403e3.jpg)

**Comment by lodici** [comment]
The size can be adjusted in preferences by reducing the ``popup scale`` setting but this is a confusing setting in my opinion. Suggest...
- __Original__ : image is displayed at its original size.
- __Predefined__ : image is scaled up or down to a predefined size - ``312 x 415``, ``480 x 680``, etc.
- __Custom__ : user selects an image with the required dimensions. Check that w:h ratio is 0.71 ± 0.01.

**Comment by ShawnieBoy** [comment]
I have to say the scaling is making the cards look pretty ugly - even when they're the same size as the pop-up size

**Comment by lodici** [comment]
There is an issue with card preview stage of the animation - if it cannot be shown at its native size then it will use the very low quality scaling that is used for the animation. I need to fix that. There should be no issues with the popup image which should be using high quality scaling,

**Comment by ShawnieBoy** [comment]
I see, I thought they were somehow linked. The pop-ups are fine (I'm also liking the duel startup window too :grinning:
