### ISSUE TITLE
Modified P/T overlay does not work with variable preferred image size.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#533]
![screenshot00374](https://cloud.githubusercontent.com/assets/2443519/11516954/a0ec3e04-987e-11e5-9a62-fa7b51f66c6b.png)

**Comment by ShawnieBoy** [comment]
May have some problems with this as there's currently four different card frames in use, I doubt they'll all line up.

**Comment by lodici** [comment]
Well that was always the case - this just fixes what I basically broke with the new preferred image size setting.

**Comment by lodici** [comment]
Updated to fit two styles.
![screenshot00378](https://cloud.githubusercontent.com/assets/2443519/11526229/ec2a9bd4-98d0-11e5-892d-5cb05ff51f4d.png)

**Comment by lodici** [comment]
Another solution could be to add the modified P/T as a tab at the bottom RHS of the card similar to the way additional abilities are displayed (see image). That way you could also see the original P/T.
![screenshot00379](https://cloud.githubusercontent.com/assets/2443519/11526292/6c4f2154-98d1-11e5-98ad-b6f0e1e08f2a.png)
