### ISSUE TITLE
Strange instances of a single number in brackets in log message.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#534]
I have noticed this a few times recently...
![screenshot00377](https://cloud.githubusercontent.com/assets/2443519/11517119/8e312da0-987f-11e5-8968-362c61aa047c.png)

**Comment by ShawnieBoy** [comment]
This is from the 'GainLifeYou' in RuleEventAction - I think it's for life gain 'for each' to give a total.
The total is calculated wrong, and the 'for each' is an optional part of the regex, so it appears for all life gain
