### ISSUE TITLE
additional (1) in log for Scroll of Griselbrand ability and other lose life effects

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#537]
See second log from the top in 
![screenshot](https://cloud.githubusercontent.com/assets/1620634/11531250/6ca1cd86-9936-11e5-8747-bbba03bb8369.jpg)

**Comment by lodici** [comment]
see also #534.

**Comment by melvinzhang** [comment]
#534 has been fixed, this is new.

**Comment by lodici** [comment]
Well presumably it is related? Quite a coincidence if not.

**Comment by ShawnieBoy** [comment]
Ahh, found it - It's a similar problem. This is for Discard 'for each' - I'll do the same fix

**Comment by ShawnieBoy** [comment]
Fixed with a2e2b1e9723b40a425b0f81ce3269dc11e0edc4a

**Comment by ShawnieBoy** [comment]
Also done the same for LifeLossYou - other instances of 'for each' are not optional
