### ISSUE TITLE
Slightly better looking images in player's hand?

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#545]
By changing the scaling algorithm it is possible to affect the image quality of the cards in your hand. The following screenshots are before (ie. current implementation) and after.

![screenshot00403](https://cloud.githubusercontent.com/assets/2443519/11607211/a971857a-9b35-11e5-94d1-f1ef7f3cc5c5.png)
![screenshot00404](https://cloud.githubusercontent.com/assets/2443519/11607213/ac3e0102-9b35-11e5-830c-1099645a338e.png)

To my eyes, the text looks better and the card names slightly easier to read in the second but the artwork seems more blurry. At the sizes used in the hand zone I don't think it matters either way, I would still identify a card more by the picture than the text on the card. But just thought I would throw it out there anyway!

**Comment by melvinzhang** [comment]
what were the two algorithms shown here?

**Comment by lodici** [comment]
[Image #1](https://github.com/magarena/magarena/blob/master/src/magic/ui/duel/viewer/ImageCardListViewer.java#L244)
[Image #2](https://github.com/magarena/magarena/blob/master/src/magic/ui/utility/GraphicsUtils.java#L54)

**Comment by melvinzhang** [comment]
Thanks! The second one looks a bit better for me. The first one looks fairly jagged, when the second one is more blurred but looks like there are less artifacts from the scaling.

**Comment by lodici** [comment]
I agree that the second image looks slightly better even if the text is still illegible (to my eyes). I will update the scaling for the hand images but leave the permanents for now - see if anyone notices.
