### ISSUE TITLE
Overload and AI restrictions

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#548]
Spells that can be 'Overloaded' would probably require AI casting restrictions as they then become untargeted (Generally `each <target> you don't control`) Just had the AI cast an overloaded [Electrickery](http://magiccards.info/rtr/en/93.html) with an empty battlefield.

Would this be able to be attached somehow to the Overloaded version, or would having it on the script itself be better? Without being overloaded they always target so could look a bit strange.

**Comment by melvinzhang** [comment]
On the script would be better.

**Comment by ShawnieBoy** [comment]
Cool - I'll do the edits now, there's not many.

**Comment by ShawnieBoy** [comment]
[Counterflux](http://magiccards.info/c15/en/214.html) is a bit of a strange one.

**Comment by ShawnieBoy** [comment]
There's also a problem with `Cast SN with AI only if you control a creature` for some reason, I've had a look at the parsing, and it should work ok as there is a condition that matches.

**Comment by melvinzhang** [comment]
what's the problem with it?

**Comment by ShawnieBoy** [comment]
The problem is me, lol :grimacing: Typo.
However Counterflux would need something like `Cast SN with AI only if an opponent has a spell on the stack`?

**Comment by melvinzhang** [comment]
Counterflux timing is counter, so it will only be cast by AI when there is an opponent's spell on the stack (that is the restriction implemented by timing=counter).

**Comment by ShawnieBoy** [comment]
Ahh yes, of course - That solves everything. Thanks.
