### ISSUE TITLE
Voice of Resurgence trigger during combat

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#550]
The casting trigger for Voice of Resurgence doesn't seem to trigger when attacking with it, and the opponent has priority. (I should have captured the game-state but was looking for something else)

It was going to die from combat damage, and the AI cast a spell - Once everything resolved, the death trigger and casting trigger should have both resolved, however only one did (I'm assuming the death trigger)

**Comment by melvinzhang** [comment]
Unable to replicate. When opponent casts a spell as Voice of Resurgence was attacking, the casting trigger fired and put at token into play.
