### ISSUE TITLE
 A copied Ally will not trigger other Ally abilities

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#553]
Cards which enter the battlefield as a copy of another card/permanent have a few bugs and inconsistencies which require looking at.

On the whole it's a veritable minefield of problems, for the game in real life, and for Magarena.

Currently it is functioning as a 'when cast' effect instead of an 'enters the battlefield' effect, so entering the battlefield in other ways is not activating the ability.

Even when it does enter the battlefield, it doesn't trigger enter the battlefield abilities from other permanents regarding the copy's attributes, e.g. A copied Ally will not trigger other Ally abilities.

#93 Also shows that removing the copied target is countering the spell due to no valid targets. (This may have been fixed)

I was wondering if an enters the battlefield replacement effect could return the card to the stack with the copied attributes.

**Comment by ShawnieBoy** [comment]
And some general improvements to the distinction between "As SN enters the battlefield", "SN enters the battlefield with" and "When SN enters the battlefield" - three very close, yet separate timings.

**Comment by melvinzhang** [comment]
I'll focus this issue on the following as it is the only with the specific example that we can test and confirm a fix. 

"A copied Ally will not trigger other Ally abilities."

For the other issues, please open separate issues for them. Each one should contains a when I did X, I observed Y, but it should be Z example. Even better if they can have a test game/test case.

**Comment by melvinzhang** [comment]
I'm unable to replicate this issue. I added Tuktuk Grunts to TestClone in above commit, then I cast "Phantasmal Image" copying "Tuktuk Grunts", both the original Grunts and the copied Grunts trigger was put on the stack as expected.

**Comment by ShawnieBoy** [comment]
Try Jwari Shapeshifter - That was the card that didn't trigger the opponents allies

**Comment by melvinzhang** [comment]
Thanks, specific details like this are very important. I'll give it a try.

**Comment by melvinzhang** [comment]
I did the same actions, with Jwari Shapeshifter instead of Phantasmal Image, both triggers got put onto the stack as expected.

**Comment by ShawnieBoy** [comment]
Strange - let me put a different test together

**Comment by melvinzhang** [comment]
If I choose no for Jwari Shapeshifter copy, it comes into play as an Ally itself and Grunts trigger fired as per normal for Ally entering the battlefield.

**Comment by ShawnieBoy** [comment]
I think I may have been misreading the cards, the opponent ones were probably "under your control" some are for any - My mistake. I'll test for the other situations as well.

**Comment by ShawnieBoy** [comment]
Wow.

How does the spell-card effect manage to cope with effects like "put this card onto the battlefield" or even flicker effects?

**Comment by melvinzhang** [comment]
Which "spell-card effect" are you referring to?

**Comment by ShawnieBoy** [comment]
MagicSpellCardEvent() The event for the cloning. I was assuming this would only occur when cast as a spell

**Comment by melvinzhang** [comment]
That's because some time ago I fixed PlayCardAction, so it uses the spell card event as some cards modify this. PlayCardAction simulates the casting of the card by creating a fake MagicCardOnStack and gets the spell card event. See https://github.com/magarena/magarena/blob/8621e97374345ddb69fd82033897ba100dcd9f73/src/magic/model/action/PlayCardAction.java#L44

**Comment by ShawnieBoy** [comment]
Cool :smile: I've been skirting around submitting 'enter as copy' cards due to thinking there were still issues with them. Looks like that's no longer the case. Time to add some more then!

Thanks for looking at these and the explanation - case closed
