### ISSUE TITLE
implement vancouver mulligan

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#557]
> To perform a Vancouver mulligan, the player returns his or her hand to his or her library, then draws a hand of one fewer card. Once all players keep their opening hands, each player with fewer cards than their starting hand size may scry 1. -- http://mtgsalvation.gamepedia.com/Mulligan#Vancouver_mulligan

**Comment by ShawnieBoy** [comment]
I had completely forgot about the new mulligan changes. :+1:

**Comment by lodici** [comment]
Will this require a UI update? Presumably, on closing the Mulligan screen the user prompt will display the scry prompt if appropriate, so I am assuming not.

**Comment by melvinzhang** [comment]
Yes, that's how it works in this first-cut implementation. Please try and see if it feels confusing. The initial scry seems a bit abrupt if you have never heard the new rule.

**Comment by lodici** [comment]
It is probably fine as long as you are aware that you are playing a Vancouver mulligan.The mulligan screen can be updated to make it a bit clearer -
![screenshot00412](https://cloud.githubusercontent.com/assets/2443519/11766812/81f223be-a18f-11e5-8afa-034a5adce7b1.png)

**Comment by melvinzhang** [comment]
@lodici Looks good! Please add this in. The tooltip is especially helpful.
