### ISSUE TITLE
eliminate minimum loading time of 3s

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#560]
I was puzzled by the long load time of the loading screen. Digging into the implementation, I found that in DuelGameScreen.StartupWorker, there is a parameter MINWAIT. After completing the game logic, the thread sleeps an amount of time to make the total loading time at least 3s.

Removing the call to Thread.sleep reduces my loading time to less than 1s. Consequently, I only saw one loading message instead of three. One of our goals is being fast to play, I feel that getting the player into the game quicker is preferable over having them see more loading screen messages.

**Comment by melvinzhang** [comment]
@lodici are there some technical issues when the loading goes too fast? I think we should not set a minimum loading time, it should be as fast as the user's machine can perform the task. 

For users with slower machines, they will naturally take longer and they will be able to view more loading messages. For users with faster machines, they should be able to get into the game sooner.

**Comment by lodici** [comment]
> One of our goals is being fast to play, I feel that getting the player into the game quicker is preferable over having them see more loading screen messages.

I disagree. I hardly think 3 seconds at the start of each game is going to have players jumping up and down with impatience. I think it acts like a natural pause, a delineation between the game proper and all the other extra screens and functionality - prepare yourself, take a breath, gird your loins, etc. Given that the default AI thinking time is 6 seconds, gameplay is hardly a quickfire experience anyway so I think this slight delay fits with the overall rhythm of a card strategy game where brains rather than trigger finger rule.

I would like to leave it as-is for the next release. Obviously if there is huge uproar it is easy enough to remove. We can always disable it completely for development purposes if it is proving an irritation.

**Comment by melvinzhang** [comment]
By "fast to play" I mean relatively quick to get into a game and starting thinking about what move to make. I do not mean each move is made in a short amount of time. For me, the loading screen is dead time, whereas on the mulligan screen or during AI think, I can continue to look at my hand/battlefield and plan my next move. 

When I have all my duel settings prepared, I just hit "Resume Duel", "Game 1" and I'm in, ready to play. The loading screen adds unnecessary delay. My initial assumption is that the program got slower and not that we added in a natural pause. I understand that my view may be biased as I'm more aware of the implementation details, so I think we should bring this up on the forum where more users can pitch in.

**Comment by lodici** [comment]
>  For me, the loading screen is dead time, whereas on the mulligan screen or during AI think, I can continue to look at my hand/battlefield and plan my next move.

It's 3 seconds! Once per game. I think you are coming at this from a developer/tester POV instead of a normal game player who will start a new game on average what? once every 10 to 20 minutes. Look at any commercial game, most have a loading screen usually for much longer than 3 secs.

**Comment by ShawnieBoy** [comment]
Loading screens are generally something to display while the computer is thinking, giving the player info that the game hasn't crashed and is still functioning.

If there is no thinking time involved during a set-up, a loading screen wouldn't be displayed. Loading screens in general are seen as a negative, something which developers try and remove where they can (and sometimes advertise as a bonus "No loading screens!").

Adding in an artificial loading screen seems a bit strange to me, if the program isn't doing anything during that time, why is it there?

**Comment by melvinzhang** [comment]
Yes, I am biased as a developer, I have acknowledged this in my previous post. My strong feelings against this is that it goes against one of the key goals, which is that it is quick and east to start a new game and begin playing.

**Comment by lodici** [comment]
I have added a new setting to the Gameplay tab which lets you turn off the game loading screen. I have also reduced MINWAIT to one second which is feels like enough to get a sense of transition - there needs to be a MINWAIT otherwise the loading screen flashes up very briefly which is jarring and messy.

**Comment by melvinzhang** [comment]
Thanks for the changes. When the loading screen transitions to the mulligan screen, I don't find it jarring when sleep is disabled, since what pops up briefly is the loading message. The background stays the same on the mulligan screen.

If there is no mulligan screen, then yes, it would be rather jarring. I would like to propose a further fine tuning: minimum wait time only applies if mulligan screen is disabled (goes straight to battlefield screen)

**Comment by lodici** [comment]
Nice try.  I get it - you don't want the delay whereas I think it is perfectly reasonable to smooth the transition to the Mulligan screen or game board. It is akin to using animations which slow down gameplay but which I think makes the game more playable. Still if you don't like it you can switch it off. You have already jumped the gun somewhat with your leading post on the forum when no-one can actually test the feature so I think the least we can do is let people decide for themselves by including it in the next release.

**Comment by melvinzhang** [comment]
Most users will not bother to customize the settings, the out-of-box behavior is important (search for " tyranny of the default"). While the option to customize is good, the default is that the loading screen shows and adds delay to the game load process which is contrary to our goal of making it quick to start.

**Comment by melvinzhang** [comment]
Looking into the load time for starting the game, the main culprit is ability parsing when construct the MagicCard objects. I'm looking into whether that can be reduce or eliminated so that loading time can be reduced.

**Comment by melvinzhang** [comment]
Not much luck there, as doing the ability load in MagicCard constructor seems to be the best place to work in different situations such as regular game and test game.
As it is not clear cut this is a desirable feature, it is safer to make this optional rather than default. Interested users can enable it in their settings.

**Comment by lodici** [comment]
Unbelievable. I think you are totally out of order.

**Comment by melvinzhang** [comment]
That was not my intention, I did not realize the default is a controversial change. Previously, when we had an optional feature that was not a clear win for everyone, we left it off by default, such as with HideAiActionPrompt.

In this case, it looks like we have different opinions on what the default for this option should be, I'll create a separate issue to vote on this.
