### ISSUE TITLE
Split Colorless and Generic mana

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#562]
With colorless mana now having it's own 'color' symbol and code `{C}` - There needs to be a renaming of current usage of 'colorless' to 'generic' to represent any color of mana, including colorless - to distinguish it from 'colorless only' costs

**Comment by ShawnieBoy** [comment]
107.4b Numeral symbols (such as {1}) and variable symbols (such as {X}) represent generic mana in costs. Generic mana in costs can be paid with any type of mana.

**Comment by melvinzhang** [comment]
one of the places to be changes is MagicCostManaType, the current Colorless enum should be renamed to Generic and a new Colorless enum added after Snow with value Arrays.asList(MagicManaType.Colorless)

**Comment by melvinzhang** [comment]
tested a card with colorless cost, payment works correctly.
