### ISSUE TITLE
decks screen as loading screen

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#564]
While playing with no loading screen, I realized that the decks screen (where you view your deck and the AI's deck) itself could serve as a loading screen. 

When the "game n ->" button is clicked, it changes to a please wait button, and all buttons that let you modify the deck are removed. The middle of the bottom action bar could also be used to display loading messages.

Once the load is complete, the deck screen is removed and you get into the game. The benefit is that you can continue to browse through your deck and your opponent's deck while waiting.

**Comment by lodici** [comment]
As it is not clear cut this is a desirable feature, it is safer to make this optional rather than default. Interested users can enable it in their settings.

**Comment by melvinzhang** [comment]
If added, will definitely make it optional. For now, we will be using loading screen with MT related messages. Should test one loading screen at a time, so shelving this for now.
