### ISSUE TITLE
propose to default showGameLoadingScreen to disabled

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#565]
The new game loading screen allows users to enable a loading screen before the mulligan screen loads. Some discussions on this feature occurred on https://github.com/magarena/magarena/issues/560 and it was modified into a configurable option.

Currently the option defaults to enabled, I'm proposing to change this to disabled by default for the next release. We are tied 1-1 for this at the moment, @ShawnieBoy please let us know your preference for the default to help break the tie.

**Comment by ShawnieBoy** [comment]
Personally, either option is counter-intuitive.

The answer is for loading screens to appear where they are needed - as similar to the splash screen which covers the thinking time during set-up, and the AI-thinking animated.gif.

If there is a loading time for lower-spec pc's or tablets (Which I'm assuming there are plenty of) then a loading screen makes sense.

There shouldn't be an option to turn it on or off, it should just be.

**Comment by melvinzhang** [comment]
That is assuming that loading screens are the only way. The two options here are actually loading screen or current screen + busy cursor.

For reference, the behavior in 1.68 is to show the background image with spinning cursor in the middle. What I like about the 1.68 behavior is that there is no enforced minimum time to show this screen, it goes away as soon as the cards to mulligan shows up.

To rephrase a bit, the two options amount to the following:

Method A: Show a loading screen with various "MTG related but slightly irreverent" progress messages for at least 1s.

Method B: Stay on decks screen and switch to a busy spinning cursor.

Profiling shows that the waiting time after starting and before mulligan choice is mainly attributed to evaluation of card abilities in loadAbilities for the cards used in the particular match.

@ShawnieBoy any preference for method A or B? Or perhaps there is a better way?

**Comment by ShawnieBoy** [comment]
As a personal preference I'd go for version A, as I don't use the mulligan screen.

The loading screen would more clearly display 'thinking time' than a 'busy' cursor.

I spend my time more in dev mode, so it would make more sense to release the loading screen and then make any adjustments to it based on user feedback, or if the card loading time can be reduced, as in dev mode I think everything is loaded up-front.

**Comment by melvinzhang** [comment]
Yup, I'm hopeful we'll figure out how to eliminate the loading time due to ability parsing. Method A it is then. Proposed change is not accepted.
