### ISSUE TITLE
Loading screen solution.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#566]
This should leave everyone happy. The solution is to use the DuelDecksScreen as the loading screen and start setting up the game in the background as soon as it is opened instead of when clicking on "Game 1". Once the game is ready then the next game button is displayed (see demo). No artificial delays required. The rough idea is shown below - just needs refining.

![capture-2](https://cloud.githubusercontent.com/assets/2443519/11857331/2ff5d822-a44f-11e5-848d-a682dc5653a7.gif)

**Comment by melvinzhang** [comment]
Brilliant! It should work for "New duel" as well, as long as when the deck is changed the start game button is removed and the duel is notified to generate a new game via nextGame. The "show next game button only when ready" trick is amazing, simple and clean.

**Comment by melvinzhang** [comment]
Something to note about nextGame. Card script parsing is cached, only the first first call to nextGame is slow, subsequent calls for game 2, 3 etc will be very fast as the cards remain the same.

**Comment by melvinzhang** [comment]
Thinking through this, it will be harder to apply this for the first game since the player is allowed to change the deck very quickly using the generate deck button. Doing a card parse each time the deck is changed will consume unnecessary memory as only the cards in the last deck are used.

**Comment by lodici** [comment]
> Something to note about nextGame. Card script parsing is cached, only the first call to nextGame is slow, subsequent calls for game 2, 3 etc will be fast as the cards remain the same.

I deliberately it slowed down for the demo. Unrestricted, in subsequent calls the next game button appears immediately.

> Thinking through this, it will be harder to apply this for the first game since the player is allowed to change the deck very quickly using the generate deck button. Doing a card parse each time the deck is changed will consume unnecessary memory as only the cards in the last deck are used.

If a deck is changed then I was planning on simply re-running new game setup in the background again with the new deck(s). Usability-wise, you can disable the Generate button until the new game is ready or alternatively you can leave the Generate button enabled and cancel the running background task on each click which lets you flick through decks more or less as you do now. I am not totally clear on how game setup uses memory but assume that it would be released if setup was cancelled because the task was interrupted.

**Comment by lodici** [comment]
It seems to handle the memory ok - here is some debug memory info when clicking Generate quickly and using the cancel running task approach
```
Worker cancelled : Used Memory: 90M, Free Memory: 51M, Total Memory: 142M, Max Memory: 494M
Worker cancelled : Used Memory: 91M, Free Memory: 50M, Total Memory: 142M, Max Memory: 494M
Worker cancelled : Used Memory: 91M, Free Memory: 50M, Total Memory: 142M, Max Memory: 494M
Worker cancelled : Used Memory: 92M, Free Memory: 49M, Total Memory: 142M, Max Memory: 494M
Worker cancelled : Used Memory: 93M, Free Memory: 48M, Total Memory: 142M, Max Memory: 494M
Worker cancelled : Used Memory: 94M, Free Memory: 47M, Total Memory: 142M, Max Memory: 494M
Worker cancelled : Used Memory: 94M, Free Memory: 47M, Total Memory: 142M, Max Memory: 494M
Worker cancelled : Used Memory: 95M, Free Memory: 46M, Total Memory: 142M, Max Memory: 494M
Worker cancelled : Used Memory: 96M, Free Memory: 45M, Total Memory: 142M, Max Memory: 494M
Worker cancelled : Used Memory: 97M, Free Memory: 44M, Total Memory: 142M, Max Memory: 494M
Worker cancelled : Used Memory: 98M, Free Memory: 43M, Total Memory: 142M, Max Memory: 494M
Worker cancelled : Used Memory: 99M, Free Memory: 42M, Total Memory: 142M, Max Memory: 494M
Worker cancelled : Used Memory: 99M, Free Memory: 42M, Total Memory: 142M, Max Memory: 494M
Worker cancelled : Used Memory: 100M, Free Memory: 41M, Total Memory: 142M, Max Memory: 494M
Worker cancelled : Used Memory: 101M, Free Memory: 40M, Total Memory: 142M, Max Memory: 494M
Worker cancelled : Used Memory: 102M, Free Memory: 39M, Total Memory: 142M, Max Memory: 494M
Worker cancelled : Used Memory: 103M, Free Memory: 39M, Total Memory: 142M, Max Memory: 494M
Worker cancelled : Used Memory: 103M, Free Memory: 38M, Total Memory: 142M, Max Memory: 494M
Worker cancelled : Used Memory: 104M, Free Memory: 37M, Total Memory: 142M, Max Memory: 494M
Worker cancelled : Used Memory: 105M, Free Memory: 36M, Total Memory: 142M, Max Memory: 494M
Worker cancelled : Used Memory: 67M, Free Memory: 74M, Total Memory: 142M, Max Memory: 494M
Worker cancelled : Used Memory: 68M, Free Memory: 73M, Total Memory: 142M, Max Memory: 494M
Worker cancelled : Used Memory: 69M, Free Memory: 72M, Total Memory: 142M, Max Memory: 494M
```

**Comment by melvinzhang** [comment]
Looks good to go then :)
