### ISSUE TITLE
clicking on "face-down creature" link on log/stack shows actual card, should show morph card

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#567]
kannikkiy @ http://www.slightlymagic.net/forum/viewtopic.php?f=82&t=17929&p=190003#p189990 reports the following bug:

AI casts Ainok Survivalist with morph, it goes onto the stack as "Put [face-down creature] onto the battlefield". The part in [] is a blue link, clicking on the link shows the Ainok Survivalist card in the center of the battlefield. It should show the Morph reminder card.

**Comment by melvinzhang** [comment]
Bug also occurs when clicking link in the log.

**Comment by melvinzhang** [comment]
UI gets cardId as input, MagicCard does not know whether it was cast as morph or using normal method.

**Comment by melvinzhang** [comment]
one solution is for getMagicCard to should return the proper context, for spell on stack, it should return MagicCardOnStack instead of MagicCard, for permanent on the battlefield it should return MagicPermanent. Subsequent methods should use only the interface MagicObject instead of MagicCard.

**Comment by melvinzhang** [comment]
doesn't quite work, all the downstream methods require MagicCard, as it looks for the location

**Comment by melvinzhang** [comment]
@lodici any thoughts on how we can approach this bug?

**Comment by melvinzhang** [comment]
Quick summary of the issue: the problem is because MagicCard has no knowledge of morph, it is always the actual card. Morph creates a special MagicCardOnStack that returns the morph definition as getCardDefinition, so that when you mouse over the source in the stack, it shows the Morph reminder card and not the actual card. However, clicking on the link in the stack/log uses the MagicCard which shows the true card.

**Comment by lodici** [comment]
I think we will probably need to update [GameViewerInfo.getMagicCard()](https://github.com/magarena/magarena/blob/master/src/magic/ui/duel/GameViewerInfo.java#L108) to return not a MagicCard but a viewer object containing the required info for displaying the correct image.

**Comment by melvinzhang** [comment]
Sounds good! A custom viewer object makes a lot of sense, I was thinking along the lines of modifying the API for existing game objects but a custom viewer object would be much better.  Can I trouble you to design the class for the viewer as you are more familiar with the kind of data needed for showing the card properly?

**Comment by lodici** [comment]
The same problem occurs when running the play from hand animation in that it shows you the front face so I will look at as well.

**Comment by melvinzhang** [comment]
Good catch on the animation bug. Thanks for taking care of this.

**Comment by lodici** [comment]
I have solved the log entry but have hit a bit of brick wall when it comes to the animation and possibly the stack item. In a nutshell I have identified the MagicCard being played (Ainok Survivalist ) but do know how to determine whether it is being played face down or not. @melvinzhang is there a property/method I can use and if not can one be added?

**Comment by melvinzhang** [comment]
MagicCard doesn't know, you need to look at the MagicCardOnStack. Similarly for a Morph permanent on the battlefield, you have to check with the MagicPermanent, the underlying MagicCard is no different from a non-morph permanent.

From the model point of view, the resolution of the Morph cast event removes the card and adds it to the stack in one single event. If I'm reading the code right, after the event occurs, then the animation plays as updateGameView is after executeNextEventOrPhase. So in that case the card is already on the stack, if the playing of the card leads to a item on the stack, it is better to show the card definition obtained from MagicCardOnStack instead of showing the MagicCard.

**Comment by melvinzhang** [comment]
I briefly looked over the getPlayCardAnimationInfo, one way to get the card on stack is to do a "diff" of the stack between the oldinfo and newinfo. The extra stack item will be the card on stack for the just played card.

**Comment by lodici** [comment]
Awesome, so if I just get ``newGameInfo.getStack().get(0).itemOnStack.getCardDefinition()`` it will always be the card definition visible to the player?

**Comment by melvinzhang** [comment]
Yes, if there is a new card on stack, we should use its getCardDefinition instead of the one from MagicCard. Note that there may not always be a new card on stack, some cards do not use the stack, eg lands.

**Comment by lodici** [comment]
That should be ok, I can test for this. I have never understood why there are all these different "card" classes - in my mind you should only need MagicCardDefinition for base properties and MagicGameCard for the in-game card.

**Comment by ShawnieBoy** [comment]
>I have never understood why there are all these different "card" classes - in my mind you should only need MagicCardDefinition for static base properties and MagicGameCard for tracking the life-cycle of the in-game card.

Does mess with my head on occasion as well - Seeing as the Stack is a zone, treating it like an ordered Graveyard, with abilities being represented as ability-cards kinda makes more sense to me.

I'm sure there's plenty of reasons why though :grinning:

**Comment by lodici** [comment]
@melvinzhang please can you explain how the following methods in MagicItemOnStack return a different MagicCardDefinition given that their implementations appear identical. Thanks.
```
    @Override
    public MagicCardDefinition getCardDefinition() {
        return getSource().getCardDefinition();
    }
    
    // only for rendering the card image popup
    final public MagicCardDefinition getRealCardDefinition() {
        return getSource().getCardDefinition();
    }
```

**Comment by melvinzhang** [comment]
@lodici These two implementations return the same thing but note that these are just the default implementations. MagicItemOnStack is an abstract class that generalizes spells, triggers, and activated abilities. The individual subclasses can override these methods if they want to do something different.

In particular, MagicMorphCastActivation returns an instance of MagicCardOnStack that overrides getCardDefinition to return the Morph definition.
