### ISSUE TITLE
Revise Mana.png

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#571]
Some of the symbols are out of alignment on the Mana.png - Untap and the Colorless mana symbol stand out as being clipped (One too high and the other too low, which doesn't make sense as they're on the same row.)

From work with the cardbuilder I have all the components to assemble an updated version of this resource. Would the dimensions required remain the same, or would a different scale be more useful?

**Comment by ShawnieBoy** [comment]
I'm sure you'd know what I meant, Icons - Mana...

**Comment by ShawnieBoy** [comment]
Another option would be to have them individually instead

**Comment by lodici** [comment]
> Some of the symbols are out of alignment on the Mana.png - Untap and the Colorless mana symbol stand out as being clipped

I had noticed that too with the untap, I just assumed the symbol is out of alignment on the sheet.

> Would the dimensions required remain the same, or would a different scale be more useful?

![screenshot00414](https://cloud.githubusercontent.com/assets/2443519/11898188/eeb2536e-a58d-11e5-8de7-7a70aad30336.png)

Could be smaller? I am not sure what card image size would reflect the current native mana.png sizes but it would be enormous.

> Another option would be to have them individually instead

I would be inclined towards this option. More consistent and lets you load icons on demand. Also easier to maintain.

**Comment by melvinzhang** [comment]
The source of the sheet is this forum post: http://www.slightlymagic.net/forum/viewtopic.php?t=4430 The original file is svg. It will be good to improve it and post our improvements back to the forum.

**Comment by ShawnieBoy** [comment]
>>Another option would be to have them individually instead

>I would be inclined towards this option. More consistent with the way we handle all the other icons and lets you load icons on demand. Also easier to maintain.

I'd be more inclined to use individual files as well - while it would be nice to give something back to the community, using images in the sizes we require would save on scaling in-engine.

Looks like we use 25x25 and 15x15 as large and small images respectively for mana.

**Comment by ShawnieBoy** [comment]
I've put some mana icons and others into the resources/magic/data/icons/mana folder at 25x25 - Even as multiple files, the file size is about a third of the Mana.png

**Comment by lodici** [comment]
Looks good - are you going to update the code to use these images instead of Mana.png?

**Comment by ShawnieBoy** [comment]
Sure thing, just wanted to show the proposal - I may even put the counters in a different folder as well. It does have the appearance of a dumping ground.

**Comment by ShawnieBoy** [comment]
MagicImages is confusing me - @lodici  In what situations are large and small versions of mana icons used? (I'm guessing that only the colored mana types are used large). If that's the case, would be easier to just have large and small versions of those icons.

**Comment by lodici** [comment]
hehe - mana icon handling is a law unto itself. I will need to look at the code but I am head down on issue #567 at the moment.

**Comment by ShawnieBoy** [comment]
No problem - I'll return to this after looking at #574. Allows me to refresh my mind with  image manipulation.

**Comment by ShawnieBoy** [comment]
Managed to sort out the Mana.png - will leave this open in case there's some corner cases I've missed, but all seems to be working well.

**Comment by lodici** [comment]
It was not using the map properly which I have fixed but otherwise it looks fine. If we kept issues open on the off-chance there might be a corner case we missed then we would never close them, so I think it is safe to consider this closed!

**Comment by ShawnieBoy** [comment]
Hehe, very true - thanks for fixing that, was a bit confusing to me.
