### ISSUE TITLE
Use square corners for cardBuilder

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#579]
Raised in #574 

Just a thought before I even attempt the big image-haul required:

Editing the current frames which are not transparent would be simpler than editing all the frames to have square corners. Is there much of a benefit besides cosmetics?

**Comment by ShawnieBoy** [comment]
Just realised it's RGB which are affected - coincidence?

**Comment by lodici** [comment]
> Editing the current frames which are not transparent would be simpler than editing all the frames to have square corners. Is there much of a benefit besides cosmetics?

If updating image then square corners = JPG = smaller size.

Alternatively, consider taking the rounded corner image and cropping out the rounded corners. Here is acard.png which I opened in Paint.Net and then adjusted the canvas size by about 10 pixels. You can do the same thing dynamically from within CardBuilder so will not have to change the original rounded corner image.

**Comment by ShawnieBoy** [comment]
Cropping the final resulting image looks like the best option - changing the image file size would be a nightmare for compositing!

Good solution.
