### ISSUE TITLE
Better distinguish card type with missing proxy.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#583]
With the new missing proxies although the frames are better it is harder to read the card name or to distinguish the card type. There is probably not a lot you can do with the name but consider using the future sight symbol (maybe on the parchment background) for the artwork instead of "Magarena".

![screenshot2](https://cloud.githubusercontent.com/assets/2443519/11957446/c106c4d4-a8b9-11e5-9f44-a83cd94498d7.png)
![screenshot1](https://cloud.githubusercontent.com/assets/2443519/11957463/cffb735e-a8b9-11e5-9708-1b542628b5b4.png)

**Comment by ShawnieBoy** [comment]
That's a good idea for those not using crops.

**Comment by lodici** [comment]
Who said anything about crops - it is for missing images only.

**Comment by ShawnieBoy** [comment]
If someone was using crops, then the card images would be there to aid in identifying cards. The Magarena image only appears if there's no crop file to be found.

**Comment by lodici** [comment]
As I said, it is for missing images/crops (same thing as far as Magarena is concerned) only.

**Comment by ShawnieBoy** [comment]
I was kinda thinking of them as separate - but don't worry, it's a good idea!

**Comment by lodici** [comment]
> I was kinda thinking of them as separate

Please explain.

**Comment by ShawnieBoy** [comment]
I saw thinking of it as a tiered thing:

If no CardImage then use a Proxy
If no Crop image then use Default crop

A user could be using the card images, but doesn't have images for the latest set or something. But may have got hold of some cropped images for them.

They can be mixed and matched.

**Comment by lodici** [comment]
How do envisage crop images being obtained?

**Comment by ShawnieBoy** [comment]
I never knew that magiccards had crops stored - #582 
To be honest I orignally thought that players could 'sort it for themselves' but it looks like from #582 we could download them for users. There's not so much a strict need for particular images as the current image-quality/legibility doesn't really apply to crops.

**Comment by lodici** [comment]
Will need to give crops some more thought. I was assuming that for every ``magiccards.info\scan`` image there will be a corresponding ``magiccards.info\crop`` image. So for example when new cards are released we add the (full) image url to the script as we do now but if a user is running option 2 in #582, Magarena will look for the image in the crops folder and if not found will download using the ``magiccards.info\crop`` instead of ``magiccards.info\scan``. 

The three modes described in #582 are distinct and determine where Magarena looks for images in the case of options 2 and 3. There is no mixing and matching - you are either using full scans, proxy images with crops or proxy images without crops. The provisio being that in the first two cases if an image or crop is missing then it falls back to generating a cropless proxy image (the third case described and as currently implemented).

Obviously if we cannot guarantee that we can maintain a complete set of cropped images for all playable cards then that kind of blows it out of the water in terms of integrating into the current mechanism.

**Comment by lodici** [comment]
Please note that cropless proxy image mode is a valid mode in its own right. I think melvin mentioned the case where someone is running Magarena from a usb stick that has no space for images.

**Comment by lodici** [comment]
All this think has led me to create #585.

**Comment by ShawnieBoy** [comment]
pushed first pass of proxy-type images 77ce3406ede8cbbe6f70f836abbffaf240c570ce

**Comment by ShawnieBoy** [comment]
Actually the multi-type symbol is fairly redundant - most of the other types will effect the card frame.
Tribal spells and Artifact lands are probably an exception.

**Comment by lodici** [comment]
Looks good. Shame the symbols are so jaggy edged. I think they were the same in the previous proxies but the greater transparency kind of hid that fact.

**Comment by ShawnieBoy** [comment]
Yeah, they look kinda bad - I've got some SVG versions, so will be working with those for something a bit better.
