### ISSUE TITLE
Cardbuilder does not show morph card image.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#584]
Instead it shows a 2/2 creature proxy.

**Comment by ShawnieBoy** [comment]
That's what it should show - Cardbuilder doesn't show any card images.

**Comment by lodici** [comment]
You pushed for the morph image which is a static image so why not use it. So what if the other side is a proxy image?

**Comment by ShawnieBoy** [comment]
But Cardbuilder will only kick in if it can't find an image - if the user hasn't download the image for Morph it won't be there to show.

**Comment by lodici** [comment]
I thought the morph image was included as a static image as part of the release. My apologies if that is not the case.

**Comment by ShawnieBoy** [comment]
They're downloaded - if you move the morph image into the empty folder - it should display it (I'm still pointing my downloads to an empty folder.

**Comment by lodici** [comment]
If it is downloaded then this issue has no legs. Closing.
