### ISSUE TITLE
New decision tree for displaying a card image.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#585]
Each of the following three modes can be selected as the default mode by a user. For example, if I choose (B) then (A) will never run. If I don't have access to a set of images for some reason then I might choose (C) which will get rid of the new images alert since it is not relevant in this mode.

**(A) Full scan image mode**
1. load full scan image.
2. if full scan image is missing goto **(B)**.

**(B) Cropped proxy image mode**
1. generate proxy using cropped image.
2. if cropped image is not found goto **(C)**.

**(C) Cropless proxy image mode**
1. generate cropless proxy. This will always work.

**Comment by ShawnieBoy** [comment]
This could be distinguished in a downloads option:

1. Download full-size images
2. Download crops
3. Neither

As the process already checks if an image is present, there needn't be a 'mode' for the program to be in, it would just depend on what it finds.

**Comment by lodici** [comment]
In the case of 1 and 2 I would want to know when new images are available. But the new image alert would be annoying in the case of 3. How would Magarena know whether to suppress it or not?

**Comment by ShawnieBoy** [comment]
It would depend if the option was 1, 2 or 3 - a drop-list maybe - a setting set similar to where the image folder is located.

**Comment by ShawnieBoy** [comment]
Hehe, I guess it is kinda like having a mode - just a download mode

**Comment by lodici** [comment]
Exactly, you say 1, 2 ,3 I say A, B, C.

**Comment by melvinzhang** [comment]
No longer relevant, we have moved to getting the user to declare his/her preference for how cards images are shown in-game, either as 'printed' or 'rendered proxy'
