### ISSUE TITLE
Can't cast Carrion Call, for no apparent reason.

### ISSUE THREAD

**Issue by itandetnik** [magarena/magarena#591]
I have `Carrion Call` in hand, and enough land to cast it. Yet the computer doesn't highlight it, and clicking on it has no effect. There's nothing fancy in play that would explain it. It's my phase M1 (and in any case, it's an *Instant*).

Report attached: [gameplay-report.zip](https://github.com/magarena/magarena/files/72009/gameplay-report.zip)

**Comment by ShawnieBoy** [comment]
`Carrion Call` had the wrong timing of 'Main' fixed in 4aaff55b98c76f26d48fa938f4013e5bff9fd13c

**Comment by melvinzhang** [comment]
@ShawnieBoy did you reproduce the bug? In the report, the card can't be cast during your first main.

**Comment by ShawnieBoy** [comment]
Encountered #593 - And misread the bug description >.<

**Comment by ShawnieBoy** [comment]
Ok, not able to duplicate - but the card edit is still valid :grinning:

**Comment by melvinzhang** [comment]
Unable to replicate. Opening the snapshot from the gameplay zip shows Carrion Call highlighted.
