### ISSUE TITLE
Noticing significant performance degradation.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#594]
I have been testing the latest builds on a very low spec AspireOne and linux mint running in VBox on my main high-spec PC. On the aspire it is generally at the limit when animating and can be quite jerky sometimes. In linux animation is generally fine given the limits of the VBox graphics drivers in a linux guest.

When testing the very latest build on these two platforms I noticed that the busy throbber was very jerky and the animation extremely jerky to the point of being non-existent. There was a definite feeling of sluggishness to gameplay.

Since then I have gone back through previous builds looking for the point at which this started and I believe it to be [build 494](https://circleci.com/gh/magarena/magarena/494). This is where [I added](https://github.com/magarena/magarena/commit/fe3412f0295c156ce809577caa862e5f2b1d165f) ``synchronized`` to ``loadAbilities()``. I wondered whether this might have side-effects!

I am 90% sure this is the cause, but as yet I don't know why. @melvinzhang, @ShawnieBoy please could you test build 494 and 493 and see if you notice any differences in performance. Thanks.

**Comment by lodici** [comment]
Actually I get the issue with build 493 as well just not always. Build 487 is consistently smoother so I will start working my back up from there.

**Comment by lodici** [comment]
update: 488 is fine. 493 is now suspect.

**Comment by ShawnieBoy** [comment]
Still want to test for any performance issues?

**Comment by lodici** [comment]
If could you run a 1.68 game vs latest 1.69 build and let me know if 1.69 feels suggish that would be helpful.

**Comment by ShawnieBoy** [comment]
Tested 493 and 494 and didn't really notice any difference. The only thing that catches my eye is the flickering of "Play a card or ability" while the AI is skipping phases.

**Comment by lodici** [comment]
Thanks for looking. I must admit running in Windows 7 I have noticed no obvious slow downs but have definite issues on the slower netbook and when running linux in a vbox. PS. you can turn off the AI prompts in settings.

**Comment by ShawnieBoy** [comment]
I think they're prompts for me, but I'm unable to do anything.

**Comment by ShawnieBoy** [comment]
If I have time later, I'll install onto my notebook - it has windows 7 but graphically it even struggles with Youtube!

**Comment by ShawnieBoy** [comment]
Oh, and Windows 10 has it's own version of the Magarena Splash screen...
![2015-12-25_223416](https://cloud.githubusercontent.com/assets/2363180/12004533/d5addec2-ab57-11e5-9fb0-6862b67dc9f2.png)

**Comment by lodici** [comment]
``MagicCardDefinition.loadAbilities()`` is called during gameplay but never on the EDT so that blows my theory above out of the water. It is possible that it is a false alarm. I have updated the animation code which might need tuning for lower spec platforms but the fact is it runs as smooth as you like on my main PC - testing on a crappy netbook and in a suspect vbox environment (in terms of graphical capabilities) might not be the best representation of real world usage.

**Comment by lodici** [comment]
Running linux mint natively and performance is smooth as Windows 7. I am going back down to DEFCON 5 but will leave this open for now while I look at trying to fine tune animation for my netbook. Maybe we have a crossed a min spec threshold which excludes my old aspire.

**Comment by melvinzhang** [comment]
loadAbilities is only called when creating the game (during nextGame, specifically when creating MagicCard), it is not called when the game is ongoing. The only exception is token cards, these are created as needed during the game. Does your testing games have a lot of token cards?

**Comment by lodici** [comment]
> loadAbilities is only called when creating the game

That is what I thought but I stuck the following debug in loadAbilities and every time the AI is thinking it churns out a load of new statements. I am watching it even now as I play a test game.
```
System.out.println(System.currentTimeMillis() + " loadAbilities, isEDT = " + SwingUtilities.isEventDispatchThread());
```

**Comment by melvinzhang** [comment]
Your right, I see it too. That is a bug, looking into it now.

**Comment by melvinzhang** [comment]
Nope, it is correct. It is only calling loadAbilities for tokens. In my case, it was a Soldier token. You can print the card it is loading by printing "this" inside loadAbilities.

**Comment by lodici** [comment]
Mainly insects but a few fluster storms as well..
```
1451096468797 Flusterstorm loadAbilities, isEDT = false
1451096468797 Flusterstorm loadAbilities, isEDT = false
1451096468798 Flusterstorm loadAbilities, isEDT = false
1451096468832 Flusterstorm loadAbilities, isEDT = false
1451096468919 Insect loadAbilities, isEDT = false
1451096468954 Insect loadAbilities, isEDT = false
1451096469127 Flusterstorm loadAbilities, isEDT = false
1451096469310 Insect loadAbilities, isEDT = false
1451096469365 Flusterstorm loadAbilities, isEDT = false
1451096469365 Flusterstorm loadAbilities, isEDT = false
1451096469411 Insect loadAbilities, isEDT = false
1451096469414 Flusterstorm loadAbilities, isEDT = false
```

**Comment by melvinzhang** [comment]
Token cards are also created when spells are copied such as in storm. Anyway it is all within the AI's thinking thread, it is doing much more heavy duty stuff besides calling load abilities.

**Comment by lodici** [comment]
I agree, presumably ``requiresGroovy`` will be null for most if not all these cases anyway so it will just zip through the method without doing anything.

**Comment by melvinzhang** [comment]
Yes, most tokens are vanilla creatures, some have ability property which are also processed in loadAbilities (these are relatively fast, some regex matching), only two have groovy code.

**Comment by lodici** [comment]
Closing - not able to definitively identify or replicate consistently.
