### ISSUE TITLE
Planeswalker's with abilities containing ':'

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#595]
Planeswalkers which give activated abilities are not displaying the full text. This is due to `:` normally signifying the cost of the Planeswalker ability, not any abilities mentioned in the ability text. e.g 

Freyalise, Llanowar's Fury:
+2: Put a 1/1 green Elf Druid creature token onto the battlefield with "{T}: Add {G} to your mana pool."

**Comment by melvinzhang** [comment]
Where is this ':' checked in cardbuilder? There was similar issues with text replacement in card script parser, i.e. All creatures have "Sacrifice this creature: This creature deals 1 damage to target player.". Normally "This creature" in text is replaced with SN, however the replacement should not occur for "This creature" inside a quoted ability. The solution is to only perform replacement for "This creature" followed by an even number of quotes, see ARG.EVENQUOTES.

**Comment by ShawnieBoy** [comment]
The CardBuilder uses Oracle Text, as Script syntax is normally different/contains additional characters.

CardBuilder splits the Planeswalker text by colon and takes the info before a colon as being the loyalty cost. This is over-generalising.

**Comment by melvinzhang** [comment]
You can try with split(":" + ARG.EVENQUOTES). This way it will only split on ':' that is not inside a quote.

**Comment by ShawnieBoy** [comment]
Cool - Put this up here so I wouldn't forget it while working on the 4 ability planeswalkers.

**Comment by ShawnieBoy** [comment]
This seems to be keeping what's before the colon as well - back into the world of regex...

One thing you may be able to help with, for some reason the text manipulation for planeswalkers has difficulty with strings beginning with '-' I can't match them, only assume it's a minus if it's not a '+' or '0' cost.

**Comment by melvinzhang** [comment]
I see, in this case, perhaps split with limit will be simpler since we know there is exactly two parts. eg split(":", 2)

**Comment by melvinzhang** [comment]
Btw, why is the index out of bounds needed? What cases causes it to occur?

**Comment by melvinzhang** [comment]
> difficulty with strings beginning with '-'
Which part of the code is this? Please give a specific example of the difficulty, i.e. the code should do X, but it doesn't and does Y instead.

**Comment by ShawnieBoy** [comment]
Great!

>Btw, why is the index out of bounds needed? What cases causes it to occur?

To be honest I was looking at that just now and trying to think the same thing.
I'd guess text on a planeswalker with no loyalty cost - e.g. "This planeswalker can be used as a commander"

**Comment by melvinzhang** [comment]
Makes sense, in that case perhaps a simple if check on the length of the array returned by split would do. Or if you always want the last elements, just fulltext[fulltext.length - 1] would work for both cases.

**Comment by ShawnieBoy** [comment]
>Which part of the code is this? Please give a specific example of the difficulty, i.e. the code should do X, but it doesn't and does Y instead.

Taking a cost with -1 for example, returns 1. To display a string beginning with minus, I need to put it back in:

`PTFrame.getLoyaltyPanelText'

**Comment by ShawnieBoy** [comment]
Just a strange peculiarity - still getting my head around some of this code still, around a year old!

**Comment by melvinzhang** [comment]
The NPE handlers also looks a bit weird, the expression in the try and catch are exactly the same!

**Comment by melvinzhang** [comment]
getPlaneswalkerActivationCosts should just use the split method just discussed here instead of substring(0,3), if there are two parts the first part is the cost text, should not need PTFrame.getLoyaltyPanelText to fix it up.
