### ISSUE TITLE
problem showing minus in planeswalker script

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#596]
@ShawnieBoy The problem with minus is that it is not the ascii hyphen we are familiar with, it is the unicode minus (code point 8722). I'm guessing your font does not have a glyph for this code point.

**Comment by melvinzhang** [comment]
I'm replacing the unicode minus with ascii hyphen.

**Comment by ShawnieBoy** [comment]
Ahh, thought something was fishy - I'll have a look at adding it to the font.

**Comment by melvinzhang** [comment]
Should there be unicode minus in the card script though? I think those should be changes to use the ascii hyphen-minus since that is what we use for negative pt, -1/-1 counters etc. We don't use the unicode minus anywhere else except in the loyalty cost oracle text for planeswalkers.

**Comment by ShawnieBoy** [comment]
Well, there's a variety of ways of fixing the HEAVY_HYPHEN - 
add it to the font, 
replace it in the scriptsbuilder, 
or replace it in cardBuilder

**Comment by melvinzhang** [comment]
Agree, I propose replacing it in the scripts builder, so that generated scripts use a consistent symbol for minus.

**Comment by melvinzhang** [comment]
Just curious, but why do you call it HEAVY_HYPHEN? The common name is "minus", eg http://www.codetable.net/decimal/8722

**Comment by ShawnieBoy** [comment]
Ahh, sorry - in the .ttf that's the symbol it replaces
