### ISSUE TITLE
Monte Carlo Crash Against Specific Deck

### ISSUE THREAD

**Issue by Gothmagog** [magarena/magarena#601]
[BugReport.zip](https://github.com/magarena/magarena/files/72667/BugReport.zip)

Magarena crashes on the AI's first turn every time I play this deck with the Monte Carlo engine. Doesn't seem to matter which deck the AI plays. Seems to work ok against minmax, haven't tried other engine.

**Comment by melvinzhang** [comment]
Thanks for the bug report and deck! We've been trying to track down a bug in the MCTS AI for a while but have been having trouble replicating the bug reliable. It is good that this deck manage to get it to crash every time.

**Comment by ShawnieBoy** [comment]
Been playing a mirror match with this deck - not had a crash, but there's plenty of time warnings related to discarding 20+ cards during simulations.

**Comment by ShawnieBoy** [comment]
And happily munching up around 5gig of RAM

**Comment by ShawnieBoy** [comment]
Forced Fruition is the main culprit for the discard time - but haven't been able to make it break

**Comment by ShawnieBoy** [comment]
This looks more like a platform issue - as in this deck is very CPU + RAM intensive for the amount of thinking involved for the AI for every phase. Even my gaming pc slows down and feels as though it's struggling.

 @lodici Could you try this on your netbook?

**Comment by melvinzhang** [comment]
What is a platform issue? I would understand that as a JVM or OS bug, in this case I think what you mean is that the program is using too much memory. I'm surprised it didn't generate an OutOfMemoryError for you. The max memory available is fixed to be 512MB, once the program requires more than this, it will crash with OutOfMemoryError. Using more than 512MB of memory is a bug in the program.

**Comment by ShawnieBoy** [comment]
Oh yes, of course - I have it set at 1g - Would explain the no crash.

**Comment by melvinzhang** [comment]
Due to #479, this deck will still play to be slow large number of discard options.
