### ISSUE TITLE
Cropped Images

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#602]
Raised in 87159a5eb6b2c2f1dc8264158c324fde4f22cfd6 and effects #585 #582 #337 #245 #117 #115 (A quick round up of cardbuilder and image-related issues)

Primarily a question about what support and functionality should be given to cropped images.

Currently we have the option to be able to display cropped images for cards, however there's many ways of approaching this and any changes will have lots of 'knock-on' for other parts of Magarena, as we've been primarily a full-image program.

In a sense - the proxy builder has become a replacement for the text-only mode, a version of Magarena we've been moving away from. Text-mode does have the benefit of not requiring extra HD space for images, or image download maintenance, but we still don't really know how much of the user-base actually uses it. Hence it's planned removal in 1.70
##### Usage

I'd assume, from a user standpoint, the decision would be "Do I use images", then "Full-sized or cropped". I can see this choice being dependant on the users platform and space available, but also language. Multi-language support is only currently supported for full images.
##### Downloading

Cropped images can be supplied by magiccards.info - However would have to check if all cards are supported, and how soon crops are available after full-size images etc. - So they could be downloaded in the same style as current full-size images. There would not be as much urgency as there are for full-images, as full-images are essential for the game to be playable regarding accurate card-text and legibility, which isn't the case for crops, which are purely cosmetic.
##### Updating

I would assume there would be little need to update existing cropped images as we currently do for full-images. I can only think for possible image-errors (wrong card image). I guess an image_updated relating to a full-size image could be used to 'update' a cropped image in the case of a version change to a new image.
##### Impact

There's not been any real full test of the proxy-builder in terms of performance impact, - a long, token-heavy game for example - it's not likely to come up before the next release either as we currently have no cards without images, and we have little knowledge about text-mode users who may end up using the proxies in this release or from previous releases of the proxy-builder.
##### Implementation

With the choice of "Full-Images" or "Crops" - The check for full-images being missing to implement proxies still stands fine, but if a user was going to change from Full-Images to crops (or vice versa), a check would be needed to check if cropped/full images exist and which are required.

(This wasn't supposed to turn into an essay! Apologies for 'waffle', just kept thinking of other things.)

**Comment by lodici** [comment]
Lots of very interesting points. I will give the crops download a try and cogitate.

**Comment by lodici** [comment]
Hacked and ran the downloader for crop images up to and including some of the B's and [logged the results](https://gist.github.com/lodici/2ae77e07cdafc4fba2f9). "X" indicates the specified download url could not be found.

From the log you can see that the downloader can get the majority of the crop images needed but not all. Where a crop is missing then the downloader can get the full image instead. Thus there needs to be a new setting in the download dialog where you select "Full images" or "Cropped images".

Given that the cropped image name should be exactly the same as the full image (just its location is different) I think the new images alert can more or less remain as-is. When looking for missing images, first look in ``crops`` and if no image found, look in ``cards`` and if still no image then flag as missing.

So here is what I suggest as the new decision tree when Magarena needs to display a card image -

1. look for full scan in ``custom``.
2. look for crop image in ``crops``. If found then get proxy image with crop from CardBuilder.
3. look for full scan in ``cards``.
4. get missing proxy image from CardBuilder.

The main assumption is that the image name will always be the same in (1), (2) or (3).

**Comment by ShawnieBoy** [comment]
That results log is really useful - it looks like the main sets which don't have crops are online editions (Masters Edition, Tempest Remasters etc,) and some flip cards (which would have a different sized cropped image). Which makes sense.

What's interesting is that 'Born of the Gods' and 'Theros' seem to be missing, but later sets e.g. 'Fate Reforged' are available.

It's a bit of a shame they can't be searched-up by card name - that would solve the editions problem if they were saved like mtgimage (just keeping the most recent printed version)

Being able to obtain full-images instead is a great solution!

**Comment by lodici** [comment]
One other user-case to consider is whether you would want the option to use CardBuilder only. In this case if a crop is missing it would skip (3) and run (4) displaying the equivalent missing proxy. This way you would not get a mixture of proxy images and full images. For someone who prefers consistent card frames over art, I guess.

**Comment by ShawnieBoy** [comment]
Possibly in the future - the main reason for it's integration was to be able to display card changes in-game. Things like color and types will be simple enough, but displaying added abilities will be more tricky as our parser converts text -> abilities, but not back again.

Also that would lose multi-language support, as it's more efficient to download images of a variety of different languages, but having card scripts with the oracles of all supported languages would be quite the undertaking. Just thinking about fonts required makes me shudder!

**Comment by ShawnieBoy** [comment]
Complete reparse of the scripts and scripts_missing folder now completed. Image urls should now all be pointing to their optimum targets in regards to cropped images and full-image language options.

Don't want to be doing that again any time soon! 😩

**Comment by melvinzhang** [comment]
@ShawnieBoy anything left on this? Crops are properly supported since a while ago.
