### ISSUE TITLE
If PN don't, PN sacrifice SN.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#604]
![untitled](https://cloud.githubusercontent.com/assets/2443519/12013533/6adc6342-ad10-11e5-9a6d-f407cba19ba7.jpg)

If PN doesn't, PN sacrifices SN.

**Comment by melvinzhang** [comment]
@lodici up to which commit is this? In be5c935af70ee20329e, when I cast Rupture Spire it shows "Player may (no) pay {1}. If Player doesn't, Player sacrifices Rupture Spire".

**Comment by melvinzhang** [comment]
Assuming I'm reading the issue right, that expected log is suppose to be "If PN doesn't, PN sacrifices SN." Then it is closed by 8c499f2abe22b87

**Comment by lodici** [comment]
This was on the 1.69 release.
