### ISSUE TITLE
Would a limited casting cost reduction/increase support be useful?

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#613]
I think it should not be too much work to allow a limited form cost reduction/increase effect. Eg, "Noncreature spells cost {1} more to cast.", "Soldier spells you cast cost {1} less to cast."

Some limitations would be:
1. does not reduce additional costs such as kicker, only reduces the card's mana cost
2. cannot reduce {X} cost, {X} spell costing {1} less to cast where X is chosen to be 5, will still cost {5}

@ShawnieBoy what do you think?

**Comment by melvinzhang** [comment]
Just realized that limitations only affect cost reduction, cost increase seems to work fine. I've gone ahead and added it. We can stick to only cost increase if we feel that the limitations of cost decrease is too confusing.

**Comment by ShawnieBoy** [comment]
I do think it would be a bit confusing - especially with X-spells traditionally being the go-for spell to take advantage of cost reduction.

I think it could be possible to fix those two issues (which were the two stumbling blocks whenever I tried as well). They're both linked by the extra choice before actual casting.

If there was a ManaCost Math-type process which would reduce the printed cost, then increased cost, then additional costs, it could be do-able

**Comment by ShawnieBoy** [comment]
Generic mana for X spells would mainly mean the adjusting of the min and max values for X - which would be easier to attempt than additional costs.

**Comment by melvinzhang** [comment]
Supporting X spell is more doable than additional costs, as each additional costs is a separate event. 

If we can only support X but not additional costs for next release, @ShawnieBoy do you think we should go ahead with cost reduction cards? For now, we can put additional costs not affected by cost reduction as a "Magarena" specific rules difference. Eventually we may find a good solution for it.

**Comment by ShawnieBoy** [comment]
I'm always hesitant to add something until it's doing everything it should - I'm kinda on the fence with this one.

All of the cards will work fine in most of the scenarios, but there will be times when it will stick-out because it's not right, and will no doubt have bugs raised about it.

There's also the issue with reduced/increased activated costs as well.

I'd say add them in, as a work in progress, there may even be things that a release-worth of testing might bring up.

But then once cards are added, they can't be removed :cry: 

I guess the answer is: I don't know.

**Comment by melvinzhang** [comment]
What's the issue with reduce/increase activated costs? They are not affected by the current changes which are only for casting cost. {X} spells turns out to be harder than I thought, mainly due to the delayed mana cost use by the AI, needs more work than expected.

**Comment by melvinzhang** [comment]
Think I found a way around the {X} mana cost issue, doing some simple tests now and looks fine so far.

**Comment by ShawnieBoy** [comment]
>What's the issue with reduce/increase activated costs? They should not affected by the current changes which are only for casting cost.

I was just thinking of cards like Gloom which effect both in different ways.

**Comment by melvinzhang** [comment]
Sorry it wasn't clear in the title, the mechanic being discussed here is only casting cost reduction/increase. Cards like Gloom is not supported.

**Comment by melvinzhang** [comment]
The easy part was getting the player mana choice to work, the harder part is the AI, aka MagicPayManaCostResultBuilder. So far so good, in a simple test, the AI is able to figure out it needs to case a mana reduction artifiact then blast you to the face with an X spell. Just pushed the changes to master and also a simple test case (TestCostReduction).

**Comment by melvinzhang** [comment]
So far so good, CI test games have turned out ok. Would appreciate more testing on cost reduction cards. Please file new bugs as discovered, thanks!
