### ISSUE TITLE
Mental Misstep can counter Chalice of the Void when X=1

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#617]
Chalice of the Void {X}{X} being cast as X=1 (Total 2 mana) can be countered by Mental Misstep which can only counter spells with a converted cost of 1.

Looks like it's observing the printed cost of X, not the actual cost

**Comment by melvinzhang** [comment]
A problem with MagicCardOnStack.getConvertedCost, it doesn't take into account the number of X in the cost, it is always treated as though there is only one X. Fix incoming.
