### ISSUE TITLE
Creature-type related Mana Cost reduction and AI

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#618]
Might be a difficult one to catch properly - But in my test deck containing Etherium Sculptor, Dark Confidant  with Stonybrook Banneret (All Wizards with the Banneret having `Merfolk and Wizards cost {1} less to cast`). The AI prefers to not cast the cost reduction first.

Currently in a game with 2 of each Etherium and Sculptor while keeping the Banneret in hand.

**Comment by melvinzhang** [comment]
A test case would help, eg in this situation the AI should do X, Y, Z to get a huge advantage/win the game, but the AI misses it.

**Comment by ShawnieBoy** [comment]
Hehe, actually the Sculptors aren't Wizards at all - They're Artificers - doh!

**Comment by ShawnieBoy** [comment]
As the Sculptors were out-numbering the Dark Confidants, there would have been no need to cast the Banneret.
