### ISSUE TITLE
game slows down after 5-10 turns, and after 20 or so turns the game becomes unplayable

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#62]
reported by sponeta @ http://www.slightlymagic.net/forum/viewtopic.php?f=82&t=3735&start=855#p170719

So I was toying around with a new deck, and for some reason Magarena seems to slow down considerably with this deck. More than with others. It's not just the AI taking time either. Every few clicks the game will pause for a second, the spinner doesn't move at all. It's like the UI is freezing. This starts happening after 5-10 turns, and after 20 or so turns the game becomes unplayable. The same thing happens with all AIs.

The deck strategy is very nonstandard. The first few turns you need to prevent damage until you have a few lands, then use Time of Need or Captain Sisay to search for Azusa, Lost but Seeking. Then keep searching for legendary lands, and combo Buried Alive with Volrath's Stronghold and Loyal Retainers to get the big dragons out. Probably not going to win any tournaments, but it's weirdly fun!

Here's the deck. I'm using a lot of legendary lands, maybe that's related?

# 8 creatures
1 Azusa, Lost but Seeking
1 Captain Sisay
1 Knight of the Reliquary
1 Kokusho, the Evening Star
4 Loyal Retainers
1 Sheoldred, Whispering One
1 Skithiryx, the Blight Dragon
1 Teneb, the Harvester

# 9 spells
4 Buried Alive
1 Day of Destiny
3 Dead Weight
4 Fog
4 Holy Day
1 Moat
2 Pacifism
2 Sylvan Scrying
4 Time of Need

# 12 lands
1 Eiganjo Castle
6 Forest
1 Karakas
1 Kor Haven
1 Maze of Ith
1 Mikokoro, Center of the Sea
1 Miren, the Moaning Well
1 Okina, Temple to the Grandfathers
4 Plains
1 Shizo, Death's Storehouse
5 Swamp
1 Volrath's Stronghold

**Comment by melvinzhang** [comment]
Melvin:
The legendary uniqueness check could be the cause, when it starts to slow down how many legendary lands are on the field?

Sponeta:
Might be something there. I tried a test game. The slowdown became noticeable with 4 legendaries (3 lands, 1 creature). Then I stopped adding legendaries to the battlefield, played for 10 more turns, and it didn't slow down further. Then I added 3 more legendaries, and it slowed down further. I did a replay, and used different legendaries, but the result was the same. So it's probably not any specific card.

**Comment by melvinzhang** [comment]
Melvin:
Did the slow down occur as soon as when the legendaries are on the field or did you have to play a couple of turns into the game with the legendaries around? Wanted to confirm if number of turns had any effect.

Sponeta:
The slowdown started immediately when I added the last 3 legendaries. Even casting the third one was slower.

**Comment by lodici** [comment]
Unable to replicate and possibly related to #419.
