### ISSUE TITLE
Oracle text Attributed string doesn't replace second digit for activated costs over {9}

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#620]
If a card as an activated cost over {9} e.g. Spawnsire of Ulamog - The icon replacement doesn't take into account the possibility of double-digits in a cost.

**Comment by melvinzhang** [comment]
I'm trying to understand textIconReplace, is the idea to put the icon on one of the character, then add add the nulled attribute to every other character?

**Comment by melvinzhang** [comment]
@ShawnieBoy the above commit does what I mentioned in the previous comment, and it removes the extra 0 after the icon as desired. Please if check it is ok.

**Comment by melvinzhang** [comment]
Does it matter which characters gets null and which gets icon? Currently I've made the middle one get icon and the rest null but it could be simpler if either the first/last gets icon and the rest gets null.

**Comment by ShawnieBoy** [comment]
Looks good to me, not been able to test it yet.

Aiming for the centre is the best bet as the Null character is still a pixel wide and some combinations look a bit strange with the extra gap, mainly normal mana against hybrid or phyrexian

**Comment by melvinzhang** [comment]
I see, that explains why there is a larger gap between {20} and colon vs {4} and colon. I think there shouldn't be any null at all.

**Comment by melvinzhang** [comment]
I'll try compacting the text first so that all {..} sequence is one char, then we just change the attribute for that one char to the icon. In this way, there will not be extra null images.

**Comment by ShawnieBoy** [comment]
:+1: 

Nice work - I've been cobbling that together due to not being able to remove from the pre-formed string.
