### ISSUE TITLE
Require Ligature for 'Ky' in Beleren font

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#621]
The current kerning for `Ky` is pretty awful:
![kytheon](https://cloud.githubusercontent.com/assets/2363180/12068134/c6458b00-affe-11e5-9dd2-cb6842a36b72.png)

Requires use of alternate K character or ligature for Ky:
![knight](https://cloud.githubusercontent.com/assets/2363180/12068135/da175ad2-affe-11e5-9ba3-3274b2cd8e8e.png)
![kytheon2](https://cloud.githubusercontent.com/assets/2363180/12068138/dd7c2126-affe-11e5-8c32-86cefb1e00e2.png)

**Comment by ShawnieBoy** [comment]
Same applies to `Kj`

**Comment by ShawnieBoy** [comment]
Other method is using an attributed string for cardName and adjusting font for capital K if followed by y or j (and maybe any other characters with a descent for future-proofing)

**Comment by ShawnieBoy** [comment]
Right-flow capitals `K`, `Q`, `R`
Left-flow `y`
Straight descent `g`, `j`, `p`, `q`

**Comment by ShawnieBoy** [comment]
![king](https://cloud.githubusercontent.com/assets/2363180/12105709/3b7535ee-b34f-11e5-9d63-1a90ff7d5eed.png)

Have to say I'm quite pleased with this - something that no-one will notice :grinning:

**Comment by kudit** [comment]
Shouldn't the f in "of" have a pointy bottom?  Is this an alternate character?

**Comment by ShawnieBoy** [comment]
Well spotted - it looks as though the f character in the font we're using doesn't match the f on cards.
