### ISSUE TITLE
sudo apt-get install magarena?

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#622]
That would be pretty cool! Debian seems the one most recommended. Maybe too much exposure though? Also I get the impression that the submission process is quite involved - would be a interesting exercise for someone though I am sure.

**Comment by melvinzhang** [comment]
Outside our scope, someone needs to pick it up and package it for their distro. For example, one was done for Arch Linux at https://aur.archlinux.org/packages/magarena/
