### ISSUE TITLE
Use card builder to generate images for permanents

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#623]
> The second "MagicCard" phase is to use CardBuilder to dynamically generate the images used during a game including displaying adjustments to card properties through activated abilities and so forth. Will build upon the work completed in phase one which should have already been integerated into Magarena and proven itself stable and robust.
-- lodici

**Comment by ShawnieBoy** [comment]
There are some interesting rendering options when it comes to in-game -

The current rendering is an attempt to render the card as-printed - this would remain the same for all MagicCards whether in hand or library (and most of the time, in exile or on the stack).

The options come with the more irregular card-frames and using a separate tab on the zoom image to render the MagicCard as well as MagicPermanent:
 - Leveller could render it's current level properties only, as a regular creature frame.
 - Flip cards would not use the flip frame and instead render as the current creature (Also aids with clarity when tapped)
 - Transform cards may be rendered as normal permanents - although not much difference to regular frames.
 - Split spells would show only the half being cast while on the stack. (Not implemented, but still)

**Comment by ShawnieBoy** [comment]
Being able to produce in-game card properties with cardbuilder should really begin with properties we cannot yet display.

I'd propose to implement permanent color changes first (And if that goes smoothly, then type/subtype changes). This would also give us a focus on when to call for a redraw for cards.

**Comment by melvinzhang** [comment]
I second the idea. Changing this issue to only be about color changes.

**Comment by ShawnieBoy** [comment]
Looking at the card rendering and involving the cardbuilder - it's more likely to be all-or-nothing for card properties. Having a permanent renderer for duels which caches images per permanent changes will catch everything. It's more of an issue of how often cards on the battlefield are updated.

**Comment by melvinzhang** [comment]
We can the value returned by getStateId() as the key into image cache.

**Comment by ShawnieBoy** [comment]
Added a first push of implementing this 7e5adc12edced3a9c403662d7ea6cd3abed73fee Annotated card panel is still adding an overlay for power toughness as not all cards have a crop, and is still used for custom images. With crops, it should now display color, type and name changes.

**Comment by ShawnieBoy** [comment]
Just noticed that subtypes are not showing...

**Comment by melvinzhang** [comment]
Looks good, I just tried with animating a Rakdos Keyrune. Not a bad idea to duplicate the image selection logic in two places, I've merged them in 8a8f03509fca7

**Comment by ShawnieBoy** [comment]
Thanks for going over that - I ended up duplicating code to keep it separate from the current image rendering in case something major popped up. I think this issue can be closed, I'll now get to work with some kind of solution for Token images.

**Comment by melvinzhang** [comment]
No prob, it is good idea to prototype and try things out by using a separate code path. Once we get a better feel of how it is suppose to work, we can merge them back like we did here. This way is easier than trying to figure out the general way directly.

**Comment by melvinzhang** [comment]
What is issue with token images? Thought it is covered by card builder?

**Comment by ShawnieBoy** [comment]
The issue with token images is that full-card images are downloaded for tokens, as no crops exist. Cardbuilder looks for crops and doesn't find any, so full-card images are used instead.

Tokens need to take a full card image, and if there's no custom image, and the user language is English, cut the full-card image to size to use as a crop.

Tokens also need to be able to take a crop image of a normal card to be able to display a token copy of an existing card.

**Comment by ShawnieBoy** [comment]
As all of this testing would have no way of seeing if it was working, tokens don't yet use images, proxy or otherwise.

**Comment by melvinzhang** [comment]
![spirit_token](https://cloud.githubusercontent.com/assets/1620634/19155733/19c61174-8c12-11e6-9cd1-a0824fa2c738.png)

What you mean by token don't use proxy? I deleted the full token image and this is what a spirit token proxy looks like to me. The only issue is the black box instead of showing the creature symbol like a card would.

**Comment by ShawnieBoy** [comment]
That's what I meant by a proxy image, instead of the black space. I'm working on some masks now.

**Comment by melvinzhang** [comment]
Ah, i get what you mean now. The proxy image is the art box. I was thinking it should at least show the "claws" creature symbol like cards do. I'm guessing the problem is that the shape is different from a regular cards art box.

**Comment by ShawnieBoy** [comment]
It's the same I had to do with Planeswalkers - However with tokens, no crops exist, so it would be using full-art if it is a token, but a crop file if it is a token of an existing card, as the existing card (may) have a crop file.

**Comment by ShawnieBoy** [comment]
By that I mean cropping a full image into a crop, or stretching a crop into a token crop
