### ISSUE TITLE
Log messages generated by card but with no interactive link.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#628]
![selection_005](https://cloud.githubusercontent.com/assets/2443519/12089445/b6b7a494-b2dc-11e5-9e0c-c4b70097d5f5.png)
would be useful to identify the card generating this action -
![selection_006](https://cloud.githubusercontent.com/assets/2443519/12089471/02df31ca-b2dd-11e5-8d52-ca176f092b56.png)
Implement a way to highlight the card on the battlefield when mouse over a log message without any interactive card link. Maybe add source where applicable as hidden property of log message. Would only activate if log message contains no interactive links to avoid confusion.

**Comment by lodici** [comment]
Although the stack does show the source (if you are observant) -
![selection_007](https://cloud.githubusercontent.com/assets/2443519/12089860/27043e7a-b2e1-11e5-8ba2-6d3ba5e4522f.png)

**Comment by ShawnieBoy** [comment]
Good name by the way -

I assumed the icons were yours - I'm guessing that's an 'Event' or 'Trigger' flag - similar to the other icons used when casting of particular card types.

**Comment by lodici** [comment]
> I assumed the icons were yours - I'm guessing that's an 'Event' or 'Trigger' flag - similar to the other icons used when casting of particular card types.

Is it important to show this in the stack? How does it help? Given that the card name is there.

**Comment by ShawnieBoy** [comment]
Well it shows it's an effect from that card, not that card being cast?
I never really look at them to be honest. It's one of those things that are there all the time that you become a bit blind to them. The trigger ones are probably more useful than the 'creature' 'artifact' card-type ones.

**Comment by melvinzhang** [comment]
This issue seems to overlap or duplicate #531, where we identified that the main problem is that the log does not show the source of the event.

**Comment by ShawnieBoy** [comment]
>This issue seems to overlap or duplicate #531, where we identified that the main problem is that the log does not show the source of the event.

Thanks, I thought this was familiar - couldn't find it.

**Comment by lodici** [comment]
Yes you are right although I am proposing a bit more of a subtle effect here. Whether it would work consistently I cannot say.

**Comment by melvinzhang** [comment]
> Would only activate if log message contains no interactive links to avoid confusion.

That might be a bit too restrictive. Say the effect is "At the beginning of your upkeep, return target creature to its owner's hand". There would be an interactive link in this case, the chosen creature, but it would still be nice to know in the log which permanent's trigger is this.

**Comment by lodici** [comment]
> I never really look at them to be honest. It's one of those things that are there all the time that you become a bit blind to them.

That is how I view them - I don't really know what each icon represents so ignore them (ui design red flag!). It actually took me a while to work out what the red bar meant as well, although that is a bit more useful I think.

**Comment by lodici** [comment]
> That might be a bit too restrictive. Say the effect is "At the beginning of your upkeep, return target creature to its owner's hand". There would be an interactive link in this case, the chosen creature, but it would still be nice to know in the log which permanent's trigger is this.

Damn, another idea shot down in flames! :boom:

**Comment by lodici** [comment]
Closing, see #531.
