### ISSUE TITLE
Magarena rarity symbol?

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#631]
Just something that has sprung to mind - and the only part of the cardbuilder images that looks a bit blank - rarity symbol

Could use the 'M' logo as a rarity symbol for cardbuilder cards

**Comment by lodici** [comment]
Why not add the rarity to the script file so you can use a rarity icon - it's in the json feed?

**Comment by ShawnieBoy** [comment]
Rarity is in the script file already - was just suggesting a Magarena symbol for rarity

**Comment by lodici** [comment]
So why not use the appropriate rarity icon?

**Comment by ShawnieBoy** [comment]
Rarity icons are dependant on set - we don't use multiple images for each set version

**Comment by lodici** [comment]
I understand (I think) - the M symbol would represent the special Magarena set.

**Comment by ShawnieBoy** [comment]
Well, it would technically be representing all sets. Cards that are reprinted in multiple sets don't have separate set versions - we just use the most recent image and oracle.

**Comment by ShawnieBoy** [comment]
How about these?
![mythic](https://cloud.githubusercontent.com/assets/2363180/12121158/c4dc0c96-b3cb-11e5-93ea-971fcdb4bee0.png)
![rare](https://cloud.githubusercontent.com/assets/2363180/12121160/c4f0e1a2-b3cb-11e5-908e-d24423fffe8e.png)
![uncommon](https://cloud.githubusercontent.com/assets/2363180/12121161/c50e2028-b3cb-11e5-88c0-64fb22fdef7b.png)

**Comment by lodici** [comment]
Very nice. Bit big though. The gold one would make a great logo...oh wait, we've already been down that route!

**Comment by ShawnieBoy** [comment]
Hehe

Thankfully they scale well - Will see how they look on a card.

**Comment by lodici** [comment]
> Thankfully they scale well - Will see how they look on a card.

There is no point in storing an image greater than the max size it is going to be used in the jar. That is just inefficient and a waste of space. Creating images and scaling at runtime are expensive operations and we should try to keep these to a minimum to avoid lag. By all means add to _excluded at whatever size.

**Comment by ShawnieBoy** [comment]
I meant in Photoshop - Will have to check the amount of unneeded in-game scaling.
