### ISSUE TITLE
getFlippedDefinition() and getTransformedDefinition() both return null for unimplemented cards

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#633]
Unimplemented cards don't have a CardDefinition for obvious reasons.

However, would it be possible to generate a partial CardDefinition?

This would contain things like name, mana cost, types etc. Essentially everything that can parse ok and still remain an unimplemented card?
Even being able to partially parse ability text would be very useful for things like Devoid and Leveller, and having the information of a card's transformed definition in regards to transform-type symbol to use (Sun, Moon, Planeswalker, 'Spark')

**Comment by melvinzhang** [comment]
Enable "show missing card data" in preferences?

**Comment by ShawnieBoy** [comment]
The main thing that led me to this is the combination of #577 and trying to get the information for Flip + Transfrom via getFlippedDefinition() + getTransformedDefinition()

**Comment by melvinzhang** [comment]
I'm not getting how this goes beyond "show missing card data".  It shows name, mana cost, types, pt, oracle text etc for cards in scripts_missing. What are the additional things you need that is not already provided by "show missing card data"?

**Comment by ShawnieBoy** [comment]
getFlippedDefinition() and getTransformedDefinition() both return null for unimplemented cards

**Comment by ShawnieBoy** [comment]
Unimplemented cards also don't have abilities - even though some of the abilities can parse. For cardbuilder the important ones being Devoid, Level up and Miracle

**Comment by melvinzhang** [comment]
That is not an unimplemented cards issue, all cards have this problem. Abilities are loaded on demand as it is slow and takes up memory. Both getFlippedDefinition and getTransformatedDefinition also fall #577, they are also loaded on demand .

**Comment by melvinzhang** [comment]
Sorry, my mistake, getFlippedDefinition itself does the loading, so we don't need to call loadAbilities. Calling getFlippedDefinition or getTransformedDefinition will return the correct MagicCardDefinition, even for unimplemented cards. Returning null is a bug.

**Comment by melvinzhang** [comment]
@ShawnieBoy how I can replicate the getFlipped/TransformDefinition returning null bug?

**Comment by melvinzhang** [comment]
@ShawnieBoy Are you trying to get unimplemented cards to switch on click and it is not working?

**Comment by ShawnieBoy** [comment]
Nope, I just need to compare the card types of a transform card with it's hidden half.

To replicate the bug - you'd need to include getFlipped and getTransform to IRenderableCard - and retrieve them from PTFrame,getTransformSymbol()

```java
static void drawTransformSymbol(BufferedImage cardImage, IRenderableCard cardDef) {
        Graphics2D g2d = cardImage.createGraphics();
        BufferedImage typeSymbol = ResourceManager.sunSymbol;
        if (cardDef.isHidden()) {
            typeSymbol = cardDef.isPlaneswalker() && cardDef.getTransformedDefintion.isPlaneswalker() ? ResourceManager.moonSymbol: ResourceManager.planeswalkerTypeSymbol;
        } else if (cardDef.isCreature() && cardDef.getTransformedDefinition().isPlaneswalker()) {
            typeSymbol = ResourceManager.sparkSymbol;
        }
        g2d.drawImage(typeSymbol, 19, 25, null);
        g2d.dispose();
    }
```

**Comment by melvinzhang** [comment]
Do you already have these changes? If so please commit it so that we can replicate the bug. As mentioned, it should return the proper card definition for unimplemented cards as long as the flip= or transform= is defined in the card script.

**Comment by ShawnieBoy** [comment]
Ok - will do

**Comment by melvinzhang** [comment]
I was testing with card explorer, and what I get is a crash as it trying to load the unimplemented card script from scripts folder. This is fixed by adding a getMissingOrCard method to card definitions to first check the missingCards map, see https://github.com/magarena/magarena/commit/1fee8d660719ec9555010f3ec54c6799c1748a30

Bonus is that when "show missing card data" is on, clicking on unimplemented flipped/transform cards will show the other side, just like with regular cards.

**Comment by ShawnieBoy** [comment]
Ahh, I see - That looks like it's fixed it.

Nice added extra too :grinning:

**Comment by melvinzhang** [comment]
Were you actually able to get a null value returned? There should never happen, what I got was a crash in the CardDefinitions.getCard call when it tries to load a missing card script. If you could get getFlipped/TransformDefinition to return a null please let me know, that should never happen.

**Comment by ShawnieBoy** [comment]
Looking back through the log crash, I think I may have merged two crashes in my head - It was a file not found error. The null was related to tokens and rarity which I've since solved.

**Comment by melvinzhang** [comment]
Thanks, that clear things up. I got a file not found error due to CardDefinitions.getCards as well.
