### ISSUE TITLE
MagicType enum order

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#634]
The current order is alphabetical - is this order required?

There's potentially two Type-ordering methods:
 - one for cardbuilder which will eventually take into account in-game types
 - one for cardexplorer

If the enum was ordered in the same priority for cards, these methods needn't be used and can just traverse MagicType instead.

**Comment by melvinzhang** [comment]
The order is following the rules document, I think it is better to keep in sync with the order as presented in the rules text as that is the source of truth, makes it easier to update when new types are added to the rules text. If alternative ordering are needed, please create a List<MagicType> constant in MagicType.

**Comment by ShawnieBoy** [comment]
The List constant would also need to be updated as well - but will add a new set

**Comment by melvinzhang** [comment]
Yes, it would have to be. It needs to be a `List<MagicType>` not Set to have a different order from the one in MagicType.

**Comment by ShawnieBoy** [comment]
Closed via dfd18996f7c5ea9fae444bea9620f886b7c3470a
