### ISSUE TITLE
Create an AUR package for Magarena

### ISSUE THREAD

**Issue by Airon90** [magarena/magarena#635]
Hi, could someone create  an AUR script to make Magarena available to Arch Linux users?

[This](https://wiki.archlinux.org/index.php/Creating_packages) is a page from the Arch Linux wiki about creating an AUR package.

**Comment by vmassuchetto** [comment]
Here: https://aur.archlinux.org/packages/magarena

**Comment by melvinzhang** [comment]
Awesome! Thanks @vmassuchetto :smiley:

**Comment by melvinzhang** [comment]
@vmassuchetto I noticed that the launcher script in /usr/bin/magarena duplicates the JVM options from https://github.com/magarena/magarena/blob/master/release/Magarena.sh This may cause an issue when we need to adjust the JVM options. Would it be possible to call Magarena.sh from your launcher?

**Comment by vmassuchetto** [comment]
This was the solution I found to share the jar file and leave each user with its own options in the system. (the default options get stored and are copied on demand). Is there any better way of doing it?

If not, we can just parse the `Magarena.sh` and copy those options on package generation.

**Comment by melvinzhang** [comment]
Thanks for the clarification, I see the issue now. You are sharing the jar file but the Magarena.sh assumes a local copy of the jar file. 

What if we enhance Magarena.sh to accept an optional argument that is the path to the jar file? Then you could call it with the path to the shared jar file. Would that work?

**Comment by vmassuchetto** [comment]
To be distributable, `Magarena.sh` would have to get arguments for both user data and jar file locations.

Anyway, just updated the package to generate a launch script that automatically updates the call parameters for JVM when installed.

**Comment by melvinzhang** [comment]
Thanks for the suggestion! We have provisions to customize the user dir, by passing -Dmagarena.dir=<path> as a JVM option. We will add both of these to the `Magarena.sh`, first option is the path to jar file and second option is the path to user dir.

**Comment by vmassuchetto** [comment]
That would be perfect. It's way safer to use the default script. I'll update the package, then.

**Comment by melvinzhang** [comment]
Implemented the parameters for path to jar and magarena.dir in commit https://github.com/magarena/magarena/commit/5cd24d378c777d71630e1b476eedbfb6e5d42b58

Note that the path should be the folder containing the Magarena folder, in the case of the package that should be ` $HOME/.magarena` Please give this a try and let us know how it goes.

**Comment by vmassuchetto** [comment]
Works beautiful. So it will be shipped in 1.84?

**Comment by melvinzhang** [comment]
Thanks for testing it out. Yes, this commit will be included in 1.84 (April) release.
