### ISSUE TITLE
Remove all references to UI from model and data classes.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#64]
Once this is done it will be much easier to implement the UI using a more modern alternative to Swing such as JavaFX, LibGDX, Slick2D, etc without requiring any changes to core classes. It might even be worthwhile considering moving the core classes into a separate library.

**Comment by melvinzhang** [comment]
Great initiative! Following are the list of classes outside of src/magic/ui that references ui:
src/magic/MagicUtility.java:import magic.ui.ScreenController;
src/magic/data/TextImages.java:import magic.ui.IconImages;
src/magic/data/CardStatistics.java:import magic.ui.IconImages;
src/magic/utility/MagicDownload.java:import static magic.ui.widget.downloader.HQImagesDownloadPanel.getImageDimensions;
src/magic/utility/MagicStyle.java:import magic.ui.screen.interfaces.IThemeStyle;
src/magic/utility/MagicStyle.java:import magic.ui.theme.Theme;
src/magic/utility/MagicStyle.java:import magic.ui.theme.ThemeFactory;
src/magic/utility/GraphicsUtilities.java:import magic.ui.theme.Theme;
src/magic/model/stack/MagicTriggerOnStack.java:import magic.ui.IconImages;
src/magic/model/stack/MagicCardOnStack.java:import magic.ui.IconImages;
src/magic/model/stack/MagicAbilityOnStack.java:import magic.ui.IconImages;
src/magic/model/choice/*
src/magic/model/player/PlayerProfile.java:import magic.ui.IconImages;
src/magic/model/player/PlayerProfile.java:import magic.ui.theme.PlayerAvatar;
src/magic/model/MagicManaCost.java:import magic.ui.IconImages;
src/magic/model/MagicPlayerDefinition.java:import magic.ui.theme.PlayerAvatar;
src/magic/model/MagicGameReport.java:import magic.ui.ScreenController;
src/magic/model/event/MagicMorphCastActivation.java:import magic.ui.IconImages;
src/magic/FiremindQueueWorker.java:import magic.ui.GameController;
src/magic/game/state/GameStateFileReader.java:import magic.ui.ScreenController;
src/magic/DeckStrCal.java:import magic.ui.GameController;
src/magic/MagicMain.java:import magic.ui.ScreenController;

**Comment by lodici** [comment]
I think that just about matches my own list. Also any direct references to ``javax.swing.*`` and ``java.awt.*`` will need to be removed - JavaFX for example, uses ``javax.scene.image`` instead of ``java.awt.BufferedImage``. I am currently looking at ``magic.ui.IconImages`` which effectively provides direct links to ``BufferedImage`` and ``javax.swing.ImageIcon`` objects which you don't want in the core classes.

**Comment by lodici** [comment]
Moved ``GraphicsUtilities.java`` and ``MagicStyle.java`` into UI package.

**Comment by lodici** [comment]
fixed: ``magic.model.stack``, ``magic.model.event`` and ``magic.data.CardStatistics.java``.

**Comment by lodici** [comment]
I have updated ``src/magic`` so that it only contains 'launch' classes (ie. containing the ``main`` method) which also means that it can be crossed off the list since these classes would not be included in a library of core classes, each being specific to the type of app you are running - ie, ``MagicMain`` runs Magarena using a Swing UI, ``DeckStrCal`` runs as Ai vs Ai headless mode (likewise ``FiremindQueueWorker``).

**Comment by melvinzhang** [comment]
crossed off the launch classes

**Comment by melvinzhang** [comment]
Added SoundEffects as it references packages not available on android (javax.sound). Suggest moving it to ui as it is platform specific, similar to swing.

**Comment by lodici** [comment]
> Added SoundEffects as it references packages not available on android (javax.sound). Suggest moving it to ui as it is platform specific, similar to swing.

I think this is a good point. For example, JavaFX has a much improved sound handling library so even though it is not strictly UI related sound does seem to be intrinsically tied in with the UI of choice.

**Comment by lodici** [comment]
Phew, player avatars - what a pain extricating that from the core classes! One side effect is fa502bc6a840dc53cf114e5ccb5fdfce8846f3fb which removes the requirement to specify the avatar image (using an obscure integer index) when defining players in a test case since the image is basically irrelevant in the content of running a test game.

**Comment by melvinzhang** [comment]
Good stuff! This set of changes feels very exciting to me, its like we now able to almost see the reusable abstract core of the game.

**Comment by lodici** [comment]
There were a number of cases where model and data classes were referencing the MagicMain launch class to get the latest version or to display a progress message on startup. I have removed all these references but please note that the VERSION constant has been moved to the ``magic.data.GeneralConfig`` class.

**Comment by lodici** [comment]
Almost there...
![screenshot00032](https://cloud.githubusercontent.com/assets/2443519/6203780/aa87c4e8-b52a-11e4-89e8-b3a53d119d65.png)

**Comment by lodici** [comment]
While looking at ``MagicGameReport`` I took the opportunity to update the exception handling. ``MagicGameReport`` is now gone, replaced by classes in new ``magic.exception.handler`` package. This contains two non-ui handlers - ``ConsoleExceptionHandler`` which outputs the report to stderr and ``FileExceptionHandler`` which saves the report to ``crash.log`` (and outputs to stderr). I have updated ``DeckStrCal`` to use ``ConsoleExceptionHandler`` but you can easily replace with ``FileExceptionHandler`` if required (wasn't sure whether Jenkins expects it or not so went for the simplest solution). ``MagicMain`` uses ``UiExceptionHandler`` which is in the ``magic.ui`` package and should work more or less the same as ``MagicGameReport``.

**Comment by melvinzhang** [comment]
Looks good, DeckStrCal logging to console is what is needed by Jenkins.

There is a problem with the removal of try/catch around doAction, it is
needed to report the correct MagicGame instance. AI always creates clones
of MagicGame to test various actions safely without affected the actual
game. Sometimes an error occurs inside one of these cloned MagicGame
instance.

I've restored the try/catch around doAction by adding GameException to
store the private copy of the game, and modified ExceptionReport to extract
the game instance from GameException.

**Comment by lodici** [comment]
Only ``magic.model.choice`` to go but unfortunately on first look this could be difficult.

**Comment by melvinzhang** [comment]
For the GameController I think we should make it an interface and have SwingGameController be the concrete class in the ui package. 

The *ChoicePanel dependency is more tricky, one way is to move it into GameController interface as a method. For MagicBasicLandChoice's getPlayerChoiceResults could be written as
````
controller.disableActionButton(false);                                                                                                                                                
return new Object[]{controller.askForLandSubType(controller, source)};
````

**Comment by lodici** [comment]
> For the GameController I think we should make it an interface and have SwingGameController be the concrete class in the ui package.

Good idea. ``DeckStrCal`` also references the controller so ultimately it might be worth looking at a concrete ``HeadlessGameController`` as well. This exercise would help to identify a common ``GameController`` class which can be added to the core library and from which the ``SwingGameController`` and ``HeadlessGameController`` can extend.

**Comment by lodici** [comment]
I will work on implementing ``IGameController`` and a concrete ``SwingGameController`` first (maybe with an eye on ``HeadlessGameController`` as well) which should get rid of ``import magic.ui.GameController;`` from all *choice classes.

**Comment by lodici** [comment]
> The *ChoicePanel dependency is more tricky, one way is to move it into GameController interface as a method.
Also very good solution! I have started implementing this as well...

**Comment by lodici** [comment]
Ok, I think that's it! To test, I created a new library project in Netbeans and copied all core classes (see screenshot). Once the required libraries were added I was able to successfully create ``magarena-core.jar``. I then created a simple java project with just ``DeckStrCal`` and a link to the jar and it worked perfectly. I also tried updating a JavaFX project I have been playing around with and was able to remove all the ``magic.*`` packages and just link to ``magarena-core`` and it worked as well. I was also able to whip up a much smaller non-ui ``HeadlessGameController`` which ``DeckStrCal`` now uses. Next step is to identify common functionlity with ``SwingGameController``.

![screenshot00033](https://cloud.githubusercontent.com/assets/2443519/6235638/e2feb1a8-b6db-11e4-921e-2794454fbeaf.png)

**Comment by melvinzhang** [comment]
I've switched DeckStrengthViewer and FiremindQueueWorker over to HeadlessGameController. Only the UI uses SwingGameController now.

**Comment by lodici** [comment]
In looking to remove UI references from DeckUtils there is some particularly messy code for handling unsupported cards when loading a deck. Currently it will actually fail when running from DeckStrCal because it attempts to display a dialog. The intent (which will work from the UI) is to drop any unsupported cards and continue with a slightly lighter deck. This is inconsistent with how the UI handles decks in other cases so I intend to rectify this. Since DeckStrCal uses the same code for loading decks, should it also fail or just drop the invalid cards (with a suitable stderr message) and continue dueling with a smaller deck?

**Comment by melvinzhang** [comment]
DeckStrCal should fail with a suitable message to stderr, it wouldn't be a proper comparison of deck or AI strength if not all the cards are used.

**Comment by lodici** [comment]
All the ``UnsupportedException`` _*Choice_ method stubs in ``HeadlessGameController`` are a bit smelly. For a simpler ``HeadlessGameController``, suggest -

    HeadlessGameController -> IGameController
    SwingGameController -> IUiGameController -> IGameController

where all the _*Choice_ methods in ``IGameController`` are moved into ``IUiGameController``.

**Comment by melvinzhang** [comment]
Good idea!

**Comment by lodici** [comment]
Everything on the above list has now been de-UI'd.
