### ISSUE TITLE
Highlight graveyard zone when containing cards with activated abilities

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#643]
Currently the cards themselves in the graveyard are highlighted when they have an ability that can be activated, however you have to look in that zone to see them.

If each zone with available cards could be outlined in the Roll-over color from the theme, this would aid in finding cards that can be used (Could also be used for the Hand zone if you're in a different zone).

![look hand](https://cloud.githubusercontent.com/assets/2363180/12357724/76760b14-bba1-11e5-9b6e-0bb4f1c25f31.png)
Graveyard highlighted as cards can be activated, but currently in the hand zone.

![in grave](https://cloud.githubusercontent.com/assets/2363180/12357801/ec0b1d06-bba1-11e5-8349-dc1e3d9b754d.png)
Graveyard selected, and no cards in hand are able to be cast. If there were, it would have the highlight outline.

**Comment by lodici** [comment]
Looks good. This has definitely been mentioned before.

**Comment by lodici** [comment]
Implemented in 3f4aa3389f93bee17c88f34232b0ba2d824182b5 (although uses the same highlight color applied to the cards for consistency).
![screenshot00613](https://cloud.githubusercontent.com/assets/2443519/26282046/7e8867ec-3e00-11e7-9942-ba4826f98c95.jpg)
