### ISSUE TITLE
Implementing Haunt

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#654]
I've been fiddling with this ability using Cipher as a guide, and I'm having a bit of a problem with ensuring the 'owner' of the effect is correct when an opponent's creature is haunted.

I'll push what I have so far (also doesn't work with Haunt-spells) as it won't have any effect without added scripts.

**Comment by ShawnieBoy** [comment]
I do feel as though the HauntTrigger should be using OtherDiesTrigger where died=haunted

**Comment by melvinzhang** [comment]
When Haunted creature dies should be implemented as a delayed trigger whose source is the permanent with huant and player is the controller of the permanent, the trigger is linked to the creature that is haunted as done now. See scripts containing DelayedTrigger, eg release/Magarena/scripts/Vizkopa_Guildmage.groovy

**Comment by melvinzhang** [comment]
I'm working on adding a createDelayed to ThisDiesTrigger to be used in Haunt.

**Comment by melvinzhang** [comment]
Done, also simplified HauntTrigger by extending ThisDies instead of OtherDies. Not tested as I don't have any Haunt cards on hand.

**Comment by ShawnieBoy** [comment]
Excellent, thanks - It seems to be working well, although will have to test with a simpler deck as it's very confusing with a deck full of them!

I'll push the creatures with haunt

**Comment by ShawnieBoy** [comment]
All looks good.

For spells, the Haunt trigger occurs after the spell has resolved i.e. 'successfully' cast. A `WhenSpellIsCastTrigger` is too soon, and `WhenPutIntoGraveyardTrigger` while generally for permanents, wouldn't know if the spell had been countered or not.

I've looked at the trigger-types and wouldn't really want to include one for resolved spells.

It's confusing as it's an ability which functions like a MagicSpellCardEvent similar to Buyback and am having trouble tracing it's path.

**Comment by ShawnieBoy** [comment]
...Ok, worked out what's going on - will see if I can use buyback as a guide.

**Comment by ShawnieBoy** [comment]
The problem with that, is that it would give permanents the spell version of Haunt :confounded:

**Comment by melvinzhang** [comment]
Permanents get Haunt as an ability, spells get it as an effect. Why would there by any overlap?

**Comment by melvinzhang** [comment]
Rebound would be a good example to follow.

**Comment by ShawnieBoy** [comment]
I think I'm just thinking of it in 'rules-mode' - As it's a triggered ability, not an effect. (Did see Rebound :grinning: )

**Comment by melvinzhang** [comment]
For spell, it would be an effect that creates a triggered ability, much like how the permanent's version is a trigger (HauntTrigger) that creates a trigger (the delayed trigger).

**Comment by ShawnieBoy** [comment]
Just an example that doesn't exist, hehe: 'Search you library for a card with Haunt' wouldn't find haunt spells.
I know it doesn't matter really, just try to get everything by-the-book

**Comment by melvinzhang** [comment]
As an example, DrawSelfNextUpkeep is an effect that creates a delayed trigger.

**Comment by melvinzhang** [comment]
Doing it as a custom MagicSpellCardEvent like Buyback is essentially the same thing, i.e. putting it into the spell effect but in a much more messy way. The reason why I did Buyback that way is to avoid duplicating Buyback both in the ability property and in the effect, since the ability version is needed to setup the additional cost.

**Comment by ShawnieBoy** [comment]
At least with Buyback, even though it's not functioning as an ability, it is an ability and can be recognized by any effects that would look for that ability. It's also different as it has a cost involved.

**Comment by melvinzhang** [comment]
Doing buyback as part of the effect was a much cleaner solution code-wise, but it introduces this duplication of requiring buyback twice (once in the ability and once in the effect).

**Comment by ShawnieBoy** [comment]
Yes, I don't think there's any way around that really.
Coming from it from a rules angle, having abilities being recognised as abilities would be preferable.
I think Cascade is the only other non-cost related spell-ability which also appears on permanents.

**Comment by ShawnieBoy** [comment]
The main problem with Haunt is that it's essentially two abilities with the same name.
"When this creature dies, exile it haunting target creature."
and
"When this spell card is put into a graveyard after resolving, exile it haunting target creature."

**Comment by melvinzhang** [comment]
Just saw a deeper flaw for "Haunt" as part of the effect, it cannot be countered with Stifle. Does your current method generate a trigger on the stack for "Haunt" for spells?

**Comment by ShawnieBoy** [comment]
> Just saw a deeper flaw for "Haunt" as part of the effect, it cannot be countered with Stifle. Does your current method generate a trigger on the stack for "Haunt" for spells?

It's what I'm attempting :confounded:

**Comment by melvinzhang** [comment]
My bad, actually Haunt as an effect can create a trigger, by using EnqueueTriggerAction to put the Haunt event on the stack.

**Comment by melvinzhang** [comment]
The MagicEvent returned by HauntTrigger.executeTrigger is almost good enough except that it needs to be generalized to work for both permanent and card on stack.

**Comment by ShawnieBoy** [comment]
Still makes me lean towards a SpellResolvedTrigger

**Comment by melvinzhang** [comment]
One approach is to create a separate HauntEvent that can be created in two forms, with a permanent and with a card on stack. Change HauntTrigger to return new HauntEvent(permanent), and the spell version to use new HauntEvent(cardonstack).

**Comment by ShawnieBoy** [comment]
I keep coming back to haunt on spells and each time I get myself into a confused mess! The haunt ability creates an effect, which creates a trigger, to add an effect which creates the delayed trigger.
I've pushed what I've assembled so far - and still functions for permanents - but I can't wrap my brain around spells.
Could you have a look @melvinzhang ?

**Comment by melvinzhang** [comment]
What's the issue with spells? A test game with steps to replicate will be very useful.

**Comment by melvinzhang** [comment]
Off hand from looking at the src for MagicAbility, both Haunt and HauntSpell are empty so spells have nothing additional over a normal spell with effect and no abilities.

**Comment by ShawnieBoy** [comment]
The problem I have is, well my brain I think! At the moment the ability for permanents is added via it's own death trigger. However making a trigger to add a trigger is confusing my brain as each needs to know the effect to add it to the second trigger.

Haunt for permanents is implemented as a kind-of cheat for an Ability. Doing the same for spells. HauntSpell is currently empty as I'm not sure how best to even start it. Trying to keep it as an ability to prevent using Haunt twice in the script had me trying to include is akin to Cascade or Buyback.

**Comment by ShawnieBoy** [comment]
Spell ability -> HauntSpellTrigger (added after resolution) -> HauntTrigger (on targeted permanent) -> HauntEffect.

The first two sections have me confused.

**Comment by melvinzhang** [comment]
I think you are stuck because it is implemented as card script, try doing it in groovy first. Then it will become clear how it would look as a script.

**Comment by ShawnieBoy** [comment]
:+1: Good idea - thanks!

**Comment by melvinzhang** [comment]
"When the creature SN haunts dies, ..." isn't a triggered ability of the card, it is an effect that creates a delayed trigger. It is similar to a delayed draw effect, eg "You draw a card at the beginning of the next turn's upkeep".

**Comment by melvinzhang** [comment]
My bad, it is a triggered ability of the card based on rule 702.54c which states that "Triggered abilities of cards with haunt that refer to the haunted creature can trigger in the exile zone." Unfortunately we only support triggered abilities on permanents, so we can only stick the trigger on the haunted creature instead.

**Comment by ShawnieBoy** [comment]
Yes, that's for the final effect, however there needs to be a casting trigger for spells so that the ability can then choose a creature to haunt.

**Comment by ShawnieBoy** [comment]
"When this spell card is put into a graveyard after resolving, exile it haunting target creature." Would essentially be another delayedTrigger?

**Comment by melvinzhang** [comment]
That would be an immediate trigger, you can add it with EnqueueTriggerAction.

**Comment by ShawnieBoy** [comment]
But the trigger can't be queued when the spell is cast, as it may be countered.

**Comment by melvinzhang** [comment]
Correct, it should be last item in the spell's effect.
For example, 
```
new MagicSpellCardEvent() {
  ...
   public void executeEvent(final MagicGame game, final MagicEvent event) {
      // regular part of the spell's effect
      ...
      // enqueue haunt trigger
      game.doAction(new EnqueueTriggerAction(new MagicHauntEvent(...));
   }
}
```
If there is a target, the enqueue should inside the processTarget block.

**Comment by ShawnieBoy** [comment]
:+1:  Yes - Thanks for your patience, getting there - hehe

**Comment by ShawnieBoy** [comment]
I think I've got it sorted - going through the groovy version first was a good help.

While the implementation doesn't have the Haunt effect part of the processTarget, it should only be added when it resolves as part of the executeEvent of the spell.

**Comment by melvinzhang** [comment]
If it is not part of the processTarget block, it will always run. So even if I make the target illegal, the Haunt trigger will still activate which should not be the case.

**Comment by ShawnieBoy** [comment]
Ahh yes, I see - that's a bit of a problem. Is there a way of checking if an effect resolved?

**Comment by melvinzhang** [comment]
There is no way to check. As this is a very small number of cards, I'd recommend doing it all as groovy code and putting the Enqueue in the processTarget block.

**Comment by melvinzhang** [comment]
The buyback hack is also wrong in the same way, the card should not go back to hand if it is countered by game rules due to illegal target.

**Comment by melvinzhang** [comment]
I guess one way around this is to do the illegal target check in the executeEvent. It is possible in some sense.

**Comment by melvinzhang** [comment]
Another problem with Haunt is that it does not interact correctly with Rest in Peace which prevents cards from going to graveyard.

**Comment by ShawnieBoy** [comment]
Would make sense, a legal target is needed to cast - so warrants a check. Then before it resolves check again.

**Comment by ShawnieBoy** [comment]
Haunt does check if the card is in the graveyard

**Comment by melvinzhang** [comment]
Ah, that's right, good. Even though the trigger activates, it will do nothing on resolution. Good enough for now.

**Comment by ShawnieBoy** [comment]
The one issue I had with groovy, was using a MagicSourceEvent and MagicRuleEventAction - I couldn't get the cards to function, but I could see the correct structure.

**Comment by ShawnieBoy** [comment]
Whoops, crash (doesn't look as though it's related to Haunt)
```
CRASH REPORT FOR MAGARENA THREAD Thread[pool-24-thread-1,5,main]
CREATED ON 2016/01/28 14:36:36
MAGARENA VERSION 1.70, JRE 1.8.0_66, OS Windows 10_10.0 amd64
================================
Used Memory: 645M
Free Memory: 345M
Total Memory: 990M
Max Memory: 990M
================================
-Ddebug=true
-Xms256M
-Xmx1g


Turn : 6  Phase : FirstMain  Step : ActivePlayer  Player : Monty Carlo  Score : 0
0] Player : ShawnieBoy  Life : 30  Delayed : Total=0
   - Hand : Unknown
   - Hand : Unknown
   - Graveyard : Nip Gwyllion
   - Permanent : Scoured Barrens  Tapped
   - Permanent : Scoured Barrens  Tapped  Summoned
   - Permanent : Swamp  Tapped
1] Player : Monty Carlo  Life : 24  Delayed : Total=0
   - Hand : Tainted Field
   - Hand : Scoured Barrens
   - Hand : Tainted Field
   - Hand : Unknown
   - Graveyard : Seize the Soul
   - Graveyard : Orzhov Euthanist
   - Graveyard : Nip Gwyllion
   - Permanent : Plains
Stack : 0
1. ExecuteFirstEventAction = 0
2. DiscardCardAction = -290
3. MoveCardAction (Orzhov Euthanist,OwnersHand,Graveyard) = 0
4. PutItemOnStackAction (MagicTriggerOnStack,Cry of Contrition) = 1
5. AddEventAction (EVENT: Cry of Contrition  Choose target creature.) = 0
6. DequeueTriggerAction = 0
7. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
8. ExecuteFirstEventAction = 0
9. ExecuteFirstEventAction = 0
10. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
11. ExecuteFirstEventAction = 0
12. StackResolveAction = 0
13. RemoveCardAction (Cry of Contrition) = 0
14. MoveCardAction (Cry of Contrition,Graveyard,Exile) = 0
15. AddTriggerAction (Nip Gwyllion,magic.model.trigger.ThisDiesTrigger$2@7b506876) = 0
16. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
17. ExecuteFirstEventAction = 0
18. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
19. ExecuteFirstEventAction = 0
20. AddEventAction (EVENT: NONE  Declare attackers.) = 0
21. ExecuteFirstEventAction = 0
22. DeclareAttackersAction = 0
23. TapAction (Nip Gwyllion) = 10
24. DeclareAttackerAction = 0
25. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
26. ExecuteFirstEventAction = 0
27. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
28. ExecuteFirstEventAction = 0
29. AddEventAction (EVENT: NONE  Declare blockers.) = 0
30. ExecuteFirstEventAction = 0
31. DeclareBlockersAction = 0
32. DeclareBlockerAction = 0
33. SetBlockerAction = 0
34. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
35. ExecuteFirstEventAction = 0
36. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
37. ExecuteFirstEventAction = 0
38. CombatDamageAction = 0
39. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
40. ExecuteFirstEventAction = 0
41. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
42. ExecuteFirstEventAction = 0
43. CombatDamageAction = 0
44. DealDamageAction = 0
45. ChangeStateAction = 0
46. ChangeLifeAction (Monty Carlo,1) = 100
47. ChangePlayerStateAction = 0
48. AddStaticAction (MagicPermanent.NONE,magic.model.action.ChangePlayerStateAction$3@4fd6169c) = 0
49. DealDamageAction = 0
50. ChangeStateAction = 0
51. ChangeLifeAction (ShawnieBoy,1) = -100
52. ChangePlayerStateAction = 0
53. RemoveFromCombatAction (Nip Gwyllion) = 0
54. ChangeStateAction = 0
55. ChangeStateAction = 0
56. ChangeStateAction = 0
57. RemoveFromCombatAction (Nip Gwyllion) = 0
58. ChangeStateAction = 0
59. ChangeStateAction = 0
60. DestroyAction = 0
61. RemoveAllFromPlayAction = 0
62. RemoveFromPlayAction (Nip Gwyllion,0) = 922
63. EnqueueTriggerAction = 0
64. EnqueueTriggerAction = 0
65. EnqueueTriggerAction = 0
66. RemoveFromCombatAction (Nip Gwyllion) = 0
67. MoveCardAction (Nip Gwyllion,Battlefield,Graveyard) = 0
68. DestroyAction = 0
69. RemoveAllFromPlayAction = 0
70. RemoveFromPlayAction (Nip Gwyllion,0) = -922
71. EnqueueTriggerAction = 0
72. RemoveFromCombatAction (Nip Gwyllion) = 0
73. MoveCardAction (Nip Gwyllion,Battlefield,Graveyard) = 0
74. RemoveTriggersStaticsAction = 0
75. RemoveTriggersStaticsAction = 0
76. PutItemOnStackAction (MagicTriggerOnStack,Benediction of Moons) = -1
77. DequeueTriggerAction = 0
78. PutItemOnStackAction (MagicTriggerOnStack,Benediction of Moons) = 1
79. DequeueTriggerAction = 0
80. PutItemOnStackAction (MagicTriggerOnStack,Cry of Contrition) = 1
81. AddEventAction (EVENT: Cry of Contrition  Choose target creature that was dealt damage this turn.) = 0
82. DequeueTriggerAction = 0
83. PutItemOnStackAction (MagicTriggerOnStack,Cry of Contrition) = 1
84. DequeueTriggerAction = 0
85. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
86. ExecuteFirstEventAction = 0
87. ExecuteFirstEventAction = 0
88. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
89. ExecuteFirstEventAction = 0
90. StackResolveAction = 0
91. ChangeLifeAction (ShawnieBoy,2) = -200
92. ChangePlayerStateAction = 0
93. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
94. ExecuteFirstEventAction = 0
95. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
96. ExecuteFirstEventAction = 0
97. StackResolveAction = 0
98. DestroyAction = 0
99. RemoveAllFromPlayAction = 0
100. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
101. ExecuteFirstEventAction = 0
102. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
103. ExecuteFirstEventAction = 0
104. StackResolveAction = 0
105. ChangeLifeAction (ShawnieBoy,2) = -200
106. ChangePlayerStateAction = 0
107. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
108. ExecuteFirstEventAction = 0
109. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
110. ExecuteFirstEventAction = 0
111. StackResolveAction = 0
112. ChangeLifeAction (Monty Carlo,2) = 200
113. ChangePlayerStateAction = 0
114. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
115. ExecuteFirstEventAction = 0
116. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
117. ExecuteFirstEventAction = 0
118. ReturnExiledAction = 0
119. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
120. ExecuteFirstEventAction = 0
121. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
122. ExecuteFirstEventAction = 0
123. CleanupTurnTriggersAction = 0
124. CleanupPlayerAction = 0
125. CleanupPermanentAction = 0
126. CleanupPermanentAction = 0
127. CleanupPermanentAction = 0
128. CleanupPlayerAction = 0
129. CleanupPermanentAction = 0
130. CleanupTurnStaticsAction = 0
131. UntapAction (Plains) = 5
132. DrawAction = 300
133. AddEventAction (EVENT: NONE  ...) = 0
134. ExecuteFirstEventAction = 0
135. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
Score = -172

Exception from controller.runGame: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
magic.exception.GameException: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at magic.ai.MCTSAI.growTree(MCTSAI.java:421)
	at magic.ai.MCTSAI.TreeUpdate(MCTSAI.java:240)
	at magic.ai.MCTSAI$1.run(MCTSAI.java:147)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at magic.ai.MCTSAI.growTree(MCTSAI.java:417)
	... 5 more
```

**Comment by melvinzhang** [comment]
Can the crash be replicated? Hard to say if Haunt is involved, this is a very generic crash, meaning that the game did not play out in the same way every time, eg previously there were 3 choices but later when the AI revisited this section of the game there were only 2 choices.

**Comment by melvinzhang** [comment]
MCTS is particularly sensitive to this type of bugs as it caches the previously search tree and reuses it in the next AI decision. When the reused search tree does not line up with the current game, such a crash will occur.

**Comment by ShawnieBoy** [comment]
Not been able to replicate so far - but will keep an eye out.
On another note - I'm sure you've heard about Goggle and it's Go AI :clap:

**Comment by melvinzhang** [comment]
storing the sourceEvent inside HauntEvent is a bit worrying as it is a tiny bit of hidden state that is not captured by MagicEvent.getStateId ffbd58d39989624e2 fixes it.

**Comment by ShawnieBoy** [comment]
Ok, it's happened again with the same deck - no idea what triggered it

**Comment by ShawnieBoy** [comment]
```
# 3 creatures
4 Nip Gwyllion
4 Orzhov Euthanist
4 Souls of the Faultless

# 3 spells
4 Benediction of Moons
4 Cry of Contrition
4 Seize the Soul

# 4 lands
4 Plains
4 Scoured Barrens
4 Swamp
4 Tainted Field

>
```
This is the deck, and I'm more convinced it's the 'creature dealt damage this turn' which is causing the crash - Mirror match with this seems to crash all the time (at some point).

**Comment by melvinzhang** [comment]
If you could try with asserts enabled (-ea), there will be more useful debug info in the crash. It will show specifically how the game diverged.

**Comment by ShawnieBoy** [comment]
```
CRASH REPORT FOR MAGARENA THREAD Thread[pool-5-thread-1,5,main]
CREATED ON 2016/01/28 15:09:29
MAGARENA VERSION 1.70, JRE 1.8.0_66, OS Windows 10_10.0 amd64
================================
Used Memory: 567M
Free Memory: 1024M
Total Memory: 1592M
Max Memory: 7282M
================================
-Xms1g
-Xmx8g
-ea


Turn : 2  Phase : SecondMain  Step : Resolve  Player : Monty Carlo  Score : 289
0] Player : ShawnieBoy  Life : 21  Delayed : Total=0
   - Hand : Plains
   - Hand : Souls of the Faultless
   - Hand : Souls of the Faultless
   - Hand : Tainted Field
   - Hand : Plains
   - Permanent : Scoured Barrens  Tapped  Summoned
1] Player : Monty Carlo  Life : 22  Delayed : White=1 Total=1
   - Hand : Orzhov Euthanist
   - Hand : Souls of the Faultless
   - Hand : Plains
   - Hand : Cry of Contrition
   - Hand : Orzhov Euthanist
   - Hand : Orzhov Euthanist
   - Graveyard : Benediction of Moons
   - Permanent : Plains  Summoned
Stack : 0
1. ExecuteFirstEventAction = 0
2. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
3. ExecuteFirstEventAction = 0
4. AddEventAction (EVENT: NONE  Declare attackers.) = 0
5. ExecuteFirstEventAction = 0
6. DeclareAttackersAction = 0
7. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
8. ExecuteFirstEventAction = 0
9. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
10. ExecuteFirstEventAction = 0
11. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
12. ExecuteFirstEventAction = 0
13. AddEventAction (EVENT: Plains Play <Plains~1000065>. ) = 0
14. ExecuteFirstEventAction = 0
15. RemoveCardAction (Plains) = -375
16. PlayCardAction = 0
17. AddEventAction (EVENT: Plains Put <Plains~1000065> onto the battlefield. ) = 0
18. ExecuteFirstEventAction = 0
19. PlayCardFromStackAction (Plains) = 679
20. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
21. ExecuteFirstEventAction = 0
22. AddEventAction (EVENT: Benediction of Moons Pay {W}$. Choose how to pay the mana cost.) = 0
23. AddEventAction (EVENT: Benediction of Moons Play <Benediction of Moons~1000053>. ) = 0
24. ExecuteFirstEventAction = 0
25. PayDelayedCostAction = 0
26. ExecuteFirstEventAction = 0
27. RemoveCardAction (Benediction of Moons) = -212
28. PutItemOnStackAction (MagicCardOnStack,Benediction of Moons) = -1
29. AddEventAction (EVENT: Benediction of Moons  ) = 0
30. ExecuteFirstEventAction = 0
31. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
32. ExecuteFirstEventAction = 0
33. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
34. ExecuteFirstEventAction = 0
35. StackResolveAction = 0
36. ChangeLifeAction (Monty Carlo,2) = 200
37. ChangePlayerStateAction = 0
38. AddStaticAction (MagicPermanent.NONE,magic.model.action.ChangePlayerStateAction$3@a04f29a) = 0
39. EnqueueTriggerAction = 0
40. MoveCardAction (Benediction of Moons,Stack,Graveyard) = 0
41. PutItemOnStackAction (MagicTriggerOnStack,Benediction of Moons) = -1
42. AddEventAction (EVENT: Benediction of Moons  Choose target creature.) = 0
43. DequeueTriggerAction = 0
44. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
45. ExecuteFirstEventAction = 0
46. ExecuteFirstEventAction = 0
47. AddEventAction (EVENT: NONE  Play a card or ability.) = 0
48. ExecuteFirstEventAction = 0
49. StackResolveAction = 0
Score = 290

Exception from controller.runGame: java.lang.ArrayIndexOutOfBoundsException: 0
magic.exception.GameException: java.lang.ArrayIndexOutOfBoundsException: 0
	at magic.model.MagicGame.doAction(MagicGame.java:555)
	at magic.model.phase.MagicPhase.executePhase(MagicPhase.java:43)
	at magic.model.MagicGame.executePhase(MagicGame.java:469)
	at magic.model.MagicGame.advanceToNextEventWithChoice(MagicGame.java:794)
	at magic.ai.MCTSAI.runSimulation(MCTSAI.java:473)
	at magic.ai.MCTSAI.randomPlay(MCTSAI.java:446)
	at magic.ai.MCTSAI.access$000(MCTSAI.java:65)
	at magic.ai.MCTSAI$2.run(MCTSAI.java:188)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at magic.model.MagicGame.executeEvent(MagicGame.java:771)
	at magic.model.stack.MagicItemOnStack.resolve(MagicItemOnStack.java:127)
	at magic.model.action.StackResolveAction.doAction(StackResolveAction.java:13)
	at magic.model.MagicGame.doAction(MagicGame.java:553)
	... 10 more
```

**Comment by melvinzhang** [comment]
The exception during resolve is caused by https://github.com/magarena/magarena/commit/0fad2093032f5c1f1e80eda928bf63ac0b19c64c Fix has been pushed.

**Comment by ShawnieBoy** [comment]
Looks like everything's working well - Though have had a thought that ExileLink should be used somewhere, as the death-trigger should only occur if the haunt-card is still in exile.

**Comment by melvinzhang** [comment]
Working well as in no more crashes at magic.ai.MCTSAI.growTree?

c5a997890c9c864a91a5 adds a check similar to Grave Betrayal that will only fire the death-trigger if the haunting card is in exile. 

What else do we need to do for this issue?

**Comment by ShawnieBoy** [comment]
>Working well as in no more crashes at magic.ai.MCTSAI.growTree?

I've not encountered any since.

I think this is all done
