### ISSUE TITLE
ArrayIndexOutOfBoundsException right after mulligan

### ISSUE THREAD

**Issue by itandetnik** [magarena/magarena#656]
Got `ArrayIndexOutOfBoundsException` right after clicking No for "take mulligan" prompt.

    CRASH REPORT FOR MAGARENA THREAD Thread[pool-3-thread-4,5,main]
    CREATED ON 2016/01/25 09:27:57
    MAGARENA VERSION 1.69, JRE 1.8.0_31, OS Windows 7_6.1 x86
    ================================
    Used Memory: 137M
    Free Memory: 110M
    Total Memory: 247M
    Max Memory: 494M
    ================================
    -Xms256m
    -Xmx512m
    -Xverify:none
    
    
    Turn : 1  Phase : Untap  Step : Begin  Player : Igor  Score : 524
    0] Player : Igor  Life : 20  Delayed : Total=0
       - Hand : Honor of the Pure
       - Hand : Soul Warden
       - Hand : Squadron Hawk
       - Hand : Plains
       - Hand : Ranger of Eos
       - Hand : Plains
       - Hand : Plains
    1] Player : Computer  Life : 20  Delayed : Total=0
       - Hand : Hinterland Harbor
       - Hand : Charging Troll
       - Hand : Hallowed Fountain
       - Hand : Angelic Destiny
       - Hand : Noble Hierarch
    Stack : 0
    1. AddEventAction (EVENT: NONE Igor may$ take a mulligan. ) = 0
    2. AddEventAction (EVENT: NONE Computer may$ take a mulligan. ) = 0
    3. ExecuteFirstEventAction = 0
    4. ExecuteFirstEventAction = 0
    5. ShuffleCardsIntoLibraryAction = 0
    6. ShiftCardAction = 0
    7. RemoveCardAction (Ethercaste Knight) = 306
    8. MoveCardAction (Ethercaste Knight,OwnersHand,TopOfOwnersLibrary) = 0
    9. ShiftCardAction = 0
    10. RemoveCardAction (Hinterland Harbor) = 494
    11. MoveCardAction (Hinterland Harbor,OwnersHand,TopOfOwnersLibrary) = 0
    12. ShiftCardAction = 0
    13. RemoveCardAction (Forest) = 412
    14. MoveCardAction (Forest,OwnersHand,TopOfOwnersLibrary) = 0
    15. ShiftCardAction = 0
    16. RemoveCardAction (Akrasan Squire) = 364
    17. MoveCardAction (Akrasan Squire,OwnersHand,TopOfOwnersLibrary) = 0
    18. ShiftCardAction = 0
    19. RemoveCardAction (Deft Duelist) = 375
    20. MoveCardAction (Deft Duelist,OwnersHand,TopOfOwnersLibrary) = 0
    21. ShiftCardAction = 0
    22. RemoveCardAction (Plains) = 375
    23. MoveCardAction (Plains,OwnersHand,TopOfOwnersLibrary) = 0
    24. ShiftCardAction = 0
    25. RemoveCardAction (Breeding Pool) = 506
    26. MoveCardAction (Breeding Pool,OwnersHand,TopOfOwnersLibrary) = 0
    27. ShuffleLibraryAction = 0
    28. DrawAction = -2479
    29. AddEventAction (EVENT: NONE Computer may$ take a mulligan. ) = 0
    30. ExecuteFirstEventAction = 0
    31. ShuffleCardsIntoLibraryAction = 0
    32. ShiftCardAction = 0
    33. RemoveCardAction (Robe of Mirrors) = 387
    34. MoveCardAction (Robe of Mirrors,OwnersHand,TopOfOwnersLibrary) = 0
    35. ShiftCardAction = 0
    36. RemoveCardAction (Rafiq of the Many) = 357
    37. MoveCardAction (Rafiq of the Many,OwnersHand,TopOfOwnersLibrary) = 0
    38. ShiftCardAction = 0
    39. RemoveCardAction (Sunpetal Grove) = 488
    40. MoveCardAction (Sunpetal Grove,OwnersHand,TopOfOwnersLibrary) = 0
    41. ShiftCardAction = 0
    42. RemoveCardAction (Sigiled Paladin) = 372
    43. MoveCardAction (Sigiled Paladin,OwnersHand,TopOfOwnersLibrary) = 0
    44. ShiftCardAction = 0
    45. RemoveCardAction (Rancor) = 450
    46. MoveCardAction (Rancor,OwnersHand,TopOfOwnersLibrary) = 0
    47. ShiftCardAction = 0
    48. RemoveCardAction (Nulltread Gargantuan) = 425
    49. MoveCardAction (Nulltread Gargantuan,OwnersHand,TopOfOwnersLibrary) = 0
    50. ShuffleLibraryAction = 0
    51. DrawAction = -2308
    52. AddEventAction (EVENT: NONE Computer may$ take a mulligan. ) = 0
    53. ExecuteFirstEventAction = 0
    54. AddEventAction (EVENT: NONE  Move this card from the top of the library to the bottom?) = 0
    Score = 524
    
    Exception from controller.runGame: 1
    java.lang.ArrayIndexOutOfBoundsException: 1
    	at magic.model.choice.MagicBuilderManaCost.compress(MagicBuilderManaCost.java:46)
    	at magic.model.MagicManaCost.addTo(MagicManaCost.java:316)
    	at magic.model.MagicManaCost.getBuilderCost(MagicManaCost.java:304)
    	at magic.model.condition.MagicManaCostCondition.accept(MagicManaCostCondition.java:23)
    	at magic.model.event.MagicPayManaCostEvent.isSatisfied(MagicPayManaCostEvent.java:38)
    	at magic.model.event.MagicActivation.canPlay(MagicActivation.java:108)
    	at magic.model.event.MagicSourceActivation.canPlay(MagicSourceActivation.java:26)
    	at magic.model.choice.MagicPlayChoice.addValidChoices(MagicPlayChoice.java:78)
    	at magic.model.choice.MagicPlayChoice.getArtificialOptions(MagicPlayChoice.java:68)
    	at magic.model.choice.MagicChoice.getArtificialChoiceResults(MagicChoice.java:86)
    	at magic.model.event.MagicEvent.getArtificialChoiceResults(MagicEvent.java:424)
    	at magic.ai.MCTSAI.getNextChoices(MCTSAI.java:513)
    	at magic.ai.MCTSAI.growTree(MCTSAI.java:354)
    	at magic.ai.MCTSAI.TreeUpdate(MCTSAI.java:239)
    	at magic.ai.MCTSAI$1.run(MCTSAI.java:146)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    	at java.lang.Thread.run(Unknown Source)

**Comment by melvinzhang** [comment]
Should be fixed by 2b677b0d543 that is in 1.70. Please reopen this or create a new issue if the same problem is encountered in 1.70.
