### ISSUE TITLE
token indicator on copied cards

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#66]
previously was issue 555...

> I like cards as Mirrorworks or Rite of Replication, which copy existing artifacts and/or creatures. Now, if you got some copies lying on the battlefield, it's easy to lose track of which of them are originals and which of them are tokens. \r\n\r\nA tiny small indicator, like, a white dot with a black T in it, would very helpful. _[Landhotel.Westerwald]_
> 
> > additional, there are cards that turn any permanent into artifacts. An indicator for that, like, a white dot with a black A in it, would be nice, too  _[Landhotel.Westerwald]_
> > 
> > > An indicator for token copies of permanents would make sense and shouldn't be too tricky it implement.\r\n\r\nThere are also cards that can change a cards: color, type, subtype, card text.\r\n\r\nPersonally I would prefer these changes to be displayed by different card frames. Only requiring cropped images to be downloaded, as the oracle text and card frames are built in-game.\r\n\r\nI'll get there at some point.\r\n\r\nI'm not sure if text mode gives an indicator for tokens - I do know it sometimes has extra information.\n\n  _[ShawnieBoyUK]_

**Comment by lodici** [comment]
See [forum example](http://www.slightlymagic.net/forum/viewtopic.php?f=82&t=3736&sid=77512908f3c77790e9d50c19ca9252f8&start=255#p173726) using Progenitor Mimic and Phantasmal Image.

Just indicating which original is a token is not enough, even though that would be useful (Text Mode actually does this using token.png . More importantly, there is no way to tell which Young Wolf is the Progenitor Mimic...

> a player need to know which one is the progenitor mimic, the owner might want to put shroud / other buff ability to protect, while opponent need to know which one to kill. [@hong yie]

Likewise with the fourth Young Wolf created using Phantasmal Image...
> While in phantasmal case, player might need to know that this token will be destroyed when targeted.

**Comment by melvinzhang** [comment]
merged into https://github.com/magarena/magarena/issues/719
