### ISSUE TITLE
'Up to' and Multi-targets

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#660]
We can currently search for 'up to' in a library, and I was looking about doing the same for the graveyard. The method isn't much different, and the AI thinking time should be the same, if not quicker as the graveyard is generally smaller than the library.

It was then that I realised that this was actually a multi-target, and many other spells/abilities involve up-to.

This could be a halfway-house for multi-target spells and abilities - What would be the issues in attempting this application?

**Comment by melvinzhang** [comment]
Single target is a fairly in-grained assumption, for example we use getTarget to retrieve the single target and getTargetChoiceResultIndex to find the position of the target in the Object[] choiceResult.

**Comment by ShawnieBoy** [comment]
Yes, thinking about this more - it's all to do with interactions. While in isolation returning multiple cards from a graveyard to hand appears like a search in a different location, things that can change the targets of a spell would cause lots of problems.

**Comment by melvinzhang** [comment]
Closing this as there are no further discussions.
