### ISSUE TITLE
Replace aura and enchantment icons (in stats viewer).

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#661]
![screenshot00448](https://cloud.githubusercontent.com/assets/2443519/12678523/1500df52-c697-11e5-8d1e-fbe7b26b6ada.png)

The red (aura) and blue (enchantment) gems currently used are not intuitive (to me anyway).

Ideally for all the icons I would like to use a simple black design in keeping with the minimalist look used elsewhere (eg. player zone buttons, action-bar icons, etc) but I have not been able to find suitably sized ones so far.

**Comment by ShawnieBoy** [comment]
I'll have a look - I might have some SVG ones which should scale well

**Comment by ShawnieBoy** [comment]
That is, the Futursight type icons

**Comment by lodici** [comment]
Thanks - any help would be very welcome.

**Comment by ShawnieBoy** [comment]
I've found them - would you want them in the same size are currently?

**Comment by lodici** [comment]
Yes, 16x16 I believe. The problem I have found at this size is that single color (ie. black) icons unless simple in design don't look that good. I think at smaller sizes the color helps to make icons more distinguishable.

**Comment by ShawnieBoy** [comment]
I think you can keep Enchantment and Aura together, as separating by subtype is a bit extreme - can then have Instant and Sorcery separate as they are different types

**Comment by ShawnieBoy** [comment]
Same could be said for Equipment and Artifact

**Comment by ShawnieBoy** [comment]
![new icons](https://cloud.githubusercontent.com/assets/2363180/12679857/55f6cff6-c69e-11e5-8278-2812fa1d5b8d.png)
Just replacing the ones which have a corresponding icon

**Comment by ShawnieBoy** [comment]
The layout would be the same if Planeswalker type is included as well 7 types:
Artifact
Creature
Enchantment
Instant
Land
Planeswalker
Sorcery
The 7 card types we use

**Comment by lodici** [comment]
That seems like a more logical list which I am assuming players will be more familiar with. If it also means we can use a standard set of mono-color icons even better. Also seems more consistent with the images used by proxies. I should probably look at the tiled decks screen and update the type icons there as well.
![screenshot00449](https://cloud.githubusercontent.com/assets/2443519/12680054/b4ee407e-c69f-11e5-9b11-bf13c8ba3f84.png)

**Comment by ShawnieBoy** [comment]
I can supply a white version for those sizes as well

**Comment by lodici** [comment]
That would be useful, thanks.

**Comment by ShawnieBoy** [comment]
What size are they rendered at, as they seem to be different sizes. 26x26 -> 30x30

**Comment by lodici** [comment]
Go for 30x30.

**Comment by ShawnieBoy** [comment]
![icon panel](https://cloud.githubusercontent.com/assets/2363180/12680419/9f3e5bea-c6a1-11e5-9d27-7dee22b03807.png)

Looks good to me

**Comment by lodici** [comment]
> Artifact
> Creature
> Enchantment
> Instant
> Land
> Planeswalker
> Sorcery

should this be the order in which the stats are presented?

**Comment by lodici** [comment]
the new tiled decks screen icons look great.

**Comment by ShawnieBoy** [comment]
That's just alphabetical - I'd probably go with a 'most likely' distribution:
Land
Creature
then it goes a bit iffy, uhm...
Artifact
Instant
Sorcery
Enchantment
Planeswalker

**Comment by ShawnieBoy** [comment]
Planeswalker last at least, I'd guess

**Comment by ShawnieBoy** [comment]
Maybe Artifact then Enchantment as they both have multiple subtypes

**Comment by ShawnieBoy** [comment]
By the way, how does the Deck Stat panel handle multiple types? Add them to both categories?
eg. Artifact Land, Enchantment Creatures

**Comment by lodici** [comment]
Do you want to look at this since you are more knowledgable about this stuff? The ``CardTypeStatsPanel`` is used to display the stats and it gets all its info from ``CardStatistics``. Fairly simple and self-contained.

**Comment by ShawnieBoy** [comment]
Sure, no problem

**Comment by ShawnieBoy** [comment]
![new icons panel](https://cloud.githubusercontent.com/assets/2363180/12681335/0b0a6676-c6a6-11e5-839f-b8a5045eb30b.png)

Here's the new look.
I'll probably have a bit more of a fiddle with the statistics, I feel as though multiple types should be represented in each type. As an example of strange things that can happen, here's a purely Artifact Deck:

![artifactless](https://cloud.githubusercontent.com/assets/2363180/12681404/65514000-c6a6-11e5-9922-e3b23ff5da47.png)

As all the creatures and all the lands are also artifacts, the artifact count is 0.

**Comment by lodici** [comment]
Very nice! :+1:

**Comment by ShawnieBoy** [comment]
Also as a side-effect, the icons that appear when casting have also been changed to match.
