### ISSUE TITLE
Add new Type icons in tiled deck screen

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#662]
Extending the implementation of the new type icons.

Two things I've noticed:

This area uses translation strings which I've not had to deal with before, is it fair to continue the numbers in increasing value or is there a master-list in case other string use those numbers.

Filtering by type when it comes to permanents with multiple types is excluding creatures and lands from artifacts. I'd lean towards displaying all cards of a chosen type (eg. Is an Enchantment Artifact displayed as an artifact or an enchantment? It's both)

- [X] Display filter buttons only for types that appear in the deck

**Comment by ShawnieBoy** [comment]
![tiled panel](https://cloud.githubusercontent.com/assets/2363180/12683608/0c26ca52-c6b2-11e5-9a98-39a1909d92f4.png)

**Comment by lodici** [comment]
Awesome.

> This area uses translation strings which I've not had to deal with before, is it fair to continue the numbers in increasing value or is there a master-list in case other string use those numbers.

If you mean the ``_S`` strings then they just have to be unique. I usually just continue from the last number. But if you want to fill in any gaps that is fine as well.

**Comment by ShawnieBoy** [comment]
>If you mean the _S strings then they just have to be unique. I usually just continue from the last number. But if you want to fill in any gaps that is fine as well.

I see, they are only unique in regards to the class they are in. Was worried they were unique throughout the project.

Also noticed the percentage calculation between the statistics panel and the tiled view header must be done differently as the values aren't matching up.

**Comment by lodici** [comment]
> I see, they are only unique in regards to the class they are in.

correct.

> Also noticed the percentage calculation between the statistics panel and the tiled view header must be done differently as the values aren't matching up.

and also correct. Probably a rounding difference.

**Comment by ShawnieBoy** [comment]
![totals](https://cloud.githubusercontent.com/assets/2363180/12683795/3256a426-c6b3-11e5-9e9d-561947d5b3c7.png)

Just a rounding issue I expect, header says 16 cards = 26% Panel says 16 cards = 27%

**Comment by ShawnieBoy** [comment]
Snap, hehe

**Comment by lodici** [comment]
I would add that the % in the stats viewer does not always add up to 100%.

**Comment by ShawnieBoy** [comment]
No, there would be overlap with types.

**Comment by lodici** [comment]
A tad confusing but ok. Out of interest when learning MTG a common guidance is that your deck should ideally contain X% of land cards, Y% of other cards. Does the percentage displayed help in this respect?

**Comment by ShawnieBoy** [comment]
The land percentage should cover the rough 33% - As long as the land amount is right, then the rest will be too

**Comment by ShawnieBoy** [comment]
Would be nice to be able to only show the filter buttons if cards of that type actually appear in the deck

**Comment by lodici** [comment]
> Would be nice to be able to only show the filter buttons if cards of that type actually appear in the deck

Having run it I am not entirely convinced this is the way to go. I thing it brings up a usability issue and am wondering whether it is too fine-grained for displaying cards. The reason I went for the initial 3 categories - lands, creatures, anything else - is because it seems to be quite a common categorization on deck-related websites. It is a quick way of viewing cards using the most important categorizations. Sometimes just because we can doesn't mean we should.

**Comment by lodici** [comment]
A more intuitive approach might be to make each card type stat panel act like a toggle button which you can click on to filter the deck displayed in the right-hand pane - it would work on both text list and images. Something to consider for 1.71 possibly.

**Comment by ShawnieBoy** [comment]
Good point - The Lands, creatures, spells trio is used more often. For hand filtering it would make more sense.

The card types panel with the statistics would fit ok as it is, when looking at mana curve and more detailed analysis

**Comment by ShawnieBoy** [comment]
Well, I've already completed the filter of the filters, so I'll push it to see if that makes things look better.

**Comment by lodici** [comment]
> Well, I've already completed the filter of the filters, so I'll push it to see if that makes things look better.

That definitely helps and prevents any irritation on clicking an empty type. Its affected the action-bar layout with the sample hand button but I will sort that out.
