### ISSUE TITLE
Anyone having issues downloading images?

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#667]
I am currently getting fails when using the download dialog. However if I enter the image url in my browser the image is displayed ok.

**Comment by ShawnieBoy** [comment]
I'll have a try, I've not updated for a while

**Comment by ShawnieBoy** [comment]
Unexpected end of file errors? That's strange

**Comment by ShawnieBoy** [comment]
Hopefully this is a server error and not a refusal to download card images from the server...

**Comment by lodici** [comment]
Hopefully. If they are restricting non-browser access it might be because of end-of-month overload - all these pesky opensource apps releasing new versions.

**Comment by lodici** [comment]
Thankfully, it is not a complete showstopper because we now have the missing image proxies. Would perhaps hold the next release though. It was not working last night either so it has been like this for the last 12 hours or so.

**Comment by ShawnieBoy** [comment]
I did notice last night that the images weren't even showing in-browser - so there could be other problems on their end.

**Comment by lodici** [comment]
Oh, that's good to know.

**Comment by lodici** [comment]
Yay! Looks like it was a server issue - just tried again and all downloaded ok.

**Comment by lodici** [comment]
Back down again, :disappointed:

**Comment by lodici** [comment]
Strange - downloads when running from IDE but running as release (Magarena.exe) fails. Must be something like a firewall issue but as yet unable to confirm cause.
