### ISSUE TITLE
Filtering/highlighting cards in a zone or on battlefield.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#672]
One of features of the now defunct TextMode was an ability to filter cards in a zone -

```
private static final ImageIcon[] FILTER_ICONS={
    MagicImages.getIcon(MagicIcon.ALL),
    MagicImages.getIcon(MagicIcon.LAND),
    MagicImages.getIcon(MagicIcon.CREATURE),
    MagicImages.getIcon(MagicIcon.ARTIFACT),
    MagicImages.getIcon(MagicIcon.ENCHANTMENT),
    MagicImages.getIcon(MagicIcon.VALID)};
...
...
switch (filter) {
    case 1: return permanentInfo.mana;
    case 2: return permanentInfo.creature;
    case 3: return permanentInfo.artifact;
    case 4: return permanentInfo.enchantment;
    case 5: return controller.getValidChoices().contains(permanentInfo.permanent);
    default: return permanentInfo.root;
}
```

Would something similar be useful for image mode? I guess being able to temporarily simplify a busy and confusing battlefield of small card images might be useful.

**Comment by ShawnieBoy** [comment]
Hmm, not sure - Could imagine leaving a filter on and not realising, especially if there's not many of that type (or none) on the battlefield.

**Comment by ShawnieBoy** [comment]
I'm wondering if it's there due to Text-mode not scaling the cards

**Comment by lodici** [comment]
> Hmm, not sure - Could imagine leaving a filter on and not realising, especially if there's not many of that type (or none) on the battlefield.

It is probably not a relevant use-case in image mode but having deleted all the code from PermanentFilter I thought I would bring it up just in case.
