### ISSUE TITLE
Returning Spine of Ish Sah to hand puts it into graveyard

### ISSUE THREAD

**Issue by tahti** [magarena/magarena#673]
When I used Master Transmuter ability on Spine of Ish Sah to return it to hand, it was put into graveyard. I guess it is an issue with double toggle as Spine of Ish Sah cannot be put into graveyard.

**Comment by melvinzhang** [comment]
I'm unable to replicate this. When I activate Master Transmuter's ability, I'm able to return Spine of Ish Sah to hand as part of the cost, and put Spine of Ish Sah onto the battlefield as part of the effect of the ability.

@tahti were there other cards on the battlefield that may affect cards leaving the battlefield? In your case, when you tried to return Spine to hand, it did not go to hand but when to the graveyard instead, is that what happened?

**Comment by ShawnieBoy** [comment]
I was definitely able to replicate this one!

**Comment by ShawnieBoy** [comment]
For me, it never went to the hand, just straight to the graveyard.
I'm wondering if something else has fixed this since being reported?

**Comment by melvinzhang** [comment]
@ShawnieBoy Are you able to replicate now?

**Comment by ShawnieBoy** [comment]
Nope - looks fixed now

**Comment by melvinzhang** [comment]
Thanks for the confirmation. Considering it closed then.
