### ISSUE TITLE
Converted Mana Cost doesn't count Multiple X's

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#677]
Raised on [Forums](http://www.slightlymagic.net/forum/viewtopic.php?f=82&t=17988&p=192357#p192321)

X is only calculated once - incorrect totals for cards with multiple X

**Comment by melvinzhang** [comment]
@ShawnieBoy were you able to replicate this? I tried and could not replicate, I'm able to counter Hangarback Walker cast for X=2 with Disdainful Stroke.

**Comment by ShawnieBoy** [comment]
No, I also realise an error now, I was looking at the converted cost of permanent which doesn't take into account multiple X as X is always 0. Should have looked at MagicCard.

**Comment by ShawnieBoy** [comment]
Thinking about it, I must have been able to duplicate, otherwise I'd have asked for more info. I'm wondering more if something has fixed this since being raised.

**Comment by ShawnieBoy** [comment]
MagicStackGetChoicesEvent?

**Comment by melvinzhang** [comment]
Does it mean you can't replicate now? It would be helpful to commit a test game/test class when you are able to replicate so we don't duplicate efforts in trying to replicate an issue.

**Comment by ShawnieBoy** [comment]
No I can't replicate now - best way would be to test under 1.70 release

**Comment by melvinzhang** [comment]
Considering it done then.
