### ISSUE TITLE
Images not downloading in Windows

### ISSUE THREAD

**Issue by arcashaid** [magarena/magarena#679]
What should I do ? 

https://fbcdn-sphotos-c-a.akamaihd.net/hphotos-ak-xat1/v/t1.0-9/12647524_1746925675540641_4489735074548615688_n.jpg?oh=9e81711c23c83723d1209cd314218b9d&oe=572673D7&__gda__=1467046879_2b908531e816e2ee2d87821bec9da46a

**Comment by lodici** [comment]
This is a temporary workaround for Windows until 1.70 is released.

1. Open the Magarena installation folder.
2. Create a shortcut to the Magarena.jar file **in the same folder**.
3. Right-click shortcut and select Properties.
4. Replace the Target field with following text -
```
javaw.exe -Dhttp.agent="Magarena" -Xms256M -Xmx512M -noverify -jar Magarena.jar
```
5. run Magarena using the shortcut and image download should work.

**Comment by arcashaid** [comment]
error message "The specified path does not exist "

**Comment by lodici** [comment]
Try creating a new text file, enter the line above and save as ''Magarena.cmd''.

**Comment by arcashaid** [comment]
nothing yet, just open and close the pront , but does not start the program

**Comment by lodici** [comment]
1. Open the command prompt - WIN-r -> cmd
2. change to the directory containing ``Magarena.jar``.
3. ``java.exe -Dhttp.agent="Magarena" -Xms256M -Xmx512M -noverify -jar Magarena.jar``

Any errors please copy and paste here.

**Comment by arcashaid** [comment]
I do not know how to change the directory , I'm giving up

**Comment by ShawnieBoy** [comment]
:cry: The new version containing the fix should be released this weekend

**Comment by arcashaid** [comment]
is to download a rar file with the cards you miss and put manually?

**Comment by melvinzhang** [comment]
Please upgrade to 1.70, https://github.com/magarena/magarena/releases/tag/1.70 It includes the fix to this problem.
