### ISSUE TITLE
1.70 release is not complete.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#681]
@melvinzhang , something has not worked with the latest release. The [website](https://magarena.github.io/) page is still showing 1.69 and the new release alert is not being triggered. Is it a GitHub issue?

I took a look at https://github.com/magarena/magarena.github.io but could not see any obvious differences from previous releases. There is no related CiCircle build and the last build failed - could that be it?

**Comment by melvinzhang** [comment]
Yes, Github updated jekyll (the static site builder) to 3.0. Our current version is not building as it is using some things that have been removed. I'm working on it.

**Comment by melvinzhang** [comment]
Recent commits to the site makes it compatible with Jekyll 3.

**Comment by lodici** [comment]
Thanks - took at look at your fixes, but this jekyll stuff is all a bit black art to me. No way I would have worked out the problem that's for sure.

**Comment by melvinzhang** [comment]
To github's credit they do send a rather helpful email each time the build of the site fails and suggest how to fix it. Only problem was I wasn't actively checking my mail and didn't notice the first failure until a while ago.
