### ISSUE TITLE
Static initializer gotcha?

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#684]
This is really weird but I just noticed that the Magarena caption is missing the "[DEV MODE]" suffix if ``-DdevMode=true``. The reason it is not displayed is because of the static initializer that was recently introduced by 2908480ff1f67bb614ca96a7c8a72b1e7a4a7a55 (sets the ``http.agent`` to fix image downloading). 

For some reason if it comes before the setting of ``IS_DEV_MODE`` then ``IS_DEV_MODE`` returns false the first time it is accessed. However, by the time the Main Menu screen is opened it is returning true as expected since dev-mode only options for loading game and test files are shown.

Moving the static initializer after the setting of ``IS_DEV_MODE`` and it behaves as expected. I don't understand why though! :confused:

**Comment by lodici** [comment]
Sussed! It is because of the ordering of the statics. The ``MagicFileSystem`` static initializer which sets ``http.agent`` calls `` GeneralConfig.SOFTWARE_TITLE`` which in turn calls ``MagicFileSystem.IS_DEV_MODE`` which comes after the first static initializer and so will not yet have been set because it has to wait for the first static initializer to finish! In short it is a mess.

**Comment by ShawnieBoy** [comment]
:+1: hehe
