### ISSUE TITLE
Unable to isolate text layers in splash.psd.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#687]
@ShawnieBoy when I open ``resources\magic\data\_excluded\splash.psd`` in gimp or paint.net I get
![screenshot00457](https://cloud.githubusercontent.com/assets/2443519/12930248/10c3e8b8-cf6f-11e5-8b71-16e89a235116.png)
I can see and edit all the layers but I am unable to isolate just the text like the following (but without the background)
![screenshot00456](https://cloud.githubusercontent.com/assets/2443519/12930189/b77ce9f8-cf6e-11e5-8501-6dcc88af3bfb.png)
Any ideas on what I am doing wrong?

**Comment by ShawnieBoy** [comment]
That would probably be to do with installed fonts and gimp, along with photoshop effects - I'll have a look using gimp

**Comment by ShawnieBoy** [comment]
The text is there, it's just in photoshop, clipping masks are used to put the texture in the text - looks like another method would need to be used in gimp

**Comment by ShawnieBoy** [comment]
Hiding the textures above the text will show the 'Magarena' but without the texture and outline applied in photoshop styles and clipping

**Comment by ShawnieBoy** [comment]
I'll go through and apply any styles and clipping so they're not photoshop dependant

**Comment by lodici** [comment]
Thanks - if it is easier then the splash screen with a transparent background would be fine.

**Comment by ShawnieBoy** [comment]
Would that be without the Vignetting as well?

**Comment by ShawnieBoy** [comment]
![splash](https://cloud.githubusercontent.com/assets/2363180/12932146/3feebf28-cf79-11e5-9fbb-1660819e8bd7.png)
![splash2](https://cloud.githubusercontent.com/assets/2363180/12932150/41aaa46c-cf79-11e5-8c21-ff4bb6052632.png)
One with and one without :smile:

**Comment by lodici** [comment]
No need for vinegar, the first image above is perfect. Thanks.

**Comment by ShawnieBoy** [comment]
hahaha :+1:
