### ISSUE TITLE
Tarmogoyf should not be killed by lightning bolt that adds to its toughness

### ISSUE THREAD

**Issue by Muppet1** [magarena/magarena#688]
when you try to kill  a 2/3 goyf with a lightning bolt with no instant in the gy it shd not die the card you are casting shd count as being in the gy by the time it takes damage.

Currently the goyf dies.

**Comment by ShawnieBoy** [comment]
Yes, it should survive - state based effects should be checked when a player would get priority. The lightning bolt should be in the graveyard by then.

@melvinzhang ?

**Comment by melvinzhang** [comment]
@Muppet1 do you have a gameplay report for this issue? Do save a gameplay report and submit it together with the issue. It will help us replicate the problem and test that it is fixed properly.

**Comment by Muppet1** [comment]
no sorry will save one next time it happens.
basically you need a kill card that does exactly the damage a goyf has toughness with none of that type of card in any gy at the time of casting. 

    On Wednesday, 10 February 2016, 1:22, Melvin Zhang <notifications@github.com> wrote:
 

 @Muppet1 do you have a gameplay report for this issue? Do save a gameplay report and submit it together with the issue. It will help us replicate the problem and test that it is fixed properly.—

**Comment by melvinzhang** [comment]
This is fixed by other changes made since this was created. Tested by running TestTarmogoyf.
