### ISSUE TITLE
game.log not cleared.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#69]
Start a game, Quit to main menu, resume duel, start game  - previous log entries still present in ``game.log``. UI log seems to be ok though. Replicated in 1.58 and 1.57.

**Comment by melvinzhang** [comment]
Currently the log is cleared when the program starts up, in initializeEngine. Wouldn't it be easier for someone to report bugs if logs are kept on a per session basis instead of per duel? The user might finish a few duels, then want to report a bug and post the log.

**Comment by lodici** [comment]
Since your the one who I imagine makes most use of the log then I think you should have the final decision. I should point out that this update clears the log (only when played via the UI) _every game_.

**Comment by melvinzhang** [comment]
Decided to have the game log be cleared on a per session basis to support bug reporting.
