### ISSUE TITLE
Make color distribution stats panel fixed height.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#692]
Currently it only show the colors in the deck which means it has a variable height based on the number of colors found. On smaller screens, especially in the deck selector screen this is very distracting. If the color distribution were a fixed height then this would alleviate the problem and make layout easier as well, eg. (very rough idea)
![screenshot00469](https://cloud.githubusercontent.com/assets/2443519/13053939/ff32cfd0-d3fe-11e5-80b4-8492c853a84b.png)

**Comment by lodici** [comment]
Same info (plus color distribution for all types) but in a fixed and more compact format. Tooltips on headings.
![screenshot00472](https://cloud.githubusercontent.com/assets/2443519/13076426/1f766cce-d4aa-11e5-8fe8-0475ba5c0d03.png)

**Comment by ShawnieBoy** [comment]
Really nice :+1: 
Maybe some icons to help with the colorless/mono/multi headings? (Thank you tooltips :grinning:)

**Comment by ShawnieBoy** [comment]
Well, we have colorless already ![c](https://cloud.githubusercontent.com/assets/2363180/13082828/3763771c-d4ca-11e5-91ae-ac322f2636e1.png)

**Comment by lodici** [comment]
Thanks, I will add the colorless icon in place of "=0". I had no idea what to use for mono and multi so any suggestions welcome.

**Comment by ShawnieBoy** [comment]
The rainbow for anymana could work for multicolor - I'm stuck with mono though
