### ISSUE TITLE
"Choose the mode" prompt does not display all options.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#700]
I think it is if there are more than two choices available -
[TestChoice.game.txt](https://github.com/magarena/magarena/files/137064/TestChoice.game.txt)
![screenshot00485](https://cloud.githubusercontent.com/assets/2443519/13160360/cd1d7ec2-d68e-11e5-9bdf-3f9f152c0414.png)

**Comment by lodici** [comment]
Also, "Please choose an option - " is friendlier and seems less jargony (what the heck is a "mode"?).

**Comment by ShawnieBoy** [comment]
I agree with the 'option' preference - the reason the third option isn't showing is that both targets are illegal (Both have prot white).

**Comment by lodici** [comment]
Thanks for the explanation, although I think Magarena could be more helpful in this case (see #702).

**Comment by lodici** [comment]
@ShawnieBoy can you suggest a card that will trigger the  "Choose which ability to play." prompt (PlayChoicePanel), preferably with as many ability choices as possible. Thanks.

**Comment by ShawnieBoy** [comment]
Morphling springs to mind - 5 abilities
If you're trying to push the amount of activated abilities I can try and come up with a scenario

**Comment by lodici** [comment]
Thanks, works perfect.
