### ISSUE TITLE
Ability icons regression due to ImageDrawingUtils refactoring.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#704]
Somewhere between the release of 1.68 and 1.69, possibly related to the move to CardBuilder the default ability color icons as displayed on the battlefield card image have been changed to use the custom icons designed for the popup image (not suited in size or style for display at 16x16).
**1.68**
![screenshot00486](https://cloud.githubusercontent.com/assets/2443519/13177388/afddd94c-d710-11e5-8bba-c6bd324d09e5.png)
**1.69**
![screenshot00487](https://cloud.githubusercontent.com/assets/2443519/13177396/bd0635ec-d710-11e5-8393-25cb4594304f.png)

**Comment by ShawnieBoy** [comment]
Which screen is this from? I'm getting this.

![2016-02-19_140654](https://cloud.githubusercontent.com/assets/2363180/13177598/1618304e-d712-11e5-9222-9ea47cff571d.png)

**Comment by lodici** [comment]
It requires the [SkyBlue theme](http://www.slightlymagic.net/forum/viewtopic.php?f=89&t=15039).

**Comment by ShawnieBoy** [comment]
Oh I see, custom Icons - Cardbuilder doesn't get involved with the ability overlay - I'm assuming custom icons are overwriting all ability icons. (I can't see any ability.small, ability.large versions of the ability icons)

**Comment by ShawnieBoy** [comment]
Here's a messy example without cardbuilder involved

![2016-02-19_141858](https://cloud.githubusercontent.com/assets/2363180/13177897/db860f62-d713-11e5-9c46-c0227cc0b854.png)

**Comment by lodici** [comment]
I think it is due to changes made to ImageDrawingUtils in the same month. So not CardBuilder. And relax! :smiling_imp:

**Comment by lodici** [comment]
culprit = 6bc8075b2857d9b88690608d40c691dab7e6d95
