### ISSUE TITLE
Creatures that are removed from combat, but then blocked still appear in combat

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#707]
Ok, this is a strange scenario anyway, but Magarena makes it stranger.

Player attacks with Creature-A, owned by the AI, but enchanted with Illusory Gains.
The AI blocks with Ætherplasm.
The AI chooses to return Ætherplasm to its hand.
The AI plays Creature-B blocking Creature-A.
 - now the tricky part.
The Illusory Gains attaches to Creature-B.
This returns Creature-A to the AI's control and puts Creature-B under the Players control.

As control has changed, both should be removed from combat, but both still appear in the centre of the 'battle area', only in swapped positions, so that the attacker becomes the blocker (and vice versa).

No combat damage is dealt (thankfully) as they're not in combat anymore.

Is this due to the creature coming into play blocking? Brimaz, King of Oreskos does something similar, but with tokens. Or does removal from combat from control change not get to the UI?

**Comment by melvinzhang** [comment]
Is it possible to create a test game for this?

**Comment by melvinzhang** [comment]
Btw I noticed Ætherplasm seems to be missing a RemoveCardAction before the PlayCardAction so the card will stay in hand. ReturnCardAction automatically does a remove first, so perhaps that should be used instead.

**Comment by melvinzhang** [comment]
Without a test game, I would guess the problem is they were removed from combat due to control change and then later put back into combat due to SetBlockers action from Ætherplasm.

**Comment by melvinzhang** [comment]
On second thoughts that shouldn't be possible because Ætherplasm's SetBlockerAction would occur before Illusory Gains' trigger resolves.

**Comment by ShawnieBoy** [comment]
No longer seems to be the case - Thanks for the edit too :smile: 

TestGame doesn't recreate the above but does strangely give the newly enchanted creature summoning sickness.
