### ISSUE TITLE
Identify target of ability cast by opponent.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#71]
From @muppet in [forum post](http://www.slightlymagic.net/forum/viewtopic.php?f=82&t=3736&sid=77512908f3c77790e9d50c19ca9252f8&start=255#p173639)...

> I sometimes have trouble determining the target of an ability cast by the opponent. For example I have 10 soldier tokens in play opponent casts Maelstrom Pulse, I need to know which one is targeted so I can kill it with a Doom Blade to fizzle the pulse.

**Comment by melvinzhang** [comment]
Idea 1: Draw an arrow from stack item to permanent
See https://github.com/magefree/mage/blob/e20a5f68e68cde5e360d057c671125a9f7e8fa67/Mage.Client/src/main/java/mage/client/util/gui/ArrowBuilder.java for an example implementation

Idea 2: Highlight permanent when mouse hover over stack item

**Comment by lodici** [comment]
Since the code is already there for valid choices I would go with the highlight. Perhaps also flash the permanent two or three times initially. However, this would also affect the current behaviour which is to show the source card image when mousing over the stack item. Arrows would be useful for linking cards on the battlefield.

**Comment by ShawnieBoy** [comment]
I think the arrows would be useful in a situation like shown in https://github.com/magarena/magarena/issues/157#issuecomment-89654471

With he prompt 'Move a +1/+1' counter displaying an arrow representing a 'from' and 'to' - This would be different from an arrow from the stack to the permanent, but instead from a permanent to a permanent.

Could also be implemented for blocking assignment, which may(?) make creatures that can block multiple attackers easier to represent (Although not code!)

**Comment by melvinzhang** [comment]
Card that is targeted has highlight.
