### ISSUE TITLE
Frost Walker not being sacrificed

### ISSUE THREAD

**Issue by yaywalter** [magarena/magarena#716]
Targeting the AI's Frost Walker with the triggered Landfall ability of Retreat to Valakut should force the AI to sacrifice it, but doesn't.

Would test to see if it's repeatable, but Magarena appears to not have any way of allowing the use of illegal decks... *hint hint*

**Comment by ShawnieBoy** [comment]
The issue with targets determined by a choice has been fixed for the next release.

There's a couple of ways to put together tests. A Game report from the game menu is essentially a list of cards/permanents in each zone for the player and opponent (although no attached permanents) - These can be loaded while in dev-mode.

There's also test classes that can be created which do a similar thing to be launched in dev-mode.

Have a look at the Wiki - [Testing and Debugging](https://github.com/magarena/magarena/wiki/TestingAndDebugging) And maybe the whole Dev Guide if you're interested - always happy to have more bug-hunters! :grinning:
