### ISSUE TITLE
discarding large hand down to 7 causes out of memory error

### ISSUE THREAD

**Issue by Muppet1** [magarena/magarena#721]
a few times 1.70 crashed and a few of those involved reanimation I think.

here is a log from 1.71 where it crashed just after putting Sphynx of the Steel Wind into play with Exhume.
it isn't just me I think firemind has occasional crashes with this reanimator deck.  They have worked ok in the past though I think but not sure this exact creature was in it.
[crash.txt](https://github.com/magarena/magarena/files/170351/crash.txt)

**Comment by lodici** [comment]
Possibly related to #717 which also has issues with the choice classes and lack of memory.

**Comment by Muppet1** [comment]
Ok this is fairly common play a few games with the deck below and it will crash.   Can't tell exactly which card is causing it and not had any crash with any other deck i'll add them if I do.
[leg reanimator.txt](https://github.com/magarena/magarena/files/177810/leg.reanimator.txt)
this is a .dec file I renamed it txt to allow me to post it.

**Comment by lodici** [comment]
Please don't forget there is a gameplay report option which you can access from the game menu (hit the Escape key). This creates a zip file which you can drag directly into a GitHub comments box and which contains all sorts of useful data to help replicate an issue. Likewise, if you are getting an crash please consider posting the ``crash.log`` file. Thanks.

**Comment by melvinzhang** [comment]
The culprit seems to be Griselbrand, his ability could generate a large hand leading to discard of many cards which slows things down.

**Comment by melvinzhang** [comment]
other cards that could lead to a large hand include: Swans of Bryn Argo, Stroke of Genius, and Enter the Infinite

**Comment by melvinzhang** [comment]
break the discard into several steps instead of doing it all one shot, as the number of combinations may be too large.

**Comment by melvinzhang** [comment]
The fix to discard in groups of 3, the leg reanimator.txt deck above is able to play without crashing. Tested on mirror match with both players using the deck.
