### ISSUE TITLE
fetch lands and the AI not a bug.

### ISSUE THREAD

**Issue by Muppet1** [magarena/magarena#726]
1. AI has Scalding Tarn and Mox  Ruby in play.  If in its first main phase it uses the land to fetch another land into play it does not recalculate and simply moves into declare attackers.

It has other valid plays at this point but nothing appears in the game log.   It is reproducible if I take it back it always skips.  So it looks like this action needs to be added to whatever triggers the AI to have another think before moving to the next phase.
MCTS  level 8.

Hopefully this explains why the AI is in general bad with fetch lands.  If I see  similar  things with fetch lands I will add them here.
1. Ok I found another of these which is after using Jace the MIndsculptor it did not think about any options just auto passed.  I'll keep checking for these and adding them
2. AI has Misty Forest in play second main phase.  AI plays Forest then doesn't rethink about what to do it just auto passes.  It has things in hand ready to cast if it uses the fetch land which was a close second option to playing the forest.    But maybe it didn't realise it was going to auto pass if it played the forest.

**Comment by melvinzhang** [comment]
Hard to reproduce without the gameplay report. Do include the report when something similar happens.
