### ISSUE TITLE
Download card images failure

### ISSUE THREAD

**Issue by slartifer** [magarena/magarena#729]
Not sure if this is a bug, but I have tried to rule out other possible causes and this looks like the preferred place to post issues.

'Download card images' has been behaving strangely for me (new user, magarena 1.70).  When I use it, it will rapidly download some images correctly, interspersed with error 503's, e.g.:

java.io.IOException: Server returned HTTP response code: 503 for URL: http://magiccards.info/scans/en/tsts/55.jpg [Avalanche Riders.jpg]

After about 200 correct downloads and 100 error 503's, it will then switch to slowly timing out, e.g.:

java.net.SocketTimeoutException: connect timed out [Black Oak of Odunos.jpg]

Additionally, at that point, magiccards.info (which previously responded to all requests from me) will time out on all requests for a period of time I haven't been able to determine (maybe 24 hours?).  After that time passes, I can restart the whole thing and get another 200 or so correct downloads.

The surprising thing is that I *can* access those exact addresses via HTTP without an error 503 (or any other problem), in a web browser.  (Through a proxy, currently, as I'm getting timed out again.)

I have gotten the same behavior on multiple computers, on my home and work networks, with antivirus software disabled, etc., and traceroute turns up no other problems.  My guess is that magiccards.info is blacklisting my IP because of all the rapid error 503's.  Not sure what's causing those but it doesn't seem to be the URL, at least.  Full errors from last session below.

[example errors.txt](https://github.com/magarena/magarena/files/176780/example.errors.txt)

**Comment by ShawnieBoy** [comment]
Sorry to hear you're having download problems.
There had been a few issues with the downloading of images from magiccards.info which had been fixed for the 1.70 release - it looks as though the server settings may have been adjusted again.

The 503 errors made me think that magiccards may had been down/having maintenance, but being able to access them through a browser runs counter to that.

@lodici is the downloads-man, it looks like the method needs to be fine tuned - it could be that each card image request is being made as a separate connection and causing the server to block further requests. It may be possible to make one connection and then download instead.

Hopefully the card proxies will aid in playing in the mean-time.

**Comment by ShawnieBoy** [comment]
The [HQ pics forum](http://www.slightlymagic.net/forum/viewtopic.php?f=15&t=12336) has links to the torrents and resources for crops and full images as well as the three Mega collections as well:

[CCGHQ Releases](https://goo.gl/6qlF9Y)
[CCGHQ More Releases](https://goo.gl/Jzy3k0)
[CCGHQ Missing Promos List](http://updates.mtgapps.com/missingpromos.html)

However these will most likely require name editing for the '.full.' etc of the file endings, if you have a bulk-renamer. Magarena uses the card names as printed (accents included) ending in just '.jpg' for both crops and full images.

**Comment by lodici** [comment]
@slartifer, recently ``magiccards.info`` appeared to block anonymous java apps from downloading images (see #667, #676). So Magarena was updated to include its name and version in the request header which seemed to fix the problem. I guess it is possible that they might have targeted Magarena since then but I would have expected more complaints. From what you describe it does sound similar to the problems we were experiencing in the issues mentioned so perhaps they are restricting the IP address perhaps in conjunction with access via Magarena. You mention using a proxy, have you tried downloading images using that? If it works then that would suggest there is some IP blacklisting going on with your default, non-proxied address. If not, then it could be a temporary issue with the server or worst case scenario, they are restricting access specifically to Magarena.

**Comment by slartifer** [comment]
Thanks @ShawnieBoy and @lodici for the helpful replies and the links.

I tried again tonight and it worked fine, this time, for about 1000 card images, including the cards that previously produced error 503's.  Then the error 503's hit.  I did notice, this time, that there were **exactly** 100 instances of error 503 before it switched to timing out.  That is consistent with what happened previously, and the round number sure smells like it is an IP-specific response.

Re proxies, I was just using a web-based proxy before.  I don't have a functional server handy to test via magarena's settings, unfortunately.

I did see some of the previous issues before posting and was also surprised no one else was sharing this problem currently -- hence all the checking I did to make sure it wasn't on my end.  Given that I've consistently been able to download 200 images at a time, though, it seems likely that this would primarily affect new users who are trying to download the entire bank, rather than an update or two; that could be part of why it hasn't come up.

**Comment by slartifer** [comment]
Further update: if I pay close attention and stop the download process as soon as the first error 503's appear, then wait a few moments and restart it, I once again can get a good chunk of downloads without hitting error 503's.  I can do this repeatedly.  I have just done it about 100 times and never got to the point of timeouts or blacklisting even though I'm sure the cumulative number of error 503's I've had is well over 100.

This smells like an issue with the server responding either to rapidity of connections or maybe number of simultaneous connections.  It might be adequately resolved simply by automatically pausing for 5-10 seconds every time an error 503 is received.

**Comment by lodici** [comment]
Thanks for the additional info. It only downloads one image at a time but otherwise downloads as fast the server will allow. The auto pause is a good idea.

**Comment by lodici** [comment]
I have done some tests. When 1.71 is released I make it that there will be 324 new playable images to download and 186 missing images. When I download both sets at the same time I invariably get a number of 503 errors. When I downloaded the sets one after the other, all images downloaded with no errors.

So it would seem that having two connections open at the same time, one for playable images and one for missing images is at least one possible cause of the problem. @slartifer please can you confirm whether you are downloading both sets of images at once? It looks like it might be wise to prevent more than one connection at a time.

**Comment by slartifer** [comment]
I'm not sure what the distinction is between new versus missing images?  I had just been using the "Download card images" box and hit "Download" to the right of "Playable = n" where as a new user, n was originally over 10,000.  (I did not ever attempt to download cropped images at the same time, just card images, if that's what you mean?)

**Comment by lodici** [comment]
Sorry, I meant "unimplemented" as in
![screenshot00504](https://cloud.githubusercontent.com/assets/2443519/14051133/86177848-f2b8-11e5-9341-ffd151092484.png)

**Comment by slartifer** [comment]
Ahh... nope, I left Unimplemented alone.

**Comment by slartifer** [comment]
(I have "show missing card data" unchecked, which actually seems to default to displaying "Unimplemented = 0" if it has been unchecked since Magarena last started up, so I never even had that option.)

**Comment by lodici** [comment]
Ok, thanks. Looks likes some sort of cool-down will also be required. Sorry for the confusion, due to historical reasons we use "missing" and "unimplemented" to refer to cards that are as yet unplayable. If "show missing card data" (should really be "show unimplemented card data") is switched off then Magarena does not even attempt to check whether any images of this type need to be downloaded.

**Comment by lodici** [comment]
The above commit adds an incremental pause that increases by 100 milliseconds each time an error is generated containing the text "HTTP response code: 503". Using the small set of cards mentioned above I am consistently able to download all cards if I download playable and unimplemented one after the other. Also consistently, if I attempt to download both in parallel I will get one or more "HTTP response code: 503" errors. I found that for my modest broadband connection the pause would increase to about 200 or 300 milliseconds and I would end up with maybe two to four fails which I downloaded successfully on a rerun. I am guessing that @slartifer has a much faster connection which is perhaps upsetting the server so hopefully this solution will help to alleviate that particular problem.

**Comment by lodici** [comment]
The above commit prevents both playable and unimplemented download streams from running at the same time which has definitely fixed my own experience of getting 503 errors. I consider this issue now closed for the next release. Please re-open if it continues to be a problem in 1.71.
