### ISSUE TITLE
Actions dependant on previous Events

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#734]
Just polishing up the final Bolster cards, and have a bit of a headscratcher with Sunbringer's Touch.

Essentially bolsters for X and then creatures with +1/+1 counters gain Trample.

Trying this with game.addFirstEvent() didn't give a creature that had just gained a +1/+1 counter trample. Would using game.update() between the event and action also cause triggers to be put onto the stack before the gainAbility action completes?

(The game.update() still doesn't make the targetFilter catch the newly added +1/+1 counters)

**Comment by melvinzhang** [comment]
Checking for counters does not need an update. Hard to tell what's the issue without the groovy code. Please commit the groovy code and a test case/game showing the bug.

**Comment by ShawnieBoy** [comment]
cast Clockwork Beetle then Sunbringer's Touch - The Beetle gains trample, but the elves do not.
Looks as though the Action is occurring before the FirstEvent.

**Comment by melvinzhang** [comment]
Event happen in sequence (one after another), actions occur immediately. So the bolster event happens after SpellCardEvent but the trample gaining happens during the SpellCardEvent. Fix is to change the trample gaining to an event. Working on it.
