### ISSUE TITLE
1_1_red_Devil_creature_token.txt ability property cannot be loaded

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#747]
it reference is ambiguous, it should be SN or this creature.

**Comment by ShawnieBoy** [comment]
Yes, my bad - was using the syntax from the card that created it.

**Comment by melvinzhang** [comment]
This helped to uncover a gap in debug mode actually so it was not all bad. Now debug mode will also check token abilities, previously it only checked card ability.
