### ISSUE TITLE
Combat Phase Timings slightly misleading

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#748]
The timings for Attack attack Block can be a bit misleading when determining timings for when spells are cast.

As declaring attackers or blockers occurs at the beginning of those phases, and during that step fast effects and spells cannot be cast/activated, spells with those timing will be cast afterwards.

This can be more of an issue with spells that grant defensive abilities (ie. Reach or Fog-like spells) which would be cast after blockers are declared. The same for spells which grant abilities which trigger 'When SN attacks' which are cast after attackers are declared.

In essence, Attack timing should really be checking the BeginOfCombat phase, and Block timing should be checking Attack phase (as in cast after attackers are declared).

**Comment by melvinzhang** [comment]
Existing timing hints are given with this in mind based on cursory inspection of a few cards. Eg: Excise, "Exile target attacking creature unless its controller pays {X}" has timing attack. If we change the meaning of existing hints, Excise would need to be changed to Block. It would be hard to find all the cards to change. I suggest adding new timing hints for the proposed functionalty, perhaps a BeforeAttack and BeforeBlock.

**Comment by melvinzhang** [comment]
Attack means during declare attacker step and Block means during declare blockers step, changing the meaning to the step before would be more confusing for me.

**Comment by ShawnieBoy** [comment]
However spells can't be cast during those steps, only before or after - which is confusing for me, hehe

It's a good idea though, prevents cards like Change of Heart using a Must-Attack timing for a spell which prevents attacks.

**Comment by ShawnieBoy** [comment]
Excise should just have a removal timing anyway - removal covers the declare blockers phase, so attacking creatures will still be attacking

**Comment by melvinzhang** [comment]
They are cast during those steps,  just that it is always after the main decision for those step. https://pokeinthe.io/files/Magic%20the%20Gathering%20Turn%20Structure.pdf has a nice illustration.

Exiling before blocking reduces the number of decisions needed to consider during blocking as there is one less attacker. Would there be some strategic reason to wait until after blockers are declared?

**Comment by ShawnieBoy** [comment]
But what I was meaning is that spells can only be cast after creatures are attacking or blocking during those phases, so a 'Target creature can't attack' can't be cast during the declare attackers phase as it would be too slow. It would have to be Begin Combat at the latest.

>Exiling before blocking reduces the number of decisions needed to consider during blocking as there is one less attacker. Would there be some strategic reason to wait until after blockers are declared?

Maybe if you wanted when-blocking triggers to occur, but not the best way of going about it. Maybe Removal should include Attack, as the only other time would be Main phase, or after blocking. No help against things which can enter the battlefield attacking during combat.

**Comment by melvinzhang** [comment]
> so a 'Target creature can't attack' can't be cast during the declare attackers phase

Yes, I agree with this. It needs to be before. Similarly granting Reach to block flyers should be before Blocking phase. Note that Magarena use of phase/step is a bit different from the pdf, what we call a phase is named step in the pdf, what we call a step is named actions.

> Maybe if you wanted when-blocking triggers to occur, but not the best way of going about it.

That makes sense.

**Comment by melvinzhang** [comment]
Attack and Block timing is as their name suggest, the thing to note is that during the Attack/Block step, priority occurs after the attackers/blockers are decided.
