### ISSUE TITLE
Amulet of Vigor doesn't work for 'enters the battlefield tapped unless...'

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#750]
Amulet of Vigor doesn't work for Canopy Vista.

**Comment by melvinzhang** [comment]
Also affects Ravnica Lands that comes into play tapped unless you pay 2 life. Issue is due to land getting tapped by an event, but the AoV trigger fires before the tap event executes.

**Comment by melvinzhang** [comment]
Does not affect "SN enters the battlefield tapped" as the tapping occurs as part of executeTrigger which is before the AoV trigger check.

**Comment by ShawnieBoy** [comment]
So it look like the checking of the condition is 'slowing down' the tap from a trigger to an effect.

``` Java
return condition.accept(permanent) ?
    game.doAction(TapAction.Enters(permanent))
    : MagicEvent.NONE;
```
Although a log message would help with what's occurring as well.
