### ISSUE TITLE
check moderator actions allowed on forum

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#756]
@ShawnieBoy @lodici Huggybaby have added moderator permissions to your forum accounts. Please check that you can create new topics as announcement/sticky and you can lock old topics. If there any issues please PM Huggybaby directly.

Also please be careful when editing/deleting posts on the forum.

Please comment here when you have checked that you have the necessary permissions to create topics for a new release.

**Comment by lodici** [comment]
Looks like all the relevant options are now enabled. Thanks.

**Comment by ShawnieBoy** [comment]
Yes, all activated here too

**Comment by melvinzhang** [comment]
Thanks for the reports. This is all good.
