### ISSUE TITLE
Unable to Identify Layer Dependencies

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#758]
Raised on [Forums](http://www.slightlymagic.net/forum/viewtopic.php?f=82&p=196291#p196222)

Enchanted Evening + Opalescence does not work if Opalescence was the first card to enter the battlefield.

This appears to be related to Layer Dependencies.

- 613.7. Within a layer or sublayer, determining which order effects are applied in is sometimes done
using a dependency system. If a dependency exists, it will override the timestamp system.

 - 613.7a An effect is said to “depend on” another if (a) it’s applied in the same layer (and, if
applicable, sublayer) as the other effect (see rules 613.1 and 613.3); (b) applying the other
would change the text or the existence of the first effect, what it applies to, or what it does to
any of the things it applies to; and (c) neither effect is from a characteristic-defining ability or
both effects are from characteristic-defining abilities. Otherwise, the effect is considered to be
independent of the other effect.

 - 613.7b An effect dependent on one or more other effects waits to apply until just after all of those effects have been applied. If multiple dependent effects would apply simultaneously in this way, they’re applied in timestamp order relative to each other. If several dependent effects form a dependency loop, then this rule is ignored and the effects in the dependency loop are applied in timestamp order.

 - 613.7c After each effect is applied, the order of remaining effects is reevaluated and may change if an effect that has not yet been applied becomes dependent on or independent of one or more other effects that have not yet been applied.

**Comment by melvinzhang** [comment]
Documented this as a game rule on the wiki page, https://github.com/magarena/magarena/wiki/GameRules
