### ISSUE TITLE
Bolster and scripting AI

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#76]
As some AI hints is now being scripted, would it make sense for all Bolster to have 'Cast SN with AI only if AI controls a creature' be relevant. Or to be included in the engine?

**Comment by ShawnieBoy** [comment]
Although bolster is normally a secondary effect, maybe only fully creature-related bolster cards should. Some which gain life etc. can always be handy for the AI even without the bolster effect.

**Comment by melvinzhang** [comment]
Make sense only if bolster is the only effect of the card.
