### ISSUE TITLE
hangs/freezes in gameplay

### ISSUE THREAD

**Issue by plrmag7388** [magarena/magarena#762]
the game freezes and, the crash report screen pops up. once the crash report screen pops up the game unfreezes, but closes the game. this version is unplayable for me. attached are the logs.

![crash](https://cloud.githubusercontent.com/assets/19209307/15047950/d605c440-12ac-11e6-84f5-98ad345b9265.png)
[crash.txt](https://github.com/magarena/magarena/files/250645/crash.txt)
[game.txt](https://github.com/magarena/magarena/files/250646/game.txt)
[import.txt](https://github.com/magarena/magarena/files/250647/import.txt)

**Comment by melvinzhang** [comment]
Thanks for the report. From the crash report, it looks like in both cases it ran out of memory trying to find all cards to discard. Do any of the decks involve lead to a large number of cards in hand?

**Comment by melvinzhang** [comment]
@plrmag7388 It would help us to troubleshoot the issue if you can attach the decks played. Thanks!

**Comment by plrmag7388** [comment]
yes i have an artifact that allows for unlimited hand size

**Comment by plrmag7388** [comment]
ok
here they are

**Comment by melvinzhang** [comment]
@plrmag7388 the decks did not appear in the comment, perhaps it could not receive attachments via email. Could you try attaching them in a new comment? Thanks!

**Comment by Muppet1** [comment]
[crashenchantress.txt](https://github.com/magarena/magarena/files/263412/crashenchantress.txt)
i'll  post mine here too its just 2 decks that do this oddly.

**Comment by melvinzhang** [comment]
merge into #721
