### ISSUE TITLE
Ranger of Eos able to fetch Crovax the Cursed

### ISSUE THREAD

**Issue by Muppet1** [magarena/magarena#763]
A.I. fectched a Crovax.  Not sure if it can fetch things with more mana cost than it should or if it thinks Crovax  costs 1.  
The script looked ok as far as I cld tell.
I think this works fine as a player but not used it recently will add more if I find out.

**Comment by melvinzhang** [comment]
Crovax = Crovax the Cursed? I'm wondering if there are any mana cost reducing permanents on the field at the time. It would be best to include a gameplay report zip (Esc -> Gameplay report).

**Comment by melvinzhang** [comment]
Unable to reproduce without more details. @Muppet1 feel free to reopen when you have more details.
