### ISSUE TITLE
AI infinite loop with Champion ability

### ISSUE THREAD

**Issue by Muppet1** [magarena/magarena#776]
if a card with champion champions a card with champion and then it plays another card with champion you get an infinite loop.  No idea how to prevent this and hopefully its pretty rare.

e.g. Wren's Run Packmaster.  not a bug as such just an infinite loop that needs closing somehow.
The problem is its a new permanent each time so the 3 times rule might be hard to use.

**Comment by melvinzhang** [comment]
Did the AI discover this loop and kept looping instead of continuing the game so that it would lose?

**Comment by Muppet1** [comment]
yes that is correct.

**Comment by ShawnieBoy** [comment]
In game-rule terms this won't be a loop that ends in a draw, as there's a choice involved. However, combine this with an 'Enters the battlefield' trigger (eg. Warstorm Surge) and you get a win condition.

**Comment by melvinzhang** [comment]
This is a tough one to prevent, none of the existing tricks for prevent loops work. For now, we'll document such cases on the wiki at https://github.com/magarena/magarena/wiki/Loops
