### ISSUE TITLE
Card Image overhaul

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#777]
With the expansion of card rendering to include cropped images, and the extra languages now supported, I think it's worth having another look at the script builder in regards to image linking.

Already most of the smaller reprint runs and limited prints are not included, as they generally have far fewer language distribution.

This could be expanded to include online-only sets as well. These sets don't have multiple languages or crops. However they may have updated oracle, and some definitely have type and subtype changes. Oracle and type don't effect crops as the text is already generated from the Oracle, but would effect Language and those using full-images.

The goal would be to have each card image targeting a version with a crop, and the most language options - these are generally the main core printings.

As always the custom folder can be used for player-found images.

**Comment by ShawnieBoy** [comment]
To confuse matters, there are sections on magiccards.info which display languages where a card set -was- printed in that language, but may not have images in that language.

**Comment by ShawnieBoy** [comment]
I feel that these image updates shouldn't prompt a 'download new images' dialog for the user, as in most instances these images will either already exist as full images, and present no functional changes, or will not exist for crops. (Also makes it a lot easier to update). Having already pushed a set with that prompt, having more images with the prompt are redundant as the image downloader scans whether images are present as default.

**Comment by lodici** [comment]
#94 is the original discussion we had regarding the ```image_updated``` property. My understanding, it would be something used fairly infrequently for the odd link error or for upgrading low quality images to high (mainly with new sets). In both these cases I think the "new images" alert is appropriate. If, as it seems to be, ``image_updated`` is being used for other more frequent use cases then we need to clearly identify these and perhaps look at adding additional script properties instead of trying to commandeer ```image_updated```.

**Comment by ShawnieBoy** [comment]
Thanks, yes, I agree - the recent image url adjustments to help accommodate languages and crops don't require prompting the user to download 'newer' images. The `image_updated` would be used when CN2 images are of a better quality.

To save forcing unnecessary downloads, I'll remove the download prompts I've pushed for 09-10 and 09-11. I don't think that any other script properties would be appropriate for this use, just a mention in the release notes that more language/crop sources are supported.

**Comment by ShawnieBoy** [comment]
linked with #602 I think I've now managed to have all card urls pointing to a source which has crops/additional languages. Several sets on magiccards.info don't have any crops available: CN2, C15, C13,  M14, BNG, THS. There are also some problems with split cards, where one half will have a crop and not the other, or both crops combined, or even just a full image instead of a crop.
Tokens still do not have crops.

Even with the above issues, the number of available images is vastly improved. (If I do say so myself)

**Comment by melvinzhang** [comment]
>  just a mention in the release notes that more language/crop sources are supported.

Good point, do consider adding an item to release/README.txt
