### ISSUE TITLE
AI vs AI game does not pause when menu is displayed

### ISSUE THREAD

**Issue by magreenblatt** [magarena/magarena#798]
Magarena version 1.74

1. Run an AI vs AI game (add -DselfMode=true to the Java command-line).
2. Display the menu by pressing ESC. For example, to generate a gameplay report.
3. Notice that the AI vs AI game does not pause.

In addition to facilitating the capture of gameplay reports having the game pause when showing the menu would be a nice feature for observers of AI vs AI games.

**Comment by melvinzhang** [comment]
Good idea, looking into it.

**Comment by melvinzhang** [comment]
@magreenblatt this will be available in next release. On a related note, I'm curious as to how you are using the AI vs AI mode? 

This mode isn't officially supported (as you can tell from the command line shenanigans needed to get it going). If there a nice use case for it, it may be worthwhile to upgrade it to something more users can make use of.

**Comment by magreenblatt** [comment]
Thank you for implementing this :)

> I'm curious as to how you are using the AI vs AI mode?

I'm using AI vs AI mode to play test decks that I design. This is fun for a number of reasons:

1. I get to see how "someone else" plays my decks. Occasionally I'm surprised and either learn something new or file a bug.
2. It's faster than playing one of the decks myself (no pauses waiting for user input), and more reliable since the "human factor" is removed.
3. In the future I might automate the process to generate relative deck performance stats.

For the average user I think issue #138 would be nice.

For my purposes I was thinking about adding some additional command line flags to specify (a) the decks (by path to deck file) and (b) the number of games. For the automated use case I want to write a log file with the win/loss ratio and then have the program exit after the games are complete instead of starting over.

**Comment by magreenblatt** [comment]
> For my purposes I was thinking about adding some additional command line flags

Looks like AI vs AI mode plays whatever was last stored in the "Magarena\duels\latest.duel" file. This file is written by the "New duel" screen src\magic\ui\screen\DuelDecksScreen.java saveDuel() and read by src\magic\MagicMain.java startUI() using src\magic\data\DuelConfig.java load(). The format for this file is quite simple, so it's probably better to just write this file with the desired contents before starting Magarena instead of adding new command line flags.

**Comment by magreenblatt** [comment]
> For the automated use case I want to write a log file with the win/loss ratio and then have the program exit after the games are complete instead of starting over.

This logic is controlled in src\magic\ui\MagicFrame.java showDuel(). If the game is finished then exit instead of calling newDuel().

**Comment by melvinzhang** [comment]
@magreenblatt thanks for sharing how you are using this. Yes, it looks like #138 would be the best way to proceed with this for the interactive mode. For automated mode, we already have an existing facility which I've mentioned in #800. 

Most of the time we only hear of the bad moves, what are some of the interesting moves you've seen from the AI?

**Comment by magreenblatt** [comment]
> Most of the time we only hear of the bad moves, what are some of the interesting moves you've seen from the AI?

One of my favorites was something like:

- AI player 1 has a 3/3 creature and < 4 life. Hand consists of 2 x instant that deals 2 direct damage. It's player 1's turn.
- AI player 2 has a 4/4 creature and 5 life. Hand unknown (by me).

Play proceeds as follows:

1. Player 1 deals 2 direct damage to 4/4 creature.
2. Player 1 attacks with 3/3 creature.
3. Player 2 declines to block (presumably so the 4/4 doesn't die), and goes down to 2 life.
4. Player 2 kills Player 1 with 2 direct damage.

If I were Player 1 I probably would have killed the 4/4 creature with the instants and left my opponent with 2 life just to be on the safe side. Kudos to the AI for taking a risk and winning :)
