### ISSUE TITLE
Partially implement some "unimplementable" cards?

### ISSUE THREAD

**Issue by magreenblatt** [magarena/magarena#799]
Some cards like Deathrite Shaman [1] could still be good cards even without the "unimplementable" mana ability. What is the preference/policy on partially implementing cards in cases where the card can still function without the "unimplementable" component?

[1] http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=413757

**Comment by melvinzhang** [comment]
We try not to have partial implementations, as which subset of implementable abilities make a card viable is not clear cut. It would depend on the deck that card is in, the metagame, etc. Btw the link to the card description is very handy.

**Comment by magreenblatt** [comment]
Thanks for the explanation. Closing this issue.
