### ISSUE TITLE
Add option to exit AI vs AI mode after completion of games

### ISSUE THREAD

**Issue by magreenblatt** [magarena/magarena#800]
Magarena version 1.74

When running in AI vs AI mode (-DselfMode=true) the program will automatically start a new duel after the specified number of duels ("config.games" in Magarena\duels\latest.duel) have completed [1]. For automated use cases it would be nice to have an option whereby the program exits after the specified number of duels and outputs the win/loss ratio (in a log file, for example). See issue #798 for related discussion.

[1] This logic is controlled in src\magic\ui\MagicFrame.java showDuel().

**Comment by melvinzhang** [comment]
For automated runs, there is a separate facility that runs the AI and the model without the view. We use it for benchmarking the various AIs. It has facilities to select the deck and AI for each player and the number of games to play. It is implmented in the class DeckStrCal which can be accessed as follows:
```
java -Xms256M -Xmx512M -noverify  -cp lib/groovy-all-2.4.5.jar:Magarena.jar  \
magic.DeckStrCal \
--seed 101 \
--ai1 MCTS --str1 6 \
--ai2 MCTS --str2 6 \
--games <number of games> \
--deck1 <path to deck for player 1>
--deck 2 <path to deck for player 2>
```
It outputs a tab separated table of results. See https://github.com/magarena/magarena/blob/master/src/magic/DeckStrCal.java for more options and output format

Would this work for you intended use case?

**Comment by melvinzhang** [comment]
https://www.firemind.ch/ uses a variation of this to provide a service that does automated play testing of submitted decks. For each duel, you can also drill down into the game log, eg https://www.firemind.ch/games/1811263

**Comment by magreenblatt** [comment]
Thanks, using DeckStrCal (or similar) should work nicely. Closing this issue.
