### ISSUE TITLE
change images directory doesn't work in Linux

### ISSUE THREAD

**Issue by smutkovski** [magarena/magarena#803]
hi,
just noticed that it's impossible to change directory(from default one) where cards images will be downloaded on Linux, as it always fails on free disk space, independently on actual free space on disk.
![magarena](https://cloud.githubusercontent.com/assets/6854763/16850793/fb20d248-4a00-11e6-94aa-9a31534d8c2b.png)

**Comment by lodici** [comment]
Sorry, unable to replicate. Had a play with Linux Mint and was able to point to another folder without any problems. Could it be a permissions thing? Is the folder on a different drive? etc.

**Comment by smutkovski** [comment]
after few more tests, problem happens only when i write path in folder name text field with path to directory that i want to create. When existing folder is used, then it works. I think game tries test free space on non existing folder, when it should do the "would you like to create this folder?" dialog and then test the free space.

**Comment by lodici** [comment]
Thanks for the clarification. The "not enough space" message box is misleading. Should either show a "invalid directory/path" message instead and you could then use the "new directory" button in the dialog or Magarena attempts to automatically create the path if it does not exist.

**Comment by lodici** [comment]
Disabled the folder name text box - the folder either needs to already exist or can only be created by using the "new folder" button in the dialog.
