### ISSUE TITLE
Phyrexian Metamorph cannot be cast using life for the phyrexian mana but can be using blue.

### ISSUE THREAD

**Issue by Muppet1** [magarena/magarena#81]

**Comment by melvinzhang** [comment]
As mentioned on http://www.slightlymagic.net/forum/viewtopic.php?f=82&t=3735&start=900#p173158 this is fixed in https://github.com/magarena/magarena/commit/2d695a9f48bb5f3bd75fd46eb486c15156bf4992 which is part of 1.59. Did it occur again in 1.59?

**Comment by Muppet1** [comment]
yes 1.59 

     On Wednesday, 4 March 2015, 8:49, Melvin Zhang <notifications@github.com> wrote:
   

 As mentioned on http://www.slightlymagic.net/forum/viewtopic.php?f=82&t=3735&start=900#p173158 this is fixed in 2d695a9 which is part of 1.59. Did it occur again in 1.59?—

**Comment by melvinzhang** [comment]
Did you have sufficient life points? Please describe the permanents available, especially the mana generating permanents on your board and artifact/creatures on the board. The best way is to attach a game.log file from <install dir>/Magarena/logs/game.log.

**Comment by Muppet1** [comment]
yes board had a creature on both sides but occurs in all situations I have never ever been able toc ast it for Phyrexian life mana and I have always been able to cast it for blue in all situations if you find one where u can cast it for phyrexian life let me know and i'll see if I can all other phyrexian spells work fine on life 

     On Wednesday, 4 March 2015, 9:36, Melvin Zhang <notifications@github.com> wrote:
   

 Did you have sufficient life points? Please describe the permanents available, especially the mana generating permanents on your board and artifact/creatures on the board. The best way is to attach a game.log file from /Magarena/logs/game.log.—

**Comment by melvinzhang** [comment]
Thanks, I'm able to replicate the issue now.
