### ISSUE TITLE
Latest java version 8.0_101 incompatible with launch4j?

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#817]
originally raised by [jerichopumpkin in forum](http://www.slightlymagic.net/forum/viewtopic.php?f=82&t=18865&p=199710#p199705).

![screenshot00532](https://cloud.githubusercontent.com/assets/2443519/17278930/23040cb4-5760-11e6-9d6c-05fa6c116320.png)

I have been able to replicate in Windows 7. I have been using 8.0_72 and downloaded and installed the latest version 8.0_101 but without removing 8.0_72. I updated JAVA_HOME and `java -version` returns 101 and when I double-click the jar it uses 101 as expected. BUT, when I run Magarena.exe it still uses 72 for some reason. If I rename the 8.0_72 JRE folder (ie. so it is not effectively installed) and run the exe I get the above error.

**Comment by lodici** [comment]
I actually had three versions of java installed - 8.0_51, 8.0_72 and 8.0_101. I removed 72 and the exe still worked by using 51 instead. I then removed 51 and the exe ran fine using 101. Still a bit strange though. So looks like this might be a problem if you have multiple versions of java installed on your system.

**Comment by melvinzhang** [comment]
Seems to be a Java issue unrelated to the application. Java version have moved on significantly since this was reported.
