### ISSUE TITLE
Implement Melee mechanic from CN2

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#824]
As there is no other players, the creature gets +1/+1 for attacking the opponent.

**Comment by ShawnieBoy** [comment]
This raises the 'attacking planeswalker' issue again, as the bonus wouldn't be gained for attacking a planeswalker, only a player. For Magarena, it makes this ability more powerful as the extra damage can be redirected to a planeswalker.

**Comment by melvinzhang** [comment]
@ShawnieBoy Yes, that's true. Should go ahead with this item or treat all Melee cards as not supported?

**Comment by melvinzhang** [comment]
added in 40780bc8d8bca9fc
