### ISSUE TITLE
Implement Goad mechanic from CN2

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#825]
"If the creature can't attack a player other than you, then it must attack you or a planeswalker if it can."

Therefore it can be implemented as until your next turn, creature must attack if able.

**Comment by ShawnieBoy** [comment]
Goading would prioritise attacking a player over attacking a planeswalker. Only if the creature is unable to attack a player would it then attack a planeswalker. Attacking a planeswalker issue one again. Would be nice if there was some way of getting that implemented.
