### ISSUE TITLE
Implement Monarch mechanic from CN2

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#826]
As an MagicPlayerState, "you become Monarch", "if you were the Monarch". Only one player can be the Monarch at a time.

The Monarch:
"At the beginning of your upkeep, draw a card"
"Whenever a creature deals combat damage to you, its controller becomes the monarch"

**Comment by ShawnieBoy** [comment]
I would hold-fire on this mechanic, as it is would appear to be format specific to Consipiracy draft. We neither support multiplayer or drafting. Being monarch also has rules included which involve drawing a card at the end of turn. Seeing how comprehensive rules incorporate this will be interesting to see, they may simply remove the additional card draw and allow a 'monarch' player state.

**Comment by melvinzhang** [comment]
Thanks for that, I'd forgotten about the extra card draw. Your right, should wait and see if they allow these cards in Legacy/Vintage.

**Comment by ShawnieBoy** [comment]
Monarch also changes on creature combat damage too - I've a feeling that the cards themselves will be legal, but the extra monarch mechanics will be format rules. Extending the banned list would be limiting for them, having a card type banned is easier (Conspiracy card type).

**Comment by melvinzhang** [comment]
Looks like the non-conspiracy cards are legal as twitted by Matt, see https://twitter.com/TabakRules/status/765218877038964736

**Comment by ShawnieBoy** [comment]
Cool - I'd guess that changing of monarch would be limited to card effects and not combat damage in non-conspiracy games then. Also without extra card draw.

**Comment by melvinzhang** [comment]
I think the combat damage switch needs to be there, otherwise it would be unfair when only one player plays with Monarch cards, he/she gets to stay as Monarch all the way and gain a lot of additional advantage in the cards that care about Monarch.

**Comment by ShawnieBoy** [comment]
That's a very good point. Base game state would involve no player being monarch, and would then swap when and if someone 'becomes monarch' - The state change would also be a player state trigger as well, only if they weren't the monarch to begin with.

**Comment by ShawnieBoy** [comment]
Guess would just have to wait and see what happens :smile:

**Comment by melvinzhang** [comment]
Official rules for Monarch from http://magic.wizards.com/en/articles/archive/feature/conspiracy-take-crown-release-notes-2016-08-22

716.1. The monarch is a designation a player can have. Some cards instruct a player to become the monarch.

716.2. There are two inherent triggered abilities associated with being the monarch. These triggered abilities have no source and are controlled by the player who was the monarch at the time the abilities triggered. This is an exception to rule 112.8. The full texts of these abilities are "At the beginning of the monarch's end step, that player draws a card" and "Whenever a creature deals combat damage to the monarch, its controller becomes the monarch."

716.3. Only one player can be the monarch at a time. As a player becomes the monarch, the current monarch ceases being the monarch.

716.4. If the monarch leaves the game, the active player becomes the monarch. If the leaving monarch is the active player, the next player in turn order becomes the monarch.

The game starts with no monarch. Once an effect makes one player the monarch, the game will have exactly one monarch from that point forward.

Abilities that trigger whenever you "become the monarch" trigger only if you aren't already the monarch. For example, if you are already the monarch as Custodi Lich enters the battlefield, its last ability won't trigger.

If the triggered ability that causes the monarch to draw a card goes on the stack, and a different player becomes the monarch before that ability resolves, the first player will still draw the card.

**Comment by ShawnieBoy** [comment]
@lodici Is there any room left on the player avatar for a monarch indicator? A simple crown icon would do the trick nicely, but I know it's fairly pushed for space already.

**Comment by lodici** [comment]
![screenshot00065](https://cloud.githubusercontent.com/assets/2443519/6641088/8f7f6d40-c993-11e4-8d4d-fcba50cd81b8.png)

Looks like there is a vacancy in the top left corner.

**Comment by ShawnieBoy** [comment]
Excellent - Thanks for that. I'm working on getting the monarch player state included, but surprisingly complicated as it links into lots of things we've not done before with player states.
It's another of those mechanics which won't appear very often, but having something visual to see if it's being registered would help while trying to get it to work. I'll push some basic state info later today and have a look at the avatar overlay.

**Comment by lodici** [comment]
Take a look at ```magic.ui.duel.player.PlayerImagePanel```. You should just need to add an ```isMonarch()``` method to the passed in ```PlayerViewerInfo``` and then add a method to draw the monarch icon in ```paintComponent()```.

**Comment by ShawnieBoy** [comment]
Having trouble getting Monarch to work - I'll push what I've put together so far, hopefully someone will be able to salvage it.

**Comment by melvinzhang** [comment]
Thanks for the initial work on this, the problem is because of the way player state is handled. Previously it only works when implemented as MagicStatic, now it works with calls to setState/clearState in actions as well. Fixed up a couple of other bugs as well, such as missing undoAction and wrong cast of getImage. Please help to check that all works as intended.

**Comment by ShawnieBoy** [comment]
Thanks for looking into that - was getting myself in a mess!

Are there any issues with the engine regarding the draw trigger source? Game-wise it should have no source, which can be included with `MagicSource.NONE` and with some testing seems to be working ok without linking to a pseudo-card source, but I could be missing something esp. with AI.

**Comment by melvinzhang** [comment]
Event that goes on the stack can't have a NONE source. It will crash due to calling methods on source. That's why I had to create the pseudo-card. It seems like a good way to remind players of the monarch rules as well.

It seems you got NONE source to work, could you paste a code sample here. I'm curious as to how it can be done.

Btw the change to "The monarch draws a card. (PN)" is incorrect. Even if you are no longer the monarch when it resolves, you still draw a card. The full text of the rules is "At the beginning of the monarch’s end step, that player draws a card".

**Comment by ShawnieBoy** [comment]
>Btw the change to "The monarch draws a card. (PN)" is incorrect. Even if you are no longer the monarch when it resolves, you still draw a card. The full text of the rules is "At the beginning of the monarch’s end step, that player draws a card".

Very good point. Although it will still display the player that will be drawing a card. The name of the trigger log won't change who is drawing the card.  I was trying to show that the game was triggering the effect, and not a player, it may be confusing when looking at logs.

For there to be no source, I was just using MagicSource.NONE instead of the link to the cardDescription. 
`game.createDelayedSource(MagicSource.NONE, eotPlayer),`

**Comment by melvinzhang** [comment]
Sorry, I didn't mean the effect is incorrect, I used the wrong phrase. I meant it is misleading for players. If I read the stack as saying "The monarch..." I would think that changing the monarch would have an effect. However, once it is triggered whether the player is a monarch or not is no longer relevant.

Furthermore, the rules states that "These triggered abilities have no source and are controlled by the player who was the monarch at the time the abilities triggered." The trigger is not neutral, it is controlled by the player.

The phrasing is also inconsistent, for example an ability that is "At the beginning of each player's upkeep, that player draws a card." would trigger and it does not say "The upkeep player draws a card (PN)", it says "{player name} draws a card".

I feel that showing "The Monarch" reminder card makes it clear what created the effect and the complete rules text. Cards with monarch might randomly be selected for a deck and having the "The Monarch" reminder card shown is helpful.

**Comment by melvinzhang** [comment]
I just realized you were referring to the "log" while I was talking about the "stack". I see the problem now, once this goes to the log, the "The Monarch" stack title does not carry over.

The issue with the log not showing the source of triggered effect is something that affects all triggers and a solution has reached in https://github.com/magarena/magarena/issues/531
