### ISSUE TITLE
Card Image Sources

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#828]
It looks like magiccards.info hasn't been updated for quite a while, Eldritch Moon is still not up.
I've been using cropped images from [CCGHQ](http://www.slightlymagic.net/forum/viewtopic.php?f=15&t=12336) There are also full size images available too at the CCGHQ Mega storage [Release 1](https://goo.gl/6qlF9Y) and [Release 2](https://goo.gl/6qlF9Y) which also includes Eldritch Moon.

These may be handy links until magiccards.info gets updated

**Comment by lodici** [comment]
The default download of card images from magiccards.info via the downloader is definitely the most convenient way but I must admit I much prefer the CCGHQ 200DPI cards from Mega, although it is slow to download each set. I think I might look at a hacking some code which will automatically extract and rename the images from a downloaded Mega zip into the custom folder.

**Comment by melvinzhang** [comment]
Cards have been updated to magiccards.info @ShawnieBoy does that resolve the problem raised in this issue?

**Comment by ShawnieBoy** [comment]
Yes, I think that this can be closed, but the info is still valid. There have been times when we've been ahead of magicards.info.
