### ISSUE TITLE
Implement Crew mechanic from Kaladesh

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#829]
similar to DevourTrigger's event

**Comment by ShawnieBoy** [comment]
I do wonder if this is a step towards "Assembling a contraption" for [Steamflogger Boss](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=136151) - The "crews a vehicle" condition on [Speedway Fanatic](http://media.wizards.com/2016/bVvMNuiu2i_KLD/en_fpBCSo5oJh.png) sounds very similar.
