### ISSUE TITLE
Is land count icon necessary?

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#83]
ie...
![screenshot00044](https://cloud.githubusercontent.com/assets/2443519/6509842/f37be1ce-c359-11e4-8e9d-256cb3fba287.png)

**Comment by ShawnieBoy** [comment]
I personally never use it, and since coming back I noticed it on a theme (Was just a green game-piece) and I couldn't work out what is was for ages!
Having a separate damage shield and poison counter would make more sense.

**Comment by lodici** [comment]
Ok, thanks. The reason I ask is that I am redesigning the game player panel (very much a WIP)...
![screenshot00045](https://cloud.githubusercontent.com/assets/2443519/6510190/575287aa-c35c-11e4-826f-023901e4bab1.png)
Health and poison counters are overlayed on the avatar image with an additional fancy gauge for combined overall health (if I can get it to work). The player zones (hand, graveyard and exile) are now toggle buttons which when pressed will display the cards in the appropriate zone.

> Having a separate damage shield and poison counter would make more sense.

I am not sure what you mean by damage shield. Could you clarify (in noob terms! :))

**Comment by ShawnieBoy** [comment]
The blue shield icon in the above image is for 'prevent the next X damage done to you this turn' type abilities. That's normally replaced with a poison counter when poisoned. Not sure what happens when you have both.

**Comment by lodici** [comment]
Thanks for the explanation, I was not even aware of this mechanic. There is enough room so I will add another overlay on the avatar image when that comes into effect. As you say not sure how it manages to fit two into one at the moment (well not until I look at the code anyway).

**Comment by lodici** [comment]
> not sure how it manages to fit two into one at the moment (well not until I look at the code anyway).

Poison counters have priority over damage prevention!

**Comment by ShawnieBoy** [comment]
I had a feeling that was the case - The damage prevention and poison will be niche cases for certain decks, so overlay would suit them far more than big icons. I'm liking the mock-up.

Instead of land-count information overlaying the avatar, what about when cursoring over land, or displayed somewhere in the hand? I'm not sure how many times it would be useful (I'm guessing X-spells mainly) as cards are already being highlighted (highlit?) when they're able to be cast.

**Comment by lodici** [comment]
> Instead of land-count information overlaying the avatar,

Well actually I was planning on omitting the land-count altogether since I am unclear why it is required. No point in cluttering up the UI with meaningless data. Of course there might be some play or mechanic where the land count is absolutely essential. I am all ears! :ear: :ear:
