### ISSUE TITLE
Pending token generation oracle changes and scriptbuilder

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#833]
Tokens will not longer be 'put onto the battlefield', but 'created' instead - this will no doubt have a big oracle edit for previous cards.

![image](http://media.wizards.com/2016/bVvMNuiu2i_KLD/en_iP3U5MKa0W.png)

So scriptbuilder will no doubt be run, for simplicity's sake, on all cards once the json is updated (and gatherer!).

Things that will need adjusting would be the image-update field, if it would need to be retained. An edit to the method used to change only the image url ref on the update images could work, however things like the 'removal' value and 'enchant' property will also be lost. Or in the case for enchant, defaulting to 'default permanent'.

Even if only the token generators were re-scripted, there would still be a bit of tweaking involved.

**Comment by melvinzhang** [comment]
All the card scripts have been updated to use the new syntax.
