### ISSUE TITLE
AI uses Incendiary Flow on itself

### ISSUE THREAD

**Issue by tywkeene** [magarena/magarena#834]
Unless I am sorely mistaken, [Incendiary Flow](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=414432) would be better off being used on a target creature or player, like the 2/2 [Walking Corpse](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=413376) I had on the field. Instead, Monte Carlo thought it prudent to use the card on itself.

Below is the information that may be needed in resolving this. Thanks and cheers.

The AI is: Monte Carlo, Level 6 AI (MCTS)
I also have a screenshot of the board state:
http://imgur.com/a/bR4o7
![x6fc83q](https://cloud.githubusercontent.com/assets/2443519/18384164/fc95b984-7680-11e6-86bf-88e1decf06bd.jpg)

Here is my game.log leading up to this bug:

```
LOG (C): Monty Carlo attacks with <Dawn Gryff~1000065>.
LOG (P): {c}savior loses 2 life.
LOG (C): Monty Carlo puts a 1/1 white and black Human Cleric creature token onto the battlefield. Put <Cleric~-1> onto the battlefield.
LOG (P): savior may (no) take a mulligan.
LOG (C): Monty Carlo may (no) take a mulligan.
LOG (P): Play <Swamp~1000053>. Put <Swamp~1000053> onto the battlefield.
LOG (P): Tap <Swamp~1000053>. Pay {B}. Play <Sanitarium Skeleton~1000015>.
LOG (P): Put <Sanitarium Skeleton~1000015> onto the battlefield.
MCTS cached=0
MCTS cheat=false index=1 life=20 turn=2 phase=FirstMain sims=24 time=6074
* [66/8/?] (pass)
  [64/8/?] (Plains)
  [58/8/?] (Mountain)
MCTS cached=8
MCTS cheat=false index=1 life=20 turn=2 phase=SecondMain sims=32 time=6505
  [53/10/?] (pass)
  [60/14/?] (Plains)
* [61/15/?] (Mountain)
LOG (C): Play <Mountain~1000089>. Put <Mountain~1000089> onto the battlefield.
LOG (P): Play <Swamp~1000056>. Put <Swamp~1000056> onto the battlefield.
LOG (P): Tap <Swamp~1000056>. Tap <Swamp~1000053>. Pay {1}{B}. Play <Walking Corpse~1000026>.
LOG (P): Put <Walking Corpse~1000026> onto the battlefield.
LOG (P): savior attacks with <Sanitarium Skeleton~1000015>.
LOG (C): {c}Monty Carlo loses 1 life.
MCTS cached=0
MCTS cheat=false index=1 life=19 turn=4 phase=FirstMain sims=23 time=6543
  [58/8/?] (pass)
* [68/14/?] (Plains)
  [20/1/?] (Mountain)
LOG (C): Play <Plains~1000088>. Put <Plains~1000088> onto the battlefield.
MCTS cached=14
MCTS cheat=false index=1 life=19 turn=4 phase=FirstMain sims=26 time=6122
  [57/11/?] (pass)
* [61/15/?] (Steadfast Cathar)
  [56/13/?] (Incendiary Flow)
LOG (C): Pay {1}{W}. Tap <Mountain~1000089>. Tap <Plains~1000088>. Play <Steadfast Cathar~1000067>.
LOG (C): Put <Steadfast Cathar~1000067> onto the battlefield.
LOG (P): Play <Swamp~1000052>. Put <Swamp~1000052> onto the battlefield.
MCTS cached=0
MCTS cheat=false index=1 life=19 turn=6 phase=FirstMain sims=29 time=6613
* [72/10/?] (pass)
  [9/1/?] (Plains)
  [7/1/?] (Steadfast Cathar)
  [65/7/?] (Prophetic Ravings)
  [46/2/?] (Incendiary Flow)
  [73/8/?] (Mountain)
MCTS cached=10
MCTS cheat=false index=1 life=19 turn=6 phase=DeclareAttackers sims=26 time=6020
* [67/24/?] ([Steadfast Cathar])
  [54/11/?] ([])
LOG (C): Monty Carlo attacks with <Steadfast Cathar~1000067>.
LOG (C): <Steadfast Cathar~1000067> gets +0/+2 until end of turn.
LOG (P): savior blocks with <Sanitarium Skeleton~1000015>.
LOG (P): <Sanitarium Skeleton~1000015> is destroyed.
MCTS cached=0
MCTS cheat=false index=1 life=19 turn=6 phase=SecondMain sims=31 time=6569
  [7/1/?] (pass)
  [71/9/?] (Plains)
  [13/1/?] (Steadfast Cathar)
  [67/8/?] (Prophetic Ravings)
  [9/1/?] (Incendiary Flow)
* [66/11/?] (Mountain)
LOG (C): Play <Mountain~1000097>. Put <Mountain~1000097> onto the battlefield.
MCTS cached=11
MCTS cheat=false index=1 life=19 turn=6 phase=SecondMain sims=35 time=6617
* [72/18/?] (pass)
  [72/15/?] (Steadfast Cathar)
  [62/9/?] (Prophetic Ravings)
  [43/3/?] (Incendiary Flow)
LOG (P): Tap <Swamp~1000052>. Tap <Swamp~1000053>. Tap <Swamp~1000056>. Pay {2}{B}. Play activated ability of <Sanitarium Skeleton~1000015>.
LOG (P): Return <Sanitarium Skeleton~1000015> from savior's graveyard to savior's hand.
MCTS cached=0
MCTS cheat=false index=1 life=19 turn=6 phase=SecondMain sims=27 time=6404
  [65/6/?] (pass)
  [70/8/?] (Steadfast Cathar)
  [26/1/?] (Prophetic Ravings)
* [72/12/?] (Incendiary Flow)
MCTS cached=12
MCTS cheat=false index=1 life=19 turn=6 phase=SecondMain sims=34 time=6607
  [61/12/?] ()
* [73/33/?] ()
MCTS cached=0
MCTS cheat=false index=1 life=19 turn=6 phase=SecondMain sims=33 time=6135
  [16/1/?] (savior)
* [76/12/?] (Monty Carlo)
  [75/12/?] (Walking Corpse)
  [67/8/?] (Steadfast Cathar)
LOG (C): Pay {1}{R}. Tap <Mountain~1000089>. Tap <Mountain~1000097>. Play <Incendiary Flow~1000076>.
LOG (C): <Incendiary Flow~1000076> deals 3 damage to target creature or player (Monty Carlo). If a creature dealt damage this way would die this turn, exile it instead.
```

Edit: Forgot screenshot link
Edit (lodici): add image by dragging into edit box.

**Comment by lodici** [comment]
Thanks for the report - that definitely looks like a bad play. Magarena also has a gameplay report (not very well documented) which can be generated during a game by opening the game menu (see image below) via the Escape key. It generates a zip file which can be attached to a github issue simply by dragging it into a comments box. The zip file contains a screen shot, game log and a snapshot of the game state which helps immensely in trying to replicate an issue.

![screenshot00537](https://cloud.githubusercontent.com/assets/2443519/18384435/5f61c0d4-7682-11e6-8a9b-4b82941db9ee.png)

**Comment by ShawnieBoy** [comment]
This is interresting, I've not seen the AI damage itself with direct damage before. Do you have the decklists? Would be interesting to see what else was in the AI's deck, and yours - why a low life would lead to a victory (In the AI simulations).

Did you play the game through?

**Comment by tywkeene** [comment]
> Magarena also has a gameplay report

I saw this, but didn't even think about it at the time, and since have played another game or two.

> Would be interesting to see what else was in the AI's deck, and yours


My deck is:
7 creatures:

4 Crow of Dark Tidings
4 Gravedigger
4 Indulgent Aristocrat
4 Sanitarium Skeleton
4 Stromkirk Mentor
4 Vampire Cutthroat
4 Walking Corpse

3 spells:

4 Choking Restraints
4 Marked by Honor
4 Shamble Back

2 lands:

4 Forsaken Sanctuary
16 Swamp

Unfortunately the AI was using a random red/white deck in the Shadows over Innistrad Block, so I can't reproduce it exactly.

I will keep these tips in mind when reporting future bugs. Sorry for not getting it right this time, I know how frustrating it can be when bugs like this happen.

**Comment by ShawnieBoy** [comment]
That's ok - thanks for the extra info does help to narrow it down a bit. There's nothing in your deck which would suggest that it wouldn't matter if it's life was lower, although the simulations could be showing that the self-mill of Crow of Dark Tidings would mill you before killing the AI (If repeatedly returning it with Gravedigger).

The simulations (number in square brackets) were close between choosing to damage you or itself.

Melvin is the AI-guy, just throwing some ideas around. 😁

**Comment by tywkeene** [comment]
I'm still pretty new to Magic (Loving it by the way, the art, the gameplay, amazing game) so I had no idea there might be situations where you would want less HP. I'll try to keep that in mind when reporting further bugs.

**Comment by melvinzhang** [comment]
Something that jumped out at me is that number of simulations (sim=n) seems rather low, the way MCTS works is by using simulations to gauge its moves. With very low simulations it cannot differentiate between different options. Were there some other CPU intensive application running in the background or was this on a system with an older CPU?

**Comment by melvinzhang** [comment]
The AI's deck is important here. The gameplay report would include it. There may be cards that benefit from the AI having a lower life.

**Comment by lodici** [comment]
@tywkeene if you are still playing the duel (I noticed it is best of 7) then you can save the AI's deck from the Duel Decks screen (see image) by selecting the AI tab and opening the deck editor (highlighted) and clicking on the save deck icon.
![screenshot00538](https://cloud.githubusercontent.com/assets/2443519/18408319/f5b9708a-7723-11e6-8e4f-0bfe0d85cbb6.jpg)

**Comment by tywkeene** [comment]
> if you are still playing the duel

Sorry I'm not. I was playing pretty late at the time and when I quit for the night I ended up closing Magarena, then started another duel with different decks today. Whoops. Like I said before I'll keep these tips in mind if I come across another bug.

> Were there some other CPU intensive application running in the background or was this on a system with an older CPU?

Yep, Chrome and I think gimp, and cockatrice most likely. This paired with the fact I'm running on a Core 2 Duo (I know, poor me) probably didn't help much.

**Comment by melvinzhang** [comment]
The number of sim is too low to have a decent result with MCTS. Without a gamplay report, it is difficult to replicate the scenario.
