### ISSUE TITLE
Automatically create the gameplay report each turn.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#835]
It is clear from the number of posts here and in the forum reminding players about the game report that the game report function does not really work because it relies too much on players (1) knowing about it and (2) remembering to use it. I think it would be more useful if it was automatically generated at the beginning of each turn. Players could still manually create the report but if they forget then at least we would have something closer to the issue with a bit more info.

Alternatively, it might help to create an [issue template](https://help.github.com/articles/creating-an-issue-template-for-your-repository/) with a reminder on how to create a game-play report. Likewise with the forum if possible.

**Comment by lodici** [comment]
I have added a first draft of ISSUE_TEMPLATE.md which add instructions to a new issue. Feel free to amend.

**Comment by lodici** [comment]
Decided to just go with the ISSUE_TEMPLATE, see how that pans out.

**Comment by melvinzhang** [comment]
Thanks for creating the issue template. For reference the forum bug report template is as follows:

To help us in addressing bugs, the best way is to create an issue on the issue tracker. This lets us keep track each report separately and ensures it doesn't get lost.
https://github.com/magarena/magarena/issues (requires github account)

For game play bugs, please include a gameplay report zip file. You can create a gameplay report by opening the options menu (press Esc during a duel) and selecting the "Gameplay Report" menu item.

Less preferred is to post your report in this thread. (requires forum account)

You can report anonymously via gitreports, note that name/email if provided will be listed on the issue tracker.
https://gitreports.com/issue/magarena/magarena (no sign-up required, name/email optional)

**Comment by lodici** [comment]
I have added the instructions on how to create the the gameplay report. Does not look like the anonymous gitreports picks up the ISSUE_TEMPLATE which is a shame.

**Comment by melvinzhang** [comment]
Thanks for bringing up gitreports. It doesn't support ISSUE_TEMPLATE but I can configure the message shown at the top of the report page. I've added in the template manually.
