### ISSUE TITLE
Cropped Image download card count

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#836]
While looking over card images and urls - I've found that the card image numbers don't match between full image and crops.

From a fresh install:
card images show 11077 playable and 4872 unimplemented
cropped images show 11307 playable and 4872 unimplemented

I'd imaging cropped images to show a lower number, not higher.

**Comment by ShawnieBoy** [comment]
I think these extra images may be split and flip cards (2 images per side), but still looks like a high amount (230)

**Comment by lodici** [comment]
> cropped images show 11307 playable and 4872 unimplemented

Do you mean the number of images in your crops folder is 11307?

**Comment by ShawnieBoy** [comment]
Nope, the number of images to download is listed as 11307 - I'm wondering if it's including token images

**Comment by lodici** [comment]
I downloaded the latest 1.77 zip from CiCircle, no import of previous settings so it is a completely clean install and the download dialog displays 11307 for both "Card images" and "Cropped images".

**Comment by ShawnieBoy** [comment]
That's strange - I probably didn't clean out my directory properly... Thanks for checking.
