### ISSUE TITLE
Account for split cards when calculating total card counts

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#84]
see http://www.slightlymagic.net/forum/viewtopic.php?f=82&t=3736&p=174429&sid=a246e214574167b77b30d3e2b28423d1#p174429.

**Comment by lodici** [comment]
Probably the easiest way I can think of is whenever returning a set cards count the number that are splits then subtract half this number from the total cards returned.

**Comment by lodici** [comment]
Had a quick look but I don't think split cards are actually identified at the moment, at least I couldn't find any script with an appropriate setting or reference to split cards in the code, only flip and double-sided. Perhaps splits can be linked using a "split" property similar to the "transform" used with double-sided cards?

**Comment by ShawnieBoy** [comment]
Yes, I would imagine they would have a similar format once we can work out a way of sorting out the annoying state of split cards in the hand.

While there (and in the library) they have both sets of information and we're currently unable to return two values for a card mana cost.

If unimplemented transform cards are not being counted as two cards, then it shouldn't be too difficult to do the same for the split cards.

**Comment by lodici** [comment]
Could we still add the "split" property to the appropriate card scripts even though the mechanic is not yet implemented? It would mean that split cards could at least be identified and this particular issue regarding counts could be resolved.

**Comment by ShawnieBoy** [comment]
I'll have a look at the script-builder. I think it's already doing something with the split cards from a naming point of view.

It also looks as though transform is counting both sides as separate cards, at least with search results, not sure how to tell with an unfiltered list.

**Comment by ShawnieBoy** [comment]
Closed by c5c635c4640084772c32fa3749c07b06933c7cc8
