### ISSUE TITLE
Rite of the Raging Storm

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#841]
name=Rite of the Raging Storm
image=http://magiccards.info/scans/en/c15/30.jpg
image_updated=2016-02-29
value=2.500
rarity=U
type=Enchantment
cost={3}{R}{R}
ability=At the beginning of your upkeep, put a 5/1 red Elemental creature token named Lightning Rager onto the battlefield.;\
        At the beginning of each opponent's upkeep, that player put a 5/1 red Elemental creature token named Lightning Rager onto the battlefield.;\
        As long as it's not your turn, creatures named Lightning Rager can't attack.
timing=enchantment
oracle=Creatures named Lightning Rager can't attack you or planeswalkers you control.\nAt the beginning of each player's upkeep, that player puts a 5/1 red Elemental creature token named Lightning Rager onto the battlefield. It has trample, haste, and "At the beginning of the end step, sacrifice this creature."

**Comment by melvinzhang** [comment]
@kelsioboy Thanks for creating the issue, working via issues is much easier then private messages. The 
"As long as it's not your turn" trick you found is very neat, I think it does the job nicely of providing an equivalent effect. I've added this card and the token in b139e4421be0b8e

**Comment by melvinzhang** [comment]
@kelsioboy I'm not sure why, but it shows that you also closed these issues. Please leave them as open.
