### ISSUE TITLE
Spectral_Grasp

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#842]
name=Spectral Grasp
image=http://magiccards.info/scans/en/cn2/24.jpg
value=2.500
rarity=U
type=Enchantment
subtype=Aura
cost={1}{W}
ability=Enchant creature;\
        As long as it's not your turn, enchanted creature can't attack.;\
        As long as it's your turn, enchanted creature can't block.
timing=aura
enchant=default,creature
oracle=Enchant creature\nEnchanted creature can't attack you or a planeswalker you control.\nEnchanted creature can't block creatures you control.

**Comment by melvinzhang** [comment]
Thanks! Added in 5f46f8aa73ae61b

**Comment by melvinzhang** [comment]
The enchant property should be `enchant=can't attack or block,neg creature`
