### ISSUE TITLE
Vow_of_Flight

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#843]
name=Vow of Flight
image=http://magiccards.info/scans/en/cmd/68.jpg
value=3.339
rarity=U
type=Enchantment
subtype=Aura
cost={2}{U}
ability=Enchant creature;\
        Enchanted creature gets +2/+2 and has flying.;\
        As long as it's not your turn, enchanted creature can't attack.
timing=aura
enchant=default,creature
oracle=Enchant creature\nEnchanted creature gets +2/+2, has flying, and can't attack you or a planeswalker you control.

**Comment by melvinzhang** [comment]
added in https://github.com/magarena/magarena/commit/17fdb282fd99b03a6a83cdb7cf1a8ca79463fde8
