### ISSUE TITLE
Vow_of_Malice

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#844]
name=Vow of Malice
image=http://magiccards.info/scans/en/c15/140.jpg
image_updated=2016-02-29
value=3.467
rarity=U
type=Enchantment
subtype=Aura
cost={2}{B}
ability=Enchant creature;\
        Enchanted creature gets +2/+2 and has intimidate.;\
        As long as it's not your turn, enchanted creature can't attack.
timing=aura
enchant=default,creature
oracle=Enchant creature\nEnchanted creature gets +2/+2, has intimidate, and can't attack you or a planeswalker you control.

**Comment by melvinzhang** [comment]
added in https://github.com/magarena/magarena/commit/b217b88b7e70ec1f98c4cb2620a1adc8ed12dc46
