### ISSUE TITLE
Vow_of_Wildness

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#845]
name=Vow of Wildness
image=http://magiccards.info/scans/en/cmd/178.jpg
value=3.606
rarity=U
type=Enchantment
subtype=Aura
cost={2}{G}
ability=Enchant creature;\
        Enchanted creature gets +3/+3 and has trample.;\
        As long as it's not your turn, enchanted creature can't attack.
timing=aura
enchant=default,creature
oracle=Enchant creature\nEnchanted creature gets +3/+3, has trample, and can't attack you or a planeswalker you control.

**Comment by melvinzhang** [comment]
added in https://github.com/magarena/magarena/commit/7edf2b732d8740a6a93eb6b0f6bdbf2bb2cd3f38
