### ISSUE TITLE
Vow_of_Lightning

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#846]
name=Vow of Lightning
image=http://magiccards.info/scans/en/cmd/138.jpg
value=3.485
rarity=U
type=Enchantment
subtype=Aura
cost={2}{R}
ability=Enchant creature;\
        Enchanted creature gets +2/+2 and has first strike.;\
        As long as it's not your turn, enchanted creature can't attack.
timing=aura
enchant=default,creature
oracle=Enchant creature\nEnchanted creature gets +2/+2, has first strike, and can't attack you or a planeswalker you control.

**Comment by melvinzhang** [comment]
added in https://github.com/magarena/magarena/commit/0bc292c85e7ea201a2824294ba9770681ed91e34
