### ISSUE TITLE
Vow_of_Duty

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#847]
name=Vow of Duty
image=http://magiccards.info/scans/en/c15/84.jpg
image_updated=2016-02-29
value=3.500
rarity=U
type=Enchantment
subtype=Aura
cost={2}{W}
ability=Enchant creature;\
        Enchanted creature gets +2/+2 and has vigilance.;\
        As long as it's not your turn, enchanted creature can't attack.
timing=aura
enchant=default,creature
oracle=Enchant creature\nEnchanted creature gets +2/+2, has vigilance, and can't attack you or a planeswalker you control.

**Comment by melvinzhang** [comment]
added in https://github.com/magarena/magarena/commit/a8794f7db1f2b563091ea537cad1dd90868f507a
