### ISSUE TITLE
5_1_red_Elemental_creature_token_named_Lightning_Rager

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#848]
name=5/1 red Elemental creature token named Lightning Rager
token=Lightning Rager
image=http://cdn.staticneo.com/w/mtg/a/ae/Lightning Rager.jpg
value=2
type=Creature
subtype=Elemental
color=r
ability=Trample;\
        haste;\
        At the beginning of the end step, sacrifice SN.
pt=5/1
oracle=Trample, haste\nAt the beginning of the end step, sacrifice Lightning Rager.

**Comment by melvinzhang** [comment]
The URL you provided for the image does not exists, I've replaced it with a link to https://media.wizards.com/2015/c15_9dsm28ccakCDSk2/en_KrFJ6WHvCU.png
