### ISSUE TITLE
Energy counters

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#850]
Kadalesh introduces Energy counters which are stored 'on' the player, not a permanent. Requires icon for cardbuilder text strings and some kind of ui element for spending/tallying them.

Represented in oracle as E

`Whenever Thriving Rhino attacks, you may pay EE. If you do, put a +1/+1 counter on it.`

**Comment by ShawnieBoy** [comment]
I've been able to get the energy symbol involved, however due to the current symbol replacement with cardbuilder, they need to be enclosed in curly brackets as per other card symbols.

**Comment by melvinzhang** [comment]
So far all symbols are between curly brackets, I would expect energy to be denoted as {E}.

**Comment by ShawnieBoy** [comment]
>So far all symbols are between curly brackets, I would expect energy to be denoted as {E}.

I'd hope so, the example given on their website had me a bit concerned.

I've done a mock up of a way we could display energy counters in-game. Without adding more to the player avatar or panel, the left-most 'column' in the play area is reserved for the combat indicators, the bottom of this area could house the Energy counters. Having something permanent for Energy counters on the zone viewer panel would feel a bit of overkill to me, but there is space.

![energycountertally](https://cloud.githubusercontent.com/assets/2363180/18636284/1844d74e-7e80-11e6-8e98-6dc0fabbc708.png)

![energycounter2](https://cloud.githubusercontent.com/assets/2363180/18636695/a77a9d26-7e81-11e6-946b-2c361d913c65.png)

**Comment by ShawnieBoy** [comment]
I think the main difference between poison and energy counters, is that energy can be spent much like mana. In essence it would be much like having a mana-pool.

**Comment by lodici** [comment]
It would be interactive?

**Comment by ShawnieBoy** [comment]
Probably not being interactive, but at least feel more like a resource than just a value. The way energy functions is almost mana-lite, and I think if we can implement it, a mana pool would become an expansion of it.

**Comment by lodici** [comment]
Ok, I think I understand. Unlike the poison and shield damage counters, the energy counters [are used to pay the cost to activate abilities](http://mtgsalvation.gamepedia.com/Energy_counter). So showing a count in the space at the end of the zones seems reasonable. Presumably, the user prompt would then be used to ask the user how many counters to pay, etc.

**Comment by ShawnieBoy** [comment]
I don't think there are any prompts needed at the moment, all activated abilities would require having enough to spend, similar to how mana is currently used.

A couple of examples of gaining and spending energy.

![image](http://media.wizards.com/2016/bVvMNuiu2i_KLD/en_Glljicz8gT.png)
![image](http://media.wizards.com/2016/bVvMNuiu2i_KLD/en_9YWFIpP1Pe.png)

**Comment by ShawnieBoy** [comment]
Although there could well be an X energy counter ability in the next set.

**Comment by lodici** [comment]
Thanks for showing the sample cards. I vote for the second mockup - about time that space was used for something. It does seem an ideal location for a mana pool but in the meantime the energy pool seems like a good fit.

**Comment by melvinzhang** [comment]
I'd prefer the first mockup as Energy is more like lands, it is a resource. Putting it in the user panel doesn't seem consistent as it for card locations and number of cards currently. Having the panel be: Library, Hand, Graveyard, Exile, Energy feels inconsistent.

![Energy card](https://hydra-media.cursecdn.com/mtgsalvation.gamepedia.com/thumb/3/3a/KLD_Energy_Reserve.png/300px-KLD_Energy_Reserve.png?version=7685cfeb35ae42fba1ca2ed5ffa8640a)

Something else I just thought of would be an Energy card (see above) on the battlefield on the same level as the lands. With counters on it like how we show counters on permanents. The cons would be getting this confused as a permanent.

**Comment by melvinzhang** [comment]
> I'd hope so, the example given on their website had me a bit concerned. -- @ShawnieBoy 

I guess you mean the release notes? It is probably just the formatting for the website, for example "Aetherworks Marvel" has the oracle text: "T, Pay EEEEEE: ..." The tap symbol, mana symbols, etc are all written without the curly braces.

**Comment by lodici** [comment]
> Something else I just thought of would be an Energy card (see above) on the battlefield on the same level as the lands. With counters on it like how we show counters on permanents. The cons would be getting this confused as a permanent.

And scaling - potentially it could be scaled so small as to become unusable. I think it is clearer to have a separate area for this kind of non-card-specific info, the battlefield is complex enough.

**Comment by ShawnieBoy** [comment]
I've been considering Energy counters as essentially another mana type - something that wouldn't appear on the battlefield and be more abstract. Considering energy as mana would essentially be consdering a mana pool #752

**Comment by ShawnieBoy** [comment]
We'll need something in place soon, as Aether Revolt adds a bunch more Energy-releated cards, and there's no way to know how many you have.

**Comment by ShawnieBoy** [comment]
Also completely forgot about Experience counters which are also put on the player. From Commander 2015.

**Comment by lodici** [comment]
Posted in [forum by @jerichopumpkin](http://www.slightlymagic.net/forum/viewtopic.php?f=115&p=209446#p209437) -

> I've noticed that the new Energy mechanic is implemented alright (they are counters, after all), but there is no visual cue for the player to see hoew much energy he or the AI actually have. So I was wondering if it could be possible to improve the UI to show more relevant information.
> I'd like to suggest changing one of the icons in the player display (or better yet, the avatar image) to a button to enlarge a panel with those info.
> What do you think?

**Comment by ShawnieBoy** [comment]
I think having to interact with something to display information might not be the bast way - Although the Avatar image is getting a bit crowded showing Poison, Monarch and Damage Prevention and then adding Energy and Experience (plus anything new which sticks more things on the player)

**Comment by lodici** [comment]
How about increasing the height of the player panel slightly, say 20 pixels which then gives you a line to add the various missing values probably as an icon and value next to it.

**Comment by lodici** [comment]
Something like...
![1844d74e-7e80-11e6-8e98-6dc0fabbc708](https://cloud.githubusercontent.com/assets/2443519/22432549/25221922-e70d-11e6-877c-c19e602b3267.jpg)

**Comment by lodici** [comment]
For consistency, consider moving shield and poison counters...
![1844d74e-7e80-11e6-8e98-6dc0fabbc708](https://cloud.githubusercontent.com/assets/2443519/22433332/f19322b0-e70f-11e6-82fb-1eaf4866cfdd.jpg)

**Comment by ShawnieBoy** [comment]
Yeah - that looks good 👍

**Comment by lodici** [comment]
It should be fairly straightforward to implement assuming ``PlayerViewerInfo`` has all the totals, but please can you confirm all the counter types that need to be shown since I have lost track. :confused: Also any icon suggestions welcome.

**Comment by ShawnieBoy** [comment]
Poison counter, Energy counter and Experience counter. 😃
The icon for poison could be the skull and crossbones, but experience? No idea. Maybe even just the letters 'XP' could work.

**Comment by lodici** [comment]
![screenshot00569](https://cloud.githubusercontent.com/assets/2443519/22442597/dd881f4a-e733-11e6-821a-b1fe338813d5.jpg)
This was nice and simple which makes a change (looking at you deck stats!).

**Comment by ShawnieBoy** [comment]
Ooh, nice 👍 
Is it possible to make them only appear when they have a value?

**Comment by lodici** [comment]
I am not sure a blank space would look that good. You could fade-out/grayscale if zero (like the icons in the deck stats panel). Or hide the counters line completely and only reveal it when counters are present, which would mean dynamically changing the size of the side bar as a player panel increases/decreases in size so is a bit more involved.

**Comment by ShawnieBoy** [comment]
Yeah, see what you mean - What if they were right-aligned and the space beneath the avatar was used for something else? Wouldn't look so strange when they weren't there.

**Comment by lodici** [comment]
They might look better aligned to the  zones, true. Not sure what you would put under the avatar image, you could possibly increase the avatar size to fill the extra space below which means everything moves 20 pixels or so to the right. Alternatively, as mentioned in earlier posts you make use of the extra space to the right of the exile zone button, I reckon two rows of two columns would fit quite nicely.

**Comment by lodici** [comment]
After playing with this a few times - its even in the latest 1.81 release which I did not expect! :wink: - I am not sure I like it. It would be fine if there were enough counters to fill out the line but as it stands it feels lob-sided, unbalanced and clutters up the display with unnecessary information most of the time.

**Comment by lodici** [comment]
I think this makes better use of the space -
![screenshot from 2017-02-01 18 42 16](https://cloud.githubusercontent.com/assets/2443519/22520985/4c3bafee-e8ae-11e6-99d8-01457f9ccad2.png)

**Comment by lodici** [comment]
Here is an alternative layout (I have no particular preference)...
![screenshot00575](https://cloud.githubusercontent.com/assets/2443519/22546504/3df03608-e935-11e6-9447-d554c09e5d92.jpg)

**Comment by melvinzhang** [comment]
I prefer the icons on the left side, as they are more similar (game wise) to the life counter (also on the left) than they are to the number of cards icons.

**Comment by lodici** [comment]
If on the left then it would be more natural to swap the icon and value positions thus...
![screenshot00584](https://cloud.githubusercontent.com/assets/2443519/22739951/c25ee2c0-ee05-11e6-9375-60b2b604913c.jpg)
![screenshot00585](https://cloud.githubusercontent.com/assets/2443519/22739954/c629067e-ee05-11e6-9716-f86112c840df.jpg)

Not sure about the gap between the counters and zones when the counters are zero. It seems less jarring when on the right but that may be because I am used to it.

**Comment by lodici** [comment]
Will close this as it has been released, but please raise new issue if unhappy with current layout. I am still not totally convinced (see #1109).
