### ISSUE TITLE
Arachnogenesis

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#851]
name=Arachnogenesis
image=http://magiccards.info/scans/en/c15/32.jpg
image_updated=2016-02-29
value=2.500
rarity=R
type=Instant
cost={2}{G}
ability=Cast SN only during the declare attackers step and only if you've been attacked this step.
effect=Put a 1/2 green Spider creature tokens with reach onto the battlefield for each attacking creature.~Prevent all combat damage that would be dealt this turn by non-Spider creatures.
timing=token
oracle=Put X 1/2 green Spider creature tokens with reach onto the battlefield, where X is the number of creatures attacking you. Prevent all combat damage that would be dealt this turn by non-Spider creatures.

**Comment by melvinzhang** [comment]
@kelsioboy it may be useful to cast this when you are attacking as a kind of pseudo Fog.

**Comment by kelsioboy** [comment]
Cool, I had not thought of that, thank you melvin zhang.
