### ISSUE TITLE
Chasm Skulker

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#852]
name=Chasm Skulker
image=http://magiccards.info/scans/en/m15/46.jpg
value=4.000
rarity=R
type=Creature
subtype=Squid,Horror
cost={2}{U}
pt=1/1
ability=Whenever you draw a card, put a +1/+1 counter on SN.;\
        When SN dies, put a 1/1 blue Squid creature token with islandwalk onto the battlefield for each +1/+1 counter on it.
timing=main
oracle=Whenever you draw a card, put a +1/+1 counter on Chasm Skulker.\nWhen Chasm Skulker dies, put X 1/1 blue Squid creature tokens with islandwalk onto the battlefield, where X is the number of +1/+1 counters on Chasm Skulker.

**Comment by ShawnieBoy** [comment]
This is already implemented e7c4a2d0383da18242ad9681b825208a00ddf668
