### ISSUE TITLE
Chimney Imp

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#853]
name=Chimney Imp
image=http://magiccards.info/scans/en/mi/59.jpg
value=3.312
rarity=C
type=Creature
subtype=Imp
cost={4}{B}
pt=1/2
ability=Flying;\        
timing=main
requires_groovy_code
oracle=Flying\nWhen Chimney Imp dies, target opponent puts a card from his or her hand on top of his or her library.

[
    new ThisDiesTrigger() {
        @Override
        public MagicEvent executeTrigger(final MagicGame game, final MagicPermanent permanent, final MagicPermanent died) {
            return new MagicEvent(
                permanent,
                TARGET_OPPONENT,
                this,
                "Target opponent\$ puts a card from his or her hand on top of his or her library."
            );
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            event.processTargetPlayer(game, {
                game.addEvent(new MagicReturnCardEvent(event.getSource(), it));
            });
        }
    }
]

**Comment by melvinzhang** [comment]
Included this card for next release. Thanks!

**Comment by ShawnieBoy** [comment]
A real good find 😀
