### ISSUE TITLE
Chimney Imp groove

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#854]
[
    new ThisDiesTrigger() {
        @Override
        public MagicEvent executeTrigger(final MagicGame game, final MagicPermanent permanent, final MagicPermanent died) {
            return new MagicEvent(
                permanent,
                TARGET_OPPONENT,
                this,
                "Target opponent\$ puts a card from his or her hand on top of his or her library."
            );
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            event.processTargetPlayer(game, {
                game.addEvent(new MagicReturnCardEvent(event.getSource(), it));
            });
        }
    }
]

**Comment by melvinzhang** [comment]
moved groovy code into same issue as card script.
