### ISSUE TITLE
Confront the Unknown

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#855]
name=Confront the Unknown
image=http://magiccards.info/scans/en/soi/198.jpg
value=2.500
rarity=C
type=Instant
cost={G}
ability=When you cast SN, investigate.
effect=Target creature gets +1/+1 until end of turn for each Clue you control.
timing=removal
oracle=Investigate, then target creature gets +1/+1 until end of turn for each Clue you control.

**Comment by ShawnieBoy** [comment]
This would function better with groovy code, mainly for getting the investigation to occur before tallying the Clues. Having Investigate trigger before the spell resolves would cause it not to be countered if the spell is.

**Comment by melvinzhang** [comment]
Agree, there should not be an additional trigger for this card. Unfortunately it can only be done in groovy code for now. @kelsioboy feel free to reopen this issue when you submit the groovy code for this.
