### ISSUE TITLE
Diseased Vermin

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#856]
name=Diseased Vermin
image=http://magiccards.info/scans/en/ai/5.jpg
value=3.303
rarity=U
type=Creature
subtype=Rat
cost={2}{B}
pt=1/1
ability=Whenever SN deals combat damage to a player, put an infection counter on it.;\
        At the beginning of your upkeep, SN deals X damage to target opponent, where X is the number of infection counters on it.
timing=main
oracle=Whenever Diseased Vermin deals combat damage to a player, put an infection counter on it.\nAt the beginning of your upkeep, Diseased Vermin deals X damage to target opponent previously dealt damage by it, where X is the number of infection counters on it.

**Comment by ShawnieBoy** [comment]
If your Diseased Vermin is controlled temporarily by your opponent (eg. Act of Treason) and it gets an infection counter after dealing damage to you, it shouldn't then deal damage to that opponent when control returns to you until you deal damage to them with it.

**Comment by melvinzhang** [comment]
Not possible to track whether a player was dealt damage previously by a permament.
