### ISSUE TITLE
Eater of the Dead

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#857]
name=Eater of the Dead
image=http://magiccards.info/scans/en/med/67.jpg
value=3.400
rarity=U
type=Creature
subtype=Horror
cost={4}{B}
pt=3/4
ability={0}, {Q}: Exile target creature card from a graveyard.
timing=main
oracle={0}: If Eater of the Dead is tapped, exile target creature card from a graveyard and untap Eater of the Dead.

**Comment by ShawnieBoy** [comment]
I can see what you're trying here, but the untap here is an effect, not a cost. It can be activated while untapped as many times as you want, it only checks the tapped status on resolution. Burning-Tree Shaman, this and a couple of spirit loops would give infinite life with no cards in a graveyard.

**Comment by kelsioboy** [comment]
Got Shawnie Boy, thank you.
