### ISSUE TITLE
Edgewalker

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#858]
name=Edgewalker
image=http://magiccards.info/scans/en/sc/137.jpg
value=4.213
rarity=U
type=Creature
subtype=Human,Cleric
cost={1}{W}{B}
pt=2/2
timing=main
requires_groovy_code
oracle=Cleric spells you cast cost {W}{B} less to cast. This effect reduces only the amount of colored mana you pay.

[   
    new MagicStatic(MagicLayer.CostReduction) {
        @Override
        public MagicManaCost reduceCost(final MagicPermanent source, final MagicCard card, final MagicManaCost cost) {
            if (card.hasType(MagicType.Creature) && card.hasSubType(MagicSubType.Cleric) && source.isFriend(card)) {
                return cost.reduce(MagicCostManaType.Black, 1);
            } else {
                return cost;
            }
        }
    },
    new MagicStatic(MagicLayer.CostReduction) {
        @Override
        public MagicManaCost reduceCost(final MagicPermanent source, final MagicCard card, final MagicManaCost cost) {
            if (card.hasType(MagicType.Creature) && card.hasSubType(MagicSubType.Cleric) && source.isFriend(card)) {
                return cost.reduce(MagicCostManaType.White, 1);
            } else {
                return cost;

            }
        }
    }
]

**Comment by ShawnieBoy** [comment]
This and #869 both look good to me - was there a particular reason these weren't included in the first pass of cost-reduction abilities @melvinzhang? They look mechanically sound, but would they return one reduction over the other? e.g. return a cost with {B} reduced or {W} reduced but not both?

**Comment by ShawnieBoy** [comment]
Having multiple returns with the cost is problematic - reducing the cost in serial is a better way.
```
[
    new MagicStatic(MagicLayer.CostReduction) {
        @Override
        public MagicManaCost reduceCost(final MagicPermanent source, final MagicCard card, final MagicManaCost cost) {
            if (card.hasSubType(MagicSubType.Cleric) && source.isFriend(card)) {
                final MagicManaCost reducedFirst = cost.reduce(MagicCostManaType.Black, 1);
                final MagicManaCost reducedTotal = reducedFirst.reduce(MagicCostManaType.White, 1);
                return reducedTotal;
            } else {
                return cost;
            }
        }
    }
]

**Comment by melvinzhang** [comment]
Colored reduction doesn't work, as implemented above only the cost {B} is reduced but the cost {U/B}, {W/B}, etc are not affected. The key problem is there is more than one mana cost that include {B}. Moreover, when both {U/B} and {B/R} are both present, it is not clear which one the player wants to reduce.
