### ISSUE TITLE
Edgewalker groovy

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#859]
[   
    new MagicStatic(MagicLayer.CostReduction) {
        @Override
        public MagicManaCost reduceCost(final MagicPermanent source, final MagicCard card, final MagicManaCost cost) {
            if (card.hasType(MagicType.Creature) && card.hasSubType(MagicSubType.Cleric) && source.isFriend(card)) {
                return cost.reduce(MagicCostManaType.Black, 1);
            } else {
                return cost;
            }
        }
    },
    new MagicStatic(MagicLayer.CostReduction) {
        @Override
        public MagicManaCost reduceCost(final MagicPermanent source, final MagicCard card, final MagicManaCost cost) {
            if (card.hasType(MagicType.Creature) && card.hasSubType(MagicSubType.Cleric) && source.isFriend(card)) {
                return cost.reduce(MagicCostManaType.White, 1);
            } else {
                return cost;

            }
        }
    }
]

**Comment by melvinzhang** [comment]
moved to issue with card script
