### ISSUE TITLE
Instill Energy

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#860]
name=Instill Energy
image=http://magiccards.info/scans/en/me4/157.jpg
value=4.395
rarity=U
type=Enchantment
subtype=Aura
cost={G}
ability=Enchant creature;\
        Enchanted creature has haste.;\
        {0}: Untap enchanted creature. Activate this ability only during your turn. Activate this ability only once each turn.
timing=aura
enchant=haste,pos creature
oracle=Enchant creature\nEnchanted creature can attack as though it had haste.\n{0}: Untap enchanted creature. Activate this ability only during your turn and only once each turn.

**Comment by ShawnieBoy** [comment]
This doesn't give haste. In a way it's the opposite of 'can attack as though it didn't have defender'. Cards that check for the abilities of the enchanted creature shouldn't find Haste. e.g Odric, Lunarch Marshal

**Comment by kelsioboy** [comment]
Really hear a mistake on my part in this detail, what happened was I when I made this script I was using an image I downloaded on the net and this image the letter of the effect of hurry. More and I checked this with every reason, thank you.
