### ISSUE TITLE
Ma Chao, Western Warrior

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#861]
name=Ma Chao, Western Warrior
image=http://magiccards.info/scans/en/p3k/116.jpg
value=3.816
rarity=R
type=Legendary,Creature
subtype=Human,Soldier,Warrior
cost={3}{R}{R}
pt=3/3
ability=Horsemanship;\
        SN can't be blocked as long as it's attacking alone.
timing=main
oracle=Horsemanship\nWhenever Ma Chao, Western Warrior attacks alone, it can't be blocked this combat.

**Comment by ShawnieBoy** [comment]
Nice rephrasing. I'll have a look at why this isn't working as oracle text 'MagicAbility.AnyAttacksAloneEffect` should catch this. Or need a `SelfAttacksAlone` ability added.

**Comment by ShawnieBoy** [comment]
Very strange, Lunk Errant, Reckless Ogre, and Rogue Kavu all 'self target', but Ma Chao doesn't like a `whenever sn` target.

**Comment by melvinzhang** [comment]
The rephrasing makes it into a static ability instead of a triggered ability. The problem is "SN can't be blocked this turn" is a valid effect but not "this combat".  How about rephrasing it as "SN can't be blocked this turn"? This is equivalent since we don't support multiple combat phases.

**Comment by ShawnieBoy** [comment]
Would 'until end of combat' be better? This also involves Yuan Shao's Infantry. Although we don't yet support multiple phases, it may appear in the future.

**Comment by melvinzhang** [comment]
Why is 'until end of combat' better than 'this combat'? In any case, both are not supported.

**Comment by melvinzhang** [comment]
Thinking of the difference between 'until end of combat' and 'this combat' made by think of another method "as long as it is combat". This can be done in groovy code using the MagicStatic.AsLongAsCond.
