### ISSUE TITLE
Mistform Ultimus

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#862]
name=Mistform Ultimus
image=http://magiccards.info/scans/en/tsts/26.jpg
value=3.391
rarity=R
type=Legendary,Creature
subtype=Illusion
cost={3}{U}
pt=3/3
ability=Changeling
timing=main
oracle=Mistform Ultimus is every creature type.

**Comment by ShawnieBoy** [comment]
Mistform Ultimus always has all creature types even if the ability is removed, the changeling ability can be removed.

**Comment by kelsioboy** [comment]
ok.

**Comment by melvinzhang** [comment]
The solution is to give it the same implementation as Changeling. See 7172d6efe789d
