### ISSUE TITLE
Mox Diamond

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#863]
name=Mox Diamond
image=http://magiccards.info/scans/en/tpr/228.jpg
image_updated=2015-11-14
value=2.500
rarity=M
type=Artifact
cost={0}
ability=When SN enters the battlefield, you may discard a land card. If you don't, sacrifice SN.;\
        {T}: Add one mana of any color to your mana pool.
timing=artifact
oracle=If Mox Diamond would enter the battlefield, you may discard a land card instead. If you do, put Mox Diamond onto the battlefield. If you don't, put it into its owner's graveyard.\n{T}: Add one mana of any color to your mana pool.

**Comment by ShawnieBoy** [comment]
This ability should be a replacement effect - it doesn't enter the battlefield or become sacrificed if a land isn't discarded. It either enters the battlefield or goes from the hand to the graveyard. Have a look at Sheltered Valley for an enters the battlefield replacement effect.

Cards can also be submitted through [Project Firemind - Workspace](https://www.firemind.ch/workspace)

**Comment by kelsioboy** [comment]
It would be like this ?

name=Mox Diamond
image=http://magiccards.info/scans/en/tpr/228.jpg
image_updated=2015-11-14
value=2.500
rarity=M
type=Artifact
cost={0}
ability=When you cast SN, you may discard a land card. If you don't, Counter SN.;\
        {T}: Add one mana of any color to your mana pool.
timing=artifact
oracle=If Mox Diamond would enter the battlefield, you may discard a land card instead. If you do, put Mox Diamond onto the battlefield. If you don't, put it into its owner's graveyard.\n{T}: Add one mana of any color to your mana pool.

**Comment by ShawnieBoy** [comment]
It would be more like this:
```
[
    new EntersBattlefieldTrigger(MagicTrigger.REPLACEMENT) {
        @Override
        public MagicEvent executeTrigger(final MagicGame game,final MagicPermanent permanent,final MagicPayedCost payedCost) {
           return new MagicEvent(
                permanent,
                new MagicMayChoice(),
                this,
                "PN may\$ discard a land card. If a he or she does not, put SN into its owner's graveyard."
            );
        }
        @Override
         public void executeEvent(final MagicGame game, final MagicEvent event) {
            final MagicEvent costEvent = new MagicDiscardChosenEvent(event.getSource(), MagicTargetChoice.LAND_CARD_FROM_HAND);
            if (event.isYes() && costEvent.isSatisfied()) {
                game.addEvent(costEvent);
            } else {
                game.doAction(RemoveFromPlayAction.NoUpdate(event.getPermanent(), MagicLocationType.Graveyard);
            }
        }
    }
]
```
However it should still trigger for a 'card put into the graveyard from anywhere' - The replacement effect basically occurs before triggers, so it's technically on the battlefield before the choice to discard is made. The problem is getting it into the graveyard in the correct way. Lands don't use the stack, so it either exists in the hand or on the battlefield. Going from hand -> graveyard should not trigger a discard, likewise a battlefield -> graveyard shouldn't trigger 'dies' or 'enter the graveyard from the battlefield', but _should_ trigger 'enter the graveyard from anywhere'

**Comment by kelsioboy** [comment]
:+1:

**Comment by ShawnieBoy** [comment]
Don't know why I started talking about Land and the stack - Must have been thinking of Lotus Vale - they were both around at the same time and have similar wording. 😕

**Comment by melvinzhang** [comment]
@ShawnieBoy as you are returning an event from the trigger, this new event can only run after PlayCardFromStackAction finishes, which means it would cause "come into play" trigger to fire. The correct method is to use MagicSpellCardEvent like Clone and friends.

**Comment by melvinzhang** [comment]
The way to think about the two is like this, if it is something that adds on to a play event, say tapped into play. Then a trigger with with no event and the action inside executeTrigger is ok as it is putting into play then do action.

If a choice is needed and if affects how the permanent comes into play (like Clone) or whether it comes into play at all, then it  should be via MagicSpellCardEvent

**Comment by melvinzhang** [comment]
I've did up Mox Diamond as an illustration of what I mean by using MagicSpellCardEvent, see 6467659f3500ea

**Comment by ShawnieBoy** [comment]
This wasn't meant as an actual card - it was just an example for exploring ways to get the card to work. Wouldn't a spellcardevent not trigger if the land was flickered or put onto the battlefield in a non-standard way. Libarary->battlefield, graveyard->battlefield

**Comment by melvinzhang** [comment]
It should work for other ways of getting onto the battlefield. Please create an issue if you find a specific example where it fails.
