### ISSUE TITLE
Nature's Chosen

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#864]
name=Nature's Chosen
image=http://magiccards.info/scans/en/ai/81.jpg
value=3.846
rarity=U
type=Enchantment
subtype=Aura
cost={G}
ability=Enchant creature you control;\
        {0}: Untap enchanted creature. Activate this ability only during your turn. Activate this ability only once each turn.;\
        As long as enchanted creature is white, enchanted creature has "{0}, {T}: Untap target artifact, creature, or land. Activate this ability only once each turn." 
timing=aura
enchant=default,creature you control
oracle=Enchant creature you control\n{0}: Untap enchanted creature. Activate this ability only during your turn and only once each turn.\nTap enchanted creature: Untap target artifact, creature, or land. Activate this ability only if enchanted creature is white and is untapped and only once each turn.

**Comment by ShawnieBoy** [comment]
The abilities should remain on on the enchantment - there are situations when the aura could end up on a creature you no longer control, but you should still be able to activate abilities which use the creature as a cost.

**Comment by kelsioboy** [comment]
ok.
