### ISSUE TITLE
Ongoing Investigation

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#865]
name=Ongoing Investigation
image=http://magiccards.info/scans/en/soi/77.jpg
value=2.500
rarity=U
type=Enchantment
cost={1}{U}
ability=Creatures you control have "Whenever SN deals combat damage to a player, investigate.";\
        {1}{G}, Exile a creature card from your graveyard: You gain 2 life.~and investigate.
timing=enchantment
oracle=Whenever one or more creatures you control deal combat damage to a player, investigate.\n{1}{G}, Exile a creature card from your graveyard: Investigate. You gain 2 life.

**Comment by ShawnieBoy** [comment]
The total number of times you investigate isn't linked to the amount of creatures that deal combat damage. If three creatures deal combat damage to an opponent, you Investigate once.

**Comment by kelsioboy** [comment]
Compreendi Shawnie obrigado pela explicação. :)

**Comment by kelsioboy** [comment]
Shawnie realized thanks for the explanation.

**Comment by kelsioboy** [comment]
I understand Shawnie thanks for your explanation.

**Comment by melvinzhang** [comment]
Closing this as when-one-or-more is not supported.
