### ISSUE TITLE
Orbs of Warding

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#866]
name=Orbs of Warding
image=http://magiccards.info/scans/en/ori/234.jpg
image_updated=2015-11-05
value=2.500
rarity=R
type=Artifact
cost={5}
timing=artifact
requires_groovy_code=Spirit of the Hearth;Orbs of Warding
oracle=You have hexproof.\nIf a creature would deal damage to you, prevent 1 of that damage.

[
    
    new PreventDamageTrigger() {
        @Override
        public MagicEvent executeTrigger(final MagicGame game,final MagicPermanent permanent,final MagicDamage damage) {
            if (permanent.isController(damage.getTarget()) && damage.getSource().hasType(MagicType.Creature)) {
                // Prevention effect.
                damage.prevent(1);
            }
            return MagicEvent.NONE;
        }
    }
]

**Comment by ShawnieBoy** [comment]
This looks good to me 👍

**Comment by melvinzhang** [comment]
@kelsioboy nice clean implementation, @ShawnieBoy thanks for reviewing Included in next release via b4b0cc86f2b4a7036
