### ISSUE TITLE
Orbs of Warding groovy

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#867]
[
    
    new PreventDamageTrigger() {
        @Override
        public MagicEvent executeTrigger(final MagicGame game,final MagicPermanent permanent,final MagicDamage damage) {
            if (permanent.isController(damage.getTarget()) && damage.getSource().hasType(MagicType.Creature)) {
                // Prevention effect.
                damage.prevent(1);
            }
            return MagicEvent.NONE;
        }
    }
]

**Comment by melvinzhang** [comment]
moved to issue with card script
