### ISSUE TITLE
Ragemonger

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#869]
name=Ragemonger
image=http://magiccards.info/scans/en/bng/153.jpg
value=3.811
rarity=U
type=Creature
subtype=Minotaur,Shaman
cost={1}{B}{R}
pt=2/3
timing=main
requires_groovy_code
oracle=Minotaur spells you cast cost {B}{R} less to cast. This effect reduces only the amount of colored mana you pay.

[   
    new MagicStatic(MagicLayer.CostReduction) {
        @Override
        public MagicManaCost reduceCost(final MagicPermanent source, final MagicCard card, final MagicManaCost cost) {
            if (card.hasType(MagicType.Creature) && card.hasSubType(MagicSubType.Minotaur) && source.isFriend(card)) {
                return cost.reduce(MagicCostManaType.Black, 1);
            } else {
                return cost;
            }
        }
    },
    new MagicStatic(MagicLayer.CostReduction) {
        @Override
        public MagicManaCost reduceCost(final MagicPermanent source, final MagicCard card, final MagicManaCost cost) {
            if (card.hasType(MagicType.Creature) && card.hasSubType(MagicSubType.Minotaur) && source.isFriend(card)) {
                return cost.reduce(MagicCostManaType.Red, 1);
            } else {
                return cost;

            }
        }
    }
]

**Comment by ShawnieBoy** [comment]
```
[
    new MagicStatic(MagicLayer.CostReduction) {
        @Override
        public MagicManaCost reduceCost(final MagicPermanent source, final MagicCard card, final MagicManaCost cost) {
            if (card.hasSubType(MagicSubType.Minotaur) && source.isFriend(card)) {
                final MagicManaCost reducedFirst = cost.reduce(MagicCostManaType.Black, 1);
                final MagicManaCost reducedTotal = reducedFirst.reduce(MagicCostManaType.Red, 1);
                return reducedTotal;
            } else {
                return cost;
            }
        }
    }
]
```

**Comment by melvinzhang** [comment]
Colored reduction is not supported as there is more than one cost that includes a particular color. i.e. {B}, {W/B}, {U/B}, {B/R}, {B/G} all include {B}.

**Comment by kelsioboy** [comment]
Yes, I had already seen it with other cards. But I thought it was this way and sent to you guys test.
