### ISSUE TITLE
error when downloading card images on Mac

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#87]
Bog Wraith @ http://www.slightlymagic.net/forum/viewtopic.php?f=82&t=16836&p=174492#p174492 reported:

I am using the Mac version and when I tried to download the card images, I would get around 600 card images then I'd get an error saying that I should look at the console for details as to what went wrong. Well I'm not sure where or what the console is so I tried it again & the same thing happened.

**Comment by lodici** [comment]
see #88.
