### ISSUE TITLE
Rooftop Storm

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#872]
name=Rooftop Storm
image=http://magiccards.info/scans/en/isd/71.jpg
value=3.877
rarity=R
type=Enchantment
cost={5}{U}
timing=enchantment
requires_groovy_code=Rooftop Storm;Rooftop Storm 2
oracle=You may pay {0} rather than pay the mana cost for Zombie creature spells you cast.

**Comment by kelsioboy** [comment]
I did two groovys because my limitations.

**Comment by melvinzhang** [comment]
[
    new MagicStatic(MagicLayer.CostReduction) {
        @Override
        public MagicManaCost reduceCost(final MagicPermanent source, final MagicCard card, final MagicManaCost cost) {
            if (card.hasType(MagicType.Creature) && card.hasSubType(MagicSubType.Zombie) && source.isFriend(card)) {
                return cost.reduce(16);
            } else {
                return cost;
            }
        }
    },
    new MagicStatic(MagicLayer.CostReduction) {
        @Override
        public MagicManaCost reduceCost(final MagicPermanent source, final MagicCard card, final MagicManaCost cost) {
            if (card.hasType(MagicType.Creature) && card.hasSubType(MagicSubType.Zombie) && source.isFriend(card)) {
                return cost.reduce(MagicCostManaType.Black, 16);
            } else {
                return cost;
            }
        }
    },
    new MagicStatic(MagicLayer.CostReduction) {
        @Override
        public MagicManaCost reduceCost(final MagicPermanent source, final MagicCard card, final MagicManaCost cost) {
            if (card.hasType(MagicType.Creature) && card.hasSubType(MagicSubType.Zombie) && source.isFriend(card)) {
                return cost.reduce(MagicCostManaType.Blue, 16);
            } else {
                return cost;

            }
        }
    }
]
[
    new MagicStatic(MagicLayer.CostReduction) {
        @Override
        public MagicManaCost reduceCost(final MagicPermanent source, final MagicCard card, final MagicManaCost cost) {
            if (card.hasType(MagicType.Creature) && card.hasSubType(MagicSubType.Zombie) && source.isFriend(card)) {
                return cost.reduce(MagicCostManaType.Red, 16);
            } else {
                return cost;
            }
        }
    },
    new MagicStatic(MagicLayer.CostReduction) {
        @Override
        public MagicManaCost reduceCost(final MagicPermanent source, final MagicCard card, final MagicManaCost cost) {
            if (card.hasType(MagicType.Creature) && card.hasSubType(MagicSubType.Zombie) && source.isFriend(card)) {
                return cost.reduce(MagicCostManaType.Green, 16);
            } else {
                return cost;
            }
        }
    },
    new MagicStatic(MagicLayer.CostReduction) {
        @Override
        public MagicManaCost reduceCost(final MagicPermanent source, final MagicCard card, final MagicManaCost cost) {
            if (card.hasType(MagicType.Creature) && card.hasSubType(MagicSubType.Zombie) && source.isFriend(card)) {
                return cost.reduce(MagicCostManaType.White, 16);
            } else {
                return cost;

            }
        }
    }
]

**Comment by ShawnieBoy** [comment]
This should be presented as an optional alternative cost - however we're not yet able to add abilities to cards, only permanents
