### ISSUE TITLE
Rooftop Storm groovy

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#873]
[
    new MagicStatic(MagicLayer.CostReduction) {
        @Override
        public MagicManaCost reduceCost(final MagicPermanent source, final MagicCard card, final MagicManaCost cost) {
            if (card.hasType(MagicType.Creature) && card.hasSubType(MagicSubType.Zombie) && source.isFriend(card)) {
                return cost.reduce(16);
            } else {
                return cost;
            }
        }
    },
    new MagicStatic(MagicLayer.CostReduction) {
        @Override
        public MagicManaCost reduceCost(final MagicPermanent source, final MagicCard card, final MagicManaCost cost) {
            if (card.hasType(MagicType.Creature) && card.hasSubType(MagicSubType.Zombie) && source.isFriend(card)) {
                return cost.reduce(MagicCostManaType.Black, 16);
            } else {
                return cost;
            }
        }
    },
    new MagicStatic(MagicLayer.CostReduction) {
        @Override
        public MagicManaCost reduceCost(final MagicPermanent source, final MagicCard card, final MagicManaCost cost) {
            if (card.hasType(MagicType.Creature) && card.hasSubType(MagicSubType.Zombie) && source.isFriend(card)) {
                return cost.reduce(MagicCostManaType.Blue, 16);
            } else {
                return cost;

            }
        }
    }
]

**Comment by melvinzhang** [comment]
moved to issue with card script.
