### ISSUE TITLE
Rooftop Storm 2 groovy

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#874]
[
    new MagicStatic(MagicLayer.CostReduction) {
        @Override
        public MagicManaCost reduceCost(final MagicPermanent source, final MagicCard card, final MagicManaCost cost) {
            if (card.hasType(MagicType.Creature) && card.hasSubType(MagicSubType.Zombie) && source.isFriend(card)) {
                return cost.reduce(MagicCostManaType.Red, 16);
            } else {
                return cost;
            }
        }
    },
    new MagicStatic(MagicLayer.CostReduction) {
        @Override
        public MagicManaCost reduceCost(final MagicPermanent source, final MagicCard card, final MagicManaCost cost) {
            if (card.hasType(MagicType.Creature) && card.hasSubType(MagicSubType.Zombie) && source.isFriend(card)) {
                return cost.reduce(MagicCostManaType.Green, 16);
            } else {
                return cost;
            }
        }
    },
    new MagicStatic(MagicLayer.CostReduction) {
        @Override
        public MagicManaCost reduceCost(final MagicPermanent source, final MagicCard card, final MagicManaCost cost) {
            if (card.hasType(MagicType.Creature) && card.hasSubType(MagicSubType.Zombie) && source.isFriend(card)) {
                return cost.reduce(MagicCostManaType.White, 16);
            } else {
                return cost;

            }
        }
    }
]

**Comment by melvinzhang** [comment]
moved to issued with card script.
