### ISSUE TITLE
Werewolf of Ancient Hunger

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#876]
name=Werewolf of Ancient Hunger
image=http://magiccards.info/scans/en/soi/225b.jpg
value=2.500
rarity=R
type=Creature
subtype=Werewolf
color=g
pt=*/*
ability=Vigilance, trample;\
        At the beginning of each upkeep, if a player cast two or more spells last turn, transform SN.
transform=Sage of Ancient Lore
timing=main
hidden
requires_groovy_code
oracle=Vigilance, trample\nWerewolf of Ancient Hunger's power and toughness are each equal to the total number of cards in all players' hands.\nAt the beginning of each upkeep, if a player cast two or more spells last turn, transform Werewolf of Ancient Hunger.

[
    new MagicCDA() {
        @Override
        public void modPowerToughness(final MagicGame game, final MagicPlayer player, final MagicPermanent permanent, final MagicPowerToughness pt) {
            final int amount = player.getHandSize() + player.getOpponent().getHandSize();
            pt.set(amount,amount);
        }
    }
]

**Comment by melvinzhang** [comment]
Good fine! Included in next release. As this is the same groovy code as Multani the groovy file can be left out by using `requires_groovy_code=Multani, Maro_Sorcerer`
