### ISSUE TITLE
Werewolf of Ancient Hunger groovy

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#877]
[
    new MagicCDA() {
        @Override
        public void modPowerToughness(final MagicGame game, final MagicPlayer player, final MagicPermanent permanent, final MagicPowerToughness pt) {
            final int amount = player.getHandSize() + player.getOpponent().getHandSize();
            pt.set(amount,amount);
        }
    }
]

**Comment by melvinzhang** [comment]
moved groovy to #876 @kelsioboy please submit one issue per card, include the groovy on the same issue.

**Comment by lodici** [comment]
Are these issues or submissions? If submissions, why using GitHub issues? Having to trawl through these is a pain. Can they be tagged with a label so they can be excluded from the list if required.

**Comment by melvinzhang** [comment]
They are submissions of new cards. I asked kelsioboy to create issues to allow for feedback on the submissions. I've added the label "card" to these issues to make them easier to filter out.

**Comment by lodici** [comment]
Thanks, but it would be better to use a distinct tag ("submission"?) since card would also filter out UI related issues as well.

**Comment by melvinzhang** [comment]
Ah, good point. I've changed the tag to "new card"

**Comment by lodici** [comment]
Perfect, thanks.

**Comment by ShawnieBoy** [comment]
>They are submissions of new cards. I asked kelsioboy to create issues to allow for feedback on the submissions. I've added the label "card" to these issues to make them easier to filter out.

Ahh I see - In that case I don't feel so bad for seemingly complaining about them all 😨
