### ISSUE TITLE
Salt Road Ambushers

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#878]
name=Salt Road Ambushers
image=http://magiccards.info/scans/en/dtk/198.jpg
value=2.500
rarity=U
type=Creature
subtype=Hound,Warrior
cost={3}{G}
pt=3/3
ability=Whenever another creature you control is turned face up, put two +1/+1 counters on RN.;\
        Megamorph {3}{G}{G}
timing=main
oracle=Whenever another permanent you control is turned face up, if it's a creature, put two +1/+1 counters on it.\nMegamorph {3}{G}{G}

**Comment by ShawnieBoy** [comment]
This has a similar issue to #879 it would need to check before adding a counter.
