### ISSUE TITLE
Trail of Mystery

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#879]
name=Trail of Mystery
image=http://magiccards.info/scans/en/ktk/154.jpg
value=2.500
rarity=R
type=Enchantment
cost={1}{G}
ability=Whenever a face-down creature enters the battlefield under your control, you may search your library for a basic land card, reveal it, put it into your hand, then shuffle your library.;\
        Whenever a creature you control is turned face up, that creature gets +2/+2 until end of turn.
timing=enchantment
oracle=Whenever a face-down creature enters the battlefield under your control, you may search your library for a basic land card, reveal it, put it into your hand, then shuffle your library.\nWhenever a permanent you control is turned face up, if it's a creature, it gets +2/+2 until end of turn.

**Comment by ShawnieBoy** [comment]
I'll have to have a look at the trigger for this - the reason it states `permanent you control is turned face up` is that the face down side may not be a creature, even if the other side is, or vice versa. The trigger in the script would only be checking the face that is currently seen, if a non-creature became a creature it should get the +2/+2.
