### ISSUE TITLE
download errors should show error to user instead of asking user to check the console

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#88]
On Mac, the console is not available. Should either ask the user to check a log file or show the error in a text box which the user can copy and paste into a report.

**Comment by lodici** [comment]
Ok, I will look into a non-fatal error dialog with copiable text. Pesky Mac users. :camel:

**Comment by lodici** [comment]
![screenshot00053](https://cloud.githubusercontent.com/assets/2443519/6648858/2843ee78-c9d7-11e4-9c99-48400f10875f.png)
