### ISSUE TITLE
Valeron Wardens

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#881]
name=Valeron Wardens
image=http://magiccards.info/scans/en/ori/203.jpg
image_updated=2015-11-05
value=2.500
rarity=U
type=Creature
subtype=Human,Monk
cost={2}{G}
pt=1/3
ability=Renown 2;\
        Creatures you control have "When SN becomes renowned, draw a card."
timing=main
oracle=Renown 2\nWhenever a creature you control becomes renowned, draw a card.

**Comment by ShawnieBoy** [comment]
This doesn't give other creatures abilities - it triggers, and is the source of, the draw. A BecomesStateTrigger in groovy will work. There are no current examples for this, but looking at the java should help [BecomesStateTrigger](https://github.com/magarena/magarena/blob/8966a4dd49ab36f91da5bb874b83498ac1016cad/src/magic/model/trigger/BecomesStateTrigger.java)

**Comment by melvinzhang** [comment]
@kelsioboy I've added the groovy code for this card, do take a look at https://github.com/magarena/magarena/commit/5105f410dac08b5e5aeb13265112c5dbbb974b1c
