### ISSUE TITLE
Creature with Blazing Torch sacrifices itself to do damage instead of sacrificing Blazing Torch

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#882]
problematic script is the following ability:
`Equipped creature has "{T}, Sacrifice SN: SN deals 2 damage to target creature or player."`
This is equivalent to `{T}, Sacrifice this creature: This creature deals 2 damage to target creature or player.`

**Comment by ShawnieBoy** [comment]
This is a scriptbuilder issue - It replaces instances of a card's own name with SN. It will be difficult for it to determine context in this way.

**Comment by melvinzhang** [comment]
Yes, it is too messy, script-builder should be simple and always replace the name with SN. The problem is I did not check through before adding the generated script.

**Comment by ShawnieBoy** [comment]
It's very easily missed - Although does make me think about using the card name instead of SN - matches oracle closer then as well. Could even use the oracle value instead of duplicating text for ability.

**Comment by lodici** [comment]
> Could even use the oracle value instead of duplicating text for ability.

I wondered about that too. I am guessing that it would be an onerous task extracting the generic ability text at runtime.  For example, in the following script, a parser would need to identify the card name from the oracle to get the equivalent "SN" in the ability text. Multiply by 15,000 (with more complicated text) and it might affect loading times. Would be cool though.

```
name=Keeper of Kookus
image=http://magiccards.info/scans/en/vi/85.jpg
value=3.128
rarity=C
type=Creature
subtype=Goblin
cost={R}
pt=1/1
ability={R}: SN gains protection from red until end of turn.
timing=main
oracle={R}: Keeper of Kookus gains protection from red until end of turn.
```
