### ISSUE TITLE
Kaladesh Image Change

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#883]
If magiccards.info isn't updated to include Kaladesh by the time of 1.7 release, an image reparse of the set will be needed.

**Comment by melvinzhang** [comment]
Thanks for creating this so that we don't miss it out. Release is in a couple of days, so most likely will have to refer to image gallery links.

**Comment by ShawnieBoy** [comment]
I thought it would most likely be the case. Shame for those using crops.
