### ISSUE TITLE
Nissa, Voice of Zendikar

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#885]
name=Nissa, Voice of Zendikar
image=http://magiccards.info/scans/en/ogw/138.jpg
image_updated=2016-02-29
value=2.500
rarity=M
type=Planeswalker
subtype=Nissa
cost={1}{G}{G}
loyalty=3
ability=+1: Put a 0/1 green Plant creature token onto the battlefield.;\
        −2: Put a +1/+1 counter on each creature you control.;\
        −7: You gain 1 life for each land you control.~and draw 1 card for each land you control.
timing=main
oracle=+1: Put a 0/1 green Plant creature token onto the battlefield.\n−2: Put a +1/+1 counter on each creature you control.\n−7: You gain X life and draw X cards, where X is the number of lands you control.

**Comment by kelsioboy** [comment]
replace the "X" for an alternative value without using groovy. I think the result is the same, the more I leave the discretion of you.

**Comment by ShawnieBoy** [comment]
The life gain in this version would be in several amounts eg: Seven Lands would gain 1 life 7 times. It should be 7 life.

Effects that rely or look at life gain should look at the totals, not lots of 1 amounts.  Ajani's Pridemate should only trigger once, not for each land you control.

**Comment by kelsioboy** [comment]
ok

**Comment by melvinzhang** [comment]
@kelsioboy good find, using the "for each" replacement does exactly the same thing and avoids the use of groovy code. It does the same thing as the original gain X, there is some misconception about for each. I added this sometime back in Sept 15 with 4e314c03fca4a3951bf30

@ShawnieBoy "gain life ... for each" is a single gain life event not multiple, it is functionally equivalent to "gain X life where X is" see https://boardgames.stackexchange.com/questions/18053/how-does-the-wording-for-each-work
