### ISSUE TITLE
Tezzeret, Agent of Bolas

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#886]
name=Tezzeret, Agent of Bolas
image=http://magiccards.info/scans/en/mbs/97.jpg
value=3.999
rarity=M
type=Planeswalker
subtype=Tezzeret
cost={2}{U}{B}
loyalty=3
ability=+1: Look at the top five cards of your library. You may reveal an artifact card from among them and put it into your hand. Put the rest on the bottom of your library in any order.;\
        −1: Target artifact becomes a 5/5 artifact creature.;\
        −4: Target opponent loses 2 life for each artifact you control.~and you gain 2 life for each artifact you control.
timing=main
oracle=+1: Look at the top five cards of your library. You may reveal an artifact card from among them and put it into your hand. Put the rest on the bottom of your library in any order.\n−1: Target artifact becomes an artifact creature with base power and toughness 5/5.\n−4: Target player loses X life and you gain X life, where X is twice the number of artifacts you control.

**Comment by melvinzhang** [comment]
Wow, another awesome find! Included in 23314e30ae7b1c5fb
