### ISSUE TITLE
Oran-Rief Hydra

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#887]
name=Oran-Rief Hydra
image=http://magiccards.info/scans/en/bfz/181.jpg
image_updated=2015-11-08
value=2.500
rarity=R
type=Creature
subtype=Hydra
cost={4}{G}{G}
pt=5/5
ability=Trample;\
        Whenever a land enters the battlefield under your control, put a +1/+1 counter on SN.;\
        Whenever a forest enters the battlefield under your control, put a +1/+1 counter on SN.
timing=main
oracle=Trample\nLandfall — Whenever a land enters the battlefield under your control, put a +1/+1 counter on Oran-Rief Hydra. If that land is a Forest, put two +1/+1 counters on Oran-Rief Hydra instead.

**Comment by ShawnieBoy** [comment]
Using groovy would be better to prevent multiple triggers.

**Comment by kelsioboy** [comment]
ok

**Comment by melvinzhang** [comment]
@kelsioboy Closing for now to keep the issues list tidy. Feel free to reopen this when you have the groovy for this that only generates one trigger.
