### ISSUE TITLE
Living Hive

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#888]
name=Living Hive
image=http://magiccards.info/scans/en/pch/75.jpg
value=4.107
rarity=R
type=Creature
subtype=Elemental,Insect
cost={6}{G}{G}
pt=6/6
ability=Trample;\        
timing=main
requires_groovy_code
oracle=Trample\nWhenever Living Hive deals combat damage to a player, put that many 1/1 green Insect creature tokens onto the battlefield.

[
    new ThisCombatDamagePlayerTrigger() {
        @Override
        public MagicEvent executeTrigger(final MagicGame game,final MagicPermanent permanent,final MagicDamage damage) {
            return new MagicEvent(
                permanent,
                damage.getDealtAmount(),
                this,
                "PN puts RN 1/1 green Insect creature tokens onto the battlefield. " 
            );
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            game.doAction(new PlayTokensAction(
                event.getPlayer(),
                CardDefinitions.getToken("1/1 green Insect creature token"),
                event.getRefInt()
            ));
        }
    }
]

**Comment by melvinzhang** [comment]
Looks good! Included as part of next release in 2090e56109fc8dc27de5
