### ISSUE TITLE
Tenza, Godo's Maul

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#890]
name=Tenza, Godo's Maul
image=http://magiccards.info/scans/en/chk/271.jpg
value=3.620
rarity=U
type=Legendary,Artifact
subtype=Equipment
cost={3}
ability=Equipped creature gets +1/+1.;\
        As long as equipped creature is legendary, equipped creature gets +2/+2.;\
        As long as equipped creature is Red, equipped creature has trample.;\
        Equip {1}
timing=equipment
oracle=Equipped creature gets +1/+1. As long as it's legendary, it gets an additional +2/+2. As long as it's red, it has trample.\nEquip {1}

**Comment by melvinzhang** [comment]
This is a nice one. Added on Sept 15 in c37d39cb7e 

@kelsioboy There was a bunch I added on Sept 15, you can see https://github.com/magarena/magarena/wiki/UpcomingCards for the list of included cards.
