### ISSUE TITLE
Yomiji, Who Bars the Way

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#891]
name=Yomiji, Who Bars the Way
image=http://magiccards.info/scans/en/bok/30.jpg
value=3.131
rarity=R
type=Legendary,Creature
subtype=Spirit
cost={5}{W}{W}
pt=4/4
ability=Each other legendary permanents has "When SN dies, return SN from the graveyard to its owner's hand."
timing=main
oracle=Whenever a legendary permanent other than Yomiji, Who Bars the Way is put into a graveyard from the battlefield, return that card to its owner's hand.

**Comment by ShawnieBoy** [comment]
This should remain as a triggered ability. Other legendary permanents which lose their abilities should still be affected.

**Comment by kelsioboy** [comment]
Ok

**Comment by melvinzhang** [comment]
@kelsioboy you can checkout https://github.com/magarena/magarena/blob/master/release/Magarena/scripts/Wind_Zendikon.groovy for how it is done currently in groovy code. This is for `When enchanted land dies, return that card to its owner's hand.`
