### ISSUE TITLE
Putting MagicSpellCardEvent on lands is confusing

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#893]
ShawnieBoy commented on dd23352 
> I think it's just the terminology that Magarena uses runs counter to official rules. Playing lands with a spellcardevent, which is actually affecting enter the battlefield events. Would a separate method, named more clearly, be better in explaining what is occuring. As for me it's really confusing/misleading.

**Comment by melvinzhang** [comment]
@ShawnieBoy what do you recommend? Perhaps a MagicLandCardEvent instead of MagicSpellCardEvent?

**Comment by melvinzhang** [comment]
Another suggestion is to rename MagicSpellCardEvent to a more generic name such as MagicPlayCardEvent since comp rules states that " 701.11b To play a card means to play that card as a land or to cast that card as a spell, whichever is appropriate."

**Comment by ShawnieBoy** [comment]
>what do you recommend? Perhaps a MagicLandCardEvent instead of MagicSpellCardEvent?

The main point of confusion is that the spellcardevent is creating an entersthebattlefield-type effect. Maybe a WouldEnterTheBattlefieldEvent? Or something to distinguish it more from a spell-event.

**Comment by melvinzhang** [comment]
For artifacts, creatures, enchantments, etc it is appropriate. It goes from card in your hand, to spell on the stack, when the spell resolves the effect of the spell creates a permanent on the battlefield. The part when they are on the stack is when counter spells can be used to prevent the permanent from being created.

The odd one out is lands, it goes from card in hand to on the battlefield without going through a spell first. For simplicity in the engine, a psuedo spell is created and but never put on the stack.

**Comment by ShawnieBoy** [comment]
What I'm getting at, is that the effect still triggers if the card is not played, but enters the battlefield in a another way. When a card is 'put' onto the battlefield it is not cast again, so does not use the stack itself.

**Comment by melvinzhang** [comment]
That's true and that is a relatively recent change, that was added to support Clone. Previously, putting a card on the battlefield directly did not make use of the event created by MagicSpellCardEvent but rather created a permanent directly without a MagicCardOnStack. As you can imagine, this would not work with Clone and creates some duplication/inconsistency in the code there are two different of getting on the battlefield.

At some point, the direct method was replace by using the event from MagicSpellCardEvent. I see how that could be confusing now, since technically no spell was cast. I think EnterTheBattleFieldEvent as you have suggested is a better name.

**Comment by melvinzhang** [comment]
@ShawnieBoy please see the commit https://github.com/magarena/magarena/commit/fc862a47334d2871dfd3b05806d4578ac4c14eee

Does this resolve the confusion?

**Comment by ShawnieBoy** [comment]
Yes, this better describes how the effect occurs. Almost like a hybrid trigger.
