### ISSUE TITLE
replace Æ with Ae in card names

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#896]
> The change will be retroactive. Cards with the Ae ligature will now just be an “A” and an “e”. 
-- http://markrosewater.tumblr.com/post/144471532728/this-is-a-bit-weird-but-i-notice-its-the-aether

**Comment by ShawnieBoy** [comment]
Shame to see it go 😢 But can understand why. Now, how about sorting out Lim-Dul, hehe

**Comment by melvinzhang** [comment]
@ShawnieBoy the groovy files should be renamed too.

**Comment by ShawnieBoy** [comment]
Not finished yet

**Comment by melvinzhang** [comment]
Don't forget the prebuilt dec files containing Aether cards.

**Comment by ShawnieBoy** [comment]
All the Æ to Ae cards have their images set to redownload, as the file-names for the images will be different. Shame there's no way to delete the old ones.

**Comment by melvinzhang** [comment]
For future reference, it is preferable to rename the txt and groovy file of the same card together in one commit to prevent CI failures.

**Comment by ShawnieBoy** [comment]
Sure thing.

Player decks containing cards will need to be edited manually and Firemind will probably go a bit strange (at a guess). But everything's been replaced.
