### ISSUE TITLE
Deathbringer Liege Fix not working

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#899]
[
    new OtherSpellIsCastTrigger(1) {
        @Override
        public MagicEvent executeTrigger(final MagicGame game,final MagicPermanent permanent,final MagicCardOnStack cardOnStack) {
            return (permanent.isFriend(cardOnStack) &&
                    cardOnStack.hasColor(MagicColor.White)) ?
                new MagicEvent(
                    permanent,
                    new MagicMayChoice(
                        NEG_TARGET_CREATURE
                    ),
                    MagicTapTargetPicker.Tap,                    
                    this,
                    "PN may\$ tap target creature\$."
                ):
                MagicEvent.NONE;
        }

        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            if (event.isYes()) {
                event.processTargetPermanent(game, {                    
                        game.doAction(new TapAction(it));                    
                });
            }
        }
    },
    new OtherSpellIsCastTrigger(2) {
        @Override
        public MagicEvent executeTrigger(final MagicGame game,final MagicPermanent permanent,final MagicCardOnStack cardOnStack) {
            return (permanent.isFriend(cardOnStack) &&
                    cardOnStack.hasColor(MagicColor.Black)) ?
                new MagicEvent(
                    permanent,
                    new MagicMayChoice(
                        NEG_TARGET_CREATURE
                    ),
                    MagicDestroyTargetPicker.Destroy,
                    this,
                    "PN may\$ destroy target creature\$ if it's tapped."
                ):
                MagicEvent.NONE;
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            if (event.isYes()) {
                event.processTargetPermanent(game, {
                    if (it.isTapped()) {  
                    game.doAction(new DestroyAction(it));
                    } 
                });
            }
        }
    }
]

**Comment by kelsioboy** [comment]
Hello, I know it's boring to hit the same key, but I've been testing the new version 1.77, and the first thing I did was check the fix. The Deathbringer Liege is not working, so I took the liberty to recreate the Groovy and send it to you guys test. The secret of the effect of the order are the numbers in ( ) are the ones who dictate the order of occurrences. Please test this groovy I send without change it and then answer me.

**Comment by melvinzhang** [comment]
@kelsioboy Thanks for checking if the fix works, it is good to ensure that a fix is working as expected. I found a simpler solution which is to turn the tap trigger into card script, see 8402589

I tested it with a black and white spell and it works as expected. If you could help to test and confirm that it works for you as well would be great.

**Comment by kelsioboy** [comment]
@melvinzhang  I tested this method and unfortunately it did not work here, continued the old way ie, it first asks if you want to destroy and then turn more right should be, he asks if I want to turn around and then destroy. I was curious why you do not want to use the groovy I sent? You have something wrong with it? .Pois Here it works perfectly. He asks if I want to turn around and then destroy in the expected order.

**Comment by melvinzhang** [comment]
@kelsioboy As you have set the tap trigger to priority 1 it does not go onto the stack which wrong. 

It is correct that the game asks you which creature to destroy as the destroy trigger goes on to the stack first. Then it asks you which creature to tap as the tap trigger goes onto the stack later (so it is on top).

It should look like the following:
![deathbringer](https://cloud.githubusercontent.com/assets/1620634/18936869/c51201a0-861d-11e6-9b34-4393af580053.png)

After this, the top most trigger, i.e. the tap trigger, resolves first. Then the destroy trigger.

It is important to note that the both triggers should on the stack together, with the tap trigger on top so that it resolves first.

**Comment by kelsioboy** [comment]
I was just wondering what was wrong with this groovy that you guys did not put, right now I know and understand. Thanks for the answer. :+1:
