### ISSUE TITLE
Afiya Grove (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#900]
name=Afiya Grove
image=http://magiccards.info/scans/en/mr/103.jpg
value=3.293
rarity=R
type=Enchantment
cost={1}{G}
ability=SN enters the battlefield with three +1/+1 counters on it.;\
        At the beginning of your upkeep, remove a +1/+1 counter from SN.;\
        At the beginning of your upkeep, put a +1/+1 counter on target creature.;\
        When SN has no +1/+1 counters on it, sacrifice SN.
timing=enchantment
oracle=Afiya Grove enters the battlefield with three +1/+1 counters on it.\nAt the beginning of your upkeep, move a +1/+1 counter from Afiya Grove onto target creature.\nWhen Afiya Grove has no +1/+1 counters on it, sacrifice it.

**Comment by melvinzhang** [comment]
Moving a counter should be a single trigger, not two triggers. If I need to prevent a move, I can counter it with a single Stifle.
