### ISSUE TITLE
Arachnus Spinner (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#901]
name=Arachnus Spinner
image=http://magiccards.info/scans/en/m12/162.jpg
value=4.135
rarity=R
type=Creature
subtype=Spider
cost={5}{G}
pt=5/7
ability=Reach;\
        Tap an untapped Spider you control: Return target card named Arachnus Web from your graveyard to the battlefield.;\
        Tap an untapped Spider you control: Search your library for a card named Arachnus Web and put it onto the battlefield. If you do, shuffle your library.
timing=main
oracle=Reach\nTap an untapped Spider you control: Search your graveyard and/or library for a card named Arachnus Web and put it onto the battlefield attached to target creature. If you search your library this way, shuffle it.

**Comment by melvinzhang** [comment]
The card isn't the target, it is the creature to to be attached that is the target of this effect. If the opponent destroys the creature in response to the ability, then the ability would be countered.
