### ISSUE TITLE
Broken Ambitions (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#902]
name=Broken Ambitions
image=http://magiccards.info/scans/en/lw/54.jpg
value=3.538
rarity=C
type=Instant
cost={X}{U}
ability=When you cast SN, clash with an opponent. If you win, target opponent puts the top four cards of his or her library into his or her graveyard.
timing=counter
requires_groovy_code
oracle=Counter target spell unless its controller pays {X}. Clash with an opponent. If you win, that spell's controller puts the top four cards of his or her library into his or her graveyard.

[
    new MagicSpellCardEvent() {
        @Override
        public MagicEvent getEvent(final MagicCardOnStack cardOnStack,final MagicPayedCost payedCost) {
            return new MagicEvent(
                cardOnStack,
                NEG_TARGET_SPELL,
                payedCost.getX(),
                this,
                "Counter target spell\$ unless its controller pays {X}. (X=RN)"
            );
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            event.processTargetCardOnStack(game, {
                final int amount = event.getRefInt();
                game.addEvent(new MagicCounterUnlessEvent(
                    event.getSource(),
                    it,
                    MagicManaCost.create("{"+amount+"}")
                ));
            });
        }
    }
]

**Comment by melvinzhang** [comment]
Clashing should be part of the resolution of spell and not a separate trigger. This is so that if I counter this spell, the clash will not occur.
