### ISSUE TITLE
Cavalry Master (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#903]
name=Cavalry Master
image=http://magiccards.info/scans/en/ts/6.jpg
value=3.895
rarity=U
type=Creature
subtype=Human,Knight
cost={2}{W}{W}
pt=3/3
ability=Flanking;\
        As long as it's your turn, other attacking creatures with flanking have flanking.
static=player
timing=main
oracle=Flanking\nOther creatures you control with flanking have flanking.

**Comment by kelsioboy** [comment]
Not sure if the effect is this way, test, and answer me.

**Comment by melvinzhang** [comment]
@kelsioboy Still looking into this, please leave this issue open.

**Comment by kelsioboy** [comment]
Excuse me I thought I had to close, try not to repeat the mistake.  :)

**Comment by melvinzhang** [comment]
We've improved the card script to directly support "Other creatures you control with flanking" :)
