### ISSUE TITLE
Dark Supplicant (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#904]
name=Dark Supplicant
image=http://magiccards.info/scans/en/le/64.jpg
value=3.375
rarity=U
type=Creature
subtype=Human,Cleric
cost={B}
pt=1/1
ability={T}, Sacrifice three Clerics: Return target card named Scion of Darkness from your graveyard to the battlefield.;\
        {T}, Sacrifice three Clerics: Put target card named Scion of Darkness from your hand onto the battlefield. Activate this ability only if you have a creature card in your hand.;\
        {T}, Sacrifice three Clerics: Search your library for a card named Scion of Darkness and put it onto the battlefield. If you do, shuffle your library.
timing=main
oracle={T}, Sacrifice three Clerics: Search your graveyard, hand, and/or library for a card named Scion of Darkness and put it onto the battlefield. If you search your library this way, shuffle it.

**Comment by melvinzhang** [comment]
@kelsioboy This is nice idea to do searching from multiple locations. Please leave this open while we review it. 

@ShawnieBoy what do you think of this technique for search from different locations?

**Comment by ShawnieBoy** [comment]
The only situation I can think of that this can't cover, is the option of gaining a free shuffle while searching through the library, graveyard and hand.

**Comment by melvinzhang** [comment]
@ShawnieBoy how does the oracle text give you a free shuffle? If you search your library using the third ability, you do get a shuffle.

Yay or nay for including this card script?

**Comment by ShawnieBoy** [comment]
>Search your graveyard, hand, and/or library for a card named Scion of Darkness and put it onto the battlefield. If you search your library this way, shuffle it.

You can choose to search your library during any search, even if you fail to find anything or are also searching elsewhere. If Scion of Darkness is in your hand, you can choose to search your library and your hand to enable a shuffle of your library, when you 'find' the card in your hand.

**Comment by ShawnieBoy** [comment]
If the non-library searches had an optional 'You may shuffle your library' rider, that would cover all corner-cases, simulating a 'failed' search of the library if a shuffle is also wanted.

**Comment by melvinzhang** [comment]
Unfortunately that is not possible, rider cannot have choices.

**Comment by melvinzhang** [comment]
Looking at the card choice, it does support multiple locations. I'm going to try and see if we can get it done with an ability in groovy.

**Comment by melvinzhang** [comment]
It is possible to show valid cards in all three locations at once. However this means we can't tell if a player actually searched the library or not. So the shuffle will be compulsory.
