### ISSUE TITLE
Debt of Loyalty (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#905]
name=Debt of Loyalty
image=http://magiccards.info/scans/en/wl/127.jpg
value=4.281
rarity=R
type=Instant
cost={1}{W}{W}
effect=Gain control of target creature.~Regenerate *it*.
timing=pump
oracle=Regenerate target creature. You gain control of that creature if it regenerates this way.

**Comment by kelsioboy** [comment]
I know the effect of regenerating should come first, but if you make a small modification works opposite. Just I made that way for the sake of adaptation, because as I play with preference limited the other way does not work correctly in limited mode. Anyway, I believe the effect was satisfactory.

**Comment by melvinzhang** [comment]
"regenerates this way" means when the regeneration occurs not when the regeneration shield is put on the create. There is no way currently (with card script or groovy) to do something additional when a create regenerates. 

A creature regenerates when it is about to be destroyed, while regenerate it means put a regeneration shield on it.
