### ISSUE TITLE
Feed the Clan (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#906]
name=Feed the Clan
image=http://magiccards.info/scans/en/ktk/132.jpg
value=2.500
rarity=C
type=Instant
cost={1}{G}
effect=You gain 5 life.~If you control a creature with power 4 or greater, you gain 5 life.
timing=removal
oracle=You gain 5 life.\nFerocious — You gain 10 life instead if you control a creature with power 4 or greater.

**Comment by melvinzhang** [comment]
This is a nice trick, unfortunately it doesn't work well with "whenever you gain life" triggers. Those will trigger twice becaose of the 5 life gain and 5 life gain, but it should only trigger once due to 10 life gain.
