### ISSUE TITLE
Flame-Wreathed Phoenix (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#907]
name=Flame-Wreathed Phoenix
image=http://magiccards.info/scans/en/bng/97.jpg
value=3.589
rarity=M
type=Creature
subtype=Phoenix
cost={2}{R}{R}
pt=3/3
ability=Flying;tribute 2 effect SN gains "When SN dies, return SN from the graveyard to its owner's hand."~and SN gains haste until end of turn.
timing=main
oracle=Flying\nTribute 2\nWhen Flame-Wreathed Phoenix enters the battlefield, if tribute wasn't paid, it gains haste and "When this creature dies, return it to its owner's hand."

**Comment by melvinzhang** [comment]
@kelsioboy Did you find some problem with this? If not, please leave it open while we review it.

**Comment by melvinzhang** [comment]
Looks good. The effect can be done as a single line without repeating `SN gains` part. The final version is `Tribute 2 effect SN gains haste and "When this creature dies, return this creature from the graveyard to its owner's hand."`
