### ISSUE TITLE
Guul Draz Overseer (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#908]
name=Guul Draz Overseer
image=http://magiccards.info/scans/en/bfz/112.jpg
image_updated=2015-11-08
value=2.500
rarity=R
type=Creature
subtype=Vampire
cost={4}{B}{B}
pt=3/4
ability=Flying;\
        Whenever a land enters the battlefield under your control, other creatures you control get +1/+0 until end of turn.;\
        Whenever a swamp enters the battlefield under your control, other creatures you control get +1/+0 until end of turn.
timing=main
oracle=Flying\nLandfall — Whenever a land enters the battlefield under your control, other creatures you control get +1/+0 until end of turn. If that land is a Swamp, those creatures get +2/+0 until end of turn instead.

**Comment by melvinzhang** [comment]
A swamp entering the battlefield creates two triggers when there should only be one. We want to make sure the number of triggers follow the original card text.
