### ISSUE TITLE
Hellkite Tyrant (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#909]
name=Hellkite Tyrant
image=http://magiccards.info/scans/en/gtc/94.jpg
value=4.209
rarity=M
type=Creature
subtype=Dragon
cost={4}{R}{R}
pt=6/5
ability=Flying, trample;\
        At the beginning of your upkeep, if you control twenty or more artifacts, you win the game.
timing=main
requires_groovy_code
oracle=Flying, trample\nWhenever Hellkite Tyrant deals combat damage to a player, gain control of all artifacts that player controls.\nAt the beginning of your upkeep, if you control twenty or more artifacts, you win the game.

[
    new ThisCombatDamagePlayerTrigger() {
        @Override
        public MagicEvent executeTrigger(final MagicGame game, final MagicPermanent permanent, final MagicDamage damage) {
            return new MagicEvent(
                permanent,
                this,
                "PN gains control of all Artifacts."
            )
        }

        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            final MagicPlayer player = event.getPlayer();
            ARTIFACT.filter(event) each {
                game.doAction(new GainControlAction(player, it));
            }
        }
    }
]

**Comment by melvinzhang** [comment]
@kelsioboy This looks quite good actually. I think it needs a small tweak. Gain control of that player's artifacts should be `ARTIFACT_YOU_CONTROL.filter(event.getPlayer())`

Why did you close this issue?

**Comment by kelsioboy** [comment]
I liked the idea. :+1:
