### ISSUE TITLE
Huntmaster of the Fells (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#910]
name=Huntmaster of the Fells
image=http://magiccards.info/scans/en/dka/140a.jpg
value=3.953
rarity=M
type=Creature
subtype=Human,Werewolf
cost={2}{R}{G}
pt=2/2
ability=Whenever this creature enters the battlefield, put a 2/2 green Wolf creature token onto the battlefield.~and you gain 2 life;\
        Whenever this creature transforms into SN, put a 2/2 green Wolf creature token onto the battlefield.~and you gain 2 life.;\
        At the beginning of each upkeep, if no spells were cast last turn, transform SN.
transform=Ravager of the Fells
timing=main
oracle=Whenever this creature enters the battlefield or transforms into Huntmaster of the Fells, put a 2/2 green Wolf creature token onto the battlefield and you gain 2 life.\nAt the beginning of each upkeep, if no spells were cast last turn, transform Huntmaster of the Fells.

**Comment by melvinzhang** [comment]
This is ok, unfortunately the other half is not possible right now.
