### ISSUE TITLE
Ravager of the Fells (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#911]
name=Ravager of the Fells
image=http://magiccards.info/scans/en/dka/140b.jpg
value=3.953
rarity=M
type=Creature
subtype=Werewolf
color=rg
pt=4/4
ability=Trample;\
        When this creature transforms into SN, SN deals 2 damage to target creature an opponent controls.;\
        When this creature transforms into SN, SN deals 2 damage to opponent.;\
        At the beginning of each upkeep, if a player cast two or more spells last turn, transform SN.
transform=Huntmaster of the Fells
timing=main
hidden
oracle=Trample\nWhenever this creature transforms into Ravager of the Fells, it deals 2 damage to target opponent and 2 damage to up to one target creature that player controls.\nAt the beginning of each upkeep, if a player cast two or more spells last turn, transform Ravager of the Fells.

**Comment by melvinzhang** [comment]
This creates two triggers on transform, when there should only be one. We prefer to avoid changing the number of triggers as it is confusing and does not interact well with cards that counter target triggered ability.

**Comment by kelsioboy** [comment]
got it.
