### ISSUE TITLE
Structural Distortion (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#912]
name=Structural Distortion
image=http://magiccards.info/scans/en/soi/185.jpg
value=2.500
rarity=C
type=Sorcery
cost={3}{R}
effect=Exile target artifact or land.~SN deals 2 damage to that permanent's controller.
timing=main
oracle=Exile target artifact or land. Structural Distortion deals 2 damage to that permanent's controller.

**Comment by melvinzhang** [comment]
Good one, nice find.
