### ISSUE TITLE
Redeem the Lost (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#913]
name=Redeem the Lost
image=http://magiccards.info/scans/en/mt/21.jpg
value=2.971
rarity=U
type=Instant
cost={1}{W}
effect=Target creature you control gains protection from the color of your choice until end of turn.~Clash with an opponent. If you win, return SN to its owner's hand.
timing=removal
oracle=Target creature you control gains protection from the color of your choice until end of turn. Clash with an opponent. If you win, return Redeem the Lost to its owner's hand.

**Comment by melvinzhang** [comment]
Looks good!

**Comment by ShawnieBoy** [comment]
Hmm, wouldn't this try to return the creature to your hand instead of the spell on the stack?
