### ISSUE TITLE
Pristine Skywise (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#914]
name=Pristine Skywise
image=http://magiccards.info/scans/en/dtk/228.jpg
value=2.500
rarity=R
type=Creature
subtype=Dragon
cost={4}{W}{U}
pt=6/4
ability=Flying;\
        Whenever you cast a noncreature spell, untap SN.~SN gains protection from the color of your choice until end of turn.
timing=main
oracle=Flying\nWhenever you cast a noncreature spell, untap Pristine Skywise. It gains protection from the color of your choice until end of turn.

**Comment by melvinzhang** [comment]
Looks good, we can keep the "It" as it means the same as SN internally.
