### ISSUE TITLE
Pollen Lullaby (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#915]
name=Pollen Lullaby
image=http://magiccards.info/scans/en/cmd/26.jpg
value=2.593
rarity=U
type=Instant
cost={1}{W}
effect=Prevent all combat damage that would be dealt this turn.~Clash with an opponent. If you win, creatures your opponents control doesn't untap during its controller's next untap step.
timing=removal
oracle=Prevent all combat damage that would be dealt this turn. Clash with an opponent. If you win, creatures that player controls don't untap during the player's next untap step.

**Comment by melvinzhang** [comment]
Looks good. Works since "that player" is always the opponent.

**Comment by melvinzhang** [comment]
Hang on, there is a problem with this. It needs to be done like https://github.com/magarena/magarena/blob/master/release/Magarena/scripts/Exhaustion.groovy

The problem with the current script is that only the creatures that are on the battlefield at the time the spell resolves don't untap. Those that enter the battlefield after the spell resolved are not affected. Similar to Exhaustion, even those that enter later should not untap.
