### ISSUE TITLE
Misstep (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#917]
name=Misstep
image=http://magiccards.info/scans/en/mm/88.jpg
value=3.344
rarity=C
type=Sorcery
cost={1}{U}
effect=Creatures your opponents control doesn't untap during its controller's next untap step.
timing=main
oracle=Creatures target player controls don't untap during that player's next untap step.

**Comment by melvinzhang** [comment]
The part about "target player" is important. It is possible for a player to gain hexproof and therefore cannot be targeted.
