### ISSUE TITLE
Lash Out (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#918]
name=Lash Out
image=http://magiccards.info/scans/en/cmd/127.jpg
value=3.012
rarity=C
type=Instant
cost={1}{R}
effect=SN deals 3 damage to target creature an opponent controls.~Clash with an opponent. If you win, SN deals 3 damage to opponent.
timing=removal
oracle=Lash Out deals 3 damage to target creature. Clash with an opponent. If you win, Lash Out deals 3 damage to that creature's controller.

**Comment by melvinzhang** [comment]
This prevents the player from casting it on his/her own creature. Generally we find it ok to prevent the AI to make such odd moves, but we would like the player to be able to make them if needed.
