### ISSUE TITLE
Lashwrithe (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#919]
name=Lashwrithe
image=http://magiccards.info/scans/en/c14/245.jpg
value=2.500
rarity=R
type=Artifact
subtype=Equipment
cost={4}
ability=Living weapon;\
        Equipped creature gets +1/+1 for each Swamp you control.;\
        Equip {B/P}{B/P}.;\
        Equip—Pay 4 life.
timing=equipment
oracle=Living weapon\nEquipped creature gets +1/+1 for each Swamp you control.\nEquip {B/P}{B/P}

**Comment by kelsioboy** [comment]
This card I just like breaking branch.

**Comment by melvinzhang** [comment]
This looks reasonable, similar to the alt cost. There should be one more `Equip—{B/P}, Pay 2 life`. There is a small usability issue in that all the three equip activations have the same name in the UI.

**Comment by melvinzhang** [comment]
With a bit of groovy code, it is possible to give differernt names to each of the three equip.
