### ISSUE TITLE
Chandra, Pyrogenius (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#920]
name=Chandra, Pyrogenius
image=http://mythicspoiler.com/kld/cards/chandrapyrogenius.jpg
value=2.500
rarity=M
type=Planeswalker
subtype=Chandra
cost={4}{R}{R}
loyalty=5
ability=+2: SN deals 2 damage to each opponent.;\
        −3: SN deals 4 damage to target creature.
timing=main
requires_groovy_code
oracle=+2: Chandra, Pyrogenius deals 2 damage to each opponent.\n−3: Chandra, Pyrogenius deals 4 damage to target creature.\n−10: Chandra, Pyrogenius deals 6 damage to target player and each creature he or she controls.

[
    new MagicPlaneswalkerActivation(-10) {
        @Override
        public MagicEvent getPermanentEvent(final MagicPermanent source, final MagicPayedCost payedCost) {
            return new MagicEvent(
                source,
                NEG_TARGET_PLAYER,
                new MagicDamageTargetPicker(6),
                this,
                "SN deals 6 damage to target player\$ and each creature he or she controls."
            );
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            event.processTargetPlayer(game, {
                game.doAction(new DealDamageAction(event.getSource(), it, 6));
                CREATURE_YOU_CONTROL.filter(it) each {
                    final MagicPermanent target ->
                    game.doAction(new DealDamageAction(event.getSource(),target,6));
                }
            });
        }
    }
]

**Comment by kelsioboy** [comment]
A small note, I changed the address of the image because it was causing crash here, I recommend you change it to another.

**Comment by melvinzhang** [comment]
Looks good! The groovy code for dealing damage to each creature he/she controls is spot on.

**Comment by kelsioboy** [comment]
:+1:
