### ISSUE TITLE
Morph permanents cannot be turned face up

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#921]
The effects of Morph and Megamorph are no longer worked in version 1.77. Please see. Detail, the effect of Manifest is normal.

Melvin: Moved other bug to https://github.com/magarena/magarena/issues/922

**Comment by melvinzhang** [comment]
@kelsioboy thanks for catching this. By "no longer worked" do you mean you cannot turn a morph creature face up? 

Please be more specific next time, "no longer worked" is too vague for us as there are many ways a card is not working right. The best way to explain it is to indicate what is expected and what is observed. For example:

Expected: I am able to pay the mana cost to turn a morph creature face up.
Observed: There is no option to turn morph creature face up.

**Comment by kelsioboy** [comment]
okay, I'll try to be more specific but have a little dificudade to pass it to you guys. Slowly I learn.
