### ISSUE TITLE
Nissa, Nature's Artisan (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#923]
name=Nissa, Nature's Artisan
image=http://mythicspoiler.com/kld/cards/nissanaturesartisan.jpg
value=2.500
rarity=M
type=Planeswalker
subtype=Nissa
cost={4}{G}{G}
loyalty=5
ability=+3: You gain 3 life.;\
        −12: Creatures you control get +5/+5 and gain trample until end of turn.
timing=main
requires_groovy_code
oracle=+3: You gain 3 life.\n−4: Reveal the top two cards of your library. Put all land cards from among them onto the battlefield and the rest into your hand.\n−12: Creatures you control get +5/+5 and gain trample until end of turn.

[
    new MagicPlaneswalkerActivation(-4) {        
        @Override
        public MagicEvent getPermanentEvent(final MagicPermanent source, final MagicPayedCost payedCost) {             
            return new MagicEvent(
                source,
                POS_TARGET_PLAYER,
                this,
                "PN reveal the top two cards of your library."+
                "PN put all land cards from among them onto the battlefield and the rest into your hand."
            );
        }

        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            final MagicPlayer player = event.getPlayer();
            final MagicCardList cards = player.getLibrary().getCardsFromTop(2);
            for (final MagicCard card : cards) {
                game.doAction(new RevealAction(card));
                if (card.hasType(MagicType.Land)) {
                    game.doAction(new ReturnCardAction(MagicLocationType.OwnersLibrary, card, player));
                } else {
                    game.doAction(new ShiftCardAction(card, MagicLocationType.OwnersLibrary, MagicLocationType.OwnersHand));
                }
            }
        }
    }
]

**Comment by melvinzhang** [comment]
Looks good! I made two small corrections: 

`POS_TARGET_PLAYER` should not be there (this effect does not target a player) and

Both cards should be revealed together using `game.doAction(new RevealAction(cards));` before the for loop.

**Comment by kelsioboy** [comment]
:+1:
