### ISSUE TITLE
Foundry Inspector (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#924]
name=Foundry Inspector
image=http://media.wizards.com/2016/bVvMNuiu2i_KLD/en_ZistwQAtse.png
value=2.500
rarity=U
type=Artifact,Creature
subtype=Construct
cost={3}
pt=3/2
timing=main
requires_groovy_code=Etherium Sculptor
oracle=Artifact spells you cast cost {1} less to cast.

**Comment by melvinzhang** [comment]
Nice find and good use of groovy code from another card.

**Comment by kelsioboy** [comment]
:+1:
