### ISSUE TITLE
Raving Dead (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#927]
name=Raving Dead
image=http://magiccards.info/scans/en/c14/29.jpg
value=2.500
rarity=R
type=Creature
subtype=Zombie
cost={4}{B}
pt=2/6
ability=Deathtouch;\
        SN attacks each turn if able.
timing=main
requires_groovy_code
oracle=Deathtouch\nAt the beginning of combat on your turn, choose an opponent at random. Raving Dead attacks that player this combat if able.\nWhenever Raving Dead deals combat damage to a player, that player loses half his or her life, rounded down.

[    
    new DamageIsDealtTrigger() {
        @Override
        public MagicEvent executeTrigger(final MagicGame game, final MagicPermanent permanent, final MagicDamage damage) {
            return (damage.isSource(permanent) && damage.isTargetPlayer() && damage.isCombat()) ?
                new MagicEvent(
                    permanent,
                    damage.getTargetPlayer(),
                    this,
                    "PN loses half his or her life, rounded down."
                ):
                MagicEvent.NONE;
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            final MagicPlayer player = event.getPlayer();
            game.doAction(new ChangeLifeAction(player,-player.getLife()/2));
        }
    }
]

**Comment by melvinzhang** [comment]
Nice one, can be a little simpler by using ThisCombatDamagePlayerTrigger instead of DamageIsDealtTrigger. I made this simplification in the commit.
