### ISSUE TITLE
Dragon With An Alarm Clock

### ISSUE THREAD

**Issue by Cecil-Lizard** [magarena/magarena#928]
I had the Slumbering Dragon card [http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=253693](url) played, but it could attack and block from the get go (it still gained counters), which was cool and all, but not what the text said.

In-universe I thought of this happening:

An Adventurer (to his companions, whispering): Alright, as long as we are quiet, we should be fine, dragons are heavy sleepers-
Dragon: My, my, what do we have here this early in the morning?
Adventurer: Oh Sh- (adventuring party is incinerated)

**Comment by ShawnieBoy** [comment]
Haha, hmm, well, not sure why this dragon has more than one eye open, but can definitely confirm it's a bug. Maybe @melvinzhang will know a lullaby.

**Comment by melvinzhang** [comment]
Thanks, I can confirm this occurs and the reason is because 'can't attack' was added at a layer which we stopped using for permanents. Fix incoming.
