### ISSUE TITLE
Domesticated Hydra (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#930]
name=Domesticated Hydra
image=http://magiccards.info/scans/en/cn2/63.jpg
image_updated=2016-09-05
value=2.500
rarity=U
type=Creature
subtype=Hydra
cost={2}{G}{G}
pt=3/3
timing=main
requires_groovy_code
oracle={X}{G}{G}{G}: Monstrosity X.\nAs long as Domesticated Hydra is monstrous, it has trample.

[
    new MagicPermanentActivation(
        [MagicCondition.NOT_MONSTROUS_CONDITION],
        new MagicActivationHints(MagicTiming.Pump),
        "Monstrosity"
    ) {
        @Override
        public Iterable<? extends MagicEvent> getCostEvent(final MagicPermanent source) {
            return [
                new MagicPayManaCostEvent(source,"{X}{G}{G}{G}")
            ];
        }

        @Override
        public MagicEvent getPermanentEvent(final MagicPermanent source,final MagicPayedCost payedCost) {
            return new MagicEvent(
                source,
                payedCost.getX(),
                this,
                "If SN isn't monstrous, put RN +1/+1 counter on it and it becomes monstrous."
            );
        }

        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            game.doAction(new ChangeCountersAction(event.getPermanent(),MagicCounterType.PlusOne,event.getRefInt()));
            game.doAction(ChangeStateAction.Set(
                event.getPermanent(),
                MagicPermanentState.Monstrous

            )); 
        }
    },       

    new MagicStatic(MagicLayer.Ability) {
        @Override
        public void modAbilityFlags(final MagicPermanent source, final MagicPermanent permanent, final Set<MagicAbility> flags) {
            permanent.addAbility(MagicAbility.Trample, flags);            
        }
        @Override
        public boolean condition(final MagicGame game, final MagicPermanent source, final MagicPermanent target) {
            return MagicCondition.IS_MONSTROUS_CONDITION.accept(source);
        }
    }
]

**Comment by melvinzhang** [comment]
Nice one. Thanks to this, I realized we've always had a bug with monstrosity, there should be another check for "isn't monstrous" when the ability resolves. Also figured out how the second ability can be done in card script with some small tweaks to the card script parser.
