### ISSUE TITLE
Ghirapur Orrery (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#931]
name=Ghirapur Orrery
image=http://media.wizards.com/2016/bVvMNuiu2i_KLD/en_emy2dmKzBz.png
value=2.500
rarity=R
type=Artifact
cost={4}
timing=artifact
requires_groovy_code=Rites of Flourishing;Ghirapur Orrery
oracle=Each player may play an additional land on each of his or her turns.\nAt the beginning of each player's upkeep, if that player has no cards in hand, that player draws three cards.

[
    new AtUpkeepTrigger() {
        @Override
        public MagicEvent executeTrigger(final MagicGame game, final MagicPermanent permanent, final MagicPlayer upkeepPlayer) {
            return upkeepPlayer.getHandSize() == 0 ?
                new MagicEvent(
                    permanent,
                    upkeepPlayer,   
                    this,
                    "If PN has no cards in hand, PN draws three cards."
                ):
                MagicEvent.NONE;
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            if (game.getTurnPlayer().getHandSize()==0) {
                final MagicPlayer player = event.getPlayer();
                game.doAction(new DrawAction(event.getPlayer(),3));                
            }
        }
    }
]

**Comment by melvinzhang** [comment]
A nice build around card. Improved the card script to handle the second ability without groovy code.

**Comment by kelsioboy** [comment]
:+1:
