### ISSUE TITLE
Grifter's Blade (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#932]
name=Grifter's Blade
image=http://magiccards.info/scans/en/rav/263.jpg
value=2.378
rarity=U
type=Artifact
subtype=Equipment
cost={3}
ability=Flash;\
        When SN enters the battlefield, attach SN to target creature you control.;\
        Equipped creature gets +1/+1.;\
        Equip {1}
timing=flash
oracle=Flash\nAs Grifter's Blade enters the battlefield, choose a creature you control it could be attached to. If you do, it enters the battlefield attached to that creature.\nEquipped creature gets +1/+1.\nEquip {1}

**Comment by melvinzhang** [comment]
Looks good. The ability should not target so it should work on creatures with shroud. I've rephrased it as `attach SN to a creature you control`
