### ISSUE TITLE
Workshop Assistant (New card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#933]
name=Workshop Assistant
image=http://media.wizards.com/2016/bVvMNuiu2i_KLD/en_R4aHIPqwSv.png
value=2.500
rarity=C
type=Artifact,Creature
subtype=Construct
cost={3}
pt=1/2
timing=main
requires_groovy_code=Junk Diver
oracle=When Workshop Assistant dies, return another target artifact card from your graveyard to your hand.

**Comment by melvinzhang** [comment]
Nice find and reusing the existing groovy code.
