### ISSUE TITLE
Custom scrollbar

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#935]
2d5983fb1eb788c55bce4640b9ff1f9485524417
Finally managed to come up with a working custom scrollbar. I think it would be nice if Magarena had its very own consistent look & feel (laf) so this is one step towards that goal. This requires very minimal code change since it changes a laf property which then applies to the default JScrollBar. However, the potential drawback is that how a laf is treated is very much OS dependent. I have tested on linux mint and windows 7 and it looks the same in both but mileage may vary on other OSes (cough, Mac). Consequently, although I would like it to default to the custom style there should be an option to switch it off in settings. You can do this now by setting ``customScrollBar`` to false in the configuration file manually but I intend to add a setting to themes tab in UI before next release.

Please let me know what you think, espeically if you have "issues" - it is very gray but I took my cue from the logo. Design and colors and stuff I find a frustrating timesink so feel free to play with the look - it is all done in ``magic.ui.widget.scrollbar.MScrollBarUI``.

**Comment by ShawnieBoy** [comment]
Appears to work fine on Win 10 too. 👍 
To my eyes the actual button-bit looks a bit pale against the background, but then, I don't really remember what the old version looked like, hehe.

**Comment by lodici** [comment]
Yes, I agree, sometimes it is difficult to pick out. I will have a look at making it a bit darker. TBH I was trying to get close to the scrollbar used in Linux Mint but come to think of it I have exactly the same problem with that one as well. lol.
