### ISSUE TITLE
Ignore value on scripts

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#94]
While doing a partial reparse of the scripts folder, I've found a couple of files with an 'Ignore' value.

Air Bladder and the 2/1 white Cleric enchantment creature token

What is this?

**Comment by melvinzhang** [comment]
They identify image files to ignore when checking for images to download.
They are added when a wrong image URL is fixed so that the downloader will
overwrite the wrong image.

**Comment by lodici** [comment]
...which is not used anymore. I believe ``CardProperty.IGNORE`` can be removed.

**Comment by melvinzhang** [comment]
I think old ignore properties on cards can be removed, assuming all users have ran the downloader once since the properties were added to the cards.

What's the replacement for the ignore property that will solve the "wrong image" not updated by downloader issue?

**Comment by lodici** [comment]
There is none at present.

**Comment by lodici** [comment]
Possible solution - add an optional ``imageUpdated`` script property which can be added to any script which has an updated image. Its value is the date (YYYY-MM-DD). The downloader will keep an entry in ``general.config`` that records the date it was last run. If on startup it discovers any scripts with a ``imageUpdated`` greater than that stored in ``general.config`` it will add the script image link to the download queue.

**Comment by ShawnieBoy** [comment]
Just to simplify things a bit:
What's wrong with the image for Air Bladder for example? The url link looks fine to me

**Comment by lodici** [comment]
Indeed and gven that you only found two scripts I not sure how essential it is. But...say you add new cards which as yet have no image available on _mtgimage.com_, so you use an alternative link in the script. If that link points to a high quality image then even if you later update the image link to point to _mtgimage.com_ it will not be downloaded. The only way is to remove the actual image to make it visible to the downloader.

**Comment by melvinzhang** [comment]
The previous image for Air Bladder is a html file, it was corrected in https://github.com/magarena/magarena/commit/0515100643bfdac173eaa8a5afbd9deb1bc5da50

**Comment by melvinzhang** [comment]
@lodici the image_updated property is a good idea, instead of YYYY-MM-DD, lets use the output of System.currentTimeMillis() to keep it as a simple long value. I'll remove ignore and add image_updated. Can you help to make the changes to the downloader?

**Comment by lodici** [comment]
Sure I will look at the downloader. But I am not sure about System.currentTimeMillis() from a user-friendly point of view. Wouldn't the property in most cases be updated manually so you would need to know how to represent the current date as a ``Long``!.

**Comment by melvinzhang** [comment]
Good point, will use the Date class then and YYYY-MM-DD format. Will also add an isAfter(Date d) method to check if a image needs to be updated. Returns true if imageUpdate is after than d.

**Comment by ShawnieBoy** [comment]
Would this value be needed to be added to the script builder or is this something that will be added to the script file once images have been downloaded?

**Comment by melvinzhang** [comment]
No, it would not have to be added to the script builder. The purpose is to cover up our mistakes without the user needed to do anything. If the scripts builder always generates the correct URL, the image_updated property is never used since there is no mistake to fix.

**Comment by ShawnieBoy** [comment]
I see - the scriptbuilder shouldn't be making any mistakes, unless they include a new card with an as-yet unused accent. But that would probably be checked before release.

Would it be easier to have a 'force overwrite' on the downloader instead? Or for it to have an option to force overwrite on a new install where an existing folder has been chosen?

**Comment by melvinzhang** [comment]
What would a downloader with 'force overwrite' do?

**Comment by ShawnieBoy** [comment]
Well, you're saying that if an image has been downloaded which is wrong, and has a higher resolution then it won't get replaced. Having an option to 'force overwrite' will do a fresh download of card images, overwriting any that already exist.

**Comment by lodici** [comment]
Well there is already a "force overwrite" option - it goes by the name of "delete images folder"! :smile:

**Comment by ShawnieBoy** [comment]
Hehe, very true - I just feel that this is becoming more complicated and labour-intensive than it should be.

**Comment by lodici** [comment]
Really the ``image_updated `` is just a safe-guard which will hardly ever need to be used. It will only apply to existing playable scripts so should not clash with the scripts builder. For example, say _mtgimage.com_ supplied a high-quality image link that turned out to be wrong - with this system we can simply open the script, update the link and add the ``image_updated`` property. The user is none the wiser.

**Comment by ShawnieBoy** [comment]
However, say mtgimage for some reason moved server, or changed the folder names or whatever, every card would have image_updated so would kinda defeat the purpose.

**Comment by melvinzhang** [comment]
if mtgimage moved server or change path, we update the image url but do not add a image_updated property, because the image didn't change just the URL to the image changed, there is no need for the user to download the same image again.

image_updated for the case when the actual image changed, usually because the URL is pointing to the wrong image initially.

**Comment by ShawnieBoy** [comment]
I think I understand now. It's for images that are wrong, not for images that need to be updated.

Just trying to think of another way of fixing the problem without adding information onto a scripts file.

**Comment by lodici** [comment]
We could always add an option to the Card Explorer that will force a re-download of cards displayed in the card list. Then you could update the images for just a set or format or whatever is the filter criteria.

**Comment by melvinzhang** [comment]
image_updated property released in 1.60
