### ISSUE TITLE
Arlinn, Embraced by the Moon ( Request for help to end the emblem.)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#941]
name=Arlinn, Embraced by the Moon
image=http://magiccards.info/scans/en/soi/243b.jpg
value=2.500
rarity=M
type=Planeswalker
subtype=Arlinn
color=rg
ability=+1: Creatures you control get +1/+1 and gain trample until end of turn.;\
        −1: SN deals 3 damage to target creature or player.~Transform SN.
transform=Arlinn Kord
timing=main
hidden
requires_groovy_code
oracle=+1: Creatures you control get +1/+1 and gain trample until end of turn.\n−1: Arlinn, Embraced by the Moon deals 3 damage to target creature or player. Transform Arlinn, Embraced by the Moon.\n−6: You get an emblem with "Creatures you control have haste and ‘{T}: This creature deals damage equal to its power to target creature or player.'"

[
    new MagicPlaneswalkerActivation(-6, "Ultimate") {
        @Override
        public MagicEvent getPermanentEvent(final MagicPermanent source,final MagicPayedCost payedCost) {
            return new MagicEvent(
                source,
                this,
                "PN gets an emblem with \"Creatures you control have haste.\""
            );
        }
        @Override
        public void executeEvent(final MagicGame outerGame, final MagicEvent outerEvent) {
            final long pId = outerEvent.getPlayer().getId();
            outerGame.doAction(new AddStaticAction(
                new MagicStatic(MagicLayer.Ability, ANY) {
                    @Override
                    public void modAbilityFlags(final MagicPermanent source,final MagicPermanent permanent,final Set<MagicAbility> flags) {
                        permanent.addAbility(MagicAbility.Haste, flags);
                    }
                    @Override
                    public boolean condition(final MagicGame game,final MagicPermanent source,final MagicPermanent target) {
                        return target.getController().getId() == pId && (                            
                            target.isCreature() 
                        );
                    }
                }
            ));
        }
    }
]

**Comment by kelsioboy** [comment]
Hello, everybody, I'm asking for help from you guys to finish the second part of the emblem of this card, I would be very happy if they could help me with this. For just need it to complete my werewolf deck.

**Comment by melvinzhang** [comment]
Looks good, just missing the tap ability. I added it in with the tap ability in the above commit.

**Comment by kelsioboy** [comment]
A thousand thanks Melvin Zhang for you have finished this card was really wonderful, my deck werewolf improved.
