### ISSUE TITLE
Unable to cast Aether Meltdown with untapped Island and Aether Hub

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#945]
Unable to cast Aether Meltdown. I had an untapped Island and Aether Hub, opponent had Island, Mountain and Eddytrail Hawk. Aether Meltdown was not highlighted, even though I should have been able to cast it on opponent's Eddytrail Hawk.

**Comment by ShawnieBoy** [comment]
Could be that there wasn't enough energy to produce mana?

**Comment by melvinzhang** [comment]
More likely to be a duplicate of #922 where the card can only enchant Creature AND Vehicle
