### ISSUE TITLE
Waxing Moon (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#949]
name=Waxing Moon
image=http://magiccards.info/scans/en/emn/177.jpg
image_updated=2016-09-05
value=2.500
rarity=C
type=Instant
cost={1}{G}
effect=Transform target Werewolf you control.~Creatures you control gain trample until end of turn.
timing=removal
oracle=Transform up to one target Werewolf you control. Creatures you control gain trample until end of turn.

**Comment by melvinzhang** [comment]
You should be able to cast this spell with no Werewolf to target for the trample effect. As implemented, there needs to be a target.
