### ISSUE TITLE
new keywords screen

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#950]
![screenshot from 2016-10-14 20 35 37](https://cloud.githubusercontent.com/assets/2443519/19401081/37929c46-9251-11e6-8743-9f515f3fe0dd.jpg)

It is still somewhat experimental but perfectly useable. Initially I had intended to replace the old one but on reflection decided not to. Instead you can switch back and forth between the two layouts and whatever is selected will be saved and restored. In fact I would say the new screen is better suited to running full-screen on bigger monitors whereas the old style works better with smaller screens.

The new screen can show example cards which have the selected ability. At the moment it cannot show images of missing cards but I hope to resolve that. Click on a image to view full size. This has also meant an update to the keywords file where the name of one or more cards can be specified. If more than one card is named then it will show one at random. Here is the start of `/keywords/English.txt` which shows the changes - I have added instructions at the beginning so it should be easy enough to understand.

```
# 
# Magarena keywords glossary.
#
# A blank like will be ignored.
# A line starting with...
# '#' will be ignored.
# '*' is the keyword definition.
# '@' is a list of card names (semi-colon delimiter) demonstrating the keyword.
# none of the above is assumed to be the keyword description.
#

*Absorb N
If a source would deal damage to this creature, prevent N of that damage.
@Lymph Sliver

*Affinity for [...]
This spell costs you {1} less to cast for each [...] you control.
@Frogmite;Razor Golem
```

I have started adding some cards but any help in filling out blanks would be much appreciated. Missing card names can be added but won't be shown as yet.

With regards to the keywords themselves. They are now presented as a list both visually and internally which means they can be navigated left, right, up and down using the arrow keys. You can also select as you go by holding down the left mouse button as you move the mouse cursor over the keywords. Finally, if you start to type the name of a keyword it will jump to the first match which is quite cool.

**Comment by melvinzhang** [comment]
Released and looking good. Any issues with it should be raised as separate issues.
