### ISSUE TITLE
Moonmist (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#951]
name=Moonmist
image=http://magiccards.info/scans/en/isd/195.jpg
value=3.880
rarity=C
type=Instant
cost={1}{G}
timing=removal
requires_groovy_code
oracle=Transform all Humans. Prevent all combat damage that would be dealt this turn by creatures other than Werewolves and Wolves.

def HUMAN_CREATURES = new MagicPermanentFilterImpl() {
    public boolean accept(final MagicSource source,final MagicPlayer player,final MagicPermanent target) {
        return target.hasSubType(MagicSubType.Human) && target.isCreature();

    }
};
def NONWEREWOLF_CREATURES = new MagicPermanentFilterImpl() {
    public boolean accept(final MagicSource source,final MagicPlayer player,final MagicPermanent target) {
        return !target.hasSubType(MagicSubType.Werewolf) && !target.hasSubType(MagicSubType.Wolf) && target.isCreature();

    }
};

[    new MagicSpellCardEvent() {
        @Override
        public MagicEvent getEvent(final MagicCardOnStack cardOnStack, final MagicPayedCost payedCost) {
            return new MagicEvent(
                cardOnStack,
                this,
               "Transform all Humans."+" Prevent all combat damage that would be dealt this turn by creatures other than Werewolves and Wolves."
            );
        }

        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            HUMAN_CREATURES.filter(event) each {
                game.doAction(new TransformAction(it
                    ));
            }
            NONWEREWOLF_CREATURES.filter(event) each {
                game.doAction(new AddTurnTriggerAction(
                    it,
                    PreventDamageTrigger.PreventCombatDamageDealtBy
                ));
            }
        }
    }
]

**Comment by melvinzhang** [comment]
We can make use of MagicRuleEventAction for transform and the prevent damage should be a different form that takes a filter so that it works for creatures that enter the battlefield after the spell resolves. Fixed version is on the way.

**Comment by kelsioboy** [comment]
:+1:
