### ISSUE TITLE
Winter Orb (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#953]
name=Winter Orb
image=http://mtgimage.com/card/winter%20orb.jpg
value=2.500
rarity=R
type=Artifact
cost={2}
ability=Lands don't untap during their controllers' untap steps, as long as SN is untapped.
timing=artifact
requires_groovy_code
oracle=As long as Winter Orb is untapped, players can't untap more than one land during their untap steps.

[
    new AtUpkeepTrigger() {
        @Override
        public MagicEvent executeTrigger(final MagicGame game, final MagicPermanent permanent, final MagicPlayer upkeepPlayer) {
            return new MagicEvent(
                permanent,
                upkeepPlayer,
                A_LAND_YOU_CONTROL,
                MagicTapTargetPicker.Untap,
                this,
                "PN untaps a land PN controls\$."
            );
        }
        @Override
        public void executeEvent(final MagicGame game,final MagicEvent event) {
            event.processTargetPermanent(game, {
                game.doAction(new UntapAction(it));
            });
        }
    }
]

**Comment by kelsioboy** [comment]
I changed the Oracle of this agreement with this card:

http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=159277

**Comment by ShawnieBoy** [comment]
If more than one Winter Orb is in play, only one land should be able to be untapped. #345
