### ISSUE TITLE
Smoke (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#954]
name=Smoke
image=http://magiccards.info/scans/en/5e/268.jpg
value=4.059
rarity=R
type=Enchantment
cost={R}{R}
ability=Creatures don't untap during their controllers' untap steps.
timing=enchantment
oracle=Players can't untap more than one creature during their untap steps.
requires_groovy_code=Stoic Angel

**Comment by ShawnieBoy** [comment]
Stoic Angel is implemented incorrectly - #345
