### ISSUE TITLE
Mungha Wurm (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#955]
name=Mungha Wurm
image=http://magiccards.info/scans/en/pr/119.jpg
value=2.639
rarity=R
type=Creature
subtype=Wurm
cost={2}{G}{G}
pt=6/5
ability=Lands you control don't untap during your untap steps.
timing=main
requires_groovy_code
oracle=You can't untap more than one land during your untap step.

[
    new AtYourUpkeepTrigger() {
        @Override
        public MagicEvent executeTrigger(final MagicGame game, final MagicPermanent permanent, final MagicPlayer upkeepPlayer) {
            return new MagicEvent(
                permanent,
                upkeepPlayer,
                A_LAND_YOU_CONTROL,
                MagicTapTargetPicker.Untap,
                this,
                "PN untaps a land PN controls\$."
            );
        }
        @Override
        public void executeEvent(final MagicGame game,final MagicEvent event) {
            event.processTargetPermanent(game, {
                game.doAction(new UntapAction(it));
            });
        }
    }
]

**Comment by melvinzhang** [comment]
See #345

**Comment by melvinzhang** [comment]
My bad for marking these cards as "needs groovy". They are not supported. Fixed in  91ea7611cbb8b948

**Comment by kelsioboy** [comment]
I had realized this and also found it strange, really I was going to ask about this case. Glad you guys already answered me. Thank you.
