### ISSUE TITLE
Protector of the Crown (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#958]
name=Protector of the Crown
image=http://magiccards.info/scans/en/cn2/21.jpg
image_updated=2016-09-05
value=2.500
rarity=R
type=Creature
subtype=Giant,Soldier
cost={5}{W}
pt=2/5
ability=When SN enters the battlefield, you become the monarch.
requires_groovy_code=Empyrial Archangel
timing=main
oracle=When Protector of the Crown enters the battlefield, you become the monarch.\nAll damage that would be dealt to you is dealt to Protector of the Crown instead.

**Comment by melvinzhang** [comment]
Looks good! Great find.
