### ISSUE TITLE
Alternative log message suggestion.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#96]
Some of the log messages seem excessively wordy...
![screenshot00060](https://cloud.githubusercontent.com/assets/2443519/6567364/0e48f71e-c6be-11e4-8584-290b15e147c8.png)
How about instead...
_Monty Carlo searches his or her library for a Mountain or Forest card and puts it onto the battlefield. Then Monty Carlo shuffles his or her library....etc_

Also, what about if we added a gender property to the player profile - ♂ (male) and ♀ (female) - so that you could also replace the clunky "his or her" phrase?
_Monty Carlo searches his library for a Mountain or Forest card and puts it onto the battlefield. Then he shuffles his library....etc_

Or even _gender unknown!_ = _it_

**Comment by ShawnieBoy** [comment]
I think this is more of a groovy issue - I know I sometimes got carried away with PN shortcuts. I've always disliked the 'he or she' as 'they' is still grammatically correct and gender neutral.

I think assigning gender could be a bit much - maybe a look through the groovy files for extreme use of PN could tidy this up, and keep to the card text.

**Comment by ShawnieBoy** [comment]
addressed in #503
