### ISSUE TITLE
`Grand Abolisher` won't let the opponent cast anything at all.

### ISSUE THREAD

**Issue by itandetnik** [magarena/magarena#962]
Once the opponent has `Grand Abolisher`, I can't do anything at all - not even play a land during my turn. 

`Grand Abolisher` is supposed to only prevent casting during its controller's turn - looks like there might be a bug in its script that makes this effect active at all times.

Gameplay report attached.
[gameplay-report.zip](https://github.com/magarena/magarena/files/559958/gameplay-report.zip)

**Comment by ShawnieBoy** [comment]
Confirmed - Strange it's no longer working. I know that permanents no longer use the game layer - could this be related to the Morph bug @melvinzhang

**Comment by ShawnieBoy** [comment]
Would most likelt affect [Dragonlord Dromoka](http://magiccards.info/dtk/en/217.html) and [Basandra, Battle Seraph](http://magiccards.info/vma/en/244.html) with similar groovy.

**Comment by melvinzhang** [comment]
These effects are put in player state at layer Player, I don't see the connection with Morph.

**Comment by melvinzhang** [comment]
This is caused by the MagicPlayerState revamp in 88de23c2195f698a85

**Comment by melvinzhang** [comment]
Correction, what happens is that it gets cleaned up, then set again due to the call to game.update after CleanupPlayerAction.
