### ISSUE TITLE
Status comments

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#966]
Is there an unobtrusive way to include comments with the status of unimplemented card scripts?

Looking through cards I came across [Open the Vaults](http://magiccards.info/c15/en/77.html), and although it could be done with groovy, the main issue with it is the returning of auras (Which are declared in turn order what they will enchant, and then enter the battlefield at the same time as everything else, but can't enchant something which is also entering the battlefield from the graveyard)

Having something (short?!) to add to this could help with finding cards and issues with implementation. Same with [Waxing Moon](http://magiccards.info/emn/en/177.html) which has a tendency to keep popping up.

**Comment by melvinzhang** [comment]
You can add comments on lines starting with '#'. These will be skipped when the property file is loaded.

**Comment by ShawnieBoy** [comment]
Ahh yes, forgot about that - I'll try to remember them when next finding 'sticking points' in implementing new cards - and maybe even as notes on cards which are included, but not completely accurate eg. [Varolz,  the Scar-Striped](http://magiccards.info/dgm/en/112.html) and [Stoic Angel](http://magiccards.info/ala/en/199.html)
