### ISSUE TITLE
Catastrophe (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#969]
name=Catastrophe
image=http://magiccards.info/scans/en/br/12.jpg
value=4.222
rarity=R
type=Sorcery
cost={4}{W}{W}
effect=Choose one — \
        (1) Destroy all creatures. They can't be regenerated. \
        (2) Destroy all lands.
timing=main
oracle=Destroy all lands or all creatures. Creatures destroyed this way can't be regenerated.

**Comment by ShawnieBoy** [comment]
A land that is also a creature won't be able to regenerate if option (2) is chosen

**Comment by kelsioboy** [comment]
That I had not thought, thanks for the tip.

**Comment by kelsioboy** [comment]
If you reverse the options would work?

**Comment by melvinzhang** [comment]
No, it would not work, because the "Creatures destroyed this way can't be regenerated." needs to be applied in both cases. This also has the modal copying problem from earlier, i.e. if I copy this spell, I should be able to decide lands or creatures when the spell resolves.
