### ISSUE TITLE
Return to the Earth (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#971]
name=Return to the Earth
image=http://magiccards.info/scans/en/frf/135.jpg
value=2.500
rarity=C
type=Instant
cost={3}{G}
effect=Choose one — \
        (1) Destroy target artifact. \
        (2) Destroy target enchantment. \
        (3) Destroy target creature with flying.
timing=removal
oracle=Destroy target artifact, enchantment, or creature with flying.

**Comment by ShawnieBoy** [comment]
Copying a modal spell doesn't allow you to change the mode - If this is copied, you should be able to target a different type.

**Comment by kelsioboy** [comment]
Ok.

**Comment by kelsioboy** [comment]
For me, you can close this.
