### ISSUE TITLE
Song of Serenity (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#972]
name=Song of Serenity
image=http://magiccards.info/scans/en/ex/125.jpg
value=3.640
rarity=U
type=Enchantment
cost={1}{G}
ability=Each creature that is enchanted can't attack or block.
timing=enchantment
oracle=Creatures that are enchanted can't attack or block.

**Comment by melvinzhang** [comment]
A wonderful find! Keep it up.
