### ISSUE TITLE
Stalking Yeti (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#973]
name=Stalking Yeti
image=http://magiccards.info/scans/en/cs/98.jpg
value=2.919
rarity=U
type=Snow,Creature
subtype=Yeti
cost={2}{R}{R}
pt=3/3
ability=Whenever SN enters the battlefield, SN fights target creature an opponent controls.;\
        {2}{S}: Return SN to its owner's hand. Activate this ability only any time you could cast a sorcery.
timing=main
oracle=When Stalking Yeti enters the battlefield, if it's on the battlefield, it deals damage equal to its power to target creature an opponent controls and that creature deals damage equal to its power to Stalking Yeti.\n{2}{S}: Return Stalking Yeti to its owner's hand. Activate this ability only any time you could cast a sorcery.

**Comment by ShawnieBoy** [comment]
Fight deals damage simultaneously. Stalking Yeti deals damage first - if it has infect it will receive less damage from the weakened creature. This would work better as a groovy file, as it also requires the Yeti to still be on the battlefield, not bounced back to hand to avoid damage.

**Comment by kelsioboy** [comment]
got it.

**Comment by kelsioboy** [comment]
Redid her and was so.

**Comment by kelsioboy** [comment]
name=Stalking Yeti
image=http://magiccards.info/scans/en/cs/98.jpg
value=2.919
rarity=U
type=Snow,Creature
subtype=Yeti
cost={2}{R}{R}
pt=3/3
ability={2}{S}: Return SN to its owner's hand. Activate this ability only any time you could cast a sorcery.
timing=main
oracle=When Stalking Yeti enters the battlefield, if it's on the battlefield, it deals damage equal to its power to target creature an opponent controls and that creature deals damage equal to its power to Stalking Yeti.\n{2}{S}: Return Stalking Yeti to its owner's hand. Activate this ability only any time you could cast a sorcery.
requires_groovy_code

[
    new EntersBattlefieldTrigger() {
        @Override
        public MagicEvent executeTrigger(final MagicGame game,final MagicPermanent source,final MagicPayedCost payedCost) {
            return new MagicEvent(
                source,
                TARGET_CREATURE_YOUR_OPPONENT_CONTROLS,
                new MagicDamageTargetPicker(source.getPower()),
                this,
                "SN deals damage equal to its power to target creature an opponent controls\$ " +
                "and that creature deals damage equal to its power to SN."
            );
        }

        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            event.processTargetPermanent(game, {
                game.doAction(new DealDamageAction(
                    event.getPermanent(),
                    it,
                    event.getPermanent().getPower()
                ));
                game.doAction(new DealDamageAction(
                    it,
                    event.getPermanent(),
                    it.getPower()
                ));
            });
        }
    }
]
