### ISSUE TITLE
Winds of Rath (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#974]
name=Winds of Rath
image=http://magiccards.info/scans/en/tp/264.jpg
value=2.500
rarity=R
type=Sorcery
cost={3}{W}{W}
effect=Destroy each creature that isn't enchanted. They can't be regenerated.
timing=main
oracle=Destroy all creatures that aren't enchanted. They can't be regenerated.

**Comment by melvinzhang** [comment]
Another cool find without groovy code. Nice work.
