### ISSUE TITLE
Toolcraft Exemplar( New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#977]
name=Toolcraft Exemplar
image=http://magiccards.info/scans/en/kld/32.jpg
image_updated=2016-10-05
value=2.500
rarity=R
type=Creature
subtype=Dwarf,Artificer
cost={W}
pt=1/1
ability=At the beginning of combat on your turn, if you control an artifact, SN gets +2/+1 until end of turn.~If you control three or more artifacts, SN gains first strike until end of turn.
timing=main
oracle=At the beginning of combat on your turn, if you control an artifact, Toolcraft Exemplar gets +2/+1 until end of turn. If you control three or more artifacts, it also gains first strike until end of turn.

**Comment by melvinzhang** [comment]
Good find, the rewording works perfectly.
