### ISSUE TITLE
Ohran Viper (Not Destroying creature at end of combat step, after the damage it be given)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#978]

**Comment by melvinzhang** [comment]
Unable to replicate in 1.79. Creature destroyed at end of combat as expected.

For game play bugs, please include a gameplay report zip file. You can create a gameplay report by opening the options menu (press Esc during a duel) and selecting the "Gameplay Report" menu item.

**Comment by kelsioboy** [comment]
Magarena 1.89 problem returned

**Comment by melvinzhang** [comment]
kelsioboy commented:
Magarena 1.89 problem returned. They are all cards that have "deals damage to a creature, destroy that creature to end of combat." no matter if the damage is combat or not. The cards for "blocks or becomes blocked by, destroy that creature at end of combat" are working normal.

**Comment by melvinzhang** [comment]
@kelsioboy please include a gameplay report zip file. You can create a gameplay report by opening the options menu (press Esc during a duel) and selecting the "Gameplay Report" menu item.

**Comment by melvinzhang** [comment]
I'm able to replicate this bug. We are missing a player priority after combat damage for the trigger to be put on the stack.
