### ISSUE TITLE
Saskia the Unyielding (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#979]
name=Saskia the Unyielding
image=http://media.wizards.com/2016/bn8f9t2zc_C16/4WABqQpTjv_EN.png
value=2.500
rarity=M
type=Legendary,Creature
subtype=Human,Soldier
cost={B}{R}{G}{W}
pt=3/4
ability=Vigilance, haste;     
timing=main
oracle=Vigilance, haste\nAs Saskia the Unyielding enters the battlefield, choose a player.\nWhenever a creature you control deals combat damage to a player, it deals that much damage to the chosen player.
requires_groovy_code

[
    new IfDamageWouldBeDealtTrigger(MagicTrigger.INCREASE_DAMAGE) {
        @Override
        public MagicEvent executeTrigger(final MagicGame game,final MagicPermanent permanent,final MagicDamage damage) {
            final MagicSource source = damage.getSource();
            if (permanent.isFriend(source) && source.isCreaturePermanent() && damage.isCombat() && damage.isTargetPlayer()) {
                // Generates no event or action.
                damage.setAmount(damage.getAmount() * 2);
            }
            return MagicEvent.NONE;
        }
    }
]

**Comment by kelsioboy** [comment]
As in Macarena only has two players, I think the effect of this card, you can be that way.
For the player chosen in this case is always the opponent's controller "Saskia the Unyielding."

**Comment by ShawnieBoy** [comment]
The second amount of damage isn't combat damage - it's also two separate 'packages' of damage.
It's always best to try and give the player full choices available even though it's only a two-player game, it's target player, not opponent, so you could target yourself with it (I can't think of a reason off the top of my head, but it's always good to keep an option) - The AI would obviously need a NEG_TARGET_PLAYER option for it though.
Black Vise has a 'chosen opponent' to use as a template.

**Comment by kelsioboy** [comment]
I tried to do it again by following what you said, I could not, I found it difficult for me.

**Comment by ShawnieBoy** [comment]
Ahh yes - the problem is that scripts are unable to 'choose a player', only 'choose an opponent'. The rest of the code would look something like this:
```java
[
    new DamageIsDealtTrigger() {
        @Override
        public MagicEvent executeTrigger(final MagicGame game,final MagicPermanent permanent,final MagicDamage damage) {
            return damage.isTargetPlayer() && 
            damage.isCombat() &&
            damage.getSource().isFriend(permanent) &&
            damage.getSource().hasType(MagicType.Creature) ?
                new MagicEvent(
                    damage.getSource(),
                    permanent.getChosenPlayer(),
                    damage.getDealtAmount(),
                    this,
                    "SN deals RN damage to PN."
                ):
                MagicEvent.NONE;
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            game.doAction(new DealDamageAction(event.getSource(), event.getPlayer(), event.getRefInt()));
        }
    }
]

**Comment by ShawnieBoy** [comment]
I've included choosing a player to script abilities
