### ISSUE TITLE
If you play Snapcaster Mage and have and alternate cost card in GY you cannot use alternate cost e.g. Gush, Daze

### ISSUE THREAD

**Issue by Muppet1** [magarena/magarena#98]

**Comment by melvinzhang** [comment]
Snapcaster Mage grants the card flashback with cost equal to its mana cost. So we are already casting using an alternative cost, the flashback cost. Only one alternative cost may be used. I've improved the description for Snapcaster Mage to clarify that we are paying the flashback cost. Reference: http://gatherer.wizards.com/Pages/Card/Details.aspx?name=snapcaster+mage

**Comment by Muppet1** [comment]
ahh yes sorry you are right its quite confusing because it does work with phrexian mana which works correctly in magearena too. 

     On Thursday, 12 March 2015, 12:14, Melvin Zhang <notifications@github.com> wrote:
   

 Closed #98.—
