### ISSUE TITLE
Planar Void (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#980]
name=Planar Void
image=http://magiccards.info/scans/en/us/149.jpg
value=4.173
rarity=U
type=Enchantment
cost={B}
timing=enchantment
oracle=Whenever another card is put into a graveyard from anywhere, exile that card.
requires_groovy_code

[
    new WouldBeMovedTrigger(MagicTrigger.REPLACEMENT) {
        @Override
        public MagicEvent executeTrigger(final MagicGame game, final MagicPermanent permanent, final MoveCardAction act) {
            if (act.card && 
                act.to(MagicLocationType.Graveyard)) {
                act.setToLocation(MagicLocationType.Exile);
            }
            return MagicEvent.NONE;
        }
    }
]

**Comment by ShawnieBoy** [comment]
This isn't a replacement effect - The card does reach the graveyard, it then gets exiled from the graveyard. It doesn't use the words 'if'...'instead'

**Comment by kelsioboy** [comment]
[
    new OtherPutIntoGraveyardTrigger() {
        @Override
        public MagicEvent executeTrigger(final MagicGame game, final MagicPermanent permanent, final MoveCardAction act) {
            final MagicCard card = act.card;
            return (card.getOwner()) ?
                new MagicEvent(
                    act.card,
                    this,
                    "Exile SN."
                ) :
                MagicEvent.NONE;
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            game.doAction(new ShiftCardAction(event.getCard(),MagicLocationType.Graveyard,MagicLocationType.Exile));
        }
    }
]

**Comment by kelsioboy** [comment]
New groovy.
