### ISSUE TITLE
Gahiji, Honored One (New card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#984]
name=Gahiji, Honored One
image=http://magiccards.info/scans/en/c13/191.jpg
value=3.768
rarity=M
type=Legendary,Creature
subtype=Beast
cost={2}{R}{G}{W}
pt=4/4
ability=Whenever a creature you control attacks, that creature gets +2/+0 until end of turn.
timing=main
oracle=Whenever a creature attacks one of your opponents or a planeswalker an opponent controls, that creature gets +2/+0 until end of turn.

**Comment by melvinzhang** [comment]
Nice way to rephrase the ability.
