### ISSUE TITLE
Creature doesn't die when its toughness goes to 0

### ISSUE THREAD

**Issue by itandetnik** [magarena/magarena#986]
It's opponent's M2. The computer has `Myr Enforcer` with `Cranial Plating` attached, 11/4 (P/T). I play `Grasp of Darkness` on it. I can see its P/T go to 7/0 for a brief moment, while the phase indicator moves to ET then CU, at which point its P/T reverts to 11/4 and it remains in play.

I can't catch the game report in the exact moment this happens, so I'm attaching one from right before and another from right after. Maybe that'll help.

Before: [gameplay-report-before.zip](https://github.com/magarena/magarena/files/574220/gameplay-report-before.zip)

After: [gameplay-report-after.zip](https://github.com/magarena/magarena/files/574221/gameplay-report-after.zip)

**Comment by itandetnik** [comment]
In another game (with the same pair of decks), I got the situation where a creature is alive with 0/0 during the time where I can grab the game report: 

[gameplay-report.zip](https://github.com/magarena/magarena/files/574242/gameplay-report.zip)

In this game, `Myr Enforcer` was finally put into graveyard during DA step, after I've assigned attackers and the computer got the priority.

**Comment by itandetnik** [comment]
Another game report, with a creature looking alive while having P/T of 8/-2:

[gameplay-report.zip](https://github.com/magarena/magarena/files/574251/gameplay-report.zip)

**Comment by melvinzhang** [comment]
Thanks for including the gameplay reports. I'm able to replicate this issue.
