### ISSUE TITLE
Murk Dwellers (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#987]
name=Murk Dwellers
image=http://magiccards.info/scans/en/5e/42.jpg
value=1.654
rarity=C
type=Creature
subtype=Zombie
cost={3}{B}
pt=2/2
ability=Whenever SN attacks and isn't blocked, it gets +2/+0 until end of turn.
timing=main
oracle=Whenever Murk Dwellers attacks and isn't blocked, it gets +2/+0 until end of combat.

**Comment by kelsioboy** [comment]
The effect I used card text.

http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=3863

**Comment by melvinzhang** [comment]
Should be "until end of combat" not "until end of turn".
