### ISSUE TITLE
Player may choose to sacrifice no creatures to Mogis, God of Slaughter evading damage

### ISSUE THREAD

**Issue by WormFrizzer** [magarena/magarena#99]
At the beginning of each opponent's upkeep, Mogis, God of Slaughter deals 2 damage to that player unless he or she sacrifices a creature.

**Comment by melvinzhang** [comment]
I'm unable to replicate this. When no is chosen, Mogis deals 2 damage to the player. Perhaps some of the other cards on the board is interacting with damage being dealt.

**Comment by ShawnieBoy** [comment]
Could it be a situation where you have no creatures, but choose yes?

**Comment by ShawnieBoy** [comment]
was fixed with 26bdbe22325c942cf650a90a33a4cf0ca16c7acb
