### ISSUE TITLE
rename Target in MagicTarget, MagicTargetChoice, MagicTargetFilter to a different word to reduce confusion

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#990]
The Target in MagicTarget is NOT the same as "target" in "target player". MagicTargetChoice can be targetted or not.

One suggestion is to rename Target to Selection. Giving us MagicSelection, MagicSelectionChoice, and MagicSelectionFilter.

**Comment by melvinzhang** [comment]
Another suggestion is Chosen, eg MagicChosen, MagicChosenChoice, MagicChosenFilter. 

@ShawnieBoy any thoughts on this?

**Comment by ShawnieBoy** [comment]
My confusion was in MagicEvent - I assumed MagicEvent.processTarget<Type> was re-checking the legality of the target for resolution e.g. Destroy target creature - is it still a creature?

Also within MagicEvent there's the getChosenCard, getChosenPermanent which I thought would then be extended to getChosenPlayer in the same trend.

**Comment by melvinzhang** [comment]
It is the same issue, processTarget means process MagicTarget, perhaps should be process processChosen instead to avoid confusion.

**Comment by ShawnieBoy** [comment]
Well, where is the extra check performed? I'm not sure if changing the names would help - just knowing when and where the two target checks are made would be clearer.

**Comment by melvinzhang** [comment]
The checking is in MagicGame.isLegalTarget, note the use of isTargeted to distinguish between "target something" and "a something".
