### ISSUE TITLE
Have 3 `Swamp`s, can't play `Stillmoon Cavalier`

### ISSUE THREAD

**Issue by itandetnik** [magarena/magarena#992]
I have 3 `Swamp`s in play, and `Stillmoon Cavalier` in hand (cost: 1{W/B}{W/B}). It's my M1. `Stillmoon Cavalier` is not highlighted and cannot be played.

Gameplay report:
[gameplay-report.zip](https://github.com/magarena/magarena/files/592261/gameplay-report.zip)

**Comment by itandetnik** [comment]
Turns out, `Stillmoon Cavalier` can be played once I have 5 `Swamp`s. Looks like the cost is specified incorrectly somewhere.

**Comment by itandetnik** [comment]
But curiously, even though it requires 5 `Swamp`s before it can be played, it actually only costs 3 to play.

**Comment by ShawnieBoy** [comment]
I have a feeling that the {W/B} is being recognised as {2/B} instead - colorless hybrid instead of dual hybrid

**Comment by melvinzhang** [comment]
Unable to replicate, in the snapshot game from the gameplay-report zip, Stillmoon Cavalier is playable and highlighted.
